### ISSUE TITLE
Processing team queue

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1000]
* As an IAO analyst 
* I want to see per request the number of extensions and the number of pages for review
* so that I can manage my daily work

**Assumptions & Scope**	
What are the assumptions for this story?

The processing team will need a custom queue. If number of extensions and number of pages for review are shown on the queue, the analyst will not need to run daily reports to decide how to manage his or her work.

Filters will function the same in this queue as with other queues (My Team's Requests, My Requests, Watching Requests).

What is IN scope?
Queue for IAO processing analysts.

What is NOT in scope?
Assignment to processing analysts.
Number of pages, while showing as a column, will not have information to be pulled at this time. There may be a dependence with AXIS ETL for this field. Similar for XGOV as well. 

**Acceptance Criteria**	

Scenario 1: Data in each row for a request
* GIVEN an IAO analyst from a processing team has logged in successfully
* WHEN the IAO analyst is on the queue
* THEN for each request assigned, the analyst will see, from left to right: Request ID, applicant name, applicant category, request type, current state, days left, number of extensions, number of pages, and XGOV

Scenario 2: Order of requests in queue
* GIVEN a FOI analyst on a processing team has logged in successfully.
* WHEN the analyst is on the queue
* THEN the requests will be sorted with the requests sorted by legislated due date, from oldest to newest.

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/846624085

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
AC updated - I used our Ministry coordinator queue story as a template, and transposed it over with the relevant details and ordering (assuming FOI analysts will want to see requests in order of LDD, oldest to newest.

@lmullane @arielleandrews @JHarrietha-AOT @mpilchar

**Comment by JHarrietha-AOT** [comment]
@jadmsaadaot I am pushing this back to in progress. We are missing the titles of the coloumns don't match the designs and the spacing doesn't match the designs which is creating weird spots where content it to tight or has to much room. 

Days Left, Ext, Pages and XGOV should all have much small columns widths which will give more space to the columns on the left that need it.

Let me know what were looking at time wise. @m-prodan @arielleandrews should we test as is or wait, if we wait we will likely have little to show for demo tomorrow as I don't see #1213 getting through test before demo

**Comment by jadmsaadaot** [comment]
As for the spacing issue:

It is difficult to assign a static pixel width since it would be designing
to one screen size. I used a dynamic option where the column width is
decided on run time. And the mentioned columns on the right are half the
width of the columns on the left right?

As for the column names, I will recheck which columns did not match the
design but I also tried to match column names that already exist in the
system like the ones in the ministry dashboard for consistency reasons. I
would ask that a decision be made on this based on whether the remaining
mismatches are considered blockers or not. If not, we can address them in a
separate task

**Comment by JHarrietha-AOT** [comment]
@divyav-aot Would you have any inights for the spacing issue? Just curious is this is a bigger issue in itself

**Comment by JHarrietha-AOT** [comment]
@jadmsaadaot Perfect! Thanks for that. Just wondering if it would be better to make a separate ticket for fixing/adjusting spacing of columns in all queues? I haven't flagged it previously but it is very noticeable here and just wondering what the best approach it technically. @divyav-aot feel free to weigh in on thoughts here

**Comment by jadmsaadaot** [comment]
@JHarrietha-AOT I would definitely suggest we go that way, to address this in a separate ticket. I'll just expound a bit on the column width, so for a column we can specify by two ways, either a fixed column width or like a ratio where 1 is equivalent to width of table divided by number of columns. With that known, we can discuss now or later what ratios to specify for the columns and which would have a specific width

**Comment by JHarrietha-AOT** [comment]
@jadmsaadaot completely understand and I think this might require some screen sharing and adjusting to figure out the best wifth. I'll more to QA. 

@m-prodan just flagging for you above, spacing is off for column width @jadmsaadaot suggestion is moving to a separate ticket and it will likely take some time for me to sit with him and figure out the best ratios. And I think it is something we should adjust on all queues

**Comment by m-prodan** [comment]
From what I can see on the processing team queue, it looks OK. It is picking up extensions, and updating the number as they are added. Some issues I found while testing: 

1) JERI requests do not appear in the team queue at all when they are assigned to the Ministry team (I tried logging in as all test JERI users, and no requests were populating). This may be able to be addressed via keycloak, but I am unsure if this will impacts our Ministry users.
 
2) Can not manually assign requests to a specific teams the team level (I am unable to assign requests to "Social Tech Team" or "Business Team" - for example, assigning a general request from flex user to the processing team I have to assign to a specific user) - encountered this when I was trying to see how generals were behaving vs personals
 
3) Requests assigned to users, with some exceptions, are not appearing under "My Requests" when the filter is activated. Ministry users and Intake users appear to be the exception, though intake users no longer see requests even if they are assigned, if they are passed the “Intake in Progress” stage. Processing team and flex team are unable to filter to their own requests, the watched requests filter does work though.

I will move this back to review - we can chat more at stand up tomorrow

**Comment by m-prodan** [comment]
Actually - we may need to do some more thorough testing to try and uncover all potential issues - I will pin this for tomorrow. It is late :)

**Comment by jadmsaadaot** [comment]
@Prodan, Matthew CITZ:EX ***@***.***>  Thank you.

Read through and understood the issues here, but are they within the scope
of this particular task namely the ACs above? I understand this task is to
display specified columns and to define a default for the processing team
dashboard.

We could create another task with ACs to address the following issues as
they require changes for the filters we have in place to pull the requests
and not in the specific fields pulled and how to display them. Does this
logic seem off?

**Comment by m-prodan** [comment]
Closing Ticket - processing team queue works as expected. Issues raised above have been fixed or will be fixed with existing bug tickets - but AC is largely met. Many issues are related to permissions of view for specific users/groups and will be addressed in #1609
