### ISSUE TITLE
Backend  Model. Service updates/additions, - Tagging users(US#787)

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#1001]
Title of ticket: 

#### Description
The purpose of this task is to capture the tagged users on comments specific to a request to the DB. An additional Service will be written on the existing Python Flask API side. DB Model will get updated to store tagged users

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] DB Model Update for Tagged Users - Comments table?? or a different bridged table
- [ ]  Service to Parse Tagged users(@anntony, @mpilchar ) from the comment and store to DB
- [ ]  API Updates, if any
- [ ]  Unit tests
- [ ]

**Comment by molly** [comment]
Wrong Molly, I think 🙂

**Comment by abin-aot** [comment]
> Wrong Molly, I think 🙂

Sorry about that. Also, thanks for highlighting :)
