### ISSUE TITLE
UX Design Update - Visual Indicator for Comments & Attachments

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1005]
Title of ticket: UX Design Update - Visual Indicator for Comments & Attachments

#### Description
Design a new visual indicator for the attachments to show which stage it was uploaded.
Design for comments to have a visual indicator for users, and for the Request History Comments

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Design update for attachments
- [x] Design update for comments

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews @lmullane @mpilchar 

Just wanted to share out the proposed designs for the badges for Attachments and Comments.

Attachments: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
My plan with colours if that the badge takes on the colour of the stage that is affected by the uploaded document for the stages, and anything in general is the standard blue we are using across the system.

Comments: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/827609369
For MVP I have used a 60% opacity of a randomly selected colour that we use in the system, with the initials of the users first and last name. This provides quick visual indicator and post MVP we could look at adding profile settings so users could change the colour or upload an image if they want to.

Please share any thoughts for ideas when you have a chance.

**Comment by arielleandrews** [comment]
Designs were updated and related User Stories have been drafted
