### ISSUE TITLE
Prototype Update - Processing Team Queue

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1011]
Title of ticket: Prototype Update - Processing Team Queue

#### Description
Prototype Update - Processing Team Queue

#### DOD
- [x] Update UI for Processing Team Queue based on Sessions and Jamies Feedback
- [x] Have SME & PO review
- [ ] Circle back with Jamie for feedback

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews Could you have a look at this updated design when you have a chance and let me know if you have any changes: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/846624085

**Comment by m-prodan** [comment]
Looks great to me - I'll get started on the AC. Number of pages may be dependent on AXIS ETL, so I will mention in the AC that it should read as N/A for now. We could also look at adding a field for IAO to manually enter the info into the review request page if there's an issue with pulling that number from AXIS

**Comment by JHarrietha-AOT** [comment]
Good catch @m-prodan I don't think we have that built into the system yet, we should add a ticket for how this will be flagged. 

We will also have to circle back to the creating multiple requests at once in intact which would be a flagged for XGOV along with request coming into the system with multiple ministries selected

**Comment by arielleandrews** [comment]
Late to the party but noting for teams heavy on personal requests, we may hear a want to see the "on behalf of" field displayed. An example is some lawyers/law firms will submit requests on behalf of multiple clients. In that case the applicant name would display as the lawyer's name and you would not have an easy way to differentiate the requests in your queue aside from the ID number

**Comment by m-prodan** [comment]
Good one to flag... I wonder if we can do something similar to what we were thinking for request description, for example: when an analyst hovers over a law firm/OBO app name, it shows the OBO name in a little pop up over the mouse pointer.

Alternatively we could just set up a different queue for personals heavy teams (Social Tech, Justice Health, and CFD)

**Comment by JHarrietha-AOT** [comment]
@arielleandrews good one to flag, do we think we would want to just replace the request type column with on behalf of? (for personal focused teams) Or add it?

**Comment by arielleandrews** [comment]
@JHarrietha-AOT I would say add that column. The Social Tech and Justice Health teams both have a pretty even split of generals vs personals so they may still find the request type column beneficial. CFD Personals is the only team that wouldn't need it since all their requests are personal

**Comment by JHarrietha-AOT** [comment]
Sounds good, I'll add. Thanks Arielle. Will share a link her shortly with the update

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Updated: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/846624085

**Comment by JHarrietha-AOT** [comment]
@arielleandrews  Thanks for reviewing, I have updated columns accordingly https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/846624085
