### ISSUE TITLE
Recruitment for Reporting Personas

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1013]
Title of ticket: Recruitment for Reporting Personas

#### Description
Recruitment for Reporting Personas

#### Dependencies
Completion of #1012

#### DOD
- [ ] General vs Personal
- [ ] Team leads - responsible for a good cross section of reporting
- [ ] Meghan Kane (CFD)
- [ ] IAO - Tara Heinrich
- [ ] IAO - Jonelle Weinrich
- [x] Susan Shust + Darlene and Vicki
- [x] Jackie Biggs
- [ ] Justine Nisbet
- [x] Alexandra Kavadas / Hayley
- [x] EDUC pilot
- [x] ECON pilot

**Comment by mpilchar** [comment]
@arielleandrews and I have discussed setting up the research sessions to have an analyst and manager both. This would cover off the follow up we suggested during the working group meeting, and bring in both perspectives in terms of reporting. cc @JHarrietha-AOT @m-prodan

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Recruitment will be Ministry focused - 4 sessions with working groups members and their coordinators and 2 additional sessions with Pilot Ministries and their coordinators

**Comment by m-prodan** [comment]
Will need to send invites out this week for the new year - I will update this comment as I hear more responses:
EDUC - Carrie has confirmed she will be available for first 2 weeks of Jan
ECONO - David confirmed at last pilot meeting, him, Vicki (and Danny) would likely be available for a session first two weeks of Jan
Haley Ronda and Alexandra Kavadas (ENV): Confirmed will be in office first 2 weeks of Jan - will commit to making time for a session


To reach out to still:
HLTH (Susan and Darlene)
CITZ (Jackie Biggs)
PSSG (Justine Nisbet)
Jonelle and Meghan Kane (TL/Manager, IAO CFD Personals)
Tara Heinrich (TL, IAO Social Tech)


Not Available First 2 Weeks Jan:
FIN (Melissa Morgan) - Advised late January preferable

**Comment by m-prodan** [comment]
@arielleandrews - for when you are back tomorrow... but what about Kelly Mackinnon from CFD? Thinking it would be good to have them as part of this research.

**Comment by arielleandrews** [comment]
Kelly would be great to include! She did indicate she uses the dashboards very regularly

**Comment by m-prodan** [comment]
I'll reach out to her today. While it's fresh on my mind, just thinking about the IAO sessions - do we want to chat with Jackie about those first? I suspect she's tailored her interviews for Ministry clients and may want some time to prepare different questions for those groups.

**Comment by arielleandrews** [comment]
Jackie hasn't started on a research plan or study guide for these sessions yet (it's something we can take a run at if we have time) so it's very open at this time. She did request we schedule sessions starting the week of Jan 10 so there's a buffer for her to get caught up

**Comment by m-prodan** [comment]
Invites have been sent to those that confirmed interest. I know Jackie wanted 4 WG members, still waiting to hear back from Kelly, but we could pivot to Justine from PSS if Kelly isn't available. I will follow up with Kelly this week.

**Comment by JHarrietha-AOT** [comment]
All sessions booked for Jan 10th - 15th
