### ISSUE TITLE
FE changes to reopen a request (#832)

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#1024]
Title of ticket: 

#### Description
FE changes to reopen a request

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Populate state drop down
- [x] Show Close requests in dashboard
- [x] Update Unit tests if any
- [ ] Integration testing
- [x] Functionality of state change
- [x] Review Comments

**Comment by JHarrietha-AOT** [comment]
@divyav-aot Here is a link to the updated design for the modal, we removed the complexities after talking to Matt and Arielle. 

https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/843963404

With the goal being that when a request is in closed the only option in the left nav will be the previous state the request was in. Then this modal will appear with the relevant Request #, State Name and Remaining Days, Let me know if you have any questions
