### ISSUE TITLE
Set up shared email for user feedback

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1027]
#### Description
Create a shared common email for IAO and Ministry users to submit feedback 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Determine name and address for email
- [x] Submit iStore order for email to be created and add access for Loren, Molly, Matt, Arielle, Jackie, Abin, others?
- [ ] Have all users add shared email account
- [ ] Promote feedback email at demo and with working group
- [ ]

**Comment by arielleandrews** [comment]
@lmullane @mpilchar @m-prodan @JHarrietha-AOT I suggest the address FOI.Modernization@gov.bc.ca and naming it FOI Modernization Feedback. Thoughts? Other suggestions?

**Comment by lmullane** [comment]
Good idea, @arielleandrews.

**Comment by m-prodan** [comment]
I've submitted the order - recommended users with access to be myself, Loren, Molly, Arielle and Jackie

**Comment by m-prodan** [comment]
Update - mailbox is complete, but there were IDIR access issues. Update was received yesterday that a new order was submitted to address it.

**Comment by m-prodan** [comment]
hey! It's actually done! (no one let me know it was done, I just tried adding it and it all finally works).

I will need to add @KaraBeach to this, and we can advertise the email at our next training session tomorrow and the MS Teams channel for visibility. I will close the ticket after I inform users and submit the ticket for Kara's access

**Comment by mpilchar** [comment]
confirming I have access
