### ISSUE TITLE
Revise modal text when closing out of a draft reply comment

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1029]
**Describe the bug in current situation**

When I am on the comments tab of a request details page, if I draft a reply (child comment) and click the 'x' without submitting the comment, a modal appears with title "test-foirequest.apps.silver.devops.gov.bc.ca.ca says" and message " Are you sure you want to leave? Your changes will be lost" and options "OK" or "Cancel.

This bug proposes revising the title of the modal to "Close Comment" and message to "Are you sure you want to close? Your changes will be lost"

This would be more consistent with the modal the user encounters if trying to leave the page

**Link bug to the User Story**
#785

**Impact of this bug**
Impact: User confusion

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Will occur with any user type, so long as user is on Comments tab

**Steps to Reproduce**
1. Go to Comments tab of any request
2. Click on "reply" to a comment
3. Type sample text
4. Click 'x' to leave
5. The described modal will appear

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/c9bea98c-9b8d-45f3-b38e-ac7d0199804d)

**Comment by abin-aot** [comment]
Need to discuss the feasibility or go for bigger customization

**Comment by mpilchar** [comment]
Determined during refinement that development effort not worth the bug fix. Closing this ticket
