### ISSUE TITLE
Analysis of ETL for AXIS

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1048]
Title of ticket: 

#### Description
This task addresses steps that would need to be taken in order to set up an ETL within the firewall to read and transfer data from AXIS into OpenShift

#### DOD
- [x] Meet with CITZ MISO to determine whether we can expose the AXIS db server IP (to DMZ, open shift). 
- [x] Confirm location of service account needed for ETL
- [x] TBD: Submit istore request for service account (or work with IMB to submit)

**Comment by mpilchar** [comment]
@lmullane @m-prodan @abin-aot Looks like CITZ MISO is away until the new year. His ooo message indicates us reaching out to the Privacy and Security general mailbox

**Comment by abin-aot** [comment]
[https://app.zenhub.com/files/358004325/4f465ec1-329f-4355-b35a-37ee591c31f3/download](https://app.zenhub.com/files/358004325/4f465ec1-329f-4355-b35a-37ee591c31f3/download)

**Comment by abin-aot** [comment]
[https://app.zenhub.com/files/358004325/b5b738fb-0635-43de-84d9-ab601becd040/download](https://app.zenhub.com/files/358004325/b5b738fb-0635-43de-84d9-ab601becd040/download)
@lmullane , @m-prodan , @ariannedee @mpilchar  : Myself and @VineetBala-AOT has analyzed the effort for ETL and here are tasks and effort. We are planning to start this next sprint onwards.
