### ISSUE TITLE
Assigned To shows User ID instead of full name on Ministry Dashboard

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#1073]
On ministry dashboard, "ASSIGNED TO" column should display full name if it is assigned to a ministry member. However, it is displaying user ID now.

**Comment by lmullane** [comment]
Full name is appearing.

**Comment by mpilchar** [comment]
Reopening due to issues on DEV/TEST and need to retest

**Comment by lmullane** [comment]
Re-tested and it's fixed.
