### ISSUE TITLE
UX Assurance - Request Details - Front End Fixes

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1076]
UX Assurance - Request Details - Front End Fixes

Series of front end changes to Request Details Page so that UX better aligns with original designs and provides a more consistent user experience with consistent margin and spacing.

- [ ]  Logo, buttons and icons along top nav bar should be aligned to overall white space width
- [x]  Remove "Option X" in Left Nev Bar
- [x]  Extend Left nav to fit full width of screen so it is responsive to users screen
- [x]  Equal spacing of right and left margin

Screenshot provided with notes to provide visual reference of changes

![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/03c3e203-12ea-4884-9b49-7830e97d3119)

**Comment by mpilchar** [comment]
![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/8b2244bc-99aa-4ff9-9ed6-236bdd891044)
Alignment of Sign out button doesn't match what is requested. @nkan-aot . Please let me know if this was an oversight or if it can be removed from A/C for this UX Assurance ticket

**Comment by nkan-aot** [comment]
Hey @mpilchar , thanks for catching this, issue is with some breakpoints in css. I will move back to in progress and fix

**Comment by JHarrietha-AOT** [comment]
@nkan-aot Looks great as always! Passes UX Assurance moving to closed
