### ISSUE TITLE
UX Assurance - Request Description - Front End Fixes

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1077]
UX Assurance - Request Description - Front End Fixes

Series of front end changes to Request Descriptions Page so that UX better aligns with original designs and provides a more consistent user experience with consistent margin and spacing.

- [x]  Issue with grey appearing instead of white below left nav
- [x]  Alignment! There is a huge variety of alignment and spacing in this window. (All window "Request Details, Address and Contact Info, Request Description" should have same margins) All items in box should be aligned
- [x]  Spacing between "Description History" and top of box should be decrease which will move all content up with it

Screenshot provided with notes to provide visual reference of changes

![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/149ee7ec-7390-474c-a057-79fcb0a4e68b)![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/57feb29e-6de0-49f6-8a21-c9ca3ef11965)

**Comment by mpilchar** [comment]
Checked this on Chrome and Edge, on different sized monitors, and in full screen and half screen modes - looks good!
