### ISSUE TITLE
UX Assurance -  Attachment Log - Front End Fixes

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1078]
UX Assurance -  Attachment Log - Front End Fixes

Series of front end changes to Attachment Log Page so that UX better aligns with original designs and provides a more consistent user experience with consistent margin and spacing.

- [x] Align Request # and +Add Attachment Button
- [x] Decrease spacing between Request # and first Attachment so more can be shown on page
- [x] Design update for Badge
- [x] Ellipses is not in correct blue

Screenshot provided with notes to provide visual reference of changes

![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/149ee7ec-7390-474c-a057-79fcb0a4e68b)![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/57feb29e-6de0-49f6-8a21-c9ca3ef11965)![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/bfc90372-0206-4f53-812c-83719481da5c)

**Comment by JHarrietha-AOT** [comment]
Ready for QA

**Comment by lmullane** [comment]
@JHarrietha-AOT, looking at the notes the expectation is the background behind the left nav bar is white, right?

On the Attachment Log and Comment page it is white, but on the Request page it is grey? The latter provides more contrast imo.

Either way it should be consistent across pages.

What would you like to do here?

<img width="560" alt="Screen Shot 2022-02-14 at 8 51 08 AM" src="https://user-images.githubusercontent.com/12040839/153909357-7253284f-fdba-41df-9882-f871b3f11b9f.png">

<img width="572" alt="Screen Shot 2022-02-14 at 8 51 30 AM" src="https://user-images.githubusercontent.com/12040839/153909393-2a00cdd4-ddb2-4663-93a1-848676a5c52f.png">

**Comment by JHarrietha-AOT** [comment]
@jadmsaadaot @divyav-aot What @lmullane flagged in the comment above with screenshots is something we have talked about fixing previously. Wondering if this is a bug/UX Assurance that should be in its own ticket so it can be estimated on its own and focused on fixing. Or if you would prefer for us to move this back to in progress. Let us know how you both would like to proceed.

**Comment by JHarrietha-AOT** [comment]
Double check complete! Great work @jadmsaadaot
