### ISSUE TITLE
istore order - more storage on PENGUIN

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1084]
Title of ticket: 

#### Description
PENGUIN VM - Increase storage to 200GB

#### Dependencies
File migration requires this

#### DOD
- [x] Determine if FOI team or IMB submits istore request
- [x] Provide info to IMB: Cost coding & EA, Drive label: D: or E:, Tier 2 or 3
- [ ] Confirm complete

**Comment by mpilchar** [comment]
David Smyth from IMB will submit, Alexander Punnett will stick handle

**Comment by mpilchar** [comment]
@lmullane @abin-aot Did this get submitted last week?

**Comment by lmullane** [comment]
I've provided the info to the IMB to submit the order.

**Comment by mpilchar** [comment]
closing - this is captured in IMB's jira board
