### ISSUE TITLE
Middle Name issue with applicant - Users with Same First and Last Names, but different Middle names

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#1087]
**Describe the bug in current situation**
When 2 applicant has same FIRSTNAME, MIDDLENAME , only 1 entry goes to Applicant info table and for the second applicant, middlename is getting replaced with first applicant. The issue is with back end applicant unique check function. Need to bring in email along with Middle Name confirm. 

**Link bug to the User Story**

**Impact of this bug**
Uniqueness of applicant is getting affected, data is getting stale. Major Issue.
**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. CREATE A REQUEST with JOHN W SMITH(First, middle, lastname) as applicant
2. CREATE ANOTHER REQUEST with JOHN BARRY SMITH(First, middle, lastname) as applicant
3. SAVE these 2 requests with updates on other fields - MIDDLE NAME will get interchanged between 2.

**Actual/ observed behaviour/ results**

**Expected behaviour**
JOHN W SMITH and JOHN BARRY SMITH  should be saved as 2 different users

**Screenshots/ Visual Reference/ Source**
CONTACT @abin-aot :) - can help to reproduce

**Comment by sumathi-thirumani-aot** [comment]
Unable to reproduce. The logic to reuse applicant info no more exists.
