### ISSUE TITLE
Data Load / Volume Test -: Queue Optimization - Dashboard + System under more volume of data

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#1088]
Title of ticket: 

#### Description
The purpose of this issue is to make the FOI Flow system under at least 1 - 2 years of data volume and under stand the break conditions and do required optimizations. One of the known candidate is the Dashboard queue.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Use Automation Testing Tool or JMeter to Load the system with 1000 - 3000 records. This is should be set up by set up process. 
- [x]  MAJOR DELIVARABLE -DO SERVER SIDE PAGINATION, SORTING and FILTERING
- [x]  If possible, make it work for 1000- 1500 records.  Create sensible amount of data/request with different states
- [x]  Understand the loading on Dashboard. TRY TO MITIGATE THE LOADING with UX
- [x]  Because 1000 records will not be available for a state at a given point to time

@m-prodan  @arielleandrews @lmullane  - Advice with a historical data volume or # of records under each state for FOI Requests

**Comment by m-prodan** [comment]
@abin-aot  - I'm not sure I can check historically active, but looking at right now it appears we have 2767 active FOI Requests - of those, the majority (1035) are in Records Review, and second highest state is CFR at 460. Looking at the last 3 years, we receive on average 864 requests a month. That doesn't account for the impact the application fee will have on that figure going forward.

Hopefully that can help you get started!

**Comment by mpilchar** [comment]
Looking to start this one in the new year - jan 4

**Comment by abin-aot** [comment]
#1094  #1000 - Should be analyzed while doing this.

**Comment by richard-aot** [comment]
Hi team,

Since business team already wrote the ACs for IAO queue and Ministry Queue, shall we reuse the ACs in the related User stories?

Please reference ACs in the following US when doing QA:
#20 Queue for Unopen
#85 Sorting
#200 Search
#288 Search by state
#354 Navigate to request from queue
#570 Ministry queue
#571 Filter (for example, Assigned to me)

**Comment by lmullane** [comment]
@richard-aot, do we need a QA on this? Unclear to me how we test this?

**Comment by lmullane** [comment]
Discussed with @abin-aot.  We know what needs to be done.

**Comment by richard-aot** [comment]
@Mullane, Loren CITZ:EX ***@***.***>Good question. Yes, we do
need a QA on this. I understand the confusion here. From the user
perspective, nothing seems changed on the IAO queue (dashboard) and
Ministry queue, which is what we are trying to archive.

However, behind the scenes, both frontend and backend are updated:
For IAO queue and Ministry queue, we used to retrieve all requests from the
server in one API call, then do the listing, pagination, searching, sorting
on the front end. This works fine if we don't have too many requests in our
system. If there is more data, we will start seeing performance and memory
issues.
In the new implementation, the pagination, searching, sorting is executed
on the database server, which is what the database is designed for. The API
serves 10 requests (configurable) to frontend each time, so regardless of
how many requests in the system, the performance will not be impacted.

To QA this, we need to re-test User Stories for IAO queue and Ministry
queue. Go through the ACs in those US's again. The purpose is making sure
that both queues are working as they used to be (same columns,  data,
searching and sorting).

Below are the User Stories that I found for re-test:
#20 <https://github.com/bcgov/foi-flow/issues/20> Queue for Unopen
#85 <https://github.com/bcgov/foi-flow/issues/85> Sorting
#200 <https://github.com/bcgov/foi-flow/issues/200> Search
#288 <https://github.com/bcgov/foi-flow/issues/288> Search by state
#354 <https://github.com/bcgov/foi-flow/issues/354> Navigate to request
from queue
#570 <https://github.com/bcgov/foi-flow/issues/570> Ministry queue
#571 <https://github.com/bcgov/foi-flow/issues/571> Filter (for example,
Assigned to me)

Let me know if you have any questions.

Thanks.

**Comment by lmullane** [comment]
Note, when you sort by 'Received Date' the sort is not chronological.
