### ISSUE TITLE
PHN Information is getting missed on Personal FOI Request

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#1089]
**Describe the bug in current situation**
System is not maintained information entered inside PHN for Personals requests

**Link bug to the User Story**

**Impact of this bug**
DATA LOSS or  DISPLAY missing for PHN or DATA NOT POPULATING on Front end - PHN

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by jadmsaadaot** [comment]
https://github.com/bcgov/foi-flow/pull/1219

**Comment by lmullane** [comment]
This is fixed.

As discussed, the PHN (editable field only for the analyst) is not a field in the online form.
