### ISSUE TITLE
Setup CI/CD pipeline

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#109]
Title of ticket: Setup CI/CD pipeline

#### Dependencies
None - this is foundational

#### DOD
- [x] Setup jenkyns pipeline - with github actions
- [x] Automated build pipeline to dev ~~and test~~ (Adam: removed test, see comment below)
- [x] All devs have access to the system
- [x] OpenShift authentication configured in GitHub repo secrets
- [x] Service account created in GitHub for logging in as GH actions.
- [x] GA tests or build checks run on PRs.
- [x] GA deploys build to "dev" OpenShift when work is checked into "dev" GitHub branch.

**Comment by mpilchar** [comment]
@acoard-aot where are things at with this?

**Comment by acoard-aot** [comment]
I met with Sumesh and Saravan to go over the GitHub Actions (GA) pipeline
they used.

Here's the link:
https://github.com/bcgov/sbc-auth/tree/main/.github/workflows

I'm currently reviewing this.  I was going to start the task in ernest, but
it turns out I need to help deploy Patroni to the test env first

**Comment by acoard-aot** [comment]
After beginning implementing, I suggest adding the following definitions of done.  It's fine if we don't, these can still serve as documentation of tasks completed.

* OpenShift authentication configured in GitHub repo secrets
* Service account created in GitHub for logging in as GH actions.
* GA tests or build checks run on PRs.

**Comment by acoard-aot** [comment]
Good news.  The "CI" part is done, and the "CD" part is completed for pushing a build to dev.  I've created the PR and will move this ticket to "Review." I will share this with the team more fully on Monday, maybe setup a meeting after discussing with team.

A minor issue I'll bring up with the 2nd definition of done item for deploying to "dev and test".  As discussed with Loren, we're drawing our implementation from sbc-auth.  However, their solution from what I can tell only deploys to dev.  After discussing with dev team, we think this is best approach for now (we can always revisit).  As such, I've crossed off "test" in the DoD description in the card.  Please let me know if this is an issue.  My thought is that for now test needs to be stable if we are using it for our demos.

This task was about creating a minimal CI/CD pipeline, and is complete, but there is a lot more to gain by continuing to work on it.  Many of these were in the sbc-auth project, but we just haven't had time to setup, and we will absolutely want to do (next sprint?). This includes:


* [CI] Running Abin's unit tests for request management api
* [CI] Running postgres migrations from request management api
* [CD] Watching rollout status after build is complete
* [CD] Sending push notifications of success or failure to Teams (? or RocketChat if teams doesn't support).

Additionally, we may wish to look at including FormsFlowAI in github actions, particularly the web component.

**Comment by mpilchar** [comment]
@acoard-aot I know there were some aspects of this body of work you wanted to make note of as we go forward. Let me know if you have any thoughts on how to do this (add to backlog or something less formal?) before this gets closed
