### ISSUE TITLE
Start Date and End Date not displayed in description summary on stage "Intake in Progress".

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#1098]
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/2901ebd7-c2b9-4d4c-ac12-10489f4b374e)

**Comment by jadmsaadaot** [comment]
#1204 which is about the order of the request description history follows this one

**Comment by lmullane** [comment]
This is fixed.

**Comment by mpilchar** [comment]
Reopening due to issues on DEV/TEST and need to retest

**Comment by lmullane** [comment]
Checked again and this bug is fixed.
