### ISSUE TITLE
UX Assurance - Date Format Display

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1101]
User feedback at the last sprint demo indicated a strong preference to have all dates in the application displayed in MMM DD YYYY format (i.e. DEC 12 2021)

- [x] Update date format in Intake Team queue
- [x] Update date format on Ministry Queue
- [ ] Update date format on Request view for Ministry users

Intake Team Queue:
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/5b7f21b9-d119-48a0-9edd-3bbe3442fb59)
Ministry Queue:
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/ced94347-9206-4045-96c6-9b2a4ea8876b)
Ministry Request View:
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/5cb46539-306c-4bc7-a25f-1af4bfa33943)

**Comment by arielleandrews** [comment]
Updated to remove any date pickers, bug ticket is to make consistent displayed dates only

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Wanted to confirm that the date format this ticket was supposed to update to is MMM DD YYYY (ie, FEB 09 2022)

**Comment by JHarrietha-AOT** [comment]
As discussed on Feb 14th, dates in Queues have updated to MMM DD YYYY format (FEB 14 2022). All areas where dates windows have a date picker have not been updated as they will need to be changed across the whole system and this will require a dedicated task with a larger estimate

Great work on the update @jadmsaadaot
