### ISSUE TITLE
Team Queues - hover to display request description

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1102]
* As a user
* I want to see the request description of a request when I hover my cursor over the Request ID 
* so that I can more easily differentiate and prioritize the requests in my queue

**Assumptions & Scope**	
* Applies to all queues (Intake, Flex, Ministry, and Processing Team queues)
* Requires Processing Team Queue to have already been built (user story #1000)
* Full text of the request description will display and the date range for the records search
* Only the latest version of the request description will display

What is IN scope?
* Displaying and collapsing the request description when hovering the cursor

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Move cursor over request ID Number**
* GIVEN I am a user on a queue
* WHEN I move my cursor over the ID Number for a request 
* THEN a display window will appear that displays the full request description for that request
* AND the text window will also display the date range for the request at the end of the request description in parentheses e.g. This is the request description (Jan 1 2021 to Jan 31 2021) 

**Scenario 2: Move cursor off request ID Number**
* GIVEN the cursor is hovered over the ID number for a request
* WHEN I move the cursor off the ID number to anywhere else on the page 
* THEN the display window will disappear 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/831805474
Click on 2nd Request ID from the top to see expected view on hover

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Looks great to me - I have a feeling when we demo this, the Ministry's may ask for this too :)

**Comment by JHarrietha-AOT** [comment]
Looks good, my only question would be - should this be on all queues or just processing team. Like wouldn't all user groups find this to be useful?

**Comment by lmullane** [comment]
We should do it for all queues imo. Don't you think so?

**Comment by arielleandrews** [comment]
Thanks team! Rewrote assumptions and AC to include all queues

**Comment by KyEggleston** [comment]
ACs pass, closing.

**Comment by nimya-aot** [comment]
@KyEggleston @nkan-aot  There is an issue while hovering over to request . Some requests which IAO creates has no records search date, on that case when hover over the request it shows a default date range . Can you check this screenshot? May be we can check on the stand up tomorrow
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/ab26001e-25f5-48ec-9f4e-18378aeb7917)

**Comment by KyEggleston** [comment]
@nimya-aot - reopened and will check edge cases more tomorrow

**Comment by KyEggleston** [comment]
AC's pass - in addition, when no search date is populated (start and end date), no search date is displayed in request description tooltip (only the request description is displayed).
