### ISSUE TITLE
Deploy File Watcher on Windows VM

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#111]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Create deployment package
- [ ] Deploy to dev
- [ ] QA 
- [ ] Deploy to prod

**Comment by mpilchar** [comment]
VM access is with Matt Morris, Waiting on test IDIRS for Divya/Abin, plus service account

**Comment by m-prodan** [comment]
Service Accounts being re-requested through Sandra Baxter - IAOAgileTeamTest and IAOAgileTeamProd

"-A"IDIR access has been requested for both @divyav-aot  and @abin-aot 

All 4 IDIRs being requested to be part of an active directory group.

Discussed with Sandra Baxter morning of June 9th to ensure order is understood - will copy me when submitted. I will escalated to Gladys when submitted to try and move it along faster.

**Comment by abin-aot** [comment]
Deployment package ready, Waiting for VMs, Access etc.
