### ISSUE TITLE
Implement reporting feedback

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1119]
#### Description
Creating this as a placeholder since we may not implement feedback until the new year

Assumptions: 
Discussed at Jan 7/22 - There are two user groups. Those who want data manipulation option and those who want a finished, formatted option

WG feedback
- [ ] team may not use report without formatting
- [ ] Is there an OIPC review attached to the file?
- [ ] include # of days overdue / when LDD has been missed
- [ ] indicate that LDD includes extensions applied

Jamie and Andrew:
- [ ] 3 big stages recommended by Jaimie to include: CFR, Gathering, Sign off
- [ ] For closed requests: Percent on time, average days overdue
- [ ] For received requests: Frequency/on time
- [ ] Date range retention policy - 5 fiscal years. Going forward, keep CRTS data but don't include it. Just have AXIS data. 
- [ ] Test if data can run during day - any timeout errors? (Run time has diminished since moving from Oracle to Sequel)
- [ ] Enthusiasm for ability to sort by RBAC

**Comment by mpilchar** [comment]
@m-prodan @arielleandrews feel free to add any reporting feedback from the pilot meetings or working group session

**Comment by mpilchar** [comment]
Assumption discussed at Jan 7/22 - Those who want data manipulation option and those who want a finished, formatted option

**Comment by JHarrietha-AOT** [comment]
Closing this ticket, Andrew will be reviewing and giving feedback on redash this sprint
