### ISSUE TITLE
Absence of modal with unsaved divisional changes

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1121]
**Describe the bug in current situation**
When I'm logged in as a ministry user and delete a division, or change the state of the division, and navigate to another tab, the information will still be on the request page. However, if I refresh the page, the information will appear without a warning such as "changes will be lost, are you sure you want to exit without saving?" 

**Link bug to the User Story**
#586

**Steps to Reproduce**
1. Go to https://test-foirequest.apps.silver.devops.gov.bc.ca/foi/dashboard and login as an education user
2. Click on Request tab in left nav
3. Scroll down to divisional tracking section
4. Delete a division by clicking on the trash can
5. Click on another tab such as comments, then return to request page
6. Refresh page - changes will not be saved
7. If I click the "back" arrow, I cannot leave the page, but a modal also doesn't prompt me to save changes

Impact: Confusion for loser, lost changes
Expected behaviour: A modal should appear after clicking refresh or back button, prompting a save

**Comment by abin-aot** [comment]
#762 which @aparna-aot is currently working on fixes this. @mpilchar please confirm on #762 release to test
