### ISSUE TITLE
iStore Order - new Folder on LAN for Filewatcher

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1136]
Title of ticket: iStore Order - new Folder on LAN for Filewatcher

#### Description
Need to have new folder on LAN called 0 - Filewatcher for development purposes

#### DOD
- [x] Determine permissions (flex, social tech team)
- [x] Submit iStore Orders
- [x] Confirm Completion

**Comment by m-prodan** [comment]
Order submitted today - user groups include flex team and social tech. Determine if any additional users will be required, will submit additional request at a later date

**Comment by mpilchar** [comment]
@m-prodan  is this complete?

**Comment by m-prodan** [comment]
It's about 95% complete - folder has been created but for whatever reason iStore missed two flex team analysts for permissions. So leaving this open until Michelle confirms the last two have been granted access.

**Comment by m-prodan** [comment]
Closing ticket - Jazmine and Debbie have confirmed they can access the folder now.
