### ISSUE TITLE
Update Content on FOI Webform

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1139]
Title of ticket: Update Content on FOI Webform

#### Description
Definition of IGE is being published to IAO website, and a broken link has been identified.

#### DOD
- [x] Update broken link on form
- [x] Add approved text to content around IGEs

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/0762dba3-6783-4c01-b8ae-6f46c1069662)

Highlighted link in image should direct to: https://www2.gov.bc.ca/gov/content/governments/about-the-bc-government/open-government/open-information/freedom-of-information/11936

Approved text to add (locations TBD) : Indigenous governing entities (IGE) are not required to pay application fees. Indigenous governing entity “means an Indigenous entity that exercises governmental functions, and includes but is not limited to an Indigenous governing body as defined in the Declaration on the Rights of Indigenous Peoples Act.”

**Comment by m-prodan** [comment]
Ticket drafted from email sent by Natalie re: webform content

cc @jadmsaadaot @lmullane - let's plan to do a quick estimate on this one at sprint planning and bring it in with the IGE work. This should just be a content update.

**Comment by lmullane** [comment]
Thanks, @m-prodan . Probably less than a 1.

**Comment by m-prodan** [comment]
Hi @jadmsaadaot - let us place the text in these two spots:

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/aee96d15-a762-430f-8e26-f0e2007e436f)

Please put the text in a new bullet, below the first one under Fees.

Secondly...

![Check box - location 1.PNG](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/84fd0d50-3292-4c08-b33b-d10e14494c58)

Just add after the sentece next to the checkbox: 

Indigenous governing entity “means an Indigenous entity that exercises governmental functions, and includes but is not limited to an Indigenous governing body as defined in the Declaration on the Rights of Indigenous Peoples Act."

Also Jad - please note that they would like a hyperlink added to the word Indigenous Governing Entity which will link to: https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96165_07#Schedule1

**Comment by abin-aot** [comment]
@m-prodan - assuming this can be closed.

**Comment by m-prodan** [comment]
Yep! Didn't realize it was still showing but it was because I didn't select all the repos! Closing ticket
