### ISSUE TITLE
Request view when multiple boxes have been selected on a Personals Intake form

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1151]
* As an intake user
* I want to see a single request containing all relevant information when an applicant has selected multiple boxes on the Personals intake form
* so that the applicant's request can be adequately actioned and responded to
![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/9da51856-f8b4-4886-b037-7ca1fd3b6370)

**Assumptions & Scope**	
Currently the applicant has the ability to select all boxes - this story assumes all information will get treated as a single request from a single applicant, even when the request is for multiple individuals. For example - a mother applying for her own information, her child over 12 and her other child under 12

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: xxxxxx**
* GIVEN ... (you or your condition)
* WHEN ... (what you do) 
* THEN ... (what you see) 

**Scenario 2: xxxxxx**
* GIVEN ... (you or your condition)
* WHEN ... (what you do) 
* THEN ... (what you see) 

**Scenario 3: xxxxxx**
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
I uncovered this use case while I was testing personal attachments. Creating a new issue so it can be addressed. cc: @lmullane @arielleandrews @m-prodan @JHarrietha-AOT

**Comment by m-prodan** [comment]
Just looking at this one now @mpilchar - Is the issue here that on the personals request view, it's not clear that an applicant has checked all of those boxes?

**Comment by mpilchar** [comment]
@m-prodan The issue at hand is that if they do select all boxes only partial information gets captured in the single request that gets generated. Happy to demo this for you
