### ISSUE TITLE
UX research study guide for Redirect

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#116]
Description: 
Draft of the questions we will be asking users, plus a script
Possible tactic format: User is given a task and asked to complete it

DOD:
- [x] Drafted
- [ ] Reviewed and discussed with SMEs or PO

**Comment by JHarrietha-AOT** [comment]
@m-prodan 

Please review when you have a chance

https://teams.microsoft.com/l/file/859CCEB4-FEB1-4CAE-93FF-59829AFECE00?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FSprint%203%20-%20Research%20-%20Redirect%2FUX%20Research%20-%20Sprint%203%20-%20Study%20Guide.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by m-prodan** [comment]
Looks good @JHarrietha-AOT - I added a comment for consideration, thinking we might need to add a bit more re: how the app is expected to function, mostly for the benefit of those we haven't met with yet.

**Comment by JHarrietha-AOT** [comment]
@m-prodan Have you read the additional sentence I added?

@arielleandrews @lmullane Did you have any additional comments to add before the first session today?

**Comment by arielleandrews** [comment]
@JHarrietha-AOT commenting late but nothing further to add at this point

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan Thats great to hear! Could one of you close both this issue (#116) and #118 as you reviewed it. Thank you
