### ISSUE TITLE
UX research plan for redirect

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#117]
Description: 
text doc of tactics we'll use for user testing, goals and list of participants

DOD:
- [x] Drafted
- [ ] Reviewed and discussed by SME or PO

**Comment by JHarrietha-AOT** [comment]
@m-prodan Please review the research plan when you have time

https://teams.microsoft.com/l/file/212B327B-EBF1-4969-AB6D-ABD57EBC4CE7?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FSprint%203%20-%20Research%20-%20Redirect%2FUX%20Research%20-%20Sprint%203%20-%20Plan.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by m-prodan** [comment]
Looks good to me @JHarrietha-AOT - I just made some quick corrections as I went along and am good with the content. I think we can close this ticket, I'll close this ticket with my comment
