### ISSUE TITLE
"Attached Documents" text shows on Child Details and On Behalf of Details

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#1171]
I guess that we added "Attached Documents" text on Child Details and On Behalf of Details for personal requests as a place holder. Since we have Attachment tab now, those place holders are not needed anymore.

![image.png](https://images.zenhubusercontent.com/6140ffb032396d7b882056ce/4f55f681-a4c8-45d2-83a4-a15ffc84df66)

**Comment by abin-aot** [comment]
@richard-aot  - Once the deployment for #1355 is done. This will be covered.??

**Comment by richard-aot** [comment]
That is correct. This will be covered when #1355 is deployed.

**Comment by KaraBeach** [comment]
Confirmed that attachment details text is removed under child details and on behalf of details. Ticket closed.
