### ISSUE TITLE
Create a survey for IAO for Reporting research

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1178]
#### Description
We discussed using a survey or some other wide-reaching method to hear from analysts how they use reporting. It appears there are wide variances in the types of reports used by teams and we are limited in time and resources to do research sessions with everyone.

#### DOD
- [x] Draft questions
- [x] Review questions - PO, designer
- [x] Determine survey tool (UniverCITZy uses Survey Monkey)
- [x] ED approval
- [x] Create survey

**Comment by mpilchar** [comment]
@lmullane please review once you're back. https://bcgov.sharepoint.com/:w:/t/03521/EZGzM0YS7FdEk1fVyNMDbBsB4p6m95SJKD2NidHSGtxq1Q

**Comment by lmullane** [comment]
@mpilchar, I've made some comments and track changes in the doc. Thanks for the opportunity to review.

**Comment by JHarrietha-AOT** [comment]
@mpilchar @lmullane 
Wanted to share out a link to the survey questions update that I worked on, @m-prodan and @arielleandrews  have already had a first pass. Feel free to leave comments so we can continue to improve them with the goal of sending out the survey mid-week this week.

https://bcgov.sharepoint.com/:w:/t/03521/EbM0jDXN6VNIuRgFQkfDxbkBvP3KFxdhhVmbEbtQt_dATQ?e=kBF5Py

**Comment by mpilchar** [comment]
@JHarrietha-AOT I'm good with the list of questions and have added in a couple thoughts for consideration

**Comment by lmullane** [comment]
Thanks. Will look in a bit. Our ED wants to review as well.

**Comment by mpilchar** [comment]
I have built the survey using the draft questions we shared with Rhianna (it will be easy enough to update with any changes). I made one change to the demographic collection approach, which I've tagged for Loren. Also awaiting payment guidance from @lmullane

**Comment by mpilchar** [comment]
Survey was rebuilt in IAO forms. Will be sent out today
