### ISSUE TITLE
Determine most common data fields for reporting

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1179]
#### Description
During Jan 5 sprint, we will be designing the data warehouse for our new system. We need to know what data fields to include as part of this. 

#### DOD
- [x] Determine the top utilized reports needed for the pilot
- [x] compile a list of data fields from those reports

**Comment by arielleandrews** [comment]
List compiled here: https://bcgov.sharepoint.com/:x:/t/03521/EXfwcfnYMlpMmiovOsSm2bkBHkHru76JXuiuVx3-RMkFKA?e=TfWPXD
