### ISSUE TITLE
User testing sessions for Redirect

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#118]
Description
- 6 x 1 hour sessions with IAO

DOD

UX Research Tests completed with:
- [x] Melissa Kerr - Jun 15 11am-12pm
- [x] Tanya James - Jun 16 10am-12pm
- [x] Richard Webster - Jun 16 1pm-2pm
- [x] Liz Babecy - Jun 17 11am-12pm
- [x] Marc Everitt - Jun 17 1pm-2pm
- [x] Arun Sudireddy - Jun 18 1pm-2pm

**Comment by mpilchar** [comment]
@arielleandrews Please add names cc: @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
Session 1 Recording: https://bcgov-my.sharepoint.com/:v:/g/personal/arielle_andrews_gov_bc_ca/ERPwFpJ5SOFInFoWr2uodQMBba61rpS-oSdRC2mZagDnlg

**Comment by JHarrietha-AOT** [comment]
Session 2 Recording: https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%203%20-%20Research%20-%20Recordings/Redirect%20Workflow%20User%20Testing%20-%20Tanya-20210616_130021-Meeting%20Recording.mp4

**Comment by JHarrietha-AOT** [comment]
Session 3 Recording: https://bcgov-my.sharepoint.com/:v:/r/personal/jacklyn_harrietha_gov_bc_ca/Documents/Recordings/Redirect%20Workflow%20User%20Testing%20-%20Richard-20210616_160046-Meeting%20Recording.mp4?csf=1&web=1&e=zbyb2s

**Comment by JHarrietha-AOT** [comment]
Session 4 Recording: https://bcgov-my.sharepoint.com/:v:/g/personal/jacklyn_harrietha_gov_bc_ca/EQ3g21bVLhxEmYoHWTeHKswBIoBzdQSdM5LllmmbX6VLAA

**Comment by JHarrietha-AOT** [comment]
Session 5 Recording: https://bcgov-my.sharepoint.com/:v:/g/personal/jacklyn_harrietha_gov_bc_ca/EfEKrCaupelJhCNt9dX8EVMBzzg3ZqjYsUjEoNGejaycPg

**Comment by mpilchar** [comment]
@JHarrietha-AOT ok to move this to closed?

**Comment by JHarrietha-AOT** [comment]
Session 6 Recording: https://bcgov-my.sharepoint.com/:v:/g/personal/jacklyn_harrietha_gov_bc_ca/ERcvpNL8nqRMiMkHs7lzQikBJVtaUkV_nJ1QLXWQG36WDA

**Comment by JHarrietha-AOT** [comment]
@mpilchar Yup, just like to link to recordings in the issue so they are there for reference. This is closed
