### ISSUE TITLE
UX design for additional divisional stages (#1109)

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1186]
Title of ticket: 

#### Description
A design is needed for ADM sign off and routinely releasable requests at the division level. Whether the solution is to incorporate in the current dropdown menus or handle in some other fashion needs to be decided.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Create a permission matrix for super admins and managers
- [ ] Set up meetings with managers
- [ ] 
- [ ] 
- [ ]

**Comment by JHarrietha-AOT** [comment]
@mpilchar Trying to get an understanding of what is needed for this ticket design wise. Are we updating the dropdown for divisions? Just trying to understand what the users need here. If you can explain I can add it to the Divisional Design Updates I will be doing this sprint
