### ISSUE TITLE
Badges for Attachments

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1187]
* As a user
* I want to see colour coded badges next to the filenames of attachments 
* so that I can easily differentiate between attachments and locate the one I want 

**Assumptions & Scope**	
* This is a UX update to the functionality already in place for attachment badges
* Attachments uploaded using the Add Attachment button in the Attachments tab will have the General badge attached, and the colour will be the same navy blue used in the BC header on the page
* Attachments uploaded during a state transition will have the badge display which state the request was moved to and from, and the colour will be the same colour as the new state e.g. "Open > CFR" and the colour will be the same as the CFR state

What is IN scope?
* Updates to the attachment badges only

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Badge for attachment uploaded during state change**
* GIVEN the user has selected to change the state when an attachment is required (e.g. CFR to Fee Estimate)
* WHEN the user uploads the attachment and selects Save 
* THEN the attachment will appear in the attachment tab
* AND a badge will display showing the state transition (e.g. CFR > Fee Estimate)
* AND the badge will be the same colour as the new state (e.g. Fee Estimate)

**Scenario 2: Badge for attachment uploaded directly to the attachment tab**
* GIVEN the user is on the attachment tab of a request
* WHEN the user clicks the Add Attachment, uploads a file and selects Save
* THEN the attachment will appear in the attachment tab
* AND a badge will display showing General
* AND the badge will be the same navy blue colour as the BC logo header

**Scenario 3: xxxxxx**
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Looks good - thanks for capturing this @arielleandrews

**Comment by JHarrietha-AOT** [comment]
@lmullane @arielleandrews I am going to close this ticket, it is completed with the recent work on the attachment log #2489, #1974, #2470
