### ISSUE TITLE
User Research for Additional Queue (super admin, manager)

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1189]
Title of ticket: 

#### Description
We need to determine what features IAO managers would need in a queue, as well as how they'll be using the new system during the pilot rollout. Do managers involved in the pilot ministries also require the ability to manage requests for the non-pilot ministries they oversee? 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by JHarrietha-AOT** [comment]
@mpilchar I think this Issue can be closed, Managers would see the same queue based on their team. And if we are building our customizing Queues later on they could leverage that to change. Managers would also use the "My Team Request" to see the requests of their teams.
