### ISSUE TITLE
Modal for "Linked Requests" link

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1191]
* As an IAO or Ministry user
* I want to know which other ministries a request was sent to
* so that I have a fulsome understanding of the request I am reviewing

**Assumptions & Scope**	
* Linked Requests Link will be present for all requests, regardless of number of ministries selected (1 vs all ministries)
* Summary of ministries is flat - no hyperlinks included to other requests
* AXIS has a field called 'Linked Requests' - which shows the same requests opened across multiple public bodies

At this time - there should be no active hyperlinks, just the request IDs showing. As not all Ministries are yet in Mod, we will go with a basic view first.

NOTE: would like a front end text update, from "Ministries Canvassed" to: "Linked Requests"

There are no other significant changes with respect to the AXIS sync, but I added a scenario to ensure it is included in the preview accordion.

For the AXIS Sync preview accordion - "Linked Requests" will show up on the left side of the table, and on the right side will be the linked requests.

What is IN scope?
The hyperlink, modal, and summary of ministries included within the modal
AXIS Sync to pull the linked request data

What is NOT in scope?
Hyperlinks to take users to the other requests

**Acceptance Criteria**	

**Scenario 1: AXIS Sync - Link Activation**
* GIVEN an IAO user has synced a request to FOI Mod
* WHEN the synced request has request IDs in the 'Linked Request' table
* THEN the link for "Linked Requests" will be active

**Scenario 2: Click on "Linked Requests"**
* GIVEN a user is on the review request page
* AND the linked requests hyperlink is active
* WHEN they click on "Linked Requests" link under "Request details" section
* THEN a modal will appear, showing the request ID and Ministry associated with each linked request

**Scenario 3: Close modal**
* GIVEN a user is on the 'Linked Requests' Modal
* WHEN they click the x in the top right corner
* THEN the modal will close and I will be returned to the Request details section of the Request page

**Scenario 4: Linked Requests added to AXIS**
* GIVEN a request has been synced to FOI Mod
* WHEN the Linked requests table has been updated for the request
* THEN the AXIS sync banner and button will be active

**Scenario 5: Sync with AXIS**
* GIVEN a request has been synced to FOI Mod
* AND the linked requests table has been updated for the request
* WHEN IAO user clicks sync with AXIS
* THEN the preview change modal will appear
* AND the linked requests will display in the preview accordion (see assumptions)
* AND any other syncable changes will also show if present

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/799026754 and https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088423

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Design for pop-out is here: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/799026754

I think from our conversation yesterday... not sure where we landed, but maybe we call it "Same Requests" instead of Ministries Canvassed? 

@arielleandrews

**Comment by mpilchar** [comment]
@JHarrietha-AOT I think there's something broken on the design for this one - when I try to close the x on the modal, the modal will not close. Can you please look into this? Thanks!

**Comment by mpilchar** [comment]
During refinement, discussed the need to create a link and modal for all users - currently this link does not show on IAO users request views. Will create a story for this

**Comment by lmullane** [comment]
Intake should enter the linked request and then this should be viewable for both the IAO analysts and ministry clients.

AKA are also linked.

**Comment by m-prodan** [comment]
Updated this user story and added AXIS sync scenarios. May need to be re-estimated, as this was originally written without AXIS sync in mind.

**Comment by m-prodan** [comment]
cc: @liseandtea @KyEggleston @JHarrietha-AOT

**Comment by KyEggleston** [comment]
Tested on WLR-2023-30172 in DEV - all ACs pass. Fix for 'Linked Requests' hyperlink being active when no linked requests pending, and will be done as part of this ticket.

**Comment by KyEggleston** [comment]
Check 'Linked Request' link is only active when there are linked requests. Should be inactive when no linked requests.

**Comment by aparna-aot** [comment]
Scenarios to test : 

- Syncing a new request with linked requests in axis.
Move the request to open state and then update the linked requests in axis for that request.
Check if the axis banner is showing and on clicking the sync with axis button, it should show all the linked requests in axis on the modal. 
And once you save that change , linked requests in FOI mod should show the updated linked request.

- Remove all the linked requests from axis for that particular request.
Again FOI mod should show the banner and in the modal there should be linked requests field with empty values.
And once you click save all the existing linked requests in FOI mod should also get deleted.

**Comment by m-prodan** [comment]
Tested again in TEST - working as expected, also tested additional scenario raised by aparna around removing all linked requests and the corresponding behavior. Closing ticket
