### ISSUE TITLE
Create a second alternative for Redirect flow

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#120]
Title of ticket: 

#### Description
Split the request, edit descriptions later, open request later

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Created
- [x] Reviewed internally

**Comment by JHarrietha-AOT** [comment]
@m-prodan 

Here is a link to the queue, can you review the 5 tasks of the different request types and let me know if I missed anything

https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451

**Comment by JHarrietha-AOT** [comment]
@m-prodan I finished all the adjustments we discussed late yesterday. Let me know if there is anything further.

@arielleandrews Click through and let me know if you have any changes, you can see in the Study Guide how participants will be asked to navigate through

**Comment by arielleandrews** [comment]
@JHarrietha-AOT nothing additional to provide after our call this morning. Thanks for all your great work on this!

**Comment by m-prodan** [comment]
It looked good to me as well @JHarrietha-AOT  - I clicked through it as you were starting your session. I hope the first session went well! I think we can close this one up now?
