### ISSUE TITLE
Request Description History out of order

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1204]
When user makes edit to request description during stage Intake In progress, description history becomes out of order

**Steps to Reproduce**
- create new request
- move to stage intake in progress
- make edits to the request description
- save request
- view description history

**Actual/ observed behaviour/ results**
first edit made in stage intake in progress gets listed as original request description, instead of the request description that was submitted from public

If first edit is made in any other stage (i.e. open, call for records) there is no problem 

Also once request moves to next stage open, history is in the right order again

**Expected behaviour**
submitted request description should be listed as original

**Comment by lmullane** [comment]
@nkan-aot, thanks for your work on this. Could you add an esitmate?

**Comment by lmullane** [comment]
This fix is working. Just need an estimate and then we can close. cc @mpilchar @m-prodan
