### ISSUE TITLE
Request Description History username from online form

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1206]
Request description history only shows "online form" as username if IAO user makes first edit in stage "unopened"
If first edit is made in any other stage (e.g. intake in progress, call for records, open) description history will show the IAO user as the author for the original request description

**Link bug to the User Story**
related to issue #31

**Steps to Reproduce**
- submit new request 
- login as IAO user, complete form, save request and move to intake in progress
- edit description , save again
- open description history

**Actual/ observed behaviour/ results**
current username displays as author for both original description and edit

**Expected behaviour**
- should say "online form" for the original description, then current user for the edit
- description submitted should always have "online form" as author, for people who can view it
- if there were edits made, then ministry users will see the first edit as original description, with the user who made the first edit as author, if there were no edits made, then ministry user will see the original description

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
Hi @nkan-aot - I've done QA on this one.

While it seems to work at first - there is something that happens that I am starting to be able to replicate. When a request is moved to call for records, and is assigned to a Ministry, then these issues present themselves again. What is more interesting is that the Ministry user assigned to the request, suddenly becomes the author of the previous request description. I don't know if this should be a new bug ticket or If I just update here with some screenshots and steps. I'll flag this to raise quickly at stand-up tomorrow.

**Comment by nkan-aot** [comment]
i think i have an idea why this happening, looking into it

**Comment by nkan-aot** [comment]
i have a fix for the first situation but i am unable to reproduce the second issue

**Comment by m-prodan** [comment]
Can no longer replicate - appears to be fixed - closing ticket
