### ISSUE TITLE
Object Storage data migration

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/foi-flow#1208]
Title of ticket: Object Storage data migration

#### Description
This task is to copy all the data from LAN to Object Storage

#### Dependencies
No

#### DOD
- [x] Execute the script to copy files from LAN to TEST VM
- [x] Check if GeoDrive is moving the files from TEST VM to Object Storage and replaces it with a stub file in TEST VM
- [x] Compare the files migrated to Object Storage
- [x] Note all the files that were not copied through the logs
- [x] Schedule the scripts to run daily once after business hours

**Comment by mpilchar** [comment]
@VineetBala-AOT Is this complete (other than the files we need IMB's help with to manually transfer)? If so, can you please close and create a new task for the manual transfer?

**Comment by VineetBala-AOT** [comment]
Closing this ticket. Opened a new task #1340 to track the files that need a manual transfer.
