### ISSUE TITLE
Request description history date incorrect

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1209]
**Describe the bug in current situation**
Date for description history edits are one day ahead

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
- submit request
- login as intake user
- complete form and save
- make edit to request description and save again
- click on description history

**Actual/ observed behaviour/ results**
date is one day ahead

**Expected behaviour**
date should be the same day edit is made

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by abin-aot** [comment]
@aparna-aot  - Could you please check this ?

**Comment by aparna-aot** [comment]
@abin-aot Found the issue. Will fix after finishing current task.

**Comment by aparna-aot** [comment]
@arielleandrews Can you hold testing this task? In DEV we have found an issue with the date while Camunda was down (which is not in TEST right now). But for ensuring that won't happen in TEST need to make some updates. After fixing that up, will have to test this ticket again. So moving this task to In Review.

**Comment by JHarrietha-AOT** [comment]
Bug is fixed, great work!
