### ISSUE TITLE
Creation of Homepage for app

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#121]
* As an analyst
* I want a homepage
* so that I can login to the application

**Assumptions & Scope**	
Custom React landing page
Use images and logo from Jackie's design
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932449
https://github.com/bcgov/design-system

What is in and not in scope?
Does not include the redirect to formsflow (for that, see #35)

**Acceptance Criteria**	

**Scenario 1: Analyst access homepage landing page**
* GIVEN ... that analyst is on the internet
* WHEN ... they click this URL
* THEN ... they will see homepage design

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [x] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [x] If there is a user interface, is there a design? 
4. [x] Does the user story need user research/validation?
5. [x] Does this User Story needs stakeholder approval?
6. [x] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [x] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [x] Has the story been estimated?

**Definition of Done**

1.    [x] Passes developer unit tests
2.    [x] Passes peer code review
3.    [x] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[x] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[x] Developer to list Config changes/ Update documents and designs
10.	[x] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
@divyav-aot can you please check off which of the DOD boxes are complete and which are still underway?

**Comment by m-prodan** [comment]
Home page looks good to me, have had no issues accessing it in test.
