### ISSUE TITLE
Reopen Request to On Hold

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1211]
**Describe the bug in current situation**
Requests closed and reopened to On Hold state and then moved to Call for Records state have an extra business day added to the legislated due date

Example: 

**Link bug to the User Story**
User Story #832

**Impact of this bug**
Impact is Medium. Only occurs on requests reopened to On Hold state which is rare, however the legislated due date being incorrect has significant impact.

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Request must be On Hold prior to being Closed, reopened to On Hold, then moved to Call for Records. Request needs to be On Hold for at least 1 business day to properly test due date recalculation.

**Steps to Reproduce**
Request is able to move from Closed to On Hold successfully. However, when taking the request from On Hold to Call for Records, the due date and days remaining countdowns are not calculating correctly. Example EDUC-2021-27080 in Test: request placed On Hold on Dec 17 (Friday), then closed on Dec 20 (Monday), and reopened to On Hold on Dec 20. The due date remained as Jan 14 but should have updated to add two business days. Clarification: in this example, the Friday and Monday should be counted as "on hold" days.

![image](https://user-images.githubusercontent.com/82615839/146822100-fa4330c7-3d8d-413c-a1d7-e7bfc6cc9cf2.png)
![image](https://user-images.githubusercontent.com/82615839/146822052-00102deb-b15a-4b87-b437-376f4fea2b58.png)

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by arielleandrews** [comment]
@divyav-aot tagging you for awareness

**Comment by jadmsaadaot** [comment]
@divyav-aot and I can confirm that this works fine on local and we could not reproduce the error. It seems that it has been fixed. We will just test one more time in real time in Dev.

**Comment by JHarrietha-AOT** [comment]
Tested bug on multiple requests. Extra day no longer added when moved to and from On Hold. Great work, moving but to closed!
