### ISSUE TITLE
Search for requests not in the queue (closed, unopened, not assigned to them, etc.)

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1213]
* As an IAO analyst
* I want to be able to search for and locate requests not on my queue 
* so that I can view other requests including closed requests

**Assumptions & Scope**	
What are the assumptions for this story?
 
We will reuse the search field and paramters in the the current client-side search (e.g request #, ministry abbrevation, general vs personal, x gov number, assignee, etc.).

If a user searches for an applicant name, then the results will show all requests with that applicant name (requests that are closed, requests in any state in the user's queue already, and requests in any state in other user's queues).

Select Public Body dropdown menu with multiple selections will function the same as the Watcher drop down.

Date range functionality will be consistent with request dates.

What is IN scope?
Backend search for requests not in the user's queue.
Includes pt: Row request #, AXIS #
Includes pt 2: Synching data between our system and AXIS 

What is NOT in scope?
Current client in side search for requests that are in the user's queue.

Ministry coordinator advanced search will be covered in a separate ticket.
**Acceptance Criteria**	

**Scenario 1: IAO queue**
* GIVEN an IAO analyst is on his or her queue
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445057
* WHEN the user clicks the 'Advanced Search' toggle
* THEN the advanced search view will open
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
* AND there will be a search field, search buttons (AXIS request #, Raw request #, Applicant Name, Assignee Name, Request Description, Subject Code), Request State checkboxes (Unopened, Call for Record, Records Review, Ministry Sign off, Closed), Request Status Checkboxes( All Active, Overdue, On Time), Request Type checkboxes (General, Personal) Search date range (From, To), Select Public Body Dropdown, and a button to 'Apply Search' (primary action), and a button to 'Clear All Filters' (secondary action).

**Scenario 2: Open Search by Public Body**
* GIVEN an IAO analyst is on the advanced search view
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
* WHEN the user clicks the 'Select Public Body' dropdown
* THEN the dropdown will enter with all the public bodies listed
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058

**Scenario 3: Select Public Body**
* GIVEN an IAO analyst has opened the 'Select Public Body' dropdown
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
* WHEN the user clicks an empty box next to a public body 
* THEN the box will turn green and have a white checkmark
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058

**Scenario 4: Unselect Public Body**
* GIVEN an IAO analyst has opened the 'Select Public Body' dropdown
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
* WHEN the user clicks a filled box (already selected) next to a public body 
* THEN the box will turn be white and empty
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
...
Scenario 5: Close Select Public Body Dropdown
GIVEN an IAO analyst has selected or unselected one or more public bodies on the drop down
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
WHEN he or she clicks anywhere outside the dropdown list
THEN the dropdown will close
AND the public bodies selected will be filters for the search

Scenario 6: Open Date Calendar
* GIVEN an IAO analyst is on the advanced search view
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
WHEN the analyst clicks the calendar icon next to the From Date or To Date 
THEN the calender view will open
AND the analyst cannot select a 'To Date' before the 'From Date'

Scenario 7: Edit Date 2
GIVEN the analyst has opened the calendar for the 'From Date' or 'To Range (
WHEN the analyst clicks on a date in the calendar (standard material UI function)
THEN that date will be selected

Scenario 8: Edit Date Range Start Date 3
GIVEN the analyst has selected a date
WHEN the analyst clicks 'anywhere on the screen outside the calendar
THEN the calender will closed
AND the selected date will be displayed
AND the selected date will be the new 'From Date' or 'To Date' diplayed
AND those dates will be filters for the search

Scenario 9: Cannot select to 'To Date' before the 'From Date'
GIVEN the analyst has opened the calendar
*https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957829
WHEN the analyst clicks a 'To Date' before the 'From Date' 
THEN date will not be able to be selected
AND a message will appear that you cannot select a  'To Date' before the 'From Date' 

Scenario 10: Select a Request State, Request Status, Request Type
* GIVEN an IAO analyst is on the advanced search view
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
* WHEN the analyst clicks a box for Request State, Request Status,  Request Type
* THEN the search will be filtered by that selection
* AND only one box can be checked

Scenario 11: Select a pre-filter button (e.g. AXIS Request #)
* GIVEN an IAO analyst is on the advanced search view
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
* WHEN the analyst clicks a button (e.g. AXIS Request #)
* THEN the search will be filtered by that selection
* AND only one button can be checked

Scenario 12: 'Clear All Filters
* GIVEN an IAO analyst is on the advanced search view
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
* AND selections have been made
* WHEN the analyst clicks the 'Clear All Filter' button
* THEN all search filters will be removed

Scenario 13: Apply Search
* GIVEN an IAO analyst is on the advanced search view
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
* AND selections have been made
* WHEN the analyst clicks the 'Apply Search' button
* THEN requests will be returned based on the selected search criteria and listed below the Advanced Search in the same order with the same columns at they do on the queue

**Scenario 14: Return to queue**
* GIVEN an IAO analyst is on the advanced search view
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
* WHEN the user clicks the 'Your FOI Request' toggle
* THEN the ministry coordinator or IAO analyst will be returned to his or her queue
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445057

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, I like your thoughts on the user experience for how a user would search and get results for request(s) that are not part of their standard queues.

For example, requests that are closed or assigned to another team. I've taken a very speculative approach right now (see AC above) but don't love how it sounds.

**Comment by lmullane** [comment]
Tasks will be:

1. Custom API to integrate with AXIS
2. AXIS request number in Flow database
3. Search unopened requests from Flow database
4. Advanced search for any request not in queue (i.e. closed requests, assigned to a different user, watcher)

**Comment by lmullane** [comment]
For 3 and 4 need a user experience. Jacky is working on advanced search design already.

**Comment by lmullane** [comment]
@JHarrietha-AOT, small thing but on the design can we change the request state from 'Sign Off' to 'Ministry Sign Off' to be consistent with the state dropdowns?
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058

**Comment by JHarrietha-AOT** [comment]
@lmullane Good catch, designs have been updated. https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058

**Comment by lmullane** [comment]
@JHarrietha-AOT, please review the AC and let me know of any errors or admissions.

**Comment by JHarrietha-AOT** [comment]
@jadmsaadaot @amichard I am pushing this back to In Progress, I have listed the changes needed below to better meet the designs. Great job on functionality! Let me know if you have any questions and tag me when you are ready for me to review again.

**On Queue Changes**
- [ ] Decrease spacing around queue filters  (My Request, My Team's Request, Watching Requested)
- [ ]  Increase space around pipe between "You FOI Request Queue" and "Advanced Search"
- [ ] Remove Grey hover/highlight effect that happens when clicking between "You FOI Request Queue" and "Advanced Search"

**In Advanced Search Tab Changes**
- [ ] Increase font size for sections titles (Advanced Search, Request State, Request Status, Request Type, Date Range & Public Body) and make titles bold
- [ ] Decrease spacing between lists of checkboxes
- [ ] Increase spacing Date Range & Public Body Options
- [ ] Decease width of buttons at bottom (Apply Search & Clear All Filters)
- [ ] Buttons should not be in all caps, (Filters in bubbles should stay in all caps)]
- [ ] Remove Hover colour from bubble filters (Remove hover completely, just have change of colour on click)

**Comment by jadmsaadaot** [comment]
![Screenshot 2022-02-26 194929.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/1ee5910f-a118-4344-895d-b8a31fef0c0b)

**Comment by JHarrietha-AOT** [comment]
Ready to QA

**Comment by lmullane** [comment]
@mpilchar, could we please confirm that ministry coordinators also have advanced search as per the AC. The toggle was not there for ministry trainees last week.

**Comment by lmullane** [comment]
Decision is to remove ministry coordinator from the AC and create a new ticket for ministry coordinators and advanced search.

cc @mpilchar

**Comment by lmullane** [comment]
@JHarrietha-AOT, @arielleandrews, is this scenario correct? 

GIVEN the ministry coordinator or IAO user is on the advanced search view
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
WHEN the analyst clicks a box for Request State, Request Status, Request Type
THEN the search will be filtered by that selection
AND only one box can be checked


I see this AC listed in the QA master list, but it and others on the list, are not part of the original AC.

Will close this ticket as past but want to capture this scenario elsewhere as this scenario currently fails.

cc @mpilchar

**Comment by lmullane** [comment]
Confirmed that AC in above comment is incorrect.
