### ISSUE TITLE
Update FileWatcher reference material for IAO

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1214]
**Update FileWatcher reference material for IAO**

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Update FileWatcher page in OneNote
- [x] Draft communication for IAO and Ministry contacts
- [x] Deploy
- [x] Send out communication
- [ ] 
- [ ]

**Comment by m-prodan** [comment]
Draft of One-Note material complete. Need to consider updating the video recording embedded within (or perhaps remove it?)

**Comment by mpilchar** [comment]
Heard from Patrick and team today that we can go to prod asap
