### ISSUE TITLE
Secure URLs to Host Application

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#123]
Title of ticket: Secure URLs to Host Application

#### Description
Approvals requested for:
https://foirequests.gov.bc.ca
https://testfoirequests.gov.bc.ca
https://devfoirequests.gov.bc.ca

Policy requires this to be submitted to and approved by the GCPE Joint Working Group prior to us being able to request the websites.

#### Dependencies
Prior approvals required by MCIO and GCPE - Approvals received from both on June 15th

#### DOD
- [x] Approval Received from GCPE Joint Working Group
- [x] iStore Order Resubmitted and Completed for 3 URLs noted above

**Comment by m-prodan** [comment]
Package submitted with required approvals to GCPE Joint Working Group June 16th

**Comment by m-prodan** [comment]
Joint working group approval received today - total package submitted to iStore for processing

**Comment by m-prodan** [comment]
Redirected package to IMB - after discussion with David Smyth when questions arose, it was determined this should have been sent through the IMB

**Comment by lmullane** [comment]
Hey @m-prodan , any status updates on this?

**Comment by m-prodan** [comment]
Per message from Alexander Punnet today - iStore order is complete, all 3 domains should be ready for use. Closing ticket (finally!)
