### ISSUE TITLE
UX Study Guide - Reporting - Ministry & IAO Team Leads 

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1234]
Description
This is the small scale Research Plan and Study Guide for the next phase of reporting research

Dependencies
Are there any dependencies?

DOD
- [x] Draft Study Guide
- [x] Designer feedback
- [x] PO Review & Provide Feedback

**Comment by m-prodan** [comment]
Study guide here for review: https://bcgov.sharepoint.com/:w:/t/03521/Eacak0hGfVZKo6SvaVy5GGQBcLSFt5PlsKAeLjf2R8hPzA?e=0K5gOJ

cc @arielleandrews @lmullane @JHarrietha-AOT
