### ISSUE TITLE
Katalon CI/CD integration

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/foi-flow#1237]
Title of ticket: Katalon CI/CD integration

#### Description
Run Katalon tests in GitHub action in CI/CD pipeline.

Idea: If we have one floating license, we can run all tests on a cron overnight.  They do not _have_ to run on each push, though that would certainly be preferable.

#### Dependencies
A central email set up 
Katalon license needs to be sorted out.  (Floating?)  Requires discussion.

#### DOD
- [x] Katalon tests run in GitHub action
- [x] Refactor Katalon tests to not use db connection
- [x] Katalon license configured in GitHub securely
- [x] Use free trial (week of Jan 17)
- [x] Get a second trial with new email - determine whose email this will be
- [x] Determine if license can be moved to a different email address over time
- [x] Confirm our data is not going into their public cloud / our machines are not required to integrate with their cloud services
- [x] Add katalon github action to the end of CD scripts after merge to dev (confirm with rest of team)
- [x] Find a way to host larger files for testing attachments

**Comment by mpilchar** [comment]
Runtime license - $1340USD/yr, to unlock features on Nick's machine $890USD/yr.

**Comment by mpilchar** [comment]
![2162e712-3f94-4611-8fb1-1e633c0aa49c.jpg](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/af31a6ae-fb76-4a77-af80-ccd25f5831ce)

**Comment by mpilchar** [comment]
![9e6c71df-88b5-4ad2-9646-c7c697dbfb40.jpg](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/b64c3ef5-279f-4ab6-ad16-38d72ecefcf6)

**Comment by mpilchar** [comment]
Likely about 3 points remaining out of 8 at this point

**Comment by acoard-aot** [comment]
Marking as complete.  Just reviewed this with @nkan-aot who has done outstanding work and this has already been merged into main.  In effect this should have been waiting for review, and the review is done.  Nick's work is exemplary here and makes him a great option for any other devops work.
