### ISSUE TITLE
Analysis of moving our OpenShift namespace to a gold cluster

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1239]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by mpilchar** [comment]
Discussed at Jan 5 sprint planning. Need support filling out the DOD on this @lmullane @acoard-aot @abin-aot

**Comment by acoard-aot** [comment]
Should I still work on completing this? What's the priority, and are there gaps in our understanding that we want addressed after our previous meetings with Olena?
