### ISSUE TITLE
Monitor and/or Reduce OpenShift Resource Usage for FormsFlowAI via SysDig

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/foi-flow#1240]
Title of ticket: Monitor and/or Reduce OpenShift Resource Usage for FormsFlowAI via SysDig

#### Description
In task #1238, we need to increase CPU/mem availability so we can host a new Redash.

This task is about using SysDig in combination with load-testing of the application.  The goal is to either:

1. Identify there is under-utilized resources and properly tune formsflow deployment to use less.
2. Identify all resources are fully utilized, and make a request to platform team for more space.

#### Dependencies
Load-testing using JMeter is working

#### DOD
- [x] SysDig dashboards are working and displaying resource utilization
- [ ] ~~SysDig reports/dashboards created during load testing~~
- [ ] ~~Solution is identified (either tuned down resource limits or requesting more resources)~~

**Comment by mpilchar** [comment]
@acoard-aot Is the goal to complete this task in its entirety during this sprint or do we need to revisit scope?

**Comment by acoard-aot** [comment]
Potentially need to revisit.  There is still more work for me to do here,
but a large chunk of the work can only begin after Richard is done his load
testing work.  I don't know exactly how long that will take, but could
potentially push into next sprint.  Good to raise it and happy to discuss
more, maybe at next standup? I can split up tasks if that's what we decide.

**Comment by acoard-aot** [comment]
Splitting ticket and marking the remaining ticket as completed.
