### ISSUE TITLE
Notifications - CFR and LDD events trigger pull notifications

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1242]
* As a User
* I want CFR and LDD events to trigger notifications through a pull
* so that I can be informed of important changes to my requests

**Assumptions & Scope**	
This covers specific events in the application that will PULL a notification to a user assigned or watching a request

Notification Pulls will occur every 15 minutes

What is IN scope?
This covers events across the application that will be pull notifications to an assigned user, as both a primary user and watcher of the request. 

This story covers notification events for CFR and LDD only.

What is NOT in scope?
Event notifications for state changes and assignments (separate user story #855)
Dismissing Notifications (Separate user story #854)
Navigation from Notifications (Separate user story #856)

**Acceptance Criteria**	

**Scenario 1: Call for Records Due Date [insert next business day]**
* GIVEN a FOI Request is in the "Call for Records" state
* WHEN the Call for Records countdown reaches 1
* THEN all users assigned to the request will receive a notification that includes: FOI Request number, and a message saying: Call for Records due on Date [insert next business day] through a pull notification that occurs every 15 minutes. 

**Scenario 2: Call for Records Due Today**
* GIVEN a FOI Request is in the "Call for Records" state
* WHEN the Call for Records countdown reaches 0
* THEN all users assigned to the request will receive a notification that includes: FOI Request number, and a message saying: Call for Records due Today through a pull notification that occurs every 15 minutes. 

**Scenario 3: Legislated Due Date [insert next business date]**
* GIVEN a FOI Request is in any state
* WHEN the days remaining on a request reaches 1
* THEN all users assigned to the request will receive a notification that includes: FOI Request number, and a message saying: Legislated Due Date is due date [insert business date] through a pull notification that occurs every 15 minutes. 

**Scenario 4: Legislated Due Date Today**
* GIVEN a FOI Request is in any state
* WHEN the days remaining on a request reaches 0
* THEN all users assigned to the request will receive a notification that includes: FOI Request number, and a message saying: Legislated Due Date is Today through a pull notification that occurs every 15 minutes. 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@sumathi-thirumani-aot, new story is here. cc @mpilchar

**Comment by sumathi-thirumani-aot** [comment]
Please help refining the notification messages listed @lmullane @mpilchar 
Sample Notifications:

Legislative Due Date due on 2022 JAN 11
Legislative Due Date is Today
Call for Records due on 2022 JAN 11
Call for Records due Today

**Comment by sumathi-thirumani-aot** [comment]
Need confirmation on date format given 2022 JAN 11 @lmullane @mpilchar

**Comment by sumathi-thirumani-aot** [comment]
Please help with generation ID of these reminders . Have defaulted to "System" now @lmullane @mpilchar

EDUC-2022-140151
Call for Records due Today
System | 2022 JAN 11 10:20AM

**Comment by sumathi-thirumani-aot** [comment]
1	Open	Opened Request
2	Call For Records	Call For Records
3	Closed	Request closed
4	Redirect	Redirect
5	Unopened	Unopened
6	Intake in Progress	Intake in Progress
9	Consult	Consult required on Request
10	Ministry Sign Off	Request Signed Off
11	On Hold	On Hold
12	Deduplication	Deduplication
13	Harms Assessment	Harms Assessment
14	Response	Response
8	Fee Estimate	Fee Estimate
7	Records Review	Records Review
15	Archived	Archived

**Comment by sumathi-thirumani-aot** [comment]
Raised tech debt for inquiry -> https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/bcgov/foi-flow/1329

**Comment by arielleandrews** [comment]
QA completed, all test scenarios passed in Chrome, Edge and Firefox.
