### ISSUE TITLE
Identify Required Mapping fields for Reporting comparing provided Report samples

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#1250]
Title of ticket: 

#### Description
The purpose of this task is to cross reference the the Data Mapping done on Task #1247 and Reporting samples provided. Also, discuss with SME team with various options , existing gaps(if any) and Futuristic asks for MoM, YoY reporting

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Create Mapping between Reports(available vs Jackie's UR) and columns/fields in identified
- [x]  Make sure, Relations found is good for EDW Design, which is followed by this task
- [ ]  _Field confirmation via IMB_ : moving this DOD to #1348
- [ ] 
- [ ]

**Comment by abin-aot** [comment]
[https://app.zenhub.com/files/358004325/abea4a78-672c-493a-9855-a6f62d86020a/download](https://app.zenhub.com/files/358004325/abea4a78-672c-493a-9855-a6f62d86020a/download)

**Comment by abin-aot** [comment]
These are report template samples we referred [https://app.zenhub.com/files/358004325/34f6af70-d0e2-46ec-9c40-d776cf633dd6/download](https://app.zenhub.com/files/358004325/34f6af70-d0e2-46ec-9c40-d776cf633dd6/download) . Since these report templates only have fields and not DATA. We are thinking to review the existing extract logic used to create existing reports - so that we can be double sure on exact source data column from axis. @m-prodan is coordinating this IMB (Alexander)

**Comment by mpilchar** [comment]
@m-prodan I have also added this as a task in our IMB excel sheet - as their PO requested we track all requests of their team in one spot for easier management: https://bcgov.sharepoint.com/:x:/t/00192-FOIModernizationTeamandIMBTeamCommunication/EfYTNgmQZHhPm6JXQNRWtjgBwHB99Zcg3bH9DXrO-klgdw?e=b340OU

**Comment by abin-aot** [comment]
@mpilchar @m-prodan @lmullane @arielleandrews , we(myself and @VineetBala-AOT ) is moving the last DOD of this task - "field confirmation on report", to a separate task with estimate of 5. since we haven't received that information from them yet(as per above comments). But we can reduce the estimate on this task to 8 from 13.

**Comment by mpilchar** [comment]
Makes sense, thanks @abin-aot ! There might be a question for us in here about how we can manage external dependencies so they don't impact team velocity - retro fodder!
