### ISSUE TITLE
Redash - Keycloack Integration

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/foi-flow#1259]
Title of ticket: Redash - Keycloack Integration

#### Description
Analysis

#### Dependencies
No

#### DOD
- [x] Check Redash - Keycloack Integration
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by VineetBala-AOT** [comment]
Redash - KeyCloak integration is working fine with Redash Version 8. With the later versions of Redash the SAML login using KeyCloak is broken. The issue is already open with Redash team and awaiting a fix.

**Comment by lmullane** [comment]
Thanks for capturing the update, @VineetBala-AOT

**Comment by mpilchar** [comment]
We will be going with version 8
