### ISSUE TITLE
CFR Folder Structure updates on FileWatcher

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#126]
[https://app.zenhub.com/files/358004325/95342d7e-8e1f-4567-b02e-4d970a172551/download](https://app.zenhub.com/files/358004325/95342d7e-8e1f-4567-b02e-4d970a172551/download)[https://app.zenhub.com/files/358004325/b4b96880-6a7f-4a04-8e3f-5a7758842102/download](https://app.zenhub.com/files/358004325/b4b96880-6a7f-4a04-8e3f-5a7758842102/download)

During QA Cycle of FileConversion/FileWatcher,  its been understood that incoming files/CFR is being done on separate main folder by each ministry.  Means, FNR will be the main folder for corresponding and underneath this folder, there will be a sub folder named "InComing" ( or "call for records" for some ministries) , underneath where CFR subfolder are created with File#. Refer attachment for File Paths used on Production LAN.

**Comment by m-prodan** [comment]
I have replicated folder structure consistent to PROD LAN and produced test files in each Ministry subfolder. Filewatcher and convertor successfully identified and converted files in all folders as expected.
