### ISSUE TITLE
Display 'Ministry Team' name in Assigned in IAO request view

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1266]
* As an IAO or ministry user, when I change a request to the CFR state
* I want the 'Ministry Team' to show as assigned in the 'Ministry Assigned to' drop down menu
* so that I know that the request has been assigned to a team

**Assumptions & Scope**	
What are the assumptions for this story?

Does not need to be a dropdown as IAO can see who is assigned at the ministry but not make a change.

We want the ministry to take ownership over assignment. Ministry process can remain as-is, the only changes incorporated in this issue are the changes that happen on the IAO queue.

Assume that the one person should be assigned at a ministry or at IAO.

As is currently required, when a ministry team first receives a request into their queue, then a user from that team should be required to assign to an individual user before they can save changes to a request. After which it cannot be assigned back to the ministry team.

What is IN scope?
- Ministry Team assignment displaying in the 'Ministry assigned to' drop down for IAO request view

What is NOT in scope?

- In Ministry request view the dropdown will show as unassigned, until user assigns request to individual user before making changes is already required
- 
**Acceptance Criteria**	

**Scenario 1: Display ministry team assignment for CFR state change**
* GIVEN a request is in the open state
* WHEN the Flex Team user changes a request into the CFR state
* THEN the 'Ministry Team' will appear as assigned in the 'Ministry assigned to'  on the IAO request view 
* AND  the 'Ministry assigned to' field will not be editable
* AND (as is current) the 'Ministry assigned to' field on the ministry request view will read 'Unassigned' and the be editable

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KaraBeach** [comment]
Acceptance criteria- passed.  Nice work!
