### ISSUE TITLE
Save a request

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#128]
* As an analyst 
* I want to be able to save a request
* so that edits I make will be saved

**Assumptions & Scope**	
What are the assumptions for this story?
What is in and not in scope?
All fields are editable

**Acceptance Criteria**	

**Scenario 1: Save a request**
* GIVEN an intake analyst is on an the detailed view of a request
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/663873013
* WHEN the applicant clicks 'Save'
* THEN the request and any update fields (i.e. request description, date range, category, etc.,) will be saved
AND a toast will briefly appear that the request has been saved
AND the request status will change to "intake"

**Scenario 2: Navigate away from an edited request before saving**
*  GIVEN an intake analyst is on an the detailed view of a request
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/663873013
*AND the analyst has made edits but not saved
* WHEN the analyst navigates away from the Request
* THEN a modal will open asking "Are you sure you want to leave? Your changes will be lost" with a 'Yes' and 'Cancel 'button
**<design needed here>**

**Scenario 3: Yes to navigating away before saving changes**
*  GIVEN an analyst is on the modal confirming they want to navigate away
* WHEN the analyst clicks 'Yes'
* THEN the modal will disappear 
* AND they will be redirected to where they selected
* AND all of their edits will be lost
**<design needed here>**

**Scenario 4: Cancel to navigating away before saving changes**
*  GIVEN an analyst is on the modal confirming they want to navigate away
* WHEN the analyst clicks 'Cancel'
* THEN the modal will disappear 
* AND the analyst will remain on the Request View
* AND their edits will still be there

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.     [ ] Has been integrated with workflow
[ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
@JHarrietha-AOT please reference scenario #2 for additional designs needed

**Comment by abin-aot** [comment]
1. The links added on this story, seems to be different, Hence referring to this link, [https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/ckpq19gnk00p3011q1mef2ha8/play](https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/ckpq19gnk00p3011q1mef2ha8/play )
2. Considering this link, I am assuming below conditions(pre & post) need to be satisfied
    

- All mandatory fields need to be filled (with asterick* mark) along with Primary & Secondary assignees - Primary & Secondary , right ? . Are they both mandatory ? Please explain.
                           

- Any appetite disabling "Save" if any of the mandatory fields are empty

- Any particular reason for having a separate Save for description, so will this  overall "save" cover that as well?

- Assuming every time we click  "Save" , a version of this request is created, keeping previous one in the database , considering the fact we will have a UX to see the historical path of this request

- Are we covering the disabled section on bottom for this "Save" ? Especially, "Request notes"

-  Assuming Workflow status change will happen behind the scene.

**Comment by lmullane** [comment]
@abin-aot 

Save will not work if mandatory fields are empty. Only Primary assignment.

@JHarrietha-AOT is removing the 'Save for Description' button has discussed. There will be one universal 'Save' button. We will need exceptions - red text to tell the analyst to complete mandatory fields.

Let's discuss versioning. Probably only the original version is required.

When an Unopen request is saved it will automatically go into the Intake state.

**Comment by JHarrietha-AOT** [comment]
@abin-aot @lmullane I have updated the Save button, it is now as the bottom of the screen as an overall save.
