### ISSUE TITLE
Team meeting orientations

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1283]
Title of ticket: 

#### Description
Matt, Arielle, Loren and Molly will be joining IAO team meetings as a way to help support change and hear from analysts directly. 

Ken and Neva - Every second Tuesday at 2pm - Matt attending starting Jan 25
Jamie - Every Wednesday 11am-noon - Arielle attending, starting Jan 26
James/Gitta - Personals Intake - need to confirm
Patrick - Generals Intake/Flex Team - Thursday Jan 27 @11AM

#### DOD
- [x] Assign ourselves to teams / add to calendars
- [x] Determine details around these engagements/how any follow up actions will be captured/communicated
- [x] Schedule future pilot check ins?
- [x] Determine frequency of social tech meetings
- [x] Determine go forward meetings for intake 
- [x] Meet with Personals intake/scanning

**Comment by mpilchar** [comment]
@m-prodan have you heard back from Patrick or James on joining their team meetings?

**Comment by mpilchar** [comment]
@lmullane @arielleandrews - given we are meeting with intake tomorrow, can I close this ticket? Is there anything required for the scanning team?

**Comment by arielleandrews** [comment]
We've met with all groups now - closing this ticket.
