### ISSUE TITLE
Redash Deployment on Openshift Prod, TEST

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1293]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] EXECUTE OCP DC Template for redash, set up service accounts
- [x]  Review resources on namespace
- [x]  Set up SAML authentication with KC
- [ ] 
- [ ]

**Comment by abin-aot** [comment]
Prod - https://foi-flow-reporting-c84b95-prod.apps.silver.devops.gov.bc.ca/
TEST - https://foi-flow-reporting-c84b95-test.apps.silver.devops.gov.bc.ca/
