### ISSUE TITLE
Plan migration/updates on EDW tables, schema

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1297]
Title of ticket: 

#### Description
Plan migration/updates on EDW tables, schema - Alembic? 

#### Dependencies
This task is related to EDW / PostGres DB Set up on Openshift (#1295) and script deployment (#1296)

#### DOD
- [x] Create base framework
- [x]  Create an entry point for the project with Docker/.sh to run alembic migration
- [ ] 
- [ ] 
- [ ]

**Comment by abin-aot** [comment]
decided to go with Alembic. Created a code base with Python and alembic
