### ISSUE TITLE
SSIS ETL package Design & Development  - Framework

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1302]
Title of ticket: 

#### Dependencies
This assumes FW problems and access issue between DMZ VM, AXIS DB and OC is solved. 
Plan B: work locally with AXIS DB Back up

#### DOD
- [x] Distribute ETL SSIS packages as per the Reports Visualizations planned
- [x]  Design packages separately
- [x]  Create ENV VAR/ PARAMETERS for Connections, configuration values
- [x]  TEST LOCALLY

**Comment by abin-aot** [comment]
For ease of development while waiting ETL Server(DMZ - DEV), splitting this to 2 pieces - One Local development of ETL and other one Deployment to DEV Server. - Moving DODs -FYI :  @mpilchar

**Comment by abin-aot** [comment]
### Master DIM ETL SSIS -5
This SSIS package(s) need to be developed first before any. Development of all listed DIM tables, which serves master data to all FACT tables

1. dimECOffice
2. dimECGroups
3. dimRequesterTypes
4. dimRequestTypes
5. dimExtensionStatuses
6. dimExtensionTypes
7. dimRequestStatuses
8. dimRequestforDocumentStatuses - New!
9. dimReceivedModes
10. dimDeliveryModes
11. dimprogramoffices
12. dimFeeTypes
13. dimPaymentmodes
14. dimPaymentstatus


### ETL DimRequest,dimRuncyle -3
This goes second, which is for DIM on Requests, Runcycles. for DimRequest, dimRuncyle

> ALL THE BELOW FACT TABLE ETL can be done parallelly, if all of the above DIM ETLs are completed

### FACT on request Details
factrequestdetails - 8

### FACT on Payment transactions
factRequestPaymentTransaction - 5

### FACT on Request Extensions
factRequestExtensions -5

### FACT on Request Documents
factRequestDocumentsdetails - 8
factRequestForDocuments - 5

**Comment by abin-aot** [comment]
- factrequestdetails , factRequestPaymentTransaction , factRequestDocumentsdetails  - These facts can serve 3 workdashboard reports

- factrequestdetails , factRequestExtensions  - These fact table can serve 2 extension related Reports - Active OIPC Review, OIPC 10 1 d report

- factrequestdetails , factRequestDocumentsdetails , factRequestForDocuments , factRequestExtensions   - These FACT tables can serve rest of reports - BROADER AXIS Fields, addtitions Fields, etc

cc: @VineetBala-AOT
