### ISSUE TITLE
ETL #1  - Master Data - DIMENSION ETLs 

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1303]
Title of ticket: 

#### Description
The purpose of this task is create ETL (Initial Load + Incremental) for Master Dimension tables listed below. This task evolved / reduced from 21 to 3, and with other sub task created for Fact tables ETLs. This development can be done locally with AXIS DB Back up restore on Local SQL DB and VS Community with SSDT, EDW Postgres on Local 

1. dimECOffice -DONE
2. dimECGroups - DONE
3. dimRequesterTypes - DONE
4. dimRequestTypes - DOne
5. dimExtensionTypes - DONE
6. dimRequestStatuses - Done
7. dimRequestforDocumentStatuses - New! - DONE
8. dimReceivedModes - DONE
9. dimDeliveryModes - DONE
10. dimprogramoffices - DONE
11. dimFeeTypes - DONE
12. dimPaymentmodes - DONE

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Create ETL DataFlow, ControlFlow for above mentioned DIM tables
- [X]  Design, Develop logic for Initial Full Load and Incremental Load
- [x]  Develop Queries - Inline(PARAMETERIZED), since AXIS DB SP, View creation will not allowed ???
- [x]  TEST MIGRATION - FULL INITIAL LOAD, UPDATE/INCREMENTAL
- [ ]

**Comment by abin-aot** [comment]
@mpilchar @lmullane : This will get split off as per the ETL fragments logic, can change to multiple tasks with 8,5,8 store points.

**Comment by abin-aot** [comment]
@mpilchar @lmullane @VineetBala-AOT : As discussed,  I am splitting this task to several other sub tasks, so 21 points will be combination of (3+5+5+5+3+5). there is residue/extra for integration and change of etl. dev plans due to infra. wait. Refer Comments on #1302

**Comment by abin-aot** [comment]
Increased estimate from 3 to 5, due the technical limitation with ETL for POSTGRES DRIVERS with SSIS

**Comment by abin-aot** [comment]
@VineetBala-AOT , @richard-aot  - Lets sit on this Master Data ETLs tomorrow. we can discuss few approaches related with Datatypes, Incremental update strategy and a general template logic for all SSIS.
