### ISSUE TITLE
ETL Testing - Confirm Data Migration and Updates

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1305]
Title of ticket: 

#### Description
This relates strictly to moving data to PROD

#### Dependencies
Are there any dependencies?

#### Assumptions
Data is in test but not yet in prod

#### DOD
- [x] Data validation Manually, the LOGIC
- [x]  Compare Reports from AXIS vs FOI FLOW Reporting on REdash
- [x]  Confirm with Business
- [ ]

**Comment by lmullane** [comment]
Add issues that flagged by business to the DOD for this ticket.

**Comment by nkan-aot** [comment]
details about andrew's feedback in #1889

**Comment by m-prodan** [comment]
Andrew has confirmed requests are pulling over into the reports as expected - some additional feedback for consideration:

In the Analyst Workload and Received dashboards, the subject field wasn’t populating, but appears to be functioning as of today.
	
The request descriptions for personal requests aren’t showing up, which is good for the client side, but would be better if it was viewable on IAO’s side. I understand there may be role-based permissions implemented in the future to allow for certain aspects of the reports or reports themselves to be viewed by certain users.
	
I like that the filters are now in alphabetical order, where they weren’t previously.
	
The columns of Category, Not Closed and Exec Cmts are not required in the Received dashboard
	
The columns of Category, startdatecurrdateeqflag, Not Closed and Exec Cmts are not required in the Performance dashboard
	
The details section of the Performance dashboard should be modified to be able to be viewed and scrolled through like the Received dashboard.

**Comment by m-prodan** [comment]
I think the true validation though, will occur when we use PROD data - it is hard to visualize the test data as accurate until we have something to compare it to from the current dashboard reporting perspective

**Comment by abin-aot** [comment]
PROD deployment for reporting and ETL was over a week before - Refer #1308. Informed business Team and waiting for the feedback @m-prodan , @lmullane
