### ISSUE TITLE
Analyst Workload Dashboard - Reporting Design & Visualization -Local Redash

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1306]
Title of ticket: 

#### Description
Summarize issue : Create Redash Visualization for Analyst Workload Dashboard . Since OC environment is not ready @VineetBala-AOT  is developing this locally first, then will migrate to DEV, TEST

#### Dependencies
Are there any dependencies? - Since Environment is not Ready on OC, might need to migrate Visualizations to DEV, TEST once its up

#### DOD
- [x] Create Visualization for the listed reports (Locally)
- [x]  Confirm filters with business
- [x]  Confirm Visualization with Business
- [ ] 
- [ ]

**Comment by lmullane** [comment]
Need a screenshot of reports from @m-prodan and @arielleandrews

**Comment by mpilchar** [comment]
Discussion at Redash demo today:
- Search vs Reporting - There is a lot of overlap between the two. We discussed wanting to drive behavior, ie use reporting for performance stats and using search functionality when users require specifics. 
- Determining which filters to include will be MVP.

**Comment by mpilchar** [comment]
Business area decision needed: There are conversations around performance metrics (ie How many requests are getting closed by individual or group). Numbers at the surface don't always tell the whole story, and this needs to be considered if access/visibility to any information is available to anyone

**Comment by VineetBala-AOT** [comment]
Below are the list of filters and logic we are applying before data is shown on the dashboard.

1) For processing organizations CFD, JAG , MAG, MSD, PSS replace the request description with the subject
2) Include requests where the request types are: 'Consultation', 'Correction', 'General', 'Other', 'Personal', 'Review'
3) Excluded the requests where the processing organizations are: IMB, IAO, XGR, CLB, HSA, IIO, MGC, OBC

**Comment by VineetBala-AOT** [comment]
Closing this task as dashboard demoed and feedback noted. We will be following same theme for other dashboard development.
