### ISSUE TITLE
SSO FOI Flow to Redash

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1307]
* As an IAO analyst or ministry coordinator
* I want to single sign on from Flow to Redash
* so that when I sign into Flow I am also signed into Redash automatically

**Assumptions & Scope**	
What are the assumptions for this story?
Single sign on is a configuration of Keycloak

What is IN scope?
Single sign on 

What is NOT in scope?
Single Sign Out is covered in#1853
Single Sign On from Redash to Flow

**Acceptance Criteria**	

**Scenario 1: Sign into Flow**
* GIVEN a user is signed into the Flow app
* WHEN the user navigates to Redash
*THEN the the user will already be signed into Redash too

#### DOD
- [x] TEST , SSO between FOI FLOW and Redash Reporting App
- [x]  CHECK ON DEV, TEST
- [x]  MAKE SURE REDASH use same Keycloack client app
- [ ] 
- [ ]

**Comment by abin-aot** [comment]
@lmullane , @m-prodan  @mpilchar  - This/SSO is created as task, not as User story, but you can test as per Link Report to FLOW app User story

**Comment by lmullane** [comment]
@divyav-aot, @sumathi-thirumani-aot, how much effort would it take to have this scenario as well?

**Scenario 2: Sign into Redash**
* GIVEN a user is signed into Redash 
* WHEN the user navigates to the Flow app
* THEN the the user will already be signed into Flow app too

**Comment by lmullane** [comment]
Scenario 2 will be covered in #1869.

AC passed.
