### ISSUE TITLE
Secure VM server for AXIS data migration

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1311]
Title of ticket: 

#### Description
Once ETL is complete, we will need to do the deployment of data from AXIS, and require a VM server to enable this

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Determine if there are any CIRMO servers within DMZ not currently in production
- [ ] Confirm coding 112.32999.20403.STOB.3200000. STOB 6301 and whether CITZ Finance is ok to track by project code
- [x] Submit request with QA network hosting (3-4 weeks)
- [x] Download software sequel server (CSAM)
- [x] SSL search
- [x] Add software to server

**Comment by mpilchar** [comment]
@lmullane @abin-aot  Please review this Issue from our IMB meeting this afternoon and make any additions/changes

**Comment by abin-aot** [comment]
I can see EA approved for the Servers, SSIS license. So checking 2 second DOD. All other related tasks are managed on IMB JIRA

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/d2120bcf-89be-415e-af5c-52d0b7a30c0b)
