### ISSUE TITLE
UX design for Opening an AXIS-based Request in the new system

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1314]
Title of ticket: 

#### Description
As we embark on an ETL to merge requests between AXIS and the new system, we need to define intake users' experience

#### Dependencies
Determine: Will intake users enter an AXIS request number? Will a request be automatically added to their queue? How does the request load? 

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by mpilchar** [comment]
cc: @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
@abin-aot Wanted to share a link for you of the sync with Axis. Let me know if you have any questions

https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451

**Steps for creating new request:**
1. Users can sign into and select add request in queue
2. User inputs axis id and hits sync
3. User gets loading bar to show that data is being pulled from AXIS (Bar moves as loads, user can cancel load if they need to)
4. User see page reload with data pulled from Axis
5. User reviews to ensure data is correct
6. User clicks to create new request at bottom

Steps for syncing request:
1. User can go to any active request and click sync on bottom
2. Modal appears: User can sync with AXIS in one click, Cancel or review what is being updated
3. If user wants to see what fields are being updated it appears simplified in a table to with the title of the field and the new content
4. User can again, sync updated data or cancel

cc: @arielleandrews @mpilchar @lmullane @m-prodan

**Comment by lmullane** [comment]
@JHarrietha-AOT, when the data is syncing, is the bar supposed to show the progress of the sync?

**Comment by JHarrietha-AOT** [comment]
@lmullane That's exactly the idea, I think users need some sort of visuals to show that the sync is happening just so there is no confusion and repeatedly clicking the button

**Comment by lmullane** [comment]
Thanks for the confirmation, @JHarrietha-AOT. Note, this design showing updates from AXIS shows Extensions: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852

I thought we were leaving out extensions and state changes?

**Comment by JHarrietha-AOT** [comment]
@lmullane We can't sync state changes because of the vast amount of state changes and current actions don't match in our system - as we simplified the process. Where extension reasons match 1:1 from AXIS to our new system so we are able to pull them in. Also reducing what analyst need to duplicate in the system as this is a key pain point in the existing process. And many Ministries have said they are not typically notified when an extensions happens and have to go search for it in one of the existing reporting tools, this should hopefully remove that.

@abin-aot Feel free to add any additional thoughts on this

**Comment by lmullane** [comment]
Thanks for the confirmation. So we will sync extension information.

**Comment by lmullane** [comment]
Let's chat after standup about the review changes button. Wondering if we don't show this right away (aka 1 modal).
