### ISSUE TITLE
Set up admin access to AXIS db servers

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1332]
Title of ticket: 

#### Description
This relates to IMB granting Admin access to AXIS 10.3 and 10.7 - Abin (test), Vineet (dev and test)

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Molly to request with IMB DA
- [x] IMB to provision for Abin 
- [x] Molly to order _A account for Vineet
- [x] Abin to verify and confirm that he has the correct AXIS
- [ ] IMB to clarify that access is for 10.7 and 10.3 versions of server
- [x] Vineet to verify and confirm _A account access
- [x] IMB to help Vineet access PELICAN using his _A account

**Comment by mpilchar** [comment]
Di Tran (IMB) has given Abin access to the databases: 
Read access has been granted to all ATIP* database in IXIAS\CIRMOTST
Other access privileges that may be considered:
data writer: change data in existing tables in these databases.
dbowner: create tables, drop tables, and other objects these databases.

**Comment by mpilchar** [comment]
_A account for Vineet will be set up during IMB's Jan 20 sprint

**Comment by mpilchar** [comment]
@abin-aot @VineetBala-AOT I have updated DOD with remaining steps needed for you both to have full _A access, and access to versions 10.3 and 10.7. Please ensure this is the correct list of steps. Thanks!

**Comment by mpilchar** [comment]
@abin-aot @VineetBala-AOT @divyav-aot - Can I close this now? Are any others still waiting on _A accounts? Can you connect to the AXIS servers you need (10.3, 10.7)?

**Comment by VineetBala-AOT** [comment]
@mpilchar I can connect to the AXIS DB. We can close this ticket. cc: @abin-aot @divyav-aot
