### ISSUE TITLE
In-App Notifications - Navigating from Notifications(Open state scenario) (#1346)

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#1343]
**Description:**
When a request (eg: U-00X) is moved to open state, then a notification is raised against the unopened request id with a message as "Moved to Open state" for assignees and watchers. But on clicking the "U-00X" request Id of the notification, the redirected URL will be invalid; as it is archived. Also the redirected page now looks incomplete and the save button is enabled so there is a chance of clicking on the save button accidently. 

Solution as discussed:
On one of the standups @abin-aot  suggested as on clicking the request Id we could show a view of all the ministries canvassed (all opened request IDs) for that request and then a user can choose the request they want to view. **This solution will need a design** for the view in addition.

DOD:

Remove request state from the URL of request view page.

**Acceptance Criteria**

Scenario 1: When a request is moved to open state

GIVEN The Watcher of the request will get a notification stating the request has been "Moved to open state" and
WHEN the user clicks on the Request Id
THEN a modal showing the list of ministries canvassed and corresponding request Ids should popup and on clicking the request Id , the user should be able to redirect to the corresponding request review page.

Scenario 2: Check #1346
GIVEN Request Review pages
WHEN the user tries to change the state of the request through the URL
THEN UI shouldn't be affected.
(Note: There shouldn't be any request state present in the request URL.)

**Comment by mpilchar** [comment]
Thanks for flagging this @aparna-aot ! Tagging @JHarrietha-AOT as well for awareness of design request

**Comment by aparna-aot** [comment]
@lmullane @m-prodan @mpilchar @arielleandrews @JHarrietha-AOT 
As a suggestion, we can use this design of ministries canvassed : https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/799026754 for this task as well. If someone could confirm this, I can take up this task today so that it is a continuation of the Notification's US.

**Comment by JHarrietha-AOT** [comment]
@aparna-aot I think that makes sense, we should display the list of the other Ministries in a consistent  style. Do you anything from me today to get started?

**Comment by aparna-aot** [comment]
@JHarrietha-AOT Nothing else. Just the things we have discussed over the call. Thanks!

**Comment by aparna-aot** [comment]
The acceptance criteria (Scenario 1) is already in QA. And since Scenario 2 (#1346) is in progress, keeping the task status to In Progress itself.

**Comment by aparna-aot** [comment]
A bug was noticed in relation to the task: For a request submitted from public which is in unopened state , from the IAO dashboard if a user clicks on the request and opens it, instead of showing Unopened state the left dropdown is empty.

**Comment by arielleandrews** [comment]
@aparna-aot I haven't been able to get notifications to generate for this ticket. Is this ticket for backend only? Do we still need a design?
