### ISSUE TITLE
Navigating to Comments from Notifications

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1345]
* As a user
* I want to be able to navigate directly to the comments page of a request from the comment notification 
* so that I can read the comment right away and minimize the amount of clicking I have to do

**Assumptions & Scope**	
This expands on the functionality developed in user story #1343
Related to user story #906 
Note: This covers only moving to the Comments tab (MVP), not the comment/thread itself (cadillac)

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Comment Related Notifications**

* GIVEN a user has received a notification related to a comment (reply, or new comment)
* WHEN the user clicks on the request ID from the log
* THEN they will be taken to the comment log of that request

..

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
Notifications for Comments are required before the navigation can be completed (#906)

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
FYI @aparna-aot - a separate user story has been drafted as suggested in #1343

**Comment by mpilchar** [comment]
This is ready for technical refinement. Will bring into 2.1 if low effort

**Comment by JHarrietha-AOT** [comment]
@lmullane @arielleandrews @m-prodan This ticket is ready for QA. Should be a quick one

**Comment by lmullane** [comment]
Works as expected. Good work team.
