### ISSUE TITLE
State of Request in request view is based on url

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1346]
**Describe the bug in current situation**
User appears to be able to change the state of a request by changing the url 
i.e. if I have a request open "https://dev-foirequest.apps.silver.devops.gov.bc.ca/foi/reviewrequest/66/Unopened"
and I change the url to "https://dev-foirequest.apps.silver.devops.gov.bc.ca/foi/reviewrequest/66/Open"
the request appears to be in Open state

Data is not affected as user is still not able to change state. State dropdown options are either grayed out, or if user clicks save changes the data will not actually change in the backend. However this is confusing for the user.
Consider the following situation:
- IAO user moves request into Call For Records stage
- IAO user remains on the request review page or keeps its tab open
- Ministry user moves request into Fee Estimate stage
- IAO user refreshes the request review page
- Request will still appear to be in CFR stage since the url will still have "Call%20For%20Records" in it

Chances of this occurring might be medium to low, since user is unlikely to manually change the url, and they likely navigate away from request after they are finished working on it. However to be safe, UI should be based on the request object from backend, not URL. If there is discrepancy between URL and request object, UI should defer to displaying state in request object.

**Link bug to the User Story**

**Impact of this bug**
medium

**Chance of Occurring (high/medium/low/very low)**
medium

**Comment by abin-aot** [comment]
Thanks @nkan-aot  for the issue. Technically we were are discussing this issue as part Notifications navigations. This is also related with bug #1343, @lmullane has raised - Means, cause is same.  @aparna-aot started working on this.

**Comment by mpilchar** [comment]
@aparna-aot Please combine any additional Acceptace Criteria from this ticket with #1343 and close this ticket - thanks!

**Comment by aparna-aot** [comment]
Referenced this bug in #1343 and so closing it.
