### ISSUE TITLE
Extensions - Ministry View

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1347]
* As a ministry coordinator
* I want to see the extensions log 
* so that I know the details of the extensions on a request 

**Assumptions & Scope**
All ministry coordinators will be able to see the extension information for their ministry's requests
Extensions information will be read only
Extensions information will be available from Open state onward
Both Public Body and OIPC extensions will display with the corresponding extension status

**What is IN scope?**
Displaying the extensions information on the Request Details view for ministry users

What is NOT in scope?
Entering and updating extensions information - this is being completed in other user stories

Acceptance Criteria
**Scenario 1: IAO adds new extension**
* GIVEN an IAO user is on the Request Details view
* WHEN a new extension is added
* AND the IAO user clicks Save
* THEN the extension log information will populate and display on the Ministry Request Details view
* AND this information will not be editable by ministry users

**Scenario 2: IAO user updates extension information**
* GIVEN an IAO user is on the Request Details view
* WHEN an extension has been updated (approved or denied), edited or deleted
* AND the IAO user clicks Save
* THEN the extension information will update in the display on the Ministry Request Details view
* AND this information will not be editable by ministry users

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
@JHarrietha-AOT design please!

**Comment by mpilchar** [comment]
Completed as part of extension log - testing for ministry view is required. Can close if all tests pass
