### ISSUE TITLE
Update prototypes based on feedback from user sessions

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#135]
#### Split Request Changes
- [x] Design of ministry checkbox
- [x] Toggle more prominent for redirect/clarify
- [x] Original description more prominent 
- [x] Add Date Range to each added Ministry
- [x] Combine creating acknowledgement and redirect in 1 letter

#### Review Request Changes
- [x] Add sections for "on behalf of"
- [x] Move buttons down page
- [x] Action items are greyed until category gets selected
- [x] View Validated BC Services Card
- [ ] Finalize Top Redirect 'Reasons'
- [x] Add *asterisks* to fields that require action

#### Action
- [x] Push all changes to prototype

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews All changes have been pushed to the prototype expect the top 12 redirect reasons. Would you both be able to create a list and share it with intake to confirm?

**Comment by JHarrietha-AOT** [comment]
Updated prototype can be seen here: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C

I have kept it task based so it is easy to see 5 different options and how they will function

Unopened Request 1 - Open Request
Unopened Request 2 - Full Redirect
Unopened Request 3 - Multi Ministry
Unopened Request 4 - Partial Redirect
Unopened Request 5 - Multi Ministry & Partial Redirect

**Comment by arielleandrews** [comment]
@JHarrietha-AOT I've sent an email to the two TLs at Intake for their suggestions and requested a response by Weds Jun 30

**Comment by JHarrietha-AOT** [comment]
@arielleandrews saw the email, thanks for reaching out to them! I will leave this issue in progress till we hear back from them.

**Comment by JHarrietha-AOT** [comment]
Redirect Reasons has been separated out into its own task as Gitta and Patrick provided a great list of redirect reasons and it will take time for us to categorize and reduce this list to core redirect reasons to include in the prototype.
