### ISSUE TITLE
Change Ministry assigned to after CFR state

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1357]
**Describe the bug in current situation**
Ministry Assigned To field is not editable once the request has moved past Call for Records state. Ministry users should be able to change the assignee at any stage past CFR.

**Link bug to the User Story**

**Impact of this bug**
Medium impact. Ministry users stays assigned but would be unable to change this if away from the office. 

**Chance of Occurring (high/medium/low/very low)**
High. Occurs on all requests after Call for Records state.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Log in as Ministry user
2. Assign self to a request in CFR state
3. Move request to another state (i.e. Deduplication)
4. See Ministry Assigned To field is now disabled

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by arielleandrews** [comment]
QA completed. Confirmed ministry assigned to is now available in all states from Call for Records onward. Nice work @aparna-aot and @nkan-aot!

**Comment by nkan-aot** [comment]
Thanks Arielle!
