### ISSUE TITLE
Create templates for Acknowledgment letters

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#136]
#### Dependencies
External teams' guidance and approvals

#### DOD
- [x]  GDX to advise on design guidelines
- [x] Checked for Legislative guidelines in accordance with FOIPPA
- [x] Letter templates
- [x] Email templates

**Comment by JHarrietha-AOT** [comment]
Removed Review Process as separate task as this will take a while and require back and forth

In ticket #168

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews 

Here is the first draft of the re-design of the acknowledgment letter/email. Core difference is letter has header and footer with contact info, email has signature with contact info. And I have added titles for content to be easier to find. I designed these as examples, so anything in orange is what would be auto-populated based off of what is selected.

Email: https://teams.microsoft.com/l/file/A3D540CF-108A-488D-9A76-8625B9E721E1?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FTemplates%2FNEW%20Email%20Templates%2FProposed%20-%20Acknowledgment%20Email.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

Letter: https://teams.microsoft.com/l/file/F240EE45-10DB-4041-A5EC-F5F321FA5175?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FTemplates%2FNEW%20Letter%20Examples%2FProposed%20-%20Acknowledgment%20Letter.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

Here is the start of the excel with the different options and the text for each, included what was originally provided and what I have changes: https://teams.microsoft.com/l/file/327608AA-011C-44C9-AF85-B325C3325F31?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=xlsx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FTemplates%2FTemplates.xlsx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by arielleandrews** [comment]
And same here @JHarrietha-AOT, I think these are very user friendly. I have added some comments and suggested edits in Teams. @m-prodan would you like to review before moving this to closed?

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Thanks for all the great feedback I made changes, just had one question based of the sentence you added at the start. 

@m-prodan Would you like to review before we move over the the review task ticket? Otherwise either of you can close the ticket when it feels ready to do so, all links are also in the review ticket

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Saw your comment that makes sense. I will add to my list for prototype updates

**Comment by JHarrietha-AOT** [comment]
Closing with this comment, review process has been pulled out into #168, completing the multiple levels of review in a sprint was not achievable in a sprint so we split up the creation and research into this ticket and the review in #168
