### ISSUE TITLE
Front End : Navigating from Notifications (Moved to Open State scenario) (#1343)

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#1369]
Description:

This task is meant for the front end updates involved with navigation from notifications task for an open request.

DOD:

- [x] Modal for displaying the ministries and request Ids.

- [x] Redirecting to the corresponding request page.

- [x] Integrate API update.

- [ ] Unit tests

**Comment by JHarrietha-AOT** [comment]
@aparna-aot Just wanted to leave a comment here based off of the discussion we had yesterday, we want the Request ID# to show in the blue clickable colour and underlined. This is for consistency across the app for anything clickable. Let me know if you need any further clarifications.

**Comment by aparna-aot** [comment]
@JHarrietha-AOT Can you mention here the exact color code to be applied for the Request ID# considering the background color ?
