### ISSUE TITLE
Resolve Web Dependabot Vulnerabilities 

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/foi-flow#1371]
Title of ticket: Resolve Web Dependabot Vulnerabilities 

#### Description
Resolve as many dependabot issues for the web/ folder as possible.  This does not include the api/ issues, which is a separate task.

Dependabot issues can be found here: https://github.com/bcgov/foi-requests/security/dependabot?page=3&q=is%3Aopen

Most issues should be resolvable by updating package.json.  If any are particularly tricky, and might require coordination with third party package maintainers, I'm happy to help.  However, the first-pass of fixes should be done by a developer with domain expertise for the web section.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] All web dependapot vulnerabilities are either resolved or split into other tickets

**Comment by m-prodan** [comment]
closing as duplicate
