### ISSUE TITLE
Add Pilot Users (IDIRs)

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1374]
Title of ticket: Add Pilot Users (IDIRs)

#### Description
Need to create all user groups and populate with pilot team users.

Estimated # of users to add is ~45-50

#### DOD
- [x] List of IDIRs, broken down by teams
- [x] Adds to keycloak
- [x] Users confirm they can login with IDIRs

**Comment by mpilchar** [comment]
This was completed prior to training. cc @m-prodan to confirm and close

**Comment by arielleandrews** [comment]
Closing - all pilot users were added prior to production launch
