### ISSUE TITLE
Comment textbox shifts if last word in a line doesn't fit 

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1387]
**Describe the bug in current situation**
Comment text box will shift slightly if the last word in a line is longer than the line. In the extreme case, if a user pastes a very long string into the text box, the text box will shift off screen

**Link bug to the User Story**

**Impact of this bug**
medium

**Chance of Occurring (high/medium/low/very low)**
medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. submit request, login as IAO user
2. open request from queue, go to comment tab
3. click add comment
4. add some text, make sure the last word in a line is long, doesn't have spaces

**Actual/ observed behaviour/ results**
textbox will shift as you are typing

**Expected behaviour**
textbox should stay stationary regardless of what is entered in textbox 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/fe2ede37-3f43-4932-9091-e4a03b85fca5)

**Comment by mpilchar** [comment]
Passed in Chrome and Edge - thanks for the fix @nkan-aot !
