### ISSUE TITLE
Prep for Pilot Training

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1391]
Title of ticket: 

#### DOD
- [ ] Finalize two system process
- [ ] Review of Matt's draft plan
- [x] Determine dates for training
- [ ] Create IDIRs
- [ ] Communications material for onboarding users
- [x] Onboarding of users (login on keycloak, devs then will ad. This can be done as part of team meetings)
- [ ] Determine feedback mechanism
- [x] Schedule sessions
- [ ]  Prepopulate FOI requests
- [ ] what's required to "launch darkly"? / setup staging?

**Comment by arielleandrews** [comment]
Link to Miro board user flow of AXIS vs New Application: https://miro.com/app/board/uXjVOYEf4eA=/

**Comment by mpilchar** [comment]
EDUC - March 3
ECON - Feb 23 or 24

**Comment by arielleandrews** [comment]
Training scheduled for Mar 3 and Mar 9. All users scheduled to attend these sessions have permissions added to their IDIRs. Any others can be added as needed
