### ISSUE TITLE
System generated comments for Extension (#876)

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#1393]
Title of ticket: 

#### Description
System generated comments for Extension 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Create event for public body extension
- [x] Create event for OIPC extension
- [x] Integration test

**Comment by JHarrietha-AOT** [comment]
Based on conversation with @m-prodan and @arielleandrews we will remove comments for pending extensions and we will remove comments for editing extensions, users will likey not find these comments useful and it will just fill up the comment log.

cc: @divyav-aot @jadmsaadaot
