### ISSUE TITLE
Request is managed entirely by a single user group external to IAO

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1396]
* As an FOI analyst outside of IAO
* I want autonomy to manage records myself
* so that I can protect highly sensitive information

**Assumptions & Scope**	
We have a user group,--Criminal Justice Branch (BC Prosecution Service), a program area of Attorney General--that uses AXIS strictly as a case management tool. They have no interaction with IAO in terms of the process due to the hyper-sensitivity associated with the records themselves - they are a very unique use case. We may need to consider a way for a request to be managed entirely by a single user group.

**What is IN scope?

**What is NOT in scope?
SSO may need to be considered as part of this user story -  IAO has in the past, entered into contracts with BCPS entities that may not want to onboard to our system, or can't as they don't have IDIRs

**Acceptance Criteria**	

**Scenario 1: xxxxxx**
* GIVEN ... (you or your condition)
* WHEN ... (what you do) 
* THEN ... (what you see) 

**Scenario 2: xxxxxx**
* GIVEN ... (you or your condition)
* WHEN ... (what you do) 
* THEN ... (what you see) 

**Scenario 3: xxxxxx**
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
@lmullane @m-prodan - this was made for BC Prosecution Service, which is still on hold for onboarding. Do we want to keep this ticket or close it? Presumably we will have a new round of chats with them when we have an onboarding planned.

**Comment by KyEggleston** [comment]
Closing, and added as notes on our onboarding spreadsheet - this will be discussed when BCPS is being prepared for onboarding.
