### ISSUE TITLE
Integrate ZAP testing into CI/CD pipeline

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1398]
Title of ticket: Integrate ZAP testing into CI/CD pipeline

#### Description
ZAP testing is automated and done within CI/CD pipeline, specifically GitHub Actions.

Note that Zap scans will probably be done against a live environment, eg the test environment hosted in openshift, but will explore 'self-hosting' an instance in GitHub actions.

Currently, ZAP scans are run locally (eg on Jad's developer machine)

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Zap scan done in GitHub Actions for Flow, reporting, angular, etc.
- [x] Zap scan done by one of i) on PR ii) On nightly cron, depending on the impact of tests iii) manual trigger (via workflow_dispatch)
- [x] Schedule automatically like Katalon
- [x] FOI doc editor

**Comment by acoard-aot** [comment]
Estimated as an 8, as this will require some new things on GitHub actions (eg generating files within actions and then using those as a multi-step process to generate ZAP testing report).  Also will update the definition of done after this comment.

**Comment by lmullane** [comment]
Will do manually for the pilot.

**Comment by acoard-aot** [comment]
I have it working with scanning non-IP restricted URLs, as the scans themselves originate on GitHub IPs.

**Comment by lmullane** [comment]
ZAP scan is manually triggered currently with this ticket. Could copy nightly schedule with Katalon and have run nightly.

It is not currently running automatically when code is pushed to TEST; we will want the automated job running in pipeline in TEST in the future.

**Comment by acoard-aot** [comment]
Runs automatically every night.  Still need to setup notification on failures, #1976.

Example: https://github.com/bcgov/foi-flow/actions/runs/3957852953
