### ISSUE TITLE
Updates to Divisional Tracking not displaying until saved

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1404]
**Describe the bug in current situation**
When updating the "Select Division Stage" field for a division, the new stage selected from the dropdown list doesn't display until the user clicks Save; the previous stage continues to display until the change is saved.

**Link bug to the User Story**
#566 

**Impact of this bug**
May cause confusion for the user as change selected is not displayed

**Chance of Occurring (high/medium/low/very low)**
High. Occurs on all requests and across multiple browsers. Does **not** occur for the "Select Division" field, only "Select Division Stage".

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Occurs in Test env

**Steps to Reproduce**
1. Log in as a Ministry user 
2. Go to any request in Call for Records stage with divisions and stages already added
3. Select any other option other than what is already selected from the "Select Division Stage" dropdown
4. See that selection does not change when the dropdown closes
5. Click Save on request details page
6. See selection then updates

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**

**Comment by abin-aot** [comment]
We tried reproducing this during our internal catchup @arielleandrews - Could you please help us to reproduce this?

**Comment by m-prodan** [comment]
Tested AC against #566 - all appears to be working as expected now. Thank you for fixing quickly @aparna-aot
