### ISSUE TITLE
UX Design - Basic Search - Iterate 

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1417]
Title of ticket: UX Design - Basic Search - Iterate 

#### Description
Meeting with Abin to discuss first draft of basic search design (this incorporates the AXIS Integration piece
Decide technical capabilities and challenges and adjust design accordingly 

#### Dependencies
- [x] Meet with Abin

#### DOD
- [x] Meet with Abin
- [x] Decide Technical Changes
- [x] Mini Research Sessions to review and get feedback
- [x] Adjust design
- [x] Update Prototype
- [x] Review with SME & PO

**Comment by JHarrietha-AOT** [comment]
@lmullane @m-prodan @arielleandrews @mpilchar 

Below is a link with the updated Advanced Search Design, Feel free to review when you have a chance and share any suggestions or changes. 

https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058

**Comment by arielleandrews** [comment]
Looks great @JHarrietha-AOT, thanks for incorporating that feedback

**Comment by JHarrietha-AOT** [comment]
Going to move this to closed as we have ha lots of reviews and eye on it. Thanks team for all the great feedback
