### ISSUE TITLE
Design & Workflows - Processing Fees

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1418]
Title of ticket: Design & Workflows - Processing Fees

#### Description
Working on workflow and designs for processing fees

#### DOD
- [x] Workflow for Processing Fees
- [x] Design Update for Processing Fees
- [x] Update Prototype
- [x] Review with SEM & PO

**Comment by mpilchar** [comment]
@m-prodan @KaraBeach - Following up on a question from ECON during yesterday's UX - Is there a way to build in the criteria for when fees get applied into the form? (asked around the 12:00 mark here https://bcgov-my.sharepoint.com/:v:/r/personal/jacklyn_harrietha_gov_bc_ca/Documents/Recordings/UX%20Research%20-%20Processing%20Fees%20(MUNI%20+%20FOI%20Mod%20team)-20220503_180152-Meeting%20Recording.mp4?csf=1&web=1&e=bR5Y1B cc: @JHarrietha-AOT

**Comment by lmullane** [comment]
@JHarrietha-AOT, previously only the Request View (i.e., not Comments or Attachments) had the Watcher and Assign To fields. 

Can I confirm the intention to have these appear on the Fees view as well?

https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803

**Comment by lmullane** [comment]
@m-prodan, @JHarrietha-AOT, in the CFR Division form why is it necessary to include this information in the view for the ministry coordinator and IAO analyst?

They have that info already for a the request.

![Uploading Screen Shot 2022-05-09 at 5.07.07 PM.png…]()

**Comment by JHarrietha-AOT** [comment]
@lmullane Let's remove them and keep it consistent to what we have built so far and have the watcher and assign only on request details. I will remove them tonight before demo.

For your second comment the screenshot isn't uploaded could you re-add it?

**Comment by lmullane** [comment]
<img width="942" alt="Screen Shot 2022-05-09 at 5 07 07 PM" src="https://user-images.githubusercontent.com/12040839/167519559-be5899e2-f667-4f62-9550-e48802327e12.png">

**Comment by lmullane** [comment]
This info is good for the person filling out the form, but a duplicate for the ministry coordinator imo.

**Comment by JHarrietha-AOT** [comment]
I completely agree, with the approach discussed today it make sense to remove this information section for IAO and Ministry Coordinators and just have it auto-populate for Division Users. I'll remove that as well and make sure to discuss it at demo tomorrow.

Thanks @lmullane

**Comment by lmullane** [comment]
Cool, thanks Jacky. I don't expect you to respond to all of this tonight so ignore any other questions I post until the morning:)

**Comment by JHarrietha-AOT** [comment]
@m-prodan @lmullane 

Was just thinking as I was about to remove these info sections above, can you advise if you think it is easier to have reference of the description here for IAO and Ministry Users so they don't have to go back and forth between the fees tab and Request Details Tab? 
I don't think the dates are necessary for them as we have the details in the bottom of the left nav, but could see description being useful when reviewing the CFR form.

**Comment by lmullane** [comment]
Good question. I think no, at least not replicated for each division.  Curious what @m-prodan thinks?

**Comment by lmullane** [comment]
Future research consideration. At the mgmt demo today it was also suggested for the division user that it might make sense to have one form for estimated hrs (filled out pre-search) and 1 for actual hrs (filled out post search). 

For the ministry coordinator having them together in 1 place make sense though, so no change required of this interface design.

**Comment by lmullane** [comment]
@m-prodan, @JHarrietha-AOT, assumption on how this will impact state changes:

The ministry coordinator cannot change the state of a request to Records Review or Fee Estimate until they have a CFR form/Fee Estimate with all mandatory fields completed.

        GIVEN the all mandatory fields are NOT completed
        WHEN the ministry coordinator clicks on the state 'Records Review' and 'Fee Estimate'
        THEN an error message will be displayed stating they must complete the forms to make the state change

Question is how will the application know the form is complete (i.e. 2 of 3 divisions have filled out their forms)? Perhaps we will need logic to check the divisional stages.

**Comment by lmullane** [comment]
Should we call the left nav item Call for Records instead of Fees so it can be generic for both general and personal requests?
