### ISSUE TITLE
Recruitment for Next Steps

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#142]
Recruitment for Next Steps

Description
Recruitment based off of plan for next steps.

Which is our focus? This will be flushed out in #141
- Generals and the Ministry Coordinators Involved
- Second Level Personals Intake and Flex Team

Dependencies
#141 - Research Plan must be completed before we start recruitment

DOD
- [x] User sessions booked in (ideally 4-6 based on availability)

**Comment by mpilchar** [comment]
Timing: July 12-16
Approach: PSS personals, MSD personals, flex team for generals

**Comment by arielleandrews** [comment]
User research sessions scheduled for second stage intake and CFR:
- Katie Innes, PSSG (Corrections) Personals, Justice Health Team - Mon Jul 12 10am-11am PST
- Pablo Frederick, Generals, Flex Team - Tue Jul 13 11am-12pm PST
- April Haussman and Leala Bull, MSD and CLBC Personals, Social Tech Team - Tue Jul 13 2:30pm-4pm PST
- Jazmine Anderson, Generals, Flex Team - Wed Jul 14  10:30am-11:30am PST

**Comment by arielleandrews** [comment]
@JHarrietha-AOT this ticket can be closed, unless you would like to do another session with MCFD Personals as well?

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Should we wait till we hear about how much research this MCFD project will be doing and when they will be starting? @m-prodan When should we have more information about it?

**Comment by m-prodan** [comment]
I'm going to try and meet with CK tomorrow before lunch - should hopefully know more then!

**Comment by JHarrietha-AOT** [comment]
4 user session booked in:

- Katie Innis (PSSG Personals) - Mon July 12th
- Pablo Frederick (Generals Flex team) - Tues July 13th
- April Houseman (SDPR), Leala Bull - Tues July 13th
- Jazmin Anderson (Flex team) - Wed July 14th

Recruitment is complete, with the Deloitte team having sessions booking in this week and there report out being in Aug we with hold out on taking up any time from this team for now

Thanks @arielleandrews for booking in the sessions.
