### ISSUE TITLE
Active OIPC Reviews - Report Visualization on Redash - Local Dev

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#1421]
Title of ticket: 

#### Description
Summarize issue : Create Redash Visualization for Active OIPC Reviews . Since OC environment is not ready @VineetBala-AOT  is developing this locally first, then will migrate to DEV, TEST

#### Dependencies
Are there any dependencies? - Since Environment is not Ready on OC, might need to migrate Visualizations to DEV, TEST once its up

#### DOD
- [ ] Create Visualization for the listed reports (Locally)
- [ ]  Confirm filters with business
- [ ]  Confirm Visualization with Business
- [ ] 
- [ ]

**Comment by arielleandrews** [comment]
An OIPC Review or "Review" is a request type in AXIS, same as a Personal or General is a request type. All the same reporting field parameters apply to a Review file as a General or Personal. Below are the additional fields that are added to capture OIPC Review information. Let me know if you have questions @VineetBala-AOT 
![image](https://user-images.githubusercontent.com/82615839/155416968-3b6dadbe-b85b-42dd-aff7-f5eaace8b24f.png)
