### ISSUE TITLE
OIPC 10 1d Report - Redash Visualization

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#1424]
Title of ticket: 

#### Description
Summarize issue : Create Redash Visualization for OIPC 10 1d Report . Since OC environment is not ready @VineetBala-AOT  is developing this locally first, then will migrate to DEV, TEST

#### Dependencies
Are there any dependencies? - Since Environment is not Ready on OC, might need to migrate Visualizations to DEV, TEST once its up

#### DOD
- [x] Create Visualization for the listed reports (Locally)
- [x]  Confirm filters with business
- [x]  Confirm Visualization with Business
- [ ] 
- [ ]

**Comment by arielleandrews** [comment]
This one I'm not sure we need specific visualizations for. It is a report sent as an Excel spreadsheet from our office to the OIPC. The main pain point with this report is it requires a fair amount of manual manipulation from what we extract from AXIS before we can send it. Below are links to the reports on Teams: the "AXIS Extract" is the raw report as it is pulled from AXIS, and the "Final Version" is the report after the manual manipulation is completed. 
AXIS Extract: https://bcgov.sharepoint.com/:x:/t/03521/ER5D3HRoQZ1HmMMzDaRfXCgBUKyZt18BOCwzZYObiSNh2g?e=hB6zPZ
Final Version: https://bcgov.sharepoint.com/:x:/t/03521/EQFTyxOXhNFAqE4zC1CU-PABjVMCz1PkFgs-3-c_5J-oiw?e=G7rVb3

**Comment by nkan-aot** [comment]
remove public body for redash
