### ISSUE TITLE
CFR/RFD Weekly Report Redash Visualizations

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#1425]
Title of ticket: 

#### Description
Summarize issue : Create Redash Visualization for CFR/RFD Weekly Report. Since OC environment is not ready @VineetBala-AOT  is developing this locally first, then will migrate to DEV, TEST

#### Dependencies
Are there any dependencies? - Since Environment is not Ready on OC, might need to migrate Visualizations to DEV, TEST once its up

#### DOD
- [x] Create Visualization for the listed reports (Locally)
- [x]  Confirm filters with business
- [x]  Confirm Visualization with Business
- [ ] 
- [ ]

**Comment by nkan-aot** [comment]
![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/2a3e0d6b-3a20-4883-863d-4f584e078047)

**Comment by arielleandrews** [comment]
![image](https://user-images.githubusercontent.com/82615839/155377094-237ff02c-d4d5-4036-b97c-7ffe42dfb1f7.png)
