### ISSUE TITLE
Scanning Report- Redash Visualization

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#1426]
Title of ticket: 

#### Description
Summarize issue : Create Redash Visualization for Scanning Report. Since OC environment is not ready @VineetBala-AOT  is developing this locally first, then will migrate to DEV, TEST

#### Dependencies
Are there any dependencies? - Since Environment is not Ready on OC, might need to migrate Visualizations to DEV, TEST once its up

#### DOD
- [x] Create Visualization for the listed reports (Locally)
- [x]  Confirm filters with business
- [x]  Confirm Visualization with Business
- [ ] 
- [ ]

**Comment by arielleandrews** [comment]
Link to Scanning Report sample: https://bcgov.sharepoint.com/:x:/t/03521/ERYoOISmwv1EkjY06vRz3CAB5O4XCuCVAqpANH5lP8Wqxw?e=StKF0p
Generated using the request reporting fields in AXIS:
![image](https://user-images.githubusercontent.com/82615839/155419358-25358f72-3bbe-4327-9726-52f538ac8b20.png)
