### ISSUE TITLE
Sample TL Report - Redash Visualizations

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#1427]
Title of ticket: 

#### Description
Summarize issue : Create Redash Visualization for Sample TL Report. Since OC environment is not ready @VineetBala-AOT  is developing this locally first, then will migrate to DEV, TEST

#### Dependencies
Are there any dependencies? - Since Environment is not Ready on OC, might need to migrate Visualizations to DEV, TEST once its up

#### DOD
- [x] Create Visualization for the listed reports (Locally)
- [x]  Confirm filters with business
- [x]  Confirm Visualization with Business
- [ ] 
- [ ]

**Comment by arielleandrews** [comment]
There are a number of different reports from team leads at IAO that we have as examples, they can be found in this folder on Teams: https://bcgov.sharepoint.com/:f:/t/03521/EiwqRPAOk_FMt4ddTbsrhqYBWth9drh_bz1EeRzb58O55w?e=3A7Grv
The Sample TL Report is a consolidation of the common fields we saw across most of the examples. They are generated using the same request reporting screen in AXIS:
![image](https://user-images.githubusercontent.com/82615839/155419963-23633bab-15c6-4f4a-a380-0afe43d268af.png)
