### ISSUE TITLE
Add Request page - Multiple modal issue on state change from dropdown

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#1432]
**Description:**
This task is about an existing tech debt in the FOI Add Request page. 
Scenario:
While creating a new request, try to change the dropdown from Unopened to Intake in Progress state and try to cancel the state change. The expected behavior is to close the modal without any state change but instead the same modal pops up again.

**Impact of this bug** : Medium impact

**Steps to Reproduce**

- Login as IAO user, click on Add Request button
- Fill in all required fields
- Click on status dropdown, select Intake in progress
- Try to cancel or close the modal without saving any state change.

**Actual/ observed behaviour/ results**
The same modal pops up again.

**Expected behaviour**
The modal should close without any state change.

This bug can be related to #1349. So who ever takes this bug can take up #1349 as well.
[Uploading... Add Request-issue.webm]

**Comment by lmullane** [comment]
@jadmsaadaot, can you please add an estimate to this ticket.

**Comment by jadmsaadaot** [comment]
@lmullane done.
