### ISSUE TITLE
Multiple Public Body Extensions

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1438]
* As an IAO user
* I want to be able to take more than one public body extension 
* so that I can take the maximum allowable 30 days under different reasons for extensions 

**Assumptions & Scope**	
* This is an update to user stories #858 and #878
* Feedback from IAO users indicated there are use cases where an analyst might take a public body extension for less than 30 days for one reason (e.g. 10 days for applicant consent), and then take another public body extension for the remaining days allowed for a different reason (e.g. 20 days for consultation)
* Current functionality limits users to one public body extension only, regardless of the number of days
* The number of days for combined public body extensions cannot exceed 30
* Once 30 days of public body extension(s) have been taken, the public body reasons for extensions should no longer appear in the 'New Extension' modal
* Analysts can pick the same reason for more than one public body extension (e.g. consent can be selected for first and second public body extension)

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: First public body extension is taken for 30 days**
* GIVEN an IAO user has added a public body extension
* WHEN the user inputs 30 days as the number of days extended
* AND saves the extension 
* THEN the user will not see any public body extension reasons listed in the 'Reason for Extension' dropdown in the 'New Extension' modal

**Scenario 2: First public body extension is taken for less than 30 days**
* GIVEN an IAO user has added a public body extension
* WHEN the user inputs the number of days extended as any number less than 30
* AND saves the extension
* THEN the user will continue to see all public body extension reasons listed in the 'Reason for Extension' dropdown in the 'New Extension' modal

**Scenario 3: Second public body extension is taken for less than 30 days**
* GIVEN an IAO user has previously added a public body extension for less than 30 days
* WHEN the user adds a second public body extension
* THEN the maximum number of days the user can input in 'Extended Days' will be the difference between 30 and the number of days in the first public body extension (e.g. if the first public body extension was for 10 days the user can only input a maximum of 20 days for the second public body extension)
* AND the user saves the extension
* THEN the user will not see any public body extension reasons listed in the 'Reason for Extension' dropdown in the 'New Extension' modal

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
@m-prodan @mpilchar @lmullane user story drafted based on feedback received during the IAO branch meeting on Feb 2nd. Please review and make any edits you see fit!

**Comment by m-prodan** [comment]
Nice job on this one @arielleandrews - no changes proposed

**Comment by lmullane** [comment]
Likewise.  Looks great.

**Comment by JHarrietha-AOT** [comment]
@divyav-aot Scroll bar should be removed from modal, adding screenshot for reference. Moving back to in progress

![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/9ee90f3b-edeb-4f5e-bead-ece457206b29)

**Comment by JHarrietha-AOT** [comment]
@jadmsaadaot @divyav-aot let me know if this is something quick we can remove before EOD or not

**Comment by JHarrietha-AOT** [comment]
Ready for QA making a UX Assurance Ticket regarding Scroll

**Comment by arielleandrews** [comment]
QA completed, works great. Nice work as always @divyav-aot

**Comment by mpilchar** [comment]
woo! Ya @divyav-aot!!
