### ISSUE TITLE
Add additional "states" to Request queue

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#144]
As an intake analyst, I want to see a list of FOI requests so that I can understand the status of requests and action requests.

As an intake analyst, I want to see a list of FOI requests so that I can understand the status of requests and action requests.

Assumption
States are shown in this miro board: https://miro.com/app/board/o9J_l9AKkos=/
Treat request as being unopened
No editing information on the Queue - edits will be at single view of a request.
Will need a custom page created in Forms flow. Include Get from API. (TBD based on technical convos)
API work is in #27 to capture webform request.

Acceptance Criteria

Scenario 1: Data in each row for a request

- GIVEN an intake analyst has logged in successfully
- WHEN the intake analyst is on the Queue
- https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451
- THEN for each request the analyst will see applicant last name and first name, request type (general or personal), file number (blank for 'Unopened' request), current status (Unopened, Intake, Redirect, Open), Assigned to (blank for 'Unopened' requests).

Scenario 2: Order of requests on Queue

- GIVEN an intake analyst has logged in successfully
- WHEN the intake analyst is on the Queue
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451
- THEN the requests will sorted by Unopen at top (by date submitted from oldest to newest), Intake in the middle (by date submitted from oldest to newest), followed by Redirect (by date submitted from oldest to newest) and at the bottom by Open (by date submitted from oldest to newest).

Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)

Validation Rules? (If yes, list here)

Design
See designs in Scenarios

Definition of Ready

 Is there a well articulated User Story?
 Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
 If there is a user interface, is there a design?
 Does the user story need user research/validation?
 Does this User Story needs stakeholder approval?
 Design / Solution accepted by Product Owner
 Is this user story small enough to be completed in a Sprint? Should it be split?
 Are the dependencies known/ understood? (technical, business, regulatory/policy)
 Has the story been estimated?
Definition of Done

[ ] Passes developer unit tests
 Passes peer code review
 If there's a user interface, passes UX assurance
 Passes QA of Acceptance Criteria with verification in Dev and Test
 Confirm Test cases built and succeeding
 No regression test failures
 Test coverage acceptable by Product Owner
 Ticket ready to be merged to master or story branch
 Developer to list Config changes/ Update documents and designs
 Can be demoed in Sprint Review
 Tagged as part of a Release
 Feature flagged if required
 Change Management activities done?

**Comment by lmullane** [comment]
@arielleandrews, where in the queue should requests in 'Redirect' status appear? Something link this order from top to bottom: 'Unopened', 'Intake', 'Redirect', 'Open'

cc @mpilchar , @JHarrietha-AOT

**Comment by arielleandrews** [comment]
Assuming we assign the Redirect status when the action has been taken and the correspondence sent out to the applicant, then my preference would be top to bottom Unopened, Intake, Open, Redirect. I would have Open higher in the event the intake team still has some continued involvement in the file. Redirect I would put at the bottom as no further action should be required.

**Comment by lmullane** [comment]
@arielleandrews, our workflow required the Redirect to Closed so still an action that would be needed. If the letter is sent should a redirect automatically be Closed?

**Comment by mpilchar** [comment]
duplicate - closing
