### ISSUE TITLE
Extension Console Errors on Request Review page

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#1452]
Description
While clicking on add request or opening an Unopened / Intake In Progress Request, there are several console errors related to extensions. Not breaking anything but there are some console errors on the page.

![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/53c717f1-e59b-4b35-b96f-6676d9c72414)

**Comment by lmullane** [comment]
@aparna-aot, @jadmsaadaot,  Did we fix this? If so please add an estimate.
