### ISSUE TITLE
Advanced Search - Front End

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/foi-flow#1461]

**Comment by JHarrietha-AOT** [comment]
@jadmsaadaot @amichard Here are the updated designs for the advanced search, let me know if you have any questions

https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058

**Comment by lmullane** [comment]
@JHarrietha-AOT , @jadmsaadaot, is this a duplicate of #1213?

**Comment by lmullane** [comment]
Resolved with @abin-aot. This is a task for #1213
