### ISSUE TITLE
Changes to State updates for Personals requests

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1464]
* As a FOI Analyst
* I do not want to see state changes "On Hold" or "Fees" for any Personals requests
* because these states don't exist for Personals requests

**Assumptions & Scope**	
What are the assumptions for this story?

There are no fees for personal requests, so the states 'Fee Estimate' and 'On Hold' should not be options.

What is IN scope?
Remove 'Fee Estimate' and 'On Hold' on all personal requests.

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: No 'Fee Estimate' state for Personal request**
* GIVEN a ministry coordinator on a personal request
* AND the request is in a CFR state
* WHEN the coordinator clicks on the state dropdown
* THEN 'Fee Estimate' will not appear as a state

**Scenario 2: No 'On Hold"**
* GIVEN an IAO analyst is on a request
* WHEN the analyst clicks on the state dropdown
* THEN the 'On Hold' state will not appear

**Scenario 3: xxxxxx**
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
ccL @lmullane @arielleandrews @m-prodan

**Comment by lmullane** [comment]
@abin-aot, I believe scenario 2 will be fixed with scenario 1, correct?

As there is no 'On Hold' state unless a request is in 'Fee Estimate.'

cc @m-prodan, @arielleandrews

**Comment by m-prodan** [comment]
That would be correct. We may need to consider what is called a "pending section 5 hold state" - which would be more valuable if it was tracked separately than on hold generally, since one is related to fees and the other more having to do with eligibility.

Section 5 hold is more of a CFD/PSS/SDPR issue though - so I wouldn't worry about that state yet, but there will be a time when we need a kind of hold function (or we just keep a request under 'intake in progress' as some food for thought)

**Comment by lmullane** [comment]
@m-prodan, how about we cover section 5 as a separate ticket?

**Comment by arielleandrews** [comment]
Weighing in here, I agree section 5 pending should be covered as a separate ticket. The due date calculation follows a different logic than On Hold and I personally would like to create a bigger distinction between Section 5 Pending and On Hold. They are often conflated and this has caused confusion with our clients and even the OIPC.

**Comment by lmullane** [comment]
@divyav-aot, assuming this ticket passes QA, shall we include this one with the pilot release?

**Comment by divyav-aot** [comment]
yes @lmullane . We can include this as part of pilot release.

**Comment by mpilchar** [comment]
passes QA - great work @divyav-aot
