### ISSUE TITLE
Redirect AssignedTo shows Unassigned

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#1477]
Title of ticket: 

#### Current Behavior
Create a General Request
Click Open from state dropdown
Cancel the Modal
Click on Redirect
The modal shows AssignedTo as "Flex Team"
Click Save changes
The assignedTo in the review page shows "Unassgined"

#### Expected Behavior
Create a General Request
Click Open from state dropdown
Cancel the Modal
Click Redirect from state dropdown
The modal shows AssignedTo as Intake team member
Click Save changes
The assignedTo in the review page shows Intake team member

**Comment by m-prodan** [comment]
QA complete - issue appears to be resolved. Thanks @divyav-aot
