### ISSUE TITLE
Schedule first WG committee meeting

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#149]

**Comment by mpilchar** [comment]
@m-prodan I've added a task to keep working group related activity on the radar

**Comment by m-prodan** [comment]
Done and done - first meeting scheduled for July 7th - will place in progress while I prep and reconsider materials (may need to update my slideshow given the date I originally created it)

Next step - prepare slideshow and agenda, short 30 minute introductory meeting to determine cadence of formal WG meetings and set expectations for participants

**Comment by m-prodan** [comment]
Slideshow prepared, agenda set and sent - closing this issue now as we get ready for first meeting tomorrow.
