### ISSUE TITLE
UX Research Plan on Request Que

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#15]
- [x] 1-2 page UX Research Plan with research goals, tactics, and participants

**Comment by JHarrietha-AOT** [comment]
UX Research Plan - Intake Team - Sprint 0

[https://app.zenhub.com/files/358004325/bc0deb78-10c9-40a8-8a37-7df27af7aa9e/download](https://app.zenhub.com/files/358004325/bc0deb78-10c9-40a8-8a37-7df27af7aa9e/download)
