### ISSUE TITLE
Add BRD to processing team mapping 761

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1500]
BRD was missed in the initial breakdown for 761. BRD should be part of central team 
#761
#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Add BRD to Central Team ministries
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by nkan-aot** [comment]
@arielleandrews will confirm if we still need this ministry

**Comment by arielleandrews** [comment]
BRDO ceased to exist and is now CABRO which falls under Crown Agencies Secretariat under the Ministry of Finance - @divyav-aot do we need any changes to reflect this or are we good to close this ticket? cc @nkan-aot

**Comment by nkan-aot** [comment]
CAS already has its own checkbox so i believe this can be closed
