### ISSUE TITLE
Prototype Update - Fields updates we need to pull from AXIS

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1512]
Title of ticket: Prototype Update - Fields updates we need to pull from AXIS

#### Description
Updated designs & prototype to include all additional fields that we plan to pull from AXIS so we have somewhere to display info

#### Dependencies
- [x] List from @arielleandrews of fields 
- [ ] List from @abin-aot of fields he has identified that we are pulling from AXIS but do not have in front-end

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Thanks for sharing the screen shots, is there any fields in these that you do not think are required for MVP? @abin-aot Can you confirm if there are any fields listed above that you are not able to pull from AXIS

**Comment by arielleandrews** [comment]
@JHarrietha-AOT definitely. I think anything under the 'Open Information', 'Section 43 Information', 'Fee Waiver Requested', 'Fee Details', and 'Translation Requested' headings are not required for MVP - all the OI work will occur in AXIS so I don't think it's necessary to pull across into our app at this stage. We can also brainstorm if 'Link Requests' is required once we have the ministries canvassed link/modal built. Happy to have a chat through these on a call, and welcome your thoughts too @m-prodan
