### ISSUE TITLE
Get plug-ins for testing accessibility

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1513]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Run plugin
- [ ] Report out on results
- [ ]

**Comment by lmullane** [comment]
@divyav-aot , as discussed, devs to chat on effort.

**Comment by mpilchar** [comment]
@acoard-aot Checking that our app meets all accessibility requirements during last release planning. We discussed during refinement a need to possibly do this sooner than later, because it there are changes needed, we'll want to get them in during April. Do you have recommendations on how we go about this? Let's discuss

**Comment by mpilchar** [comment]
splitting this into two: 1) Research and determine plug in, 2) Run accessibilty testing

**Comment by lmullane** [comment]
Duplicate
