### ISSUE TITLE
Setup Liveliness, Readiness Probes for OpenShift for FOI-Flow (aka Health checks or probes)

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/foi-flow#1515]
Title of ticket:  Setup Liveliness, Readiness Probes for OpenShift for FOI-Flow

#### Description
Setup livelinessProbe, readinessProbe, etc, in the deployment-configs.yaml 

This task is related to the High Availability for FOI flow task.  No direct dependency too, but the features combine.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Probes in in API
- [x] Probes in web
- [x] If any redis/camunda probes, enable, but those are likely pre-configured and we can't do much.
- [x] Kibana
- [x] #427 FE App Readiness issue , can be covered ???

**Comment by abin-aot** [comment]
We might need to refer #427 as well while doing this - related to OC Readiness proble.

**Comment by mpilchar** [comment]
Completed during last sprint
