### ISSUE TITLE
High Availability For FOI Flow - Testing, OC Configuration

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#1516]
Title of ticket: 

#### Description
The purpose of this task is test and confirm all FOI Flow Functionalities under HA configuration (Prod alike) on TEST. 

#### Dependencies
Are there any dependencies?

### Assumptions

1.  Health Checks , Readiness Probe YAML DC updates will be on #1515

#### DOD
- [x] Plan for Production Resource Spec and apply on TEST OC ENV - CPU, Memory. 
- [x] Resource Planning - OCP
- [x] Update OC Deployment Configs for Multiple PODS/Replicas 2/3 Pods each . FE , API, Redis, Camunda
- [ ]  Storage as well
- [ ]

**Comment by mpilchar** [comment]
Did we confirm whether this would happen on the QA test region? @acoard-aot @sumathi-thirumani-aot @abin-aot

**Comment by mpilchar** [comment]
Closing this one. @sumathi-thirumani-aot now working on System Optimization
