### ISSUE TITLE
LOB API - Redis Queue Implementation for WF instantiation 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#152]
Title of ticket: 

#### Description
As part of design we decided to create a loosely coupled mechanism to trigger WF. this is planned to implement with Redis PUB-SUB . 

#### Dependencies
Are there any dependencies?
Redis

**Comment by JHarrietha-AOT** [comment]
@acoard-aot @divyav-aot @sumathi-thirumani-aot This can be pushed to closed once code review is complete along with technical tasks in review. Once any users stories are ready to review feel free to put in Ready to QA
