### ISSUE TITLE
Add and Sync a New Request from AXIS

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1535]
* As an Intake Analsyt
* I want to be able to sync data from AXIS when I open a request
* so that I can save time on data entry and ensure there is not duplicate requests

**Assumptions & Scope**	
What are the assumptions for this story?
- AXIS request ID is mandatory in request and in unopened state. AXIS request number will be shown on header

Intake will open the request in AXIS first as we cannot push data from the new system to AXIS

What is IN scope?
Creating a new requests in the new system and syncing the data with the request information in AXIS.

What is NOT in scope?
Syncing requests after the request is first opened. That is in a separate ticket: 
**Acceptance Criteria**	

**Scenario 1: Add a Request**
* GIVEN an Intake Analyst is on the queue:
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451
* WHEN the analyst clicks the 'Add Request' button'
* THEN a blank request will open with a mandatory 'AXIS ID Number' field and a 'Sync with AXIS' button
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/736503621

**Scenario 2: Sync With AXIS - invalid number **
* GIVEN the analyst has entered an invalid AXIS ID Number
* WHEN the analyst clicks the 'Sync with AXIS' button
* THEN an error message will be displayed in red: This ID number was not found

**Scenario 3: Sync With AXIS - valid number**
* GIVEN the analyst has entered a valid AXIS ID Number
* WHEN the analyst clicks the 'Sync with AXIS' button
* THEN the data will be synced
* AND then the analyst will remain on the request details view
* AND the fields all the request fields from AXIS will be filled (GENERAL: applicant details, address and contact information, date range, request description, ministry, additional request details; PERSONAL same fields as general and additional personal fields)

**Scenario 4: Save and Display AXIS number**
* GIVEN an analyst has synced to add a request
* WHEN the analyst clicks 'Save'
* THEN the request ID number from AXIS will be displayed a the top of the request view
* AND the AXIS request ID number will appear on the Queue

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team's backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
See #1314
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, @arielleandrews, @m-prodan, @abin-aot 

Please review the AC and advise if any changes are required.

cc
@mpilchar

**Comment by lmullane** [comment]
@abin-aot, what happens again if a request does not come through the online form and there is no raw request?

**Comment by JHarrietha-AOT** [comment]
@lmullane if a request is received by email, fax or mail then Intact can open it as usual in AXIS and follow scenario 1 with the AXIS request # to create it in out new system.

@abin-aot feel free to add if I'n wrong in that thinking

**Comment by abin-aot** [comment]
its the same @lmullane - Open in AXIS and add new request with AXIS Req. #

**Comment by abin-aot** [comment]
@lmullane  : This Story is specifically for Inflight requests which is already on AXIS when launch and/or Requests coming manually - paper / email - for those even it will get entered into AXIS first and then only FOI FLOW comes into picture

**Comment by lmullane** [comment]
As discussed, decision is not to lock editing on certain fields. Reason is that there may be connection issues with the legacy system.

Removed this clause from Scenario #:

* AND the Applicant Details, Contact Information and Request Description will not be editable

**Comment by JHarrietha-AOT** [comment]
Adding an additional assumption after talking to the dev teams. AXIS request ID will be a required field and users will be unable to save a request before they input the AXIS ID to ensure they are creating the request there first

**Comment by lmullane** [comment]
Worked as expected.
