### ISSUE TITLE
Load raw requests to test env

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#1539]
Load bulk data into test environment

**Comment by richard-aot** [comment]
@arielleandrews, I have a small task to load bulk requests to test environment, so we can test the new system with more data. Do you have any suggestions on how many requests that I should add? Thanks.

I created some scripts to load "Intake in progress" requests and added 100 records for now.

**Comment by arielleandrews** [comment]
@richard-aot I just checked and between our 5 pilot ministries they have 60 open requests total right now, so 100 is sufficient to test what the load will be like for the pilot active requests only. Across all IAO clients, there are 2800 open requests. I leave it to your discretion what load level we need to test at this stage!

**Comment by richard-aot** [comment]
Thanks for the information @arielleandrews. I will add more requests next week.
