### ISSUE TITLE
Cannot assign to team in unopened stage

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1545]
If request is in unopened stage, if user selects a team as assignee (i.e. intake team) save will fail. This is because db is trying to insert into to foiassignees table null foreign keys since team has no username

**Steps to Reproduce**
Submit request
log in as iao user
open request, fill out required fields, select "intake team" as assignee
try to save

**Actual/ observed behaviour/ results**
unable to save

**Comment by lmullane** [comment]
@sumathi-thirumani-aot, assume the expected behaviour is that you can follow the steps and 'save' the request in Unopened state?

**Comment by sumathi-thirumani-aot** [comment]
Yes. We had a bug on unopened request couldn't be saved with team name
only.

**Comment by lmullane** [comment]
Ok, the save is not working for me. Possibly a caching issue.

**Comment by lmullane** [comment]
@sumathi-thirumani-aot, the fix isn't working for me. I tested in incognito windows and still unable to save when assigned to the Intake team.

I'm using the Intake user.

<img width="476" alt="Screen Shot 2022-02-22 at 3 14 18 PM" src="https://user-images.githubusercontent.com/12040839/155236195-25e8a1a6-5030-4b6f-acbd-6fe1d2ae2a13.png">

**Comment by lmullane** [comment]
I checked again and I am still unable to save a request in Unopened that is assigned to the Intake Team.

Putting back to In Progress.

cc @sumathi-thirumani-aot

**Comment by arielleandrews** [comment]
Tested on requests submitted through the webform and using the Add Request button - both scenarios passed, bug appears to be fixed. Nice work @divyav-aot!
