### ISSUE TITLE
Days Remaining to LDD - Not Displaying in Left Hand Nav for IAO Users

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1547]
**Describe the bug in current situation**
While testing features, I was observing that IAO users can no longer see days remaining to the LDD on the left hand nav panel

UPDATE : Confirm this has been fixed with #946 , @arielleandrews 

**Link bug to the User Story**
#354

**Impact of this bug**
IAO Users Can not See days remaining at a glance anymore when viewing a request

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Appears any request in the open state, when viewed by an IAO user role, can not see days remaining. Issue can not be replicated with a Ministry user. 

**Steps to Reproduce**
1. Go to any request in the open state or later as an IAO user (Flex, Intake, Processing)
2. Look at Left hand Nav panel
4. Days remaining will not be visible

**Actual/ observed behaviour/ results**

**Expected behaviour**
- GIVEN ... I am on the queue screen and have clicked on any request with  ​and Status: Open or later
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451
- WHEN ... I am taken to the review request information screen for open or later request
- THEN ... left side bar will say "xx days remaining" at the bottom
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932505

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/88b272c2-0e91-4104-ad09-f9c32ce32b4b)

**Comment by lmullane** [comment]
Can we confirm this is only once there is an extension?

**Comment by lmullane** [comment]
@arielleandrews, as discussed please check  if this is still an issue after #946 is in TEST.

**Comment by abin-aot** [comment]
As per @jadmsaadaot  - this is ready for test with #946

**Comment by JHarrietha-AOT** [comment]
Ready for QA

**Comment by arielleandrews** [comment]
This bug is fixed and is working as expected again, tested with ticket #946
