### ISSUE TITLE
Merge Automated Tests into dev for test run on dev server

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1549]
Make first PR for automated tests so we can run tests in dev and see if they work

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Merge
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by nkan-aot** [comment]
@acoard-aot tagging you so you know when this gets through

**Comment by lmullane** [comment]
Post pilot launch.
