### ISSUE TITLE
Set Up PROD - FOI Flow

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1552]
Title of ticket: 

#### Description
The purpose of this task is to set up PODS/OC for FOI FLoW. FOI reporting  OC is on other tasks

#### Dependencies
Are there any dependencies?

#### DOD
- [x]  Webfront
- [x]  Request Managment API
- [x]  Patroni
- [x]  Camunda - BPM
- [x]   Redis
- [x] Back up container - DBs
- [x] Keycloak Setup
- [x] HA
- [x] Deploy delta changes

**Comment by mpilchar** [comment]
bumping to next sprint because we prioritized patroni work

**Comment by sumathi-thirumani-aot** [comment]
1. Redis message broker setup completed.

**Comment by sumathi-thirumani-aot** [comment]
2. Redis cache setup completed

**Comment by sumathi-thirumani-aot** [comment]
camunda client has been setup in KC

**Comment by sumathi-thirumani-aot** [comment]
web client has been setup in KC

**Comment by acoard-aot** [comment]
New patroni instance (patroni-002) has been created and Camunda has been initialized using it.
