### ISSUE TITLE
Banner warning the request is out of sync

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1559]
* As an IAO analyst
* I want a banner at the top of a request to notify me that the request is out of sync with AXIS
* so that I know if I need to sync the request

**Assumptions & Scope**	
What are the assumptions for this story?
This will be pulled from the AXIS API.

What is IN scope?
A banner on the request view.

What is NOT in scope?

Viewing the actual changes. That is covered in #1540

There will be no banner on the Comments or Attachments view.

Ministry coordinators will not see a banner.

**Acceptance Criteria**	

**Scenario 1: View banner**
* GIVEN an IAO analyst is on a request view
* WHEN changes have been made to the request details, extensions, or LDD on the request in AXIS
* AND those changes have not be updated in the flow app
* THEN a banner will appear at the top of the page with the notice changes have been made in AXIS: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852
* AND the banner will be mustard yellow (see design)
* * AND the last synced date will be displayed on the right of the banner

**Scenario 2: No banner**
* GIVEN an IAO analyst is on a request view
* WHEN NO changes have been made to the request details, extensions, or LDD on the request in AXIS
* THEN a banner will not appear at the top of the page and the "SYNC WITH AXIS" button will be disabled

**Scenario 3: No connection with AXIS**
* GIVEN an IAO analyst is on a request view
* WHEN there is a connection issue with AXIS
* THEN a banner will appear at the top of the page
* AND there will be a warning message informing the analyst that there is no connection
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/775202206
* AND the banner will be orange (see design)
* AND the last synced date will be displayed on the right of the banner

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
Need a design

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@sumathi-thirumani-aot. @abin-aot, @m-prodan, please review the AC.

cc @JHarrietha-AOT, @mpilchar, @arielleandrews

**Comment by JHarrietha-AOT** [comment]
Not sure who came up with the idea, but its great. 
I will add this to the designs. 

@m-prodan @arielleandrews Do you think it would be helpful to have a Go Banner (ie. in green showing the date/time this request was last synced and that is last up to date) And a warning banner (ie. in yellow showing the last time/date the request was synced and that it is out of sync with AXIS)? Just an idea, totally okay if we just want to go with the warning banner, was wondering if it is useful for users to know that last time and/or date the request was synced with AXIS

**Comment by lmullane** [comment]
Full credit to @sumathi-thirumani-aot for the idea.

Good idea to include the last time and date a request was synced. I'm not sure that needs to be a banner though, as the banner should be a clear visual that an action should be taken. Welcome the discussion though.

**Comment by JHarrietha-AOT** [comment]
It absolutely felt like a @sumathi-thirumani-aot idea, she always thinks of great things to add. Sounds good. I'll do a draft design and post for here for people to share input on.

**Comment by lmullane** [comment]
Super. Thanks, @JHarrietha-AOT

**Comment by m-prodan** [comment]
Yeah I think just the warning banner when out of sync should suffice. Should we also trigger a system generated comment (but no notification) for this one too?

**Comment by JHarrietha-AOT** [comment]
I think notifications could get a bit out of hand with this. Kind of goes back to users saying they want notifications for important things. It is likely they will be the ones in AXIS making the change I worry it could overwhelm them if we send a notification every time it is out of sync.

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan Should the warning banner show for both IAO and Ministry users? It if shows to both it would increase transparency and accountability for IAO to keep it up to date and so Ministry users know

**Comment by arielleandrews** [comment]
I think no comment or notification personally - there are already so many comments and they will become out of date quickly (ideally) so I don't think the comment adds value.

Re the banner showing for Ministry users - my only concern would be Ministry users contacting IAO to sync after they have made a change and expecting instant follow through. But otherwise transparency is a good thing!

**Comment by JHarrietha-AOT** [comment]
@lmullane @arielleandrews @m-prodan I have attached screenshots below of the proposed designs for the banners. Let me know what you each think. 

![Ministry Banner.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/a88bf67d-9de8-4a6f-8c8e-516255bf3aff)

![IAO Banner.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/d4213b54-26f4-425d-a673-28a47e2e4667)

I am wondering if from a technical perspective we can have the IAO Banner show up right away, and have the Ministry Banner show up after a set amount of time if we are worried about Ministries following up with IAO to frequently. 
To come at it from the other side, the goal of our app is to increase transparency and accountability, by having it show up right away for Ministries it would push IAO to sync the request right after changes which would make our pilot function better. Just wanted to give two options.

**Comment by m-prodan** [comment]
Banners look good! I don't know how much the banner will create issues for us, but knowing that processing team analysts will largely be working out of AXIS, I think it's probably a good idea to ensure the Ministries see the banner too. I don't know if a time delay is worth the dev effort, I think it might be fine in real time.

**Comment by JHarrietha-AOT** [comment]
Based off of conversation in stand-up Feb 22nd, we will move forward with banner for IAO and not for Ministries. We will wait and see if having the banner for IAO is enough for IAO to do the sync with AXIS in a timely manner, if we discover that IAO is letting the request details sit outdated for longer then desired we can then look at moving forward with an extra step to encourage the sync to happen in a timely manner.

**Comment by lmullane** [comment]
Thanks, @JHarrietha-AOT. The banner looks great.

**Comment by lmullane** [comment]
@divyav-aot I've updated the AC as discussed, guided by @JHarrietha-AOT designs.

**Comment by lmullane** [comment]
Waiting for bug fix #1836

**Comment by m-prodan** [comment]
The banner appears to work, in scenario 1 and 2 - but I don't know how I can test scenario 3. Perhaps I can set some time aside where we temporarily break the link to AXIS? Ideas for this? @divyav-aot @aparna-aot ?

**Comment by aparna-aot** [comment]
@m-prodan Yeah we can set some time aside to temporarily break the link to AXIS and test that scenario. We have tested in DEV like that. Shall we do that on Monday morning as @divyav-aot will be available then?

**Comment by m-prodan** [comment]
Sure - let's aim for early in the morning. I'll message Divya when I am online

**Comment by aparna-aot** [comment]
Sounds good @m-prodan .

**Comment by lmullane** [comment]
@divyav-aot and @m-prodan do coordinate on testing scenario 3.

**Comment by m-prodan** [comment]
QA scenario 3 has now passed - all scenarios passed, closing ticket.
