### ISSUE TITLE
Suggestion to always show the result count in grid widgets (dashboard & search)

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#1565]
Currently, the system does not let the user know the total no. of records in system through dashboard and search screens. It will be nice to have the total numbers displayed.

**Comment by JHarrietha-AOT** [comment]
@sumathi-thirumani-aot This will be shown in reporting as it would not be required for users who are trying to organize there daily work and tasks that need to be complete using the queue. 

Let me know if you think differently @m-prodan @arielleandrews @lmullane

**Comment by m-prodan** [comment]
I assume this is related to #1530? I've put my comments there on this particular issue.

**Comment by KyEggleston** [comment]
Related to #1530, and # of search results has already been implemented on Advanced Search - total number of requests (without any search criteria) can be generated through the reporting app. Closing request
