### ISSUE TITLE
Reply from watcher to assignee should appear in assignee's 'My Notifications' log

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1567]
**Describe the bug in current situation**

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by abin-aot** [comment]
as promised during meeting, kindly check if its possible to fix in this sprint. thanks

**Comment by arielleandrews** [comment]
@sumathi-thirumani-aot can you please add an estimate to this bug. QA is completed and this is working great! I will close once there is an estimate. Awesome job.
