### ISSUE TITLE
Missing author name on notifications in Dashboard View 

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#1569]
**Description:**
This task is meant for fixing the issue mentioned by @JHarrietha-AOT in #906 i.e.. author name missing in notifications when viewed from dashboard. The issue was caused by the latest updates in dashboard.

**DOD:**
- [x] Fix the issue

**Steps to Reproduce:**
Login as IAO user.
From the dashboard view, open notifications

**Actual Behavior:**
Author names are missing on the notifications.
**Expected Behavior:**
Each Notification should show the respective author names on the left side after a few seconds. (The issue of showing names only after few seconds will be addressed in #455).

**Comment by aparna-aot** [comment]
This issue is fixed. However there is a tech debt related to this task which will be addressed as part of #455 . 
Tech Debt: Author names on notifications take some time to display on the initial load while in Dashboard view.

**Comment by lmullane** [comment]
@aparna-aot, was this fixed as part of #906?

**Comment by aparna-aot** [comment]
@lmullane Yeah. @JHarrietha-AOT mentioned this bug in #906. And since the ticket is already closed and also the issue existed for all notifications(push and pull), I separated the task.

**Comment by arielleandrews** [comment]
Closing this bug ticket as issue has been fixed - estimated effort captured in #946 and #455. Nice work @aparna-aot
