### ISSUE TITLE
Send extension notification after sync with AXIS

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1571]
* As an IAO anaylsy
* I want an in-app notification automatically sent to assignees and watchers when I sync a request with AXIS that has an updated extension
* so that all assignees and watchers are aware of the extension

**Assumptions & Scope**	
What are the assumptions for this story?

Assumption is no adiditional development work is required. This is story is only for testing purposes.

What is IN scope?
Testing the functionality works as expected.

What is NOT in scope?
Sending notifications and syncing with AXIS.

**Acceptance Criteria**	

**Scenario 1: Send extension notification after sync with AXIS**
* GIVEN an request has a new extension added in AXIS
* WHEN the IAO analyst syncs the request in the new app with AXIS
* THEN notifications for the new extension will appear in the 'My Notifications' and 'Watching Notifications' for users who are assignees or watchers of the request.

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
cc @abin-aot

**Comment by divyav-aot** [comment]
updated the effort as we had some dev changes to save bulk extensions from AXIS

**Comment by lmullane** [comment]
Confirmed that both the watcher and assignee are notified when an extension is synced.
