### ISSUE TITLE
Analysis of Natural Resource common email service

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#158]
#### Dependencies
precursor to #139 (set up SMTP server)
- communication with service owner

#### DOD
- [ ] Analysis
- [ ] Report to team whether this is a worthwhile service to use
- [ ]  Check whether there is an inbound as well outbound email service
- [ ]  Check whether there are any **onboarding process for our project**, contact points, SLA, security
- [ ]  Decision by PO
https://digital.gov.bc.ca/common-components/common-hosted-email-service

**Comment by mpilchar** [comment]
I've confirmed with the team that built CHES that best way to reach out with any questions is via Rocketchat: https://chat.developer.gov.bc.ca/channel/nr-common-services-showcase

**Comment by abin-aot** [comment]
Initial/Current assumption : this service does only sending email. 
we might need to understand the onboarding steps to get into this service
