### ISSUE TITLE
Certain IAO Users Unable To Filter to 'My Requests'

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1596]
**Describe the bug in current situation**
Certain IAO user groups are not able to filter to 'My Requests'

Notable exception includes Intake - however they can only see requests assigned to them in 'Intake in Progress'

**Link bug to the User Story**

**Impact of this bug**
Users will be unable to see their own work from their teams

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to any request in flex team, or processing team queue
2. Click on Assign request - assign to self within that user group
3. Click on filter to "My Requests"
4. Results will return no rows

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN a user is assigned to a request
WHEN they click on the filter button 'My Requests'
THEN all requests assigned to the user that are not closed will appear in their queue

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by mpilchar** [comment]
This may impact training on March 3

**Comment by lmullane** [comment]
@richard-aot, could we put an estimate on this bug?

**Comment by lmullane** [comment]
Working as expected. Just need an estimate on this ticket and then it can be closed.

**Comment by richard-aot** [comment]
Thanks, @lmullane. Just added estimation.
