### ISSUE TITLE
System is generating comment from unopened to intake, but not for intake to open

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1607]
System is generating comment from unopened to intake, but not for intake to open

**Impact of this bug**
all users impacted

**Chance of Occurring (high/medium/low/very low)**
high

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
-submit request
-fill out form, change to intake in progress
-save, then change to open
-click on comments in sidebar

**Actual/ observed behaviour/ results**

![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/2faf60e2-f798-4cd9-9d01-53afa71c15ec)

**Expected behaviour**
should have a comment for intake to open instead of unopened to intake, as per ac in issue #802

**Comment by nkan-aot** [comment]
@abin-aot @sumathi-thirumani-aot

**Comment by JHarrietha-AOT** [comment]
Comment now generated when Requests moved from "Intake in Progress" to "Open." Great work, moving ticket to closed
