### ISSUE TITLE
Respond to easyretro questions from Branch meeting

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1618]
Title of ticket: 
https://easyretro.io/publicboard/q9M7gyrDyHdIVFgeMBYHjCVqo9w2/6ed811c4-44bb-4fdc-9da8-3375020b8297

#### DOD
- [ ] Draft responses
- [ ] Email IAO all

**Comment by mpilchar** [comment]
@lmullane The majority of Q's that came through are related to future product dev by the looks at it. Would you like to take a run at responding as PO?

**Comment by mpilchar** [comment]
Do we still need to respond to these @lmullane? I appreciate you're going on holidays tomorrow so if we do and want to reassign this, please let me know

**Comment by lmullane** [comment]
Yikes. Thanks for the reminder, @mpilchar. Could you take a crack at response?
