### ISSUE TITLE
Ministry lead save a request assignee without doing divisional tracking

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1624]
* As a ministry team lead
* I want to be able to assign a team member and save the assignee without selecting a division
* so that my team member can do the analysis on what divisions need to respond

**Assumptions & Scope**	
What are the assumptions for this story?
Currently a ministry coordinator cannot save a request without filling out 2 mandatory fields: 1 an assignee; 2 at least 1 division tracked).

Team leads want to assign work and not do the analysis of which divsions should be engaged.

What is IN scope?
Make division tracking not mandatory.

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Save request **
* GIVEN an assignee has been assigned
* WHEN a ministry coordinator clicks Save
* THEN the request will be saved

**Scenario 3: **
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, @arielleandrews, @JHarrietha-AOT, should we make adding at least one division mandatory to save a request a second time, or do we make this no longer mandatory?

cc @abin-aot

**Comment by m-prodan** [comment]
Good question - I think there may be an argument to make that it may not need to be mandatory at all. There could be a request some day that clearly belongs to another Ministry, and the coordinator may not assign it to a division and instead just ask for a full transfer. Perhaps in a case of moving from CFR to fees, dedupe or records review... that may at least necessitate divisional tracking to justify. But I wouldn't prioritize that for MVP - it may be something to keep an eye on.

**Comment by m-prodan** [comment]
AC on this one has been met - I was able to replicate this regularly during training yesterday. Closing ticket
