### ISSUE TITLE
Browser back button not worknig

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1626]
**Describe the bug in current situation**

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Use Chrome
2. Go to 'a request view, attachment log or comment log
3. Click on '.the Browser back button..'
5. See error - the user remains on the request view

1. Use Edge
2. Go to 'a request view, attachment log or comment log
3. Click on '.the Browser back button..'
5. See error - the user is automatically logged out (need to replicate)
**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN the user is on a page in the applicaition
WHEN the user clicks the browser back button
THEN the user should be returned to the previous page they were on

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by jadmsaadaot** [comment]
@lmullane I was not able to reproduce this issue on chrome, edge, or firefox. The browser back button works fine on my end. Could this happen on only on a specific OS. @divyav-aot  @abin-aot would you be able to reproduce this issue on chrome or edge?

**Comment by lmullane** [comment]
@jadmsaadaot, could you please add an estimate to this ticket.

**Comment by jadmsaadaot** [comment]
@lmullane done, thank you.

**Comment by m-prodan** [comment]
Works as expected - nice one @jadmsaadaot
