### ISSUE TITLE
Display applicant details for Ministry on Personal requests

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1634]
* As a ministry user
* I want to see the applicant details on a personal request 
* so that I can search for and locate the correct records 

**Assumptions & Scope**	
* These fields will be displayed in addition to the fields already displayed to the Ministry
* Displayed information will be read only
* This will apply to Personal requests only. General requests will continue to have all applicant personal information hidden on the Ministry display
* Address and Contact Information for the applicant should not be displayed. This information is not required to locate records
* Blank fields will not display at all
* Ministry users will be able to view this information when the request is in any state

What is IN scope?
* Displaying the fields within the following sections to the Ministry: Applicant Details, Child Details, On Behalf Of Details, and Additional Applicant Details

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Ministry User views Personal request applicant details**
* GIVEN a Ministry user is logged in
* WHEN they click in to view the request details of a Personal request 
* THEN the information regarding applicants in the following sections will be visible to them: Applicant Details, Child Details, On Behalf Of Details, and Additional Applicant Details
* AND the information will be read only 

**Scenario 2: IAO user updates Personal request details**
* GIVEN an IAO user has made changes to any of the applicant detail fields in the following sections: Applicant Details, Child Details, On Behalf Of Details, and Additional Applicant Details
* AND the IAO user clicks Save
* WHEN the Ministry user views the request details of that Personal request 
* THEN the information will be updated with the changes
* AND the information will be read only 

**Scenario 3: Move email from Applicant Details to Contact Information**
* GIVEN I am any user 
* WHEN I  go to Request Details page
* THEN email address will be displayed under contact information, as opposed to Applicant Details

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
@m-prodan @lmullane @mpilchar Please review and suggest any changes

@JHarrietha-AOT I'm wondering if it would make sense to move the applicant email into the "Address and Contact Information" section of the request details page. I've written this story so the applicant contact information is still hidden from the Ministry and moving their email into that section would make it consistent. Open to anyone's thoughts on this!

**Comment by m-prodan** [comment]
I've reviewed - this looks right to me. I just made a slight edit to specify applicant request details instead of request details more generally. 

cc @lmullane @JHarrietha-AOT @abin-aot

**Comment by mpilchar** [comment]
I'm moving this back to Issues Backlog because it does not appear to have an estimate

**Comment by mpilchar** [comment]
@JHarrietha-AOT will create a mock up showing the fields that will be displayed; email will be moved from applicant details to contact information

**Comment by JHarrietha-AOT** [comment]
Ministry View Updated: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/813687578
Applicant View Updated: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932505

**Comment by lmullane** [comment]
All AC passed as expected. Good work, @jadmsaadaot
