### ISSUE TITLE
Remove no personal information checkbox on request description for Personal requests

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1635]
* As an Intake analyst
* I want to be able to include personal information in request descriptions for personal requests 
* so that the request is accurately captured and the Ministry can locate the records requested

**Assumptions & Scope**	
* Request descriptions for Personal requests will often contain personal information as this is required to locate the records requested
* Ministry users will need to see the full request description complete with personal information in order to fulfill a Personal request, and any subsequent changes to the request description in the Description History
* Request descriptions for Personal requests are not published so there is no need to protect personal information in the same way as General requests
* The "Description contains NO Personal Information" checkbox should continue to function as is for General requests

What is IN scope?
* Removing the "Description contains NO Personal Information" checkbox for Personal requests only

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Personal request from webform in Unopened state**
* GIVEN an Intake analyst is logged in
* WHEN the analyst clicks on a Personal request in Unopened state 
* THEN the "Description contains NO Personal Information" will not be visible
* AND the analyst will be able to save the request once all other mandatory fields have been inputted 

**Scenario 2: Use Add Request button for Personal request**
* GIVEN an Intake analyst has clicked the Add Request button to create a new request
* WHEN the analyst selects Personal as the request type  
* THEN the "Description contains NO Personal Information" will no longer be visible
* AND the analyst will be able to save the request once all other mandatory fields have been inputted 

**Scenario 3: Ministry Users able to view full description history for Personal requests**
since personal requests no longer require redaction of personal info, ministry users should be able to view full history of personal request descriptions even if IAO user has made edits to the description before sending to CFR stage
* GIVEN a personal request is submitted from online form with request description
* AND IAO user has made edits to request description during Unopened stage
* AND request is now in CFR stage
* WHEN ministry user opens the request to review  
* THEN the "Description History" is clickable
* AND a popup comes up showing full history including original description from online form 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
@lmullane @m-prodan @mpilchar @JHarrietha-AOT please review when you have time and let me know your thoughts

**Comment by mpilchar** [comment]
Validation will be needed. Estimate of 3

**Comment by nkan-aot** [comment]
@arielleandrews as per discussion ministry users will now be able to see full history for personal request descriptions

**Comment by m-prodan** [comment]
All AC passed - nice job @nkan-aot
