### ISSUE TITLE
Executive Briefing for Production Approvals

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1636]
Title of ticket: 

#### Description
Per release planning - we need to ensure we have executive approval from our respective pilot Ministries to proceed with the pilot. This will require a BN/Decision note

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Discuss preferred options with pilot Ministrys (Economy + EDU)
- [ ] Confirm same for CITZ/IAO
- [ ] Draft necessary briefing material for respective Ministries
- [ ] PO Approval on Draft
- [ ] Submit to Ministries for Approval

**Comment by mpilchar** [comment]
Duplicate with #2126 - closing
