### ISSUE TITLE
Browser back button click shows alert only once

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#1640]
**Describe the bug in current situation**
The browser back button shows alert when there is a change in the review page. If you press cancel and click the back button again then it goes back to the previous page. Ideally it should show the alert again.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to IAO/Ministry review page
2. Update any field
3. Click on browser back button
4. The Alert shows
5. Click cancel
6. Click on browser back button again

**Actual/ observed behaviour/ results**
Loads the Dashboard.

**Expected behaviour**
The alert should show again.

**Screenshots/ Visual Reference/ Source**
first time shows alert
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/fbd67433-91b0-4c2b-8259-cb0abde57613)
second time goes back to dashboard
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/0eb1dedb-36a3-47cc-81e1-b7d91448f84a)

**Comment by m-prodan** [comment]
Bug appears to be resolved - prompt shows up after multiple back attempts. Closing ticket.
