### ISSUE TITLE
Closed request is showing in IAO user queue

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1645]
**Describe the bug in current situation**
Closed request is showing in IAO user queue

**Link bug to the User Story**

**Impact of this bug**
medium - goes against ac, does not prevent users from using the system

**Chance of Occurring (high/medium/low/very low)**
high

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
- create a request
- login as any IAO user (processing, intake, flex)
- move to open stage
- close, note the request id
- return to queue
- search for request in queue (not advanced search)

**Actual/ observed behaviour/ results**
closed request shows up

**Expected behaviour**
closed request should not show up

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/e8bda921-1fcb-4614-a079-4ee41c6cf476)

**Comment by JHarrietha-AOT** [comment]
Tested as IAO Intake, Flex Team and Processing Team. Closed no longer appears in any queues. Great job. Moving Bug to closed
