### ISSUE TITLE
Redirect Reasons

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#166]
Title of ticket: Redirect Reasons

#### Description
Organize and categorize the list of redirect reasons provided by Gitta and Patrick

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Create word doc with provided list
- [x] Work with SME to categorize provide reasons
- [x] Work with SME to reduce list down

**Comment by JHarrietha-AOT** [comment]
@m-prodan Here is the start of the redirect reasons list. I highlighted things that are common between the two but am also wondering if I have captured all the sub-options for the reasons. (ie, list of school districts or relevant cities)

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews 

Here is a link to the doc for quick reference: https://teams.microsoft.com/l/file/2D640FDB-B90E-4AED-9B5F-65A0B6707FDA?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FRedirect%20Reasons.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by m-prodan** [comment]
@arielleandrews and I have reviewed and left some comments. Given that we have QA and report out on the horizon, lets aim to connect next week about it. We have some ideas on how we can better pare down this list, or make the templates less complicated/busy.

Thanks for putting this together!

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Do you think we can move this to closed? Based off of the conversation we had yesterday, With the potential that redirect reasons could be revisited after the first release and feedback from IAO

**Comment by arielleandrews** [comment]
@JHarrietha-AOT I think so yes - it would require revising the DOD to remove feedback from Patrick and Gitta though - maybe discuss at standup or retro on Tues?

**Comment by JHarrietha-AOT** [comment]
@arielleandrews based off of meeting July 29th we discussed and finalized these Redirect Reasons for our Q3 release

Quarter 3 Release 

Health Authorities 

Police Records – RCMP or Municipal 

Municipalities or Regional Districts 

Federal Government 

Crown Corporations 

Large Universities 

Other

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Based on our conversations I have added a task to the backlog  #279 to ensure we follow up on how the 6 redirect reasons is working for intake and what feedback and changes they have. With the creation of this task I will close this issue
