### ISSUE TITLE
Fix Bug in reconcilePublicHoliDays

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/foi-flow#1662]
The issue happened when add 30 business days from "2022-03-04" happened. The result was "2022-04-18". 2022-04-18 is public holiday according to the DayJS getPublicHoliDays method so it should have added 1 more business day and returned 2022-04-19 instead of 2022-04-18.

**Comment by mpilchar** [comment]
@jadmsaadaot It may be worthwhile connecting in with @m-prodan and @arielleandrews on some of the other calendar/date related bugs to understand if anything is linked. I noticed some date bugs during Training and Matt noticed one during a demo given today

**Comment by jadmsaadaot** [comment]
@mpilchar, @m-prodan any chance you remember the above mentioned bugs? Would definitely be useful to know

**Comment by jadmsaadaot** [comment]
To test this Task, While adding a new request, after specifying the start date, check that the due date has correctly factored in holidays and weekends.

**Comment by JHarrietha-AOT** [comment]
Date is now being calculated correctly factoring in Easter Monday Holiday. Closing Ticket
