### ISSUE TITLE
Link to reporting app

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1664]
* As a ministry coordinator or IAO analyst
* I want a link in Flow for the Reporting app
* so that I can navigate from the Flow app to Reporting without needed to login again

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?
Navigation from Flow to Reporting app. 

What is NOT in scope?
Navigation from Reporting app to Flow. 

AC should cover the SSO but this work as already been done in another task.

**Acceptance Criteria**	

**Scenario 1: Link to Reporting app**
* GIVEN a ministry coordinator or IAO analyst is logged into the Flow app
* WHEN the user is on any page in FLOW
* THEN there will be a Reporting icon on the top navigation bar 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445060/play

**Scenario 2: Navigate to Reporting app**
* GIVEN a ministry coordinator or IAO analyst is logged into the Flow app
* WHEN the user clicks the 'Reporting' icon
* THEN a new window will open in the browser with the Reporting homepage (https://foi-flow-reporting-c84b95-test.apps.silver.devops.gov.bc.ca/)
* AND the user will automatically be logged into the Reporting app

**Scenario 3: Navigate to Flow app**
* GIVEN a ministry coordinator or IAO analyst is logged into the Reporting app (session is active)
* WHEN they load the Flow app into a browser window
* THEN the user will automatically be logged into the Flow app
* AND the user will be on their Queue

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@abin-aot, please review the AC.

@JHarrietha-AOT, As discussed, we will need a design.

**Comment by JHarrietha-AOT** [comment]
Added to the top nav with icon. Considering all other text in top nav is the user name and the Sign Out which is more important I opted for an icon. 
Let me know if you have any questions

![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/a93e3a0b-2cc5-495f-90f4-fb12e1991f5f)

Icon: https://fontawesome.com/icons/chart-column?s=solid

**Comment by lmullane** [comment]
I'm a fan of icons. One thought is in future we will need a nav bar item where a team admin can navigate to actions such as managing their team members, and for ministries, updating their division names.

How would additional nav items fit into the design?

**Comment by JHarrietha-AOT** [comment]
@abin-aot Here is the design just an icon in the nav bar

**Comment by mpilchar** [comment]
Pass! Nice work @abin-aot
