### ISSUE TITLE
Divisional Tracking Triggering Save Change Prompt

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1669]
**Describe the bug in current situation**
When a Ministry coordinator first goes into a file, and sets themselves as assignee, and then attempts to add multiple divisions - each additional division added will generate a save change prompt. If the user clicks OK - the page refreshes and all changes are lost, if they hit 'Cancel' they are able to continue. 

**Link bug to the User Story**

**Impact of this bug**
Users will get confused as to why the prompt goes up, if they press OK they will lose all changes

**Chance of Occurring (high/medium/low/very low)**
High - many requests go to more than one division

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to an unassigned request in Call for Records as a Ministry User
2. Click on Assigned to - and select self
3. Scroll down to Divisional tracking, and attempt to add a divsion
4. Save change prompt should appear for each subsequent division added.

<img width="1154" alt="Screen Shot 2022-03-14 at 10 21 00 AM" src="https://user-images.githubusercontent.com/12040839/158226329-7d3d4a3f-b197-4a00-b115-afcb10e4bfe6.png">

**Actual/ observed behaviour/ results**

**Expected behaviour**
Save change prompt should not appear as the user is not navigating away from the page.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
@divyav-aot , check to see if this is fixed after #762 .

**Comment by JHarrietha-AOT** [comment]
Bug is fixed and working as expected without prompting user to save after each division is added. Testing on EDUC and ECON Ministry log in. Moving to closed
