### ISSUE TITLE
Review of Redirect Letters/Email

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#167]
Title of ticket: Review of Redirect Letters/Email

#### Description
Levels of review and changes requested at each level of review
#### Dependencies
Creation of letters #90

#### DOD
- [x] Review by SME and PO
- [x] Completion of any changes requested

- [x] Review by Patrick and Gitta and Leads of Intake Team
- [x] Completion of any changes requested

- [x] Review by Template Team
- [x] Completion of any changes requested

- [x] Review from Kris and Cindy
- [x] Completion of any changes requested

**Comment by JHarrietha-AOT** [comment]
**DRAFT 1**

Here is the first draft of the re-design of the redirect letter/email. Core difference is letter has header and footer with contact info, email has signature with contact info. And I have added titles for content to be easier to find. I designed these as examples, so anything in orange is what would be auto-populated based off of what is selected.

Email: https://teams.microsoft.com/l/file/ECA6AA0D-76BF-4B29-8A8C-3879655BC8DB?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FTemplates%2FNEW%20Email%20Templates%2FProposed%20-%20Redirect%20Email.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

Letter: https://teams.microsoft.com/l/file/5AE076A7-98B1-4627-9D70-11646732D606?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FTemplates%2FNEW%20Letter%20Examples%2FProposed%20-%20Redirect%20Letter.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

Here is the start of the excel with the different options and the text for each, included what was originally provided and what I have changes: https://teams.microsoft.com/l/file/327608AA-011C-44C9-AF85-B325C3325F31?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=xlsx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FTemplates%2FTemplates.xlsx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by JHarrietha-AOT** [comment]
@m-prodan Links are listed above, please review whenever you have time. Thanks

**Comment by m-prodan** [comment]
They look good @JHarrietha-AOT - just one item of note, intakes email address is IAOIntaketeam@gov.bc.ca - I fixed it on the email, but I might have made a mess of the footer in the letter :) - so once thats updated I think we can close this one!

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan I have updated the letters & emails based on your last round of feedback. I know you busy today with steering committee prep, just wanted to let you know they're ready to review when you have a chance

**Comment by m-prodan** [comment]
Just made one final comment on the letter/email - assuming that is all that needs to be reviewed in this ticket? I am giving a quick scroll through the excel sheet as well, and can update here when I am done @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
@m-prodan thanks, I have paused working on the excel just waiting until we have the finalized top redirect reasons. Figured it would be better to wait than take the time to copy them all in. I will look at your comment have any updates done before stand-up tomorrow.

**Comment by JHarrietha-AOT** [comment]
I have made the changes suggested by @m-prodan and @arielleandrews, @mpilchar  if you have time today to review as well just for another perspective before we move forward that would be great!

**Comment by mpilchar** [comment]
@JHarrietha-AOT super clean and great use of linking in info. No changes from me

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews @mpilchar wondering if we feel confident in where these are at and are ready to check off the first two review steps and share out with the next people to review.

**Comment by arielleandrews** [comment]
@JHarrietha-AOT I made one last minor change suggestion in the email and letter versions, otherwise yes I think these are ready to go to the next stage of review. @m-prodan if you agree I can send these over to Patrick and Gitta next? Or Jackie would you like to send to them directly?

**Comment by m-prodan** [comment]
Let's move this one along to the next level of review, we've got a few more folks to go through yet, so best get started now as we may get more feedback regardless.

**Comment by JHarrietha-AOT** [comment]
@m-prodan Sounds good! @arielleandrews If you are okay to send them that would be great!

**Comment by arielleandrews** [comment]
Letters sent for review to Patrick and Gitta July 15th. Feedback requested by end of day Mon July 19th.

**Comment by arielleandrews** [comment]
@JHarrietha-AOT I have uploaded Patrick and Gitta's suggested edits to Teams: https://teams.microsoft.com/_#/files/General?threadId=19%3A1c5b921afa4b45d49bad9acfaf3d5a6e%40thread.tacv2&ctx=channel&context=NEW%2520Email%2520Templates&rootfolder=%252Fteams%252F03521%252FShared%2520Documents%252FGeneral%252FUser%2520Research%252FTemplates%252FNEW%2520Email%2520Templates

**Comment by arielleandrews** [comment]
Sent for review to Jamie Onciul and Template Team Jul 21 - fyi @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Here are the updated letters & emails let me know if I missed anything. If everything looks good I think this issue can be moved to close.

https://teams.microsoft.com/_#/files/General?threadId=19%3A1c5b921afa4b45d49bad9acfaf3d5a6e%40thread.tacv2&ctx=channel&context=Final&rootfolder=%252Fteams%252F03521%252FShared%2520Documents%252FGeneral%252FUser%2520Research%252FTemplates%252FFinal

**Comment by arielleandrews** [comment]
Thanks @JHarrietha-AOT - I've reviewed and made some minor tweaks. I'll revise the DOD to reflect Kris and Cindy's review and move to closed.
