### ISSUE TITLE
Home Button

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1670]
* As a user
* I want a button or link that says "Home"
* so that I know how to get back to my queue

**Assumptions & Scope**	
This is a simple design update - currently users can go back to their queue by clicking on the "FOI" space and the "British Columbia" space in the top left corner. Per user feedback from training, they would like it to be more apparent to them that is how they should go back to the queue.

**Acceptance Criteria**	

**Scenario 1: Hover over Home Button/space**
* GIVEN a user is on the review request page
* WHEN they hover over the "Home" button/space (replace FOI in left nav with Home)
* THEN their cursor will turn into a hand

**Scenario 2: Click on Home button/space**
* GIVEN a user is hovering over the home button/space
* WHEN they click on the space
* THEN they will be returned to their home page/queue

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@JHarrietha-AOT - please link updated design here.

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by JHarrietha-AOT** [comment]
I have included a screen shot of the expected design its has also been updated throughout the invision links.

The icon is this one from Font Awesome as per @divyav-aot advise
https://fontawesome.com/icons/house-chimney?s=solid

![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/44847947-16be-442b-b914-d6b8c5dcfa81)

**Comment by aparna-aot** [comment]
@JHarrietha-AOT The icon mentioned above is introduced in fontawesome 6.0.0 and the current version we are using is 4.7.0. Migrating from 4.7.0 to 6.0.0 involves more steps rather I have found out a similar icon in 4.7.0 itself . You can view it here : https://fontawesome.com/v4/icon/home.
I am attaching the screenshot of the page with the mentioned icon added. Please share your thoughts.
![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/45e142f3-493e-4d16-b973-9a4e8f7daeab)

**Comment by JHarrietha-AOT** [comment]
@aparna-aot Thanks for sharing, this icon is great. Passes UX Assurance feel free to move it into the next column so it can be merged into test

**Comment by lmullane** [comment]
Passed QA. Nice work, @aparna-aot
