### ISSUE TITLE
UX Assurance - Grey Bars on Side of Queue

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1673]
Title of ticket: UX Assurance - Grey Bars on Side of Queue

#### Description
Grey Bars on side of Queue are thicker than the grey bars used throughout the rest of the app where the left nav bar is in play.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Decrease size of grey bar on either side of the queue to match the size elsewhere in the app
- [ ] By decreasing size of grey bars on queue page this will allow for more spacing in queues
- [x] Review page was changed to match queue width as part of 1076 - need to increase width of review page when queue increases as well

**Comment by JHarrietha-AOT** [comment]
Screenshots for reference

![Screen Shot 2022-03-14 at 12.59.08 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/87055848-eb19-49ab-9230-46d49a5e15a6)

**Comment by nkan-aot** [comment]
fixed as part of 1076

**Comment by JHarrietha-AOT** [comment]
@nkan-aot Thanks for flagging this duplication, I'll review. Wanted to ask did we increase the width of the queue with that? or is there just more white space around the queue?

**Comment by nkan-aot** [comment]
reason being queue already matched the width of the navbar

**Comment by JHarrietha-AOT** [comment]
@nkan-aot This ticket is basically highlighting to do the opposite to increase the size of the page and decrease the size of the grey bars. This is because we had a user in training who outlined they found things difficult to see as they had glasses, we also will be adding an additional column to the processing queues, and the additional space is really needed to make that more readable. So this is a dependency on the column change ticket so we have space for it before we add it

**Comment by JHarrietha-AOT** [comment]
@nkan-aot Sounds good, feel free to add that here and increase the estimate based on the work

**Comment by nkan-aot** [comment]
@JHarrietha-AOT how wide do you want the queue? currently it is 62% width (19% margin on both sides)

**Comment by JHarrietha-AOT** [comment]
@nkan-aot Great work on this give everything more space and just feels easier to look at!
