### ISSUE TITLE
Review of Acknowledgment Letters

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#168]
Title of ticket: Review of Acknowledgment Letters

#### Description
Review and completion of changes requested for Acknowledgement Letters

#### Dependencies
Creation of Letters #136

#### DOD
- [x] Review by SME and PO
- [x] Completion of any changes requested

- [x] Review by Patrick and Gitta and Leads of Intake Team
- [x] Completion of any changes requested

 - [x] Review by Template Team
 - [x] Completion of any changes requested

- [x] Review from Kris and Cindy K
- [x] Completion of any changes requested

**Comment by JHarrietha-AOT** [comment]
**Draft 1**

Here is the first draft of the re-design of the acknowledgment letter/email. Core difference is letter has header and footer with contact info, email has signature with contact info. And I have added titles for content to be easier to find. I designed these as examples, so anything in orange is what would be auto-populated based off of what is selected.

Email: https://teams.microsoft.com/l/file/A3D540CF-108A-488D-9A76-8625B9E721E1?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FTemplates%2FNEW%20Email%20Templates%2FProposed%20-%20Acknowledgment%20Email.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

Letter: https://teams.microsoft.com/l/file/F240EE45-10DB-4041-A5EC-F5F321FA5175?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FTemplates%2FNEW%20Letter%20Examples%2FProposed%20-%20Acknowledgment%20Letter.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

Here is the start of the excel with the different options and the text for each, included what was originally provided and what I have changes: https://teams.microsoft.com/l/file/327608AA-011C-44C9-AF85-B325C3325F31?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=xlsx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FTemplates%2FTemplates.xlsx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by JHarrietha-AOT** [comment]
@m-prodan Links are listed above, please review whenever you have time. Thanks

**Comment by m-prodan** [comment]
@JHarrietha-AOT - I've made some suggested edits, and a potential solution for the clarification note flagged by @arielleandrews .... I do think we'll encounter some hurdles if we don't include the note about records being published - so for consideration as to whether or not we want to include it. I think it might be worth flagging to check on feelings about -not- including it as a potential halfway?

**Comment by arielleandrews** [comment]
Good point @m-prodan. @JHarrietha-AOT what a sentence about publication was included but only pulled in if the request type is General?

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan I have updated the letters & emails based on your last round of feedback. I know you busy today with steering committee prep, just wanted to let you know they're ready to review when you have a chance

**Comment by m-prodan** [comment]
Review completed - looks good to me - made one minor change to the publication piece. I understand it is from the original paragraph, but think the change is worthwhile as the original one might have actually been somewhat confusing to an applicant I think.

**Comment by JHarrietha-AOT** [comment]
I have made the changes suggested by @m-prodan and @arielleandrews, @mpilchar  if you have time today to review as well just for another perspective before we move forward that would be great!

**Comment by mpilchar** [comment]
@JHarrietha-AOT exceptional job on this one too. Made a couple minor comments within the doc

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews @mpilchar wondering if we feel confident in where these are at and are ready to check off the first two review steps and share out with the next people to review.

**Comment by arielleandrews** [comment]
@JHarrietha-AOT I made one last minor change suggestion in the email and letter versions, otherwise yes I think these are ready to go to the next stage of review. @m-prodan if you agree I can send these over to Patrick and Gitta next? Or Jackie would you like to send to them directly?

**Comment by m-prodan** [comment]
Same comment as other ticket: Let's move this one along to the next level of review, we've got a few more folks to go through yet, so best get started now as we may get more feedback regardless.

**Comment by JHarrietha-AOT** [comment]
@arielleandrews We could send them all together in one email, explaining that these are examples and to ensure we have all required content and for them to review the changes in the design.

**Comment by arielleandrews** [comment]
Letters sent for review to Patrick and Gitta July 15th. Feedback requested by end of day Mon July 19th.

**Comment by arielleandrews** [comment]
@JHarrietha-AOT I have uploaded Patrick and Gitta's suggested edits to Teams: https://teams.microsoft.com/_#/files/General?threadId=19%3A1c5b921afa4b45d49bad9acfaf3d5a6e%40thread.tacv2&ctx=channel&context=NEW%2520Email%2520Templates&rootfolder=%252Fteams%252F03521%252FShared%2520Documents%252FGeneral%252FUser%2520Research%252FTemplates%252FNEW%2520Email%2520Templates

**Comment by arielleandrews** [comment]
Sent for review to Jamie Onciul and Template Team Jul 21 - fyi @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Here are the updated letters & emails let me know if I missed anything. If everything looks good I think this issue can be moved to close.

https://teams.microsoft.com/_#/files/General?threadId=19%3A1c5b921afa4b45d49bad9acfaf3d5a6e%40thread.tacv2&ctx=channel&context=Final&rootfolder=%252Fteams%252F03521%252FShared%2520Documents%252FGeneral%252FUser%2520Research%252FTemplates%252FFinal

**Comment by arielleandrews** [comment]
Thanks @JHarrietha-AOT - I've reviewed and made some minor tweaks. I'll revise the DOD to reflect Kris and Cindy's review and move to closed.
