### ISSUE TITLE
Advanced Search changes

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1688]
* As any user
* I want Advanced Search to be intuitive to use
* so that I can easily search for specific elements of a request

**Assumptions & Scope**	

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

WRITE OUT FOR EACH OF THE FILTER BUTTONS

**Scenario 1: Remove default setting on Request Description button**
* GIVEN ... I am on the queue 
* WHEN ... I click on Advanced Search at the top of a queue and land on the page
* THEN ... all buttons (request descrip, ID, Axis request, applicant, assignee or subject code) will be unselected (they'll be grey in colour and not filled in blue).
* AND ... the apply search button will be inactive
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058

**Scenario 2: Tool tip on request selection**
* GIVEN ... I am on the Advanced Search page
* WHEN ... I click on Tool tip button 
* THEN ... information appears explaining that at least one criteria mustbe selected for search to work
*  https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058
* AND ... the apply search button will be inactive

**Scenario 3: Perform a Key word Search / Activate Apply Search Button**
* GIVEN ... I am on the Advanced Search page
* WHEN ... I enter in one or more key words
* AND ... make at least one selection from the search categories (Request State, Request Status, Request Type, Date Range and/or Search by Public Body)
* THEN ... The Apply Search button will become active
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445059

**Scenario 4: Buttons narrow the search**
* GIVEN ... I have performed a key word search and generated the search results
* WHEN ... I select a button  (request descrip, ID, Axis request, applicant, assignee or subject code) 
* AND ... click Apply Search
* THEN ... The search results will filter by the key word + button selection

**Scenario 5: Received date
search results match
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
I've begun on the AC from the Adv Search discussion today, please feel free to refine further @lmullane
cc: @m-prodan @arielleandrews @JHarrietha-AOT @richard-aot @jadmsaadaot

**Comment by mpilchar** [comment]
@richard-aot - Do I need to write up two separate Issues... one for IAO users and one for ministry users?

**Comment by richard-aot** [comment]
One issue is fine, @Pilchar, Molly CITZ:EX ***@***.***> We
will not miss ministry this time. :)

**Comment by m-prodan** [comment]
x-ref ticket with #1654

**Comment by JHarrietha-AOT** [comment]
I am unable to edit the issue itself to add the design link but here it is: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058

**Comment by mpilchar** [comment]
@richard-aot I need to update the AC for this one. We put a ballpark estimate of 5 on this for the purpose of planning, but let's connect on this one next week (Apr 4)

**Comment by nkan-aot** [comment]
need to investigate unopened requests no longer showing unassigned in assignee column

![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/d41d88f2-8678-4809-9f1b-504208816182)

**Comment by lmullane** [comment]
@richard-aot. I've added the designs to the AC and verified that there was no change in the ACs for the first 4.

@JHarrietha-AOT, unclear to me what if there were any design or functionality changes for the last two ACs?

**Comment by lmullane** [comment]
Thanks, @JHarrietha-AOT 

I will remove scenarios 5 and 6 from this story. Could you please write a bug ticket for applicant names for general requests showing for ministry coordinators?

cc @richard-aot @KaraBeach @m-prodan @mpilchar

**Comment by JHarrietha-AOT** [comment]
@lmullane I was looking at other advanced search tickets, I don't thinks the columns in the advanced search results matching the columns in that user groups queue was ever included in AC. So I wrote it as a story so it was easy to divide out what the columns should be for each user.

Let me know if you have any questions its: #1837

**Comment by richard-aot** [comment]
#1688 is ready for testing. Also increased the estimate to 8 to reflect the actual time took for this US.

**Comment by mpilchar** [comment]
Created bug #1871 to correct date ranges

**Comment by mpilchar** [comment]
Moving back into "ready for QA" column until I get confirmation from PO on functionality and can update AC for this one
