### ISSUE TITLE
Deployment of request-management-api in dev

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#169]
This is an interim activity created till CI/CD pipeline is being setup for foi-flow repository.

**Comment by acoard-aot** [comment]
This is done.

I had previously completed this task; but after the deployment of FormsFlow we're now using Patroni.  This deploy has been updated to use the same Patroni instance that FormsFlow is using, but a separate database within the patroni instance (i.e. diff `CREATE DATABASE`'s).

**Comment by acoard-aot** [comment]
Closing issue, as there really is no QA on this. Open to discussion of course.
