### ISSUE TITLE
Patroni HA / Prod Identified Issues

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/foi-flow#1696]
Title of ticket: Patroni volume verification as common mount

#### Description
This is broken out from task #1473.  This includes some other patroni related issues that 

Patroni volume verification as common mount

#### Dependencies
None

#### DOD
- [x] Patroni volume verification as common mount (Answered by RocketChat: There is no common mount, it has to be a completely identical mount x3, also with 1G storage for each for general patroni metadata  ((X+1)*3).  So if we wanted to store 20GB, we should allocate 63GB.  ((20+1)*3)
- [x] Missing 700mb of patroni pvc is resolved (vaccuum?)
- [x] Patroni backup to be taken for schemas foidb and foi-camunda and same need to verified.

**Comment by mpilchar** [comment]
@acoard-aot is closing this ticket and creating a new post-production ticket for the remaining A/C (vacuum)
