### ISSUE TITLE
Executive level dashboard research

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1698]
Title of ticket: 

#### Description
Interest in participating in UX/UI dashboard research was experessed at Governance meeting and with a meeting with AG (March 16 '22)

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by mpilchar** [comment]
Tagging @JHarrietha-AOT for awareness

**Comment by JHarrietha-AOT** [comment]
@mpilchar I think this research was covered last sprint where I did sessions with Kris and higher level executives. We have the plan and I have shared the report out with Vineet. We will go over it this sprint and begin working on it.
