### ISSUE TITLE
Prepare Materials for 1st SC Meeting

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#170]
Title of ticket: Prepare Materials for 1st SC Meeting

#### Description
Meeting July 13 (TIME TBD - follow up w/ KG)
Requested - Draft Agenda, powerpoint, and potential speaker (Agile Coach?)

KP liked idea of having an Agile Coach (Matt) present to the committee giving an overview of what they can expect to see and need to focus on for typical Agile projects.

#### DOD
- [x] Confirm Availability of Agile Coach
- [x] Draft Agenda
- [x] Draft Slides
- [x] Sent to KG by Friday for KP Review

**Comment by m-prodan** [comment]
Thought I would include both @mpilchar and @arielleandrews on this ticket.

I was given this task this morning - still waiting to confirm actual time for the meeting on July 13th - see description above

**Comment by m-prodan** [comment]
Kris has confirmed that the SC meeting will be on July 13th from 11AM - 1145

Assuming our agile coach Matt is off this week, hopefully we can find someone from the lab that could speak to that audience for a portion of the meeting? 

I'll look at one of Loren's powerpoints from the IMML committee to see if we can repurpose it for this audience, and we'll try and come up with an Agenda.

What kind of timing do we think we want from the person from the lab... 10 minutes sufficient for this audience? That can help guide any draft agenda. Maybe we put them towards the end of the Agenda so they will be available for Q and A's as well?

**Comment by m-prodan** [comment]
@arielleandrews @mpilchar - just sent a mtg invite for tomorrow to talk steering committee. I'll try and tweak some slides for the group ahead of our call, don't know if we'll need the full hour but we can fill it with other items if need be.

**Comment by mpilchar** [comment]
@m-prodan I have reached out to the lab and Jesus - re: the agile coach. Will update on this when we meet tomorrow

**Comment by m-prodan** [comment]
Materials sent to KP today to be distributed to members - all assets in place, closing ticket
