### ISSUE TITLE
Sort by CFR Due Date or Legislated Due Date not chronological

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#1721]
**Describe the bug in current situation**
Sorting by the CFR Due Date or Legislated Due Date in the Flex Queue and Ministry queue does not sort by chronological order.

**Link bug to the User Story**

**Impact of this bug**
Low impact. Does not impact functionality or due date calculation, is only a sorting issue. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Flex Queue or Ministry Queue 
2. Click on CFR Due Date or LDD column to sort
3. See error - sorting order appears to be random

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
Ministry Queue sort
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/be1ba71b-3956-4cf5-8f85-be762f14c6c4)

Flex Queue sort
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/394875e1-cab8-4d33-a812-4b711e1a46eb)

**Comment by arielleandrews** [comment]
@richard-aot as discussed at standup this morning

**Comment by lmullane** [comment]
@richard-aot, has fixed. Can test when we push Advanced Search.

**Comment by lmullane** [comment]
Works as expected in both the queue and Advanced Search.
