### ISSUE TITLE
Standardizing Idle Logout Across App

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1724]
**Describe the bug in current situation**

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by JHarrietha-AOT** [comment]
Closing this duplicate ticket as it is covered in #1725.
