### ISSUE TITLE
Standardizing Idle Logout Across App

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1725]
**Describe the bug in current situation**
From training and general experience in using the app, there appears to be an inconsistency in how idle sessions logouts are being handled. Users have given varying accounts of experiences of being logged out of the application in a manner that doesn't feel consistent. 

**Link bug to the User Story**

**Impact of this bug**
If the idle time logout is unexpectedly short, users could lose work on files if they step away for a break

**Chance of Occurring (high/medium/low/very low)**
Medium - difficult to replicate exact timings, results have been varied across users and QA testers.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
TEST environment - a user needs to be logged into the system

**Steps to Reproduce**
1. Log in to FOI Flow App
2. Wait an indeterminate amount of time
4. Time for logout should not appear to be consistent

**Actual/ observed behaviour/ results**

**Expected behaviour**
Decision: Standardize logout timers to a 12 hour session timeout

GIVEN a user has logged into the application
WHEN they remain idle for an extended period of time (> 12 hours)
THEN they will be automatically logged out of the application.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
Hi Team - I got word from Andrew that AXIS has a 12 hour limit on the application.

I've updated the AC with that in mind, but am leaving this as "Incomplete AC" as we may want to discuss a different approach as a team.

cc: @arielleandrews @mpilchar @lmullane  @sumathi-thirumani-aot

**Comment by m-prodan** [comment]
Note for team - we are confirming idle logout timers with the lab and MISO, we may get this info just ahead of our meeting for refinement

**Comment by mpilchar** [comment]
I've set an alarm to test this from 7pm to 7am

**Comment by mpilchar** [comment]
I was auto logged out before 12 hours so will keep testing

**Comment by mpilchar** [comment]
Works! Went from 5:55am to 5:55pm. Thanks @sumathi-thirumani-aot ! Might test again overnight...maybe it resets at midnight?

**Comment by mpilchar** [comment]
I stayed logged in overnight this time - confirming this as closed
