### ISSUE TITLE
User research sessions for Call for Records

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#173]
Title of ticket: User research sessions for Call for Records

#### Description
Completion of User Walkthrough sessions for Call for Records

#### DOD
- [x] Katie Innis (PSSG Personals) - Mon July 12th
- [x] Pablo Frederick (Generals Flex team) - Tues July 13th
- [x] April Haussman (SDPR), Leala Bull - Tues July 13th
- [x] Jazmin Anderson (Flex team) - Wed July 14th

**Comment by mpilchar** [comment]
@JHarrietha-AOT Just added this. Please review and edit as needed

**Comment by JHarrietha-AOT** [comment]
@mpilchar Thanks for setting up this issue. I just removed the setup of the session as that was completed in the recruitment ticket

**Comment by JHarrietha-AOT** [comment]
Session 1 Complete - Katie Innis (PSSG Personals) - Mon July 12th

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%205%20-%20Research%20-%20Recordings/Call%20with%20Andrews,%20and%202%20others-20210712_130205-Meeting%20Recording.mp4

**Comment by JHarrietha-AOT** [comment]
Session 2 Complete - Pablo Frederick (Generals Flex team) - Tues July 13th

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%205%20-%20Research%20-%20Recordings/CFR%20Walkthrough%20-%20Flex%20Team-20210713_140234-Meeting%20Recording.mp4

**Comment by JHarrietha-AOT** [comment]
Session 3 Complete - April Haussman (SDPR), Leala Bull - Tues July 13th

Note: April did not attend

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%205%20-%20Research%20-%20Recordings/Call%20with%20Andrews,%20and%203%20others-20210713_173121-Meeting%20Recording.mp4

**Comment by JHarrietha-AOT** [comment]
Session 4 Complete - Jazmin Anderson (Flex team) - Wed July 14th

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%205%20-%20Research%20-%20Recordings/CFR%20Walkthrough%20-%20Flex%20Team-20210714_133441-Meeting%20Recording.mp4

**Comment by JHarrietha-AOT** [comment]
All sessions have been completed with links to each recording above
