### ISSUE TITLE
Ministry Name Changes in FOI App

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1736]
* As a user of the system
* I want the new Ministry names to be reflected in the application
* so that they reflect my understanding of the names in the system

**Assumptions & Scope**	
What are the assumptions for this story?
Several Ministry names are changing - we need to reflect the same in our application
We have also been advised that a new sub-org of Indigenous Relations will be handling their own requests with a new code and new box on the online form
Scope is these name changes and additions only - another ticket will be written for future name changes to be configurable by users

What is IN scope?
Name changes for:
Education (Changing to Education and Childcare) - Code: Remains EDU
Agriculture Food and Fisheries (Changing to Agriculture and Food)  - Code: Update to AGR
Forests, Lands, Natural Resource Operations and Rural Development (FLNRORD - being reduced to Forests) - Code: Update to FOR

NET NEW:
Lands, Water and Resource Stewardship - Code: LWR

Declaration Act Secretariat - Code: DAS

Note: Declaration Act Secretariat will also need a new checkbox on the online form, and similar to other sub orgs has certain rules regarding fees which will be captured in the AC below:

**Acceptance Criteria**	

**Scenario 1: Applicant Selects DAS only**
* GIVEN an applicant is submitting a request on the online form
* WHEN they select "Declaration Act Secretariat"
* THEN they will be charged the standard 10 dollar application fee for that public body selection

**Scenario 2: Applicant selects DAS and IRR**
* GIVEN an applicant is submitting a request on the online form
* WHEN they select Declaration Act Secretariat, AND the Ministry of Indigenous Relations and Reconciliation
* THEN they will be charged a single fee of 10 dollars for both public bodies selected

**Scenario 3: IRR, DAS and Others**
* GIVEN an applicant is submitting a request on the online form
* WHEN they select Declaration Act Secretariat, AND the Ministry of Indigenous Relations and Reconciliation, AND any other public bodies
* THEN they will be charged a single fee of 10 dollars for the selection of both IRR and DAS, and any additional application fees for other public bodies added as required

(Example - Applicant selects DAS, IRR and FIN - application fee would be 20 dollars) 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, confirming if the codes have changed. Need those before action can be taken.

**Comment by m-prodan** [comment]
Education remains EDU
Agriculture is changing from AFF back to AGR
Forests code will be FOR
Lands/Water is LWR

**Comment by m-prodan** [comment]
@divyav-aot - updated the AC to also include DAS. Understand this will increase the effort somewhat. I also added AC specific to the payment scenarios for DAS as the payment rules will follow similar logic to how we handle other sub-orgs (ie: Finance, GCPE and PSA).

cc: @lmullane @mpilchar @KaraBeach

**Comment by m-prodan** [comment]
QA Complete - new Ministry scenarios passed and minor regression threw no issues (BCSC Verfication works, other personal requests worked and IGE generals worked)
