### ISSUE TITLE
UX Study Guide - Call for Records (IAO)

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#174]
Description:
Draft of the questions we will be asking users, plus a script

DOD:

  - [x] Drafted
  - [x] Reviewed and discussed with SMEs or PO

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan 

Here is a link to the draft of the Study Guide for these sessions: https://teams.microsoft.com/l/file/8055AF5C-9737-4A68-B6CC-ED17A1FB647A?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FSprint%205%20-%20Research%20-%20Call%20for%20Records%2FUX%20Research%20-%20Sprint%205%20-%20Study%20Guide.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by arielleandrews** [comment]
@JHarrietha-AOT I made a comment in the document in Teams about clarifying the scope of these research sessions. Other than that I think it's good!

**Comment by JHarrietha-AOT** [comment]
@m-prodan I tagged you in the document just looking for clarification on how this should be worded, while also ensuring we are getting the whole picture of what can happen during a call for records and what the product needs to address.

**Comment by JHarrietha-AOT** [comment]
@m-prodan added sentence based off your feedback to ensure we highlight that I am wanting to see all steps in the process not just a 'happy path' request. 

If this looks good it can be moved to close

**Comment by m-prodan** [comment]
As discussed - closing ticket with this comment.
