### ISSUE TITLE
PRODUCTION ETL deployment on TIKAL

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#1746]
Title of ticket: 

#### Description
This task is a split out from #1304, where PRODUCTION ETL deployment has been delayed until STRA approval.  DEV, TEST ETL deployment is over. 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Confirm ETL Deployment from WALTZ to TIKAL, using VS. If not migrate SSISDB and populate.
- [x] Confirm trial runs on SPHINX
- [x] Set up Redash  Visualizations and confirm the dashboard
- [x]  Ask Business to confirm the reports
- [ ]

Update on May 12 : FW issue exists between WALTZ to TIKAL - Informed IMB, but proceeding with VS set up on TIKAL and moving ETL packages manually to deploy from TIKAL itself

**Comment by mpilchar** [comment]
Waiting for review by business team of reports in production enviro
