### ISSUE TITLE
Penetration Testing

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1748]
Title of ticket: 
####Descriptio
Penetration testing is scheduled to be run by Telus beginning April 8/22

#### DOD
- [x] Onboard Telus to the app
- [x] Run Pen Tests
- [x] Meet on recommendations
- [x] Sent report to CITZ MISO

**Comment by mpilchar** [comment]
cc: @lmullane @m-prodan @abin-aot @divyav-aot - Please add in any additional information required for Penetration testing, and link which stories/tasks need to be completed before April 8

**Comment by mpilchar** [comment]
Cannot estimate this until we receive recommendations. Will create separate tickets based on recommendations to pull into the sprint as needed

**Comment by lmullane** [comment]
Changes do not need to be actioned at this time. Closing this ticket.
