### ISSUE TITLE
AXIS Sync - CFR DUE DATE

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#1768]
Title of ticket: 

#### Description
AXIS has multiple CFR DUE DATE per request. We will fetch the latest CFR DUE DATE for the OFFICEID(EDU, LBR etc) 

#### Dependencies
Are there any dependencies?

#### A/C
GIVEN an IAO User has created a request for documents on a request in AXIS
AND there is a CFR date already in Flow
AND there is a different CFR date in AXIS to be synced
WHEN the user click the sync button
AND the user clicks 'Review Changes From AXIS'
THEN the user will see a comparison of the two CFR dates listed on the sync modal
WHEN the user saves the request to FOI Flow
THEN the Call for Records due date will match the due date set in the Request for Documents in AXIS
AND the CFR days remaining will be updated in Flow to reflect this

#### DOD
- [x] Update SQL Query to fetch CFR DUE DATE
- [x] Update .NET API
- [x] Update FOI FE to Save CFR DUE DATE
- [x] Show CFR DUE DATE in AXIS sync Modal
- [x] Update BE POST API
- [x] Integration test

**Comment by lmullane** [comment]
For testing check that CFR due date matches in both AXIS and the new app.

**Comment by m-prodan** [comment]
@divyav-aot @aparna-aot - does this only work for pilot Ministries? I am unable to create a new "RFD" in test AXIS, so I tried doing it with an existing request that had an open RFD, but it wasn't syncing up the CFR due dates.

**Comment by m-prodan** [comment]
Update: I found another test request with an incomplete request for documents, I changed the action office to EDU and synced it to our system. The CFR due date stayed the same at 10 days. Moving back to review for further checks. I can discuss further at stand up on monday

**Comment by m-prodan** [comment]
@divyav-aot - thanks for explaining the issues. I have tried syncing with the requests you have suggested, and can confirm that it successfully synced the new CFR due dates. I will consider this one closeable now - thank you for the quick troubleshooting!

**Comment by lmullane** [comment]
Addition will be covered in #1880

**Comment by m-prodan** [comment]
Works great with a working test environment in AXIS now - nice work @aparna-aot @divyav-aot
