### ISSUE TITLE
Deployment Request Management to DEV

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#178]
Title of ticket: 

#### Description

1.  Request Queue Management LOB API
2.  FormsFlow Web - FOI Flow Customized Web Front End
3.  FormsFlow BPM - WorkFlow - Camunda POD.
4.  Redis Cluster - 

#### Dependencies
Are there any dependencies?
- Infrastructure for Redis - @acoard-aot @sumathi-thirumani-aot  to confirm

#### DOD
- [ ]  Application will be available on dev FOI Flow URL , with the functionalities demo'd on Sprint Dubrovnik
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by acoard-aot** [comment]
As per task #169, the first item here is done and using the same patroni instance.

@sumathi-thirumani-aot the remaining items in this task are all FormsFlow etc, including homepage modifications.

**Comment by mpilchar** [comment]
Build successful, some errors for team to work through

**Comment by sumathi-thirumani-aot** [comment]
This requires setup & deployment of listed components

patroni : **Completed**
redis : **Completed**
forms-flow-bpm : **Completed**
forms-flow-web : **Completed**
forms-flow-forms: **Completed**

Note: It is observed CSS is broken after deployment from branch https://github.com/bcgov/foi-flow.
Needs debugging at module.

**Comment by sumathi-thirumani-aot** [comment]
As per dev recommendation: Changes done in config map i.e. application name to be set as "foi-flow"; and it resolved the issues.

URL : https://dev-foirequest.apps.silver.devops.gov.bc.ca/

**Comment by acoard-aot** [comment]
This task is done and deployed to dev.  For an end to end test, you can use these two links to ensure foi requests show up in the queue.


FOI Request Form: https://dev.foirequestform.gov.bc.ca/

Request Management (queue): https://dev-foirequest.apps.silver.devops.gov.bc.ca/
