### ISSUE TITLE
Accessibility Testing and Ticket Creation for Critical Changes

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1786]
Title of ticket: Accessibility Testing and Ticket Creation for Critical Changes

#### Description
Will run multiple accessibility plug-ins on all pages of app

#### Dependencies
- [x] Meet with Adam to Discuss Previous Accessibility Plug-Ins 

#### DOD
- [x] Run Plug-Ins on each screen
- [x] Find Commonality
- [x] Identify Critical Changes
- [x] Make Tickets for All Critical Changes

**Comment by JHarrietha-AOT** [comment]
Extensions recommended by Adam

Accessibility extensions I've used in the past, relevant Harrietha, Jacklyn CITZ:EX from standup discussions.
 
Wave: https://wave.webaim.org/extension/  - Used this at MAXIMUS/MoH for compliance, it was great, our source of truth.  Slightly dated UI.
 
Accessibility Insights: https://accessibilityinsights.io/ - Newer, by Microsoft. Better UI, more modern, and likely just as good, but maybe a bit less battletested. (We would run both and use Wave as our final say).

**Comment by JHarrietha-AOT** [comment]
@acoard-aot Wanted to check in to see how this is going for you. I had thought I added some issues but was having connection issues so they were not saved. Is there anything I can do to help with wherever you are at with this now?

**Comment by acoard-aot** [comment]
@JHarrietha-AOT Hey, let's connect this morning, can discuss

**Comment by JHarrietha-AOT** [comment]
Have created tickets #1927 - #1931

**Comment by JHarrietha-AOT** [comment]
@acoard-aot I am going to move this to closed as we have review all the Accessibility Issues and created Tickets. And I have shared the extension to download for all devs to have ready if they pick up the tickets
