### ISSUE TITLE
Toast error while saving changes to online submitted request in FOI

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#1792]
Title of ticket: 

**Describe the bug in current situation**
Toast error while saving changes to online submitted request in FOI. This happens when the request is in "intake in progress". 

Link bug to the User Story

Impact of this bug
data not getting saved

Chance of Occurring (high/medium/low/very low)
Medium

Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?
TEST environment - a user needs to be logged into the system

**Steps to Reproduce**

1. Submit a request using angular app
2. Login to FOI Flow
3. Open the request created in step 1
4. Fill all mandatory fields and Save
5. Try to edit the request and Save

**Actual behavior**
A toast error shows and data not getting updated

**Expected behavior**
Data should get saved without any error

Screenshots/ Visual Reference/ Source
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
Reminder to please use the Bug Report template:)

**Comment by divyav-aot** [comment]
@lmullane - Updated the ticket using bug report. This issue happens only with request submitted using Angular app.

**Comment by m-prodan** [comment]
I am no longer able to replicate - closing ticket
