### ISSUE TITLE
Bug: Image pulling issue on Openshift Service Agent

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#180]
Issue pulling images from Tools enviro into Test enviro

DOD
-{ ]- reach out in RC
-[ ]- issue resolved

**Comment by acoard-aot** [comment]
Note @sumathi-thirumani-aot  - this only seems to affect the patroni instance, not anything else.  I pulled API and postgres images fine.

**Comment by acoard-aot** [comment]
This task is done.  Image Pull issue is no longer affecting Redis, APIs, etc.

We still need to configure Patroni in dev.  We are using plain postgres, and we can circle back to upgrading with patroni later.  It is not necessary now, and getting the CI/CD setup is higher priority.  Marking this as closed.  Patroni can be captured in deployinig formsflow to test task.
