### ISSUE TITLE
_A accounts and VPN templates

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1803]
Title of ticket: 

#### DOD
- [x] Request _A accounts for Sumathi, Aparna, Nick and Adam (Molly)
- [x] Request VPN template update for their normal IDIR (request Matt Morris if these can be done in parallel) - IMB
- [x] Confirm set up with IMB

**Comment by mpilchar** [comment]
Past _A access to production database for Divya, Richard, Sumathi and Vineet documented in IMB's JIRA board here: https://apps.itsm.gov.bc.ca/jira/browse/FOIMOD-62

**Comment by mpilchar** [comment]
It appears that Sumathi has been set up with an _A account already but it hasn't been granted access to the databases yet.

**Comment by mpilchar** [comment]
I submitted requests for Adam, Aparna and NIck to IAO office manager today

**Comment by mpilchar** [comment]
Requested a status update on these today

**Comment by mpilchar** [comment]
Confirmed that the accounts have been set up and created a ticket for the IMB backlog on May 10 requesting the VPN template update

**Comment by mpilchar** [comment]
@abin-aot Do you know if this is done?

**Comment by abin-aot** [comment]
All resources has access now and confirmed . @nkan-aot , @sumathi-thirumani-aot , @aparna-aot
