### ISSUE TITLE
Research and Discussion: AXIS Database Analysis, ETL Feasibility

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#181]
Title of ticket: Research and Discussion: AXIS integration

#### Description
Summarize issue 

#### Dependencies
Dependency tagged - Dev Access managed by IMB - timetable for access to be confirmed this Friday

#### DOD
- [x] Set up Abin in dev enviro for AXIS
- [x] Abin to explore AXIS environment
- [x] ETL options to migrate data

**Comment by m-prodan** [comment]
@abin-aot  - IMB advised we can expect access to 10.7 by EOD Wednesday - will report back if I hear anything different!

**Comment by abin-aot** [comment]
Received DB access on 17/AUG via my _A account. Can see tables now. But waiting for API details from vendor - @lmullane @m-prodan

**Comment by abin-aot** [comment]
On 30/Aug/2021 , as discussed on Sprint Meeting, splitting this task to two. API Integration analysis will be on other task and will start working on it once we get access to AXIS API

**Comment by abin-aot** [comment]
AXIS DB analysed : **ATIPD on IXIAS\CIRMOTST**

**_Tables are primarily store Request information :_**

- tblRequests
- tblCaseDescriptionHistory
- tblRequestDocuments
- tblCorrespondence
- tblRequesterNotes
- tblRequestDocuments

TEST Data created on 10.7 version of AXIS Dev Deployment, refer link below
http://dev.axis.gov.bc.ca/ATIPXpress/Request/Correspondence.aspx?**RequestId**=**4217**

_**MS SQL Master Query to find the Table, Column info.**_
select t.name,c.name from sys.tables t join sys.columns c on c.object_id = t.object_id where t.name like '%req%'and c.name like '%desc%'

select t.name,c.name from sys.tables t join sys.columns c on c.object_id = t.object_id where  c.name like '%desc%'
