### ISSUE TITLE
Reopen a request assigned to a team 

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1812]
* As a ministry coordinator
* I want a request to be reassigned to my ministry team when it is re-opened instead of the previous assignee
* so that the request is not lost if the assignee is no longer with the ministry team 

**Assumptions & Scope**	
What are the assumptions for this story?
* Currently when a request is reopened it by default remains assigned to the last assignee, which is likely an individual.
* Ministry coordinators may change jobs and no longer the person a request should be assigned too.
* From CFR onward it will assign to the ministry team, and to the previous IAO assignee
* IAO will be opening it - it will have a default assignment to previous assignee with the opportunity to reassign (as opposed to having an auto assignment) 
* If previous IAO assignee has moved onto another role, any IAO analyst can reopen from Advanced Search and self assign

What is IN scope?
Assignment of a reopened request

What is NOT in scope?
Reopening a request is covered in #832 

**Acceptance Criteria**	

**Scenario 1: Assign reopened request to ministry team*
* GIVEN a request has been closed from the Call for Records stage onwards
* WHEN the IAO analyst re-opens the request
* THEN the request will automatically show as unassigned in the review page
* AND dashboard shows minstry team as assigned

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, does this look good to you?

**Comment by mpilchar** [comment]
When testing this, I assigned a request to myself I'm set up as a flex user), closed it from the CFR stage, went to Advanced Search, and reopened it. It reopened still assigned to me. Based on this, should it have reassigned to the flex queue? Do I need to log in and out inbetween? Worried I might be misinterpreting so perhaps someone else can have a look?

**Comment by m-prodan** [comment]
@mpilchar - this one is specifically for the Ministry team to revert to the team assignment, not IAO.

I did some tests with a personal and general request, and it appears to work as expected - I'll leave with you to confirm and close the ticket if yo uare satisfied.

**Comment by mpilchar** [comment]
passed and is quite a cool lil feature once I figured it out! nicely done!
