### ISSUE TITLE
API  - GET FOI RAW REQUEST DETAILS

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#182]
Title of ticket: 

#### Description
This API will fetch the details from the LOB Database  based on the Identifier passed. This details returned on the this API will be used to display the data on review FOI request details screen. 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] All details on review FOI review details are covered on the JSON output
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by acoard-aot** [comment]
Deployed in test.
