### ISSUE TITLE
Master Data GET APIs for Review Request - Ministries, Category 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#183]
Title of ticket: 

#### Description
The API**s** for listing Master Data on Review Request - Ministries, Applicant Types. We might need to leave less important aside, like request type . But this will get commented on the story level as we decide

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Multiple API endpoints to list separate Master Data details in JSON format
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by acoard-aot** [comment]
Deployed in test.
