### ISSUE TITLE
Right click search results to open new browser tab or window

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1834]
* As a ministry coordinator and IAO analyst
* I want to be able right click a request search result 
* so that I have the option to open the request in a new window or tab

**Assumptions & Scope**	
What are the assumptions for this story?

Currently, if a user executes an Advanced Search and gets a list of results, when the user clicks on a search result there is no way to get back to the previous search result list; they have do the search again.

Assumption, users will find this frustrating.

User have asked for the ability to right click and open a new window or tab.

What is IN scope?
Opening another browser window or tab for search results.

What is NOT in scope?
Actual search functionality is covered in other stories (e.g., 1688)

This is only for search results?

**Acceptance Criteria**	

**Scenario 1: Advanced Search**
* GIVEN a ministry coordinator or IAO analyst is on Advanced Search
* AND he or she has search results listed
* WHEN the user. right clicks a result listed
* THEN a drop down will open with options to 'Open in a new tab' and 'Open in a window.'

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
Decision was no design was required.

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@nkan-aot , @JHarrietha-AOT, I need clarification. Was the right click only for search results or is this to allow the user to right click and open a new window or tab for any link?

**Comment by nkan-aot** [comment]
based on my experience testing i think it makes sense to make it available to all links. definitely for both queue and advanced search results. I think the only other place we have links to requests are notifications and it shouldn't be too hard to add that as well

**Comment by lmullane** [comment]
Thanks for the confirmation, @nkan-aot

**Comment by lmullane** [comment]
@nkan-aot, I think we'll leave it just for the search results for now and see if the users ask for this functionality for other links.

**Comment by lmullane** [comment]
@nkan-aot, looks like we had our communications crossed. 

Scenario 2 was met but 1 was not, but reading through the comments I believe it was unclear what was expected.

I will remove Scenario 1 from this story and close.

**Comment by nkan-aot** [comment]
@lmullane sorry i only see 1 scenario now, what was wrong with scenario 1?

**Comment by nkan-aot** [comment]
oh okay i see when you said just search results I thought you meant just advanced search and not queue. I can add this functionality to queue as well it shouldn't take too long

**Comment by lmullane** [comment]
I don't think it's necessary for the queue. Happy to leave it as is and close this one.

Key word searches are not that sophisticated on the queue so easy to replicate.

**Comment by nkan-aot** [comment]
okay sounds good, can always add later if users request it
