### ISSUE TITLE
Banner and Sync with AXIS button enabled even though there is nothing to Sync

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#1836]
**Describe the bug in current situation**
Banner and Sync with AXIS button enabled even though there is nothing to Sync. This issue exists only if there is extensions linked to the request.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Add Request
2. Enter AXIS Number which has extension(s) linked to it
3. Save the request
4. Open the request
5. Banner shows
6. Click on Sync with AXIS
7. Extensions shows in the request

**Actual/ observed behaviour/ results**
Banner and Sync with AXIS button enabled

**Expected behaviour**
Since there is nothing to sync, the Banner and Sync with AXIS should not show/enabled

**Screenshots/ Visual Reference/ Source**
below AXIS number is from DEV
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/c5d913b1-eb4a-4e80-be1d-c1ebb2eb3352)
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/c0f01b7b-f335-49c5-b524-2737ae1436bb)

**Comment by divyav-aot** [comment]
@lmullane - we were able to reproduce the banner issue. @aparna-aot  is working to fix this issue.

**Comment by m-prodan** [comment]
This appears to be working now - the banner no longer shows when there is nothing to sync and the sync button is disabled as expected.
