### ISSUE TITLE
Advanced Search Queue Column Updates

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1837]
* As any user
* I want  my queue columns to match my advanced search results columns
* so that I only see the relevant information based off of my user group

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?
Updating the columns that show in the Advanced Search based on the columns in the queue for the signed in user type.

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Advanced Search Columns - Intake Team User*
* GIVEN the user is signed in as a Intake Team User
* WHEN they select "Advanced Search" and add criteria and "Apply Search"
* THEN search results should show in the following columns: Applicant Name, Request Type, ID Number, Current State, Assigned To, Received Date

**Scenario 2: Advanced Search Columns - Flex Team User**
* GIVEN the user is signed in as a Flex Team User
* WHEN they select "Advanced Search" and add criteria and "Apply Search"
* THEN search results should show in the following columns: Id Number, Applicant Name, Category, Type, Current State, Assigned To, CFR Due, Days Left

**Scenario 3: Advanced Search Columns - Processing Team User**
* GIVEN the user is signed in as a Processing Team User
* WHEN they select "Advanced Search" and add criteria and "Apply Search"
* THEN search results should show in the following columns: Id Number, Applicant Name, On Behalf, Type, Category, Current State, Assigned To, Days Left, Ext., Pages

**Scenario 4: Advanced Search Columns - Ministry Team User**
* GIVEN the user is signed in as a Ministry Team User
* WHEN they select "Advanced Search" and add criteria and "Apply Search"
* THEN search results should show in the following columns: Id Number, Category, Type, Request State, Assigned To, Records Due, LDD.

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
Good catch, @JHarrietha-AOT 

@mpilchar, we can refine this ticket on Friday.

**Comment by mpilchar** [comment]
On a sort of related note, one thing that @KaraBeach and I noticed when testing Advanced Search today is that the date range has "received date" and "closed date" as search options, but these are not columns in the Advanced Search results. Should they? cc: @lmullane @richard-aot 
![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/161e5c6b-c0fd-4ba4-828f-85f7d6b8ba38)

**Comment by mpilchar** [comment]
@KaraBeach and I also noticed that with the changes made to Advanced Search and requirement that at least one box be checked, we kept wishing "Request Type" came first in order to sort in descending order of how broad the criteria was. Just food for thought

**Comment by mpilchar** [comment]
Needed for Release 2.1 so ministry don't see applicants name

**Comment by lmullane** [comment]
Thanks for your work on this story, @richard-aot.

All AC passed as expected.
