### ISSUE TITLE
FOI - Security Analysis

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#1838]
- [x] Remove the unused properties from local storage and also encrypt property "authToken". [Data Protection + Data policy]
- [x] Include security headers on server-side resource response. [No-sniff +XSS+ XSRF + Data Protection] 
- [x] SSL Setup + CORS Update  [No-sniff Secured Channel]
- [x]  Schemas to include type and length (server side) [Overflow attack]

**Comment by nkan-aot** [comment]
tried out the following tools, so far no vulnerabilities found
https://github.com/mozilla/eslint-plugin-no-unsanitized
https://addons.mozilla.org/en-US/firefox/addon/csrf-spotter/
https://addons.mozilla.org/en-US/firefox/addon/check-xss/
https://addons.mozilla.org/en-CA/firefox/addon/easy-xss/
