### ISSUE TITLE
DOB is not getting cleared for Applicant/Child/OnBehalf

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#1839]
**Describe the bug in current situation**
DOB is not getting cleared for Applicant/Child/OnBehalf.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Add personal request
2. Fill all the sections including Child, OnBehalf and Applicant DOB
3. Save the changes
4. Open request
5. Remove DOB of Child, OnBehalf and Applicant

**Actual/ observed behaviour/ results**
The DOB is not getting cleared

**Expected behaviour**
DOB should get cleared

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nkan-aot** [comment]
no longer reproduceable, closing
