### ISSUE TITLE
Request Review UX and  FE

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#184]
Title of ticket: 

#### Description
Develop the UX as per wireframes, business requirement mentioned on the user story. The Review details screen will be displaying data as the selected request on Queue/Request listing

#### Dependencies
Are there any dependencies?
- To functionally complete this task APIs need to completed 

#### DOD
- [x] API Integration
- [ ] UX as per wireframes
- [x] Display as per the selected details
- [x] Separate UX components as required following best practices
- [ ] Form validation

**Comment by mpilchar** [comment]
Extent of User experience/responsiveness: No mobile, but may have some tablets (surface, ipad). Execs in particular.
