### ISSUE TITLE
FE validation for address or email (any 1 is mandatory) not working

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#1840]
**Describe the bug in current situation**
FE validation for address or email (any 1 is mandatory) not working

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Add request
2. Enter only address information and other mandatory fields except email

**Actual/ observed behaviour/ results**
Save button disabled

**Expected behaviour**
Save button should be enabled

**Steps to Reproduce**
1. Add request
2. Enter all address information and other mandatory fields including email
3. save the request
4. open request
5. remove email and address1

**Actual/ observed behaviour/ results**
Save button enabled

**Expected behaviour**
Save button should be disabled as any 1 is mandatory

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
This bug appears to be fixed - you no longer can go around the validation
