### ISSUE TITLE
Sync Multiple Public Body Extensions of Same Type

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1845]
**Describe the bug in current situation**
 
GIVEN a user has already taken a public body extension in AXIS
WHEN the user takes additional public body extensions, of the same type in AXIS (eg. consent)
AND the user syncs the request in the new app
THEN the AXIS sync banner continues to persist
AND duplicative comments will be posted in the comment log
AND duplicate notifications will be triggered for the other assignees

**Link bug to the User Story**
#1540 

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

Medium. Ministry receives repetitive notifications if IAO analyst doesn't recognize the bug behaviour

**Chance of Occurring (high/medium/low/very low)**
Medium - High -> Often consent extensions are taken as multiples, as applicants don't necessarily consent to 30 days, they may provide consent in stages (ie: 5 days for first extension, 5 days for second)

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Add a public body extension in AXIS
2. Sync Request over to new system
3. Add an additional public body extension in AXIS, with the same public body reason (eg. Consent for extension 1 and 2)
4. Sync request to new system
5. See error - user continues to receive AXIS sync banner, and multiple comments will be posted with subsequent syncs

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 
GIVEN a public body extensions has been synced to the new system
WHEN an IAO analyst attempts to sync another public body extension with the same reason from AXIS
THEN that extension should be synced over
AND all other fields can still be synced
AND the sync banner will no longer be displayed for the extension of the same type

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
![Screen Shot 2022-04-05 at 4.23.09 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/c5098207-b3f6-4302-a5c7-ce0f2b0ea7d8)

**Comment by lmullane** [comment]
@aparna-aot, to replicate if this is still an issue.

**Comment by lmullane** [comment]
If a public body extension is over 30 days, once the sync has been dismissed the first time, the validation for that extension sync will be removed going forward (i.e., it will no longer appear as a suggested sync).

cc @sumathi-thirumani-aot, @m-prodan

**Comment by m-prodan** [comment]
@lmullane @KaraBeach @arielleandrews @divyav-aot @abin-aot 

Bug story updated to be more specific to reports we are seeing from users. I have changed the ticket to only reflect syncing requests of the same type, which appears to be what is causing this behaviour (ie: IAO takes one public body consent extension for less than 30 days, then later takes another public body consent extension). This action results in the sync banner persisting, and it generates additional comments and notifications which can confuse users.

**Comment by lmullane** [comment]
Thanks, @m-prodan

**Comment by m-prodan** [comment]
@aparna-aot - I think you are working on this? I just wrote up a new bug ticket, that might be related to this one somewhat, #2727

Essentially a user that synced multiple times, which resulted in multiple comments for the same extensions being posted, noticed that the extension count on the queue display was showing the wrong number of extensions. Specifically it was showing the same number of extensions as got posted to the comment log, despite the left nav bar and extension log only showing 1. I was able to replicate this. Will this be fixed/not an issue with this one?

**Comment by aparna-aot** [comment]
@m-prodan @lmullane @KaraBeach Please include all extension syncing scenarios while testing.

**Comment by KaraBeach** [comment]
@aparna-aot, working off of EDU-2022-00314, took two of the same extensions, PB- 20 days and PB 10 days, comments have duplicated to (5) entries.

![image.png](https://images.zenhubusercontent.com/6255c38670485846988df18c/f5e30692-db9e-4f68-ab49-0562b0fca969)

@m-prodan @lmullane - I believe there is still a bug here.

**Comment by aparna-aot** [comment]
Hey @KaraBeach Which environment did u test? I couldn't find the request in https://test.foirequests.gov.bc.ca/

**Comment by aparna-aot** [comment]
@KaraBeach Seems like you have tested in test-marshal. This fix is only in https://test.foirequests.gov.bc.ca/

**Comment by KaraBeach** [comment]
@aparna-aot - ah yes, I did do it test. My mistake.

**Comment by KaraBeach** [comment]
@aparna-aot @m-prodan @lmullane - Bug is fixed. Tested in the correct environment. ![image.png](https://images.zenhubusercontent.com/6255c38670485846988df18c/571cc3fb-3987-401f-bbe7-901abfe77569)
