### ISSUE TITLE
 Camunda WF Updates - FOI Request assignment, Status Update for Intake in Progress

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#185]
Title of ticket: 

#### Description
 Camunda WF Updates - FOI Request assignment, Status Update for Intake in Progress. @sumathi-thirumani-aot  will come up with list of APIs required. @abin-aot  will update that to capture WF instanceId . This workflow task is only for Spring Elora, till reviewing an "Unopened" request. Rest of WF update tasks will come on the subsequent sprints

#### Dependencies
Are there any dependencies?

1. Required a Design and API required  for updating WF instances and assignment
2. Once all dependencies are indicated from @sumathi-thirumani-aot , @abin-aot will develop the API to make it work/integrate

#### DOD
- [x] This task will be on top of the existing WF task done by @sumathi-thirumani-aot 
- [ ] 
- [ ] 
- [ ]

**Comment by mpilchar** [comment]
DOD updated due to Save Request coming out of scope for this sprint. Removed capture the "intake in progress" , Task assignment to person
