### ISSUE TITLE
Ministry User Group - ReDash

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1852]
Title of ticket: Ministry User Group - ReDash

#### Description
User Groups for ReDash needed for Ministry users

For the purpose of the pilot launch, the two groups should be "Economy Sector" and "Ministry of Education"

#### DOD
- [x] ReDash Security Group Created for Economy Sector
- [x] ReDash Security Group Created for Ministry of Education
- [x] Dashboard Access granted to both for - Performance Dashboard
- [x] Dashboard Access granted to both for - Received Dashboard
- [x] Dashboard Access granted to both for - Analyst Workload Dashboard
- [x] Dashboard Access granted to both for - Active OIPC Reviews Report

**Comment by divyav-aot** [comment]
@m-prodan Economy Sector is the group for below ministries right?
JERI, LBR, MUNI and TACS

**Comment by m-prodan** [comment]
That is correct @divyav-aot

**Comment by m-prodan** [comment]
@nkan-aot - testing this with foiedu@idir

I can see the required dashboards, but it is also showing all of the other dashboards that are more IAO specific. They really should only see the noted reports above, analyst workload, received, performance, and active OIPC reviews. I can also see a dashboard specific to ECON sector which seems out of place - here's a screenshot:

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/5133893a-d82d-48d0-9f76-b8f6c9a53813)



Following that - how can I do the test for economy sectors? We have a test user called foiecosect@idir - can we set that one up with redash? I don't see any dashboards if I login with that one, or the foilbr user id

**Comment by m-prodan** [comment]
Thanks for clarifying logins at standup @nkan-aot - security groups appear to be set up and distinct. Before I close this ticket though, I noticed one issue with the economy sector login for "Tom Smith" per the screenshot below on the received dashboard... some widgets are giving me permission issues ![Screenshot - Received Dashboard ECON.PNG](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/447e1e97-3795-4b85-ae59-0b2f1a8c4eba)

**Comment by m-prodan** [comment]
I figure it might be a quick permissions issue fix - I did not have the same issue with the education login.

**Comment by nkan-aot** [comment]
issue should be fixed now, may have just been my mistake when setting it up. let me know if it shows up again

**Comment by m-prodan** [comment]
Confirmed it is working - thank you @nkan-aot
