### ISSUE TITLE
Fix vulnerabilities for Request webform

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1868]
Title of ticket: 

#### Description
Fix all dependabot issues - https://github.com/bcgov/foi-requests/security/dependabot

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by acoard-aot** [comment]
I granted all devs access to view dependabot alerts here.

https://github.com/bcgov/foi-requests/security/dependabot
