### ISSUE TITLE
Unit Tests LOB API - POST , GET LIST RAW Requests

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#187]
Title of ticket: 

#### Description
Bring up a unit test framework to unit test all API endpoint and functionalities on the LOB API. Technically, going forward unit tests will be part of API development task, but this is only as a stop gap arrangement 

#### Dependencies
Are there any dependencies?
API task need to be completed

#### DOD
- [ ] Create Unit tests for POST RAW request API, GET REQUEST LIST, GET REQUEST by ID
- [ ] Add Unit Test for Save request , if doing that on this sprint.
- [ ] 
- [ ] 
- [ ]

**Comment by mpilchar** [comment]
Abin is working on error reporting for this

**Comment by acoard-aot** [comment]
Deployed in test.
