### ISSUE TITLE
Date range fixes on Advanced Search

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1871]
**Describe the bug in current situation**

**Link bug to the User Story**
Bug for #1688

**Impact of this bug**
High - Doesn't function without

**Chance of Occurring (high/medium/low/very low)**
High - Always

**Steps to Reproduce**

BUG: For the To Date, should not be able to select a date in the future
1. Go to TEST - I logged in as a Flex user but this is for all user types
2. Click on Search by Date Range and Select "Received Date"
3. Fill in "From" Date. Open "To" date - shouldn't be able to select a date past today's date

BUG: For the Closed Date, should not be able to select a date in the future
1. Go to TEST - I logged in as a Flex user but this is for all user types
2. Click on Search by Date Range and Select "Closed Date"
3. Fill in "From" Date. Open "To" date - shouldn't be able to select a date past today's date

NOTE: OIPC extensions can put the LDD quite far into the future, so we may not need a date restriction on this. Please make it consistent with other LDD date parameters elsewhere in the app

**Comment by m-prodan** [comment]
Issue appears to be fixed - all main user groups have date range pickers consistent with our other ones (ie: can't pick dates in the future, except for LDD) - closing ticket
