### ISSUE TITLE
Advanced Search "Request Description" filter button

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1874]
**Describe the bug in current situation**
Search result issues when request description button is selected

**Link bug to the User Story**
#1688

**Impact of this bug**
Moderate - Advanced Search will not function properly with this bug and all users will be impacted

**Chance of Occurring (high/medium/low/very low)**
High 

**Preconditions**
Go to TEST, login as an IAO or Ministry user

**Steps to Reproduce**
1. Go to Advanced Search
2. Click on "Search" bar and input the keyword "test"
3. Click on "Request Description" filter button
4: See error: "Apply Search" button should become active but does not, or sometimes it will but a pop up text box appears below the search bar (in this case it says "Add test") and when I click on it, the Apply Search button becomes inactives again

**Expected behaviour**
Apply search button becomes active after inputting one or more key words and selecting one of the filter buttons

**Comment by lmullane** [comment]
Thanks for the fix.
