### ISSUE TITLE
Block applicant name in advanced search for ministry users (general requests)

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1875]
* As a ministry user
* I want an advanced search to block applicant name on general search
* so that privacy is maintained

**Assumptions & Scope**	
What are the assumptions for this story?
This will be a client side validation.

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Select Personal requests and then applicant name
* GIVEN a ministry coordinator is on Advanced Search
* WHEN the coordinator selects Personal - Request Type
* AND the coordinator selects Applicant Name in the Search Criteria
* THEN the General - Request Type will be greyed out and the disclaimer error message will appear
* AND the personal request type will be greyed out and cannot be unchecked

*Scenario 2: Select General requests and the applicant name
* GIVEN a ministry coordinator is on Advanced Search
* WHEN the coordinator selects General - Request Type
* AND the coordinator selects Applicant name
* THEN Personal - Request Type will be selected, General - Request Type will be grey and disables
* AND an error message will be displayed
* AND the personal request type will be greyed out and cannot be unchecked

*Scenario 3: Select Applicant Name
* GIVEN a ministry coordinator is on Advanced Search
* WHEN the coordinator selects Applicant Name
* THEN Personal - Request Type will be  automatically selected, General - Request Type will be grey and disables
* AND an error message will be displayed
* AND the personal request type will be greyed out and cannot be unchecked

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/904797759

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, we need a quick design for this ticket before Sprint Planning tomorrow.

Essentially, a ministry coordinator should not be able to search by General  Request and Applicant Name. We need a design to handle the error messaging.

Let me know if you have any questions?

cc @mpilchar, @m-prodan, @KaraBeach, @divyav-aot

**Comment by lmullane** [comment]
@JHarrietha-AOT may want to add exception handling with error messages.

**Comment by divyav-aot** [comment]
@JHarrietha-AOT - what should be the behavior when the user clicks on general first and then Applicant Name. Currently I am making the Applicant Name not selected.

**Comment by JHarrietha-AOT** [comment]
Adding scenarios for: If a user selects applicant name first (personal always selected). If a user selects Personal & General and then selects Applicant Name (Personal selected, general greyed out with message)

Will tag when updated

**Comment by JHarrietha-AOT** [comment]
@divyav-aot I have updated the AC based on our earlier conversation, let me know if I missed anything

**Comment by divyav-aot** [comment]
Thanks @JHarrietha-AOT . This looks fine to me.

**Comment by mpilchar** [comment]
thanks for the discussion and improvements :)

**Comment by m-prodan** [comment]
@JHarrietha-AOT @divyav-aot - I am currently testing this, and I found a workaround that can still pull general requests by applicant name. In looking at the AC - technically it is all met, but I think this is an unintentional side effect.

If I select applicant name, and then uncheck personal request type, and select a specific state (ie: records review) -  I am then able to bypass the restriction and pull up a general request by applicant name. 

I wonder if we should just lock the selection to personal whenever the Ministry user selects applicant name? Seems like the cleanest way to deal with this.

Thoughts?

cc @lmullane @mpilchar @KaraBeach

**Comment by divyav-aot** [comment]
@m-prodan may be we can disable personal when applicant name is selected so that it can't be edited.

**Comment by JHarrietha-AOT** [comment]
@divyav-aot I think that is the best approach. When a Ministry user selects Applicant Name in Advanced Search then Personal is disabled and General is selected. 

@m-prodan Do we want to push this back so it is covered now or make a bug ticket?

**Comment by m-prodan** [comment]
Agreed - but just to clarify, Ministry users can search applicant name by personals  - not generals. So I do think the easiest way to handle is to just disable selecting request type, and have it locked to personals when a Ministry user selects applicant name as the criteria.

@divyav-aot - would this be a quick fix? Or should I write up a seperate ticket? Let me know, I can quickly update the AC if this is an easy change. Otherwise we'll need to write up a bug/enhancement ticket and try to get it in next sprint

**Comment by divyav-aot** [comment]
@m-prodan you can update the AC. It will be a quick fix.

**Comment by m-prodan** [comment]
AC updated @divyav-aot - putting it back into review, please let me know when it is ready to go for QA again

**Comment by m-prodan** [comment]
I can't seem to get around this one now - nice work @divyav-aot - closing ticket!
