### ISSUE TITLE
Request Detail dates not syncing for already added request

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1878]
**Describe the bug in current situation**
If the user tries to sync received date and start date at the same time as due date, user may get caught in a loop if the number of days is too large.

**Link bug to the User Story**
#1540 

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

Medium. User gets caught in a loop and is unable to make additional syncs. See EDU-2022-00237

Loop resolves when user is logged out.

**Chance of Occurring (high/medium/low/very low)**
Low. Assumption is bug is because the due date in our app is derived from the start date. Unlikely user in AXIS would make the error. Confirm with @m-prodan 

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a request in AXIS
2. Updated the received date, due date and start date.
3. Save the change in AXIS
4. Go to the same request in AXIS
5. See Warning Banner for sync
6. Click Sync Button
7. See received date change only listed in the sync modal
8. Save the sync 
9. See that the received date as not been updated
10. Click Sync again
11. See that the updated Received Date is still listed to be synced
12. Stuck without being able to make more syncs

**Actual/ observed behaviour/ results**
See above

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN an Request Detail date has been updated in AXIS
AND the analyst is on the Sync modal
WHEN the analyst clicks save 
THEN the dates will be updated on the request view
AND the dates will match the dates for the request in AXIS

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
![Screen Shot 2022-04-11 at 5.41.17 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/105bfc30-38d9-4556-9add-725d22b6f890)
<img width="987" alt="Screen Shot 2022-04-11 at 5 41 32 PM" src="https://user-images.githubusercontent.com/12040839/162857242-32860a92-bae1-44e5-a934-97a3ca54a2c0.png">

![Screen Shot 2022-04-11 at 5.39.13 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/0a220ea4-defd-4776-a939-8bebbcc2dd5f)

**Comment by aparna-aot** [comment]
@lmullane @mpilchar  I wasn't able to reproduce the specific issue mentioned in the task. Instead the bug I have noticed is that while syncing the dates, even if there is change to the Start Date, it is not displayed on the modal and while saving start date is not updating as well. I will fix that issue. If anyone could reproduce the other issue, we can connect on a call and check. Please confirm.

**Comment by lmullane** [comment]
@aparna-aot, thanks Aparna.

Even if we could reproduce I believe it is an edge; assumption is IAO analysts would not have the due date beyond 30 days from the start date.

It would be best if we leave this bug in the bug column at low priority for now in case a user reproduces it, and create a new bug ticket using the bug template for the bug you have noticed.

If you could create the bug, estimate it and fix it that would be great. Use the bug template so that we can test it properly when it reaches QA.
