### ISSUE TITLE
On Behalf of Details not syncing for already added request

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1880]
**Describe the bug in current situation**

- The first time a request is synced the 'On Behalf of Details' are synced: first name, middle name, last name
- When changes are made in AXIS to the 'On Behalf of Details' there is no banner warning or display of the changes to be synced.

**Link bug to the User Story**
#1540

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

Low. User is not blocked from other syncs and they can manually edit the On Behalf o Details in the new app/

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to to a personal request in the Flow app that has already been synced
2. Go to the same request in AXIS
3. FInd the name of the 'On Behalf of' applicant 
4. Search by 'On Behalf of' applicant name in AXIS
5. Click into the 'On Behalf of' applicants profile
6. Update any of these fields: first name, middle name, last name, date of birth
7. Save the profile changes
8. Refresh the view for the request in the Flow app
9. See no banner for a sync
10. Make another change in AXIS (e.g. Applicant Category)
11. See the sync banner in Flow app
12. Click the 'Sync' button
13. Click 'Review Changes from AXIS'
14. See the other change (e.g. Applicant Category)
15. See the no 'On Behalf of Details' changes

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

* GIVEN an IAO analyst is on the sync modal
* *AND the analyst has made updates to any of these 'On Behalf Of' fields  in AXIS: first name, middle name, last name
* WHEN the analyst clicks the 'Review Changes in AXIS'
* THEN accordion on the modal will open
* AND changes that have been made to the 'On Behalf Of' in AXIS will be displayed in a right column
* AND Field Descriptors for the updated fields will be displayed in a left column for comparison"

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by divyav-aot** [comment]
@lmullane - We can sync only On Behalf of FirstName, MiddleName and LastName. Couldn't find any column for DOB. only applicant DOB is available.

**Comment by m-prodan** [comment]
I am now able to sync OBO fields for already existing requests - bug appears to be fixed. Thanks!
