### ISSUE TITLE
Breadcrumbs for Advanced Search

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1884]
* As a ministry coordinator or IAO analyst
* I want breadcrumbs when doing an advanced search
* so that I can navigate back to my original search parameters 

**Assumptions & Scope**	
What are the assumptions for this story?

Users will want to conduct a search, check individual requests, and easily navigate back to their search results without re-entering the search criteria.

Will use material UI component.

What is IN scope?
Breadcrumbs for advanced search

What is NOT in scope?
Breadcrumbs for the rest of the app

**Acceptance Criteria**	

**Scenario 1: xxxxxx**
* GIVEN a ministry coordinator or IAO analyst has selected search parameters
* AND clicked the 'Apply Search' button
* AND search results are listed
* WHEN the user clicks on the a request listed
* THEN the request view will open
* AND a 2 layer breadcrumb will show with Advanced Search and the Request Number for the request the user is currently on

**Scenario 2: Click Advanced search breadcrumb**
* GIVEN the user is on a request found as part of an advanced search
* WHEN the user clicks the Advanced Search breadcrumb
* THEN the user will be returned to the Advanced Search view
* AND their search results will be listed
* AND the their search parameters will still be selected

**Scenario 3: xxxxxx**
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
Designed based off of pre-designed component here: https://mui.com/material-ui/react-breadcrumbs/#main-content

![Screen Shot 2022-04-12 at 12.08.09 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/5407cdc2-e0ec-4a8c-a0a1-af61e56657f2)

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
I will draft the AC as discussed.

**Comment by lmullane** [comment]
@divyav-aot, please review the AC and estimate the story.

Note, I have scoped this story for breadcrumbs for advanced search only. I do not believe we need breadcrumbs for the Queue as the search parameters are limited and easily re-entered for the queue. @m-prodan @KaraBeach, let me know if you agree?

**Comment by divyav-aot** [comment]
@lmullane , breadcrumb is not expected when we right click and open the request in a new window right?

**Comment by lmullane** [comment]
Correct, there would be no breadcrumb in that scenario.

**Comment by lmullane** [comment]
Nice work, @nkan-aot.

All AC passed. This will be a big improvement for the users to retain their search results and parameters.
