### ISSUE TITLE
Investigate feedback from Andrew regarding redash reports

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1889]
Investigate feedback from Andrew regarding redash reports

- [x] Incorrect ID showing up after request ID prefix changes from IAO to CTZ
- [x] Citizens' Services filter for Analyst Workload report not working
- [x] Filter by due date and analyst = Andrew not matching results in itest
- [ ]

**Comment by nkan-aot** [comment]
@lmullane we've identified the issue, ETL was checking for updates in AXIS db based on created date instead of modified date. @richard-aot has a fix locally but we are just waiting for some extra info from Abin on deploying to test. Will update once it's ready for Andrew to check again

**Comment by richard-aot** [comment]
Got the information from Vineet. I'm testing the fix on Dev. Will deploy to Test once everything works on Dev.

**Comment by nkan-aot** [comment]
feedback that we can address immediately has been updated in test redash. closing this issue
