### ISSUE TITLE
Unable to Move Request Past CFR To Certain States

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1899]
**Describe the bug in current situation**
Users are unable to move a request through certain states, such as CFR to Fee Estimate, CFR to Records Review.

**Link bug to the User Story**
This impacts user stories around state changes

**Impact of this bug**
Major impact - users will be unable to move a request through all of the stages of a request

**Chance of Occurring (high/medium/low/very low)**
High - easily replicated

**Pre Conditions: which Env, any pre-requisites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to any request in CFR state
2. Click on State Drop down as a Ministry user and attempt to move to fee estimate or records review
3. Save Changes
4. Request will not actually update, and remain in the CFR state

**Actual/ observed behaviour/ results**

**Expected behaviour**
Request state should change to the required one (Fee Estimate, Records review, etc.)

**Comment by m-prodan** [comment]
@divyav-aot  @aparna-aot - FYI - ticket created. Please include an estimate and treat as high priority

**Comment by mpilchar** [comment]
As I'm testing this - I think the CFR stage is showing the wrong colour.... bug or just me? @m-prodan 
![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/a8f8b83f-2379-4185-a0d6-99f40ef16d69)

**Comment by mpilchar** [comment]
In terms of the file upload - this is fixed! Thanks for the fast fix! @divyav-aot  @aparna-aot
