### ISSUE TITLE
Assigning myself to a request and synching with AXIS

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1903]
**Describe the bug in current situation**
Currently unable to assign myself as a user to a request before I have synched an AXIS number

**Impact of this bug**
Medium - It's confusing for users as they're learning the system and may erode confidence in the system

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Login as an Intake User in Test enviro

**Steps to Reproduce**
1. Set up a new request in AXIS, if needed
2.. Go to FOI Flow test environment and login as an Intake user
3. Click on Add Request
4. Enter the AXIS number (format: ABC-2022-12345)
5. Go to "Assigned to" dropdown menu and assign myself
6. Press sync with AXIS button
7. Observe: Assignment will go back to being unassigned

**Comment by mpilchar** [comment]
cc @m-prodan

**Comment by m-prodan** [comment]
syncing now no longer clears the assigned to field during the opening phase - I consider this to be fixed - thanks!
