### ISSUE TITLE
Extension Log Disappears in Certain States (On Hold, Closed)

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1905]
**Describe the bug in current situation**
When an extension is on a request, and the request moves to on hold, or closed, the extension log and the extension disappears.

When it moves to any other state, even after disappearing, the extension returns.

When this happens, even on a closed request will the banner appear and attempt to sync the extensions over, despite having already been synced. 

**Link bug to the User Story**

**Impact of this bug**
This bug will likely confuse users, and make them unsure what happened to their extensions, they may attempt to sync multiple times and be unsure why it continues to not show

**Chance of Occurring (high/medium/low/very low)**
High - many requests have extensions and this will result in extensions not showing on closed requests if someone were to review the request later. 

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to any request with an extension on it
2. Change state to On-Hold, or closed
3. Scroll down to extension log
4. Extension log will be disappeared.

**Actual/ observed behaviour/ results**
Extension log is not visible when in closed, or on-hold state. 

**Expected behaviour**
Extension log should always be visible, regardless of state.

**Comment by aparna-aot** [comment]
@m-prodan Extension Log Disappearing in Certain States (On Hold, Closed) is done as part of a requirement in the extensions ticket #858. It was mentioned like "Extensions will not be visible or possible to action in Unopened, Intake in Progress, Redirect, On Hold or Closed states. "
And in regard with the axis sync banner, displaying the banner if extensions are out of sync for these states can be confusing so I will update it such that for the mentioned states, extension sync alone won't be checked and banner or modal won't appear with respect to extensions.
Please confirm. Thanks!

**Comment by m-prodan** [comment]
Thanks @aparna-aot ! I think there may have been a slight mistake in writing out that AC... and perhaps a bit of a miss in QA testing. You definitely shouldn't be able to create an extension in those states, but if any extensions had been taken, the log should still be visible and shows that. Are you able to update that?

**Comment by aparna-aot** [comment]
Yes @m-prodan . I can update that. But I need some clarifications regarding axis sync for that states as well. So shall we connect over a call to discuss that when you are free?

**Comment by m-prodan** [comment]
Nice work @aparna-aot  - closing this and the related ticket :)
