### ISSUE TITLE
State change comments from intake to redirect sometimes don't show

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1908]
State change comments from intake to redirect sometimes don't show
![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/6ac2ea2d-62ad-434d-8ef7-7102c804230e)
If user refreshes, then comment will show. Likely a race condition with async calls in backend between creating the comments and sending new workflow instance to front end

**Link bug to the User Story**

**Impact of this bug**
low, users will still see comments the next time they go to request
impacts automated testing since behaviour is unpredictable

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
create request -> intake stage -> redirect. May need to try a few times

**Actual/ observed behaviour/ results**
No state change comment from intake to redirect

**Expected behaviour**
A state change comment should show from intake to redirect

**Comment by m-prodan** [comment]
I've attempted to replicate this bug across both personal and general requests. Switched from Intake in Progress to Redirect and back and forth repeatedly (approx 5-6 times on each request). Unable to replicate, will consider this fixed!
