### ISSUE TITLE
Accessibility Updates - Queue

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1927]
Title of ticket: Accessibility Updates - Queue

#### Description
Resolve all accessability "errors" as identified by WAVE extension for the Queue - https://wave.webaim.org/extension/

Critical Changes to Queue that were identified through Running Accessibility Tests on Queue Page

#### Dependencies
No dependencies.

![Screen Shot 2022-04-19 at 4.31.14 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/70df2090-e37a-4cd6-8b7c-a73b1b3af579)

#### DOD
- [ ] All critical issues resolved or captured in new tasks
- [ ] Aria labels added to buttons
- [ ] Empty link resolved
- [ ] Empty button
- [ ] Contrast errors fixed
- [ ] Alerts reviewed and fixed if possible

**Comment by acoard-aot** [comment]
Updated description and DOD.

**Comment by JHarrietha-AOT** [comment]
All critical changes have been fixed. Great Work @divyav-aot & @richard-aot
