### ISSUE TITLE
Accessibility Updates - Request Details IAO

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1928]
Title of ticket: Accessibility Updates - Request Details IAO

#### Description
Critical Changes to Queue that were identified through Running Accessibility Tests on Request Details IAO

Use Wave extension to verify issues are resolved - https://wave.webaim.org/extension/

#### Dependencies
No

![Screen Shot 2022-04-19 at 4.32.30 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/0f8f8b28-4fe2-476a-bd4f-793317183ba4)

![Screen Shot 2022-04-19 at 4.32.36 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/92128a2c-762e-4b82-8766-cfd022e6ee44)

#### DOD
- [ ] Empty heading fixed
- [ ] Empty link fixed
- [ ] Missing form labels fixed
- [ ] Aria reference fixed
- [ ] Contrast errors fixed
- [ ] Alerts reviewed and fixed if possible

**Comment by acoard-aot** [comment]
Description and DOD updated.

**Comment by aparna-aot** [comment]
Updated the estimate as this task involves checking accessibility for different functionalities like extensions ,axis sync etc. like opening the modal and checking for issues. Also it involves left panel color changes for some of the state updates and color changes for warning signs as well.
New color codes will be shared by @JHarrietha-AOT .

**Comment by JHarrietha-AOT** [comment]
@aparna-aot Replace the red for required fields with this darker red #9E2929

**Comment by JHarrietha-AOT** [comment]
@aparna-aot Here's the new colours, let me know if you have any questions. And can we do a round of UX Assurance to see each one on the left nav when its ready?

![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/6e53b9c3-f4f9-4a50-b613-bf34d5d3964b)

**Comment by aparna-aot** [comment]
Sure @JHarrietha-AOT . I will let you know. Thanks!

**Comment by JHarrietha-AOT** [comment]
All critical changes have been fixed. Great Work @divyav-aot & @aparna-aot
