### ISSUE TITLE
Accessibility Updates - Request Details Ministry User

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1929]
Title of ticket: Accessibility Updates - Request Details Ministry User

#### Description
Critical Changes to Queue that were identified through Running Accessibility Tests on Request Details Ministry User

Use WAVE extension - https://wave.webaim.org/extension/

#### Dependencies
No

![Screen Shot 2022-04-20 at 11.40.05 AM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/3cfc651b-d717-485f-a43d-cade34f75335)

![Screen Shot 2022-04-20 at 11.40.11 AM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/068792ff-d93a-4a98-9bb7-3cb606e5ef33)

#### DOD
- [x] Missing form labels fixed
- [x] Empty heading fixed
- [x] Empty buttons fixed
- [x] Empty links fixed
- [x] Aria references fixed
- [ ] Contrast errors fixed
- [ ] Alerts reviewed and fixed if possible

**Comment by acoard-aot** [comment]
Description and DOD updated.

**Comment by JHarrietha-AOT** [comment]
All critical changes have been fixed. Great Work @divyav-aot & @nkan-aot
