### ISSUE TITLE
Accessibility Updates - Attachment Page

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1930]
Title of ticket: Accessibility Updates - Attachments

#### Description
Critical Changes to Queue that were identified through Running Accessibility Tests on Attachment Page

Use WAVE extension: https://wave.webaim.org/extension/

#### Dependencies
No dependencies.

![Screen Shot 2022-04-20 at 11.41.38 AM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/66f43785-7d85-4152-a6d6-3b123d76142c)

#### DOD
- [ ] Missing form labels fixed
- [ ] Empty heading fixed
- [ ] Empty button fixed
- [ ] Empty link fixed
- [ ] Aria references fixed
- [ ] Contrast errors fixed
- [ ] Alerts reviewed and fixed if possible

**Comment by acoard-aot** [comment]
Description and DOD updated.

**Comment by nkan-aot** [comment]
tested with attachment upload modal open and multiple attachments in list, no more errors or contrast errors. closing issue
