### ISSUE TITLE
Accessibility Updates - Comments Page

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1931]
Title of ticket: Accessibility Updates - Comments

#### Description
Critical Changes to Queue that were identified through Running Accessibility Tests on Comments Page

Use WAVE extension: https://wave.webaim.org/extension/

#### Dependencies
Are there any dependencies?

![Screen Shot 2022-04-20 at 11.49.08 AM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/b4234c03-55f0-4221-9452-01afbb7ebdc4)

#### DOD
- [ ] Missing form labels fixed
- [ ] Empty heading fixed
- [x]  Empty button fixed
- [ ] Empty link fixed
- [x] Aria reference fixed
- [x] Contrast errors fixed
- [x] Alerts reviewed and fixed if possible

**Comment by acoard-aot** [comment]
Description and DOD updated.

**Comment by nkan-aot** [comment]
all errors and contrast errors fixed except for the ones noted in comment above. closing this issue
