### ISSUE TITLE
Remove 'Select Ministry Client' #1113

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#1933]
* As an IAO analyst
* I want to only see the selected ministry name displayed once a request goes into Open or beyond
* so that I only see the relevant information based off of my user group

**Assumptions & Scope**	
What are the assumptions for this story?

Analyst do not change the ministry selected once a request goes into the CFR state.

What is IN scope?
Removing the select ministry checkboxes from the IAO request view once a request goes into the Open state

What is NOT in scope?

Changes to the ministry request view.

**Acceptance Criteria**	

**Scenario 1: IAO analyst views request in Open state or beyond*
* GIVEN a request is in the Open state or beyond
* WHEN the IAO analyst clicks on the request 
* THEN the request view will show the selected ministry
* AND there will be no checkboxes to select a different ministry

**Scenario 2: IAO analyst changes a request to Open state*
* GIVEN a request is on an open request
* WHEN the IAO analyst changes the state to Open 
* THEN only the ministry name should be displayed
* AND the ministry checkboxes to select a different ministry will no longer appear

- [ ] Remove 'Select Ministry Client' section and just display selected Ministry

**Comment by lmullane** [comment]
@richard-aot, @m-prodan, for testing purposes could you please review the user story and AC to ensure I have accurately captured the change?

My recollection is that it is the change to the CFR state that triggers the change, but it may have been the Open state?

**Comment by m-prodan** [comment]
@lmullane  It should technically be from the Open state, onwards. At that point it will be with flex or processing team, so they won't need to see all the checkboxes

**Comment by richard-aot** [comment]
Thanks, @lmullane and @m-prodan.

It is implemented for Open state onwards. Will push to test this morning.

**Comment by lmullane** [comment]
Great, thanks.

**Comment by lmullane** [comment]
Works as expected.
