### ISSUE TITLE
UX Design - Update to Collapsable Design

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1939]
Title of ticket: UX Design - Update to Collapsable Design

#### Description
Update design on Request Information Page to be Collapsable/Accordion Style Windows for ease of use, and have some sections pre-collapased based off of stage of request

#### Dependencies
React Pre-made accordions should be able to be used with each block being its own accordion with padding in-between to maintain look page has now.

#### DOD
- [x] Create Design
- [x] Review Design
- [ ] Make new Ticket for Dev Task to Update

**Comment by JHarrietha-AOT** [comment]
@lmullane @m-prodan Below are the collapsable section designs. For use of time I have not updated all designs to be collapsable but will work on that in conjunction with other work.

Link to all accordions expanded: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852

Link to default accordions closed based on CFR Stage: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/908679737

Material UI Link to include in dev ticket creation: https://mui.com/material-ui/react-accordion/

**Comment by lmullane** [comment]
Thanks, @JHarrietha-AOT 

@KaraBeach  and @m-prodan, propose that the default will be that Applicant Details and Contact Info are collapsed like in this design and AXIS: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/908679737

Do you agree?

**Comment by JHarrietha-AOT** [comment]
@lmullane I would agree that it is those two sections that are default collapsed. 

@m-prodan @KaraBeach I am thinking they should these be a default of collapsed after Intact is complete and handing off to the next team as they would be to core people who need to use these sections. Would this been once the request is in the Open State or CFR State?

**Comment by JHarrietha-AOT** [comment]
Closing Ticket based off of understanding and completion of design changes
