### ISSUE TITLE
Personal FOI Request Attachments

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#194]
* As an intake analyst
* I want to be able to review attachments included with personal FOI Request submissions
* so that I can review them and confirm eligibility.

**Assumptions & Scope**	
This story will cover the user experience for how personal requests that have attachments through the online form are handled by the application. 

Acceptance criteria will cover how each uploaded attachment through the form will be handled. 

Only IAO users will have access to these attachments
Ministry coordinators can see the files, but will be unable to download/take actions on these specific attachments.

**Acceptance Criteria**	

**Scenario 1: Proof of Guardianship**
* GIVEN an applicant has uploaded a document through the personals online web form, for proof of guardianship of a child
* WHEN the request is submitted
* THEN the guardianship document will appear in the attachment log

**Scenario 2: Proof of Authority**
* GIVEN an applicant has uploaded a document through the personals online web form, for proof of authority to request on behalf of another person
* WHEN the request is submitted
* THEN the guardianship document will appear in the attachment log

**Scenario 3: Access Restricted to IAO Users**
* GIVEN an attachment from a webform to a personal request is in the attachment log
* WHEN a Ministry Coordinator is on the attachments page
* THEN the ellipses for those attachments will be disabled
* AND the file name will be greyed out

**Scenario 4: Unable to Delete Attachments**
* GIVEN an IAO user is on the attachment log of a personal request
* WHEN they click on the ellipses of an attachment received through the online form
* THEN the only option available will be "Rename" and "Download"

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Tried my hand at writing out the user story for this one - appreciate any feedback @mpilchar @arielleandrews  . I believe we need some UX designs to go into this as well @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
@m-prodan we do need UX for this, I will have the designs completed for backlog refinement on Friday

**Comment by mpilchar** [comment]
@JHarrietha-AOT any updates needed design-wise for scenarios 1 & 2?

**Comment by JHarrietha-AOT** [comment]
@mpilchar Yes, just trying to work through things priority wise, so working on report out so thats ready for demo. Hoping to finish up prototype updates tomorrow before backlog refinement. QA just took up time this sprint that we didn't account for when pulling in UX issues to complete.

**Comment by mpilchar** [comment]
@JHarrietha-AOT Makes perfect sense and thanks for the share/reminder

**Comment by m-prodan** [comment]
@arielleandrews - I thought I had something written about personal request attachments - likely needs to be updated to match how things currently work for us

**Comment by m-prodan** [comment]
Updated this story to cover attachments to personal requests through the online form. A couple things I added:
1) Ministry coordinators will not have functional access to these requests (AC 3), I also included that we should not be allowed to delete or replace these files - only option is to rename (AC 4). 

I also included auto-naming of the file (AC 1 and 2)

Feedback welcome! @lmullane @arielleandrews @JHarrietha-AOT @mpilchar

**Comment by mpilchar** [comment]
@m-prodan @richard-aot I'm in the process of testing this and don't see the naming convention in the attachment log that's mentioned in AC 1&2. Did we discuss modifying but forget to capture the decision by chance?

**Comment by richard-aot** [comment]
Good catch @mpilchar. I missed the renaming part. This is fixed on my local. Will deploy to dev and test tomorrow morning.

**Comment by mpilchar** [comment]
Thanks @richard-aot! One other thing for consideration - I was also looking at #586 and noticed that when I hover over the ellipses of a system generated comment, there is a "not permitted" symbol that appears. I wonder if, for consistency, we should have something similar when the ellipses is disabled on personal files. Let's discuss, and happy to create a tech debt ticket if that's the route we want to take

**Comment by mpilchar** [comment]
We have determined A/C will be modified separate the naming and categorization of the file when it is uploaded.  @abin-aot and @acoard-aot will be collaborating in the new year to re-configure the openshift setting for our angular app. It will be much easier to deploy the rename feature after they finish the configuration. I will create a new issue to capture this change, and tag it with the Jan 18 sprint so we remember to implement. cc: @lmullane @m-prodan @arielleandrews @richard-aot
