### ISSUE TITLE
Pre-Production: Migrate Data (PayBC)

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/foi-flow#1940]
Title of ticket: Pre-Production: Migrate Data (PayBC)

#### Description
During pre-production setup, we decided to create a new DB.  This lead to the unanticipated work of having to migrate PayBC data in both test and prod.  

This is essentially an un-scoped step that we need to do to harmonize between the payment-integration environments and our normal test environments.  Sumathi has already done it on the code level, but now it has to be done on the DB level.

#### Dependencies
No

#### DOD
- [x] Test database migrated over, `FOIRawRequests`, `Payments`, `FeeCodes`, `RevenueAccounts`
- [x] Both data and indexes align with previous DB
- [x] Integration between pay-integration and "normal" test environments are complete
- [x] Change pay-integration frontend to submit to "normal" test environment and confirm paybc integration working with receipt generation (end to end test).
- [x] Production data migrated over to `patroni-002`, `FOIRawRequests`, `Payments`, `FeeCodes`, `RevenueAccounts` (same as first DOD but for prod)

**Comment by mpilchar** [comment]
This is a day-of production task as it involves the migration of data
