### ISSUE TITLE
Start date not syncing for already added request

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#1941]
**Describe the bug in current situation**
Start date updates from Axis are not synced with the request.

**Link bug to the User Story**
#1540

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
High
**Pre Conditions: which Env, any pre-requisites or assumptions to execute steps?**

**Steps to Reproduce**

1. Go to a request in AXIS
2. Update the received date, due date and start date.
3. Save the change in AXIS
4. Go to the same request in AXIS
5. See Warning Banner for sync
6. Click Sync Button
7. See the start  date change not listed in the sync modal.
8. Save the sync
9. See that the start date as not been updated.

**Actual/ observed behaviour/ results**
See above
**Expected behaviour**
GIVEN an Request Detail date has been updated in AXIS
AND the analyst is on the Sync modal
WHEN the analyst clicks save
THEN the dates will be updated on the request view.
AND the dates will match the dates for the request in AXIS.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KaraBeach** [comment]
Expected behavior functions as it should.  @aparna-aot nice job, thank you!
