### ISSUE TITLE
Collapsable sections on Request View

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1942]
* As an IAO analyst
* I want to be able to collapse sections of the request view
* so that I only see information that is important to me

**Assumptions & Scope**	
What are the assumptions for this story?

We will use Material UI: https://mui.com/material-ui/react-accordion/

Collapsable sections are in AXIS and have been requested for the new app by the business.

What is IN scope?

Collapsable sections for the IAO request view.

Personal and General requests.

What is NOT in scope?

Collapsable sections for the ministry request view.

**Acceptance Criteria**	

**Scenario 1:  PROCESSING ANALYST - GENERAL REQUEST - Applicant Details and Contact Information closed by default**
* GIVEN an IAO PROCESSING analyst is on their queue or advanced search
* WHEN the analyst clicks on a GENERAL request
* THEN the request view will be displayed
* AND there will be BC Blue line with an arrow for each section of the request (e.g. Applicant Details, Request Description, Extensions, etc,.)
* AND Applicant Details and Contact Information will be closed by default
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/908679737

**Scenario 2:  PROCESSING ANALYST PERSONAL REQUEST - Contact Information and Child Details will be closed by default**
* GIVEN an IAO PROCESSING analyst is on their queue or advanced search
* WHEN the analyst clicks on a PERSONAL request
* THEN the request view will be displayed
* AND there will be a BC Blue line with an arrow for each section of the request (e.g. Applicant Details, Request Description, Extensions, etc,.)
* AND Contact Information and Child Details will be closed by default

**Scenario 3:  INTAKE ANALYST - no sections closed by default**
* GIVEN an IAO INTAKE analyst is on their queue or advanced search
* WHEN the analyst clicks on a PERSONAL request
* THEN the request view will be displayed
* AND there will be a BC Blue line with an arrow for each section of the request (e.g. Applicant Details, Request Description, Extensions, etc,.)
* AND no sections will be closed by default
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852

**Scenario 4:  FLEX ANALYST - Contact Information closed by default**
* GIVEN an IAO INTAKE analyst is on their queue or advanced search
* WHEN the analyst clicks on a PERSONAL or a GENERAL request
* THEN the request view will be displayed
* AND there will be a BC Blue line with an arrow for each section of the request (e.g. Applicant Details, Request Description, Extensions, etc,.)
* AND Contact Information will be closed by default

**Scenario 5: Close a request section**
* GIVEN an IAO analyst is on a request
* AND a section is visible (e.g. Request Description)
* WHEN the analyst clicks on the BC Blue line
* THEN the request section will close
* AND the request fields for that section will not be visible

**Scenario 6: Open a request section**
* GIVEN an IAO analyst is on a request
* AND a section is not visible (e.g. Applicant Details)
* WHEN the analyst clicks on the BC Blue line
* THEN the request section will open
* AND the request fields for that section will be visible
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
[@xxx - please link the Design here](https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852)

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
I have confirmation from the business that they want Applicant Details and Contact Information closed by default. 

Confirming if Intake and Flex wants something different.

cc @m-prodan, @KaraBeach

**Comment by lmullane** [comment]
Clarified and captured preferences of Intake and Flex in AC.

**Comment by sumathi-thirumani-aot** [comment]
@JHarrietha-AOT  The grey color looks disabled. can we go with standard BCGOV blue.

**Comment by JHarrietha-AOT** [comment]
@sumathi-thirumani-aot For sure, I'll update the designs

**Comment by JHarrietha-AOT** [comment]
@sumathi-thirumani-aot Designs are updated in the links above based on your suggestion. Thanks

**Comment by JHarrietha-AOT** [comment]
Closing ticket based off of changes to design and understanding in refinement.

**Comment by lmullane** [comment]
@divyav-aot, processing team has just asked the the Child Details be closed by default.  I've updated AC 2 accordingly.

**Comment by nkan-aot** [comment]
all ACs passed, good job @aparna-aot!
