### ISSUE TITLE
Angular Webform and Application Update - new Public Body - DAS

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1948]
Title of ticket: Angular Webform and Application Update - new Public Body Code - DAS (Declaration Act Secretariat)

#### Description
The Ministry of Indigenous Relations and Reconciliation has created a new secretariat, that they want to be tracked by a different Ministry code. It will be called the Declaration Act Secretariat

#### Dependencies
Are there any dependencies?

### Assumptions
DAS will be a subsidiary of IRR - similar to how EMB is a subsidiary of PSS, and PSA and GCP are subsidiaries of FIN

For the purposes of the application fee - the behaviour for the fee calculation should therefore mean that if IRR and DAS are both selected, the applicant will only be charged a single 10 dollar fee.

For the purposes of reporting, any FOI related metrics for DAS should be captured under IRR as a whole.

#### DOD
- [ ] Update webform to include Declaration Act Secretariat
- [ ] Update foi flow app to include Declaration Act Secretariat
- [ ] Update codes in foi flow app to link Declaration Act Secretariat to DAS

**Comment by KyEggleston** [comment]
Closed, as this has been resolved on the webform, and DAS is onboarded. Decision was made for DAS does have their own reporting. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/a57edbff-5e91-4753-b6fe-3c660f5cd658)


![image](https://github.com/bcgov/foi-flow/assets/117312323/d40efa8d-a788-4e27-8321-f1853d03d0c2)
