### ISSUE TITLE
UX Research - Pilot Ministries Research with Coordinators

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1960]
UX Research - Pilot Ministries Research with CoordinatorsTitle of ticket: 

#### Description
UX Research with two Pilot Ministry Coordinators. To cover Processing Fees Design,  Questions about Desired Updates to Divisional Tracking, and Review Existing Process and Desire for Requests that have requested the same records

#### Research Plan and Study Guide
- [x] Draft Research Plan
- [x] Review and Finalize Research Plan
- [x] Draft Study Guide
- [x] Review and Finalize Study Guide

#### Book 1 hour sessions, set expectations that we may not use the full hour.
- [x] Book sessions (Molly)
- [x] Session with EDUC (Carrie)
- [x] Session with ECON (Vicki)

#### Actual Sessions Completed
- [x] Session with EDUC (Carrie)
- [x] Session with ECON (Vicki)

#### Report Out on Sessions
- [x] Create Report Out
- [x] Present Report Out at Demo

**Comment by JHarrietha-AOT** [comment]
To include in Research - Process of harms not being met by some divisions which is leading then do records review and harms at the same time and at the end which is leads to new redlines needing to be creating in IAO.

Build this into Ministry Reporting Research research

**Comment by JHarrietha-AOT** [comment]
To include in Research - Research into better understanding what users needs are for tracking Requests (HTH brought up this issue)

**Comment by JHarrietha-AOT** [comment]
STUDY GUIDE:  https://bcgov.sharepoint.com/:w:/t/03521/ES-HGDUthUpJnzGClceJs1kB7oq0OwmBj3CgD-jt2k7V0g?e=ksODZO

**Comment by JHarrietha-AOT** [comment]
RESEARCH PLAN: https://bcgov.sharepoint.com/:w:/t/03521/EcfyCoq71ONMqrd6Es8WH7oBN3iMDj2rcPAgsCnE95u1wg?e=kSzehr

**Comment by JHarrietha-AOT** [comment]
@m-prodan & @lmullane Here is a link to the new fess tab, and the undated OI section. Let me know if either of you have any questions?

https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803

cc: @mpilchar @abin-aot

**Comment by m-prodan** [comment]
Thanks @JHarrietha-AOT - presented it to managers and got some good feedback which I will share with you, I expect we'll see a good turnout tomorrow so hopefully more good discussions at demo!
