### ISSUE TITLE
Log Out from Queue

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#197]
**Describe the bug in current situation**
When user tries clicks on Log Out button, (top right hand corner of the queue screen) they are taken to an error screen.

Error Message Showing
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault>SOAP-ENV:ClientSOAP Processing Error. Exception processing request</SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

**Link bug to the User Story**

**Impact of this bug**
User is unable to log out successfully

**Chance of Occurring (high/medium/low/very low)**
High - happening for both Jacklyn and Matt

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Log in with IDIR
2. Wait for Queue to Load
3. Click on Log Out

**Actual/ observed behaviour/ results**
After conversation with Abin is appears to be a permission issue. We will troubleshoot and fix so all users who log in will be able to Log Out

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
![Screen Shot 2021-07-14 at 6.14.29 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/3efe910f-2909-4ae5-a235-a1b4d315e3f4)

**Comment by JHarrietha-AOT** [comment]
@m-prodan created bug here and assigned to @abin-aot we can meet tomorrow to troubleshoot together.

**Comment by sumathi-thirumani-aot** [comment]
**Fix Details:**
The expected role to be associated with staff must be reviewer.
Made changes in realm.

Can you please retest.
