### ISSUE TITLE
Searching Attachments

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1974]
* As an IAO user or ministry coordinator
* I want to be able to easily search for attachments within the request itself
* so that I can find the information that is important to me

**Assumptions & Scope**	
* Default filter within the attachments tab will be set to "All"
* The search function searches the file name, badges, and usernames for attachments
* Search will function same as the search within the request queue - as users start typing the results filter down, do not need to press enter
* Search results will depend on what filter has been selected, i.e. when "Applicant" filter has been applied then search is only searching within the attachments that have the Applicant badge

What is IN scope?

What is NOT in scope?
* Attachment filters. This will be covered by a separate ticket #2470

**Acceptance Criteria**	

**Scenario 1: Search attachments - All filter applied**
* GIVEN a user is on the attachments tab of a request
* WHEN the user clicks in to the Search bar
* AND the user starts typing a search term 
* THEN the attachments displayed will narrow based on the search term 

**Scenario 2: Search attachments - General, Applicant, Extensions or OIPC filter applied**
* GIVEN a user is on the attachments tab of a request
* AND the user has selected any of the filters General, Applicant, Extensions, or OIPC
* WHEN the user clicks in to the Search bar
* AND the user starts typing a search term 
* THEN the search will only apply to the already filtered attachments
* AND the attachments displayed will narrow based on the search term

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813733

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
Suggested by Neva Everitt during pilot leadup

**Comment by JHarrietha-AOT** [comment]
Passed UX Assurance Thanks for the Quick Changes @abin-aot & @richard-aot

**Comment by lmullane** [comment]
All AC passed. Thanks, @richard-aot
