### ISSUE TITLE
Create an FAQ document

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1977]
Title of ticket: 

#### Description
This document will serve as a reference guide for users who have questions about the scope and utility of the new FOI system. It  will compliment training and should be shared as part of training, prior to pilot launch, as a tool to support users as they learn the new system

#### DOD
- [x] Identify topic areas to cover (team)
- [x] Initial running draft of the document (Kara)
- [x] Review by team/PO
- [x] Final working copy
- [x] Circulate with users

**Comment by mpilchar** [comment]
@KaraBeach - How is this going? Do we think we can get it drafted/reviewed/uploaded for Pilot?

**Comment by lmullane** [comment]
Thanks, @KaraBeach. Will review and make suggested edits in track changes.

**Comment by m-prodan** [comment]
Posted to FOI Support channel today!
