### ISSUE TITLE
SSO protection for Documentation (viewers) in NextJS

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/foi-flow#1984]
Title of ticket: SSO protection for Documentation (viewers) in NextJS

#### Description
The actual content of documentation should be behind SSO too.  This is for view access of the content.  Any IDIR is sufficient. 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] SSO implemented in NextJS for staticly generated documentation

**Comment by acoard-aot** [comment]
Deployed to dev, https://foi-help-frontend-dev.apps.silver.devops.gov.bc.ca/help-articles
But need to get envs for test and tidy up OCP yaml.

**Comment by arielleandrews** [comment]
@acoard-aot this is the error message I receive when trying to log in with my idir: ![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/d277bd63-819d-445e-8a00-50406b4900d6)

**Comment by acoard-aot** [comment]
Definitely a bug, I think I know what it is, thank you for the screenshoot it really helped.

**Comment by JHarrietha-AOT** [comment]
@acoard-aot Can you tag @arielleandrews & I when this is fixed so we can test it and moved to closed

**Comment by acoard-aot** [comment]
@JHarrietha-AOT @arielleandrews please test prod, for some reason dev is down but prod should be working.

https://foi-help-frontend-prod.apps.silver.devops.gov.bc.ca/

**Comment by JHarrietha-AOT** [comment]
@arielleandrews it works for me know, with the link above. Let me know if you want to check as well then we can move to closed

**Comment by acoard-aot** [comment]
Will do!
