### ISSUE TITLE
Sign In/Sign Out Intermediate Pages

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#199]
Keycloak Login - Experience an additional sign-in page before the IDIR login page. 

Related to Issue: #35

### Log In
![Screen Shot 2021-07-16 at 2.31.03 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/383e0a6d-dfa7-4042-ad53-78a25dbc04f1)
Ideal: Remove this page and have it directly go to BC Gov IDIR Login Page
Next best: Redesign this page to feel more inline with app

### Log Out
Briefly Shows 'Welcome, Username' and then goes to 'Welcome, Sign In' Page. Can we remove the loading of the 'Welcome, Username' as it appears long enough for it to be read. If we need to have something it would be better to show loading animation then have this screen 

DOD
- Determine configuration - login
- When user clicks login link, they are brought to IDIR page (not keycloak page)
- Verify / test login
- When user clicks logout, user returns to login page (remove text Welcome Username)

**Comment by acoard-aot** [comment]
Technical notes, I believe this contains the fix I was thinking of.  It's a "hint", i.e. idp_hint.

https://stackoverflow.com/questions/46390571/how-to-bypass-keycloak-login-form-and-jump-directly-to-the-idp-login

**Comment by m-prodan** [comment]
This appears to be fixed, I no longer go to the intermediary page when I login (tried on all 3 common browsers). Sign-out also functions as expected now - closing ticket!
