### ISSUE TITLE
UX Update - Help Icon/Button

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1991]
Title of ticket: UX Update - Help Icon/Button

#### Description
Create Design for Help Button

#### Dependencies
Are there any dependencies?

#### DOD
- [x] a Help Icon
- [x] Link to Help from foi-flow
- [x] Link to Help from foi-doc-reviewer

**Comment by JHarrietha-AOT** [comment]
@lmullane This design has not been created, it been a low priority and other design this have always take priority over it. Would you like me to try and get it in this or next sprint?

**Comment by lmullane** [comment]
Hi @JHarrietha-AOT, let us know when you have a design for us to review!

cc @katrinaferacini  @m-prodan

**Comment by JHarrietha-AOT** [comment]
@m-prodan @liseandtea 

Curious what the two of you prefer.
Option 1 - larger typical style of help - would float on the right side of the screen in the FOI MOD app, and you be apart of the top nav in the redaction app(there isnt alot of space in the app) - could find a spot for it to float as just the ? icon and not the words too. With this design in the future I see it being clickable and could expand down with option that are specific to the section of the app the user is currently in
![help 1.jpeg](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/81dc05c0-81e6-43d0-9f10-46870e5c3fa8)
![Keyword Copy.jpg](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/cff4ba89-ad9b-47e7-b205-6b91cf543fa4)

Option2 - add it to the top nav beside reports - could be in the same spot across both app. Is much smaller and less like typical help icons. Could do dropdown similar to notifications in the future with recommendations based on section user is in. 
![Keyword.jpg](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/6c24b267-7930-4f39-bf1c-9cd33d400594)

For the time being both would just open a new tab and take you to the home page of help. Let me know which you prefer and if you have any questions

**Comment by m-prodan** [comment]
Personally I like option 2 - mostly because it seems to fit in that section in my opinion. I also like the idea of that future iteration of it being an eventual dropdown to related videos

**Comment by JHarrietha-AOT** [comment]
Great! Option 2 is defiantly less intrusive considering how many things we have on a screen at a given time. I will update the headers across the designs. And when we write the ticket for the devs I think default right now is you click and it opens in a new tab. And next iteration can be dropdown with most popular or videos related based on what stage the request that you currently have open, is in.

**Comment by liseandtea** [comment]
I agree with Matt for the same reasons.

**Comment by JHarrietha-AOT** [comment]
@m-prodan Designs are updated across the app to include the help icon in the top nav bar - I will close this ticket and leave it in yours or @liseandtea or @KyEggleston to write the technical story
