### ISSUE TITLE
Update ETL package 'factRequestDetails' after upgrade to AXIS 10.7

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#1992]
DoD

- [x] Update ETL package to retrieve 'refvisualrequestfilenumber' by calling function 'AFX_GetReferenceRequests'

Please note, the script is updated in Reop already. Just need to get the latest etl package from repo and deploy to test etl env.

**Comment by mpilchar** [comment]
This wlil not happen until we upgrade to 10.7 (summer)

**Comment by m-prodan** [comment]
Note: hearing that 10.7 is coming, potentially around Sep 23 or 30 - bringing this one a little closer up to the top of the backlog for visibility. Natalie will keep us posted when a date for the change is confirmed.

cc: @abin-aot @lmullane
