### ISSUE TITLE
Processing Team Queue Update (Unassigned Requests)

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#1994]
* As a team lead or request assigner with the processing team
* I want to be able to easily see when a new request has entered my team's queue 
* so that I can assign a request more quickly

**Assumptions & Scope**	
This story reflects the need for the processing team to better identify when new requests need to be assigned to an analyst. This will function similar to how we have the blue hues set up for Flex Team/Ministry teams, but operate differently. 

What is IN scope?
Processing team queues behaviour regarding requests assigned to the team level, not user. 
Sorting of the queue (sort by LDD as default), and the change of colour of the row.
Consider state

**Acceptance Criteria**	

**Scenario 1: Request Assigned to Processing Team (not a user)**
* GIVEN a FOI Request has been assigned to a processing team 
* WHEN a processing team user looks at 'My Team's Requests'
* THEN all requests assigned to the team will appear
* AND the requests NOT assigned to a user will appear at the top
* AND the row will appear with a light blue hue, consistent with functionality for flex team/Ministry team
* AND the remaining, assigned requests will appear in the order from oldest to newest by legislative due date

**Scenario 2: Request assigned from processing team to a user**
* GIVEN a FOI request is assigned to a processing team
* WHEN the request is assigned to a user
* THEN the request will no longer have a blue hue
* AND the request will be sorted with the remaining assigned requests, in order from oldest to newest by legislative due date. 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by nkan-aot** [comment]
scenario 2 has passed, but there seems to be some instances where the remaining assigned requests are not sorted by due date. Moving back to in progress
![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/5eb0cf38-72f0-475c-8245-91a3e2e66936)
![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/bb470081-f8f1-4d9c-b2b1-4647dddfd8ea)

**Comment by mpilchar** [comment]
Love that you're catching this and ensuring quality @nkan-aot - nicely done

**Comment by lmullane** [comment]
Great stuff, @nkan-aot.

AC passed as expected.
