### ISSUE TITLE
Sonar Cloud Code quality (backend)

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1997]
Title of ticket: 

#### Description
This covers all things reported on BCGov sonar cloud
https://sonarcloud.io/project/issues?languages=py&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=bcgov_foi-flow

#### DOD
- [x] make fixes
- [x] Confirm fixes 
- [ ] 
- [ ] 
- [ ]

**Comment by sumathi-thirumani-aot** [comment]
No of reported issues -> 20

**Comment by sumathi-thirumani-aot** [comment]
A general sanity is sufficient.

**Comment by sumathi-thirumani-aot** [comment]
Python reported issues are addressed.
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/0714c8f5-af70-468d-bf54-09de17f00312)

**Comment by lmullane** [comment]
Complete.
