### ISSUE TITLE
Block multiple save request option

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#2018]
Title of ticket: 

#### Description
Do not allow user to click on save button multiple time. Make the page greyed and bring the Loading modal. 

#### Steps to reproduce
1. Click on Add request
2. Fill all the required Fields
3. Click on Save button multiple times
4. Multiple requests gets created

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Check all the save and bring the Loading modal
- [ ] Block from the BE, if possible
- [ ] Integration test

**Comment by m-prodan** [comment]
Having tried a few different ways/times - I am unable to trigger the save button multiple times. Issue appears to be resolved, will close ticket and monitor for user feedback into the pilot
