### ISSUE TITLE
Add new Ministry and Code change in Angular APP (#1736)

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#2020]
Title of ticket: 

#### Description
Add "Declaration Act Secretariat" with code DAS and publicBody "Indigenous Relations and Reconciliation" 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Add new ministry (DAS)
- [x] Test all payment scenarios
- [x] Check data save properly in DB
- [x] Integration test

**Comment by m-prodan** [comment]
@divyav-aot - I've been trying to test adding in the new Ministry in the pay form, I am running into an issue where an error message gets thrown when I proceed to payment. I thought maybe it was DAS/IRR, but when I tried another singular Ministry the same error was thrown.

**Comment by m-prodan** [comment]
Working now @divyav-aot - thanks!
