### ISSUE TITLE
Penetration Testing Report - Fixes

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#2026]

**Comment by mpilchar** [comment]
@sumathi-thirumani-aot Can you please add DOD for this with the fixes required?

**Comment by sumathi-thirumani-aot** [comment]
Apply the below headers in system as environment variables
1. REDASH_COOKIES_SECURE = true
2. REDASH_REMEMBER_COOKIE_SECURE = true
3. REDASH_HSTS_ENABLED = true
4. REDASH_CORS_ACCESS_CONTROL_ALLOW_ORIGIN = https://dev.foirequests.gov.bc.ca
5.  REDASH_COOKIE_SECRET = {Generate 24 character strong key}
6. REDASH_REFERRER_POLICY = strict-origin-when-cross-origin

**Comment by sumathi-thirumani-aot** [comment]
[https://app.zenhub.com/files/358004325/e6f9e1a3-80db-488d-8ee5-678f8bde4658/download](https://app.zenhub.com/files/358004325/e6f9e1a3-80db-488d-8ee5-678f8bde4658/download)
