### ISSUE TITLE
Create document for remediation plan for STRA

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#2033]

**Comment by sumathi-thirumani-aot** [comment]
[https://app.zenhub.com/files/358004325/a4933543-b94a-4bd5-81e4-f281a6266337/download](https://app.zenhub.com/files/358004325/a4933543-b94a-4bd5-81e4-f281a6266337/download)

**Comment by lmullane** [comment]
@sumathi-thirumani-aot, instead of uploading documents like this to ZenHub, could you please save to MS Teams and post a link.

Better not to publish where anyone can see them.
