### ISSUE TITLE
Axis Sync warning is still showing after the Sync

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#2034]
**Describe the bug in current situation**
The warning banner still shows once you sync with AXIS after Open/CFR state.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Add request
2. Enter valid AXIS ID and Sync with Axis
3. Save request
4. state change to Open
5. Edit applicant name and save
6. Warning banner shows and Sync with Axis button enabled
7. Click on sync with axis and save 

**Actual/ observed behaviour/ results**
The warning banner still shows and the sync with axis button enabled. Nothing shows on click of the button. The banner disappers when you refresh the page.

**Expected behaviour**
The warning banner should get disappear and the button should be disabled as the changes are already synced 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
Tried a variety of different syncs - the banner goes away and sync is disabled when the sync happens... considering this one closed - nice work! @aparna-aot
