### ISSUE TITLE
User cannot access Comments log

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2038]
**Describe the bug in current situation**

Two of our trainees have not been able to access the Comments log for some requests.

The 1 user was using Edge.

GIVEN the user is on the request view
WHEN the user scrolls over the Comments log in the left navigation
THEN the cursor remains an arrow
AND does not turn into a hand

![Screen Shot 2022-05-04 at 12.11.49 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/b90f76e7-e49d-4229-b5c3-3f82fbf0ba88)

GIVEN the user is on the request view
WHEN the clicks on the Comments log in the left navigation
THEN the user remains on the request view
AND the Comments log does not open

GIVEN the user is tagged in a comment for the same request
WHEN the user clicks on the link in the Notification Log
THEN the user is directed to the Comments log for the request

![Screen Shot 2022-05-04 at 12.15.50 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/0ee0786d-d977-4763-8bc6-4fce6155be6d)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

Unknown. We have 2 users who have reported the issue.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

A user showed me the issue, but have not been able to replicate when I login with my IDIR or a test user.

**Steps to Reproduce**
1. Go to '..'

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN the user is on the request view
WHEN the user scrolls over the Comments log in the left navigation
THEN the cursor turns into a hand

GIVEN the user is on the request view
WHEN the clicks on the Comments log in the left navigation
THEN the user is redirected to the Comments log 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
Possible permissions issue?

cc @m-prodan, @divyav-aot

**Comment by divyav-aot** [comment]
I tested in Edge and able to see the comment tab. Also, I don't remember any permission given for comments tab. Can you try to clear the cache and check again?
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/fb68e049-d5a8-4c2c-8a2a-968db01025c6)

**Comment by divyav-aot** [comment]
@lmullane -  It looks like a screen resolution issue. @aparna-aot  has already fixed this as part of another bug. We will push the changes ones the demo is over.

**Comment by mpilchar** [comment]
Received confirmation that issue is fixed for one user in TEST; waiting to hear back from the other.

**Comment by lmullane** [comment]
Confirmed fixed with second user.
