### ISSUE TITLE
Extension 'PENDING' in AXIS become stuck in loop when synced

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2039]
**Describe the bug in current situation**

GIVEN an extension is PENDING in AXIS
WHEN the request is synced in the new app
THEN the extension is synced and APPROVED in the new app
AND the banner continues to be displayed
AND the extension can be synced again -appears in comments, but not the extension log

![Screen Shot 2022-05-04 at 12.22.02 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/c192287c-ddfd-4893-80ac-4d8fa358b42f)

![Screen Shot 2022-05-04 at 12.23.44 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/9685d930-e8ee-403f-bec3-e3c62db8ec14)

![Screen Shot 2022-05-04 at 12.21.30 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/c4d348e3-4e21-4c9f-a843-f86b10e2d469)

![Screen Shot 2022-05-04 at 12.24.48 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/f5384f7a-8042-409a-a228-d616d8b03d58)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

Low. IAO analysts should COMPLETE an extension in AXIS before syncing the request.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a request that has a pending extension in AXIS.
2. Click on 'Sync request'
3. Click on Review Changes and see the Pending extension
4. Save the change
5. Scroll down to the extension log and see that the extension has saved, but is APPROVED
6. See the Warning banner
7. Click on 'Sync request'
3. Click on Review Changes and see the same Pending extension
4. Save the change
5. Scroll down to the extension log and see that the extension only shows the extension once as APPROVED
7. Click on the Comments log
8. See that the Extension notification has posted again for the same extension
9. See the Warning banner
10. Click on 'Sync request'
11. Repeat steps above

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN an extension is PENDING in AXIS 
WHEN the request is synced in the new system
THEN the extension should be synced as PENDING 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
@m-prodan, what would be the expected behaviour. 

IMO the extension should sync once and remain in Pending. Thoughts?

**Comment by m-prodan** [comment]
Yeah, I would say if we want to fix this, we should set it to pending.

Alternatively, perhaps public body pending extensions don't sync? or would that be too confusing for the user experience to have that inconsistency?

**Comment by mpilchar** [comment]
Suggesting high for this one since it happens consistently, impacts functionality and can create confusion

**Comment by lmullane** [comment]
@divyav-aot, I'd like to update the Expected Behaviour. Quick question - have we disabled the ability of the user to approve a PENDING extension in our application?

![Screen Shot 2022-05-17 at 10.37.41 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/bbe20184-7c19-46af-a12f-cbd4f51aa96f)

**Comment by lmullane** [comment]
Disregard. I have my answer.

This is now fixed. Thanks, @divyav-aot
