### ISSUE TITLE
Discuss deployment plan

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#204]
Discuss *production* deployment plan.

- [x] Discuss deployment strategy - while API DB in place : @abin-aot 
- [x] Discuss Backup plan for Database on TEST
- [x] Release approach  - pre-release ??

Do we want CI/CD to automatically deploy to prod?  Or do we want to schedule manual deploys during change windows?

**Comment by lmullane** [comment]
Automatic deployments to prod would be my preference. cc @acoard-aot
