### ISSUE TITLE
CFR overdue wording and Scrollbar changes

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#2043]
Title of ticket: 

#### Description
1. CFR Due wording changes for overdue. 
     Text changed to "CFR Due in -x Days"
2. Scrollbar added to RequestView, Comments and Attachments

#### Dependencies
Are there any dependencies?

#### DOD
- [x] change the text
- [x] Code refactor - remove unnecessary code related CFR Overdue
- [x] Add scrollbar to all tabs
- [x] integration test

**Comment by nkan-aot** [comment]
scroll bar is visible in request comments and attachments, CFR Due wording has been changed. Closing issue now
