### ISSUE TITLE
PHN Information is getting missed on Personal FOI Request

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#2048]
**Describe the bug in current situation**
System not showing information entered inside PHN for Personals requests.

**Link bug to the User Story**

**Impact of this bug**
DATA LOSS or DISPLAY missing for PHN or DATA NOT POPULATING on Front end - PHN

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requisites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Request View of a Personal Request.
2. Enter some value on the PHN field.
3. Click Save button.
4. The PHN field would be empty.

**Actual/ observed behavior/ results**
PHN text field is empty even after saving the value.
**Expected behavior**
PHN value should be displayed on it's text field.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KaraBeach** [comment]
PHN value stayed displayed in the text field after saving and going back to the file.
