### ISSUE TITLE
UX Assurance: Overlapping text in Edge Browser

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#2052]
**Describe the bug in current situation**
Text overlaps on Request Details page in Edge browser. See screenshots below - Apparent on left nav and at the top of the page. Same page looks fine in Chrome on same sized computer monitor

Impact: Significant. Affects usability of the application and is required for pilot
Chance of Occurring: High. Happens every time for all user using a gov laptop
Environment: Test, Edge browser

**Steps to Reproduce**
1. Go to https://test.foirequests.gov.bc.ca/foi/ and log in as an Economy Sector user
2. Click into any request
3. See error on left nav panel

Screenshot: 
![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/c179738b-b6e6-4bf0-be21-3e28444caeb7)

Happens in multiple states:
![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/a8efd19e-6055-4b8e-a9be-87a89251265f)

Happens across user types: 
![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/7dda2064-5758-4a3e-8d6d-76e0b1b1956f)

**Comment by lmullane** [comment]
This appears to be fixed, but I my laptop may not be the best to confirm.

@m-prodan, could you confirm this works on your machine?

**Comment by mpilchar** [comment]
Confirmed fixed on my 14" laptop - Thanks all for the fix!
