### ISSUE TITLE
Ability to search user in watcher popup

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#2053]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to search user in watcher. With more than 20 users in list. Scrolling and searching is not very preferable.

**Describe alternatives you've considered**

**Additional context**

**Comment by KyEggleston** [comment]
Stale ticket, added to feedback repo for future consideration. Closing ticket
