### ISSUE TITLE
Dependabot Issues on FOI

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#2056]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [x] Critical issue on deserialization of data
- [x] Front-end fixes

**Comment by sumathi-thirumani-aot** [comment]
No fix required; there is already authentication in place to allow only recognized users.
Also, note: We are using only JSON formatted data and other security checks on place.

References:
https://github.com/advisories/GHSA-656c-6cxf-hvcv
https://github.com/pallets-eco/flask-caching/pull/209

**Comment by divyav-aot** [comment]
issue with FE: "async" version upgraded to "3.2.3" and jake version upgraded to "10.8.5"
