### ISSUE TITLE
Axis Banner Message not fully visible after adding scroll bar in request view page

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#2069]
**Describe the bug in current situation**
Axis Banner Message not fully visible after adding scroll bar in request view page

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requisites or assumptions to execute steps?**

**Steps to Reproduce**
1. Login as IAO user.
2. Go to Request View Page of a request with valid Axis Id.
3. Check the Axis Banner.

**Actual/ observed behavior/ results**
Some of the text on the right side of the banner is not visible.
**Expected behavior**
The message on the banner should be visible.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/712eecb2-a341-4e42-9deb-91e543e51b99)

**Comment by lmullane** [comment]
Thanks for the fix, @aparna-aot
