### ISSUE TITLE
Research and fix: Determine how we will capture and calculate stat holidays

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#207]
#### Description
Research: Determine how we will capture and calculate stat holidays when auto-populating a deadline as part of a request. 
https://www.npmjs.com/package/date-holidays

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Determine a way 
- [x] Decision: API or source code?
- [x] Fix what we can using API
- [x] That which we cannot fix, create technical debt for solution

**Comment by acoard-aot** [comment]
https://www.npmjs.com/package/date-holidays#supported-countries-states-regions

**Comment by acoard-aot** [comment]
Divya noted a problem with many sources, if holiday falls on eg Sunday the API does not properly "carry it over" to Monday as it should.

One possibility is to have a manual blackout option entered by staff.  So IAO staff could simply enter days that they're not in office and should not count against duration of FOI.

**Comment by abin-aot** [comment]
@sumathi-thirumani-aot  started working on this using NPM packages
