### ISSUE TITLE
Fee estimate/CFR view for ministry coordinator for general requests

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2075]
* As a ministry coordinator 
* I want a CFR/Fee estimate view for every general request
* so that I  can enter information fee estimates for the request 

Deduplication or Records Review

**Assumptions & Scope**	
What are the assumptions for this story?

Only estimated hours can be filled out in the CFR state.

Total Fees Due will automatically be generated by the hours filled in.

Hours entered into the online form can only be entered in 1/4 hour increments (ie: 1 and a half hours should be written as 1.5) 

What is IN scope?

Ministry coordinator editing the CFR Form

What is NOT in scope?

State changes are covered in #2194

IAO view of the CFR form and Process Payment button.

CFRs for Personal requests.

The divisional coordinator filling out the CFR form

The divisional forms autofilling the Overall Estimate

**Acceptance Criteria**	

**Scenario 1: Overall Fee Estimate**
* GIVEN a ministry coordinator is on the Request, Comments or Attachment view
* WHEN the user clicks the CFR Form on the left navigation
* THEN the  CFR Form view will open
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* AND will include the Overall Fees Estimate section with the following fields: Amount paid, Estimated Amount Total, Actual Amount Total, Balance Remaining, Locating/Retrieving (Estimated Hours, Actual Hours), Producing..(Estimated Hours, Actual Hours), Preparing...(Estimated Hours, Actual Hours), Volume - for electronic...(Electronic Estimated pages, Electronic Actual pages, Hardcopy Estimated pages, Hardcopy Actual pages)
* AND there will be a section with a field for Overall Narrowing Suggestions
*AND there will be a 'Save' button at the bottom 

**Scenario 2: Editable fields in CFR Form when request is in Call for Records State**
* GIVEN a ministry coordinator is on the CFR Form view 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* WHEN the request is in the Call for Records state
* AND the request has not been approved in the Fee Estimate state
* THEN the Estimated Hours fields will be editable and not mandatory (i.e., Locating/Retrieving, Producing.. Preparing..., Volume - for electronic...(Electronic Estimated Hours, Hardcopy Estimated Hours)
* AND all the fields for Actual Hours will NOT be editable and greyed out
* AND the Total Fee Due will be greyed out and not editable

**Scenario 3: Enter estimate hours on CFR Form when request is in Call for Records State**
* GIVEN a ministry coordinator is on the CFR Form view 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* AND the request is in the Call for Records state
* AND the request has NOT be in approved Fee Estimate state
* WHEN the coordinator fills in the Estimated Hours fields for Locating/Retrieving, Producing.. Preparing..., Volume - for electronic...(Electronic Estimated Hours, Hardcopy Estimated Hours)
* AND the hours entered are done so in 1/4 hour increments (e.g 1.25, 1.50, 1.75, 2, etc..)
* AND all the fields for Actual Hours will NOT be editable and greyed out
* THEN the Total Fee Due field will automatically be filled based on the Fee Table (insert link)

**Scenario 4: Editable fields in CFR Form has been approved Fee Estimate state**
* GIVEN a ministry coordinator is on the CFR Form view 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* WHEN the request is in the Call for Records state
* AND the request has been approved Fee Estimate state
* THEN the Actual Hours fields will be editable and not mandatory (i.e., Locating/Retrieving, Producing.. Preparing..., Volume - for electronic...(Electronic Estimated Hours, Hardcopy Estimated Hours)
* AND all the fields for estimated hours will NOT be editable and greyed out
* AND the Total Fee Due will be greyed out and not editable

**Scenario 5: Enter actual hours on CFR Form has been approved Fee Estimate state**
* GIVEN a ministry coordinator is on the CFR Form view 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* AND the request is in the Call for Records state
* AND the request has  been approved by IAO in the Fee Estimate state
* WHEN the coordinator fills in the Actual Hours fields for Locating/Retrieving, Producing.. Preparing..., Volume - for electronic...(Electronic Estimated Hours, Hardcopy Estimated Hours)
* AND the hours entered are done so in 1/4 hour increments (e.g 1.25, 1.50, 1.75, 2, etc..)
* THEN the Total Fee Due field will automatically be filled based on the Fee Table (insert link)

**Scenario 6: Active Save **
* GIVEN a ministry coordinator is on the CFR Form view
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* WHEN all at least one fields is filled in:  in CFR the estimate hour fields or Overall Narrowing Suggestions
* THEN the Save button will become blue and active

**Scenario 7: Save**
* GIVEN a ministry coordinator is on the CFR Form view
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* AND the Save button is blue and active
* WHEN the user clicks the 'Save' button
* THEN a green success toast will briefly appear
* AND changes made to the view will be saved

**Scenario 8: Enter hours - invalid format**
* GIVEN a ministry coordinator is on the CFR Form view 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* AND the request is in the Call for Records state
* WHEN the coordinator fills in the Estimated Hours or Actual Hours fields for Locating/Retrieving, Producing.. Preparing..., Volume - for electronic...(Electronic Estimated Hours, Hardcopy Estimated Hours)
* AND the hours entered are done so in an incorrect format (ie: 1.1, 1.65, 10 minutes, etc..)
* THEN a red box will appear over the field and an error message on top in red indicating that hours must be entered in 0.25 hour increments
**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
[@xxx - please link the Design here](https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/cl2yw4ity00jd01yvh1913izr/play)
#1418

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, @JHarrietha-AOT, @mpilchar, @KaraBeach  really good feedback on the CFR forms from demo. One takeaway is that the divisional CFR forms should not be editable after a certain point because of OIPC audit requirements, and likely should not be editable by the ministry coordinator at all.

**Comment by lmullane** [comment]
Thanks, @m-prodan .

They still need to enter some information though to change the state Deduplication or Records Review, even if they put zeroes, correct?

**Comment by lmullane** [comment]
Thinking through this would it be better that the estimated hours and actual hours default is zero and then that they are required to save the form even if the hours are zero?

That way we have complete CFR forms.

**Comment by m-prodan** [comment]
Based on our conversation at refinement - I removed the following scenario with respect to actuals:

**Scenario 5: Enter actual hours on CFR Form when request is in the Call For Records state**
* GIVEN a ministry coordinator is on the CFR Form view 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* AND the request is in the Call for Records state
* WHEN the coordinator fills in the Actual Hours fields for Locating/Retrieving, Producing.. Preparing..., Volume - for electronic...(Electronic Estimated Hours, Hardcopy Estimated Hours)
* THEN the Total Fee Due field will automatically be updated based on the Fee Table (insert link)

I think this needs to be covered in a different user story, because we aren't allowing actuals to be actionable until after the fee estimate state/fee is resolved or paid.  Otherwise, AC should be good to go based on our conversation today.

cc: @lmullane @abin-aot @divyav-aot @nkan-aot

**Comment by nkan-aot** [comment]
clarified at standup today, estimated hours will not be editable for ministry after IAO approval. will update AC

**Comment by mpilchar** [comment]
I'm testing this right now and it seems like the inverse is true for the current AC - seeking clarification whether, when logged in as a ministry user, editable fields should be active or inactive. Same for Actual hours

**Comment by mpilchar** [comment]
Need some help on how to test Sc. 3- Can't move to Fee Estimate state @m-prodan

**Comment by mpilchar** [comment]
Update: This seems to be an issue with the Test-Marshal enviro. @nkan-aot is looking into it

**Comment by mpilchar** [comment]
One more issue encountered: According to Matt's comment above, hardcopy pages should impact the total amount paid by $0.10/page but I am not seeing a chance when I modify that number

**Comment by nkan-aot** [comment]
I believe because you entered an actual value, then the total amount paid is now calculating using that value instead of estimate. If you start a new request with CFR Form you should see that the total is updated when you change hardcopy estimate

**Comment by nkan-aot** [comment]
Regarding state change to fee estimate, it seems to be related to object storage and file upload, and not a code issue. I do not have access to the config for our file bucket so will need to wait for @sumathi-thirumani-aot or @abin-aot, maybe tomorrow

**Comment by nkan-aot** [comment]
@abin-aot has fixed the file upload issue, state change to fee estimate should be working in test marshal now

**Comment by mpilchar** [comment]
This is working GREAT now! Everything checks out. Way to go team!
