### ISSUE TITLE
Submitting FOI w/ 2 ministries only shows 1 on review and submit queue

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/foi-flow#208]
**Describe the bug in current situation**
Divya submitted an FOI form via angular app and selected two ministries: 1) Advanced Education and Skills Training 2) Agriculture, Food, and Fisheries.  The angular app submit sent Adam an email and it shows both ministires selected.  Adam can forward email if desired.

However, when the form was reviewed in FormsFlowWeb, it only showed a singular ministry submitted.

**Link bug to the User Story**

**Impact of this bug**
High impact.  This impacts data integrity.

**Chance of Occurring (high/medium/low/very low)**
Unsure, saw it happen once in demo.  Presumably happens every time.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
None known. This happened on dev account at 3:30pm.

**Steps to Reproduce**
1. Submit angular FOI form with two selected ministries:  1) Advanced Education and Skills Training 2) Agriculture, Food, and Fisheries. 
2. Login to FormsFlowWeb via IDIR and review the new submission
3. See that only one ministry is selected.

**Actual/ observed behaviour/ results**

**Expected behaviour**
Given two ministries are selected in submission, they should be visible when reviewing the request.

**Screenshots/ Visual Reference/ Source**
Adam can email the submission email if someone needs it to help debugging.  It shows the raw data submitted via angular app and is the "source of truth".

**Comment by arielleandrews** [comment]
From Test Webform, submitted a request with 5 Ministries selected:
![image](https://user-images.githubusercontent.com/82615839/126814532-2227b2fa-03f0-4fda-b7be-634cbf647286.png)
On Review Request screen in Test, only 2 of the 5 Ministries selected were displayed:
![image](https://user-images.githubusercontent.com/82615839/126814786-7de50e2e-c921-4b41-b808-9b9773d34c21.png)

**Comment by JHarrietha-AOT** [comment]
@m-prodan I will try and replicate after stand-up and let you know if I am able to

**Comment by JHarrietha-AOT** [comment]
@m-prodan submitted both personal and general request and was unable to replicate this. 
@abin-aot @acoard-aot @divyav-aot has there been a change pushed since @arielleandrews shared the screenshot above on Friday?

**Comment by lmullane** [comment]
@arielleandrews to try to replicate again.

**Comment by arielleandrews** [comment]
Submitted a new request with same ministries and was unable to replicate. Can we consider this resolved? @abin-aot @divyav-aot @acoard @lmullane
