### ISSUE TITLE
Digitized form update - 3rd Iteration - General CFR Form

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#2082]
Title of ticket: Digitized form update - 3rd Iteration

#### Description
Making updates based off of internal suggestions from PO to better improve functionality of form along with working through list of changes from Demo May 10 and any additional notes from @m-prodan Manager Meeting

#### Dependencies
- [x] Rewatch Demo to ensure all Action Items are listed
- [x] @m-prodan add any changes here that are not Personals Specific from the Managers Meeting

#### DOD
- [x] Move Individual Divisions Forms into Sub-Menu on left nav
- [x] Add Narrowing Suggestions to Overall Fee Page
- [x] Tooltips for Estimates vs Actuals
- [x] Tooltip explaining why search is mandatory
- [x] Field for justification of search hours (should be optional)

**Comment by m-prodan** [comment]
@JHarrietha-AOT Updated with some suggestions from management meeting. Regarding the last bullet point re: justification of search hours, it was something that a couple managers raised where their team often goes back to seek justification for the search hours. I think we can add an optional field for a coordinator/division to fill out to try and get ahead of that? 

I also got a bunch of resources from folks after demo that might be worth passing off, will dive into them a bit and see what we might need to include... likely from a tooltip perspective

**Comment by mpilchar** [comment]
Discussion and comments from May 10 Sprint Review can be found here: https://bcgov.sharepoint.com/:w:/t/03521/ESr6FtnHNk9Bt-FnHncqgnoB1ALQOuT85_ah0aBk5W0rUw?e=pqiiFb

**Comment by JHarrietha-AOT** [comment]
@lmullane @m-prodan cc: @KaraBeach @mpilchar 

Just wanted to share out a series of links to the Generals CFR Form Updates

Ministry/IAO view of overall Fee Estimates GENERAL REQUEST (Ministries will have "Process Payment" disabled: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803

Divisions View of CFR Form (This page has all tooltips as clickable): https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/915277140

Ministry Coordinators view of individual divisions form for GENERAL REQUEST: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912614830

Add New Division/Program Area Form (Included field for Ministries to fill out for easy tracking): https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/915277141

Modal If Division tries to save form with 0 hours listed : https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/915277142

**Comment by JHarrietha-AOT** [comment]
@KaraBeach @m-prodan I am going to put all of the content from the tooltips into one word doc in hopes of shortening some and to have you proof or add content for new ones. Will have this together shortly

**Comment by lmullane** [comment]
@m-prodan , @KaraBeach , @JHarrietha-AOT, question for you - will a division have more than one CFR form?

For example, does the Divisional Coordinator send a CFR template to more than one branch and then consolidate the response into one divisional CFR form?

**Comment by JHarrietha-AOT** [comment]
@lmullane It was mentioned in Demo that there are rare times when this has to happen based off of the size of the Ministry, the size of the Division or the Request Itself. This is why I added the button to add a new CFR form where the Ministry Coordinator can name then with an open text field.

**Comment by lmullane** [comment]
@JHarrietha-AOT, going to give you a ring to discuss.

**Comment by JHarrietha-AOT** [comment]
Links above stories have been written
