### ISSUE TITLE
Fix Sonar Cloud Bugs and Code smells - FE

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#2090]
Title of ticket: 

#### Description
Fix Sonar Cloud Bugs and Code smells - FE

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Fix most of the critical code smells
- [x] Fix "Unexpected var, use let or const instead." code smells.
- [x] Fix "Extract this nested ternary operation into an independent statement." code smells.
- [x] Code Smells on Request Description, Divisional Stages etc.
- [x] Fix some of the "Remove the unused function parameter" code smells.

**Comment by lmullane** [comment]
To a regression with sync and state change and notifications.

**Comment by m-prodan** [comment]
Basic regression complete - no issues found - closing ticket.
