### ISSUE TITLE
Review individual request

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#21]
As an intake analyst, I want to be able to review all details of requests submitted.

Assumption: 
Request is unopened
This is for both General and Personal requests
"on behalf of" (a field in the personal request) is NOT included, will display as "N/A". A separate story has been created for "on behalf of" - #__.

**Acceptance Criteria**	

**Scenario 1: Hover over request**
* GIVEN is on the Queue
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451
* WHEN the analyst hovers over a request row
* THEN the cursor will turn into a hand

**Scenario 2: View GENERAL request**
* GIVEN is on the Queue
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451
* AND the analyst has the cursor over a request row for a GENERAL request
* WHEN the analyst clicks on the row
* THEN the analyst will be directed to the individual GENERAL request:
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932453
*AND the request will contain fields populated from the request form for applicant details: first name, middle name, surname, email (optional), street address, city, province, country (address information is optional if applicant provides email), on behalf of (optional), organization (optional), request description, request date range, and request details: ministry(s), request type (editable), phone number (optional), received mode, delivery mode (Matt to confirm), received date, start date (editable), due date (determined by start date)
*AND all ministries will listed

**Scenario 3: View PERSONAL request**
* GIVEN is on the Queue
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451
* AND the analyst has the cursor over a request row for a PERSONAL request
* WHEN the analyst clicks on the row
* THEN the analyst will be directed to the individual PERSONAL request:
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932502
*AND the request will contain fields populated from the request form for applicant details: first name, middle name, surname, email (optional), street address, city, province, country (address information is optional if applicant provides email), on behalf of (optional), organization (optional), request description, request date range, and request details: ministry(s), request type (editable),  phone number (optional), delivery mode, received date, start date (editable), due date (determined by start date), additional applicant information: date of birth (optional), corrections number (optional), personal health number (optional), employee number (optional).
*AND all ministries will be listed

**Scenario 4: Change Request Type 1**
* GIVEN the analyst is on a request: 
* WHEN the analyst clicks the arrow next to Request Type
* THEN a drop-down will open with 2 options: Personal or General
https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/ckpq19gnk00p3011q1mef2ha8/play

**Scenario 5: Change Request Type 2**
* GIVEN the analyst has opened the drop down for Request Type
* WHEN the analyst clicks the new request type (e.g. general)
* THEN the drop-down will close
* AND the new request type will be displayed (e.g. general)
https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/ckpq19gnk00p3011q1mef2ha8/play

 
**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
Is dependent on the backend capture of information from the webform (#27)

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.     [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, I've speculated on how the drop down menus will work for editing request type, delivery mode, etc.

I'm curious how the drop down will work for the last scenario to edit the selected ministry as there may be more than one.

We can discuss at 1:)

**Comment by lmullane** [comment]
@JHarrietha-AOT, is scenario 5 correct?

**Comment by JHarrietha-AOT** [comment]
@lmullane Scenerio 5 is correct. It looks like the page isn't updating in the prototype what it is clicked. I will look into this once I finish the final queue updates.

**Comment by lmullane** [comment]
Super. Thanks @JHarrietha-AOT

**Comment by abin-aot** [comment]
@lmullane : By this story we meant, review "Unopened request", Is it?.

**Comment by lmullane** [comment]
@abin-aot, the way this story is written it is more generic (could review an opened or unopened request from the queue).

**Comment by abin-aot** [comment]
@mpilchar @divyav-aot @sumathi-thirumani-aot @lmullane @m-prodan @acoard-aot , Arielle - Based on today's(Jun/24) discussion and decisions, this will turn to an feasibility analysis task / might have an output for the demo/sprint end date. In turn we will pick up task #82 (Filter Request Queue) for this sprint to achieve.

**Comment by lmullane** [comment]
Thanks, @abin-aot. Keep us posted on progress.

**Comment by lmullane** [comment]
@divyav-aot @JHarrietha-AOT During QA we did not find that the the acceptance criteria for scenario 1 was met:

GIVEN the analyst is on the Queue
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451
WHEN the analyst hovers over a request row
THEN the cursor will turn into a hand

Specifically, when you hover over a request row, the cursor does not turn into a hand (as it does in Jacky's designs). Instead the row is highlighted in blue.

Not a deal breaker IMO. Likely I will just revise the AC for future regression testing, unless someone feels strong otherwise.

Is the behaviour to highlight the row, instead of changing the cursor to a hand, out-of-the-box behaviour from Material UI?

cc @m-prodan @arielleandrews

**Comment by JHarrietha-AOT** [comment]
@lmullane I would agree its not a deal breaker, but I think this is a change that needs to be made as the queue doesn't currently have new/unopened requests highlight in blue as they are in the UI. So having a colour change on hover as well as the highlight in blue for new/unopened requests isn't ideal.
