### ISSUE TITLE
EDU Requests not saving when moving through states

### ISSUE THREAD

**Issue by KaraBeach** [bcgov/foi-flow#2100]
**Describe the bug in current situation**

**Example File numbers:** EDU-2022-00057; EDU-2022-00058 and EDU-2022-00059

1. A user syncs an EDU request in AXIS flow 
2. Save the request
3. When the request is moved from Intake in Progress to Open and you save the request
4. The request will show an error message
5.  If you try and use the advance search functions the file is not found 
6.  If you try and re-sync the request it will not allow you to

![image.png](https://images.zenhubusercontent.com/6255c38670485846988df18c/af14bf4c-88c0-4cc5-9fbb-678934f55550) 

![image.png](https://images.zenhubusercontent.com/6255c38670485846988df18c/fd6f5965-ba2b-4961-955d-355ca1fce9d9)

![image.png](https://images.zenhubusercontent.com/6255c38670485846988df18c/7028072d-e7dd-4851-98e6-7506f9e72f29)

**Link bug to the User Story**

**Impact of this bug**
High. We have users that use EDU files (i.e. Social Education team).

**Chance of Occurring (high/medium/low/very low)**
High. All EDU users are impacted. (i.e. Social Education team).

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1.	Create a request in perfected request in AXIS
2.	Go to FOI Flow
3.	Add request, and AXIS ID #
4.	Sync and Save Request
5.	Change request state from Intake in Progress to Open
6.	Click Save
7.	An error message will appear 

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a user changes the state of an EDU request (Intake in Progress to Open)
WHEN they hit save
THEN the request will save and sync 
AND the request will show in the queue

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
@KaraBeach - lets chat in the morning about this one if you are back. I have been unable to replicate it, and want to work through it with you as we'll want to get this ticket finalized ASAP if we can find the root

**Comment by KaraBeach** [comment]
@aparna-aot - thank you for the quick fix! Behavior works as expected now

**Comment by KaraBeach** [comment]
@m-prodan - Issue has been fixed and behavior works as expected now. Closing.
