### ISSUE TITLE
Request assigned to Flex team member not showing in Flex team queue

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2112]
**Describe the bug in current situation**

GIVEN an FOI request (EDU-2022-00042, MHA-2022-00004, EDU-2022-00057) is assigned to a Flex team member
WHEN the user browses the 'My Team's Requests' queue
THEN the request does not appear in the queue

![Screen Shot 2022-05-11 at 3.42.42 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/4786d58c-c70b-46bf-9208-02c50bea44c4)

![Screen Shot 2022-05-11 at 3.41.03 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/99ac2823-6829-4de6-8075-0d21d70d0825)

![Screen Shot 2022-05-11 at 3.41.12 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/952a4c28-8237-4d74-a3e1-75d1c4f793c1)

GIVEN an FOI request (EDU-2022-00042) is assigned to a Flex team member
WHEN the user searches the 'My Team's Requests' queue by the AXIS ID Number
THEN the missing request appears in the queue

![Screen Shot 2022-05-11 at 3.41.35 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/3617fb42-fcce-44f5-905d-8c2e2be1c358)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

High. Requests could be missed
**Chance of Occurring (high/medium/low/very low)**

High. Replicated 3 times with different flex team users.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Login as a Flex user
2. Go to 'My Team's Requests' queue
3. Click on an Open request
4. Click on the 'Assigned to' field
5. Scroll down to and select a flex team member
6. Save the assignment
7. Go to the  'My Team's Requests' queue
8. Search for the request that was just assigned
9. See that it is not listed on any page
10. Search by request ID in the 'My Team's Requests' queue
11. See the missing request listed

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a request is assigned to a Flex Team member
WHEN a flex team user goes to 'My Team's Requests' queue
THEN the assigned request should appear in the 'My Team's Requests' queue

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
@mpilchar, @m-prodan, new bug for review with the team tomorrow.

cc @divyav-aot  @abin-aot

**Comment by nkan-aot** [comment]
@lmullane i think i already captured this #2109. Will close mine

**Comment by lmullane** [comment]
Thanks, @nkan-aot. Putting this into the Sprint Backlog for a dev to pickup.

**Comment by lmullane** [comment]
This is now fixed. Thanks. @nkan-aot
