### ISSUE TITLE
TRAILING spaces with Search Key(AXIS ID/REQUEST ID) gives no search result - need to TRIM

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2113]
**Describe the bug in current situation**
While searching with a key/search text(can be AXIS REQ. ID) on FOI FLOW Dashboard's Queue or Advanced search, if there is a space character suffixed or prefixed to Search Key then results are not populating. Technically, we need to TRIM space characters suffixed or prefixed to search text/key - so that results with show up without confusing the end user 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Queue or Advanced Search with an AXIS Request ID - Say, EDU-2021-10032
2. Typing or copy paste the ID on the search field - Results will show up if exists
3. There can be scenario's by mistake user have space in end, then results will not show up.
4. So with trailing or prefixed space characters to ID, Queue will say NO RESULTS

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
trailing spaces no longer cause issues - this should rectify issues we see when people copy and paste ID numbers into the ID number field for advanced search.
