### ISSUE TITLE
Extension Details :  Ellipses symbol (...) is too faint to locate its presence on the screen

### ISSUE THREAD

**Issue by SachinShin** [bcgov/foi-flow#2114]
**Describe the bug in current situation**
 Ellipses symbol (...) is too faint to locate its presence on the request details screen
 
**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Impact: Difficult for user to this option when user wants to Edit or Delete the extension
Number of users impacted : All IAO (Intake/Flex /Processing team) users having rights to extension

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requisites or assumptions to execute steps?**
Environment : Test Environment 
Pre-Requisite : Extension, if not already created, should be created

**Steps to Reproduce**
1. Login as an IAO user (lets say Intake)
2. Go to a Request which is in 'Open' stage
3. Scroll down to 'EXTENSION DETAILS' section 
4. Click on 'New Extension' link which opens a new Extension window
5. Select any one of the option from 'Reason for Extension' (lets say - 'Public Body - Consultation')
6. Enter 'Extended Due Days'  (lets says 20)
7. Click on 'Save' 
8. New record is created in 'Extension Details' section with above entered details from step 5 and 6
9. Observe that, Ellipses is not clearly visible in 'Action' column of newly created record
 
**Actual/ observed behaviour/ results**
Ellipses is not clearly visible in 'Action' column of newly created record.

Note : Mouseover to 'Action' column of newly created record and you can see ellipses but its too faint to spot. 

**Expected behaviour**
Ellipses should be clearly seen in 'Action' column of newly created record for an user to take further action.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
![image.png](https://images.zenhubusercontent.com/62740c7d614784722371f5b1/1365ee52-95dc-4ab3-9065-0638e732f276)

**Comment by KaraBeach** [comment]
Ellipses symbol (...) presence is now bold and clear to the user. thank you @nkan-aot
