### ISSUE TITLE
Extensions comments and attachments do not show up until after refresh

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#2121]
**Describe the bug in current situation**
Extensions comments and attachments do not show up until after refresh

**Impact of this bug**
medium impact - if user wants to check documents right after they upload through attachments, they need to refresh

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Add an OIPC extension in approved or denied stage
2. upload document before saving extension
3. Attachments in sidebar will not update
4. Refresh
5. Now attachments are updated

**Actual/ observed behaviour/ results**

**Expected behaviour**
Attachments and comments should update without refresh

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
Tested and this now fixed. Thank team
