### ISSUE TITLE
ADM Briefing materials

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#2126]
Title of ticket: 

#### Description
This is to determine and/or create any ADM-level briefing materials needed for the Pilot Launch

#### DOD
- [ x] PO to determine with ED if briefing note etc is needed
- [ x] Charmaine Lowe (CITZ)
- [x] Eleanor Liddy (EDUC) - via Carrie
- [x ] Joanna White (MUNI)

**Comment by lmullane** [comment]
CITZ ADM briefing complete. Ministries handling their exec briefing.
