### ISSUE TITLE
Clear All Filters not clearing up the "On Time" Request Status Checkbox (Advanced Search for Ministry)

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#2134]
**Describe the bug in current situation**
On clicking the Clear All Filters in the Advanced Search for Ministry User view, the "On Time" Request Status Checkbox  is not unchecking/clearing up.

**Link bug to the User Story**
Scenario 10: 'Clear All Filters' of #1654.

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requisites or assumptions to execute steps?**

**Steps to Reproduce**
1. Log in as ECON Ministry User
2. Toggle to Advanced Search
3. Select the "On Time" filter for Request Status.
4. Click the 'Clear All Filter' button
5. See error

**Actual/ observed behavior/ results**
The "On Time" Request Status filter will be selected even if we choose clear all filter.
**Expected behavior**
All search filters should be removed.

**Screenshots/ Visual Reference/ Source**

![Clear filter issue.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/16da2317-4f85-4c6e-aa79-37ca5afc88cf)

**Comment by KaraBeach** [comment]
Bug has been fixed, filter clears. Thank you @aparna-aot
