### ISSUE TITLE
Advanced Search for Received Date is not working as expected

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#2140]
**Describe the bug in current situation**
Advanced Search for Received Date is not working as expected. In the test environment, if you select From Date and To Date as May 1st or May 7th.  Also note that these dates are on Saturday. This is working fine with working days.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
low priority because the issue happens only with weekend dates.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Advanced Search
2. Select Received Date from "Select Type of Date range" dropdown
3. Select From date and To date as May 1st 2022

**Actual/ observed behaviour/ results**
The list shows received date with May 2 (from and to date May 1)
The list shows received date with May 5 (from and to date May 7)

**Expected behaviour**
The list shows received date with May 1 (from and to date May 1) if any. if no data then nothing in the queue
The list shows received date with May 7 (from and to date May 7). if no data then nothing in the queue

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/7c8a834f-bdb0-44bd-821b-f3ff75429eb0)
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/afa174ab-199c-463b-8402-c4bb219d4cee)

**Comment by m-prodan** [comment]
Hi Team - May 5th to May 7th works, but the May 1st scenario is still pulling May 2nd dates per the screenshot below.

Assume I was supposed to test this in TEST? 
![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/611dd8d4-27dc-4d35-ba52-cd5a77738d84)

Sending back to review

**Comment by m-prodan** [comment]
@richard-aot - tagging for visibility

**Comment by richard-aot** [comment]
Thanks, @m-prodan 

There are some logic on generating/displaying the received date. If received date is a holiday or receive time is 4:30pm or later, add one day to the actual received date.

Do we need this logic on generating/displaying received date? Or we just need to use it while calculating due date?

**Comment by m-prodan** [comment]
Ah - yes, that makes sense. So these were probably technically received on the 1st, but because it was a sunday, it would show as received on May 2nd? Truth is - we wouldn't actually check to see if a request was received on a sunday, because you are right, the logic dictates it is received the next business day (which is the 2nd).

I think it is ok as is then. Let me just confirm one thing that if I search for received date on the 2nd, that these will show up

**Comment by richard-aot** [comment]
If you search for received date on the 2nd, you will see a group of different requests whose actual received date is May 2nd.
I think that there is an issue in the request view. For those requests submitted on May 1st, the received date in our database should be May 2nd. I'll create a bug in zenhub.

**Comment by m-prodan** [comment]
Thanks @richard-aot - yes you were right, I will close this ticket then since its already deployed to prod per @abin-aot 

Agree that we should fix that bug behaviour though! Thank you.

**Comment by richard-aot** [comment]
Sounds good. Thanks @m-prodan Created a new bug #2308 for request view
