### ISSUE TITLE
Extension attachment: one file type is missing in alert message

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#2143]
Describe the bug in current situation
In extension, the error message for uploading a invalid file will list allowed file types. "eml" is missing in the file types.

Chance of Occurring (high/medium/low/very low)
low priority

Steps to Reproduce
Click on the ellipsis of the top extension
Select "edit"
Drag a invalid file (other than pdf, docx, eml, xlsx) into box to trigger the error message

![image.png](https://images.zenhubusercontent.com/6140ffb032396d7b882056ce/d7d95ea8-f932-408d-96e4-862f893373ae)

**Comment by KaraBeach** [comment]
Confirmed that the error message pops up and notes the 5 appropriate file types. Nice work @aparna-aot
