### ISSUE TITLE
Advanced Search for Ministry users - Search by Assignee Name not working

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#2145]
**Describe the bug in current situation**
Filter result by Assignee Name is not working for Advanced Search for Ministry users.

**Link bug to the User Story**
Scenario 11 in #1654.

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requisites or assumptions to execute steps?**

**Steps to Reproduce**

1. Log in as ECON Ministry User.
2. Toggle to Advanced Search
3. Select the "Assignee Name" filter and enter "s" on the search bar.
4. You can see random requests being listed.
5. Try to type in any of the assignee's names listed below in the search bar and Apply search.

**Actual/ observed behavior/ results**
No requests will be listed.

**Expected behavior**
Only those requests with the selected assignee name should be listed.

**Screenshots/ Visual Reference/ Source**
The marked assignee's name will be searched in the next screenshot.
![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/8b82012c-21f6-47a1-a8bb-104dd05a1aa1)
Result after the search:
![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/99874099-d76b-4028-9315-caab9d46bfa4)

**Comment by KaraBeach** [comment]
Assignee name is now functioning as it should in advance search- thank you! @richard-aot
