### ISSUE TITLE
Possible bug with Search Results for Flex team

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#2147]
**Describe the bug in current situation**
From the FOI Support channel May 13 12:09pm - needs a team member to look into it and complete the bug ticket
Just testing the FOI database, and note, when a file has been assigned over to the Flex team, and we go back to do a search on the file example EDU-2022-00080, search results produce nothing.  This is a problem if we make a change in Axis and we need to pull up the file to make a note and inform the flex team. how can we do this if the system does not recognize the valid file number. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by mpilchar** [comment]
Hey team - I created this ticket based on feedback from the FOI Modernization Support channel but have not yet looked into it deeper. Hoping someone can pick up to look into

**Comment by divyav-aot** [comment]
not able to reproduce this issue.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/46fee5d6-9baf-482c-b3a1-b51aa057415a)

**Comment by mpilchar** [comment]
not a bug - close

**Comment by m-prodan** [comment]
Probably had to do with a trailing space - I was also able to find it - guessing they had a space at the end when they copy pasted into adv search
