### ISSUE TITLE
Assignee on queue not showing as assigned on request view for certain states

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2153]
**Describe the bug in current situation**

GIVEN a processing team test user is assigned to a request (assignment listed on queue)
![Screen Shot 2022-05-13 at 3.13.05 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/4f9f1099-a2d4-4eb0-b762-d5750c17aa9c)
AND the request is in Deduplication, 
WHEN you go to the request view
THEN the 'Assigned to' is showing unassigned
AND there is no ministry assigned to field
AND you cannot assign the request (greyed out)

![Screen Shot 2022-05-13 at 3.13.24 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/25f188ea-8599-43b3-99c6-a89443cee08a)

GIVEN a processing team test user is assigned to a request (assignment listed on queue)
AND the request is in Harms Assessment
WHEN you go to the request view
THEN the 'Assigned to' is showing assigned
AND there is no ministry assigned to field

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Link bug to the User Story**

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Log with Business One user.'
2.Go to My requests queue
3. See requests assigned in Deduplication state
4. Click on request
5. See error in request view
6. Return to queue
7. See requests in Harms Assessment state
8. Click on request
9. See error in request view

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a request is assigned to the user
AND the request is in any state
WHEN the user goes to the request view
THEN the users name will show in the Assigned to field and be editable
AND if the state is Call for Records and beyond
THEN the Ministry assigned to field will be on the request view

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by divyav-aot** [comment]
@lmullane @m-prodan - This is a personal request with Deduplication/Harms Assessment state. As per previous discussion, personal requests cannot be moved to Deduplication/Harms Assessment state. Due to this, we are not populating the assignedTo dropdown. We didn't remove these states from CFR dropdown. How do you want to proceed now? 
Remove Deduplication and Harms Assessment from the dropdown for personal?
Or, bring the assignedTo List for Deduplication and Harms Assessment  for personal requests?

**Comment by divyav-aot** [comment]
As discussed, keeping deduplication and harms assessment for personal requests. Also, populating the assignTo list for the same

**Comment by lmullane** [comment]
Thanks for the fix, @divyav-aot
