### ISSUE TITLE
Fixes needed for "Add Request" 

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#2158]
**Describe the bug in current situation**
Currently there are some changes needed to the "Add Request" page for Intake users

**Impact of this bug**
Inconvenient and there are workarounds, including adding a request in AXIS. However, this functionality should be consistent with the rest of the app

**Chance of Occurring (high/medium/low/very low)**
High - every time

**Steps to Reproduce**
1. Go to 'Test'
2. Login as 'Intake User'
3. Click on "Add Request"

**DOD**
- [ ] - List of ministries should appear in alphabetical order
![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/329d82be-816f-4946-ab9b-96924782209a)
- [ ] - The "received" and "start" dates in Request Detalis section should not display any dates in the future
![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/f514652a-9cc1-4b94-a26a-56549d89f331)

**Comment by KaraBeach** [comment]
Rec'd/start dates do not show future dates anymore. Thank you! @richard-aot
