### ISSUE TITLE
Assign To automatically saves

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2176]
* As a ministry coordinator or IAO analyst
* I want my selection of an assignee to automatically save (no longer need to click the Save button)
* so that I do not miss completing the assignment and the request getting lost

**Assumptions & Scope**	
What are the assumptions for this story?

Users have flagged the risk with the assignment save not been automatic like the Watcher.

What is IN scope?

Changing the assignment save for both ministry coordinators and IAO analysts.

What is NOT in scope?

Changing the design.

**Acceptance Criteria**	

**Scenario 1: IAO 'Assign To'**
* GIVEN an IAO analyst is on a request view
* AND he or she has clicked the 'Assigned to' field to open the dropdown
* WHEN the analyst clicks an assignee on the list
* THEN the selected assignee will automatically be saved as assigned to the request

**Scenario 2: Ministry Assign To**
* GIVEN a ministry coordinator is on a request view
* AND he or she has clicked the 'Ministry Assigned to' field to open the dropdown
* WHEN the coordinator clicks an assignee on the list
* THEN the selected assignee will automatically be saved as assigned to the request

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by divyav-aot** [comment]
@m-prodan do you need auto assignment for unopened request(request from angular app). Currently auto assignment added only from intake in progress onwards. Please confirm

**Comment by divyav-aot** [comment]
@m-prodan - as we discussed, the toast will indicate the success or failure. 
Also, any unsaved request in IAO and Ministry view also handled. If any unsaved data then the alert will show when you try to change the AssignedTo.

**Comment by mpilchar** [comment]
Passes! Excited about this one.... way to go @divyav-aot !
