### ISSUE TITLE
UX Research Plan for Ministries CFR

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#218]
#### Description:
text doc of tactics we'll use for user testing, goals and list of participants

#### DOD:
 - [x] Draft of UX Research Plan
 - [x] Reviewed and discussed by SME 
 - [ ] Reviewed and discussed by  PO

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan Could you review at the below link when you have a chance.

https://teams.microsoft.com/l/file/FBB066A5-9AF0-438F-A14B-820E033693E0?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FSprint%206%20-%20Research%20-%20Ministry%20Call%20For%20Records%2FUX%20Research%20Plan%20-%20Sprint%206%20-%20Ministry%20CFR.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by JHarrietha-AOT** [comment]
@m-prodan thanks for reviewing, and flagging that @arielleandrews is done for today. @lmullane Please review and leave comments. I'll work on the comments as they come through

**Comment by m-prodan** [comment]
@JHarrietha-AOT - comments made on this one too, similar to what I did with the study guide. All good from me now!

**Comment by JHarrietha-AOT** [comment]
@m-prodan Updated based on your comments, thanks Matt

**Comment by lmullane** [comment]
@JHarrietha-AOT, I made a couple of comments. Thanks for the opportunity to review.

**Comment by JHarrietha-AOT** [comment]
@lmullane @arielleandrews @m-prodan Research Plan has been updated based on everyones feedback. Thanks for taking the time to review and leave great feedback. If the plan looks good this can be moved to close

**Comment by lmullane** [comment]
@JHarrietha-AOT, good to close. Great work!
