### ISSUE TITLE
Support auto conversion to upper case for AXIS ID

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#2182]
Convert the AXIS ID to upper case automatically when you type in the AXIS ID Number cell in the Add/Review request page.

**Current Behavior** 
When you type in it is in lower case and is showing the validation error.

**Expected Behavior**
It should auto convert to upper case when you type in the AXIS ID Number cell

**Comment by m-prodan** [comment]
Functioning as expected in test - closing ticket.
