### ISSUE TITLE
Additional Application Details getting cleared off after AXIS Sync - Personal Requests 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2184]
**Describe the bug in current situation**
Not a deal breaker for 24th Go live . Issue is like Additional Applicant details like DOB , Correction Number, Employee Number is **getting cleared off**,  even though data exists on AXIS side as well as on FLOW side. At the same time, some other information is **not** getting cleared. Need to bring consistent logic on which data gets cleared and what need to be overwritten.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Lose data. High.

**Chance of Occurring (high/medium/low/very low)**
Medium. Impacts all requests with this information.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Public facing app, submit a Personal FOI request with Application DOB, Correction Number, Employee Number, Child details
2. Go to FLOW app, do an advanced search for above submitted FOI request
3.  Do AXIS with a request having Application DOB and other info on the FLOW 's unopened request
4.  We can see DOB, and other information getting cleared off while Sync'ing even though data exists.

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

* GIVEN a row requests from the FOI request form includes DOB, Correction Number, Employee Number, child details etc.
* WHEN a request is synced from AXIS
* The information (DOB, Correction Number, Employee Number, child details etc.)  should not be erased from the request in Flow (ie.,Fields that are not in AXIS/ that are not pulling from AXIS but exist in FOI request form should persist.)

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
@sumathi-thirumani-aot, try to replicate as discussed.

**Comment by arielleandrews** [comment]
Decision at standup Jul 12 to create new bug ticket to address issue of Identity Verified field

**Comment by m-prodan** [comment]
Per conversation with @aparna-aot yesterday - issue seems fixed but still an issue with DOB. Need to wait for #2448 and QA together

**Comment by aparna-aot** [comment]
Hey @m-prodan #2448 is already pushed to test. Can you do a QA and let me know if the issue still exists? I couldn't reproduce the issue and if you could show it on a call that would be great. Thanks!

**Comment by m-prodan** [comment]
@aparna-aot - it is working as expected now, thanks!
