### ISSUE TITLE
Received Date for Adv. Search results and Details page seems different, offset by 1 day

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2185]
**Describe the bug in current situation**
After searching for **Unopened** requests, Request Date mentioned on the Adv,. Search results and Request Details  page seems to be different or Details Page's request date is offset by a day.  

Note : Feels like, This happens for the requests submitted after 4PM/5PM , after business hours.
Search results show May 17 see below.
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/26ebba68-0238-42b4-b2db-57fdc932279c)
On the details page,
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/41f5c796-17db-475c-b15f-da6adfd43f97)
**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Medium impact.

Will confuse users and users could miss a request if they have narrow date ranges.

**Chance of Occurring (high/medium/low/very low)**
High

Lots for request outside business hours.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Submit a request after 4:30pm PST
2. Search for request in Advanced Search
3. See  the error - the date is the day it was submitted
4. Click on request
5. See the correct Received Date (next business day)

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN the request is submitted after 4:30PM PST
WHEN the user views the Received Date on the request view or advanced search
THEN the date should be the next business day (i.e. submitted after hours Wednesday, next business day is Thursday; submitted after hours on Friday, Saturday or Sunday, next business day is Monday).

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by richard-aot** [comment]
#2185, #2192 and #2308 are the same issue

**Comment by richard-aot** [comment]
Please note, the fix will only apply to new requests onward.
1. New requests created through online form in weekend, holiday and weekdays after 16:30 will have recevied date moved to next business day.
2. For new requests created through FOI app, if an IAO member select weekend or holiday as received date, it will change to next business day.

**Comment by KaraBeach** [comment]
@m-prodan- can you send a file through EOD Friday,  so we can check to ensure that a weekend received file will change to the next business day.

EDU-2022-202020 - was submitted on the 26th EOD and the received date has been updated correctly to the next business day 27th.

**Comment by m-prodan** [comment]
Weekend and stat holiday (bonus!) submission tested - received date as expected was set to Aug 2! 

Closing ticket
