### ISSUE TITLE
Advanced Search Results Sorting issue

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2187]
**Describe the bug in current situation**
The advanced search results listed in ASC order for Received Date, when there is "Unopened"(only!) selected.
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/b7bd3f3c-7dcc-44be-8815-b1d3053b94d6)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Advanced Search Results
2. Select only "Unopened" Request state filter 
3. On the Search results, We can see a list of Unopened results
4. But the Unopened Result sets are listed in ASC order, means latest one is on the last page.

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KaraBeach** [comment]
@richard-aot -Thank you for fixing this for an Intake user, it now sort DSC. order. Newest on top.
