### ISSUE TITLE
UX Recruitment of Ministry Contacts for CFR

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#219]
Title of ticket: 

#### Description
Focus will be on the user/ministry coordinator, with invite extended to manager as well
Out of scope: program areas

#### DOD
- [x] working group members (determine and list)
- [x] GCPE
- [x] Pilot ministries (PSSG and... @lmullane to clarify)
- [x] Clarify contact (core and secondary contacts, ie HLTH) within each ministry
- [x] Send out the invite

**Comment by m-prodan** [comment]
Recruitment emails sent to working group and other contacts - establishing list and availability.

**Comment by m-prodan** [comment]
Based on responses from WG members as well as internal discussions - invites have been sent on the following schedule:

Thursday July 29th @ 11 AM - SDPR Generals (Accepted and Completed)
Thursday July 29th @ 3PM - SDPR Personals (Accepted and Completed)
Friday July 30th @ 1PM - MUNI Generals (Accepted and Completed)

August 4th @ 1PM - GCPE Generals (Confirmed)
August 5th @ 10 AM - CITZ (Confirmed)
August 5th @ 2PM - FLNRO (Confirmed)
August 6th @ 11 AM - FIN - Single Point of Contact (Confirmation Pending)
August 6th @ 2PM - FIN - Divisional Contact (Confirmed)
August 9th @ 11AM - MAG - Divisional Contact (Confirmation Pending)
August 9th @ 1PM - ENV - (Confirmation Pending 1/2)
August 11th @ 10AM - EMBC - Divisional Contact of PSS - (Confirmed)
August 11th @ 2PM - EDUC (Confirmed)
August 12th @ 11 AM - Corrections Personals/Generals - Divisional Contact (Confirmed)

I've followed up with Health to see if they are willing participants, hoping to get a divisional contact and/or their main point of contact as well.

**Comment by m-prodan** [comment]
@lmullane - do we want to consider this one closed? Based on responses, all invites have been sent out. I have followed up with Health as I didn't get a response from them and wanted to give them an opportunity if they are able - but otherwise all invites have been sent based on the initial canvass/response.

**Comment by lmullane** [comment]
Yes, let's close
