### ISSUE TITLE
Description History API should have authorization for ministry

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2191]
**Describe the bug in current situation**
Using one ministry user login, from Browser tools, we can see "Description History" other ministry's personal request description. Seems like its dropped from PEN TEST. We need to put authorization for this API by its MINISTRY code, similar to what we have done for other API endpoints. UX is not rendering which is good, but particularly this API endpoint can expose Sensitive data . As per screenshot, I am using EDUC ministry user account to peek into LBR ministries personal requests, UX is not rendering, but we can see from the screen shot anyone can see data pulled from BE. 

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/bc2bf84c-6596-4e87-9590-1f489fc4db54)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

This is not a functional issue./ but can cause data exposure to other ministry  users

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/a0a0ac0d-0588-419f-ac45-8d15315282e5)

**Comment by m-prodan** [comment]
Request description history is function as expected - closing ticket!
