### ISSUE TITLE
State changes from CFR Form to Fee Estimate

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2194]
* As a ministry coordinator 
* I want a  completed CFR/Fee with estimated hours approved
* so that I can change the state of the request to Fee Estimate

**Assumptions & Scope**	
What are the assumptions for this story?

Completing the CFR form will be mandatory to change the state of the request to Fee Estimate unless the Total Fee Amount due on the saved CFR form is greater than $0.

What is IN scope?

Ministry coordinator cannot change the state to Fee Estimate without completing this CFR form.

What is NOT in scope?

Editing the CFR Form by ministry coordinator.

IAO view of the CFR form and Approval.

CFRs for Personal requests.

The divisional coordinator filling out the CFR form

**Acceptance Criteria**	

**Scenario 1: Change state from Call for Records to Fee Estimates**
* GIVEN a ministry coordinator has saved the CFR form and the Total Fees Due are greater than zero
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* WHEN the coordinator clicks on Fee Estimate in the state menu dropdown
* THEN the state model will open
* AND uploading a CFR form will no longer be required
* AND the blue 'Save Changes' button will be active

**Scenario 2: Fail to change state from Call for Records to Fee Estimates**
* GIVEN a ministry coordinator has NOT  saved the CFR Form view or the Total Fees Due are zero
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* WHEN the coordinator clicks on Fee Estimate in the state menu dropdown
* THEN the state model will open
* AND an error message will be displayed: "To update the state you must first complete the estimated hours in the CFR Form (insert link) so that Total Fees are due."
* AND the blue 'Save Changes' button will be inactive

**Scenario 3: CFR Form is in Call for Record**
* GIVEN a request is in the CFR state
* WHEN the IAO analyst is on the CFR form
* THEN the form is not editable
* AND the CFR Form state drop down is greyed out and not editable

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
For scenario 3 and 4, we should make clear that this validation only happens when a fee estimate has been levied and a fee estimate has been paid. If there is no fee being charged, the Ministries shouldn't have to enter actual hours to change states when no fees are involved on a general request.

**Comment by mpilchar** [comment]
Discussion capture from refinement - Estimated hours are active and Actual greyed out before state changes to Fee estimate. Once that change happen, they switch - estimated is greyed out and actual is active cc: @lmullane

**Comment by mpilchar** [comment]
Discussion from refinement: Dependent on applicant experience. Can't move forward without knowing the applicant's action

**Comment by m-prodan** [comment]
QA Passed - nice work @nkan-aot
