### ISSUE TITLE
Fee estimate/CFR view for IAO analyst for general requests

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2195]
* As an IAO analyst
* I want a CFR/Fee estimate view for every general request
* so that I can enter information review the fee estimates for the request 

Deduplication or Records Review

**Assumptions & Scope**	
What are the assumptions for this story?

The fields will be view only for IAO analysts.

Only IAO will have the 'Process Payment' button.

What is IN scope?

IAO viewing the CFR Form

What is NOT in scope?

Ministry coordinator view and editing the CFR form #2075

Ministry coordinator state changes are covered in #2194

CFRs for Personal requests.

The divisional coordinator filling out the CFR form

The divisional forms autofilling the Overall Estimate

In-app notifications that the CFR form has been Approved or Clarificaiton Required
**Acceptance Criteria**	

**Scenario 1: Overall Fee Estimate**
* GIVEN an IAO analyst is on the a the Request, Comments or Attachment view
* WHEN the user clicks the CFR Form on the left navigation
* THEN the  CFR Form view will open
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* AND will include the Overall Fees Estimate section with the following fields: Amount Pending, Total Fees Due, Locating/Retrieving (Estimated Hours, Actual Hours), Producing..(Estimated Hours, Actual Hours), Preparing...(Estimated Hours, Actual Hours), Volume - for electronic...(Electronic Estimated Hours, Electronic Actual Hours, Hardcopy Estimated Hours, Hardcopy Actual Hours)
* AND all the fields will be uneditable, except for amount paid
* AND there will be a drop down for 'Approved', 'In Review' (default) or 'Clarification Required'
*AND there will be a 'Save' button at the bottom 

**Scenario 2: Approve Overall Fee Estimate**
* GIVEN an IAO analyst is on the  CFR Form view will open
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* WHEN the IAO analyst has selected 'Approved'
* THEN the 'Save' button will become blue and active

**Scenario 3: Save Approve Overall Fee Estimate**
* GIVEN an IAO analyst is on the  CFR Form view will open
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* AND the IAO analyst has clicked the checkbox for 'Approved'
* WHEN the IAO analyst clicks the 'Save' button 
* THEN the CFR form will be saved as 'Approved'
* AND the request state can be updated to 'On Hold' (updating the request state will in a different story).

**Scenario 4: Clarification Required Overall Fee Estimate**
* GIVEN an IAO analyst is on the  CFR Form view will open
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* WHEN the  IAO analyst has selected ''Clarification Required'
* THEN the 'Save' button  will be blue and active

**Scenario 4: Save Clarification Required for Overall Fee Estimate**
* GIVEN an IAO analyst is on the  CFR Form view will open
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803
* AND the  IAO analyst has selected ''Clarification Required'
* WHEN the  analyst clicks  the 'Save' button
* THEN the the CFR form will be saved as 'Clarification Required'

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
[@xxx - please link the Design here](https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/cl2yw4ity00jd01yvh1913izr/play)
#1418

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by nkan-aot** [comment]
clarified at standup today, amount paid should be editable for iao. will update ac

**Comment by mpilchar** [comment]
I think there is one more AC we haven't written here but is implied, and that is putting it back to "In Review" and having it save if it is changed back to "In Review". Let me know if I should add this to Regression test master doc @lmullane

**Comment by mpilchar** [comment]
This looks great, all scenarios passed in Chrome. Thanks @nkan-aot and @richard-aot !
