### ISSUE TITLE
Fee Actuals and State Change Logic

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2198]
* As a Ministry Coordinator
* I want to know when I have to record the actuals of a fee estimate
* so that I can accurately complete a fee estimate during a call for records

**Assumptions & Scope**	
This is related to #2075 and follows the need for a Ministry user to fill in the actual hours/figures for a fee estimate when an applicant has paid the original estimate/deposit. 

Fee actuals will behave like they do with fee estimates, they will move in 0.25 hour increments, and have the same value calculation. IAO actuals will not be a mandatory field. 

What is IN scope?
Fee estimate actuals

What is NOT in scope?
Processing Payment
Applicant Experience

**Acceptance Criteria**	

**Scenario 1: Payment Received - Actuals field - editable**
* GIVEN a FOI request has any amount of a fee estimate recorded as paid
* WHEN a Ministry coordinator navigates to the fee estimate page
* THEN the fields for actual hours and volume of pgs will be editable
* AND the fields for the original estimate will be greyed out and uneditable

**Scenario 2: Change State from Call for Records to Deduplication or Records Review when Fee Paid - No Actuals**
* GIVEN a Ministry coordinator is on a request where a fee estimate has been paid in part or in full
* WHEN they attempt to change the state to Records Review, or Deduplication
* AND the actual hours have NOT been saved or updated in the fee estimate form, and all remain at 0
* THEN an error message will appear with the following message "Unable to change state until fee estimate actuals have been completed"

**Scenario 3: Change State from Call for Records to Deduplication or Records Review when Fee Paid - With Actuals**
* GIVEN a Ministry coordinator is on a request where a fee estimate has been paid in part or in full
* WHEN they attempt to change the state to Records Review, or Deduplication
* AND the actual hours have been saved or updated in the fee estimate form to be greater than 0 in any field
* THEN the state change will complete
* AND there will be no mandatory upload required. 

**Scenario 4: Change State from Call for Records to Deduplication or Records Review when Fee Paid - IAO Actuals**
* GIVEN a Ministry coordinator is on a request where a fee estimate has been paid in part or in full
* WHEN they change the state to Records Review, or Deduplication
* THEN the field for IAO actual hours will be editable by IAO
* AND the field will not be mandatory to complete

**Scenario 5: Balance Due Calculation**
* GIVEN an IAO analyst is on a request where a fee estimate has been paid in part or in full
* WHEN the state changes to Records Review, or Deduplication
* THEN the total due will update based on the actual hours, using the same logic as estimated hours
* AND the balance will calculate based on total due, subtracted by the amount paid. 
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Wrote up this story to manage the logic around fee actuals and state changes we had discussed at refinement this morning.

cc: @abin-aot @divyav-aot @JHarrietha-AOT @lmullane @mpilchar @KaraBeach

**Comment by m-prodan** [comment]
I wrote up this one a couple weeks ago - I don't think behaviour is going to change based on the flow, should we include this for refinement tomorrow?

**Comment by m-prodan** [comment]
updated per our call just now @aparna-aot - I think this addresses what we discussed

**Comment by aparna-aot** [comment]
@m-prodan Yeah. Looks good to me. Thanks.

**Comment by arielleandrews** [comment]
@aparna-aot this is not in the AC but a Ministry user can go from CFR state to Harms Assessment to Deduplication or Records Review without completing the Actuals in the CFR form. The modal still has the same warning text about needing to complete the actuals but if you upload a file then the Save Change button is active and the user can move forward. I will write up a separate user story to address this but wanted to include it here for reference

**Comment by aparna-aot** [comment]
Got it @arielleandrews. Thanks for writing up a new user story.

**Comment by arielleandrews** [comment]
@aparna-aot and @m-prodan I just noticed when inputting the Actuals for Search time, the balance is charging for all hours. The first 3 hours of search in the Actuals should still be free, and the charge should start from the 4th hour onward. I note though that this wasn't included in the assumptions or the AC. I can add this to the AC of #2641 or write up a separate bug ticket - Aparna do you have a preference?

**Comment by aparna-aot** [comment]
@arielleandrews I think we can include this case as well in the new task #2641 so that everything related to fee actuals will be in a single task.

**Comment by arielleandrews** [comment]
Thanks @aparna-aot! I've added a scenario to #2641. QA is completed on this ticket and all AC passed. Great work.
