### ISSUE TITLE
Capture requests in AXIS

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#22]
As an intake analyst, I want to be able to approve a request and have it be auto-populated in AXIS

**Acceptance Criteria**	

**Scenario 1: xxxxxx**
* GIVEN ... (you or your condition)
* WHEN ... (what you do) 
* THEN ... (what you see) 

**Scenario 2: xxxxxx**
* GIVEN ... (you or your condition)
* WHEN ... (what you do) 
* THEN ... (what you see) 

**Scenario 3: xxxxxx**
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
- Confirm technical feasibility of integration with AXIS
- IMB prioritization
- business decision ROI and opportunity cost

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.     [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by abin-aot** [comment]
refer - https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/bcgov/foi-flow/160

**Comment by lmullane** [comment]
Assumptions:

Initial research suggests that API integration is possible, but only:

- when the request is first opened in the new system can it be POSTED via API into AXIS. There is no current way to capture edits to an open request; would require further development of the AXIS API
- Saving an Open Request from the new system into AXIS requires an upgrade to the AXIS version 10.7. Currently that version is in DEV, but PROD release date is unknown.

**Comment by mpilchar** [comment]
Initial assumptions about integration were incorrect. Closing this ticket as it has been updated in other tickets
