### ISSUE TITLE
Develop UX study guide for CFR (ministries)

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#220]
**Description:**
Draft of the questions we will be asking users, plus a script

**DOD:**

- [x] Drafted
- [x] Reviewed and discussed with SME
- [ ] Reviewed and discussed with PO

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan Could you review this when you have a chance: 

https://teams.microsoft.com/l/file/391872CD-9220-4D9E-AC3D-1E9826C8BC93?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FSprint%206%20-%20Research%20-%20Ministry%20Call%20For%20Records%2FUX%20Study%20Guide%20-%20Sprint%206%20-%20Ministry%20CFR.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by m-prodan** [comment]
@JHarrietha-AOT - I've reviewed - it looks good to me, I've made some suggestions via the comment bubbles. @arielleandrews has logged out for the day - I know we've got our first session tomorrow morning so you may want to run it by @lmullane now.

I'll review the next doc!

**Comment by JHarrietha-AOT** [comment]
@m-prodan thanks for reviewing, and flagging that @arielleandrews is done for today. @lmullane Please review and leave comments. I'll work on the comments as they come through

**Comment by arielleandrews** [comment]
Thank you @JHarrietha-AOT! Looks great, I made a couple small suggestions in the document

**Comment by arielleandrews** [comment]
Looks great @JHarrietha-AOT, I have nothing further to add beyond what's been noted already

**Comment by JHarrietha-AOT** [comment]
@lmullane @arielleandrews @m-prodan I have updated the study guide based off of everyones feedback. Thanks to everyone for the great feedback and taking time to review. Let me know if there are any further changes, if everything looks good this can be moved to closed

**Comment by lmullane** [comment]
@JHarrietha-AOT looks good. Only suggestion is a follow up question on how they currently manage communications between them and IAO and internally. See my comment in the doc.
