### ISSUE TITLE
Change the Data Type of initialdescription column to TEXT

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#2207]
Title of ticket: 

#### Description
Change the Data Type of initialdescription column to TEXT 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] create migration script to alter initialdescription column type to TEXT 
- [x] integration test

**Comment by mpilchar** [comment]
@divyav-aot Is there AC we can test against for this one?

**Comment by mpilchar** [comment]
Will test with #2224. To test, create a script with more than 500 characters in request description and try to save. 
Test from angular app then try to open it in FOI-Flow
Create one of each: 1) Personal and one 2) General w/payment

**Comment by mpilchar** [comment]
Having trouble submitting on angular test. Request description is 645 words
