### ISSUE TITLE
CFR - Fees Processing Payment

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#2209]
Title of ticket: CFR - Fees Processing Payment

#### Description
Designing Screen and Process of IAO to be able to process a Processing Fees Charge to an Applicant

#### Dependencies
Are there any dependencies?

#### DOD
Items to remember in designs
- [x] Ability for user to be able to only pay 1/2 if fee is over $200
- [x] Ability for applicant to be able ti input fee payment themselves and click through process
- [x] Receipts/Invoice design should be the same as Previous Implement of BC Pay in Application Fees Process

**Comment by JHarrietha-AOT** [comment]
@m-prodan @lmullane Here is a link to where the online payment for applicants for processing fees. I haven't included the fee waive, but removed the button based off the conversation we had Friday. I am off today, but will work on the waive route based off the documents that were shared Friday regarding what qualified for a waived fee. 

I'll work on the waive fee Tuesday while flying back to Ontario along with any changes to the link below.

https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/921685067

**Comment by m-prodan** [comment]
Hi @JHarrietha-AOT - sorry haven't gotten to this as much as I wanted to. I like what I'm seeing so far - I think one thing that is missing, is that the invoice and receipt should include a breakdown of the charge. Or was that intended to be a part of the email sent to the applicant? If so, that is fine then as is (their receipts as they exist now only show total amounts paid, not a breakdown). I'd probably make some changes to some of the wording, but we can go over that more when you are back as I'm not sure where I can flag those stylistic changes

**Comment by lmullane** [comment]
@JHarrietha-AOT, could we also include a design for the email that the applicant receives notifying them of payment with a link to the first page you created?

@m-prodan, do we have to offer them the choice of paying with cheque? 

I'd prefer the button says pay online. Note, through PayBC an applicant can pay with a VISA or MC Debit which debits the amount directly from their bank account. The 5 big Canadian banks provide these kind of debit cards.
