### ISSUE TITLE
UX research sessions, round 1

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#221]
Title of ticket: 

#### Description
Conduct research sessions with participants. Each session will have a note taker. Synthezing results is a separate ticket.

#### Dependencies
Availability of Ministry clients, they will be given a 1 month window to select a time and date were they are available

#### DOD (list sessions as they get booked)
- [x] Karen Milne - SDRP - Thurs July 29th
- [x] Kerry Ast & Alice Gillespie - SDRP - Thurs July 29th
- [x] Danny Courcy & Vicki Hudson - MUNI - Friday July 30th

**Comment by JHarrietha-AOT** [comment]
Session 1 complete - see recording below

https://teams.microsoft.com/l/file/4DD50A57-B2DD-4BC8-914D-AAD8545B3EBB?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FSprint%206%20-%20Research%20-%20Ministry%20Call%20For%20Records%2FUX%20Research%20-%20Sprint%206%20-%20NOTES%20-%20Aug%2026-30.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by JHarrietha-AOT** [comment]
Session 2 complete - see recording below

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%206%20-%20Research%20-%20Recording/Session%202%20-%20%20Kerry%20Ast%20&%20Alice%20Gillespie%20-%20SDRP%20-%20Thurs%20July%2029th.mp4

**Comment by JHarrietha-AOT** [comment]
Session 3 complete - see recording below

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%206%20-%20Research%20-%20Recording/Session%203%20-%20Danny%20Courcy%20&%20Vicki%20Hudson%20-%20MUNI%20-%20Friday%20July%2030th.mp4

**Comment by JHarrietha-AOT** [comment]
All session booked for this sprint have been completed and linked above. Closing issue with this comment
