### ISSUE TITLE
Technical approach to applicant payment

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2211]
Title of ticket: 

#### Description
Technical team need to decide on architecture for payment (Angular vs Forms Flow vs Vue.js).

#### Dependencies
Are there any dependencies?

This needs to be decided before we can start next sprint.

#### DOD
- [x] Research on  payment for both application and processing fees.
- [x] Technical team to meet on approach
- [ ] PO decision
- [x] Architecture (applicant will be separate app)

**Comment by mpilchar** [comment]
Stand up June 6: Approach - Implement a single low or no code solution. Meet with Jackie on UX.

**Comment by abin-aot** [comment]
**Updated Architecture(v2) involving FormsFlow Web, Common Services, Pay BC.**
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/113cc20a-58d7-495b-888a-98bc7588ac43)

**High Level Effort Break Down**
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/eb2b1e36-69f8-4daa-88e4-28d560db3628)

we can discuss this tommorow @lmullane
