### ISSUE TITLE
Setup Additional Test Environment

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#2215]
DOD
============
- [x] Create redis cache
- [x] Create redis message broker
- [x] Create Patroni
- [x] Create forms-flow-web
- [x] Create forms-flow-bpm
- [x] Create request-management-api
- [x] Create angular api
- [x] Create angular web
- [x] Integration testing (Create Request)
- [x] Integration testing (web form submission) with payment
- [x] Integration testing (web form submission) without payment
- [x] KC

**Comment by mpilchar** [comment]
From the testing I've done, this checks out. Closing
