### ISSUE TITLE
UX research sessions, round 2

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#222]
Title of ticket: 

#### Description
Conduct research sessions with participants. Each session will have a note taker. Synthezing results is a separate ticket.

#### Dependencies
Availability of Ministry clients, they will be given a 1 month window to select a time and date were they are available

#### DOD (list sessions as they get booked)
- [x] 2 - Session 1 - Justin Smith - GCPE - Wed Aug 4
- [x]  2 - Session 2 - Jackie Biggs - CITZ - Thurs Aug 5
- [x]  2 - Session 3 - Tami Balsom & Samuel McGrew - FLNR - Thurs Aug 5
- [x]  2 - Session 4 - Melissa Morgan & Anne Sum - FIN - Fri Aug 6
- [x]  2 - Session 5 - Lynette Linkletter - FIN - Fri Aug 6
- [x]  2 - Session 6 - Teresa Latzel - AG - Mon Aug 9
- [x]  2 - Session 7 - Brooke McCunn & Alexandra Kavadas - ENV - Mon Aug 9
- [x]  2 - Session 8 - Cole Johnston - EMBC - Wed Aug 11
- [x]  2 - Session 9 - Carrie Preziuso - EDUC - Wed Aug 11
- [x] 2 - Session 10 - Justine Nisbet - PSSG - Thurs Aug 12

**Comment by JHarrietha-AOT** [comment]
2 - Session 1 - Justin Smith - GCPE - Wed Aug 4 - no recording - participant preferred to not have the session recorded

**Comment by JHarrietha-AOT** [comment]
2 - Session 2 - Jackie Biggs - CITZ - Thurs Aug  - RECORDING BELOW 

5https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%206%20-%20Research%20-%20Recording/2%20-%20Session%202%20-%20Jackie%20Biggs%20-%20CITZ%20-%20Thurs%20Aug%205.mp4

**Comment by JHarrietha-AOT** [comment]
2 - Session 3 - Tami Balsom & Samuel McGrew - FLNR - Thurs Aug 5 - RECORDING LINK BELOW

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%206%20-%20Research%20-%20Recording/2%20-%20Session%203%20-%20Tami%20Balsom%20&%20Samuel%20McGrew%20-%20FLNR%20-%20Thurs%20Aug%205.mp4

**Comment by JHarrietha-AOT** [comment]
2 - Session 4 - Melissa Morgan & Anne Sum - FIN - Fri Aug 6 - RECORDING BELOW

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%206%20-%20Research%20-%20Recording/2%20-%20Session%204%20-%20Melissa%20Morgan%20&%20Anne%20Sum%20-%20FIN%20-%20Fri%20Aug%206.mp4

**Comment by JHarrietha-AOT** [comment]
2 - Session 5 - Lynette Linkletter - FIN - Fri Aug 6 - RECORDING BELOW

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%206%20-%20Research%20-%20Recording/2%20-%20Session%205%20-%20Lynette%20Linkletter%20-%20FIN%20-%20Fri%20Aug%206.mp4

**Comment by JHarrietha-AOT** [comment]
2 - Session 6 - Teresa Latzel - AG - Mon Aug 9 - RECORDING RELOW

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%206%20-%20Research%20-%20Recording/2%20-%20Session%206%20-%20Teresa%20Latzel%20-%20AG%20-%20Mon%20Aug%209.mp4

**Comment by JHarrietha-AOT** [comment]
2 - Session 7 - Brooke McCunn & Alexandra Kavadas - ENV - Mon Aug 9 - RECORDING BELOW

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%206%20-%20Research%20-%20Recording/2%20-%20Session%207%20-%20Brooke%20McCunn%20&%20Alexandra%20Kavadas%20-%20ENV%20-%20Mon%20Aug%209.mp4

**Comment by JHarrietha-AOT** [comment]
2 - Session 8 - Cole Johnston - EMBC - Wed Aug 11 - RECORDING BELOW

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%206%20-%20Research%20-%20Recording/2%20-%20Session%208%20-%20Cole%20Johnston%20-%20EMBC%20-%20Wed%20Aug%2011.mp4

**Comment by JHarrietha-AOT** [comment]
2 - Session 9 - Carrie Preziuso - EDUC - Wed Aug 11 - RECORDING BELOW 

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%206%20-%20Research%20-%20Recording/2%20-%20Session%209%20-%20Carrie%20Preziuso%20-%20EDUC%20-%20Wed%20Aug%2011.mp4

**Comment by JHarrietha-AOT** [comment]
2 - Session 10 - Justine Nisbet - PSSG - Thurs Aug 12 - RECORDING BELOW

https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%206%20&%207%20-%20Research%20-%20Recording/2%20-%20Session%2099%20-%20Justine%20Nisbet%20-%20PSSG%20-%20Thurs%20Aug%2012.mp4

**Comment by JHarrietha-AOT** [comment]
All sessions to be completed in this ticket have been completed and links above for reference.
