### ISSUE TITLE
Github advisories 

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#2224]
Title of ticket: 

#### Description
https://github.com/advisories/GHSA-6h5x-7c5m-7cr7/dependabot?query=user:bcgov

#### DOD
- [x] Check FOI-Flow
- [x] Check FOI-Requests
- [x] Discuss recommendations for fixing

#### DOD - TEST
- [x] Angular Personal
- [x] Angular General
- [ ] Flow Personal
- [ ] Flow General

**Comment by divyav-aot** [comment]
@mpilchar - don't close this ticket. I am yet to push the changes of FOI-Flow app
