### ISSUE TITLE
Assign Processing team member

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#2225]
Title of ticket: 

#### Description
New issue encountered in syncing...it is not a bug. There are 2 requests in AXIS that are in a current action that we would map to the Call for Records state in the new app.  However both requests in AXIS are assigned to a processing team member: Given that the state of the record is in Call for Records we are only able to assign the request to either an Intake or Flex team member. This was intended; however that does not align with the businesses behaviour.  Looks like we need to allow the IAO user to assign to a processing team when the request is in the Call for Records state

This exists for Personal requests but would need to apply to General requests. Seems to be straight forward from a BACK DATA update/ migration script, but need to check all permutations along with the queue etc.

![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/beaa33e1-94dd-4492-846c-bf50f9d4aaff)

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] update backend
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by m-prodan** [comment]
Per my comments on 2239 - I have tested and confirmed that we can now assign general requests in CFR state to processing teams

**Comment by lmullane** [comment]
@abin-aot, please add an estimate:)
