### ISSUE TITLE
Days Remaining Not Calculating on Overdue Files

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2227]
**Describe the bug in current situation**
Requests that are overdue show an incorrect number of days overdue - pattern is unclear

**Link bug to the User Story**

**Impact of this bug**
Users will be confused by discrepancies with AXIS, and Ministry users may believe files are more overdue than they are

**Chance of Occurring (high/medium/low/very low)**
High - issue appears present in every overdue request

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
PROD - Sync file over from AXIS that is over due
See result

**Steps to Reproduce**
1. Go to any overdue request
2. Click on review request page
4. See Days Overdue
5. Compare against AXIS

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN a FOI Request is Overdue
WHEN a business day passes
THEN the overdue counter increases by 1

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by mpilchar** [comment]
close - was fixed last week
