### ISSUE TITLE
Report out of UX research for ministries

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#223]
Title of ticket: 

#### Description
Create a Report out of Research and present at Demo

#### Dependencies
Completion of all research sessions with as many ministries as possible

#### DOD
- [x] Create overall user flow of identify where and how IAO and Ministries will interact within our app
- [x] Identify pain points each ministry experiences
- [x] Create MIRO Board to share existing user flows, existing pain points, and new/proposed user flow and identify how the pain points will be relieved and how ministry and IAO will communicate and intake with one another
- [x] Present Report out at Demo of Sprint 8

**Comment by mpilchar** [comment]
Description:
Develop a virtual white board to share pain points, information summarized, action items

DOD:

- [ ] Miro board completed
- [ ] Reviewed by team
- [ ] Shared at sprint review

**Comment by JHarrietha-AOT** [comment]
Demo completed on August 31st.
