### ISSUE TITLE
Advanced Search - overdue lists on hold requests

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#2235]
Describe the bug in current situation
Advanced Search - search overdue requests and it lists "On Hold" requests

Link bug to the User Story
#1213

Impact of this bug
Describe the impact, i.e. what the impact is, and number of users impacted.

All users 

Chance of Occurring (high/medium/low/very low)

High

Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?
all env

Steps to Reproduce

Go to Advanced Search
Select "Overdue" under "Request Status"
Click Apply search

Actual/ observed behaviour/ results
Result contains "On Hold" requests

Expected behaviour
The list should not includes "On Hold" requests

Screenshots/ Visual Reference/ Source
Search criteria
![image.png](https://images.zenhubusercontent.com/6140ffb032396d7b882056ce/75d32eb9-b372-4655-93e9-8963b5fdd206)

Actual Result
![image.png](https://images.zenhubusercontent.com/6140ffb032396d7b882056ce/ea32309e-a220-4df6-a7c1-e229501d9b58)

**Comment by KaraBeach** [comment]
Expected behavior now works as it should - Thank for fixing! @richard-aot
