### ISSUE TITLE
Overdue days calculation is wrong

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#2236]
screenshot taken on may 26th
![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/1c355fcf-bda2-498d-947e-f69d7b090d6e)

**Impact of this bug**
medium

**Chance of Occurring (high/medium/low/very low)**
high

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
- go to advanced search
- search for overdue requests
- open any of the results
- scroll to due date, compare to counter in left panel
example requests in prod
EDU-2022-20729
LBR-2019-98481

**Actual/ observed behaviour/ results**
see screenshot, days overdue count is inaccurate

**Expected behaviour**
should be number of days after due date, minus weekends and holidays
if today is due date, should say 0 days remaining
if tmr is due date, should say 1 day remaining
if due date was yesterday, should say 1 day overdue
etc.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KaraBeach** [comment]
@nkan-aot  I tested with MMA-2022-00013 (( test axis shows - 507 days overdue and test flow shows -524)

**Comment by nkan-aot** [comment]
ok looking into it

**Comment by KaraBeach** [comment]
@nkan-aot - closing this ticket as @m-prodan  has confirmed that current calendar year is fixed. Separate ticket is made for past calendar years
