### ISSUE TITLE
Overdue days calculation is for files from past calendar years 

### ISSUE THREAD

**Issue by KaraBeach** [bcgov/foi-flow#2240]
Overdue days calculation is for files from past calendar years 
screenshot taken on may 26th
image.png

Impact of this bug
medium

Chance of Occurring (high/medium/low/very low)
high

Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?

Steps to Reproduce

go to advanced search
search for overdue requests
open any of the results
scroll to due date, compare to counter in left panel
example requests in prod
EDU-2022-20729
LBR-2019-98481
Actual/ observed behaviour/ results
see screenshot, days overdue count is inaccurate

Expected behaviour
should be number of days after due date, minus weekends and holidays
if today is due date, should say 0 days remaining
if tmr is due date, should say 1 day remaining
if due date was yesterday, should say 1 day overdue
etc.

Screenshots/ Visual Reference/ Source
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KaraBeach** [comment]
@nkan-aot separating this ticket out from #2236. This new ticket is for past calendar years.
Can you please confirm your estimated time for this. 
I will be closing ticket #2236 as the current calendar year is fixed.

**Comment by nkan-aot** [comment]
fix has been pushed to prod and verified, closing issue
