### ISSUE TITLE
DISABLE  Source map generation on Front End and minify JS file  

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2246]
**Describe the bug in current situation**
We need to Disable source map exposure on the browser, which enables any user to debug things , if any.  Also, need to compress JS files

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
No functional QA testing for this bug.

**Comment by abin-aot** [comment]
Completed.
