### ISSUE TITLE
BE Changes for Fee estimate/CFR view for ministry coordinator for general requests(#2075)

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#2252]
Title of ticket: 
BE Changes for Fee estimate/CFR view for ministry coordinator for general requests(#2075)
#### Description
BE Changes for Fee estimate/CFR view for ministry coordinator for general requests(#2075) 

#### Dependencies
Are there any dependencies?

#### DOD

- [x] Migration scripts for CFR Fee Form.
- [x] Add new APIs - CRUD
- [x] Unit tests
- [x] Integration test

**Comment by aparna-aot** [comment]
**APIs :** 

- POST  http://localhost:15000/api/foicfrfee

Response : 
`{
    "id": 1,
    "message": "CFR Fee Form added",
    "status": true
}`

- GET  http://localhost:15000/api/foicfrfee/ministryrequest/1

`{"cfrfeeid": 1, "ministryrequestid": 1, "feedata": {"amountpaid": 10.0, "amountdue": 0.0}, "overallsuggestions": "text"}`

- PUT   http://localhost:15000/api/foicfrfee

`{
    "id": 1,
    "message": "CFR Fee updated",
    "status": true
}`

**Comment by mpilchar** [comment]
closing since the story is currently in QA
