### ISSUE TITLE
Angular App - PayBC Revenue Coding Update

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2254]
Title of ticket: Angular App - PayBC Revenue Coding Update

#### Description
Notified by PayBC that our reconciliation reports are not correct - there is an issue with the revenue coding we are using.

#### DOD
- [ ] Connect Team/Developer with PayBC Team
- [ ] Confirm Issue
- [ ] Update Code
- [ ] Deploy
- [ ] Confirm Issue is fixed

**Comment by acoard-aot** [comment]
This was resolved, confirmed by PayBC contact. Closing task.
