### ISSUE TITLE
CFR Form - Review/Approve Fee Estimate

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2258]
* As an IAO User
* I want to be able to approve a fee
* so that I can proceed to putting a request on hold

**Assumptions & Scope**
Primarily a FE change to #2195 to make current checkbox into a dropdown menu
	
This story reflects the need for IAO to signal to the Ministry the stage it is at when a request is in fee estimate, and whether or not clarification is required. If a user updates the state to "Needs Clarification" the Ministry will be able to edit the estimated figures. IAO will communicate concerns to the Ministry through the comments feature. 

What is IN scope?
IAO permissions and abilities to modify the CFR Form Status

What is NOT in scope?
Notifications/Comments for updates to state
Placing request on hold
Sending payment instructions to applicant
processing payments

**Acceptance Criteria**	

**Scenario 1: CFR Form Status - In Review Upon Viewing**
* GIVEN an IAO analyst is on a request in the 'Fee Estimate' state
* WHEN they click on CFR Form
* THEN they will be taken to the CFR form with overall fee estimate
* AND the CFR form status will automatically update to "In Review"
* AND the form will be editable for the IAO analyst

**Scenario 2: CFR Form Status - Drop Down Options**
* GIVEN an IAO analyst is on the CFR form page
* WHEN they activate the drop down for the CFR status
* THEN they will see 3 options they can select: "In Review (default), Approved, Needs Clarification"

**Scenario 3: Change of Status Modal - Needs Clarification**
* GIVEN an IAO analyst is  on the CFR form page, and has activated the drop down for CFR Status
* WHEN they change the status to "Needs Clarification"
* THEN a modal will pop out and ask "Are you sure you want to change the status to needs clarification? The CFR form will be locked for editing and only the Ministry coordinator can change it back"
* AND there will be an option to 'Save' and 'Cancel'

**Scenario 4: Change of Status Modal - Activate Save - Needs Clarification**
* GIVEN an IAO analyst is on the Change of Status Modal for Needs Clarification
* WHEN the analyst clicks save
* THEN the modal will close
* AND a toast will appear indicating the save was successful
* AND the new CFR form status will now display for both Ministry and IAO 

**Scenario 5: Change of Status Modal - Approved**
* GIVEN an IAO analyst is  on the CFR form page, and has activated the drop down for CFR Status
* WHEN they change the status to "Approved"
* THEN a modal will pop out and ask "Are you sure you want to change the status to approved? The CFR form will be locked for editing, and can only be unlocked by changing the status back"
* AND there will be an option to 'Save' and 'Cancel'

**Scenario 6: Activate Save - Approved**
* GIVEN an IAO analyst is on the Change of Status Modal for Approved
* WHEN the analyst clicks save
* THEN the modal will close 
* AND a toast will appear indicating the save was successful
* AND the new CFR form status will now display for both Ministry and IAO 

**Scenario 7: Change of CFR Status Modal - Cancel**
* GIVEN an IAO analyst is on the change of status modal for either approved OR needs clarification
* WHEN the analyst clicks cancel
* THEN the modal will close and the status will revert to the prior status

**Scenario 8: Form editable in  Needs Clarification**
* GIVEN an ministry coordinator is on the CFR Form Page
* WHEN the form has been put in Clarification by the IAO analyst
* THEN the form will be editable by ministry coordinator

**Scenario 9: Estimated hours on form not editable in Approved**
* GIVEN an ministry coordinator is on the CFR Form Page
* WHEN the form has been put in the Approved state by the IAO analyst
* THEN the estimated hours on the form will NOT be editable by the ministry coordinator

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/915277140

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
CFR form review/approve fee estimate story - ready for review, hoping to get this in for refinement on friday. 

Comments welcome @lmullane @JHarrietha-AOT @KaraBeach @mpilchar

**Comment by lmullane** [comment]
Looks good, @m-prodan. This is ready for refinement IMO.

**Comment by KaraBeach** [comment]
I agree with @lmullane - The process makes sense. @m-prodan

**Comment by JHarrietha-AOT** [comment]
This ticket is only focused on the front end changes of the state of the CFR Form, and how it will desplay

**Comment by nkan-aot** [comment]
@m-prodan sorry didn't catch this update to the AC until now, though the modal changes would come in a separate ticket. Will need an extra day or so to complete this

**Comment by sumathi-thirumani-aot** [comment]
@m-prodan @lmullane  Can the IAO change from "On Hold" to "CFR" even if payment is not done. 
Assuming yes; considering the scenario of waiver.
Can you please explain this scenario.

**Comment by sumathi-thirumani-aot** [comment]
@m-prodan @lmullane  Can the actuals go above estimated values in terms of hours .

**Comment by m-prodan** [comment]
Closing ticket as AC is met.

@sumathi-thirumani-aot - sorry missed your questions here. Yes - actuals can go above estimate, sometimes the estimates are under-estimated.

And also yes re: no payment - a fee can be waived. There is a seperate flow for that that we will need to go through/map
