### ISSUE TITLE
Queue changes - Ascending/Descending and Number displayed

### ISSUE THREAD

**Issue by KaraBeach** [bcgov/foi-flow#2267]
* As any user
* I want sort any queue or Advanced Search columns
* so that the columns will all sort ascending and descending

**Assumptions & Scope**	
What are the assumptions for this story?

**User:**               **Columns:**
Flex User:            Days Left
Analyst:               On behalf of, Days remaining, ext

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: **
* GIVEN any user is looking at their request queue or advanced search
* WHEN they click on the column the 1st time
* THEN the column will sort ascending

**Scenario 2: **
* GIVEN any user is looking at their request queue or advanced search
* WHEN they click the column a 2nd time
* THEN the column will sort descending 

**Scenario 3: Return to Default**
*GIVEN I am on the queue  or advanced search and have sorted columns
*WHEN I click on the "My FOI queue" button
*THEN columns will reset to default settings

**Scenario 4: Change number of items in queue displayed**
*GIVEN I have logged in 
*WHEN I click on any queue view or advanced search settings (my queue, team queue, etc)
*THEN I will see a default of 100 results
*AND have an option to select other result amounts as well (10, 20, 50, 100)
- DESIGN needed - 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@lmullane @mpilchar - for review, unsure if scenario 3 is possible but can confirm with devs at refinement

**Comment by lmullane** [comment]
@JHarrietha-AOT, will need a design for this story:)

**Comment by JHarrietha-AOT** [comment]
@amichard Here is the design: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932453

Let me know if you have any questions. I used the last pagination component as a model

**Comment by mpilchar** [comment]
You accidently tagged the wrong Richard! Tagging @richard-aot but hi @amichard - miss ya!

**Comment by richard-aot** [comment]
Thanks @JHarrietha-AOT and @mpilchar

**Comment by m-prodan** [comment]
Updated AC to exclude 200 results per discussion at standup today @richard-aot 

cc @lmullane

**Comment by richard-aot** [comment]
Increased the estimate to 8. Spent more effort on customized the MUI components (DataGrid footer and page size).

**Comment by richard-aot** [comment]
This user story is ready for QA on test-marshal.

**Comment by KaraBeach** [comment]
@richard-aot,  If I am logged in as a processing analyst there is no ability to sort the column "ext" in both the queue and advanced search.  Once, that is updated we can pass a/c 1-3. 

a/c 4 has passed. @m-prodan

**Comment by richard-aot** [comment]
Thanks @KaraBeach, I'm investigating this issue now.

**Comment by lmullane** [comment]
Passed as expected. Thanks for your work on this ticket, @richard-aot 

Note, I have updated the AC in the Master QA list to reflect the full functionality, including listing the exact number of the search results.
