### ISSUE TITLE
CFR Form - Review/Approve Fee Estimate - Sys Gen Comments

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2268]
* As a user
* I want the decisions made regarding fee estimates reflected in the request history 
* so that I can see how a request progressed

**Assumptions & Scope**	
This is related to User Story #2258 / #2195 - and reflects the need for a comment to be posted  to confirm that IAO is either satisfied with the fee estimate or is requesting further clarification.

What is IN scope?
System Generated/Request History comments

What is NOT in scope?
Other activities related to fee estimates
Notifications - handled in #2259

**Acceptance Criteria**	

**Scenario 1: CFR Form Status updated to Approve**
* GIVEN an IAO user has selected Approve on CFR form status
* WHEN they click save
* THEN a system generated comment will post to comments with the following message: "USER updated Fee Estimate to approved"

**Scenario 2: CFR Form Status updated to Needs Clarification**
GIVEN an IAO user has selected Needs Clarification on CFR form status
WHEN they click save
THEN system generated comment will post to comments with the following message: "USER updated Fee Estimate status to Needs Clarification"

**Scenario 3: CFR Form Status updated to In Review by ministry coordinator**
GIVEN a ministry coordinator has selected In Review on CFR form status
WHEN they click save
THEN system generated comment will post to comments with the following message: "USER updated Fee Estimate status to In Review"

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
none needed, will use existing system generated comment logic

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by sumathi-thirumani-aot** [comment]
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/7f5664a1-ceaa-4b44-9191-8476fe763960)

**Comment by m-prodan** [comment]
@sumathi-thirumani-aot - moving back to 'In Review' - AC 1 and 2 were passed, AC 3 is not functioning as expected. There is no comment being posted when Ministry reverts back to in review.
