### ISSUE TITLE
Change request from Fee Estimate to On Hold

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2270]
* As an IAO analyst
* I want to change a request with an approved CFR form to On Hold
* so that I can notify the applicant of the assessed fee

**Assumptions & Scope**	
What are the assumptions for this story?

A request can only be put On Hold if the CFR Form has been approved.

An applicant without an email address will be notified of the fee payment following the current process in AXIS.

An applicant with an email address on file will be notified of the fee payment through the new application. They will be able to pay the fee online via PayBC.

What is IN scope?

Changing a request to the On Hold state. Includes exception handling if the form is not approved.

What is NOT in scope?

The applicant notification and fee payment will be covered in other stories.

Approving the CFR Form is covered in #2268

Stopping the clock - that is already in place.

**Acceptance Criteria**	

**Scenario 1: Form is not Approved**
* GIVEN the CFR Form has not be approved
* WHEN the IAO analyst clicks On Hold in the state dropdown
* THEN a modal will open with the message: "You must review and approve the CFR Form before you can put this request On Hold." - https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922730566
* AND there will be only a close button in the modal.

**Scenario 2: Form is Approved but there is no applicant email on file**
* GIVEN the CFR Form is approved
* AND there is no applicant email on file
* WHEN the IAO analyst clicks On Hold in the state dropdown
* THEN a modal will open with the message: "There is no applicant email on file. Please check the box to confirm that you have mailed the applicant a letter before you put this request On Hold."
* AND there will be an empty checkbox
* AND as is now there will be the IAO and ministry assignees
* AND there will be a 'Save Change' and 'Cancel' button - https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922730567
* AND the 'Save Change' button will be disabled

**Scenario 3: Click Checkbox when there is no applicant email on file**
* GIVEN the CFR Form is approved
* AND there is no applicant email on file
* AND the analyst is on the  IAO analyst modal with the message: "There is no applicant email on file. Please check the box to confirm that you have mailed the applicant before you put this request On Hold."
* WHEN  the analyst clicks the checkbox
* THEN the checkbox will turn green with a white checkmark - https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922730568
* AND  the 'Save Change' button will turn blue and be active 

 **Scenario 4: Form is Approved and there is an applicant email on file**
* GIVEN the CFR Form is approved
* AND there is an applicant email in file
* WHEN the IAO analyst clicks On Hold in the state dropdown
* THEN a modal will open with the message: "Upload the completed Fee Estimate letter to change the state of this request to On Hold. When you change Request #MIN-YEAR-12345 to On Hold
the clock will be stopped and the applicant will automatically be emailed the fee estimate letter"_
* AND there will be a box with an 'Add File' button and a message: "Drag or drop Fee Estimate letter'
* AND there will be a 'Save Change' and 'Cancel' button - 
* AND the 'Save Change' button will be be grey and inactive

**Scenario 5: Add Fee Estimate letter**
* GIVEN the On Hold modal is open
* AND there is an applicant email in file
* WHEN the IAO analyst clicks the 'Add Files' button
* THEN a finder a document folder will open on their machine

**Scenario 6: Upload Fee Estimate letter**
* GIVEN the On Hold modal is open
* AND the IAO analyst has clicked the 'Add Files' button
* WHEN the analyst selects a file and click Open on a valid file type (must be PDF)
* THEN file will appear in the upload box
* AND the 'Save Change' button will be be blue and active

**Scenario 7: Drag Fee Estimate letter**
* GIVEN the On Hold modal is open
* AND the IAO analyst has clicked the 'Add Files' button
* WHEN the analyst drags a valid file type (must be PDF) into the box
THEN file will appear in the upload box
* AND the 'Save Change' button will be be blue and active

**Scenario 8: Save On Hold**
* GIVEN the analyst is on the On Hold modal
* AND the 'Save Change' button is blue and be active
* WHEN the analyst clicks the 'Save Change' button
* THEN the request state will be update to 'On Hold'
* AND the modal will close 
* AND the clock will stop

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Looks good to me Loren! Sorry for the delay in reviewing, had to help some users troubleshoot issues.

**Comment by lmullane** [comment]
We will need a design for this story as well, @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
Design Links added to stories above: @lmullane

**Comment by lmullane** [comment]
Will rewrite AC to reflect decision to have letter drafted in AXIS and uploaded into Flow when putting the request On Hold.

**Comment by lmullane** [comment]
@abin-aot, @JHarrietha-AOT, @m-prodan, updated the AC with the letter upload. Will need to review the adjusted AC to see if the estimate changes.

Using the same approach as we do for other required uploads for state change, except that it must be a PDF (no Word docs).

**Comment by lmullane** [comment]
Will go into TEST marshal.

**Comment by m-prodan** [comment]
I like that idea - it's not immediately clear how long its been on hold, so that would be a nice way to show it.

**Comment by KaraBeach** [comment]
@m-prodan @JHarrietha-AOT @nkan-aot   A/C's function as they should. Great work!
