### ISSUE TITLE
Full Fetch of AXIS IDs to FE is not required.

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2279]
**Describe the bug in current situation**
 There is a backend API (<BASE URL> / api/foirawrequest/axisrequestids) which was created to do validate existing AXIS Request IDs .   Basically, there is no need to do a full fetch of AXIS ids to FE . Also, there is no need to load this API for all request status

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to any request
2. Click on developer tool bar - 
3. Find this API URL response , api/foirawrequest/axisrequestids - can see all AXIS IDs on the FLOW system.

**Actual/ observed behaviour/ results**

**Expected behaviour**
We can do a check on click of the Sync with AXIS.
1. Go to Add Request page.
2. Enter an existing Axis Id and click on Sync with AXIS button.
4. The  "**AXIS ID Number already exists**" message will be displayed only after clicking on the Sync with AXIS button.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KaraBeach** [comment]
functions as it should now. thank you @aparna-aot
