### ISSUE TITLE
Auto assignment of assignee  alerts/clears the rest of the Request Details fields

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2281]
**Describe the bug in current situation**
If  the user decides to enter the Request Details fields **first** on a request with status above OPEN, then if he tries to change the assignee drop on top right, the browser will alert mentioning about the clear of the changes on request.

This came into conversation/demo'ing with @lmullane  , @m-prodan , @aparna-aot , @nkan-aot . @sumathi-thirumani-aot , @abin-aot . Idea is to make this auto assignment similar to add watchers feature and stop alerting about the changes on request form , and/or not clear the changes on form

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to any request, which has auto assignment.
2. Fill in the Request Fields like Description, Applicant Names etc. ( except Assignment Dropdown)
3.  Before doing "SAVE or state change", GO and change the selection on the Assignment Drop down
4. See issue : Browser Alerts that Fields will get cleared. In certain states(Unopened, Add Request), its clears without alerting

**Actual/ observed behaviour/ results**

**Expected behaviour**

1. Go  to any  request - technically above OPEN status
2. Change the values on the input fields - Applicant name, Description
3. Change the Assignee from top right dropdown
4. Browser should not alert for clearing the fields, but need to save the assignee - SIMILAR to WATCHER feature. and/OR not clear the fields.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
Confirmed this is fixed in TEST marshal. Still needs to be tagged to TEST.

Nice work, @aparna-aot
