### ISSUE TITLE
Troubleshoot webform issue for General payment

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#2285]
Solve for: 
1) Which requests came through our system but have not been received by Intake?  
2) Were any Personals impacted?
3) Are there any requests where, due to this issue, applicants got charged multiple times 

#### DOD
- [x] Dev team to Provide Intake Mgr with full list of General requests received in May and June:  Request ID, Applicant ID, date and description for

**Comment by mpilchar** [comment]
cc: @abin-aot @acoard-aot @arielleandrews @m-prodan @lmullane 
Please add to DOD and estimate effort of this.

**Comment by m-prodan** [comment]
@abin-aot @lmullane - tested another pay scenario and BCSC in TEST - no issues. I think we are good to go to PROD given the other tests the devs did over 10AM, including IGE and a non-BCSC personal request
