### ISSUE TITLE
Design - Queue Updates 

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#2292]
Title of ticket: Design - Queue Updates 

#### Description
Design updates for Queue to capture how many request total are displaying in Queue along with users ability to change number of request displaying in queue

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Indicator on Queue of total number of requests showing
- [x] Dropdown to change number of results displaying in queues

**Comment by JHarrietha-AOT** [comment]
@m-prodan Did we happen to ask at Demo what users would want the default number of items to be?

**Comment by m-prodan** [comment]
Yes @JHarrietha-AOT  - heard very strongly they'd like 100 (similar to AXIS) - I believe @lmullane has fleshed out some of the requirements based on what we heard at demo

**Comment by m-prodan** [comment]
See #2262

**Comment by JHarrietha-AOT** [comment]
Material UI examples for reference: https://mui.com/material-ui/react-pagination/

**Comment by JHarrietha-AOT** [comment]
Design can be seen here: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932453

**Comment by lmullane** [comment]
@JHarrietha-AOT, on the design do you click the arrow next to 100 for the options to see a different number of requests (i.e., 20, 50, 100, 200, etc.)?

**Comment by JHarrietha-AOT** [comment]
@lmullane that is correct. I should be the same as the material UI Component (Last one if you scroll to the bottom) 
that I linked in the ticket and shared with Richard: https://mui.com/material-ui/react-pagination/
