### ISSUE TITLE
Divisonal tracking reporting for ministries

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2297]
* As a pilot ministry coordinator
* I want divisional tracking on my reporting dashboard
* so that I can see how divisions are responding

**Assumptions & Scope**	
What are the assumptions for this story?

Our system does not have consults currently.

Graphs that default by ministry become by division when filter is applied.

Ministry coordinator wants to extract data to provide to ministry division.

Require an ETL from the new app into the reporting warehouse

ETL will run on OpenShift - new Python framework

Divisional Tracking:
Filter by division
Filter by request state
Filter by divisional stage
Due dates for 3 stages (Harms, Ministry Sign Off, Records Gathering)
Average numbers of days for each stage by Division and Ministry Total
Average number of days per state by Division and Ministry Total

What is IN scope?

Divisional tracking for pilot ministries.

What is NOT in scope?

Divisional tracking for non-pilot ministries. 
**Acceptance Criteria**	

**Scenario 1: xxxxxx**
* GIVEN the ministry coordinator is on Redash 
* WHEN the ministry coordinator selects the ministry reporting dashboard
* THEN the coordinator graphs for Percentage On-Time by Ministry, Total Closed by Ministry, Total Active by Ministry, Average Processing Days by Ministry, Average Days Overdue by Ministry, Average Days by Request States, Average Days by Divisional Stages, Number of Processing Pages by Ministry, No Records Response by Ministry
* AND filters for End FYr, End FQtr, By Month, By Week, Request Type (General, Personal), Request Status (Active, Overdue, Closed), Ministry (4 for Economy Sector), Division, Applicant Type, Ministry Assigned To (i.e., coordinators)

**Scenario 2: xxxxxx**
* GIVEN ... (you or your condition)
* WHEN ... (what you do) 
* THEN ... (what you see) 

**Scenario 3: xxxxxx**
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan. @JHarrietha-AOT, did I miss thing anything from the session with the economy sector?

**Comment by lmullane** [comment]
nkan-aot, please review and comment.

**Comment by nkan-aot** [comment]
features we need to add - 
1) category by division
2) category by Request States
3) Number of Processing Pages by Ministry
4) No Records Response by Ministry
5) Filter by division, analyst

**Comment by arielleandrews** [comment]
@nkan-aot is this a duplicate ticket? Were all these changes covered in #2379?

**Comment by lmullane** [comment]
Duplicate
