### ISSUE TITLE
ETL from Flow into data warehouse

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2298]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Select OpenShift ETL framework
- [x] Set Framework up
- [ ] Data warehouse design (adding additional tables)

**Comment by abin-aot** [comment]
Decided to go ahead with [Prefect ](https://www.prefect.io/) as the ETL / Data Flow Tool. Analyzing other tools like Apache Nifi, AirFlow which has bit more complex set up and less control over ETL using scripting , they mainly use UI based etl tasks - flows. Prefect gives much more control from developer/technical stand point, that we can create Python ETL scripts and deploy to Prefect.  Prefect basically comes in 2 flavours - Cloud and Server based, where we can use "Server" based set up - to configure it on BC GOV OCP. More this tools give better Dashboard UX to monitor RUN cycles, logs , set up schedules etc. 

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/5dbd3417-c68e-4bfa-be7f-c23617a5157b)

Also there are prebuilt ETL Task components for PostGres , which can utilized https://docs.prefect.io/api/latest/tasks/postgres.html#postgresexecute

PROS

1.  This Tool can used for any Dataflow management, Pipeline. In future it can be used for our ML integrations as well. Not sure, whether we need to upgrade to Enterprise that time, but then also it will be helpful.

2. Full control on ETL using python script. Very easy to manage.

CONS,

1.  Local Development set up is bit tricky, there are few issue Windows Dev Machines , which throws errors with docker compose. But I found the fixes for it.
2. On OCP, There is no built in security with Keycloack, to manage access to Admin WebApps. Advice from their team/group is to N/W level security on the endpoint. https://github.com/PrefectHQ/prefect/discussions/3068. But we have teams with in BC GOV already using it.  we can follow same path. 


Next 
----------------

- Need to set up Prefect on OCP and see whether any issues with that. 
- Try out accessing POSTGRES DB cross OCP namespace/project. 
- Try out Authentication integration, if too complicated set up N/W security to  limit its access.[https://app.zenhub.com/files/358004325/ded73ec1-49d5-477c-9e81-f50e8c7f8f3c/download](https://app.zenhub.com/files/358004325/ded73ec1-49d5-477c-9e81-f50e8c7f8f3c/download)
