### ISSUE TITLE
Request ID appears on the browser tab

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2318]
* As an IAO analyst or ministry coordinator
* I want the request ID to show on the browser tab (currently say foi-flow)
* so that I know what request I am have displayed in that tab

**Assumptions & Scope**	
What are the assumptions for this story?

Users have noted that they often have multiple requests views in different browser tabs at one time. They have asked to see the request ID number on the tab so they no which request is in each tab (AXIS has this).

Currently all tabs just say 'foi.flow'

What is IN scope?

Titles of browser tabs (Edge, Chrome, etc.).

What is NOT in scope?

Changes to the actual FLOW views.

**Acceptance Criteria**	

**Scenario 1: On a FOI request view**
* GIVEN a user has a browser window for a request displayed
* WHEN the user is on a request view, comment log, attachment log,  or CFR form
* THEN 'MIN-YEAR-XXXXX (i.e. the request ID) will be displayed as the title of the browser tab with the BC logo

**Scenario 2: On queue**
* GIVEN a user has a browser window for the queue 
* WHEN the user is on the queue
* THEN 'FOI Request Queue' will be displayed as the title of the browser tab with the BC logo

**Scenario 3: On Advanced Search**
* GIVEN a user has a browser window for Advanced Search
* WHEN the user is on Advanced Search
* THEN 'FOI Advanced Search' will be displayed as the title of the browser tab with the BC logo

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by abin-aot** [comment]
@lmullane  - What need to  be shown for Unopened Request? Raw request ID?

**Comment by KaraBeach** [comment]
All ACs working as they should - Thank you @nkan-aot
