### ISSUE TITLE
View attachment in browser

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2319]
* As an IAO analyst or ministry coordinator
* I want to be able to view an attachment in a browser tab
* so that I can review the attachment without needing to download it first

**Assumptions & Scope**	
What are the assumptions for this story?
VIew should include common document types like images, PDFs, and Microsoft office file types (eg: word, excel)

Email files will not be able to be opened in the browser view per discussion at refinement due to technical limitations.

Users have asked to be able to view an attachment without downloading it.

What is IN scope?

Viewing attachments.

What is NOT in scope?

Changes to the ellipse dropdown.

**Acceptance Criteria**	

**Scenario 1: View on dropdown**
* GIVEN the user is on the Attachment log 
* WHEN the user clicks the ellipsis to the right of an attachment
* AND the file is NOT an email file (.eml, .msg)
* THEN the dropdown will open
* AND 'View' will now be an option

**Scenario 2: Click 'View'**
* GIVEN the user has opened an Attachment dropdown
* WHEN the user clicks 'View'
* THEN the a display of the attachment will open in a new browser tab

**Scenario 3: Click document name**
* GIVEN the user is on the Attachment log 
* WHEN the user clicks  on the title of the attachment
* THEN the a display of the attachment will open in a new browser tab

**Scenario 4: Email files**
* GIVEN a user is on the attachment log
* AND the user has clicked on an email file
* THEN the file will download, and not open in browser like with other filetypes

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Update AC to include exception handling for email files (can't really open them in browser)

**Comment by m-prodan** [comment]
AC updated to include email exception. I thought it might be more user friendly if clicking on email files would auto-download instead of open in new browser tab... thoughts @nkan-aot ?

Is it enough to just update scenario 1 that the ellipses will not have the option to view for msg and eml files?

**Comment by abin-aot** [comment]
@m-prodan , @KaraBeach  - this US is ready for QA

**Comment by KaraBeach** [comment]
Hey- @abin-aot @m-prodan  
**Scenarios 1-3** passed
**Scenario 4** - I think we would to also be able to click on the file title to download in addition to the user clicking the ellipsis to the right of the attachment to download.

**Comment by abin-aot** [comment]
@KaraBeach : Could you please try now? a fix is released

**Comment by m-prodan** [comment]
Completed QA on behalf of Kara - the email scenario is now working as accepted. All scenarios pass - thank you @abin-aot
