### ISSUE TITLE
Queue search breadcrumbs

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2320]
* As a ministry coordinator or IAO analyst
* I want breadcrumbs when doing a search on the queue
* so that I can navigate back to my original search parameters 

**Assumptions & Scope**	
What are the assumptions for this story?

Users have asked for to do a search on their queue and easily navigate back to their search results without re-entering the search criteria, column sort, or navigate to a certain page. 

Will use material UI component.

What is IN scope?
Breadcrumbs for advanced search

What is NOT in scope?
Breadcrumbs for Advanced Search #1884

**Acceptance Criteria**	

**Scenario 1: Search on queue**
* GIVEN a ministry coordinator or IAO analyst is on a queue (My requests, My Team's Requests, Watching Requests)
* AND search keywords have been entered in the search bar
* AND/OR column sorts (asc, desc) have been activated
* AND search results are listed
* WHEN the user clicks on the a request listed
* THEN the request view will open
* AND a 2 layer breadcrumb will show with Queue Search and the Request Number for the request the user is currently on

**Scenario 2: Click Queue Search breadcrumb**
* GIVEN the user is on a request found as part of an queue search
* WHEN the user clicks the Queue Search breadcrumb
* THEN the user will be returned to the queue search view (My requests, My Team's Requests, or Watching Requests)
* AND their search results will be listed
* AND any column sort toggles that were previously active shall remain active
* AND the their search parameters will still be selected
* AND the pagination will be maintained

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Update AC to include scenario for column sort and pagination

**Comment by m-prodan** [comment]
AC Updated to include column sort and pagination requirements. Folded into existing AC

**Comment by m-prodan** [comment]
@nkan-aot - it seems to be working as expected, but I am noticing what seems like a major bug that seems to have come with it.... When I follow the breadcrumb back, I can't make any further changes to the search criteria. In fact - it seems to be extending even when I don't use breadcrumbs. For example, I did a search, and realized I spelled the name wrong... but I couldn't correct it - it locked my filter almost immediately

**Comment by m-prodan** [comment]
Just realized - it's when I sort a column, then it locks the search filter. That seems to be what's causing the issue

**Comment by m-prodan** [comment]
Nice work fixing those issues that came out of it @nkan-aot - scenarios passed, closing ticket
