### ISSUE TITLE
Fee Estimate Email Generation

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2322]
* As an applicant
* I want to receive my fee estimate information electronically
* so that I can easily pay for my fee

**Assumptions & Scope**	
* This story is the email that will be automatically delivered to the applicant upon putting a request on hold, WHEN the applicant has an email address included with their request. 
* For the email mailbox - for initial development purposes, we will use: dvptgmarshal@gmail.com 
* When service accounts and new mailboxes are set up, test account will be changed to test_foi.requests@gov.bc.ca, with a separate story to address this.
* When we go to production, we will use a new mailbox, with a separate story to address this.
* This will be a basic version of the email sent to the applicant - and will include the file uploaded as part of the on hold state change.

What is IN scope?
The email that will be generated and sent to the applicant

What is NOT in scope?
The email service that will be used and set up
The actual payment of the fee itself
Edits or additions to the email sent

**Acceptance Criteria**	

**Scenario 1: Email Details**
* GIVEN a request has been put on hold
* WHEN the email is generated
* THEN the email will be sent to the applicant's email address on file
* AND the email will be sent from dvptgmarshal@gmail.com

**Scenario 2: Attachments to email**
* GIVEN a request has been put on hold due to fees
* WHEN the email is generated
* THEN the document uploaded during the change of state to on hold will be attached to the email to the applicant.

**Scenario 3: Content of Email**
* GIVEN a request has been put on hold
* WHEN the email is generated
* THEN the contents of the message will include a hyperlink to pay the fee estimate

**Scenario 4: Send Email**
* GIVEN a request has been put on hold
* WHEN the email is generated
* AND the attachments have been added
* AND the content has been generated
* THEN the email will send to the applicant on file.
* AND the email will be sent from dvptgmarshal@gmail.com

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Keeping this one down on the list and marked as incomplete AC - will need some more research/unpacking into what the letter should entail before we move ahead on this one.

**Comment by m-prodan** [comment]
Story updated per the updated flow of having a letter to upload instead of auto-generating the letter.

Thinking we will need a design @JHarrietha-AOT - since it is just an email, I could offer to write up a mock-one instead? Thoughts? 

cc: @lmullane @KaraBeach @arielleandrews

**Comment by m-prodan** [comment]
Basic content of email:

"Dear <APPLICANT NAME>,

Please see the attached regarding your FOI Request.

If you would like to pay your estimate online, please click on this link.

Thank you,

<Contact Info>

Will create a separate design ticket for templating considerations

**Comment by m-prodan** [comment]
Per discussion at refinement, need a word doc to act as a template for the email. Include tags like contact info/other to be pulled into the email itself

**Comment by m-prodan** [comment]
@arielleandrews - will work with @JHarrietha-AOT on this

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews I am going to remove the design link from this ticket to avoid confusion with the devs. @aparna-aot I will tag you here with the word doc

**Comment by m-prodan** [comment]
@aparna-aot @JHarrietha-AOT - email template in word document here:
https://bcgov.sharepoint.com/:w:/r/teams/03521/Shared%20Documents/General/Design%20Assets%20for%20Web%20App/Letters%20and%20Templates/Fees/Draft%20Email%20-%20Online%20Pay.docx?d=w0ea79f549c554d678d12512ac09363f3&csf=1&web=1&e=EObum3 

cc: @lmullane @KaraBeach @arielleandrews

**Comment by aparna-aot** [comment]
@m-prodan Just confirming, if this email doesn't have a footer similar to FOI Request Confirmation Email.
![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/ff8e149f-e981-476b-9b2e-ca01067749bc)

**Comment by m-prodan** [comment]
Good catch - we do have something similar with our email templates, but not the same as that one. I have updated it. The letter attached will have most of that contact information in it anyways, but is good to have a consistent footer

**Comment by m-prodan** [comment]
updated story to include test email details, and assumptions around new mailbox needing to be ordered.

cc: @lmullane @KaraBeach @arielleandrews

**Comment by arielleandrews** [comment]
Testing completed, works as expected. Some notes for future changes/enhancements:

- Currently all attachments to the email have "fee.pdf" as the filename. Need tech debt ticket to have this pull actual filename of the file
- Need to allow for upload of two files (fee letter and invoice) during state change transition from Fee Estimate to On Hold, and attach both files to email to applicant
- Update design of email template to incorporate BC government logo
