### ISSUE TITLE
Pay Fee Online - Link Activation

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2323]
* As an applicant
* I want to be able to pay my fee online
* so that I can do so at my own convenience

**Assumptions & Scope**	
This follows user story #2322 which provides the initial notification to the applicant, and gives them the link to pay their fee online

This ticket includes all of the required integrations with formflow.

What is IN scope?
Initial landing page and options for the applicant when they choose to pay the fee online
Re-sending a new link, includes request history sysgen comment and notifications

What is NOT in scope?
Actual payment of fees and automated notifications and WF changes will be covered in seperate stories. 

**Acceptance Criteria**	

**Scenario 1: Pay Fee Online**
* GIVEN an applicant has received notification of a fee estimate
* WHEN they click Pay Fee Online
* THEN they will be taken to this page via their default browser (https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/921685067)

**Scenario 2: Pay Online**
* GIVEN an applicant is on the first page of the online pay process
* WHEN they click "Pay Online"
* THEN they will be taken to the pay page per the following design:
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/921685070

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Link activation story for paying fee estimate after clicking link in the letter. Note scenario 4 which I added - missing from designs. We'll need to think of a workflow for this, but figured I would start with the obvious (notification and comment posting)

cc: @lmullane @JHarrietha-AOT @KaraBeach

**Comment by lmullane** [comment]
@m-prodan , for scenario 3 when the applicant clicks 'Re-send Link' is another email sent to the applicant with a new link?

For some reason I can't view the designs in InVision.

**Comment by m-prodan** [comment]
Per refinement - decision made to remove "re-send link" function

**Comment by m-prodan** [comment]
Per discussion at standup - on the pay page, agreed to drop Ministry name, and just include the request ID, since the letter will be providing the infor to the applicants that we will be attaching to the email.

@JHarrietha-AOT - when you have a quick moment, you may wish to update the design.

**Comment by arielleandrews** [comment]
@divyav-aot and @sumathi-thirumani-aot There is a small bug with this one: I have noticed that sometimes when I click the Pay Online link from the email for the first time, I receive the below error message. When I close the tab and click the link again, it works as expected. 
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/0d93f383-8049-48c9-9762-6f62d582f7c0)

**Comment by JHarrietha-AOT** [comment]
@arielleandrews I haven't done any testing in a while, could you let me know where this is? Can I access it in test or is this is dev marshal or test marshal?

**Comment by JHarrietha-AOT** [comment]
@arielleandrews this passed UX Assurance, are you ready to close the ticket for QA? And make the separate bug ticket you listed above

**Comment by arielleandrews** [comment]
Testing completed, AC passed. Bug ticket #2502 created for intermittent error messages that occur when opening the link for the first time. cc @divyav-aot @sumathi-thirumani-aot @aparna-aot for your awareness.
