### ISSUE TITLE
Pay Fee Estimate

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2324]
* As an applicant
* I want to be able to pay the full fee, or deposit required
* so that my request can continue processing

**Assumptions & Scope**	
This follows the payment path flow, and comes after user story #2323

What is IN scope?
Decision tree and logic around fee estimates and payment options

What is NOT in scope?
Processing of payments through payBC covered under seperate user stories

**Acceptance Criteria**	

**Scenario 1: Payment Options - Fee Estimate under 200 dollars**
* GIVEN an applicant is paying a fee online
* WHEN the total fee is LESS than 200 dollars
* THEN the applicant will only have the option to pay full fee estimate
* AND the link to pay deposit will not be visible
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/921685070

**Scenario 2: Payment Options - Fee Estimate 200 dollars or more**
* GIVEN an applicant is paying a fee online
* WHEN the total fee is 200 dollars or more
* THEN both buttons to pay the full, or deposit, will be active
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/921685070

**Scenario 3: Activate Pay Full Fee Estimate**
* GIVEN an applicant is paying a fee online
* WHEN they click 'Pay Full Fee Estimate'
* THEN they will be taken to a final confirmation page showing the full fee estimate due
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/921685071

**Scenario 4: Activate Pay Deposit**
* GIVEN an applicant is paying a fee online
* AND the total of the fee is 200 dollars or more
* WHEN they click 'Pay Deposit'
* THEN they will be taken to a final confirmation page showing the deposit due
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/921685131

**Scenario 5: Process Payment**
* GIVEN an applicant is paying a fee online
* WHEN they are on the final confirmation page
* AND they click on 'Process Payment'
* THEN they will be directed to PayBC to process the fee amount required
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/921685072

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@JHarrietha-AOT  - As I was writing this up, I was thinking of some minor design updates.

Can we include text that says "You can only pay a deposit when your fee is 200 dollars or more"

Can we also update the buttons - Instead of Pay Full Estimate Fee - it would ready better as "Pay Full Fee Estimate"

**Comment by m-prodan** [comment]
Last part of chain before payBC step.

cc: @lmullane @KaraBeach

**Comment by lmullane** [comment]
@m-prodan, instead of greying it out, suggest the applicant only see the deposit option if the fee is over $200.

That way they don't fee there are missing out on something. Thoughts?

cc @JHarrietha-AOT

**Comment by m-prodan** [comment]
Decision per refinement and reflected with updated AC - deposit option will not be visible, instead of greyed out, for scenario 1

**Comment by arielleandrews** [comment]
@divyav-aot or @sumathi-thirumani-aot I am wondering if it would be possible that when the fee estimate is under $200 if the applicant skips this page entirely: https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/921685070
So they would go from the first landing page to the proceed to payment page. I can write this up as a separate ticket if so
cc @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
@arielleandrews this passed UX Assurance, are you ready to close the ticket for QA? And make the separate bug ticket you listed above

**Comment by arielleandrews** [comment]
QA completed, all AC passed during testing. User story #2500 created as an enhancement to this ticket.
