### ISSUE TITLE
Confirmation of Successful Pay and Failure and email of payment and receipt

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2325]
* As an applicant
* I want a confirmation email that my payment has been successful
* so that I know the fee has been paid

**Assumptions & Scope**	
What are the assumptions for this story?

Email will be saved in object storage.
Per discussion at stand up on July 29th - receipts will be handled in a separate story now - AC updated.
What is IN scope?
Sending a confirmation email to the applicant that the fee has been received

**Acceptance Criteria**	

**Scenario 1: Payment Successful Page**
* GIVEN the user is on the PayBC Credit Card Screen
* AND the user enters a valid CC number, Expiry, and CVD
* WHEN the user clicks 'Pay'
* THEN they will be taken to the payment successful page, which will include the transaction ID
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922730571

**Scenario 2: Cancel Payment**
* GIVEN the user is on the PayBC credit card screen
* WHEN the user clicks the 'Cancel' button
* THEN the user will be redirected back to the 'Payment failed' page
* AND a failed payment message will be displayed
* AND the button will be 'Retry Payment'

**Scenario 3: Invalid credit card CVD**
* GIVEN the user is on the PayBC credit card screen
* AND the user enters an valid credit card number
* AND the user enters an invalid CVD
* WHEN the user clicks the 'Pay' button
* THEN the user will be redirected back to the 'Payment failed' page
* AND a failed payment message will be displayed
* AND the button will be 'Retry Payment'

*Scenario 4: Declined CC**
* GIVEN the user is on the PayBC credit card screen
* AND the user enters a declined credit card number
* WHEN the user clicks the 'Pay' button
* THEN the user will be redirected back to the 'Payment failed' page
* AND a failed payment message will be displayed
* AND the button will be 'Retry Payment'

*Scenario 5: Retry Payment**
* GIVEN the user is on the 'Payment failed' page
* WHEN the user clicks the 'Retry Payment' button
* THEN the user will be redirected to the PayBC credit card screen
AND the application fee amount will be pre-filled an uneditable

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
There may be quite a bit in this one. there is more certainty with this letter, so I think we can consider moving ahead, but we may want to consider some of the content and how it appears.

cc: @lmullane @KaraBeach

**Comment by m-prodan** [comment]
Adding dependency with 2326 - auto move off of hold will recalculate new LDD, which will inform email sent to applicant

**Comment by lmullane** [comment]
For this story let's add ACs for the exceptions (i.e., failed or cancelled payments).

I can add based on the pattern we use for Application Fees.

**Comment by lmullane** [comment]
Added the payment exception ACs. 

Should the user be able to download the receipt from the Payment Successful page as they can do for application fees?

**Comment by m-prodan** [comment]
Decision: we won't include downloading a receipt - it will just be covered via email

**Comment by lmullane** [comment]
As discussed, even if payment fails there is no restriction on the IAO analyst changing the state of the request.

For example, possible the analyst pays by phone, so the analyst will need to change the state back to CFR.

**Comment by KaraBeach** [comment]
Remove Scenario 2 and put in own story for next week

**Comment by divyav-aot** [comment]
Scenario 2 and 3 are not ready yet

**Comment by m-prodan** [comment]
@divyav-aot - I've created #2543 per our discussion at stand up, to separate out the receipt from this and the other story (2327) - updating story to remove the receipt scenarios

**Comment by KaraBeach** [comment]
@m-prodan @divyav-aot  AC's all function as they should. 

Question: I didn't receive an email with receipt as the modal states after the payment was successful. It is not written in the AC, but should I have?

**Comment by divyav-aot** [comment]
@KaraBeach - it will be covered in #2543

**Comment by KaraBeach** [comment]
@divyav-aot -perfect thanks!
