### ISSUE TITLE
Fee Estimate - Successful Payment - State Change

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2326]
* As an IAO analyst and Ministry coordinator
* I want to know when a fee has been paid
* so that I know to resume records gathering

**Assumptions & Scope**	
This story reflects the need to notify those assigned to the request that the fee has been paid. Assumption is LDD calculation logic from on hold will not change in this story, and the new LDD will be updated when a request is taken off hold. 

What is IN scope?
Automated state changes
In-App notifications and comments

**Acceptance Criteria**	

**Scenario 1: Payment Successful - State Change**
* GIVEN an applicant has successfully paid a processing fee on payBC
* WHEN the payment is successful
* THEN the request state will automatically update to 'Call for Records'

**Scenario 2: Notification - Fee Payment**
* GIVEN a processing fee has been paid
* WHEN the state automatically changes to CFR
* THEN all assigned users will received a notification saying "Applicant has paid required fee, resume gathering. New LDD is <LEGISLATED DUE DATE>

**Scenario 3: System Generated comment**
* GIVEN a processing fee has been paid
* WHEN the state automatically changes to CFR
* THEN the application will post a request history comment:  "Applicant has paid required fee. New LDD is <LEGISLATED DUE DATE>"

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
@divyav-aot and @nkan-aot when I tested this on Friday the notification text was as noted in the AC, but this morning the text is different and is the normal state change text. The same is happening with the system generated comment. See snips below:
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/1d04cf4b-67fb-4a4d-b784-f1db8a6d9e5f)
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/b713ce93-fd0a-4283-8602-e8efc9e14196)
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/452b43d4-ce68-4f9d-a733-bdb2f168acad)

**Comment by divyav-aot** [comment]
@arielleandrews - we are looking into this issue.

**Comment by arielleandrews** [comment]
One other item to note: when a request is taken off hold, the Start Date on the request details page is updating to the date it was moved from On Hold to CFR. I think we need a different way to display this information, otherwise it may confuse users. Thoughts on capturing On Hold and Off Hold dates as separate fields @m-prodan @KaraBeach @JHarrietha-AOT @lmullane? I find myself wanting to easily see the original due date as well

**Comment by sumathi-thirumani-aot** [comment]
@arielleandrews The system is working as designed.
We haven't changed the format of state transition comment and notification. The dynamic value passed is instead of <FOI Staff name>, the static word "**System**" is used.

**Comment by arielleandrews** [comment]
QA completed, all scenarios have now passed. User stories #2678 and #2685 added to backlog to address balance calculation and adding fields for Original Due Date and Off Hold Date. Nice work @sumathi-thirumani-aot @divyav-aot and @nkan-aot!
