### ISSUE TITLE
Fee Estimate - Correspondence Saved to Attachment Log

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2327]
* As an IAO user
* I want to access the correspondence sent to the applicant
* so that I can reference it as needed

**Assumptions & Scope**	
This story requires the need for the emails sent to the applicant to be retained and accessible by IAO. This is required should there ever be a complaint or other issue raised by the applicant.
See comment for EML vs PDF decision

What is IN scope?
Adding these records to the attachment log
limiting permissions of accessibility

**Acceptance Criteria**	

**Scenario 1: Fee Estimate Notification Sent**
* GIVEN an applicant has been sent notice of a fee estimate
* WHEN this job has been done successfully
* THEN the email will be saved to the attachment log as a PDF
* AND will be titled "Fees - Estimate Sent"

**Scenario 2: Attachment Options**
* GIVEN a fee estimate letter, or confirmation email sent to the applicant has been saved to the attachment log
* WHEN an IAO user activates the ellipses
* THEN they will only see the options to Rename & Download

**Scenario 3: Attachment Permissions**
* GIVEN a fee estimate letter or confirmation email sent to the applicant has been saved to the attachment log
* WHEN a Ministry user navigates to it
* THEN the ellipses will be grayed out
* AND they will be unable to interact with the file

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Update AC - need to save email as PDF file.
Need story for success/fail notification - if success, PDF saved to file, if fail - no PDF saved.

**Comment by m-prodan** [comment]
Also need to include receipt/conf email

**Comment by m-prodan** [comment]
AC updated to include the above scenarios

**Comment by arielleandrews** [comment]
@JHarrietha-AOT and @m-prodan please add links to templates for fee receipt and successful payment email

**Comment by divyav-aot** [comment]
Scenario 2 and 3 are not ready yet

**Comment by m-prodan** [comment]
@divyav-aot - I've created #2543 per our discussion at stand up, to separate out the receipt from this and the other story (2325) - updating story to remove the receipt scenarios

**Comment by KaraBeach** [comment]
@m-prodan @divyav-aot - ACs function as they should. thank you!
