### ISSUE TITLE
Set up FormsFlow.ai  (Forms.io, FF API, DB) on existing OCP - Dev, Test

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2333]
Title of ticket: 

#### Description
The purpose of this task is to set up FormsFlow.ai components such as FormsFlow Web, Forms.ai + MongoDB, FF API, FF PostgresDB backend. Assuming we can use existing Patroni DB for BE. The idea is to utilize this set up for Applicant Fee Payment UX and there after migration of existing FOI Request Submission Functionalities

#### Dependencies
Are there any dependencies?

DOD - Line Items
====================
- [x] Setup Mongo cluster
- [x] Build secret for formsflow.ai
- [x] Build & Deploy formio i.e. forms-flow-forms
- [x] Setup KC for forms-flow-ai
- [x] Build & Deploy forms-flow-ai
- [x] Setup forms-flow-api

#### DOD
- [x] OC Build, Deploy Templates for FormsFlow Web , Forms.IO, FF API
- [x] Integration with KC, KC client set ups if required . Roles Set up,  auth for Designers etc.
- [x] BUILD and Deploy to DEV, TEST 
- [x]  Integration with existing Camunda BPM Instances
- [x] Onboard DEVs and confirm the built in functionalities

**Comment by sumathi-thirumani-aot** [comment]
Running up cluster of 3 for MongoDB raises issue:
exception: login failed
2022-06-20T21:47:29.585+0000 I NETWORK  [conn3] end connection 10.97.136.70:51562 (0 connections now open)
2022-06-20T21:47:29.585+0000 I NETWORK  [conn4] end connection 10.97.136.70:51572 (1 connection now open)
=> [Mon Jun 20 21:47:29] ERROR: couldn't add host to replica set!
