### ISSUE TITLE
Request View page - Edited fields flickers previous value once after saving

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#2334]
Title of ticket: 
Request View page - Edited fields flickers previous data once after saving

#### Description
On Request View page, if any field is edited and saved, the previous value of that field will flickers quickly and then displays the updated value.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Fix the issue
- [x] Testing

Attachment: 
Tested on : https://test.foirequests.gov.bc.ca/
https://images.zenhubusercontent.com/358004325/517cf7d9-ba09-45ec-a88e-eb3cc83af8e7/request_flicker.mp4

**Comment by KaraBeach** [comment]
@aparna-aot- bug has been fixed, changes happens at the same time as toast appears.
