### ISSUE TITLE
Update FOI Flow's  FE folder name in GitHub and change references 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2335]
Title of ticket: 

#### Description
The idea of this task is to rename the GitHub Folder name for apps\forms-flow-ai\ **forms-flow-web**    (existing) , to make it specific to FOI FLOW. This is because FormsFlow implementation is coming for fee payment  experience and existing folder name obsolete, since we updated that for FOI FLOW

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Folder name change - apps\forms-flow-ai\ forms-flow-web on Repo
- [x]  Update the docker/docker-compose , * .bat for local build 
- [x]  Update Path references on CI\CD - Git hub
- [x]  Confirm the build , deploy process
- [x] Smoke Testing

**Comment by lmullane** [comment]
@acoard-aot, to review.
