### ISSUE TITLE
UX Layout customization - FormsFlow Web for Application Experience

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2336]
Title of ticket: 

#### Description
The purpose of this task is to customize the UX layout on FormsFlow web as per applicant experience

#### Dependencies
Are there any dependencies?

#### DOD
- [x]  Header , Footer as BC GOV style, Wireframe
- [x]  Updates to FormsFlow Web - CSS, Images/Logos etc.
- [x]  UX - Fluidity check
- [x] Fix review comments
- [x] Update unit tests
- [x]  deployment to dev
- [ ] deployment to test

**Comment by lmullane** [comment]
@sumathi-thirumani-aot, to reestimate.

**Comment by lmullane** [comment]
No business QA required.
