### ISSUE TITLE
Revision to Divisional Tracking Stages

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2341]
Title of ticket: Revision to Divisional Tracking Stages

#### Description
Feedback from users - they would like some changes made to the names of certain stages to increase clairty.

This will apply across all Ministry groups for divisional tracking

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Updated Divisional Stage: [Awaiting Fees] to [Awaiting Fee Estimate]
- [x] Update Divisional Stage: [Fees Received] to [Fee Estimate Received]

**Comment by arielleandrews** [comment]
QA completed, text is updated in divisional stages for all pilot ministries.
