### ISSUE TITLE
Separating Feature enhancements, bug fixes from CFR Form code base - GIT DEV Branch 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2343]
Title of ticket: 

#### Description
The purpose of this ticket is to separate out feature enhancements, bug fixes from CFR Form code base. Then bundle the FOI FLOW dev branch for next Prod release. Items considered for next production release. 

#2279
#2334
#2281
#2267
#2235
#2318

From current DEV branch we need to pull PRs related to CFR Form. and move all branch new features to marshal branches/environments(Dev, TEST)

#### Dependencies
Are there any dependencies?

PR# to pull out related to CFR Form from DEV

2346
2332
2321
2316
2314
2302
2286
2277

#### DOD
- [x] Isolate **CFR Form** related code base to dev-marshal branch
- [x] Implement CI\CD to dev-marshal to push to dev-marshal image update on OCP . Apply same things to TEST-MARSHAL. test marshal branch with test marshal endpoint
- [x]  Once above steps are done and perfected, remove PRs related to CFR form from DEV branch
- [x]  Test and confirm the functionalities on DEV. Also, make sure DEV functionalities are TEST, PROD alike

**Comment by lmullane** [comment]
@sumathi-thirumani-aot, to cross reference to see if there is duplicate work with #2335
