### ISSUE TITLE
Merge Ministry Dashboards

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#2379]
Previously ministry dashboards were copies of IAO dashboards except with permissions limited to the specific ministries in that group. Based on discussion at standup it would be more useful if all the filters in analyst workload, received, and performance dashboard were combined into one dashboard. This will allow user to drill down from ministry to division to individual analyst. Because dashboards are dependent on new ETL, currently we will only combine the dashboards using existing data from AXIS just to show what it would look like. Division level filtering will be added after ETL is finished

#### Description
Related to #2297

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Analyst Received and Performance Dashboard merged, with the following graphs
- [x] Average Days by Request States, 
- [x] Number of Processing Pages by Ministry, 
- [x] No Records Response by Ministry
and filters 
- [x] End FYr, End FQtr, By Month, By Week, 
- [x] Request Type (General, Personal), 
- [x] Request Status (Active, Overdue, Closed), 
- [x] ~Ministry Assigned To (i.e., coordinators)~ _needs additional ETL_

**Comment by m-prodan** [comment]
@nkan-aot - just a few things I'm noticing so far while QA'ing:
1) I'm seeing duplicate requests again, which is putting the active numbers off, may be similar to what we saw with the regular dashboards
2) I'm also seeing the divisions for the combined econ dasbhoards are also include divisions for Education - can we seperate these out to only show the divisions for the ECON ministries? Same with analysts - it is showing all Ministry analysts, including education - should just be economy sector group. 
3) Possible to have the start FY and END fy defaul to 22/23 - or will that throw the graphs off? 

We can catch up on Monday - will continue going over everything, but wanted to flag this now

**Comment by nkan-aot** [comment]
hey @m-prodan i've fixed 2 and 3, you should only be seeing analysts and divisions from econ now. for 3, i've changed it but now graphs will be empty by default, since we are using test data there is no data in econ for fy 22/23. We'll definitely make it default for prod but let me know if you want it removed in test so it's easier to test. 

As for number 1, the problem was already there before the new dashboard, I compared the counts for the new and old dashboard and they are the same. However I confirmed issue is not happening in prod and it is not the same cause as the duplicates from before. It may just be because it is test data so there are some anomalies but I am looking into it further.

**Comment by m-prodan** [comment]
Looks great @nkan-aot - I think the Ministry will get a lot of utility out of this.

I am thinking we might need to include a graph for total received... BUT - it's not in the DOD for this ticket, and so I think its fair to close it. I'll set up a meeting with economy sector to go over this with them. 

cc @lmullane @KaraBeach @arielleandrews

**Comment by lmullane** [comment]
@m-prodan, @nkan-aot, for the release notes can I confirm that the dashboards do NOT include Ministry Assigned to?

**Comment by nkan-aot** [comment]
sorry the dod above was from before abin completed his etl for foi flow. Currently any requests that have been synced from axis to flow should have a ministry assigned to. Historical records will not have ministry assigned to
