### ISSUE TITLE
Template for Email for Online Pay

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2385]
Title of ticket: Template for Email for Online Pay

#### Description
Per ticket #2322 - need a general template for the email to be generated. 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Template designed
- [ ] Reviewed/Approved by Business/PO

**Comment by m-prodan** [comment]
Content of email:
"Dear [APPLICANT NAME],

Please see the attached regarding your FOI Request.

If you would like to pay your estimate online, please click on this link.

Thank you,

[Contact Info]

**Comment by lmullane** [comment]
Duplicate.
