### ISSUE TITLE
IAO adds preparing hours to CFR form

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2397]
* As an IAO analyst
* I want to be able to add estimated and actual hours for IAO to prepare records
* so that the IAO preparation hours can be added to the fee estimate

**Assumptions & Scope**	
What are the assumptions for this story?

At times IAO adds hours for the prep of documents time to the fee estimate charged applicants.

Only IAO analyst can edit these fields, but ministry coordinators can view them.

The hours will automatically be added to the Total Amount Due

What is IN scope?
IAO adding and saving hours.

What is NOT in scope?
Ministry adding hours.

**Acceptance Criteria**	

**Scenario 1: IAO analyst edit estimated hours**
* GIVEN a request is in the 'Fee Estimate' state
* WHEN the analyst is on the CFR form
* AND the CFR Form status is 'In Review'
* THEN under 'Preparing' the analyst will see fields for 'Estimated Hours IAO, Estimated Hours MIN, Actual Hours IAO, Actual Hours MIN'
* AND the field for 'Estimated Hours IAO' will be editable
* AND the fields for 'Actual Hours IAO',  Estimated Hours MIN' and 'Actual Hours MIN' will NOT be editable
 https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922730563

**Scenario 2: IAO analyst edit actual hours**
* GIVEN a request is in the 'Deduplication' or 'Records Review' state
* WHEN the analyst is on the CFR form
* THEN under 'Preparing' the analyst will see fields for 'Estimated Hours IAO, Estimated Hours MIN, Actual Hours IAO, Actual Hours MIN'
* AND the field for 'Actual Hours IAO' will be editable
* AND the fields for 'Estimated Hours IAO',  Estimated Hours MIN' and 'Actual Hours MIN' will NOT be editable
 https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922730563

**Scenario 3: Add estimated hours**
* GIVEN a request is in the 'Fee Estimate' state
* AND the IAO analyst is on the CFR form
* WHEN the analyst adds hours in the field for 'Estimated Hours IAO' 
* THEN the hours will be calculated as part of the 'Total Amount Due'
* AND the 'Save' button will turn blue and active

**Scenario 3: Add actual hours**
* GIVEN a request is in the 'Deduplication' or 'Records Review' state
* AND the IAO analyst is on the CFR form
* WHEN the analyst adds hours in the field for 'Actual Hours IAO' 
* THEN the hours will be calculated as part of the 'Total Amount Due'
* AND the 'Save' button will turn blue and active

**Scenario 5: Save hours**
* GIVEN an IAO analyst has added hours in the field for 'Estimated Hours IAO' or 'Actual Hours IAO
* WHEN the analyst clicks the 'Save' button 
* THEN the change will saved

**Scenario 6: Navigate away without saving hours**
* GIVEN an IAO analyst has added hours in the field for 'Estimated Hours IAO' or 'Actual Hours IAO
* WHEN the analyst clicks to navigate away from the CFR Form 
* THEN a modal will open warning changes will lost if you leave

**Scenario 7: Ministry Coordinator on CFR Form**
* GIVEN a ministry coordinator is logged in
* WHEN the ministry coordinator is on the CFR form
* THEN under 'Preparing' the ministry coordinator will see fields for 'Estimated Hours IAO, Estimated Hours MIN, Actual Hours IAO, Actual Hours MIN'
* AND the fields for 'Estimated Hours IAO' and 'Actual Hours IAO' will NOT be editable

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan , @arielleandrews, for your review. 

Do we need fields to show what the Total Estimated Amount Due was versus the Total Actual Amount Due? 

cc @JHarrietha-AOT

**Comment by lmullane** [comment]
Looking back would be valuable me thinks as well.

Thanks for the update to the AC.

@JHarrietha-AOT, could we add some design changes to be able to track the Total Estimated vs the Total Actuals. It could work like this:

GIVEN a request is in Fee Estimate
WHEN esimated hours are added to the CFR Form
THEN the amounts will summed up and appear in the Total Estimated and the Total Amount Due
AND the Total Estimated will match the Total Amount Due

GIVEN a request has had a paid esitmated fee
WHEN actual hours are added to the CFR Form
THEN the amounts will summed up and appear in the Total Actuals
AND the Total Amount Due will be equal to Total Actual minus Total Estimated (minus for a surplus for  refund, or amount still owing if the actuals exceed the estimated)

**Comment by JHarrietha-AOT** [comment]
@lmullane I have updated the designs - based off of the conversation this morning I have removed the "Balance Owning" - as this will just be show as a positive or negative amount based of what has been paid in the total.

https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922730564

Let me know if you have any questions or changes

**Comment by lmullane** [comment]
@sumathi-thirumani-aot, as discussed, preference would be for 'Actual Hours Ministry' and 'Estimated Hours Ministry' but if spacing does not work will go with MIN instead of ministry.

cc @JHarrietha-AOT

**Comment by KaraBeach** [comment]
ACs function as they should! Great Work
