### ISSUE TITLE
UX Design - Online Fees Templates

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#2430]
Title of ticket: UX Design - Online Fees Templates

#### Description
Need to dedicate time to create the updated fee emails/letter based off of the new processes.

Email will include a primary button of "Pay Online" Secondary "Reply"
Reply will allow user to open new modal with their email software on thier computer with the correct email they would need to be replying to. Goal is to help midigate the potenial of users hitting reply on the NO REPLY email.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] First draft of new email & letting for Processing Fees Estimate

**Comment by JHarrietha-AOT** [comment]
@m-prodan @KaraBeach @nkan-aot 

Have a look when you have a chance and feel free to make any additional changes Matt & Kara

https://bcgov.sharepoint.com/:w:/t/03521/EXjjpZL6tP9JtWUcDYI00-ABTPtLAVYoKfF2MID8TB1M6w?e=PaPUIQ

**Comment by nkan-aot** [comment]
Will this still be sent as the body of an email, like the design here? https://jacklyn808742.invisionapp.com/console/Applicant---Fees-cl4289pe800q5017zhr5hcbg4/cl4795m0l018r012s13spgqfm/play 
or is it an attachment
