### ISSUE TITLE
Filtering Comments

### ISSUE THREAD

**Issue by KaraBeach** [bcgov/foi-flow#2433]
* As a user (all user types)
* I want to filter comments
* so that I can easily see the most relevant comment entries based on filtered type

**Assumptions & Scope**	
What are the assumptions for this story?

* Users can toggle between tabs 'User Comments', 'Request History Comments' and 'Divisional Tracking’ in any order

When a user does a keyword search, all tabs will be searched no matter what tab they are on.
What is IN scope?

* Displaying the filtered comments as selected

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Searching  1 type of comments**
* GIVEN I am any user (Ministry or IAO) on the comments tab
* AND the filter is set to either User Comments, Request History or Divisional Stages
* WHEN I enter in one key words in the search bar and hit enter
* THEN only the comments below will refresh and only show comments containing the keyword entered and for the selected filter (e.g. User Comments)
* AND the comments will be listed in chronological order by newest to oldest at the top

**Scenario 2: Searching All Comments**
* GIVEN I am any user (Ministry or IAO) on the comments tab
* AND the filter is set to All
* WHEN I enter in one key words in the search bar and hit enter
* THEN the comments below will refresh and show all comments containing the keyword (User Comments, Request History, Divisional Stages)
* AND the comments will be listed in chronological order by newest to oldest at the top

**Scenario 3: 'User Comments default’**
* GIVEN I am a user
* WHEN I navigate to the Comments tab
* THEN the ‘user comments’ radio button will be selected by default
* AND all user Comments and Replies for the request will be displayed
* AND the comments will be in chronological order by newest to oldest from the top

**Scenario 4: 'Filter by ‘Request History Comments’**
* GIVEN I am on the Comments tab of a request
* WHEN I select the 'Request History Comments' radio button
* THEN only comments posted by 'Request History' will display
* AND any replies to the Request History comments will also display
* AND the comments will be in chronological order by newest to oldest from the top

**Scenario 5: 'Filter by ‘Divisional Tracking’**
* GIVEN I am on the Comments tab of a request
* WHEN I select the ‘Divisional Tracking Comments’ radio button
* THEN only comments posted by ‘Divisional Tracking’ will display
* AND any replies to the Divisional Tracking comments will also display
* AND the comments will be in chronological order by newest to oldest from the top

**Scenario 6: 'Viewing new comments’**
* GIVEN I am on the comment tab of a request
* WHEN I select any radio button 
* THEN a red dot will appear to the left of the username
* AND that will indicate a new comment

**Scenario 7: 'Removing new comments indicator’**
* GIVEN I am on the comment tab of a request
* WHEN I select any radio button
* THEN a red dot will appear to the left of the username
* AND when you select the comment 
* THEN the red dot will disappear as it has been read

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813726 

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
This looks good for your first go Kara - nice one. Some comments for consideration:
- Include the keyword searching of comments for the in-scope part.

Scenario 1 and 2 - just needs a minor tweak to the "THEN" function - I think you put an extra comments in there. 

Scenario 3 - include the additional "AND" you have in the other scenarios for sort order, with newest at the top.

Otherwise, it's probably in good enough shape for the devs to review, barring any further input from Loren. Thanks!

**Comment by KaraBeach** [comment]
@m-prodan- updated - thanks!

**Comment by KaraBeach** [comment]
Hi Loren, I had ask Jackie about that and she had removed the “all comments” from the design based on user feedback as it was overwhelming to navigate.

Kara Beach ( she/her)

|FOI Specialist, Social / Tech Team | Information Access Operations | Ministry of Citizens’ Services Ph: 250 952-0361 |
e: ***@***.******@***.***> | m: PO Box 9569, Stn Prov Gov, Victoria BC V8W 9K1

I am grateful to have the opportunity to live and work in the traditional territories of the lək̓ʷəŋən People, known today as the Esquimalt and Songhees Nations. In sharing this space, I commit to be an ally in the important work of lasting reconciliation with Indigenous Peoples here and everywhere.

**Comment by lmullane** [comment]
@JHarrietha-AOT, @m-prodan, @arielleandrews, 

With a keyword search I think the user will want to search one spot (i.e. All Comments)  to get all the information related to that keyword. 

For example, if I wanted to know how Harms were handled on a request, I would like want to know changes to state, division and comments. 

Searching each tab would be more time consuming. Thoughts?

**Comment by abin-aot** [comment]
As discussed over stand ups/refinement , "NEW COMMENT" is time based, as of now , its 2 days - configurable value.

**Comment by arielleandrews** [comment]
@JHarrietha-AOT please do UX Assurance on this ticket when you have a minute!

**Comment by JHarrietha-AOT** [comment]
@abin-aot I have one comment for UX assurance. There should be much less empty space around the filters.

This is what it currently looks like:
![Screen Shot 2022-08-11 at 12.51.55 PM.png]
(https://images.zenhubusercontent.com/6081a3ba692e484184671a59/80bcf21c-824a-405a-bf1a-ebc75038afd9)

It should be closer to this: ![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/08a3ab4b-907b-4730-ad7a-9032a2ba1c36)

If you can increase the width of the search comment section to decrease the negative space on either side of the filters that would be great. Post here is this is a quick fix you can do now before the ticket is closed or if you would like a separate UX Assurance task

**Comment by abin-aot** [comment]
I will try to create a quick fix for this soon!

**Comment by JHarrietha-AOT** [comment]
Sounds good @abin-aot, maybe coordinate with @amichard as it is the same issue in the attachments search. And just tag me whenever its fixed and I can have a look and move everything through to Ready for QA

**Comment by abin-aot** [comment]
@richard-aot is fixing this UX issue on both components

**Comment by richard-aot** [comment]
@JHarrietha-AOT the width issue is fixed in dev environment. Please verify. Thanks.

**Comment by JHarrietha-AOT** [comment]
Passed UX Assurance Thanks for the Quick Changes @abin-aot & @richard-aot

**Comment by KaraBeach** [comment]
@abin-aot- your comment " As discussed over stand ups/refinement , "NEW COMMENT" is time based, as of now , its 2 days - configurable value."  

Is that referring to AC #7, as I can't seem to get the comments to be read. I have tried, reply, clearing the notifications etc.  Can you confirm?

**Comment by KaraBeach** [comment]
Confirmed at standup- that Scenario 7 is time based now- 2 days. 

All AC's have passed review. Thanks! @abin-aot @richard-aot @JHarrietha-AOT
