### ISSUE TITLE
UX Design for Create a Request

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#247]
Title of ticket: 

#### Description
Purpose of this UX task is to design the flow for a intake to create a request (i.e. for requests not captured in the online webform and/or an MVP for splitting a request captured in the webform).

#### Dependencies
The request fields and editing a request are already captured in other stories.

Will need a kickoff from the Request Queue and a selection of 'General' and 'Personal Request'

Should not require UX research given this is relatively simple and a common pattern.

#### DOD
- [x] UX designs for 'Create a Request'

**Comment by JHarrietha-AOT** [comment]
Design Complete for Creating a request.

Updated Queue: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451

Updated Request Review Page: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/736503621
