### ISSUE TITLE
System generated comment - Assignments

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#2471]
* As a IAO or Ministry user (all users)
* I want a system generated comment to appear whenever this request is assigned to a new analyst 
* so that I can see in the request history who has worked on this request previously 

**Assumptions & Scope**	
* A comment will generate any time the IAO Assigned To or Ministry Assigned To changes, so a comment will appear even when a user assigns themselves
* This includes assignment to any team queues

What is IN scope?

What is NOT in scope?
* No comments for adding or removing Watchers
* No changes to how assignment notifications function

**Acceptance Criteria**	

**Scenario 1: Assign to a user**
* GIVEN an FOI Request has been assigned to a user
* WHEN the assignment is saved (done by auto save) 
* THEN a comment will appear in the Comments section stating "[User completing the action] assigned this request to [New assigned user]" in Lastname, Firstname format
* AND the comment will show Request History as the user name
* AND the comment will show the date and time stamp of when the assignment was saved

**Scenario 2: Assign to a team queue**
* GIVEN an FOI Request has been assigned to a team queue
* WHEN the assignment is saved (done by autosave) 
* THEN a comment will appear in the Comments section stating "[User completing the action] assigned this request to [Team Name queue]"
* AND the comment will show Request History as the user name
* AND the comment will show the date and time stamp of when the assignment was saved

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by abin-aot** [comment]
Functionalities has been completed as per ACs. Assignments are indicated on Comments as per "Review History"/System generated comments.  As mentioned on the stand up, auto reload  of comments after each assignment need additional effort , also as per current design reloading just Sys. generated comments require more updates. cc @arielleandrews @m-prodan , @lmullane

**Comment by KaraBeach** [comment]
@abin-aot- all AC's pass- great work! Thanks!
