### ISSUE TITLE
Files not appearing in attachments tab moving from Fee Estimate to On Hold

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#2484]
**Describe the bug in current situation**
Files uploaded during the state change transition from Fee Estimate to On Hold are not appearing in the Attachments tab

**Link bug to the User Story**
#2270

**Impact of this bug**
Impact is medium. If the page is refreshed the attachment appears. 

**Chance of Occurring (high/medium/low/very low)**
High. Occurs in all tests.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Occurs in test-marshal environment

**Steps to Reproduce**
1. Go to a request in Fee Estimate state
2. Click on state change dropdown
3. Select On Hold
4. Upload a pdf and hit Save
5. Navigate to Attachments
6. See the attachment is not listed

**Actual/ observed behaviour/ results**
Files should appear in the Attachments tab immediately after saving the state change

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KaraBeach** [comment]
@aparna-aot @arielleandrews - bug has been fixed.  File appears in the Attachments tab immediately after saving the state change. Thanks!
