### ISSUE TITLE
Add Attachment Modal with Tags

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#2489]
* As a IAO or Ministry User
* I want to be able to add a new attachment and select a tag to assoicate with an attachment
* so that it is easier for users to find and search attachments

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Add Tag to Attachment in New Attachment Modal IAO **
* GIVEN a IAO user has selected "Add New Attachment"
* WHEN the Add New Attachment Modal Appears
* THEN IAO users will be required to select 1 (1 tag maximum) tag for the new attachment: General (Default), Applicant, CFR, Records Review, Fees, Response, Harms, OIPC, Extensions

**Scenario 2: Add Tag to Attachment in New Attachment Modal Ministry **
* GIVEN a Ministry user has selected "Add New Attachment"
* WHEN the Add New Attachment Modal Appears
* THEN Ministry users will be required to select 1 (1 tag maximum) tag for the new attachment: General (Default), CFR, Records Review, Fees, Response, Harms, OIPC, Extensions

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by JHarrietha-AOT** [comment]
@richard-aot Below is what the modal currently looks like vs what the design is. Please adjust what is in dev to make the text as well as the alignment match the design. Tag here when it is ready to have a look.

Currently: ![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/d2da32c3-364d-42d1-8eb3-c3aefeb61023)

Design: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813733

**Comment by richard-aot** [comment]
Sounds good. Thanks. Actually, I did not know that there is a wireframe. Will apply the changes now.

**Comment by JHarrietha-AOT** [comment]
no worries @richard-aot! I assumed you had the link above, my bad. Just tag me when the update is complete and I can have another look

**Comment by richard-aot** [comment]
@JHarrietha-AOT, I just updated the add attachment modal. Please take a look when you are available. Thanks in advance.

**Comment by JHarrietha-AOT** [comment]
@richard-aot huge improvement! Thanks. One last ask, can we decrease the amount of space between the title and the rest of the content in the modal?

**Comment by JHarrietha-AOT** [comment]
@richard-aot let me know if this is the standard spacing across all modals. If that is the case this is a higher level UX Assurance ticket which I can make as a separate task and you can move this forward. Let me know the best way to proceed.

**Comment by richard-aot** [comment]
@JHarrietha-AOT, it was the standard spacing across all modals. I updated the title space for add attachment modal only this time. Please review. Thanks.

**Comment by JHarrietha-AOT** [comment]
@richard-aot Thanks for adjusting and letting me know. I will make sure it remember the modal spacing when I do UX Assurance on the app as a whole. 

This passes UX Assurance. Feel free to move this to the next column when you're ready.

**Comment by richard-aot** [comment]
Great. Thanks @JHarrietha-AOT

**Comment by m-prodan** [comment]
Works as expected - closing ticket!
