### ISSUE TITLE
Pay Online Link Error Message

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#2502]
**Describe the bug in current situation**
Sometimes when clicking the Pay Online link in the email received by the applicant, the landing page is an error message

**Link bug to the User Story**
#2323

**Impact of this bug**
Impact is medium. If the page is refreshed, or the tab closed and opened again, the link works as expected. Applicants may not try this however and would be confused by the error message.

**Chance of Occurring (high/medium/low/very low)**
Medium. Does not appear to happen every time.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Occurs in test-marshal environment

**Steps to Reproduce**
1. Go to a request in Fee Estimate and approve the CFR form
2. Click on the state change dropdown and select On Hold
3. Upload a file and click Save
4. Open the email received by the applicant
5. Click the Pay Online link
6. See error message

**Actual/ observed behaviour/ results**

**Expected behaviour**
Link should work the first time and take the applicant/user to this page: https://jacklyn808742.invisionapp.com/console/Applicant---Fees-cl4289pe800q5017zhr5hcbg4/cl428adz701nx01ze1maw14dn/play

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/d4a654e8-0525-4404-8fb9-521e99cfb94d)If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KaraBeach** [comment]
@divyav-aot @arielleandrews - bug has been fixed. Thanks! https://test-foi-ffa-request.apps.silver.devops.gov.bc.ca/public/form/62e03bd75e0f9ddda4925058/submission/62e19a005e0f9ddda4925110/edit
