### ISSUE TITLE
Pay BC Cancel is not working in test or dev environments

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#2519]
**Describe the bug in current situation**
Clicking cancel on pay bc page will result in error. This is likely a Pay BC issue, since error coming from their server

**Impact of this bug**
no users impacted, currently working in prod. Only broken in dev and test
will affect QA tickets that involve payment

**Chance of Occurring (high/medium/low/very low)**
high - happens every time

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
in test or dev

**Steps to Reproduce**
- go to submission form in dev or test
- complete a full general request
- proceed to payment page
- click on red cancel button
**Actual/ observed behaviour/ results**
![unnamed.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/29eb013e-e7e0-4bc6-987d-2b748726e05a)

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 
should redirect to this page
![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/24b97689-ad16-45f8-92b1-0ba70a9da394)

**Comment by sumathi-thirumani-aot** [comment]
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/a5684444-d4e8-4d4a-94da-0945e2984d54)

**Comment by sumathi-thirumani-aot** [comment]
This can be closed; as it working as on date.
@nkan-aot please acknowledge.

**Comment by sumathi-thirumani-aot** [comment]
Cancel button click ![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/259a13e3-e459-416c-a475-b2aaf7340b04)

**Comment by nkan-aot** [comment]
confirmed working now
