### ISSUE TITLE
Select Applicant Category changing page appearance

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#252]
**Describe the bug in current situation**
Top banner in the page header shifts right when the Applicant Category dropdown is open, and shifts left again when the dropdown is closed.

**Link bug to the User Story**
Related to User Story #25

**Impact of this bug**
Impact is Low, cosmetic only, but is consistent across all users completing testing. 

**Chance of Occurring (high/medium/low/very low)**
High, occurs for all users in all browsers.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Occurs in Test environment

**Steps to Reproduce**
1. Go to the Review Request page of any request
2. Click on the Category dropdown
3. See error - icons and text in dark blue banner on page header shift right
4. Click on any Category selections so the dropdown closes
5. See error - icons and text in dark blue banner on page header shift left

**Actual/ observed behaviour/ results**
As above

**Expected behaviour**
Banner heading should remain static and not change depending on any selection on page 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/fe23f168-b7b9-459a-b84e-753e26d04a0f)

**Comment by m-prodan** [comment]
closing #252 - issue no longer present
