### ISSUE TITLE
Only the newly uploaded files should be sent to user even if the request is changed from Fee Estimate to On hold multiple times

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#2526]
**Describe the bug in current situation**
Only the newly uploaded files should be sent to user even if the request is changed from Fee Estimate to On hold multiple times.

**Link bug to the User Story**
Related to #2485

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Find a General request with a valid email id and do all necessary steps with CFR Form.
2. Change the request state from Fee Estimate to On hold and also upload files.
3. Change the state back to CFR and do all necessary steps to reach Fee Estimate state again
4. Change state to On hold again with necessary files uploaded.

**Actual/ observed behaviour/ results**
The email received will have even the previous attachments uploaded while doing the state change from fee estimate to onhold.

**Expected behaviour**
Only the newly uploaded files with the last state transition of fee estimate to onhold should be sent in the email to user.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by arielleandrews** [comment]
Bug fix tested and is now working as expected. Thanks @aparna-aot!
