### ISSUE TITLE
UX : Fonts are difficult to read

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#253]

**Comment by mpilchar** [comment]
@sumathi-thirumani-aot  @JHarrietha-AOT seeing this is an early ticket - have addressed this one sufficiently through some of the other UX assurance and tech debt work we've undertaken? Please close if it is outdated

**Comment by JHarrietha-AOT** [comment]
@mpilchar this has not been addressed, this will be larger ticket. 

It would come into play POST MVP, we had it outlined in our feedback from training and I have briefly talked about it with @nkan-aot  who said it would be a larger undertaking as I think we should look at increasing most elements on the page based off of user feedback. We discovered with some user input that what feels like a comfortable size is when people are zoomed into about 125% on chrome.
