### ISSUE TITLE
Pay Link Expiry Notification

### ISSUE THREAD

**Issue by KaraBeach** [bcgov/foi-flow#2534]
* As a user
* I want an expiry notification issued 
* so that it triggers the applicant to contact the analyst if they want to pay

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Pay Link Expiry Notification - States other than On-Hold**
•	GIVEN an applicant has received their Fee Notification email
•	AND the request is in any other state EXCEPT for the on-hold state
•	WHEN the applicant selects the link “Pay Now” 
•	THEN the applicant will be taken to a page with an error notification stating: " pay link has expired please contact your analyst for a new link or further instructions" [Design needed]

**Scenario 2: Pay Link Expiry Notification - Fees Paid**
* GIVEN an applicant has received their Fee Notification email
* AND a payment has been made on the file
* WHEN the applicant selects the link “Pay Now” 
* THEN the applicant will be taken to a page with an error notification stating: " pay link has expired please contact your analyst for a new link or further instructions" [Design needed]

**Scenario 3: Pay Link Expiry Notification - File Closed**
* GIVEN an applicant has received their Fee Notification email
* AND the file is closed
* WHEN the applicant selects the link “Pay Now” 
* THEN the applicant will be taken to a page with an error notification stating: " pay link has expired please contact your analyst for a new link or further instructions" [Design needed]

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KaraBeach** [comment]
@m-prodan-for your review

**Comment by m-prodan** [comment]
update to disable when not on hold state

**Comment by divyav-aot** [comment]
considering the other scenarios of updating the submission with the latest status so that we don't take the applicant to the payment page always.

**Comment by divyav-aot** [comment]
@JHarrietha-AOT - could you please share the design for payment link expiry page?

**Comment by arielleandrews** [comment]
Need additional scenarios to cover if the applicant tries to click the link 1) after the fee is paid, 2) after the file is closed
@m-prodan or @KaraBeach please update ticket to add scenarios. @JHarrietha-AOT please add designs

**Comment by JHarrietha-AOT** [comment]
@divyav-aot @m-prodan @arielleandrews @lmullane @KaraBeach 

I kept it generic in the wording let me know if we thinks this meets the needs or if we want any changes to the content.

![Fees Opening Screen.jpg](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/2fc19a3e-0d82-4ce1-9d23-2bc8aef38c5e)

**Comment by m-prodan** [comment]
Updated to account for the change of state/closed/fee paid scenarios

**Comment by arielleandrews** [comment]
My thoughts are not to include the FOI.Requests email at this stage since that is the intake email and we likely don't want to route correspondence there at this point. The alternative would be to have this dynamically pull the inbox of the IAO team, or say something like "Please email the analyst assigned to your request" instead. @KaraBeach and @m-prodan what are your thoughts? cc @JHarrietha-AOT @lmullane

**Comment by lmullane** [comment]
Possible increase in scope so a revised estimate will likely be necessary.

cc @divyav-aot

**Comment by JHarrietha-AOT** [comment]
@divyav-aot This passed UX Assurance feel free to move it to the next column when you're ready.

**Comment by arielleandrews** [comment]
QA completed, all scenarios passed. Great work!
