### ISSUE TITLE
Processing Fees Payment Receipts - Email and Attachment Log

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2543]
* As an applicant or IAO user
* I want the receipts for processing fee payments to be sent to me/saved to the file
* so that I have a reference of confirmed payment

**Assumptions & Scope**	
This is related to #2325 and #2327 - it was noted that these were estimated without the receipt attachment, and developed without. Instead of increasing the estimate, we've agreed to carve out the receipt piece so those two tickets can close, and address receipts in the next sprint.

What is IN scope?
Receipts attached to the attachment log
Receipt attached to the email confirming payment to applicant

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Receive Confirmation Email**
* GIVEN the user is on the PayBC Credit Card Screen
* AND the user enters a valid CC number, Expiry, and CVD
* WHEN the user clicks 'Pay'
* THEN an email will be sent to the applicant
* AND the email will include the order ID, transaction number, amount and receipt of payment
(Receipt designs: https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922730570 - email confirmation design: https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922766192)

**Scenario 2: Attachment Log - Receipt Attached to Confirmation Email**

* GIVEN an applicant has successfully paid a fee estimate
* WHEN the confirmation email is sent to the applicant
* AND has been done so successfully
* THEN the attached receipt will be saved to the attachment log as a PDF
* AND will be titled "Fees - Payment Receipt

**Scenario 3: Confirmation Email - Updated Legislated Due Date**
* GIVEN an applicant has successfully paid the fee estimate
* WHEN the request is taken off hold
* AND the new Legislated Due Date is calculated
* THEN the email will include the newly calculated legislated due date
* AND all other fields in the template will be auto-populated from the system
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922766192

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
Receipt designs: https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922730570 

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
@m-prodan @KaraBeach @JHarrietha-AOT please confirm phone numbers and email addresses in receipt and email templates

**Comment by arielleandrews** [comment]
@aparna-aot or @divyav-aot what would the effort be like to have the red text about the balance not be included if the estimate was paid in full? I am thinking it may confuse users who don't have a balance remaining. If the effort is significant we may want to just edit the text to make it clearer that only applies if there is a balance. cc @JHarrietha-AOT @lmullane @KaraBeach @m-prodan 
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/8f1c0063-3f77-48e6-a79f-b59395b4b05e)

**Comment by divyav-aot** [comment]
@arielleandrews , we can remove from the template. Its not a big effort. I can remove right away, if you confirm. In total it will take approximately 1 or 2 hours to deploy till test-marshal.

**Comment by arielleandrews** [comment]
@divyav-aot Oh that's great! To be clear, it would still be there when only a deposit was paid and there is a balance remaining, but not there when the fee was paid in full and there is no balance remaining, is that right?

**Comment by divyav-aot** [comment]
yes. that is correct.

**Comment by arielleandrews** [comment]
Functional QA is complete, all scenarios have passed. Over to you @JHarrietha-AOT for UX Assurance!

**Comment by arielleandrews** [comment]
@divyav-aot I tested the update to the receipt and the red text is still showing even when the fee estimate was paid in full - see TAC-2022-54321 in test-marshal

**Comment by JHarrietha-AOT** [comment]
This ticket hasn't passed UX Assurance - I have made a separate ticket to address the changes #2629. So that this ticket can be closed and it can be estimated seprately. @arielleandrews feel free to close whenever youve completed QA

**Comment by divyav-aot** [comment]
@arielleandrews - I am checking the issue with Receipt. I will keep you posted. 
@JHarrietha-AOT - we will pick the UX issues soon after finishing the existing issues committed for this sprint.

**Comment by divyav-aot** [comment]
@arielleandrews the receipt issue has been fixed in test-marshal. Please test and confirm.

**Comment by arielleandrews** [comment]
QA is completed, all scenarios passed and functioning as expected. A future enhancement to the receipt may be to only include the line items that are actually charged (i.e not display the Producing line if there is no charge for Producing). @JHarrietha-AOT can that be added to #2629?
