### ISSUE TITLE
Update Fee Estimate Payment Email

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2551]
* As an applicant
* I want to have the option to pay online
* so that I can pay my fee estimate quickly

**Assumptions & Scope**	
This story updates the previously developed email template sent to the applicant, when a fee estimate is required, to be consistent with the confirmation email template
Header and footer will follow this template: https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922766192

What is IN scope?
Updating sent email template for fee estimates

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Email Template Generation**
* GIVEN a FOI Request is in the Fee Estimate State
* WHEN the request is changed to on hold
* AND the files have been uploaded
* THEN the fee estimate will be sent, with the following email template: *need design*

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@JHarrietha-AOT - at sprint planning today, team thinks it would be good to have a consistent design for both the confirmation email, and the initial email sent for fee payment.

cc: @lmullane @arielleandrews @KaraBeach

**Comment by arielleandrews** [comment]
@m-prodan to provide updated template content

**Comment by m-prodan** [comment]
Updated templated content to have correct phone number for footer, and updated wording for header:

https://bcgov.sharepoint.com/:w:/r/teams/03521/_layouts/15/Doc.aspx?sourcedoc=%7B0EA79F54-9C55-4D67-8D12-512AC09363F3%7D&file=Draft%20Email%20-%20Online%20Pay.docx&action=default&mobileredirect=true

Please use this content in concert with the designs template tagged in the assumptions of this story.

cc: @nkan-aot @aparna-aot @lmullane @KaraBeach

**Comment by divyav-aot** [comment]
@m-prodan We discussed earlier about the payment successful and failure email categories. Could you please confirm if we can use below ones as category.
**New Category:**
Fee Estimate/Payment Correspondence - Successful
Fee Estimate/Payment Correspondence - Failure
**Previous Category:**
Fee Estimate - Successful
Fee Estimate - Failed
Please confirm.

**Comment by divyav-aot** [comment]
As per the discussion below are the finalized categories.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/db4ad7f6-b5c5-4e26-bb65-b334e790f24d)
The subject for
Fee - Estimate Sent.eml is "Your FOI Request EDU-xxx-xxx"
Fee Estimate - Payment Receipt Sent.eml is "Your FOI Request EDU-xxx-xxx - Fee Payment Received"

**Comment by arielleandrews** [comment]
@JHarrietha-AOT testing of this ticket is essentially doing UX Assurance - assigning to you to complete. Thanks for taking this on!

**Comment by JHarrietha-AOT** [comment]
UX Assurance complete - any additional changes to emails are addressed in #2629
