### ISSUE TITLE
Design - Open Information Screens

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#2556]
Title of ticket: Design - Open Information Screens

#### Description
Based off of flows established in Roadmapping with Buisness Team, make first iteration of designs for NEW Proposed Open Information Prcoess - This will be first iteration

Iteration 1 
• No Document Viewer
• Download Document to Review
• Redaction in AXIS or Adobe
• Open Information Queue

Iteration 2
• Document Viewer (based off of technical teams recommendations)
• Download Document to Review
• Redaction in AXIS or Adobe
• Open Information Queue

Iteration 3
• Document Viewer (based off of technical teams recommendations)
• Download Document to Review
• Redaction in FOI Flow APP
• Open Information Queue

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Open Information Queue
- [x] Place for them to Download Documents to Review
- [x] Stages to happen post closing request

**Comment by JHarrietha-AOT** [comment]
Will update estimate after Release Planning & Roadmapping Session on August 4th

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @KaraBeach @lmullane @m-prodan Here is the first iteration of the Open Information process. 

You will start but entering a request in response - IAO Analyst will update the request to Closed - The Closed Modal has been updated so the user can upload the final redacted package - When IAO user is ready to pass the request to the Open Information Team they will update the Stage to Ready to Review which will assign the request to the OI Queue - Then OI Team Analysts can move through the stages - Review for Publishing (when the analyst can download the documents and review) - Pending Publishing (When the final package has been confirmed and redated) - This will also prompt our back end to pull the request to publish on Open Info Website - The stage will automatically be changes to Published when the back end action happens and the package has been uploaded to the Open Information Website. https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/942612517

**Comment by JHarrietha-AOT** [comment]
@arielleandrews I really like those stage name suggestions. Makes then feel alot more distinct. I'll definitely make that update before we do sessions next week!

**Comment by lmullane** [comment]
Thanks for the opportunity to review, @JHarrietha-AOT 

Agree with the state name changes suggested by @arielleandrews.

Couple of things:

- We should create a design for how the final response package is shared with the applicant once it is 'Closed.'
- Is the OI analyst required to upload the final redacted package when they change the state to 'Pending Published'?

**Comment by lmullane** [comment]
@JHarrietha-AOT, just following up on my question above:)

**Comment by JHarrietha-AOT** [comment]
@lmullane Sorry for not following up. I meant to cover these off in sprint planning as I had created ticket #2638 which address the changing in the state names as well as making two design updates to address the points you outlined above. I am planning on picking up that ticket tomorrow.

**Comment by lmullane** [comment]
No worries. Thanks, @JHarrietha-AOT
