### ISSUE TITLE
Non-Pilot Ministry Search - Default Filters

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2566]
* As a non-pilot User
* I want to be able to find any of my team requests
* so that I can get to them quickly

**Assumptions & Scope**	
This story covers the need for non-pilot users to be able to find their requests after they are added to the system. This could be a team lead, or another user looking for this request which is why an advanced search may be needed.

Will need non-pilot user groups set up first before we can functionally QA/test this. Will also require mapping to users based on their team and their available Ministries to search

Non-pilot users will have their search filters restricted, as they will only be searching for a specific set of requests.

The search function itself will work the same as it does for pilot users - this is mainly a front-end change to drive certain results

What is IN scope?
Advanced Search - Non-Pilot Users

**Acceptance Criteria**	

**Scenario 1: Default Filters Request Types**
* GIVEN I am a non-pilot user, signed into the application
* WHEN I click on advanced search
* THEN I will be taken to the advanced search view
* AND the following filters will be activated: Search Selected: AXIS Request #, Request State: Call for Records, On-Hold, Request Status: Active, Request Type: General 
* AND all other fields will be greyed out, and not selectable

**Scenario 2: Default Filters - Public Body**
* GIVEN a non-pilot user is on the advanced search page
* WHEN they activate the public body drop down
* THEN the Ministries selected by default will be the Ministries associated with that team

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000375

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Breakdown of Ministries/public bodies by team - note: Business and Social Ed are considered "pilot users"

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/7c36b040-64a6-4b25-8e14-3fed8f57d049)

**Comment by lmullane** [comment]
Same questions question I posed to Jackie earlier. What if I have requests that are a pilot ministry (e.g., Education) and not a pilot ministry (e.g., AEST)?

Sent from my iPhone

On Aug 8, 2022, at 12:27 PM, m-prodan ***@***.***> wrote:

﻿

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


Breakdown of Ministries/public bodies by team - note: Business and Social Ed are considered "pilot users"

[image.png]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2Ff188e74ac0aa18983e65e4be7ae723134c2bc8fa55d750057109353e946d6147%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630383161346338326630633336336464646239633161302f37633336623034302d363461362d346232352d386531342d336665643866353764303439&data=05%7C01%7CLoren.Mullane%40gov.bc.ca%7C5b65c741a00f4001c30008da79740b47%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637955836550185772%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bgDw6Hi8%2BHXV7cJp0oqSdyNJzthtcww7IGr2mB3xJn8%3D&reserved=0>

**Comment by m-prodan** [comment]
Closing story, as no longer required - users will have same advanced search features as others
