### ISSUE TITLE
Sign in – Mapping Queues Non-Pilot Analyst (NPU)

### ISSUE THREAD

**Issue by KaraBeach** [bcgov/foi-flow#2569]
As a Non Pilot Ministry, I want to authenticate and login with IDIR, so that I can securely process fee related requests.

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Requests that will Appear in the Business Queue – (Non-Pilot Ministry) **
•	GIVEN The Request queue for the Business queue is opened
•	WHEN there are requests to: Transportation, Transportation Investment Corp 
•	THEN those requests shall appear in the Business queue as NPM
•	AND the requests will be actionable for processing analysts assigned to this group

**Scenario 2: Requests that will Appear in the Justice Health Queue – (Non-Pilot Ministry**
•	GIVEN The Request queue for the Justice Health queue is opened
•	WHEN there are requests to: Attorney General (MAG), Public Safety and Solicitor General, Coroners Service of BC (OCC), Emergency Management BC (EMB), Health (HTH), Mental Health and Addictions (MHA), Independent Investigation Office (IIO) 
•	THEN those requests shall appear in the Justice health queue as NPM
•	AND the requests will be actionable for processing analysts assigned to this group

**Scenario 3: Requests that will Appear in the Social Education Queue – (Non-Pilot Ministry)**
•	GIVEN The Request queue for the Social Education queue is opened
•	WHEN there are requests to: BC Public Service Agency, Social Development and Poverty Reduction (MSD), Advanced Education and Skills Training (AED), Government Communications and Public Engagement (GCP), Education and Child Care (EDU), Children and Family Development (CFD)
•	THEN those requests shall appear in the Social Education queue as NPM
•	AND the requests will be actionable for processing analysts assigned to this group

**Scenario 4: Requests that will Appear in the Resource Queue – (Non-Pilot Ministry)**
•	GIVEN The Request queue for the Resource queue is opened
•	WHEN there are requests to: Agriculture, Food and Fisheries (AGR), Energy, Mines and Low Carbon Innovation (EML), Environment and Climate Change Strategy (MOE), Environmental Assessment Office (EAO), Indigenous Relations and Reconciliation (IRR), Declaration Act Secretariat (DAS), Ministry of Forests (FOR), Lands, Water and Resource Stewardship (LWR) 
•	THEN those requests shall appear in the Resource queue as NPM
•	AND the requests will be actionable for processing analysts assigned to this group

**Scenario 5: Requests that will Appear in the Central Queue – (Non-Pilot Ministry)**
•	GIVEN The Request queue for the Central queue is opened
•	WHEN there are requests to: Finance (FIN), (Crown Agencies Secretariat (CAS), Liquor Distribution Branch (LDB), Office of the Premier (OOP) , Citizens’ Services (CTZ), Order of British Columbia Advisory Committee (OBC), Medal of Good Citizenship Selection Committee (MGC)
•	THEN those requests shall appear in the Central queue as NPM
•	AND the requests will be actionable for processing analysts assigned to this group

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KaraBeach** [comment]
@m-prodan - for your review

**Comment by KyEggleston** [comment]
Closing request, as this is a stale ticket and this had been handled through other tickets

@m-prodan @lmullane
