### ISSUE TITLE
Long page loading time after applicant pays processing fee

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#2625]
**Describe the bug in current situation**
Once an applicant has paid their processing fee via PayBC, the applicant is redirected to a confirmation page in FormsFlow. This page takes approximately 10 seconds to load and does not display a spinner or any indication the page is loading.

**Link bug to the User Story**

**Impact of this bug**
Impact is low. Page loads as expected but may confuse users as it appears temporarily frozen, could result in unnecessarily refreshing the page.

**Chance of Occurring (high/medium/low/very low)**
High. Has occurred in all QA testing so far.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Occurs in test-marshal

**Steps to Reproduce**
1. Go to pay a processing fee online
2. Enter test credit card information and Click on Submit Payment
3. See load screen take approx 10 seconds before confirmation information appears 

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by JHarrietha-AOT** [comment]
@divyav-aot this passes UX Assurance. Feel free to move it to the next column when you're ready

**Comment by arielleandrews** [comment]
Tested and issue is resolved. Nice work team!
