### ISSUE TITLE
UX Assurance - Emails to Applicants

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#2629]
Title of ticket: UX Assurance - Emails to Applicants

#### Description
This ticket encompasses a list of changes to be made to all of the outgoing emails to Applicants. These changes would be make across all outgoing emails going forward

#### Visual References
Desktop
![Screen Shot 2022-08-15 at 3.15.02 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/4937a1ec-831b-42a7-b3de-78d61b310143)

Tablet![IMG_0484.jpg](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/e9741070-53ba-4a55-aac1-30c2b5f8b2d5)

Mobile
![IMG_1557.PNG](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/c3df53ce-5341-445e-b891-5a3e26913c53)

#### DOD
- [ ] Email content font should be changed to BC Sans (foot can remain in Serif font)
- [ ] Blue header should have increased spacing around logo
- [ ] Blue header colour needs to be corrected on Mobile and Tablet to correct colour

**Comment by lmullane** [comment]
As flagged by @KaraBeach, dollars should show 2 decimals for cents.

**Comment by JHarrietha-AOT** [comment]
@divyav-aot @sumathi-thirumani-aot  Linked #2629, as discussed at standup today all fonts one the processed receipet should be changed to BC Sans. 

Here is a link to the BC Sans reference guide for future reference: https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/bc-sans

**Comment by JHarrietha-AOT** [comment]
@divyav-aot this passes UXAssurance thanks for working through these changes, feel free to move to the next column whenever you're ready.
