### ISSUE TITLE
View CFR Fee Estimate History

### ISSUE THREAD

**Issue by KaraBeach** [bcgov/foi-flow#2633]
* As a ministry coordinator or IAO analyst
* I want be able to view the history or previous CFR fee estimates in any state
* so that I can see the history with all versions of a CFR fee estimate.

**Assumptions & Scope**	
What are the assumptions for this story?

A new fee estimate is likely as applicants often narrow requests to reduce fees.

What is IN scope?

History of CFR forms.

What is NOT in scope?

Create new CFR form is covered in #2652

**Acceptance Criteria**	

**Scenario 1: View CFR History**
•	GIVEN a request is in any state
•	AND at least one version of the form has been Approved
•.     AND the analyst is on the CFR Form
•	WHEN the analyst clicks on ‘CFR Form History’ https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000371
•	THEN a modal will open with the CFR Form History https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000379
•	AND previous versions of the CFR Form will be listed from newest to oldest
•	AND each previous version of the CFR Form will include the date and name of the user who created them 

**Scenario 2:  Open Previous Version of CFR - accordion in modal**
•	GIVEN the analyst or coordinator is on the  ‘CFR Form History’ modal
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/943161279
•	WHEN the user clicks on a listed previous versions of a CFR
•	THEN the accordion will expand
•     AND that version of the CFR Form will be displayed
•     AND the version will be greyed out and not be editable

**Scenario 3: View CFR History button inactive**
•	GIVEN a request is in any state
•	AND only one version of the CFR form has been Approved
•.     WHEN the analyst is on the CFR Form
•	THEN the ‘CFR Form History’ button will be greyed out an not clickable

**Scenario 4: CFR Form History active**
•	GIVEN a request is in any state
•	AND at least 1 version of the CFR Form has been Approved
•.     WHEN the analyst is on the CFR Form
•	THEN the CFR Form History will be active and blue

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KaraBeach** [comment]
@lmullane @m-prodan @arielleandrews - for your review

**Comment by m-prodan** [comment]
Made some tweaks to scenario 2 and 3 - otherwise I think this can go for refinement at sprint planning tomorrow - let me know your thoughts @lmullane

**Comment by lmullane** [comment]
I made some edits as well.

@JHarrietha-AOT, could we confirm what happens when you click on  a previous version of the form? Assume the modal closes as per the AC above.

**Comment by lmullane** [comment]
As discussed at sprint planning, I have split this story. This story covers versioning.

#2652 covers creation of new CFR fee estimate form.

**Comment by arielleandrews** [comment]
@JHarrietha-AOT please update design to include accordion in modal as discussed during sprint planning Aug 17. Thanks!

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Design links have been updated with new accordian

**Comment by lmullane** [comment]
Thanks for the quick turn-around, @JHarrietha-AOT!

Looks good.

**Comment by lmullane** [comment]
Updated AC so that one version of an Approved CFR form will be displayed in the history.

**Comment by JHarrietha-AOT** [comment]
@divyav-aot @nkan-aot a few small changes to this on just so it better meets the UX Designs

- [ ] Text boxes are not centred in the modal accordion
- [ ] Titles on text boxes should be greyed out
- [ ] Title of accordion should be bolded
- [ ] Content of accordion would ideally the have less space between them like the design, titles should match design in Blue

Currently:
![Screen Shot 2022-08-26 at 1.13.18 PM.png]
(https://images.zenhubusercontent.com/6081a3ba692e484184671a59/7a00839c-76fe-409f-8ad5-4959bcccf9e9)

Designs:
![Screen Shot 2022-08-26 at 1.16.36 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/bac8045a-2352-47ba-bc21-078fad76e2ae)

**Comment by JHarrietha-AOT** [comment]
Passed UX Assurance based on the changes @nkan-aot has made on his local. These changes are waiting to get pushed and nick will comment in ticket when they are pushed throught. 

Feel free to move on with functional testing instead of waiting for the UX changes to be pushed @lmullane @arielleandrews

**Comment by lmullane** [comment]
Nice work team. AC passes.
