### ISSUE TITLE
Update to Fee Actuals and State Change Logic

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#2641]
* As a Ministry Coordinator
* I want to know when I have to record the actuals of a fee estimate
* so that I can accurately complete a fee estimate during a call for records

**Assumptions & Scope**
* This is a follow-up to user story #2198. 
* Currently the Ministry user can bypass the need to complete the fee estimate actual hours if the state is changed from CFR to Harms Assessment before moving to Records Review. 
* There is a need for the Ministry user to fill in the actual hours/figures for a fee estimate when an applicant has paid the original estimate/deposit.
* The need for actuals is only initiated when a fee estimate has been paid (deposit or full). Requests that don't have fee estimates should proceed through the state changes as normal
* Scenario 4 functions the same as the estimated hours for Locating/Retrieving

**What is IN scope?**
* Fee estimate actuals when moving from Harms Assessment to Records Review

**What is NOT in scope?**
* Processing Payment
* Applicant Experience

**Acceptance Criteria**

**Scenario 1: Change State from Harms Assessment to Records Review when Fee Paid - No Actuals**
* GIVEN a Ministry coordinator is on a request where a fee estimate has been paid in part or in full
* WHEN they attempt to change the state to Records Review
* AND the actual hours have NOT been saved or updated in the fee estimate form, and all remain at 0
* THEN an error message will appear with the following message "Unable to change state until fee estimate actuals have been completed"

**Scenario 2: Change State from Harms Assessment to Records Review when Fee Paid - With Actuals**
* GIVEN a Ministry coordinator is on a request where a fee estimate has been paid in part or in full
* WHEN they attempt to change the state to Records Review
* AND the actual hours have been saved or updated in the fee estimate form to be greater than 0 in any field
* THEN the state change will complete
* AND there will be no mandatory upload required.

**Scenario 3: Change State from Harms Assessment to Records Review when Fee Paid - IAO Actuals**
* GIVEN a Ministry coordinator is on a request where a fee estimate has been paid in part or in full
* WHEN they change the state to Records Review
* THEN the field for IAO actual hours will be editable by IAO
* AND the field will not be mandatory to complete

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
@aparna-aot what would the effort be like to make the CFR form editable by the Ministry coordinator while in the Harms Assessment state? It is currently uneditable and makes it the user can't move forward to Records Review. I didn't think of that when writing the AC!

**Comment by arielleandrews** [comment]
Tagging @m-prodan and @KaraBeach - please follow up on this next week as likely need to revisit AC. Moving back to Ready for QA for now until this can be discussed. Thanks team!

**Comment by m-prodan** [comment]
As discussed at stand up - we will leave the functionality as is, users have a workaround to get back to CFR to enter actuals when needed. Will monitor user feedback when implemented

**Comment by KaraBeach** [comment]
@m-prodan- I believe Arielle QA'd minus the one question regarding one AC. Are we okay to close?

**Comment by m-prodan** [comment]
If that is confirmed - then yes, this can be closed now - thanks! @KaraBeach
