### ISSUE TITLE
Create new CFR fee estimate

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2652]
* As a ministry coordinator (pilot ministry)
* I want be able to create a new CFR fee estimate 
* so that I can issue a new fee estimate (i.e., narrowed request) 

**Assumptions & Scope**	
What are the assumptions for this story?

A new fee estimate is likely as applicants often narrow requests to reduce fees.

A new CFR fee estimate form can only be created if a previous CFR fee estimate form has been Approved.

A new fee estimate can be created only in CFR or On Hold state

What is IN scope?

Change state logic. A new fee estimate can be created only in CFR or On Hold state

Pilot ministry requests.

What is NOT in scope?

CFR form history will be covered in another story. #2633
Resending correspondence to the applicant
Creating initial CFR form.
Expiry of payment link when a new CFR Form is approved. #2656

**Acceptance Criteria**	

**Scenario 1: Active CFR Form button**
•	GIVEN a CFR fee estimate form has been previously approved
•    AND the request is in the CFR, Fee Estimate or On Hold state
•	AND the coordinator is on the CFR Form
•	WHEN the coordinator clicks on CFR Form 
•	THEN the 'Create New Fee Estimate' button will blue or active
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000373

"**Scenario 2: Create New CFR Fee Estimate Form**
•	GIVEN a CFR fee estimate form has been previously approved
•     AND the request is in the CFR, Fee Estimate or On Hold state
•	WHEN the coordinator clicks on the active 'Create New Fee Estimate' button 
•	THEN a modal will open with the message "Are you sure you want to create a new, blank CFR form? Any unsaved changes will be lost. The previous version will be locked for editing and viewable in the CFR Form History."
•	AND buttons to 'Cancel' or 'Continue'

**Scenario 3: Cancel create New CFR Fee Estimate Form**
•	GIVEN a CFR fee estimate form has been previously approved
•     AND the coordinator is on the modal to Create a new CFR Form
•	WHEN the coordinator clicks on the  'Cancel' button 
•	THEN the new blank, CFR Form will not be created
•.     AND the modal will close
•.     AND the previously 'Approved' CFR Form will be displayed

**Scenario 4: Create New CFR Fee Estimate Form**
•	GIVEN a CFR fee estimate form has been previously approved
•     AND the coordinator is on the modal to Create a new CFR Form
•	WHEN the coordinator clicks on the  'Continue' button 
•	THEN the new blank, CFR Form will be created
•.     AND the modal will close
•.     AND the new blank, CFR Form will be displayed

**Scenario 5: Inactive CFR Form button**
•	GIVEN a CFR fee estimate form has NOT been previously approved
•     AND the request is in the CFR, Fee Estimate or On Hold state
•	AND the coordinator is on the CFR Form
•	WHEN the coordinator clicks on CFR Form 
•	THEN the Create 'New Fee Estimate' button will greyed out and active
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000372

**Scenario 6: Pilot Ministry Coordinator CFR Form Status**
* GIVEN a Ministry coordinator has created a new CFR form and hit Save
* WHEN they open the CFR form status dropdown 
* THEN they will have the ability to set the status to In Review with IAO
* AND the other options will be disabled 

**Scenario 7: Create new CFR Form when a deposit has already been paid**
* GIVEN a Ministry coordinator has created a new CFR form and hit Save
* WHEN the applicant has paid a deposit
* THEN the amount paid will be carried over to the new CFR form

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
Will need a new story for sending the new CFR Form to the applicant.

**Comment by JHarrietha-AOT** [comment]
@aparna-aot I have added links above, let me know if you have any questions

**Comment by aparna-aot** [comment]
Sure. Thanks @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
Here is the updated design link for the modal: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/946185572

**Comment by lmullane** [comment]
Thanks for the quick turn-around, @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
This passes UX Assurance @lmullane @arielleandrews

**Comment by lmullane** [comment]
I have updated the AC to include better reflect the warning modal and the Cancel or Continue behaviour.

@nkan-aot, scenarios 1-5 and 7 have passed. 

Scenario 6  did not pass as the ministry coordinator can change the status of the form to 'In Review by IAO' without entering any hours and saving the form.  They should only be able to change the form status when they have saved the form.

Will put back into In Progess for you to investigate.

@JHarrietha-AOT, one design question. When a coordinator creates a new CFR form, should they see the version of the form displayed once they save it? 

I like how the CFR Form history shows the form versions (i.e., version 1) but wonder if the user may want to see they are editing, reviewing or approving version 2.

**Comment by lmullane** [comment]
Thanks for the quick fix, @nkan-aot 

All AC have passed.
