### ISSUE TITLE
Divisional Tracking Due Dates - Notifications

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2672]
* As a Ministry user
* I want to know when my division's responses are due with a notification
* so that I know when I need to follow up with them

**Assumptions & Scope**	
This is a user feedback related story - Ministry coordinators may find value in receiving notifications when certain stages of divisional tracking approach their due dates. 

Divisional tracking notifications will only be sent to the Ministry coordinators assigned to a request, as either a watcher or primary assignee.

What is IN scope?
Notifications - specifically for divisional tracking stages that have a due date

**Acceptance Criteria**	

**Scenario 1: Gathering Records - Due Tomorrow**
* GIVEN a Ministry user is assigned to a request
* AND the request has a division in the gathering records stage
* WHEN the date is one business day prior to the saved due date for that stage
* THEN all assigned Ministry users shall receive a notification with the message "[Division] records are due tomorrow"

**Scenario 2: Gathering Records - Due Today**
* GIVEN a Ministry user is assigned to a request
* AND the request has a division in the gathering records stage
* WHEN the date is the same as the saved due date for that stage
* THEN all assigned Ministry users shall receive a notification with the message "[Division] records are due today"

**Scenario 3: Pending Sign-Off - Due Tomorrow**
* GIVEN a Ministry user is assigned to a request
* AND the request has a division in the pending sign-off stage
* WHEN the date is one business day prior to the saved due date for that stage
* THEN all assigned Ministry users shall receive a notification with the message "[Division] sign off is due tomorrow"

**Scenario 4: Pending Sign-Off - Due Today**
* GIVEN a Ministry user is assigned to a request
* AND the request has a division in the pending sign-off stage
* WHEN the date is one business day prior to the saved due date for that stage
* THEN all assigned Ministry users shall receive a notification with the message "[Division] sign off is due today"

**Scenario 3: Awaiting Harms - Due Tomorrow**
* GIVEN a Ministry user is assigned to a request
* AND the request has a division in the awaiting stage
* WHEN the date is one business day prior to the saved due date for that stage
* THEN all assigned Ministry users shall receive a notification with the message "[Division] harms are due tomorrow"

**Scenario 4: Awaiting Harms - Due Today**
* GIVEN a Ministry user is assigned to a request
* AND the request has a division in the Awaiting Harms stage
* WHEN the date is one business day prior to the saved due date for that stage
* THEN all assigned Ministry users shall receive a notification with the message "[Division] harms are due today"

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
story per discussion with educ today re: Divisional tracking due date notifications. Leaving as incomplete AC, as I'd like to check with ECON sector team/Carrie to confirm how often they want reminders (ie: just day before and day of sufficient?)

Though I think we could still refine this, since at most we'd just be updating a value or adding another scenario if a third reminder is needed. 

cc: @lmullane @KaraBeach @arielleandrews @JHarrietha-AOT

**Comment by m-prodan** [comment]
Heard back from ECON and EDUC - they are good with reminders day of and day before

**Comment by sumathi-thirumani-aot** [comment]
@m-prodan We send reminder notifications on the day of expiry and the previous business day. Could you please confirm this as the "day before" scenario ?

**Comment by m-prodan** [comment]
Hi @sumathi-thirumani-aot - yes, that is correct, this would be the day before scenario.

**Comment by sumathi-thirumani-aot** [comment]
@m-prodan  At what stage of FOI Request,  do we need to send notifications ?

References: 
1. CFR due reminder is send only on Call For Records state
2. Legislative due reminder is sent on all stages except (Unopened, Intake in Progress, Redirect, On Hold, Closed, Archived)

**Comment by m-prodan** [comment]
I don't think it needs to be tied to state - the condition should be the divisional stage itself - for example:

Divisional stage = Gathering Records with a Due Date assigned = notification on
Divisional stage = Records Received = notification off

Basically any of our divisional stages that have a due date would trigger notification, I think I covered all the possibilities with the scenarios. (Gathering Records, Pending Sign-Off, and Awaiting Harms)

**Comment by sumathi-thirumani-aot** [comment]
Migration script associated with this task "**d1503b142889_.py**"

**Comment by sumathi-thirumani-aot** [comment]
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/ec7c46bf-3de2-47a1-bc37-2943f1cc480c)

**Comment by m-prodan** [comment]
Per discussion at standup - notifications will not trigger when in intake in progress, unopened, on hold and closed

**Comment by sumathi-thirumani-aot** [comment]
As per discussion with @m-prodan ; the state condition of legislative due date will hold good for division due date.

**Comment by m-prodan** [comment]
For testing - EDU-2022-22221 has all scenarios staged with due dates on Oct 24th, and 25th

**Comment by m-prodan** [comment]
all scenarios passed - closing ticket.
