### ISSUE TITLE
Update to CFR form and actuals calculation

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#2678]
* As an IAO user and ministry coordinator (all users)
* I want to clearly see the original fee estimate
* so that I can see what was estimated, paid, and the balance remaining 

**Assumptions & Scope**	
This is a design and display update only
Tool tip will explain how balance is calculated and carried over 

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Fee Estimate Total**
* GIVEN a CFR form has estimated hours added to it
* WHEN a user navigates to the form
* THEN they will see a field that includes the estimated total

**Scenario 2: Fee Actuals Total**
* GIVEN a CFR form has actual hours added to it
* WHEN a user navigates to the form
* THEN they will see a field that includes the Actual totals

**Scenario 3: Tool-Tip**
* GIVEN a user is on the CFR Form page
* WHEN they hover over the tool tip next to the payment details frame
* THEN the following message will display: "The balance remaining for a fee estimate is the Estimated total subtracted by the amount paid. When actuals are entered, the balance remaining is the actual totals subtracted by the amount paid. If the balance is negative, then an applicant may be owed a refund."
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@JHarrietha-AOT  - please link the Design here when updated

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by JHarrietha-AOT** [comment]
@arielleandrews I think this is the right design: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/912622803

Let me know if this doesn't match what you rememeber

**Comment by m-prodan** [comment]
@nkan-aot - AC updated per stand up this morning

cc: @arielleandrews @lmullane

**Comment by m-prodan** [comment]
@nkan-aot - only issue is there is no tooltip showing up - the amounts tally properly and is displayed as expected, but the tootltip is missing. Can't close this one yet unfortunately. Moving back to Review

**Comment by m-prodan** [comment]
Thanks @nkan-aot - all scenarios passed, closing ticket
