### ISSUE TITLE
Add fields for Original Due Date/Closed Date/Records Due Date

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#2685]
* As a user
* I want to see fields that capture the Original Due Date, Records Due Date, and Closed Date of a request
* so that I can see the full lifecycle of the request and respond to any questions from the OIPC in the event of a complaint

**Assumptions & Scope**	
* This ticket will require a small design update to include these fields on the request details page
* Original Due Date will display the original legislated due date from the time the request is opened and will not be editable
* Legislated due date will update after extensions and/or after a request comes off On Hold
* Date fields will always be visible but will show blank or N/A until populated following the relevant state change

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: State change from Intake in Progress to Open**
* GIVEN the request is in Intake in Progress state
* WHEN the state is changed to Open 
* THEN the field "Original Due Date" will populate and will display the original legislated due date of the request
* AND the field will not be editable

**Scenario 2: State change from Open to Call for Records**
* GIVEN the request is in Open state
* WHEN the state is changed to Call for Records 
* THEN the field "Records Due Date" will populate and will display records due date of the request (+10 business days)
* AND the field will not be editable

**Scenario 3: State change from On Hold to Call for Records**
* GIVEN the request is in On Hold state
* WHEN the state is changed to Call for Records 
* THEN the field "Records Due Date" will recalculate and will display the new records due date of the request 
* AND the field will not be editable

**Scenario 4: State change to Closed**
* GIVEN the request is any state from Open onward
* WHEN the state is changed to Closed 
* THEN the field "Closed Date" will populate and will display the date the request was closed
* AND the field will not be editable 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/928170230

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
@lmullane @m-prodan @KaraBeach for your review - I have written these so the relevant fields display based on the corresponding state changes

@JHarrietha-AOT please update designs and add links when you are ready!

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Was just wondering if there are an additional fields that we would want displayed in the request (ex. closed date)

Also do we not want these fields to show up until the specific state changes has happened, or do we want them to always be there but just be disabled until the desired state changes has happened

**Comment by JHarrietha-AOT** [comment]
@arielleandrews I have reorganized and added the above dates, let me know what you think and if you have an additional dates you would like to see added
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/928170230

**Comment by m-prodan** [comment]
I think we should add a scenario that shows the original due date when an extension is taken as well. Or perhaps we should just always have it persist? Regarding the off-hold - I feel that could get messy or misleading should a request go on hold multiple times. Having thought about it more, maybe best to leave it out altogether? Analysts can always go back in the request history log to confirm those dates anyways.

**Comment by JHarrietha-AOT** [comment]
@m-prodan @JHarrietha-AOT I've update the design based on the previous comments. Let me know if you have any additional changes.

https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/928170230

**Comment by arielleandrews** [comment]
I have updated the AC and will draft a bug ticket for the start date issue. Thanks Matt and Jackie!

**Comment by m-prodan** [comment]
@arielleandrews - at refinement, we talked about seperating these out into a bug ticket (start date shifting) and just adding the new fields. I can do this if you like - Devs also commented they couldn't reproduce the shifting start date, can you walk us through at stand up tomorrow?

**Comment by arielleandrews** [comment]
@nkan-aot and @JHarrietha-AOT ticket updated to include scenarios for Records Due Date. Let me know if there are any questions!

**Comment by JHarrietha-AOT** [comment]
@nkan-aot Designs are updated now to based off of the conversation we had earlier.

**Comment by KaraBeach** [comment]
All AC's function as they should- Thanks @nkan-aot
