### ISSUE TITLE
Contact Applicant - Email Template for Sending Fees

### ISSUE THREAD

**Issue by KaraBeach** [bcgov/foi-flow#2687]
* As an IAO analyst
* I want to select an email template for Sending Fees
* so that I can easily send an email to the applicant  

**Assumptions & Scope**	
What are the assumptions for this story?

IAO will need to send new fee estimates when a request is narrowed, the email failed or the applicant cannot find the email.

Letter templates will continue to be created in AXIS.

What is IN scope?

Only email templates for fees: new fee estimate or outstanding fees.

Email templates will include links for the latest CFR.

Analyst editing the template in a rich text editor

What is NOT in scope?
Content for the email templates.
Applicant Correspondence Log is covered in #2684.
Other email or letter templates.

**Acceptance Criteria**	

**Scenario 1: Email Template for sending Fee Estimate (no deposit or amount has been paid)**
•	GIVEN the IAO analyst is on the Applicant Correspondence Log https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941001462 
•	WHEN the analyst clicks the template drop-down 
•	THEN there will be 1 option: 'Fee Estimate Email,' 

**Scenario 2: Email Template for sending Fee Estimate Email (no deposit or amount has been paid)**
•	GIVEN the IAO analyst is on the Applicant Correspondence Log https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941001462 
•	AND the has opened the template drop-down
•	WHEN the user selects 'Fee Estimate Email'
•	THEN an email fee estimate template will populate in the comment with the Applicants NAME, the Analysts NAME, the Team NAME, the date and time, and a URL link
•	AND the URL link will have the amount owed from the latest CFR Form

**Scenario 3: Edit email Template for sending Fee Estimate Email**
•	GIVEN the IAO analyst is on the Applicant Correspondence Log https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941001462 
•	AND the  analyst has selected a template (e.g., 'Fee Estimate Email')
•	WHEN the clicks into the email body
•	THEN the analyst can edit the email template
•	AND analysts can Bold, Italicize, Underline content
•    AND analysts can put content in bullets or numbered lists

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KaraBeach** [comment]
@m-prodan - For your review - latest CFR for sending fees.

**Comment by lmullane** [comment]
Thanks, @KaraBeach. I have made some edits.

@m-prodan, @arielleandrews, please review.

**Comment by lmullane** [comment]
One question - should the analyst be able to edit the Template content?

**Comment by lmullane** [comment]
Content will be from the design.

**Comment by m-prodan** [comment]
Yes, I think the analyst should have the ability to edit the template content. Perhaps we can add in the assumptions that it will be a RT editor? So it would populate the default text, and analysts can edit as they need to? 

Also just thinking, we may want a "save draft" feature - but it may not be necessary at this point since the letters will still be generated in AXIS for now, since this is just an email function.

**Comment by lmullane** [comment]
As agreed, we will not having editing on the first release of the email template.

**Comment by lmullane** [comment]
Estimate includes rich text editor so analyst can edit the template.

Rich text editor will work the same as comments.

Will write in a separate story and re-estimate.

**Comment by liseandtea** [comment]
Passes QA however there are a couple of concerns with "scenario 2". Specifically:

- WHEN the user selects 'Fee Estimate Email'
- THEN an email fee estimate template will populate in the comment with the Applicants NAME, the Analysts NAME, the Team NAME, the date and time, and a URL link

1) Analysts may find this confusing because the actual applicant data is not displayed in the email template, it shows the field title the data is being drawn from (e.g. {{firstName}}). 
2) These parameters are live and because the email is editable, there is room for analyst error (deletion of all or a portion of a required field).
