### ISSUE TITLE
Change Request from Response to On Hold - Outstanding Fees Due

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2691]
* As an IAO analyst
* I want to change a request with an outstanding fee due (i.e., only a deposit was paid or the actuals are greater than the estimate) from Response to On Hold
* so that I can notify the applicant they must pay the outstanding balance before they can receive their response package

**Assumptions & Scope**	
What are the assumptions for this story?

A request can only be put On Hold from Response if an outstanding balance is due (i.e. the applicant paid a deposit for their processing fees and still owes the remainder or the actual hours were greater than the estimated hours).

An applicant without an email address will be notified of the remaining fee payment following the current process in AXIS.

An applicant with an email address on file will be notified of the fee payment through the new application. They will be able to pay the fee online via PayBC.

File upload in state change modal should allow for multiple files to be uploaded (same as Fee Estimate to CFR)

What is IN scope?

Changing a general request to the On Hold state from Response. 

What is NOT in scope?

Personal requests.

The applicant notification (#2692) and fee payment will be covered in other stories.

Stopping the clock - that is already in place.

**Acceptance Criteria**	

**Scenario 1: On Hold a state option when a remainder is due**
* GIVEN an applicant owes a balance for their processing fees 
* AND the request state in Response
* WHEN the IAO analyst clicks the state dropdown
* THEN  On Hold will be an option  

**Scenario 2: Remainder is due but there is no applicant email on file**
* GIVEN an applicant owes a balance for their processing fees 
* AND the request state in Response
* AND there is no applicant email on file
* WHEN the IAO analyst clicks On Hold in the state dropdown
* THEN a modal will open with the message: "There is no applicant email on file. Please check the box to confirm that you have mailed the applicant a letter before you put this request On Hold."
* AND there will be an empty checkbox
* AND as is now there will be the IAO and ministry assignees
* AND there will be a 'Save Change' and 'Cancel' button - https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922730567
* AND the 'Save Change' button will be disabled

**Scenario 3: Click Checkbox when there is no applicant email on file**
* GIVEN an applicant owes a balance for their processing fees 
* AND the request state in Response
* AND there is no applicant email on file
* AND the analyst is on the  IAO analyst modal with the message: "There is no applicant email on file. Please check the box to confirm that you have mailed the applicant before you put this request On Hold."
* WHEN  the analyst clicks the checkbox
* THEN the checkbox will turn green with a white checkmark - https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922730568
* AND  the 'Save Change' button will turn blue and be active 

 **Scenario 4: Remainder is due and there is an applicant email on file**
* GIVEN an applicant owes a balance for their processing fees 
* AND the request state in Response
* AND there is an applicant email in file
* WHEN the IAO analyst clicks On Hold in the state dropdown
* THEN a modal will open with the message: "Upload the completed Fee Estimate letter to change the state of this request to On Hold. When you change Request #MIN-YEAR-12345 to On Hold
the clock will be stopped and the applicant will automatically be emailed the fee estimate letter"_
* AND there will be a box with an 'Add File' button and a message: "Drag or drop Fee Estimate letter'
* AND there will be a 'Save Change' and 'Cancel' button - 
* AND the 'Save Change' button will be be grey and inactive

**Scenario 5: Add Fee Estimate letter**
* GIVEN the On Hold modal is open
* AND there is an applicant email on file
* WHEN the IAO analyst clicks the 'Add Files' button
* THEN a finder a document folder will open on their machine

**Scenario 6: Upload Fee Estimate letter**
* GIVEN the On Hold modal is open
* AND the IAO analyst has clicked the 'Add Files' button
* WHEN the analyst selects a file and click Open on a valid file type (must be PDF)
* THEN file will appear in the upload box
* AND the 'Save Change' button will be be blue and active

**Scenario 7: Drag Fee Estimate letter**
* GIVEN the On Hold modal is open
* AND the IAO analyst has clicked the 'Add Files' button
* WHEN the analyst drags a valid file type (must be PDF) into the box
THEN file will appear in the upload box
* AND the 'Save Change' button will be be blue and active

**Scenario 8: Save On Hold**
* GIVEN the analyst is on the On Hold modal
* AND the 'Save Change' button is blue and be active
* WHEN the analyst clicks the 'Save Change' button
* THEN the request state will be update to 'On Hold'
* AND the modal will close 
* AND the clock will stop

**Scenario 9: Save correspondence in attachment log**
* GIVEN outstanding fees were due
* WHEN the analyst puts the request On Hold 
* THEN the email and attachments will be saved in the Attachment log

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team's backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@divyav-aot , @m-prodan , @KaraBeach , @arielleandrews , @JHarrietha-AOT  for your review.

The AC follows are previous story on changing to an On Hold state.

**Comment by arielleandrews** [comment]
Thanks for the chance to review @lmullane. I would change this language "GIVEN an applicant has only paid a deposit for their processing fees" to "GIVEN an applicant owes a balance for their processing fees" - there may be cases where the applicant paid the full fee estimate but the actuals were higher and still owes more. Not specifying deposit will account for this possibility

**Comment by lmullane** [comment]
Good point, @arielleandrews. Edit made.

**Comment by divyav-aot** [comment]
@lmullane, In this user story we will show only the "Fee Estimate letter"(which is uploaded in OnHold state) in the attachment. Email will be part of  #2692. Could you please update the scenario accordingly.

**Comment by JHarrietha-AOT** [comment]
Passed UX Assurance

**Comment by m-prodan** [comment]
All scenarios passed - closing ticket - nice work team!
