### ISSUE TITLE
Applicant sent email to pay outstanding fees due

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2692]
* As an applicant
* I want an email to pay my outstanding fees due
* so that I can pay online and receive my response package

**Assumptions & Scope**	
* This story is the email that will be automatically delivered to the applicant upon putting a request 'On Hold,' WHEN a remainders is due, and AND the applicant has an email address included with their request. 
* For the email mailbox - for initial development purposes, we will use: dvptgmarshal@gmail.com 
* When service accounts and new mailboxes are set up, test account will be changed to test_foi.requests@gov.bc.ca, with a separate story to address this.
* When we go to production, we will use a new mailbox, with a separate story to address this? Do we still need to do this?
* This will be a basic version of the email sent to the applicant - and will include the file uploaded as part of the on hold state change.

What is IN scope?
The email that will be generated and sent to the applicant

What is NOT in scope?
Changing the state to 'On Hold' (#2691)
The email template (#2687)
The UI to send the email (#2684, #2694)
Adding attachments (#2698)
The actual payment of the fee itself

**Acceptance Criteria**	

**Scenario 1: Email Sent**
* GIVEN a request has been put On Hold
* WHEN the email is generated
* AND the attachments have been added
* AND the Outstanding Fee Email has been generated
* THEN the email will send to the applicant's email on file.

**Scenario 2: Attachments to email**
* GIVEN a request has been put On Hold from Response due to outstanding fees
* WHEN the email is generated
* THEN the document uploaded during the change of state to on hold will be attached to the email to the applicant.

**Scenario 3: Content of Email**
* GIVEN a request has been put On Hold
* WHEN the email is generated
* THEN the contents of the message will include a hyperlink to pay the outstanding balance

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@divyav-aot , @m-prodan , @KaraBeach , @arielleandrews , @JHarrietha-AOT  for your review.

Once again the AC follows our previous story for sending a fee estimate.

**Comment by lmullane** [comment]
Follows AC #2322

**Comment by divyav-aot** [comment]
@JHarrietha-AOT @m-prodan @arielleandrews - could you please share the template and Subject for the email.

**Comment by m-prodan** [comment]
@divyav-aot 

Template: https://bcgov.sharepoint.com/:w:/t/03521/EXZ5nlLqBHJKpiisMrJi3ZQBdBA2Q5-u0Sskk6XMwGxc4Q?e=JyQnXR

Header and footer of email should follow the design: https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922766192

Subject Line: Your FOI Request [Request ID]

cc: @JHarrietha-AOT @arielleandrews

**Comment by m-prodan** [comment]
I think I had the wrong link for the template - updated it!

**Comment by divyav-aot** [comment]
Thanks @m-prodan

**Comment by divyav-aot** [comment]
@m-prodan @arielleandrews @JHarrietha-AOT - Please confirm the .eml file name and the category for the outstanding email. You can see the filename and category in below screenshot.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/3b9e0bb7-d1e7-40af-bd24-9c2bd2ff54a9)

**Comment by arielleandrews** [comment]
@divyav-aot if you can change to "Fees - Balance Outstanding Sent" for the subject and "Fee Balance Outstanding - Letter" for the badge that would be great!

**Comment by lmullane** [comment]
Thank you, @divyav-aot 

I updated the AC as we will switch emails with #2654

This is done.
