### ISSUE TITLE
Send fee email from the Contact Applicant Log

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2696]
* As an IAO analyst
* I want to send an email to an applicant
* so that I can easily send an email to the applicant  

**Assumptions & Scope**	
What are the assumptions for this story?

IAO will need to send new fee estimates when a request is narrowed, the email failed or the applicant cannot find the email.

Letter templates will continue to be created in AXIS.

What is IN scope?

Fee emails with attachments.

What is NOT in scope?
Emails without a fee template
Email templates for fees( new fee estimate or outstanding fees) are covered in #2687.
Applicant Correspondence Log is covered in #2684.
Other email or letter templates.

**Acceptance Criteria**	

**Scenario 1: Send a fee template email with no attachment **
•	GIVEN the IAO analyst has selected a fee template
•	AND has not added an attachment to the email
•.    WHEN  the IAO analyst clicks the inactive 'Send Email' button
•	THEN no email will be sent

**Scenario 2: Send email with Attachment **
•	GIVEN the IAO analyst has added an attachment to the email
•      WHEN  the IAO analyst clicks the active 'Send Email' button
•      THEN the email with template will be sent to the applicant's email address on file
•	AND a green success toast will show
•	AND the the email with attachments will be saved in the Applicant Correpondence Log
•	AND the the email cannot be deleted

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, @arielleandrews, for your review.

Question - is there a scenario where an analyst would ever send an email without using an email template?

**Comment by lmullane** [comment]
@m-prodan, thanks for the feedback. I have moved the scenarios for attaching a document to a new story (#2698).

**Comment by divyav-aot** [comment]
@m-prodan - How do we handle PAID scenario? Currently, applicant pay in OnHold state. So based on Fee Estimate/Outstanding the state get auto changed to CFR or Response. Now, we can send email to applicant using contact applicant at any state after CFR. what should we do once the applicant is paid in any state other than OnHold? 
cc @sumathi-thirumani-aot

**Comment by divyav-aot** [comment]
@m-prodan @lmullane As we discussed, we are not going to automatically change the state if the applicant paid from a correspondence email. Please note that, this applies to "on hold' state as well. Please let me know if you have any other thoughts.
cc. @sumathi-thirumani-aot

**Comment by KaraBeach** [comment]
@divyav-aot, for **Scenario 1: Send a fee template email with no attachment ** I was able to send to the applicant without adding an attachment.  The "send email" icon was not inactive. Can you confirm?

AC 2- passed.

**Comment by divyav-aot** [comment]
I agree @KaraBeach . I will make the change and let you know.

**Comment by divyav-aot** [comment]
@KaraBeach The changes are pushed to test-marshal. You may continue with the QA.
