### ISSUE TITLE
Recruitment for Redaction Sessions

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#2701]
Title of ticket: Recruitment for Redaction Sessions

#### Description
Recruitment of participants for initial discovery sessions on the IAO redaction process

Timeframe for sessions:
Monday August 29th
Tuesday August 30th (only if we need to, lots of meetings)
Wednesday August 31st
Thursday September 1st 
(OFF Fri Sept 2nd)
(STAT Mon Sept 5th)
Tuesday September 6th
Wednesday September 7th
Thursday September 8th
Friday September 9th (only if we need would like day to put together report out)
(ON VACATION September 12-16)

#### Dependencies
non

#### DOD
- [x] Book as many sessions as we can
- [x] Please send invite to Jacklyns BC Gov & AOT Emails

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan I created this issue to help track the effort for recruitment for redaction sessions. I have outlines days above. (I think we can add Friday August 26th - this friday, was just worried it might be too soon for peoples calendars) Let me know if you have any questions.

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Going to move this into "In Process" as you have sent out emails and we are actively recruiting

**Comment by arielleandrews** [comment]
Tracking responses, availability and scheduling here: https://bcgov.sharepoint.com/:x:/t/03521/EcrmICUwWRhKsfXCZVvQLR4B7cupN-8gYLVTF751XB7YhA

**Comment by JHarrietha-AOT** [comment]
@m-prodan I am going to close this ticket as all of the 1:1 sessions have been booked. Let me know if you have any concerns
