### ISSUE TITLE
Applicant pay outstanding fee 

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2704]
As an applicant
I want to a page with information on the outstanding fees due
so that I can understand what I owe and can pay online and receive my response package

Assumptions & Scope
When the applicant receives the email for outstanding fees and clicks on the URL they will be redirected to this page.

The page will show the deposit paid and the balance owed from the most recent Approved CFR form.

An outstanding fee can happen in the following scenarios:
- The applicant paid a deposit rather than the full fee estimate and owes the balance
- The applicant paid a deposit rather than the full fee estimate and the actual hours were greater or less than the estimated hours
- The applicant paid the full fee estimate and the actual hours were greater than the estimated hours

What is IN scope?
The email that will be generated and sent to the applicant

What is NOT in scope?
Changing the state to 'On Hold' (#2691)
The email template #2687
Sending the mail #2696
The email notification they receive
The actual payment of the fee itself
Refunds will be covered seperately

**Acceptance Criteria**	

**Scenario 1: Outstanding Fee Owed page - deposit paid**
* GIVEN the applicant is on the Outstanding Fee page
* WHEN the applicant has paid a deposit
* AND there has been no change between the estimated and actual hours
* THEN the applicant will see the balance due
* AND the amount of deposit already paid
* AND a note "The outstanding balance must be paid in full before your response package will be released."
* AND a button to 'Process Payment'
new design here 

**Scenario 2: Outstanding Fee Owed page - deposit paid and hours changes**
* GIVEN the applicant is on the Outstanding Fee page
* WHEN the applicant has paid a deposit
* AND there has been a change between the estimated and actual hours
* THEN the applicant will see the balance due
* AND the amount of deposit already paid
* AND the difference between the fee estimate and the actuals
* AND a note "The outstanding balance must be paid in full before your response package will be released."
* AND a button to 'Process Payment'
new design here 

**Scenario 3: Outstanding Fee Owed page - no deposit paid and hours changes**
* GIVEN the applicant is on the Outstanding Fee page
* WHEN the applicant has not paid a deposit
* AND there has been a change between the estimated and actual hours
* THEN the applicant will see the balance due
* AND the difference between the fee estimate and the actuals
* AND a note "The outstanding balance must be paid in full before your response package will be released."
* AND a button to 'Process Payment'
new design here 

**Scenario 4: Activate Pay Full Fee Estimate**
* GIVEN an applicant is paying an Outstanding Fee online
* WHEN they click 'Process Payment'
* THEN they will be directed to PayBC to process the fee amount required
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/921685072

**Scenario 5: Fee Estimate Paid**
* GIVEN an applicant has been directed to PayBC
* WHEN they have successfully completed the payment
* THEN They will be taken to the payment success page
* AND the information included will be the transaction ID number, and a notice that an email will be sent with their receipt

**Scenario 6: Fee Estimate Paid - Email to Applicant**
* GIVEN an applicant has been directed to PayBC
* WHEN they have successfully completed payment
* THEN they will receive an email confirming payment with the receipt attached
**Design for email template in comments - Receipt to be completed by @JHarrietha-AOT **

**Scenario 7: Fee Estimate Paid - Automatic State Change/Notification**
* GIVEN an applicant has been directed to PayBC
* WHEN they have successfully completed payment
* THEN The state of the request will automatically change to Response
* AND the assigned users will get a notification that says: "Applicant has paid the required fee, the response package can now be delivered"

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, we will need a design for this story. 

Assumption is that they do not need a confirmation screen as they do not have an option of what to pay (i.e., must pay the full amount).

cc @arielleandrews @m-prodan @divyav-aot

**Comment by m-prodan** [comment]
Agreed re: no confirmation page - just the balance due. Story looks good - for one of the assumptions:

The applicant paid a deposit rather than the full fee estimate and the actual hours were greater or less than the estimated hours

Might not be necessary, but maybe clarify that if less than estimated, not less than the deposit paid (since refunds are out of scope) - but might be redundant given that refunds are out of scope

**Comment by divyav-aot** [comment]
@JHarrietha-AOT - Please find the design of the form for the outstanding balance.
I hope there is no change in the wording for different scenarios mentioned above.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/c26b348b-b9d2-4c77-a1d5-0a8173bf50fd)

**Comment by divyav-aot** [comment]
@lmullane @m-prodan - does this user story include sending the receipt after the payment?

**Comment by m-prodan** [comment]
Yes we should make sure the applicant receives a receipt for confirmation of pay. Is that covered in a different user story? That should be part of the function of the email being sent to the applicant when payment is successful. I don't see any scenarios for sending the email on successful pay

**Comment by divyav-aot** [comment]
I didn't find any User story for this. I will do as part of this user story then. I will increase the effort to 5.  Hope there is no change in the email content. It will follow the email template of Full payment. Please let me know. 
@m-prodan

**Comment by divyav-aot** [comment]
@m-prodan - looks like some changes are needed for the receipt. 
below is a sample request with estimated is less than the actual hours.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/8bbff79d-3aa1-4513-a273-5a4ab817080e)
Here the receipt email shows Total Amount Paid ($180 = $150 + $30). 
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/f5a063f4-e3f4-487c-aa35-e5e4b9254f9b)
But the receipt is totally wrong. It shows the estimated qty instead of actual qty. Due to this the Total $ is incorrect.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/b55f5bf8-b560-40cc-92a3-0d53c1f3c9a7)

How do you want to proceed with this? should the email and receipt show only the outstanding balance ($30)? Also, the outstanding receipt should show actual hours instead of estimated.
Please review the attachment name as well.

**Comment by divyav-aot** [comment]
Automatic state change to CFR is happening once the outstanding fee is paid. Please let me know if this needs to be revisited.
@m-prodan

**Comment by JHarrietha-AOT** [comment]
@m-prodan Will cover updated content for email. @JHarrietha-AOT will do updated template for receipt

**Comment by divyav-aot** [comment]
Increasing the estimate to 8 to include the new email and receipt template. Also, the automatic state change to response.

**Comment by m-prodan** [comment]
Update to email template can be found here: https://bcgov.sharepoint.com/:w:/t/03521/EcVmpJKXvKBPh__WbeDXcIMBK-MuLYh-321ju3lLIj3TUg?e=Tm9hC6

I will add scenarios to address state change, and email send with receipt attached

**Comment by m-prodan** [comment]
Updated to include the state change/notifications, and email sending with receipt attached. 

Will we need a seperate story for posting the email to the attachments/correspondence log? Or should this also be included here.

**Comment by divyav-aot** [comment]
@lmullane @m-prodan @KaraBeach Please test below scenario as well.
1. Payment link expiry scenarios (state change/paid)
2. Retry payment (declined credit cards)

**Comment by m-prodan** [comment]
@divyav-aot - only problem I am seeing right now is the notification - it is saying that applicant has paid, and to resume gathering. Message for notification should be different - per scenario 7: "Applicant has paid the required fee, the response package can now be delivered"

Moving back to review

**Comment by divyav-aot** [comment]
@m-prodan Scenario1 of #2709 will handle the notification for outstanding fee paid. Is it okay to take out scenario 7 from here and test as part of #2709?

**Comment by m-prodan** [comment]
@divyav-aot - that makes sense, I didn't realize that story had the same scenarios in it. I will remove the scenario and will close this ticket - thanks!
