### ISSUE TITLE
Recruitment for Redaction Group Sessions

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#2705]
Title of ticket: Recruitment for Redaction Group Sessions

#### Description
The goal is to plan a series of group sessions with each of the teams within IAO Processing Teams to provide a platform for all user pain points about the redaction process to be heard 

#### Dependencies
Take guidance from team leads of whether sessions should take place in one large group for there team or split into small groups. Aiming for a max of apprx. 12-15 participants per session to allow space for each persons voice to be heard

#### DOD
- [x] CFD Core Team - Session 1 - Oct 4 - 1PM PST
- [x] CFD Core Team - Session 2 - COMBINED
- [x] CFD Project Team - Session 3 - Tues Sept 20th - 11AM-12PM
- [ ] Social Education - Session 4 - Wed Oct 5th - 11AM-12PM
- [x] Justice Health - Session 5 - Thurs Sept 22th - 10:30-12PM PST
- [ ] Central/Buisness - Session 6 - DATE - TIME
- [x] Resources - Session 7 - Wed Sept 28th - 1:30-2:30

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Going to move this into "In Process" as you have sent out emails and we are actively recruiting

**Comment by arielleandrews** [comment]
Tracking responses, availability and scheduling here: https://bcgov.sharepoint.com/:x:/t/03521/EcrmICUwWRhKsfXCZVvQLR4B7cupN-8gYLVTF751XB7YhA

**Comment by JHarrietha-AOT** [comment]
@m-prodan I just updated the ticket with the list of teams, and I have included the two times for the meetings I have in my calendar so far. And maybe we can update as we schedule the rest for the week of Sept 19-23

**Comment by JHarrietha-AOT** [comment]
Closing ticket all, sessions booked and completed
