### ISSUE TITLE
Notification and Comment - Outstanding Fee Paid and Deposit Paid

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2709]
* As an IAO analyst
* I want an automated notification when the applicant has paid the fee
* so that I know I can release the response package.

* As an IAO analyst ministry coordinator
* I want a comment posted when the applicant has paid the fee
* so that I know what is happening with the request.

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

Scenario 1: Notification - Outstanding Fee Payment

GIVEN an outstanding fee is due
WHEN the outstanding fee has been paid
THEN the assigned IAO users will received a notification saying "Applicant has paid outstanding fee. Response package can be released.

Scenario 2: System Generated comment

GIVEN an outstanding fee is due
WHEN an outstanding fee has been paid
THEN a system generated comment will be posted "Applicant has paid outstanding fee. Response package can be released."

Scenario 3: Notification - Deposit Payment

GIVEN a fee estimate is due
WHEN a deposit has been paid
THEN the assigned IAO users will received a notification saying "Applicant has paid a deposit.

Scenario 4: System Generated comment - Deposit Paid

GIVEN a fee estimate is due
WHEN a deposit has been paid
THEN a system generated comment will be posted "Applicant has paid deposit."

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
As discussed, update story to include scenarios for when an applicant pays a deposit rather than the full fee estimate.

**Comment by lmullane** [comment]
@KaraBeach, are you still testing this ticket?

**Comment by m-prodan** [comment]
@lmullane I know this story looks like it works based on the demos and fee work I've been doing - I will write up/complete the testing documentation, and should close the ticket today

**Comment by m-prodan** [comment]
All scenarios passed - QA Complete
