### ISSUE TITLE
Push recent releases to Staging environment

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#2710]
**Push recent releases to Staging environment**

#### Description
Subsequent releases need to be deployed to the Staging environment for upcoming training

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by m-prodan** [comment]
Looks to be all there and working as expected - one thing I noticed though, I think it is still connected to the old AXIS 10.3? I saw the banner flag on all requests from the IAO side that the system could not connect to AXIS, is that the case @aparna-aot ?

**Comment by m-prodan** [comment]
I think it might actually be related to the password change of APITEST per Abin's note in teams - im seeing the same issue in regular test

**Comment by aparna-aot** [comment]
@m-prodan Yeah. I will confirm with @abin-aot and update it here.

**Comment by aparna-aot** [comment]
@m-prodan The banner issue was indeed due to the password change of APITEST.

**Comment by m-prodan** [comment]
Password update to the test service account appears to have resolved the issue, just checked now and all is fine. Closing this ticket - everything else appears in staging now. Thanks!

**Comment by m-prodan** [comment]
Password update to the test service account appears to have resolved the issue, just checked now and all is fine. Closing this ticket - everything else appears in staging now. Thanks!
