### ISSUE TITLE
Save applicant correspondence in Contact Applicant Log

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2722]
* As an IAO user
* I want correspondence sent to the applicant posted on the Contact Applicant log
* so that I find all applicant correspondence in one place

**Assumptions & Scope**	
This story requires the need for the emails sent to the applicant  during a state change or directly from the contact applicant log to be retained and accessible by IAO. This is required should there ever be a complaint or other issue raised by the applicant.

All correspondence sent to the applicant including attachments will ONLY be saved in the Contact Applicant Log.

The Attachment Log will be for attachments that are not sent to the applicant.

Attachments sent to applicants will still be saved in the Contact Applicant Log.

What is IN scope?

Saving these records to the Contact Applicant log

Viewing the attached PDFs in the browser.

Downloading the attached PDFs

Removing the emails and attachments sent to the applicant from the attachment log. #2543

What is NOT in scope?

Bulk downloads

Searching Contact Applicant Log.

**Acceptance Criteria**	

**Scenario 1: Fee Estimate Notification Sent**
* GIVEN an applicant has been sent an email from the system (e.g., notice of a fee estimate)
* WHEN this job has been done successfully
* THEN the correspondence will be posted as a comment in the Contact Applicant log
* AND the email will be converted and saved as a PDF
* AND any email attachments will be saved and posted with the copy of the email
* AND will be titled with the email subject heading (e.g. 'Fees - Estimate Sent' for when a request is put 'On Hold')
* AND the date and the time the email was sent will be posted as part of the correspondence
* AND correspondence sent will be posted from newest to oldest (most recent on top)
* AND the username who sent the email will be posted as part of the correspondence
* AND what was sent to the applicant should not be able to be deleted or edited

**Scenario 2: Download correspondence**
* GIVEN correspondence (i.e. the email) has been sent to the applicant
* AND posted on the Contact Applicant Log
* WHEN the IAO analyst clicks the title of the correspondence
* THEN the correspondence and attachments will download as a zip file

**Scenario 3:  'View' Attachments **
* GIVEN the user is on the correspondence log
* WHEN they click on the title of an attachment
* THEN the a display of the attachment in PDF will open in a new browser tab

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941001462

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by abin-aot** [comment]
As per the discussion on Refinement, Application correspondence emails (eml) will not be listed under attachment log, rather there will be line item on Correspondence log for .eml(NOT entire rich text) , not delete and on download(ellipsis) , we should be able to download exact .eml file for IAO. This is only for .eml file

**Comment by lmullane** [comment]
@abin-aot, @m-prodan, @JHarrietha-AOT, please review and comment.

Note, I believe a separate ellipsis is required for each email sent and attachment. The reason is then the user can view each PDF in the browser. The downside is that they cannot download the entire correspondence (email and related attachments at one time).  But we can solve this with an Export All at the top of the Log in a separate story. 

Let me know if you disagree with this approach?

**Comment by m-prodan** [comment]
@JHarrietha-AOT to add design

**Comment by nkan-aot** [comment]
as discussed system generated emails will be saved and displayed in the same way as user sent emails. If a message is downloaded, it will be converted to pdf then zipped along with any attachments

**Comment by m-prodan** [comment]
Note: update AC to be consistent with how we handle emails

**Comment by KaraBeach** [comment]
@nkan-aot - all ACs passed
