### ISSUE TITLE
Divisional Tracking - Spreadsheet Filter - Arts & Culture

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2723]
**Describe the bug in current situation**
Economy Sector Users were using the division filters, and found that not all requests were being pulled on the excel sheet.

As an example - TAC-2022-20722 does have a divisional assignment with "Arts and Culture" - when you select them as a division filter, the request does not get pulled.  It is possible that there are other divisions exhibiting this behaviour and it hasn't yet been caught

**Link bug to the User Story**

**Impact of this bug**
Will impact quality/accuracy of reports - user may no longer trust the tool. Currently this impacts a small number of users, but if is a bigger issue may eventually impact all. 

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Use PROD environment

**Steps to Reproduce**
1. Go to the Combined ECON Dashboard
2. Click on Divisional Filter for Arts and Culture and Apply
3. Scroll down to Spreadsheet
4. TAC-2022-20722 is not displayed, despite having an assignment to that division

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN a user is on the divisional tracking dashboard
WHEN they select a division
THEN any request assigned to that division will be filtered to in the dashboard subject to any other filters applied

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nkan-aot** [comment]
Matt to confirm whether they use excel or redash more often, if they want to keep division info in the combined dashboard. Will have new user session + task to create new division dashboard

**Comment by m-prodan** [comment]
@nkan-aot - the divisional stage filter is working great - there's just one thing I noticed.

For the ECON sector dashboard, when I filter to "Minister's Office" - I get the Minister's Office requests... but it seems to also pull requests that DONT have Minister's Office, but have Assistant Deputy Minister's Office, or Deputy Minister's Office... I assume the "Minister's Office" string is pulling those for that reason.

I assume it would have the same issue with EDUC - but I note I can't select Minister's Office - presumably because there are no requests that have been assigned to the Minister's office - is that right? 

Can that be fixed before I close this? Thanks!

**Comment by nkan-aot** [comment]
@m-prodan hey yes you are correct, that is why extra requests are being pulled, and also why there is no Minister's Office option for EDU. I've updated the query to correct this, please take a look when you get a chance

**Comment by m-prodan** [comment]
Appears to be working as expected - thanks @nkan-aot as always!
