### ISSUE TITLE
Request Queue - Extension Count

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2727]
**Describe the bug in current situation**
A user reported an issue where it appears that when duplicate extension comments are posted from repetitive syncs, the  number of extensions displayed on the queue erroneously increases. 

**Link bug to the User Story**

**Impact of this bug**
Moderate - IAO users will have an inaccurate at a glance-look at number of extensions on affected files

**Chance of Occurring (high/medium/low/very low)**
medium - low
Behaviour is easy to replicate, but will only occur when there is a repetitive sync issue

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Synced FOI request (any environment) with the persistent axis sync issue (ie: request in AXIS does not have a Request for Documents created). Request must have at least 1 extension synced

**Steps to Reproduce**
1. Go to a synced request that has the persistent sync banner issue, and at least 1 extension in AXIS
2. Click on sync and save
3. Repeat step 2, multiple times
4. Number of extensions should remain constant in request itself
5. Go back to queue screen, find request
4. See # of extensions to be much higher

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN a request has any number of extensions applied to it
WHEN a processing team user sees that request in the queue
THEN the row should include the actual number of extensions

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

Banner from test file showing 2 extensions (correct value)
![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/59db5544-7fca-42ee-bd8c-c2779386207b)

View from User queue for same request:

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/5948ad94-7a9b-45b4-8d37-f99a841dcdd4)

**Comment by aparna-aot** [comment]
@m-prodan I have checked this issue and it seems like this is not related to the persistent sync banner issue. This is due to an issue in the query for dashboard extension count. I will fix this as well in the current sprint with #1845. 
In addition to this, We have found out a related issue #2737, which should be fixed as well. Once fixing #1845 and #2727 I can take up #2737.

**Comment by aparna-aot** [comment]
Same issue was with advanced search as well. So please include advanced search while testing. Thanks

**Comment by lmullane** [comment]
Thanks for discovering and fixing the bug, @aparna-aot
