### ISSUE TITLE
Design Updates - Payment Release

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#2733]
Title of ticket: Design Updates - Payment Release

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] New design for email template to Applicant to cover successful payment of an outstanding fee
- [x] New design for receipt template to cover successful payment of outstanding fees that covers these scenarios: deposit paid, actuals were far greater than estimated so second deposit paid, balance paid
- [x] New design recording that fee has bee waived and the amount waived (rare that a whole fee is waived)
- [x] New design recording that a refund has been issued and the amount
- [x] Reason for adding new CFR Form

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan Just wanted to ask before I estimate do we have content for these email? Like do we need designs when the emails should all be looking the same with the header and footer we have now, shouldn't we just need the content?

**Comment by lmullane** [comment]
@JHarrietha-AOT , adding a couple of designs to this ticket:-

Please re-estimate if needed.

@abin-aot, asked it there was anything else needed, and on reflection the answer is yes. For discussion at standup.

**Comment by JHarrietha-AOT** [comment]
#2743 - design update for how title will look

**Comment by JHarrietha-AOT** [comment]
@m-prodan Can you add email content for first one

**Comment by JHarrietha-AOT** [comment]
Design - Reasons for Creating New CFR Form. I don't have list of reasons but I have added where the dropdown would be in the modal. So @m-prodan @lmullane you could start writing the ticket and Matt can just add the list of options to the ticket - https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/951726238

**Comment by JHarrietha-AOT** [comment]
Design - Updated CFR Form with updated spots for Amount Fee Waived and Amount Refunded: https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/951726231

**Comment by JHarrietha-AOT** [comment]
@m-prodan Wanted to see if you think changing the bottom section of the receipt to these three new ones would address the above issues. Let me know what you think ![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/9f521918-7205-4fe4-8c8d-55646a616231)

**Comment by JHarrietha-AOT** [comment]
Added scope to this ticket design for liking/viewing comment
