### ISSUE TITLE
Preview Email before sending - Applicant Correspondence  

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2735]
This is the placeholder for Previewing Email before sending it.

* As an IAO analyst
* I want a preview of an email going to an applicant 
* so that I can ensure the information is correct

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?
Preview of email.

What is NOT in scope?

Editing the email. Handled in #2687
Sending the email (#2696)
Posting the email on the Contact Applicant Log (#2722)

**Acceptance Criteria**	

**Scenario 1: Preview and Send Email**
* GIVEN an analyst has clicked "Add New Correspondence"
* AND the analyst has entered content (e.g. selected a template)
* WHEN the analyst clicks the active "Preview and Send Email" button
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941001462
* THEN a modal will open with a preview of what will be sent to the applicant
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941001462
* AND the content will not be editable
* AND the attachments will be listed
* AND there will be a 'Send Email" and "Cancel" button

**Scenario 2: Cancel Send**
* GIVEN  the analyst is on the Preview email modal
* WHEN the analyst clicks "Cancel"
* THEN the email will not be sent
* AND the modal will close
* AND the analyst will remain on the Contact Applicant Log
* AND the draft email will be there with an active "Preview and Send" button

**Scenario 3: Save Email message**
* GIVEN  the analyst is on the Preview email modal
* WHEN the analyst clicks "Send Email"
* THEN the email will be sent - Technically will be saved in DB using API endpoints, Email sending is part of #2696 
* AND the modal will close
* AND the analyst will remain on the Contact Applicant Log

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by JHarrietha-AOT** [comment]
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941001461

**Comment by lmullane** [comment]
@JHarrietha-AOT, @abin-aot, let me know if this covers what we discussed?

We can review during sprint planning tomorrow.

**Comment by m-prodan** [comment]
Passes all scenarios - however, I have found a bug while testing. It may not be related to this work, so I will write up a seperate bug ticket.
