### ISSUE TITLE
View number of CFR Forms

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2743]
* As an IAO analyst or ministry coordinator
* I want to see the number and version of CFR forms
* so that I know how many forms have been approved for a request

**Assumptions & Scope**	
What are the assumptions for this story?

Users will want to see how many forms have been approved, consistent with how we show number of attachments or comments.

Number will appear similar to how it looks for comments and attachments.

What is IN scope?

Users should not need to go to CFR form history to know what version of the form they are on.

List the number of CFR Forms approved in the left navigation bar.

State the version number on the CFR Form page so users can quickly understand what version they are seeing and match it to the CFR Request History.

What is NOT in scope?
CFR Form history
Editing the form

**Acceptance Criteria**	

**Scenario 1: Number of approved CFR Forms in left navigation**
* GIVEN an IAO analyst or ministry coordinator is on any view (request, comments, attachments, CFR Form)
* WHEN one or more CFR Forms have been approved
* THEN the total number of approved forms will be listed next to the CFR Form heading in the left navigation bar in brackets: (1), (2), etc.

**Scenario 2: Version at top of approved CFR Form**
* GIVEN an IAO analyst or ministry coordinator is on the CFR Form
* WHEN the CFR form has been Approved
* THEN CFR Form - Version X will be displayed at the top of the view
insert design 

**Scenario 3: Version at top of saved but not approved CFR Form**
* GIVEN an IAO analyst or ministry coordinator is on the CFR Form
* WHEN the CFR form has been saved but not yet Approved
* THEN CFR Form - Draft will be displayed at the top of the view
insert design 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, @m-prodan, @arielleandrews 

I have written this story to make it easier for a user to get oriented regarding CFR Forms for a request. 

Please review and comment.

cc @abin-aot , @nkan-aot

**Comment by JHarrietha-AOT** [comment]
@nkan-aot Just for your reference - https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/951726233

**Comment by nkan-aot** [comment]
awesome, thanks!

**Comment by lmullane** [comment]
This is complete as well. Thank you, @aparna-aot!
