### ISSUE TITLE
Extension comments are generated even if axis updates for fields other than extensions are synced up

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#2751]
**Describe the bug in current situation**
Extension comments are generated even if some other fields updates (other than extensions) from axis are synced up.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to any request with extensions synced up.
2. Update any of the fields other than extensions in axis or FOI.
3. Sync the request.
4. Go to comments tab and see

**Actual/ observed behaviour/ results**
System generated comments for extensions are getting posted.

**Expected behaviour**
Only if extensions are synced, the comments should be generated.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/c57d8027-e7be-4a2d-a1d0-cf319fb9fa99)

![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/bb28fbfd-718c-466b-9f84-bffc29f88e99)

**Comment by lmullane** [comment]
Working as expected. Thanks, @aparna-aot
