### ISSUE TITLE
Duplicate comments getting generated while syncing extensions from Axis

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#2759]
**Describe the bug in current situation**
While syncing extensions from axis, duplicate comments are getting generated.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to any request with extensions in axis.
2. Sync up the request.
3. Comments will be generated for the synced up extensions.
4. Add 1 more extension in axis and sync again.
5.Go to comments tab and See
OR
1. Go to any request with extensions in axis.
2. Sync up the request.
3. Comments will be generated for the synced up extensions.
4. Delete 1 of the synced extensions from FOI Request.
5. Again sync up the extensions.
6.Go to comments tab and See

**Actual/ observed behaviour/ results**
Duplicated extension comments will be generated for already synced extensions.

**Expected behaviour**
Whenever extensions are synced up, comments should be generated only for the newly synced up axis extensions and not for the already synced extensions.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.![screengrab.png]
![scrn.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/fa270af5-8be6-45a1-9313-34c11b62ff10)

**Comment by aparna-aot** [comment]
From now on extension comments will only be generated for each of the extensions being synced & no duplicates. Also if any extension are added manually in FOI system and then extensions are synced over from axis, comments will be generated for the extensions that gets deleted as well.

**Comment by lmullane** [comment]
Thanks, @aparna-aot
