### ISSUE TITLE
Fee Refund Amount

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2769]
* As an IAO analyst
* I want to be able to mark when a refund has been requested to CAS
* so that I can update the amount owed and retain a record of the refund

**Assumptions & Scope**	
What are the assumptions for this story?

Only IAO can update the Refund Amount. 

Refund Amount cannot be greater than amount paid.

Refunds from CAS our a manual process that requires an email be sent to CAS requesting the refund. CAS does not let us know that the refund has been issued to the applicant.

Other than the use of comments to discuss the refund with the ministry, the refund process will be handled outside the system. This includes approvals and emails to CAS.

What is IN scope?

Recording the refund amount. 

Only an IAO analyst can submit a refund and edit the field.

What is NOT in scope?

Recording the fee waiver amount.

**Acceptance Criteria**	

**Scenario 1: Refund amount field - ministry coordinator**
* GIVEN a ministry coordinator is on a request
* WHEN they click on the CFR form
* AND the form is in any status (e.g. Clarification, Approved, etc.,)
* THEN they will see a field for 'Refund Amount' under balance remaining:
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/951726231
* AND the field will be greyed out an uneditable

**Scenario 2: Refund amount field - IAO analyst**
* GIVEN an IAO analyst is on a request
* WHEN they click on the CFR form
* AND the form is Approved
* AND the request is in any state
* THEN they will see a field for 'Refund Amount' under balance remaining:
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/951726231
* AND the field will be editable

**Scenario 3: Enter 'Refund Amount**
* GIVEN an IAO analyst is the Approved CFR form
* WHEN the analyst enters an amount in the Refund Amount field that does not exceed what the applicant has paid
* THEN the save button will be activated

**Scenario 4: Save 'Refund Amount**
* GIVEN an IAO analyst is the Approved CFR form
* AND they have entered a Refund Amount
* WHEN they click the 'Save' button 
* THEN the 'Refund Amount' will be saved on the form
* AND the CFR version history will be updated with the Refund Amount

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, question for you - are refunds both in whole or in part?

**Comment by lmullane** [comment]
Thanks for confirming refunds can be partial, @m-prodan 

As discussed at standup, for financial audits we need a system generated comment to show who made the refund. That will be captured in a different story.

**Comment by aparna-aot** [comment]
@m-prodan @lmullane I have a query regarding the balance remaining calculation. What should be the balance remaining value, If both fee waiver amount and refund amount is present for a CFR Form ?
Also need to add an additional AC covering both the fields in the CFR Form History.

**Comment by m-prodan** [comment]
Updated this scenario @aparna-aot 

Loren - Aparna showed me an issue with having the refund update the balance owing field, as originally written. There is a possibility that we do a partial fee waiver, and may later have to refund what was paid. This can give the balance owing a negative figure and would be confusing. I said we will leave the refund amount as just a display, and not have it impact the balance then.

I will keep the assumption though, that the refund amount entered, cannot exceed the amount paid.

**Comment by lmullane** [comment]
I have updated the AC to reflect that the refund amount cannot exceed the amount paid and that the refund should also appear on the CFR form history.

**Comment by lmullane** [comment]
Scenario 2 did not pass as I could not edit the refund field in 'any state' but in this case the AC is likely wrong. @m-prodan, could you confirm that the refund field should not be editable in states such as CFR, Fee Estimate or Closed?

**Comment by lmullane** [comment]
Hmmm...looks like a bug where the amount is not calculating correctly. I will write up a bug ticket:

![Screen Shot 2022-09-23 at 4.54.57 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/edd8f5df-ff61-4de1-b805-51ef2ec1a4bb)

**Comment by lmullane** [comment]
Possible bug. Amount should be zero, but when I have added Actual Hours that are identical to the Estimated Hours the balance remaining and actual total are no zero.

![Screen Shot 2022-09-23 at 4.59.57 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/1f44aa99-f678-4971-ab96-a4cb6d37cf2c)
