### ISSUE TITLE
Select reason for new CFR Form

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2770]
* As a ministry coordinator (pilot ministry)
* I want be able to record why a new CFR form was required
* so that I can have a record of why the change was needed

**Assumptions & Scope**	
What are the assumptions for this story?

Analysts need to record a reason why a new CFR form was required. @m-prodan to provide the reasons.

Reasons will include:
* Narrowed Request
* Revised Fee Estimate

What is IN scope?

Only the dropdown menu  in the confirmation modal for the reason a new CFR Form is created.

What is NOT in scope?

Most of the modal functionality for confirmation is covered in. #2652

**Acceptance Criteria**	

"**Scenario 1: Create New CFR Fee Estimate Form**
•	GIVEN a a coordinator has clicked on the 'Create New Fee Estimate' button 
•	WHEN the coordinator is on the new Fee Estimate Form
•	THEN there will be a dropdown to select the reason for the new CFR: Narrowed Request, Revised Fee Estimate
•	AND selecting a reason will be mandatory to Save the form

**Scenario 2: No reason selected**
•	GIVEN the coordinator is on new Fee Estimate form
•	WHEN no reason has been selected
•	THEN the Save button will be grey and inactive

**Scenario 2: View reasons**
•	GIVEN the coordinator is on the new Fee Estimate form
•	WHEN the coordinator clicks on the 'Select reason for Creating a New CFR Form'
•	THEN a drop down will open with a list of reasons: Narrowed Request, Revised Fee Estimate

**Scenario 4: Reason selected**
•	GIVEN the coordinator has clicked on the dropdown to select a reason
•	WHEN the coordinator selects a reason
•	THEN the 'Save' button will become blue and active
•	AND the drop down will close 
•	AND the reason selected will be displayed (e.g. Narrowed Request) and editable

**Scenario 5: Save Reason**
•	GIVEN the coordinator is on the new CFR Form
•	AND the Save button is blue and active
•	WHEN the coordinator clicks the 'Save' button 
•	THEN the reason selected will be saved
•	AND the reason selected will appear on the CFR form

**Scenario 6: Tooltip for reason drop down**
•	GIVEN the coordinator is on the new CFR Form
•	WHEN the coordinator clicks the the tooltip on the dropdown menu
•	THEN a tooltip will open with an explanation of the difference between Narrowed Request and Revised Fee Estimate

Tooltip Content:
"Select 'Narrowed Request' when the applicant has narrowed their request. Select 'Revised Fee Estimate' when the request has not been narrowed but the estimated hours have changed."

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/951726238

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, tagging you to provide reasons for the dropdown menu.

Once a new form is created and a reason selected, should the analyst be able to edit the Reason (i.e., they made a mistake)? I assume yes.

**Comment by m-prodan** [comment]
Added the reasons to assumptions:
- Revised Description
- Revised Fee Estimate

Those are really the only 2 scenarios we would need a new CFR form to update. We could add an "other" but I'm really not sure what other reason we'd have. Maybe a failsafe for a third option we haven't contemplated? @lmullane

**Comment by lmullane** [comment]
Thanks, @m-prodan!

**Comment by lmullane** [comment]
As discussed, select reason drop down should be on the CFR form not in the modal. 

The user will need to select the reason before they can save the new CFR form.

**Comment by m-prodan** [comment]
@JHarrietha-AOT - will need a design update, we can chat when you are back

**Comment by aparna-aot** [comment]
@JHarrietha-AOT Can you add the design here?

**Comment by JHarrietha-AOT** [comment]
@aparna-aot link to design has been added above. This is the modal that will appear when a user clicks on New CFR Form. Let me know if you have any questions

**Comment by aparna-aot** [comment]
Sure. Thanks @JHarrietha-AOT

**Comment by aparna-aot** [comment]
@m-prodan @lmullane One more AC needs to be added regarding the display of  Reason in the CFR Form History. 
Had a discussion with @JHarrietha-AOT and decided to show the reason on the top bar like :  "CFR Form - Version 2 - REASON". 
Thoughts?

**Comment by lmullane** [comment]
All AC have passed. Thanks, @aparna-aot!
