### ISSUE TITLE
Fee Waiver Amount

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2772]
* As an IAO analyst
* I want a field to enter a fee waiver amount 
* so that I can update the balance owing

**Assumptions & Scope**	
What are the assumptions for this story?

Fee Waiver Amount cannot be greater than the Total Amount Due. Possible that an applicant may pay a deposit under protest, and then get a fee waiver that results in a refund the deposit.

Only IAO can update the fee waiver amount. 

Fee waivers only occur in a minority of pilot ministry requests.

Fee waivers are usually just for part of the processing fee.

The form for fee waivers will be created in AXIS and uploaded to the Attachment Log.

IAO will need to go to the Contact Applicant Log and then send correspondence to the applicant for the revised fee.

What is IN scope?

Capturing the Fee Waiver amount in the system.

What is NOT in scope?

The fee waiver form with approvals.

**Acceptance Criteria**	

**Scenario 1: Fee Waiver amount field - ministry coordinator**
* GIVEN a ministry coordinator is on a request
* WHEN they click on the CFR form
* AND the form is in any status (e.g. Clarification, Approved, etc.,)
* THEN they will see a field for 'Fee Waiver Amount' under 'Amount Paid':
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/951726231
* AND the field will be greyed out an uneditable

**Scenario 2: Fee Waiver amount field  'On Hold' and 'Approved'- IAO analyst**
* GIVEN an IAO analyst is on a request
* WHEN they click on the CFR form
* AND the form is Approved
* AND the request is 'On Hold'
* THEN they will see a field for 'Fee Waiver Amount' under balance remaining:
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/951726231
* AND the field will be editable

**Scenario 3: Fee Waiver amount field not on 'On Hold' and 'Approved'- IAO analyst**
* GIVEN an IAO analyst is on a request
* WHEN they click on the CFR form
* AND the form is in any status but Approved
* AND the request is  not'On Hold'
* THEN they will see a field for 'Fee Waiver Amount' under balance remaining:
https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/951726231
* AND the field will NOT be editable

**Scenario 4: Enter 'Fee Waiver Amount**
* GIVEN an IAO analyst is the Approved CFR form
* AND the request is 'On Hold'
* WHEN enter an amount in the Fee Waiver Amount field
* THEN the Balance Remaining field will be updated
* AND the 'Fee Waiver Amount' cannot be greater than the 'Total Amount Due'

**Scenario 5: Save 'Fee Waiver Amount**
* GIVEN an IAO analyst is the Approved CFR form
* AND they have entered a Fee Waiver Amount
* WHEN they click the 'Save' button 
* THEN the 'Fee Waiver Amount' will be saved on the form
* AND the saved 'Fee Waiver Amount' will be saved on the CFR version history

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
IAO should be able to edit in the Approved status but only when it is in an 'On Hold' state.

For financial audits, need a system generated comment to show who made the change.

**Comment by aparna-aot** [comment]
@m-prodan @lmullane  Just to confirm, Is it ok for balance remaining to be a negative value? If an user pays full amount (say $300) and then a fee waiver is recorded as $100 then the balance remaining will be -$100.

**Comment by m-prodan** [comment]
Yes - that would signal for the FOI analyst that a refund is owed in that particular circumstance.

**Comment by lmullane** [comment]
Updated AC to include that the fee waiver amount is saved on the CFR Form history and that the Fee Waiver Amount cannot be greater than the Total Amount Due.

**Comment by lmullane** [comment]
Great work, @aparna-aot
