### ISSUE TITLE
Disable IMAP Email Service Code base from Marshal's

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2775]
Title of ticket: 

#### Description
This ticket is to disable all code flow related with IMAP / or reading emails from inbox, since we were unable to find the IMAP service from ICIO or using summer.gov.bc.ca IMAP is not working. So , team decided to disable the code related with IMAP/reading emails for failure etc.

#### Dependencies
Are there any dependencies? 

#### DOD
- [ ] Make sure all IMAP related code bases are disabled / commented- NOT REMOVED
- [ ] confirm the functionality, clarify gaps if any.
- [ ] 
- [ ] 
- [ ]

**Comment by m-prodan** [comment]
For Testing/QA Purposes - Test failure scenarios to confirm they aren't being added to attachments
and Happy path fee payment email scenarios - wait for email (GOV) change to test this to avoid duplication.

**Comment by m-prodan** [comment]
All good - failure scenarios aren't being written and new email appears to be working as expected.
