### ISSUE TITLE
Gathering Records - Rank 1 Deduplication

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2777]
## Description:	
- Short Description of the needed Epic in the below format

* As a ministry coordinator
* I want to bulk upload records and have them deduplicated
* so that I can provide the responsive records for an FOI request

* What are the most critical features being built as part of this Epic

- Batch upload of records into Object Storage
- Deduplication of records

* Expected Outcome – Justification why this Feature must be built, what is expected value and justification for priority.

Save LAN storage costs.
Reduce manual time moving records from LAN into system and manual step in Intella.
----
**Sizing**

* T-shirt size: 

 [ ] S
 [ ] M
 [ ] L
 [ ] XL

(S=1-2 Sprints, M=2-3 Sprints, L=4-5 Sprints, XL=not sure, probably more than 5 Sprints). 

* *Risks and Assumptions**

1. [ ] What are assumptions?
2. [ ] What are the risks?
3. [ ] Have we done an RFC on a technical approach?
4. [ ] Are the dependencies (technical, business, regulatory/policy) known?
5. [ ] Has work on this Epic been prioritized with key stakeholders?

**Comment by lmullane** [comment]
Does not include:

Number of pages
Number of pages deleted
Rank 2 - remove duplicate content

Rank 2 will be another release.

**Comment by KyEggleston** [comment]
Closing this epic, as it was released in 7.0
