### ISSUE TITLE
Bulk upload responsive records

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2779]
* As a Ministry coordinator
* I want to bulk upload records for a request
* so that I can provide the records responsive to an FOI request

**Assumptions & Scope**	
Capture file created data for deduplication.

Uploads will be done by ministry coordinators; but IAO could if needed.

Ministry coordinators will be uploading records into the system more than once as divisions will provide records at different times.

Records uploaded should be tagged by division. Ministry coordinators currently keep records from each division in separate folders on their LANs

Records will go directly by the S3 API into the protected c rated Object Storage. No records will be stored a REST in the flow app in OpenShift.

Uploads will have to handle a high file size amounts.

Records can be uploaded and deduped in most request states as at time more records are found after the CFR. Records can be uploaded  and dedupe in any state other than Unopened, Intake in Progress, Open and Closed.

Divisional Stages will be a dependency for records upload as you can only tag divisions for the uploads with divisions that have been added in Divisional Stages.

Batch upload file limit will be 500 MB.

What is in scope?
Bulk upload of records.
Tagging records with a Division.

What is NOT in scope?
Gathering Records Log #2780
Dedupe of records is covered in #2739

System generated comments on the upload.

**Acceptance Criteria**	

**Scenario 1: Gathering Records log**
* GIVEN a ministry coordinator is on the Gathering Records Log
* AND the request is not Closed
* WHEN the user clicks on the 'Upload Records' button
* THEN the upload records modal will open
* AND tags for each division will be displayed
* AND no tag will be selected by default
Similar to this: ![Screen Shot 2022-09-12 at 12.10.20 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/a8c9d775-6cd3-406d-a360-fde2f922172b)

**Scenario 2: Drag and Drop to add files or folders**
* GIVEN you are on the upload records modal
* WHEN you drag and drop file(s) that are less than 500 ?? into the "drag and drop" space
* THEN the file name  or folder name will appear Add Files box

**Scenario 3: Add files/folders using the Add Files Button**
* GIVEN you are on the upload records modal
* WHEN you click on the "Add File" button
* THEN the user will be able to select file(s) from their local machine to add to the upload records modal

**Scenario 4: Adding files from machine**
* GIVEN you are selecting a file from your local machine
* WHEN you open or add a file
* THEN the file name will appear Add Files box

**Scenario 5: Cancel back to Gathering Records Log**
* GIVEN you are on the upload records modal
* AND no files appear in the Add Files box
* WHEN you click on the cancel button
* THEN the modal will close and you will remain on the Gathering Records log

**Scenario 6: Clicking On Cancel Button when Attachments uploaded**
* GIVEN you are on the upload records modal
* AND files appear in the Add Files box
* WHEN the user clicks the 'Cancel' button
* Or closes the modal
* THEN a pop up will ask the user "Are you sure you want to cancel (x) number of attachments will NOT be uploaded"
* AND the options will be "Yes" and "Cancel"

**Scenario 7: Cancel back to Attachment Upload**
•	GIVEN the user has attempted to close the modal with an active attachment, and the pop up has warned the user 
•	WHEN the user clicks on 'Cancel'
•	THEN the window will close and they will remain on the upload records modal, with the attachment still present

**Scenario 8: “Yes” to cancel uploading attached records**
•	GIVEN the user has attempted to close the modal with an active attachment, and the pop up has warned the user 
•	WHEN the user clicks on 'Yes'
•	THEN the window and attachment upload window will close and the uploaded attachment will not be uploaded to the Gathering Records log

**Scenario 9: Add divisional tag to the upload **
* GIVEN the user is on the upload records modal
* WHEN the user select 1 (1 tag maximum) tag for the new uploads: Division A, Division B, etc.
* THEN the tag will turn blue

**Scenario 10: Save uploaded records to the Gathering Records log**
* GIVEN the user is on the upload records modal
* AND the user select 1 (1 tag maximum) tag for the new uploads: Division A, Division B, etc.
* AND the user has uploaded file(s) 
* AND the total file size of the batch is 500MB or less
* WHEN the user clicks the active 'Continue' button
* THEN the modal will close
* AND the file(s) will be uploaded
* AND the file(s) will be displayed from newest to oldest upload
* AND the file(s) will be displayed with the tag selected (e.g. Division A)

**Scenario 11: Ellipsis options on Gathering Records log for files added**
* GIVEN a file has been uploaded to the Gathering Records Log
* WHEN a user clicks on the ellipsis of the file on the log
* THEN the user will see options to: Download, Rename, Delete

**Scenario 12: Batch limit of 500MB exceeded**
* GIVEN the user is on the upload records modal
* AND the user select 1 (1 tag maximum) tag for the new uploads: Division A, Division B, etc.
* AND the user has uploaded file(s) 
* WHEN the total file size of the batch is  greater than 500MB 
* THEN a warning will show "A maximum 500 MB can be uploaded at one time. Please remove some files and upload them separately"...
* AND the 'Continue' button will be disabled.

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Deployment Steps** 
refer to #2780

**Comment by lmullane** [comment]
@abin-aot, what should be the file upload maximum?

**Comment by lmullane** [comment]
Tag shown should only include Divisions added in Divisional Stages.

Decision is to go with uploads and tags from the Gathering Records  rather than an upload from the Divisional Stages as records may be added late in a request when the Gathering Records stage for that division has already occurred and the request is in sign off for example.

Decision is that they will upload individual records and not folders as the folder sub directories could be an issue.

**Comment by lmullane** [comment]
@abin-aot, to confirm largest file sizes for a request with Filewatcher and dev team to make a recommendation on max file upload size.

cc @divyav-aot, @m-prodan

**Comment by lmullane** [comment]
Dev team to do analysis upload of less common file types such as GIS files and audio files. 

GIS sampls can be found on DataBC: https://catalogue.data.gov.bc.ca/datasets

**Comment by m-prodan** [comment]
Note: Replace should not be an option for the ellipsis

**Comment by KyEggleston** [comment]
@sumathi-thirumani-aot  I encountered a bug related to this story. See [Bug # 3152](https://github.com/bcgov/foi-flow/issues/3152). Happy to clarify if needed.

**Comment by KyEggleston** [comment]
@sumathi-thirumani-aot additional items I noticed related to this story, which may not be bugs, but isn't the expected functionality. 

1. The _Records_ tab currently sorts in ascending order, meaning that it sorts files from oldest (at the top) to newest (at the bottom). This appears to be the opposite of what is written in the AC for Scenario 10. The _Records_ tab should display files from newest (at the top) to oldest (at the bottom).

2. Under the _Records_ tab, after clicking the 'Upload Records' button, in the Upload Records modal the 'Add Files' field should read: "Drag and drop attachments, or click Add Files".

3. Under the _Attachments_ tab, after clicking the 'Add Attachment' button, in the Add Attachment modal the 'Add Files' field should read: "Drag and drop attachments, or click Add Files".

**Comment by divyav-aot** [comment]
@nkan-aot - could you please take a look at these issues.

**Comment by KyEggleston** [comment]
> @sumathi-thirumani-aot additional items I noticed related to this story, which may not be bugs, but isn't the expected functionality.
> 
> 1. The _Records_ tab currently sorts in ascending order, meaning that it sorts files from oldest (at the top) to newest (at the bottom). This appears to be the opposite of what is written in the AC for Scenario 10. The _Records_ tab should display files from newest (at the top) to oldest (at the bottom).
> 2. Under the _Records_ tab, after clicking the 'Upload Records' button, in the Upload Records modal the 'Add Files' field should read: "Drag and drop attachments, or click Add Files".
> 3. Under the _Attachments_ tab, after clicking the 'Add Attachment' button, in the Add Attachment modal the 'Add Files' field should read: "Drag and drop attachments, or click Add Files".
> 
> These were tested in TEST-MARSHAL on record # EDI-2022-01234, with user **foiedu@idir** (a ministry coordinator).

After retesting ACs, these three issues are now resolved in TEST-Marshal.

**Comment by lmullane** [comment]
@nkan-aot, in Scenario 1 it states that no tag should be selected by default. 

The challenge of having a tag automatically selected is that a coordinator may upload many records under the wrong divisional tag. And that it will  then be challenging to parse out the right records for harms after the fact.

Is it technically possible to have no default like we do with Advanced Search?

cc @KyEggleston

**Comment by lmullane** [comment]
@nkan-aot, circling back on my question above?

**Comment by nkan-aot** [comment]
@lmullane hey sorry didn't see this the first time it was posted. Yes I tried making the change in local and it is working. Just to confirm, in attachment upload General will continue to be selected by default. Is it okay if we push this to test-marshal along with dedupe status related changes?

**Comment by lmullane** [comment]
No worries, @nkan-aot. 

Yes, in Attachments it will stay with General by default. 

We likely will need to add 'General' to the Records log in the future, but it still would not be selected by default. Some ministries (i.e., MCFD) package the records all together, not by division. They also do not do Harms, so division tagging is less valuable for them. However,  we can worry about that later.

Good to push with the dedupe related changed.

**Comment by lmullane** [comment]
As per discussion with @nkan-aot, will test the no default tag when the other gathering records story is pushed to TEST.

cc @KyEggleston  @liseandtea

**Comment by KyEggleston** [comment]
All ACs pass - however, we will need to revisit the question in [#2780 ](https://github.com/bcgov/foi-flow/issues/2780) regarding the file ordering in the _Attachment_ and _Records_ tab. Need to decide if files uploaded on the same date should be sorted alphabetically by the file name in an ascending manner (i.e., A-Z), or in some other manner. 

Currently, files are sorted alphabetically by file name for files uploaded on the same upload date, but they are sorted in an descending manner (i.e., Z to A). 

![image](https://user-images.githubusercontent.com/117312323/206310783-e244dae7-0237-4627-a01f-fe41465e826d.png)

I've noted this on the QA Master in the notes for this test case, and we can revisit this - but it shouldn't prevent us from moving this to Ready for Prod.

cc: @m-prodan @liseandtea @lmullane
