### ISSUE TITLE
Update File Watcher page in IAO OneNote

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#278]
Title of ticket: 
Update File Watcher page in IAO OneNote

#### Description
Add new information about known limitations to IAO resource

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Include Log Updates, and how they function
- [x] Best practices (delay after creating folder)
- [x] Update to functionality around problematic attachments
- [x] CFR Archive Folder

**Comment by m-prodan** [comment]
Forgot about this card @arielleandrews  :) I've completed this one including the more recent updates to filewatcher, including email attachments in anticipation of the production release on tuesday.
