### ISSUE TITLE
Gathering Records Log

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2780]
* As an ministry coordinator
* I want a Gathering Records log
* so that I can upload and access records for the request

* As an IAO analyst
* I want a Gathering Records log
* so that I can access records for the request

**Assumptions & Scope**	
What are the assumptions for this story?

Only ministry coordinators will upload records in practice but IAO will be able to do so too if required.

Files will be ordered by upload date  (newest to oldest) and then alphabetically by file name if uploaded on the same date.

Search will be client side. 

Keyword search will only search by tag and record's title; the record's content will not be searched.

What is IN scope?
Gathering Records log
Tag filters and search

What is NOT in scope?
Uploading records #2779, including tags
Dedupe records #2739
Export All records

**Acceptance Criteria**	

**Scenario 1: Gathering Records log**
* GIVEN a ministry coordinator or IAO analyst is on a request 
* AND the request is any state other than Unopened, Intake in Progress, Open
* WHEN the coordinator saves at least one division in Divisional Stages
* THEN the there will be a left nav item for Records 

**Scenario 2: Gathering Records log - no files**
* GIVEN a ministry coordinator or IAO analyst clicks the left nav item for Records
* WHEN no files have been previously uploaded
* THEN the Records log will be empty 
* AND there will be button for 'Upload Records'

**Scenario 3: Gathering Records log - files already uploaded**
* GIVEN a ministry coordinator or IAO analyst clicks the left nav item for
* WHEN files have been previously uploaded
* THEN by default the tag filter will be 'All'
* AND the Records log will display all uploaded files from newest upload date to oldest upload date
* AND sorted alphabetically by file name for files uploaded on the same upload date
* AND each file entry will include: the user that uploaded the file, the date/time the file was uploaded, and the title of the attachment

**Scenario 5: Search 'All'**
* GIVEN a ministry coordinator or IAO analyst is on the Records log
* AND the default the tag filter is on 'All'
* WHEN the user enters a keyword into the search bar (e.g. PNG, Call, etc.)
* THEN any record that has that keyword in the record's title will be displayed
* AND the searched records will display from newest upload date to oldest upload date
* AND sorted alphabetically by file name for files uploaded on the same upload date
* AND each file entry will include: the user that uploaded the file, the date/time the file was uploaded, and the title of the attachment

**Scenario 5: Filter by division tag'**
* GIVEN a ministry coordinator or IAO analyst is on the Records log
* AND the default the tag filter is on 'All'
* WHEN the clicks on a division tag (e.g., Deputy Minister's Office)
* THEN the only records with that division tag will be displayed
* AND the filtered records will display from newest upload date to oldest upload date
* AND sorted alphabetically by file name for files uploaded on the same upload date
* AND each file entry will include: the user that uploaded the file, the date/time the file was uploaded, and the title of the attachment

**Scenario 6: Search by keyword and division tag'**
* GIVEN a ministry coordinator or IAO analyst is on the Records log
* AND the records are filtered by a division tag (e.g., Deputy Minister's Office)
* WHEN the user enters a keyword into the search bar (e.g. PNG, Call, etc.)
* THEN the only records with the keyword in the record's title will be displayed
* AND the filtered records will display from newest upload date to oldest upload date
* AND sorted alphabetically by file name for files uploaded on the same upload date
* AND each file entry will include: the user that uploaded the file, the date/time the file was uploaded, and the title of the attachment

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Deployment Steps - Must do before releasing to prod**
- [ ] set env variable in open shift "OSS_S3_ENVIRONMENT" to dev/test/prod
- [ ] add buckets in s3 for each ministry according to the names DocumentPathMapper
- [ ] run the following query for all buckets 
```
update public."DocumentPathMapper" set attributes = '{
         "s3accesskey":"** enter access key **",
         "s3secretkey":"** enter secret key **"
     }' where bucket ilike '** enter bucket name here **%'
```

**Comment by lmullane** [comment]
Tag shown should only include Divisions added in Divisional Stages.

Decision is to go with uploads and tags from the Gathering Records  rather than an upload from the Divisional Stages as records may be added late in a request when the Gathering Records stage for that division has already occurred and the request is in sign off for example.

**Comment by m-prodan** [comment]
Discussion from refinement: Gathering records log - should have accordions set up per division. Open up accordion to show the files. When using the search feature - accordions with relevant records will display number of files that are caught, and when user expands the accordion only the searched files will show.

**Comment by lmullane** [comment]
I will update the AC as discussed.

**Comment by lmullane** [comment]
@divyav-aot , @m-prodan, please review and advise if I have captured the AC as discussed?

@JHarrietha-AOT , we will need designs for this story.

**Comment by divyav-aot** [comment]
looks fine to me @lmullane

**Comment by JHarrietha-AOT** [comment]
@nkan-aot I think I got everything covered, let me know if you have any questions. 

https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/957399281

**Comment by nkan-aot** [comment]
thanks @JHarrietha-AOT this is great!

**Comment by KyEggleston** [comment]
@sumathi-thirumani-aot Two things I noticed for this story:

1. As it relates to the AC for Scenario 3, the total number of files uploaded for each division is not displayed next to the division name in brackets.

![image](https://user-images.githubusercontent.com/117312323/205770514-1f8df282-92cb-4b1a-9cad-c0c295bf0638.png)

2. As it relates to the AC for Scenario 4, files uploaded are not being displayed from newest to oldest based on upload date. Instead, they are ordered oldest to newest. This is the same as what I commented on in [Story # 2779](https://github.com/bcgov/foi-flow/issues/2779). 

These were tested in TEST-MARSHAL on record # EDI-2022-01234, with user **foiedu@idir** (a ministry coordinator).

**Comment by nkan-aot** [comment]
Hey @KyEggleston the reason for #1 is because the design changed during the development so the AC is no longer accurate. We can discuss tmr during standup how to handle. #2 I will fix along with the other issues mentioned in 2779

**Comment by KyEggleston** [comment]
Struck out AC for scenario 3 based on previous comment (but left in ticket for future reference if needed). Will remove from QA master list as well. Will wait for #2 to be resolved before moving ticket to Ready for Prod.

**Comment by KyEggleston** [comment]
Updated AC for Scenario 3 to better clarify current state. Updated in QA Master sheet as well.

**Comment by lmullane** [comment]
@KyEggleston, I updated the AC to remove all reference to accordions.

**Comment by KyEggleston** [comment]
@nkan-aot - one other item I noticed related to Scenario 3 above, which may have occurred when fixing #2. 

The AC states that files should be sorted "...alphabetically by file name for files uploaded on the same upload date...".

Currently, files are sorted alphabetically by file name for files uploaded on the same upload date, but they are sorted in an descending manner (i.e., Z to A). 

![image](https://user-images.githubusercontent.com/117312323/206310783-e244dae7-0237-4627-a01f-fe41465e826d.png)

Instead, files should be sorted alphabetically by file name for files uploaded on the same upload date in an ascending manner (e.g., A - Z), such as the below image: 

![image](https://user-images.githubusercontent.com/117312323/206310512-fc4472cc-8eef-412e-b0ff-e9233f07d22d.png)

This could have been clearer in the AC, so I will update the Scenario 3 AC. 

This was tested in TEST-MARSHAL on record # EDI-2022-01234, with user foiedu@idir (a ministry coordinator).

**Comment by lmullane** [comment]
@KyEggleston , yes, I can confirm that files uploaded on the same date should be sorted alphabetically by the file name in an ascending manner. 

Unclear how these are sorted for attachments given this example where one upload is descending and one ascending:![Screen Shot 2022-12-08 at 2.26.37 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/c61f28d8-7efb-4fe4-9953-ee5adf3f3ed3)

**Comment by lmullane** [comment]
Let's wait until after we meet with Flex Team before we do anything about the ordering. They have insights to share.

Note, I have updated the scenario 1 to reflect when the Records log will appear in the left navigation (i.e. when at least one division is added and saved in divisional stages).

And I will add the search by tag ACs as well to this story.

**Comment by lmullane** [comment]
@JHarrietha-AOT , @m-prodan, @nkan-aot 

There is an inconsistency in how a keyword search works on the Attachment log versus the Records log.  We did not specify how it should work so we can pass this story, but I want to confirm that we want the a keyword search to include the divisional tag?

When you do a Keyword search in the Attachment Log, it will search the Tag as well as the document title. For example:![Screen Shot 2022-12-08 at 2.56.21 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/b60f3e9b-4e37-4e1e-bed4-331c834b84f0)

However, a keyword search on the Records log only searches the record titles, not the divisional tags. For example, this request has a number of records tagged with the DMO:![Screen Shot 2022-12-08 at 2.59.52 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/f36851f6-acc1-4bac-93b9-d2828e32d92f)

But when you search by 'Deputy' you get no results:![Screen Shot 2022-12-08 at 3.00.55 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/398da795-b14d-4fb6-9027-aad2fea115c3)

**Comment by lmullane** [comment]
I will write a ticket to update search in records to match search in attachments.
