### ISSUE TITLE
Fee Estimate Receipt Update - Waiver Amount

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2788]
* As an applicant
* I want to know that my first 3 hours of search time have been waived
* so that I know I am being charged appropriately

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?
Updating text in the receipt to notify applicant that the first 3 hours of search was waived. 

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Waived $ Figure, Locating and Retrieving - 3 hours or more**
* GIVEN an applicant has paid their fee estimate, or outstanding balance
* AND the fee includes locating and retrieving figures greater than or equal to 3 hours
* WHEN the receipt is generated
* THEN the $ waived value for locating and retrieving will show a value of 90.00

**Scenario 2: Waived $ Figure, Locating and Retrieving - Less than 3 hours**
* GIVEN an applicant has paid their fee estimate, or outstanding balance
* AND the fee includes locating and retrieving figures less than  3 hours
* WHEN the receipt is generated
* THEN the $ waived value for locating and retrieving will show a value of 30.00 x the qty 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
From refinement - this ticket will just cover the receipt portion for the auto-waived 3 hours of search. We will create a seperate ticket to display fee waiver amount, if the applicant is granted a partial fee waiver.

**Comment by liseandtea** [comment]
Tested and all values and quantities are calculated and displayed correctly on the receipt.
