### ISSUE TITLE
Follow Up - Redirect Reasons - After Q3 Release

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#279]
Title of ticket: 

#### Description
Follow up for IAO Intake with whether condensed list of redirect reason is working, if any reasons should be added or removed and if there is any other feedback

#### Dependencies
Q3 - release 

#### DOD
- [ ] Follow up with Gitta and Patrick to see how the 6 redirect reasons and other feature is functioning
- [ ] Make updated to UI based off of feedback after Q3 Release

**Comment by mpilchar** [comment]
went in another direction - closing
