### ISSUE TITLE
ReDash - PROD - Performance Issue

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2798]
**Describe the bug in current situation**
The ReDash application appears to be very slow - noticed first at a training session on September 14th.

**Link bug to the User Story**

**Impact of this bug**
Impact: Frustration for users attempting to manipulate reports - long loading times between filters will create significant frustration for our users.

**Chance of Occurring (high/medium/low/very low)**
High - appears to occur with most dashboards

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
ENV: PROD

**Steps to Reproduce**
1. Go to ReDash
2. Click on any dashboard
3. Attempt to refresh, or change filters
4. Note significant loading time (>2 Minutes)

**Actual/ observed behaviour/ results**

**Expected behaviour**
ReDash typically loads results in 10-20 seconds or less, depending on complexity of filters.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nkan-aot** [comment]
based on what we discussed at standup I have put a conservative limit on the past 5 years of data for the received dashboard. We can adjust after feedback from users if they want something different

**Comment by m-prodan** [comment]
Nice work Nick - dashboards are back to being snappy - we'll get feedback on the limitations as I roll out training across leadership. I expect this shouldn't present an issue though. We can always archive the last dashboard when we retire ours, if folks need to go back to 2014. 

cc @lmullane
