### ISSUE TITLE
Divisional Tracking Update - EDU - Communications 

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2821]
* As a Ministry Coordinator
* I want to see when a request is being reviewed by the Communications Office
* so that I don't need to write a comment

**Assumptions & Scope**	
Education tracks requests through their communication offices during sign-off time. This story reflects the need for the app to include this in the tracking. Important to note; however, that this particular division will not have the same actions as other divisions, as the stages will be - "In Review" and "Review Completed"

All other functions related to divisions for this one should be the same - user can delete this new division the same way they would any other. There will be no conditions for when this division is selectable. Divisional tracking updates should continue to post system generated comments under divisional tracking filter, and this new feature should not change that. 

What is IN scope?
Adding a divisional entity with new action drop downs, for Education only
System generated comments

What is NOT in scope?
Other changes to the divisional tracking

**Acceptance Criteria**	

**Scenario 1: Add new Division - Communications**
* GIVEN a Ministry of Education user is on the review request page
* WHEN they activate the division drop down
* THEN in addition to the existing divisions, they will see a new division called "Communications"

**Scenario 2: Select Communications**
* GIVEN a Ministry of Education user has activated the division drop down
* WHEN they select "Communications"
* THEN the drop down will close, and the action drop down bar will appear next to it

**Scenario 3: Communications - Action Drop Down**
* GIVEN a Ministry of Education has selected the Communications Division
* WHEN they activate the action drop down
* THEN they will see the option for "In Review" and "Review Complete"

**Scenario 4: Communications - Select Action**
* GIVEN a Ministry of Education has the actions drop down open for the Communications Division
* WHEN they make a selection
* THEN the drop down will close, and their selection will be made
* AND the save button will be active on the request

**Scenario 5: Communications - Select Action**
* GIVEN a Ministry of Education has selected an Action for the Communications Division
* WHEN they activate save
* THEN the divisional tracking will be saved to the request

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by abin-aot** [comment]
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/9071cb41-60d3-48f1-a38d-49acfb005002)****

**Comment by abin-aot** [comment]
As per Backlog refinement on 7/Nov, We decided to add "Communications" as a regular division and add "in Review", "Review Completed" to divisional stages - WIHTOUT Cascading. So that it is easy to implement. But on Gathering Records, taglist "Communications" need NOT to be shown.

**Comment by KyEggleston** [comment]
All ACs pass, and I added a note on test cases for #2779 (in the Master QA sheet) that on the Gathering Records log, the tag "Communications" does not need to be shown (so we don't miss during a reg test). Closing ticket.
