### ISSUE TITLE
Dedupe Status API into FOI FLOW

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2837]
Title of ticket: 

#### Description
The purpose of this task is to develop Dedupe status API which indicates the full status of deduplication, conversion etc. so that it is ready for review/redaction

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Development of Python Flask API Base framework  - Logging, AUTH, etc. --
- [ ]  GET API  from FOI Dedupe  Data warehouse entities based REQ#, Division or by boundary
- [ ]  Integration with FOI FLOW FE
- [ ]  Unit TEST
- [ ]

**Comment by lmullane** [comment]
Duplicate.
