### ISSUE TITLE
Generic correspondence design

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#284]
Title of ticket: 

#### Description
Generic correspondence to contact an applicant, ministry client, IAO and log the correspondence in a correspondence log.

Include attachment of documents and attachment of letter templates.

#### Dependencies
Only for outbound emails.

Does not include assignment of reviews.

#### DOD
- [x] Side Bar design for Navigation to correspondence - Same Side Bar - Different colours based on stage
- [x] Contact, include/remove attachment send email, correspondence log
- [x] Letter template selection
- [x] Save a draft
- [x] Letter template editing

**Comment by JHarrietha-AOT** [comment]
Based off of Sprint Planning - Aug 4th 

**Need to focus on the idea of having a Colour Coordinated - state based - Side Bar**
This will give the visual difference of having a an unopened request. It will also allow for the option in the side bar to be adjusted based on which state the request is in.

**Comment by JHarrietha-AOT** [comment]
Prototype Update complete and can be viewed here: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932449

Reviewed with team in Design review meeting yesterday prior to closing. All changes discussed then have been made.
