### ISSUE TITLE
"All options of state transition" are disabled - Sporadic Observation

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#2845]
**Describe the bug in current situation**
Sporadically; all the options in the the state transition dropdown is disabled during "Fee Estimate" to "On Hold".
Screenshot for reference
**Link bug to the User Story**

**Impact of this bug**
The reported issue gets resolved upon going back to dashboard and selecting the request again.

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1.  Create new request 
2.  As a ministry user; provide CFR Form & submit for review.
3.  Login as IAO user; navigate to CFR Form and approve and now move to Request tab and expand the state dropdown for transition
4. See error "All options of state transition" are disabled.

**Actual/ observed behaviour/ results**
All available options of state transition are disabled.

**Expected behaviour**
All available options of state transition must be enabled.

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/eabcf2b2-fcb3-4941-b695-1e8d08d60869)

**Comment by m-prodan** [comment]
Can confirm - I have seen this issue crop up as well. Usually refreshing can help, but unclear why it happens.

**Comment by divyav-aot** [comment]
This has been fixed along with fee processing release. hence closing this bug.
