### ISSUE TITLE
Backend - API for Gathering Records Log (#2780, #2779)

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#2857]
DOD
=====

- [x]  Create new endpoint to work on FOI request records supporting CREATE
- [x]  Create new endpoint to work on FOI request records supporting BULK CREATE
- [x]  Create new endpoint to fetch FOI request records
- [x]  Unit Testing

**Comment by sumathi-thirumani-aot** [comment]
GET http://localhost:15000/api/foirecord/1/ministryrequest/1

[{"recordid": 19, "filename": "test-new.pdf", "s3uripath": "/s3/test/3434", "divisionid": 1, "divisionname":
"Minister\u2019s Office", "createdby": "service-account-forms-flow-bpm", "created_at": "2022 Oct 03 | 04:44 AM"},
{"recordid": 20, "filename": "test2.pdf", "s3uripath": "/s3/test/3434", "divisionid": 1, "divisionname":
"Minister\u2019s Office", "createdby": "service-account-forms-flow-bpm", "created_at": "2022 Oct 03 | 04:44 AM"},
{"recordid": 21, "filename": "test.pdf", "s3uripath": "/s3/test/3434", "divisionid": 1, "divisionname": "Minister\u2019s
Office", "createdby": "service-account-forms-flow-bpm", "created_at": "2022 Oct 03 | 06:17 AM"}, {"recordid": 22,
"filename": "test2.pdf", "s3uripath": "/s3/test/3434", "divisionid": 1, "divisionname": "Minister\u2019s Office",
"createdby": "service-account-forms-flow-bpm", "created_at": "2022 Oct 03 | 06:17 AM"}]

**Comment by sumathi-thirumani-aot** [comment]
POST  http://localhost:15000/api/foirecord/1/ministryrequest/1/bulk

{ "records": [{
    "divisionid":1,
    "s3uripath":"/s3/test/3434",
    "filename": "test.pdf"
},
{
    "divisionid":1,
    "s3uripath":"/s3/test/3434",
    "filename": "test2.pdf"
}]
}

Response:
{
    "data": [
        {
            "filename": "test.pdf",
            "recordid": 23
        },
        {
            "filename": "test2.pdf",
            "recordid": 24
        }
    ],
    "message": "Records created",
    "status": true
}

**Comment by sumathi-thirumani-aot** [comment]
POST http://localhost:15000/api/foirecord/1/ministryrequest/1

{
    "divisionid":1,
    "s3uripath":"/s3/test/3434",
    "filename": "test.pdf"
}

Response:
{
    "data": [
        {
            "filename": "test.pdf",
            "recordid": 25
        }
    ],
    "message": "Records created",
    "status": true
}

**Comment by sumathi-thirumani-aot** [comment]
**Changes to decommission endpoint for single entry and support only bulk.**

NEW API : http://localhost:15000/api/foirecord/1/ministryrequest/1

{ "records": [{
    "divisionid":1,
    "s3uripath":"/s3/test/3434",
    "filename": "test.pdf"
},
{
    "divisionid":1,
    "s3uripath":"/s3/test/3434",
    "filename": "test2.pdf"
}]
}

Response:
{
    "data": [
        {
            "filename": "test.pdf",
            "recordid": 5
        },
        {
            "filename": "test2.pdf",
            "recordid": 6
        }
    ],
    "message": "Records created",
    "status": true
}

**Comment by sumathi-thirumani-aot** [comment]
Migration script associated with this task is **cd078dd1b149**

**Comment by divyav-aot** [comment]
closing this ticket as it is moved to test-marshal
