### ISSUE TITLE
Email Message Update related to the additional record type inputs for MCFD Personal requests

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2862]
* As an IAO Intake Team member
* I want  to see the the additional information from applicant on the Email Message
* so that intake has the additional details for Processing and/or ministries to work efficiently during Request Document Review, analysis cycles
**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope? 

- Refer #2861
- This change for email message content should occur "only" for the personal requests, and only if applicant selects any of the new personal MCFD specific record type options.

What is NOT in scope?
- General Requests and Personal Requests **_without_** "Yourself" option/checked on "Who are you requesting records about?"

**Acceptance Criteria**	

**Scenario 1: FOI Request email message with value "Myself" for  "Requesting info about" section**
* GIVEN ... a Personals Intake Team member reviewing FOI Request Emails
* WHEN ... a personal FOI Request email message has "Requesting info about" section with value "Myself"
* THEN ... a new section with main header "MCFD Records" should appear with subsection(s) related with new multi select options as per user story #2861

**Scenario 2: Subsection on email message under "MCFD Records" main section**
* GIVEN ...  when applicant submitted a personal request and a Personals Intake Team member is reviewing FOI Request Email and 
* WHEN ... applicant has selected all the new additional record type options while submitting -  refer scenarios under US #2861
* THEN ... on the email message received by Intake should look like below. Also, sub sections are conditional based on the selections. And all selections made should be listed with commas in between for easy copying to AXIS

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/58e603b0-1f74-43b4-8929-43da94c2c3f0)

**Scenario 3: Display of selected sub-sub options on email message**
* GIVEN ...  when applicant submitted a personal request and a Personals Intake Team member is reviewing FOI Request Email and 
* WHEN ... applicant has selected all the new additional record type options while submitting - refer scenarios under US #2861
* THEN ... on the email message received by Intake should look like above, with all "children" to the selected sub sections to be "comma" delimited - refer image above
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
#2861

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by abin-aot** [comment]
@lmullane , @m-prodan  , @JHarrietha-AOT  - ACs updated - Please have a look!

**Comment by JHarrietha-AOT** [comment]
@m-prodan this story is good for testing

**Comment by m-prodan** [comment]
QA Passed
