### ISSUE TITLE
Contact Applicant - Template Copy Saved When Sending Email

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2882]
**Describe the bug in current situation**
When sending correspondence through the contact applicant log, the system saves the email as expected, but it also saves the copy of the template. We only need what was sent to the applicant to be saved.

**Link bug to the User Story**

**Impact of this bug**
Impact: Medium - will eventually crowd the contact applicant log, and create confusion with entries doubled. 

**Chance of Occurring (high/medium/low/very low)**
high

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Test Marshal and have a request with an approved fee estimate
2. Send the fee estimate through the contact applicant log

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN the preview correspondence modal is open
WHEN the user hits send email
THEN the sent email will be saved in the contact applicant log
AND any attachments associated with it

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/0c51aa4f-d0ce-4796-8678-9b1d4412147a)

**Comment by liseandtea** [comment]
Repeated "Steps to Reproduce" several times and only the copy of what was sent to the applicant is being saved into the contact log.
![Contact Log.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/1844b635-24fd-416d-9d9d-fca4e1d8c124)
