### ISSUE TITLE
Angular Form Update - Forests

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2889]
* As an applicant
* I want to know more about BC Wildfire Requests when I submit a request to Forests
* so that I know whether I should be submitting and paying an application fee

**Assumptions & Scope**	
This story was requested by Resource team and BC Wildfire Service

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Ministry of Forests Selected**
* GIVEN an applicant is on the select Ministry screen 
* WHEN  they click on Ministry of Forests
* THEN text will appear above the continue button in red with the words: "For FOI requests relating to wildfires, records might not be released if there is an active and ongoing investigation into the fire in order to protect the integrity of the investigation. If you have questions whether an FOI request relates to a wildfire under investigation please contact BCWSFOI@gov.bc.ca for more information before submitting the FOI request. "

**Scenario 2: Ministry of Forests Unselected**
* GIVEN an applicant is on the select Ministries screen and Ministry of Forests is selected
* WHEN they uncheck the selection for Forests
* THEN the text that appears above the continue button will be removed.

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Design: ![MicrosoftTeams-image (5).png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/769f66b7-0b02-433c-b7e7-7673764d5261)

**Comment by m-prodan** [comment]
Design confirmed and approved by business. Good to move ahead for development when additional tasks allow @abin-aot 

cc: @lmullane

**Comment by m-prodan** [comment]
@abin-aot - Love the design update to this one. Having a problem though with payment flow - am not able to get to the pay part, I get stuck at "We had an issue while processing your payment" - tried with one Ministry (both forests, and a non-forests request) and also when multiple selected.

**Comment by abin-aot** [comment]
Ok will check @m-prodan

**Comment by abin-aot** [comment]
@m-prodan  : https://test.foirequestform.gov.bc.ca/ test is good with payment now
