### ISSUE TITLE
New CFR Forms - Notifications

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2901]
**Describe the bug in current situation**
Notifications on new CFR forms do not appear to be registering in the system - this was observed during demo on October 11

**Link bug to the User Story**

**Impact of this bug**
This will impact general requests that have fee estimates, with multiple CFR forms due to narrowing. Analysts will not receive notification that a new CFR form is ready for their review, and may miss the instruction if the Ministry does not also include a comment. 

**Chance of Occurring (high/medium/low/very low)**
Medium - requires events above to be present

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a request that is already on hold for fees
2. Add a new CFR form as a Ministry user
3. Save status as with IAO
4. Login as IAO user
5. Check for notification

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN a Ministry user is on the CFR Form
WHEN they change the status to "In review with IAO"
THEN all assigned IAO users will receive a notification

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
New bug found while fixing - Ministry was unable to change status of CFR form to In Review with IAO when new form created - will be fixed as part of this ticket too

**Comment by m-prodan** [comment]
New bug found while fixing - Ministry was unable to change status of CFR form to In Review with IAO when new form created - will be fixed as part of this ticket too

**Comment by lmullane** [comment]
Thanks, @aparna-aot. This is working as expected.
