### ISSUE TITLE
Include loading indicator and block multiple submission - Contact Applicant/Send Email

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#2909]
Describe the bug in current situation:
In the contact applicant tab; consider the scenario of choosing the template "Fee Estimate" and proceed with including attachment and click "Preview and Send".
In this action; the user is not informed on the system activity and also allows multiple submission from client side.

Solution: Include loading indicator and disable multiple submission from same active view (i.e. till response from server)

Link bug to the User Story

Impact of this bug
Impact of bug when triggered is high - users may inadvertently send multiple duplicate emails to an applicant if they click on the save and send button multiple times

Chance of Occurring (high/medium/low/very low)
Medium - user will need to click the button multiple times, they may not always do this, but are more likely to do so if they don't believe the application is responding.

Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?

Steps to Reproduce

Go to any general request with a pending fee estimate
Go to contact applicant log, and select a template
Prepare an email and rapidly click on the save and send. 

Expected behaviour
User should only be allowed to send one email after completing the action - the submit button should lock or disable after activating it.

Screenshots/ Visual Reference/ Source
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by liseandtea** [comment]
Followed steps to reproduce on both "Fee Estimate" and "Outstanding Balance" email. Loading indicator appeared both times after sending email, and then went to the contact applicant log when finished. As a user I did not have the opportunity to click on the sent button more than once.
