### ISSUE TITLE
Left Nav Bar "contact applicant" not showing

### ISSUE THREAD

**Issue by liseandtea** [bcgov/foi-flow#2914]
**Describe the bug in current situation**
When testing fee estimate payments, contact application option was not visible while logged in as an IAO user. 

**Link bug to the User Story** #2684 

**Impact of this bug**
Users would not be able to access correspondence and/or realize it was available to them.  

**Chance of Occurring (high/medium/low/very low)**  High for users that only use a laptop monitor

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?** Test-marshall using laptop screen

**Steps to Reproduce**
1.  'send fee estimate email out of system'
2. 'drag to laptop screen'
3. See error
4.![image.png](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/32f17964-59a3-4424-94d3-54c3ccd34171) 

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
@divyav-aot - let us know if you were working on this one as well

**Comment by liseandtea** [comment]
Tested the update and could not recreate bug - issue resolved - thanks Divya!

Tried in Edge, Chrome and Firefox, the "Contact Applicant" option was immediately displayed on the laptop screen when the page loaded. Zoomed all the way in and out - no change to the left nav bar - the option was always displayed.
