### ISSUE TITLE
CFR Form Reason - Always Showing as Mandatory Field

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2915]
**Describe the bug in current situation**
While working through fee estimate test scenarios, found it confusing to see the CFR form reason as a selectable option - even when there is just the single CFR form.

CFR form reason should only need to be selected when a new form is created, and be able to be updated after the form is created - it should not always be present.

**Link bug to the User Story**

**Impact of this bug**
Impact of bug is medium - it may confuse users, as they may assume they need to take an action on that drop down when they may not

**Chance of Occurring (high/medium/low/very low)**
high - the drop down is always present on the CFR form

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to any general request in the fee estimate state or later, where only 1 CFR form exists.
2. Click on Call For Records form
4. See drop down for CFR form reason

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN a user is on the CFR form
WHEN they click on Create New Form
THEN they will be prompted to select a reason.

GIVEN a user has created a new CFR form
AND that form is NOT the orginal
WHEN they are on the CFR form
THEN they will see the reason for the new form
AND they can change the reason

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by liseandtea** [comment]
Followed steps to reproduce: When there is only a single CFR form the "Reason for Creating a New CFR Form" does not appear. When a user clicks on "Create New CFR" then the "Reason for Creating a New CFR Form" option appears.
![1.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/6f2bc266-22bc-4265-9bfc-289607230d4b)
![2.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/9d0dae57-aa85-465d-a7fb-eb9dbe825e22)
