### ISSUE TITLE
Attachments on Change to On-Hold

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2916]
**Describe the bug in current situation**
Users should be allowed to upload multiple PDFs when changing state on hold, to notify an applicant a fee estimate can be paid online. Usually IAO analysts will upload a letter and invoice.  This occurs for both fee estimate state change to on hold, and Response to On hold state change.

You can upload multiple attachments, but the applicant only receives one. 

**Link bug to the User Story**

**Impact of this bug**
Impact: High - users that upload multiple attachments will not have their email delivered in full

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
TEST-Marshal

**Steps to Reproduce**
1. Go to any general request in a fee estimate state, OR request in a response state with an outstanding balance as an IAO user
2. Change request state to "On-Hold"
3. Upload multiple PDF attachments and save/send
4. Go to contact applicant log/see email received by applicant

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN an IAO analyst activates the on-hold state change
WHEN they upload files to the modal
THEN the files uploaded will be attached to the email to the applicant. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
Per discussion at stand-up/bug triage - only validation is PDF, no limit to number of attachments

**Comment by m-prodan** [comment]
@divyav-aot - are you working on this bug? Please put an estimate and bring into sprint.

**Comment by divyav-aot** [comment]
Increasing the effort to 5 as the changes include attachment log display

**Comment by lmullane** [comment]
This is fixed. Thanks, @divyav-aot
