### ISSUE TITLE
Assign Open Request to Flex Team

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#292]
* As an analyst 
* I want to be able to assign a request to a known user/group in the system
* so that the user can take action

**Assumptions & Scope**	
What are the assumptions for this story?

What is in and not in scope?

Not in scope - what members of a team (aka keycloak group) sees in the queue when they login and what they have permissions to search for. This will be handled by a different story.

**Acceptance Criteria**	

**Scenario 1: Assign to Flex Team 1**
* GIVEN an Intake Analyst has Opened a request
* AND the request is a General Request
* WHEN the analyst clicks 'Assign a Request'
* THEN the Flex Team will be an option

**Scenario 2: Assign to Flex Team 2**
* GIVEN an Intake analyst has clicked 'Assign a Request' for an open, general request
* WHEN the Intake Analyst selects the 'Flex Team
* AND the analyst clicks the 'Save' button
* THEN the Flex Team will be assigned
* AND the request will appear in the Flex Team queue
* AND the request will no longer appear in the Intake queue

**Scenario 3: Assign back to Intake Team**
* GIVEN a Flex Team analyst has clicked 'Assign a Request' for an open, general request
* WHEN the Intake Analyst selects the 'Intake Team'
* AND the Flex team analyst clicks the 'Save' button
* THEN the Intake team will be assigned
* AND the request will appear in the Intake team queue still in an 'Open Status'

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932505

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by abin-aot** [comment]
@lmullane @m-prodan  - So as per scenario 3 and 4, the assignee dropdown list will have ministry FOI coordinators listed on a FOI request of status "Open".  I prefer to discuss this in detail, if my above statement is valid, then Intake/ IAO staff has to go inside the "opened request" to reassign to ministry FOI coordinator.  Ideal condition is to - bring up a UX to select the assignee on the Ministry(s) side before opening the request.

**Comment by mpilchar** [comment]
@abin-aot @acoard-aot @m-prodan @divyav-aot @sumathi-thirumani-aot @JHarrietha-AOT @arielleandrews Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/FOI-flow-607f0ab6ae54b700111dc733/issues/bcgov/foi-flow/292?planning-poker)

**Comment by lmullane** [comment]
Tested all scenarios and they work as expected.
