### ISSUE TITLE
Update to Fee Estimate Email Template and Mailbox Sending

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2925]
Title of ticket: 

#### Description
Per feedback we have heard in demos, we need a small revision to the email templates used for sending out fee estimates.

This should be limited to the fee estimate email templates only - collection of the outstanding balance does not require any updates.

#### Template Update:
Dear APPLICANT
Please see the attached regarding your FOI Request. Please review the attached letter, as you have additional options outside of paying the fee including narrowing your request, or requesting a fee waiver.

If you would like to pay your estimate online, please click on this link: 

Pay Online 

Thank you,
USER
TEAM

-SIGNATURE BLOCK-

#### DOD
- [ ] Update Fee Estimate Email Template
- [ ] Update mailer sending from a DoNotReply mailer

**Comment by liseandtea** [comment]
FE letter reads as above in the "Fee Estimate Template Update"
![FE Letter.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/0787a691-3a73-4a11-b679-22c75c5c19f5)
