### ISSUE TITLE
General - Performance Testing & Optimization

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#2931]
DOD
======
- [x] Perform load testing
- [x] System Testing i.e. Analyze application for optimization
- [x] Scheduler to automatically clear and reload master data cache
- [x] Migrate existing WF instances to new WF

**Comment by sumathi-thirumani-aot** [comment]
[Uploading... FOI-FLOW_System Testing_Findings.docx]

**Comment by abin-aot** [comment]
This is a technical task for review the WF performance, @sumathi-thirumani-aot has completed , hence closing
