### ISSUE TITLE
Close Request UI

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2944]
**Describe the bug in current situation**
Closing a request in test-marshal appears to have a UI related bug, where the fields are all crunched together

**Link bug to the User Story**

**Impact of this bug**
User is able to complete actions, but it could be difficult to navigate.

**Chance of Occurring (high/medium/low/very low)**
high

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test Marshal - any request

**Steps to Reproduce**
1. Go to any active request as an IAO user
2. Click on state menu
3. Select Closed

**Actual/ observed behaviour/ results**
![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/f092d9b4-8fd7-47c4-b71b-d838432926d6)

**Expected behaviour**
Closing menu should look like this:
![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/53bdb779-f455-49fd-a5fb-1b093d11bf7b)

**Comment by lmullane** [comment]
This is now working as expected. Thanks, @aparna-aot
