### ISSUE TITLE
Deposit Paid - Automated State Change

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2945]
**Describe the bug in current situation**
When an applicant pays a deposit, it should also trigger the behavior of taking the request off hold, and changing the state to Call for Records

**Link bug to the User Story**

**Impact of this bug**
Users will be expecting the automated state change and notifications, and may not recognize they need to take action if they inadvertently dismiss the notification. 

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-Marshal

**Steps to Reproduce**
1. Go to any general request
2. Set up a fee estimate over 200 dollars and send to applicant
3. Applicant should choose to pay the 1/2 deposit
4. After payment successful, request will stay in "On-Hold" state.

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN a request is on hold
WHEN a fee estimate is paid in full OR a deposit is paid
THEN the state of the request will automatically change to "Call for Records"

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by sumathi-thirumani-aot** [comment]
The state change to "CFR" will take place only if email sent to applicant as part of state change to "On Hold".
@m-prodan New ticket will be created for state change via "Applicant Correspondence".

**Comment by sumathi-thirumani-aot** [comment]
Marking as "**No fix - Working as Expected**".

**Comment by lmullane** [comment]
@sumathi-thirumani-aot, can I confirm this is working without any code fixes?

**Comment by abin-aot** [comment]
Not as issue, discussed during stand up 2/Nov
