### ISSUE TITLE
The "Click "i" for more details" bubble in the CFR Form page is cut off / not visible 

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#2948]
Title of ticket: 

#### Description
The "Click "i" for more details" bubble in the CFR Form page is not visible or is cut off after the introduction of scrollbar.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Remove the bubble from the page.
![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/57702fa6-c284-4fa0-a13a-d4c2274a6692)

**Comment by lmullane** [comment]
This is fixed. Thanks, @aparna-aot
