### ISSUE TITLE
Save Annotations and Comments to Backend from front end

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2956]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Update DB model and API for retrieving and saving Annotations
- [x] Display Annotations and Comments in PDFTron
- [x] Save Annotations and Comments to Backend
- [x] Unit tests
- [x] Load and display documents, divisions, pages in left nav panel
- [x] Deploy to openshift
- [x] Download files from S3

**Comment by abin-aot** [comment]
Closing this task as per stand up 28/11 - will go to prod, test once Dedupe is over!
