### ISSUE TITLE
POST API - OPEN REQUEST (#33)

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#296]
Title of ticket: 

#### Description
This task is for creating python API for POSTing open request. The logic is to flush the data into the newly created tables as per #294. The Parent/Raw request will get "Archived" status, and a new request(proper) will be created on LOB DB tables with version, referential integrity etc. 

Cases need to be handled - "Archival" of existing/raw request, transition from "Unopened" to "Opened" , Logic of "File Number" generation, Versioning

Additional points to check while developing - PUBSUB for WF instantiation , TODO.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Archival logic for RAW requests
- [x] Versioning of Opened Requests
- [x] File Number Generation Logic
- [x] Transition from "Unopened" to "Open state"
- [x] Transition from "Intake in progress" to "Open"
- [x] Services for API
- [x] API Resource file with Routing
- [x] Unit testing

**Comment by sumathi-thirumani-aot** [comment]
Scenario: Create new record
Sample Http Mock:
POST http://localhost:15000/api/foirequests
{
  "requestData": {
    "requestType": {
      "requestType": "general"
    },
    "ministryRequests":[
      {
         "description":"Ministry of Advanced Education and Skills Training",
         "fileNumber":"foi",
         "dueDate":"2021-10-14",
         "assignedTo":"sumathi",
         "programAreaId":1,
         "requestStatusId":1
      }
   ],
  "contactInformations":[
      {
         "contactTypeId":1,
         "contactInformation":"sumathi@gmail.com"
      }
   ],
   "personalAttributes":[
      {
         "personalAttributeId":1,
         "attributeValue":"12333333"
      }
   ],
    "requestApplicants":[
      {
        "applicant": {
            "firstName":"test"
            },
        "requestorTypeId": 1
      },
      {
        "applicant": {
            "firstName":"test2"
            },
        "requestorTypeId": 1
      }
   ]
  }
   
}

**Comment by sumathi-thirumani-aot** [comment]
Scenario: Create revision
Sample Http Mock:
POST http://localhost:15000/api/foirequests/12
{
  "requestData": {
    "requestType": {
      "requestType": "general"
    },
    "ministryRequests":[
      {
         "description":"Ministry of Advanced Education and Skills Training",
         "fileNumber":"foi",
         "dueDate":"2021-10-14",
         "assignedTo":"sumathi",
         "programAreaId":1,
         "requestStatusId":1
      }
   ],
  "contactInformations":[
      {
         "contactTypeId":1,
         "contactInformation":"sumathi@gmail.com"
      }
   ],
   "personalAttributes":[
      {
         "personalAttributeId":1,
         "attributeValue":"12333333"
      }
   ],
    "requestApplicants":[
      {
        "applicant": {
            "firstName":"test"
            },
        "requestorTypeId": 1
      },
      {
        "applicant": {
            "firstName":"test2"
            },
        "requestorTypeId": 1
      }
   ]
  }
   
}


Sample Response:
{
    "id": 12,
    "message": "Request added",
    "status": true
}

**Comment by sumathi-thirumani-aot** [comment]
Archiving of raw request will happen from workflow.
