### ISSUE TITLE
Contact Applicant - Automated State Change From On-Hold

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2960]
* As an IAO user and Ministry User
* I want the status of a request to change from on hold to the required state when the applicant pays a fee
* so that I know what action needs to be taken

**Assumptions & Scope**	
This is a follow up to the contact applicant story, where a key requirement was missed. When an applicant is sent a fee estimate (or resent) from the contact applicant log, and the request is on hold - when then the payment of the fee is received, it should also trigger the change of state of the request in addition to the notification. 

Assumption: Automated state change will also mimic functionality that exists, with system generated comments being posted on the request history

What is IN scope?
Automated state changes when request is in the "On-Hold" state

**Acceptance Criteria**	

**Scenario 1: Fee Estimate Email - Successful Payment**
* GIVEN an applicant has been sent a fee estimate email from the contact applicant log
* AND the request is on hold
* WHEN the applicant pays the fee
* THEN the state will update to "Call for Records"

**Scenario 2: Outstanding Balance Email - Successful Payment**
* GIVEN an applicant has been sent an outstanding balance email from the contact applicant log
* AND the request is on hold
* WHEN the applicant pays the fee
* THEN the state will update to "Response"

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
As discussed at sprint planning - this was a missed requirement in the payment flow when re-sending, or sending a new fee through the contact applicant log. This is to ensure when the request is on hold, that the payment will also trigger the necessary state change, depending on the template that is used.

I think we can flag this as a known issue, and commit to adding this into our next sprint after it is refined, given the work still required this sprint. 

cc: @lmullane @abin-aot @liseandtea

**Comment by abin-aot** [comment]
As per the Backlog refinement(7/NOV), Outstanding Fee email should only be activated on ONHOLD and request state has passed, "Sign Off"

**Comment by nkan-aot** [comment]
the following text was removed from payment landing page due to effects from not automatically moving off on hold. Once this is fixed text must be added back![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/3685efb9-ecd6-4165-9f23-46459790e2b5)

**Comment by divyav-aot** [comment]
As discussed, please confirm if we need to consider both on hold and off hold days for the calculation. Also, is there any special calculation needed, if the payment date time is after 4.30PM PST.

**Comment by KyEggleston** [comment]
Added ACs to QA Master list.

**Comment by liseandtea** [comment]
@sumathi-thirumani-aot @divyav-aot 
scenario 1, has a bug where the 'On Hold' for an IAO user status is not an option when the current status is set to 'Response'. Without this, there is no way to put a request on hold when waiting for a final payment before records release (and closing the request).

**Comment by KyEggleston** [comment]
Both ACs have passed testing. 

Just need to confirm if we are still adding the LDD language back to to the Payment Successful page.  

![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/3685efb9-ecd6-4165-9f23-46459790e2b5)
