### ISSUE TITLE
Contact Applicant Log - Confirmation Email Payment Overwrites Prior Email

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2964]
**Describe the bug in current situation**
While training in test-marshal, it was observed that when a request has a fee estimate sent the standard way through the on-hold function, and then a new CFR form is created, and a subsequent fee is sent through the contact applicant log - payment of the subsequent fee overwrites the subsequent fee email.

**Link bug to the User Story**

**Impact of this bug**
High impact - users will lose the sent fee email originally provided to the applicant

**Chance of Occurring (high/medium/low/very low)**
High - applicants typically attempt to narrow requests, if the applicant chooses to pay it will trigger this bug

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

TEST-Marshal
**Steps to Reproduce**
1. Go to a general request, and send a fee estimate to an applicant using the state change
2. Create a new CFR form, and select the reason as "Request Narrowed"
3. Update the fee to be different (smaller) than the original
4. Approve new fee, and send fee estimate through contact applicant log
5. Pay fee online
6. Go to Contact Applicant log - the email that was sent in step 4 will no longer appear, and be replaced by the receipt email sent to the applicant

**Actual/ observed behaviour/ results**

**Expected behaviour**
Prior emails must be retained, and the confirmation email payment must not overwrite any prior email
GIVEN an applicant has received a fee estimate email
WHEN they complete the payment
THEN a copy of the email confirming payment and the receipt shall be added to the Contact Applicant Log

**Screenshots/ Visual Reference/ Source**
This was observed in EDU-2022-999652, and EDU-2022-88765

**Comment by m-prodan** [comment]
Email overwrite bug we observed @lmullane

**Comment by divyav-aot** [comment]
@m-prodan @lmullane - This issue is fixed with latest push. Please retest and let us know.

**Comment by liseandtea** [comment]
Tested in EDU-2022-31542 and bug is resolved. Recreated steps above and all 3 emails that were sent to the applicant appear in the contact log (initial fee estimate, revised fee estimate and acknowledge of payment). 
![emails.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/146dc256-161e-4e98-ac55-31e2412fc1c5)
