### ISSUE TITLE
New CFR From status changes back to In review with IAO from Approved in "Fee Estimate" state

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#2965]
**Describe the bug in current situation**

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a general request, and send a fee estimate to an applicant using the state change
2. Pay fee Online - deposit
3. Create a new CFR form in CFR state, and select the reason as "Request Narrowed"
4. Update the fee to be different than the original
5. Change the state to Fee Estimate (only a bug in Fee Estimate)
6. Change the CFR Form status to "In Review with IAO"
7. Approve new fee, and send fee estimate through contact applicant log
8. Pay fee online (only a bug when the applicant pays)
9. Refresh the page and check the CFR Form Status
10. The CFR form status is changed back to "In Review with IAO"

**Actual/ observed behaviour/ results**
The CFR Form Status changes to "In Review with IAO" from "Approved"

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a CFR form is Approved
WHEN the applicant pays
THEN the form should stay Approved in any state

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by liseandtea** [comment]
Tested in Chrome and Edge following the "Steps to Reproduce", issue resolved. CFR remains in approved state in both Ministry and IAO views. ![approved.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/9c538261-122c-4b1f-b8bc-89e46a8bf0cb)
