### ISSUE TITLE
Carry forward Fee waiver and Refund amount to the next CFR Form

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#2966]
Title of ticket: 

#### Description
Carry forward Fee waiver and Refund amount to the next CFR Form

#### Dependencies
Are there any dependencies?

#### Steps to test
1.  Add Fee waiver or/and Refund amount to an approved form
2.  Create new form and check the Fee waiver or/and Refund amount 
3. Fee waiver or/and Refund amount should carry forward from the previous version
4. Check the calculation of balance remaining
5. Check the CFR Form history

**Comment by divyav-aot** [comment]
@aparna-aot - test the changes and confirm

**Comment by aparna-aot** [comment]
@divyav-aot Tested in local branch. Everything seems to be working fine.

**Comment by liseandtea** [comment]
Completed test steps

Scenario 1 - Full fee waiver:  Applicant issued fee for $360, full fee waiver requested and granted; balance owing is now $0. Second fee estimate issued for $510, fee estimate waiver carried forward from original CFR and balance owing is now $150 ($510 - $360 = $150). This is the correct calculation.
![1.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/0c31ebc8-9128-4018-82fc-6da6b57408db)

Scenario 2 - Partial Fee Estimate: Applicant issued fee for $510, fee waiver requested, and a partial waiver granted for $150 (5 hours); balance owing is now $360. Second fee estimate issued for $660, partial fee estimate waiver carried forward from original CFR and balance owing is now $510 ($660 - $150 = $510). This is the correct calculation.
![2.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/4079a20c-17d2-4eb0-a31a-912d08df11bb)
