### ISSUE TITLE
Ministry Onboarding Schedule

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2968]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Update the ministry contact list with emails
- [ ] Schedule meeting on FOI Mod onboarding - invite WG
- [ ] Create slide deck
- [ ] Capture ministry clients preferred quarter to onboard
- [ ] Update schedule

**Comment by m-prodan** [comment]
@liseandtea - feel free to reach out to other TLs/Mgrs as needed if you need help getting contacts, will need more than just the coordinator, likely also a manager

**Comment by liseandtea** [comment]
Email sent to IAO managers on Friday, October 28, 2022 ~ they have until the end of the day on Wednesday to respond. Also asking for them to confirm which public bodies have different coordinators for general and personal requests (e.g., CFD and MSD have different areas that respond) to ensure no one is getting missed.

**Comment by liseandtea** [comment]
list updated as of November 4, 2022.
