### ISSUE TITLE
AXIS Sync Update - Subject Codes

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2969]
* As a user
* I want subject codes assigned to requests
* so that I can categorize requests further into sub-groups for reporting, search or management purposes

**Assumptions & Scope**	
This story details the need for subject codes, currently used in AXIS, to be visible in the Mod application.
Intention for this story is to also help with some new onboarding requirements (to be handled in a seperate user story) whereby certain requests within the same Ministry may need to be processed by a seperate keycloak group.

What is IN scope?
AXIS Sync
Design Update to FOI Request Details

**Acceptance Criteria**	

**Scenario 1: AXIS Sync Banner**
* GIVEN a user is on a synced request with AXIS
* WHEN a subject code is saved to the request in AXIS
* AND the subject code does not match with what is in the flow app
* THEN the AXIS sync banner will display for the user
* AND the Sync with AXIS button will be active

**Scenario 2: Activate Sync**
* GIVEN a user is on a request where the sync button is active
* WHEN they click on the sync with AXIS button
* THEN the review changes modal will appear
* AND the updated subject code will be viewable in the accordion
* AND any other changes that need to be synced will display for the user.

**Scenario 3: Save Sync**
* GIVEN a user is on the sync with AXIS modal
* WHEN they click on the save button
* THEN the modal will close, and all changes from AXIS will be written over to the request in the flow application
* AND the subject line will populate with the value from AXIS (need design for where this will be @JHarrietha-AOT )
* AND the AXIS sync banner will disappear

**Scenario 4: Cancel Sync**
* GIVEN a user is on the sync with AXIS modal
* WHEN they click on the cancel button
* THEN the modal will close
* AND the AXIS sync banner will continue to be displayed

**Scenario 5: Advanced Search - Subject Code**
* GIVEN a user is on the Advanced Search panel
* AND they have selected the Subject Code Filter
* WHEN they enter text into the search field
* THEN the Apply Search button will become active

**Scenario 6: Advanced Search - Subject Code - Apply Search**
* GIVEN a user has selected subject code in the advanced search window
* AND they have entered text that is in part, or in full an existing subject code
* WHEN they click apply search
* THEN all requests containing that subject code will be displayed, subject to any other filters applied

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/968972776

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Subject code story, as discussed at coordination meeting. cc @lmullane @JHarrietha-AOT @abin-aot @liseandtea

**Comment by m-prodan** [comment]
Will write up a separate story, specifically for corrections and how their requests will be handled/seen at the queue level.

**Comment by JHarrietha-AOT** [comment]
@m-prodan added design link to this ticket, reach out if you have any questions

**Comment by abin-aot** [comment]
Subject codes in AXIS, below. This is "TECHNICALLY" a sub-group  with in a ministry like, Justice, PSA and IDEA IS TO BRING A DEDICATED Queue for these categorization under "SAME" ministry.  : ![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/37273cc6-af0a-4363-b39a-19aff14a7c16)

**Comment by lmullane** [comment]
As discussed, we need another story to update Advanced Search so you can search by subject code.

**Comment by divyav-aot** [comment]
@JHarrietha-AOT @m-prodan  - does this subject code selectable at any state from Unopened?

**Comment by lmullane** [comment]
@m-prodan, could you advise here?

Assumption is that there is no subject code until a request is 'Opened' in AXIS, correct?

**Comment by m-prodan** [comment]
Yes, and it could also be added later in the process (ie: case where Intake misses the right subject code).

I would make it available from "Intake in Progress" as it is an option for Intake to enter while they are opening a request.

**Comment by m-prodan** [comment]
In other words, we shouldn't limit the state in which it can be entered. There are also cases where we will retro-actively add subject codes to in flight requests if the subject is deemed to be worth tracking.

**Comment by liseandtea** [comment]
@lmullane @m-prodan 

When a request is opened in AXIS, the ministry code defaults depending on the action office chosen, this is a required action to open a request. Subject codes can be added/updated at any time.

![Screenshot 2023-01-05 112105.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/fdef2c51-c352-4700-b5e0-ffb60c23140b)

**Comment by divyav-aot** [comment]
Thanks for the clarification @m-prodan and @liseandtea . I will make it selectable from Unopened state onwards.

**Comment by abin-aot** [comment]
As discussed @m-prodan , @divyav-aot  we are planning to handle CORRECTIONs with a Ministry level code. Hence this task will be obsolete

**Comment by richard-aot** [comment]
This user story is ready for QA. Searching by Subject Code in Advanced search is also ready for testing, please verify that feature as well. Thank you.

**Comment by KyEggleston** [comment]
Confirmed subject code searching (Advanced Search) - other ACs still need testing.

**Comment by m-prodan** [comment]
Updated AC to include advanced search options. QA passed all scenarios - nice work @richard-aot !

Thanks for staging the test items in the sheet for me @KyEggleston
