### ISSUE TITLE
User is able to send fee estimate email through applicant contact log when they should not

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#2972]
There are two scenarios where user is able to send fee estimate email when logically they should not be able to
1) when new version (# greater than 1) of the form has not been approved yet
2) when the current version has been approved, and applicant has already paid

**Link bug to the User Story**

**Impact of this bug**
medium - sending fee estimate email in these situations will lead to behaviour not explicitly defined by the system

**Chance of Occurring (high/medium/low/very low)**
medium

**Steps to Reproduce**
scenario 1
- create new request, add CFR details, approve, then add new version of CFR form
- go to applicant contact log
- user is able to send fee estimate email, even though current estimate has not been approved yet

scenario 2
- create new request, add CFR details, approve, and simulate applicant payment
- go to applicant contact log
- user is able to send fee estimate email with same details, even though applicant has already paid

**Expected behaviour**
in scenario 1 user should not be able to pick any template
in scenario 2 user should not be able to pick fee estimate template but they can send outstanding fee email

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nkan-aot** [comment]
after meeting with @m-prodan @divyav-aot @sumathi-thirumani-aot 
1. Balance remaining can be -ve in many cases. We will show -ve value. fix only NaN issue
2. Contact applicant log template drop down scenarios - 
disable the "Add correspondence" button in 
a. Fee estimate state
b. if balance remaining <=0 then

**Comment by m-prodan** [comment]
Issue appears fixed - can no longer resend fee estimate when a new, unapproved CFR form is in review. Scenario 2 also working as expected now. Nice work!
