### ISSUE TITLE
EXCEL (xls/xlsx) to PDF Document Conversion 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2974]
Title of ticket: 

#### Description
The purpose of this task is to convert XLS, XLSX Files arriving into Ministry Level S3 Bucket's request folder , to a "PROPERLY FORMATTED, ALIGNED" PDF file. We can refer the code base from File Watcher and create a Module for EXCEL to PDF to plugin with a centralized .NET core microservices(#2975), which is intended to run on Linux based Docker container, in turn with our BC GOV OCP

Refer this repo for EXCEL conversion assembly : https://github.com/bcgov/foi-file-conversion

#### Dependencies
Are there any dependencies?

#### DOD
- [ ]  Create a independent .NET core class library   for XLS/XLSX (from S3) to PDF conversion (saved back to S3)- refer File Conversion Library
- [ ]  Create Unit Test for XLS/XLSX to PDF 
- [ ]  Integrated with Main FOI DOC Conversion Microservice/computing service
- [ ]  Tested with Docker
- [ ]

**Comment by KyEggleston** [comment]
Tested on ABC-3453-45345 in TEST-Marshal

- Was able to upload both .XLS and .XLSX files to the Records tab.
- Records successfully ran through deduplication and file conversion (indicated by green checkmark for unique records, or a yellow duplicate icon for duplicates).
- Files did not change their file extension after file conversion (i.e., on the Records tab, their native file extension is displayed as a suffix on the name of the file).
- I was able to successfully download converted .XLS and .XLSX files as PDFs under the ellipsis (...) -> Download PDF
- Did not notice any significant formatting issues on PDF downloaded documents

Related to ACs under https://github.com/bcgov/foi-flow/issues/3136.
