### ISSUE TITLE
.DOC, .DOCX TO PDF File Conversion

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2978]
Title of ticket: 

#### Description
The purpose of this task is to convert .DOC, .DOCX Files arriving into Ministry Level S3 Bucket's request folder , to a "PROPERLY FORMATTED, ALIGNED" PDF file. Create a Module for WORD to PDF to plugin with a centralized .NET core microservices(#2975), which is intended to run on Linux based Docker container, in turn with our BC GOV OCP

#### Dependencies
Are there any dependencies?

#### DOD
- [x]  Create a independent .NET core class library   for DOC, DOCX (from S3) to PDF conversion (saved back to S3)
- [x]  Create Unit Test for DOC, DOCX to PDF 
- [x]  Integrated with Main FOI DOC Conversion Microservice/computing service
- [x]  Tested with Docker
- [ ]

**Comment by KyEggleston** [comment]
Tested on ABC-3453-45345 in TEST-Marshal

- Was able to upload both .DOCX and .DOC files to the Records tab. 
- Records successfully ran through deduplication and file conversion (indicated by green checkmark for unique records, or a yellow duplicate icon for duplicates). 
- Files did not change their file extension after file conversion (i.e., on the Records tab, their native file extension is displayed as a suffix on the name of the file). 
- I was able to successfully download converted .DOCX and .DOC files as PDFs under the ellipsis (...) -> Download PDF 
- Did not notice any significant formatting issues on PDF downloaded documents
