### ISSUE TITLE
PUT API - Open Request

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#298]
Title of ticket: 

#### Description
This is placeholder task as of now, in case we need an API /PUT API for WF instance update while opening request. 

On click of "Open Request", the raw request would be captured in actual transaction tables "FOI Requests". On successful navigation from raw request processing to request processing workflow; the API to update workflow instance will happen. 

#### Dependencies
Are there any dependencies? - WF Design for Open request/ New WF instance spin out??

#### DOD
- [x] Should be able to update the worfklow instance ID
- [x] Should be able to update status of single ministry record
- [x] Should be able to update status of multiple ministry records
- [x] Unit Testing
- [ ]

**Comment by sumathi-thirumani-aot** [comment]
Update of workflow instance ID 
PUT http://localhost:15000/api/foirequests/1

{"wfinstanceId":"328a8914-f166-11eb-99bc-0a580a6161f7"}

**Comment by sumathi-thirumani-aot** [comment]
Functionality: Update of ministry status

PUT http://localhost:15000/api/foirequests/1
{"selectedMinistries":[{"filenumber":"AFF-2021-13520", "status":"CFR"}]}

Response:
{
    "id": 1,
    "message": "Request updated",
    "status": true
}

**Comment by sumathi-thirumani-aot** [comment]
Unit Testing (Yet to be ran).

**Comment by abin-aot** [comment]
Unit tests fixed!. Running perfectly

**Comment by mpilchar** [comment]
Woo hoo!
