### ISSUE TITLE
Education - Division Name Updates

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2981]
Title of ticket: 

#### Description
Education has a couple divisions whose names are changing. Updating these names should not lose the data in ReDash that we were collecting, it should simply be a change of name to existing divisions

#### Dependencies
n/a

#### DOD
- [x] Rename Learning Division to - System Liaison and Supports Division
- [x] Rename Education Programs Division to - Learning and Education Programs Division

**Comment by abin-aot** [comment]
@lmullane - taking down the estimate since we are planning to do this effort with #3272

**Comment by liseandtea** [comment]
Closing this request - program areas have updated correctly. 

Tested on EDU-2023-39654
Learning Division has been changed to  System Liaison and Supports Division

Education Programs Division has been changed to Learning and Education Programs Division

![Screenshot 2023-01-13 102406.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/b9250ae5-3a40-4ec8-a694-ad15324644cf)

![Screenshot 2023-01-13 102507.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/cf1c820e-3b02-4928-80d2-06d0d2d040ba)

**Comment by abin-aot** [comment]
Created Release label 4.8.1 for this ticket - FYI @lmullane , @m-prodan , @liseandtea

**Comment by abin-aot** [comment]
Deployment to PROD is over! 
**Steps taken**

1. Backs up taken  - Camunda, PostgresDB
patroni-master-002-ffa-camunda_2023-01-16_16-10-15.sql.gz  
patroni-master-002-foidb_2023-01-16_16-10-13.sql.gz
2, ![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/d057ea9f-bb18-47a2-9d43-19603dfa4e8c)
