### ISSUE TITLE
Restricted Requests - Flagging (IAO)

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2982]
* As an Intake Manager 
* I want the ability to restrict a request
* so that I can ensure access is controlled

**Assumptions & Scope**	
This story covers how a request can be flagged as restricted.
Flagging a request as restricted can ONLY be done by the Intake Manager
Flagging a request as restricted can occur at any request state from Intake in Progress or onwards
The Intake/Processing Team manager will always see the restriction flag - users will only see the restriction flag if they are assigned or a watcher of the request that is restricted. 
Only the Intake Manager, and users assigned or watching a restricted requests, can see those requests in the system
Restricted Requests should not include any detail like request descriptions or other potential identifiers in the reports

What is IN scope?
Functionality to flag a request as restricted
Setting up user permissions/new group for Intake manager

What is NOT in scope?
Assignment Rules and Conditions (Covered in seperate user story # )
Reporting Rules and Conditions (Covered in Seperate user story # )
Comments and Tagging Rules and Conditions (Covered in separate user story # )

**Acceptance Criteria**	

**Scenario 1: Restricted Request Setting - Intake Manager**
* GIVEN an Intake manager is on the review request page
* WHEN the request is in 'Intake in Progress' or a later stage
* THEN the Intake manager will see a flag indicating the request is Unrestricted
(https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/875784933)

**Scenario 2: Activate Restriction Flag Dropdown**
* GIVEN an Intake manager is on the review request page
* AND the request is assigned to one user (not the team queue)
* WHEN they click on the "Unrestricted" Flag
* THEN a drop down will appear, and they will see the option to "Restrict" and "Unrestrict"
* AND Unrestrict will be greyed out and unselectable

**Scenario 3: Fail Activate Restriction Flag Dropdown**
* GIVEN an Intake manager is on the review request page
* AND the request is assigned to the team queue)
* WHEN they click on the "Unrestricted" Flag
* THEN a modal will appear, and they with the message "A request can only be restricted when it is assigned to one team member, not a team queue."

**Scenario 4: Select Restricted**
* GIVEN an Intake manager has activated the Restricted Drop down
* WHEN they selected "Restricted"
* THEN a modal will appear with the following message: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/968972777/play
* AND There will be the option to Save Change or Cancel

**Scenario 5: Confirm Restricted**
* GIVEN an intake manager is on the confirm restricted modal
* WHEN they selected Save Change
* THEN the modal will close, and the flag will update to Restricted

**Scenario 6: Cancel Restricted**
* GIVEN an intake manager is on the confirm restricted modal
* WHEN they selected Cancel
* THEN the modal will close, and the flag will remain as unrestricted

**Scenario 7: UnRestrict**
* GIVEN an Intake manager has activated the Restricted Drop down
* WHEN they selected "UnRestrict"
* THEN a modal will appear with the following message: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/968974910/play
* AND There will be the option to Save Change or Cancel

**Scenario 8: Confirm UnRestrict**
* GIVEN an intake manager is on the confirm restricted modal
* WHEN they selected Save Change
* THEN the modal will close, and the flag will update to Unrestricted

**Scenario 9: Cancel Unrestrict**
* GIVEN an intake manager is on the confirm restricted modal
* WHEN they selected Cancel
* THEN the modal will close, and the flag will remain as Restricted

**Scenario 10: User other than Intake Attempts to Unrestrict**
* GIVEN a user is assigned or a watcher of a restricted request
* AND The user is NOT the Intake Manager
* WHEN they click on the restricted flag
* THEN a modal will pop out with the following message: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/968972778/play
* AND the only option will be to cancel and close the modal

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/875784933

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Ok - I think I've finished capturing the scenarios for this one - this is only to flag a request as unrestricted (or remove said flag, if needed).

**Comment by JHarrietha-AOT** [comment]
@m-prodan Story looks good to me, the design link has been updated so you can click through from the Intake Manager perspective and see the modals for restricting and un-restricting a request.

Should we also add the assumption that the intake Manager should have access to this button at all stages of the request expect for once it has been closed?

**Comment by JHarrietha-AOT** [comment]
@m-prodan Also do we want to add an additional story is any user other the IAO clicks on the restricted bubble they get a modal explaining they must reach out to the intake manger if they believe that flag should be changed

I have that modal design here: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/968972778

**Comment by m-prodan** [comment]
Thanks Jackie - I will update the assumptions. I think I will also include this for closed requests - just in case there's a need to do something in retrospect... Im thinking specifically of the scenario Intake mentioned where someone was found out after the fact that a request should have been restricted... perhaps there is a future case where an old closed request was also a part of this.

**Comment by abin-aot** [comment]
Based on assumptions like, Intake manager and Processing Team manager can see restricted file, estimating to 21, but need to catch up to fool proof entire flow

**Comment by m-prodan** [comment]
Removed assumption that restricted requests can only have one watcher per feedback at demo

**Comment by JHarrietha-AOT** [comment]
@aparna-aot just sharing the link again in the comment for reference 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/968972776

**Comment by aparna-aot** [comment]
@m-prodan Is this behavior applicable to Ministry Users/View as well?

**Comment by aparna-aot** [comment]
As discussed, All tickets related to Restricted Requests-IAO should be tested in DEV environment until KeyCloak migration tasks are moved to production.

**Steps to add users as IAO Restricted Files Manager:**

- Login to DEV-Keycloak : https://dev.loginproxy.gov.bc.ca/auth/admin/foi-mod/console .
- Go to **Users** dashboard and search for the user whom you want to add as IAO Restricted Files Manager. 
- Click on the user and select Groups. From the Available Groups find **IAO Restricted Files Manager** group and click **Join**. 
- You can see "IAO Restricted Files Manager" group in Group Membership.
![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/03878f18-e266-4c84-a0b5-014c0f98ff24)![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/b2587301-7cf5-4127-94b1-a30c1df6df96)

**Comment by KyEggleston** [comment]
@aparna-aot 

Only two small updates for this ticket after QA:

<h3>Scenario 5</h3>
Currently the 'restricted file' modal reads:

![image](https://user-images.githubusercontent.com/117312323/214974020-4d77ccf8-9fb9-4140-a1f9-8565d81e36f9.png)

It should be updated to:
![image](https://user-images.githubusercontent.com/117312323/214974696-aaa81b29-b754-4a41-9f45-04306ffcac22.png)


<h3>Scenario 7</h3>
The language in the 'unrestrict file' modal needs to be updated. 
Currently it reads:

![image](https://user-images.githubusercontent.com/117312323/214973408-f0be7eee-707e-4ff2-8c1f-2aa7f9ca11ef.png)

It should be updated to read:
![image](https://user-images.githubusercontent.com/117312323/214975012-f80d2639-8c68-46c4-9755-0789fd922e6b.png)

**Comment by aparna-aot** [comment]
@KyEggleston Sounds good. Will update the text soon and let u know.

**Comment by aparna-aot** [comment]
@KyEggleston All the above mentioned text updates have been pushed to DEV environment.

**Comment by KyEggleston** [comment]
@aparna-aot - Thanks for the updates - I noticed that 'restricted' and 'unrestrict' is misspelled in the modals (in my previous comment). Could this be updated? I indicated them in the screenshots in a previous comment, but it's very minor and may have been missed.  Afterwards I'll close this ticket - thanks!

**Comment by aparna-aot** [comment]
@KyEggleston - I definitely missed that. I have fixed it and pushed to DEV. Please verify. Thanks!

**Comment by KyEggleston** [comment]
Thanks @aparna-aot - updates confirmed and closing ticket
