### ISSUE TITLE
Restricted Requests - Assignments and Conditions - IAO

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2983]
* As an IAO manager 
* I want to restrict access to Restricted requests
* so that I can ensure the privacy of applicants, and have strong control over who has responsibility of the request

**Assumptions & Scope**	
Restricted requests are typically assigned to the manager of a team, and the manager designates someone on their team that can work on the request. In most cases, this is usually a request handled by a FOI Specialist, and a Manager. 

In addition - requests are not always processed by the usual team, for example, a restricted PSA request could be handled by the analyst and manager of a team other than the Social Education Team. Auto-Assignments must be disabled for restricted requests. 

Assignments can not be done at the queue level, it must be assigned to a person.

Primary Assignments will show all active IAO users within the system, so that managers have the flexibility to assign as they see fit. 

The watcher feature can only be activated with the drop down, it will not have the quick watch function. 

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Change Request State - Open**
* GIVEN a Restricted request is in "Intake in Progress"
* WHEN the user updates the state to open
* THEN the update state modal will appear
* AND the IAO assignment will remain the same

**Scenario 2: Assign Request - Intake Manager**
* GIVEN a Restricted Request is in the Open State
* WHEN the Intake manager clicks on the primary assignment
* THEN the names that will populate will be all IAO users. 

**Scenario 3: Assign Request - Complete Action**
* GIVEN a Restricted Request is in any state
* WHEN  a user is selected from the assignment list
* THEN a modal will pop out with the options to continue or cancel
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/978958615

**Scenario 4: Assign Request - Continue**
* GIVEN the Intake manager is on the restricted assignment modal
* WHEN the manager selects continue
* THEN the modal will close, and the user assignment will update

**Scenario 5: Assign Request - Cancel**
* GIVEN a user is on the restricted assignment modal
* WHEN the user selects Cancel
* THEN the modal will close, and the user assignment will remain as it was

**Scenario 6: Assign Watcher**
* GIVEN a Restricted Request is in any state
* WHEN the Intake manager clicks on the watcher assignment drop down
* THEN they will see all active IAO users

**Scenario 7: Assign Watcher - Complete Action**
* GIVEN a Restricted Request is in any state
* WHEN  the user is selected from the watcher list
* THEN a modal will pop out with the options to continue or cancel
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/978958614

**Scenario 8: Assign Watcher - Continue**
* GIVEN the Intake manager is on the restricted watcher modal
* WHEN the user selects continue
* THEN the modal will close, and the watcher assignment will update

**Scenario 9: Assign Watcher - Cancel**
* GIVEN a user is on the restricted watcher modal
* WHEN the user selects Cancel
* THEN the modal will close, and the watcher assignment will remain as it was

**Scenario 10: Un-Assign Watcher**
* GIVEN the Intake Manager is on a restricted request with the watcher drop down activated
* AND a user is already assigned as a watcher
* WHEN the user removes the assigned watcher as such
* THEN the user shall be removed as a watcher, and be unable to interact with the request. 

**Scenario 11: Can't Assign to Team Queue**
* GIVEN a user is on a restricted request
* WHEN they activate the assignment drop down
* THEN any IAO team names will be greyed out an unselectable

**Scenario 12: User other than Intake Manager Unable to Assign*
* GIVEN a user is on a restricted request
* AND they are NOT the Intake manager
* THEN the assignment and watching functions will be disabled
* AND the user will be unable to change the assignment or watcher

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Assignment Conditions and Restrictions re: Restricted requests cc @JHarrietha-AOT @lmullane @liseandtea

**Comment by m-prodan** [comment]
Ok this one has been written out now - I think I've at least captured the IAO requirements for watching. Assumption - we will need to create keycloak groups for each manager to be a part of to differentiate them from existing users when a request is flagged as "Restricted" - managers can then have analysts added to this group that will be working on those restricted requests.

**Comment by abin-aot** [comment]
Need to catch up for assignments , ball estimate for 13

**Comment by m-prodan** [comment]
Updated story to remove number of watcher restrictions, and opened up assignment list to all IAO

**Comment by JHarrietha-AOT** [comment]
@m-prodan Can you have a quick look at the designs and let me know if you have any changes to the wording. Links in Scenario 4 & 8

**Comment by m-prodan** [comment]
Updated AC for consistent experience, restrictions will be on any state after a file is restricted

**Comment by m-prodan** [comment]
@aparna-aot @richard-aot - per our conversation, updated the AC

**Comment by KyEggleston** [comment]
@aparna-aot 

Just one update for this ticket:

<h3>Scenario 7</h3>
Currently, the watcher modal lists the user's team and their username:

![image](https://user-images.githubusercontent.com/117312323/214975335-b84de97e-6270-481a-b0c6-2ad8d8a91cee.png)

However, can this be made to display the user's display name in FOI Mod:

![image](https://user-images.githubusercontent.com/117312323/214975530-041a6edb-1740-49bb-9521-3449d0a11bc7.png)

The [UI design](https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/978958614) uses 'username', but I think, instead, we would want the 'displayname' of the user..

**Comment by aparna-aot** [comment]
@KyEggleston Updated modal with display name is in DEV now. You can verify now. Thanks!

**Comment by KyEggleston** [comment]
Confirmed display name is now present in the modal - closing ticket.
