### ISSUE TITLE
Restricted Requests - Commenting and Tagging Conditions

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2985]
* As a user assigned to a restricted request
* I want to ensure that I can only tag those assigned to the request or the Ministry users
* so that I can ensure privacy and minimize confusion on a file if I tag someone else

**Assumptions & Scope**	
This story will govern comments, and how tagging needs to be handled similar to the user assignment restrictions

What is IN scope?
Tagging in comments

**Acceptance Criteria**	

**Scenario 1: Tagging user**
* GIVEN a user is on the comment tab and is entering a comment in the RT Editor
* WHEN they write an @ and the tag list populates
* THEN the only names that shall appear and can be tagged are users assigned to the request as watchers or primary assignees and the Ministry users

**Scenario 2: Tagging user - Notification**
* GIVEN a user is tagging another assigned user in the comment
* WHEN they select an assigned user and save the comment
* THEN the user will receive a notification that they were tagged in the comment

**Scenario 3: Attempting to tag other user**
* GIVEN a user is on the comment tab and is entering a comment in the RT Editor
* WHEN they write an @ and they manually write out a name that is not in the tag list
* THEN the text will not trigger a notification to that user, and no tag will be embedded in the comment

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by aparna-aot** [comment]
@m-prodan  Is this behavior applicable to Ministry Users/View as well?

**Comment by KyEggleston** [comment]
@aparna-aot - only one thing I noticed when testing these ACs. 

When a request is in a status of 'Intake In Progress' or 'Open', I am able to tag ministry users in the comments BEFORE it is assigned to their ministry queue (which occurs when you move a request to a status of 'Call For Records'). 

I believe we should only be able to tag ministry users in comments on restricted requests AFTER it has been assigned to them/their ministry queue (which occurs when moving a request to 'Call For Records').

For example, request # ABC-2099-8903890 is in a status of 'Intake In Progress', and the request was created with the ministry client being EDU. However, the request has not been assigned to the EDU ministry queue, but I am able to tag the EDU ministry users in comments.

After tagging an EDU ministry user in a comment, they get a notification:

![image](https://user-images.githubusercontent.com/117312323/215565579-7b69bc4b-82de-412b-b2dc-4f6ed6647b6d.png)

However, if they try to open the request to see the comment, they cannot access the request (as it isn't assigned to them/their ministry yet). They are only able to open the request after the request is assigned to their ministry queue. 

Would it be possible to look as restricting the tagging of ministry users until AFTER the request has been assigned to their ministry queue (by moving a request to a status of 'Call For Records')?

Let me know if you need any clarification!

**Comment by aparna-aot** [comment]
@KyEggleston That makes sense. I can update and let you know. Thanks!

**Comment by KyEggleston** [comment]
@aparna-aot - regarding the comment above, I will write a new ticket to address it. But for this ticket, all ACs pass (following discussions on business side) and I will close it.
