### ISSUE TITLE
Restricted Requests - System Generated Comments for Watchers

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2988]
* As an IAO user
* I want to know who was added or removed as a watcher on a restricted request
* so that I can have an audit trail to refer back to as needed.

**Assumptions & Scope**	
For regular requests, assigning or removing a watcher does not generated a comment - this is by design as the watcher feature is more of a transitory item in most cases; however, the watcher will carry a specific use case for restricted FOIs

System generated comments should be posted even if a user has made themselves the watcher, or removed as such. 

What is IN scope?
System generated comments for watching assignments on restricted requests

**Acceptance Criteria**	

**Scenario 1: Watcher Assigned**
* GIVEN a user has been selected as a watcher to a restricted request
* WHEN the action is completed and the assignments updated
* THEN a system generated comment will be posted in the request history saying "[USER] has made [USER] a watcher"

**Scenario 2: Watcher Removed**
* GIVEN a user has been removed as a watcher to a restricted request
* WHEN the action is completed and the assignments updated
* THEN a system generated comment will be posted in the request history saying "[USER] has removed [USER] as a watcher"

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by abin-aot** [comment]
@m-prodan  , We are having Notifications for Watchers, but not Sys. generated comments. Also, why specifically we need a Sys. generated comments for Restricted requests

**Comment by richard-aot** [comment]
To keep it consistent with system generated comment for assignee change, the message uses "Lastname, Firstname" instead of "username".

**Comment by KyEggleston** [comment]
All AC's pass, closing ticket.
