### ISSUE TITLE
Backdating Closed Date 

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2994]
**Describe the bug in current situation**
This issue was first reported by consolidated intake. They closed a request and had to backdate the close, when they viewed the request details, it was noted that the closed date was reflected as the day they closed the request, and not the backdated date they had selected.

**Link bug to the User Story**

**Impact of this bug**
Could impact reporting if backend is recording this as the actual closed date.

**Chance of Occurring (high/medium/low/very low)**
High - easily replicated, any backdated close is not reflected in the request details accurately

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Any request as an IAO user where the received and start date are prior to the current date
2. Change state to closed
3. Select date in the past as closing date
4. View request details, see incorrect closed date reflected.

**Expected behaviour**
GIVEN an IAO user is closing a request
WHEN they select a date in the past as the closed date
AND they hit save
THEN the closed date will be recorded as the date they selected. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
@aparna-aot has learned this is a front-end issue, so reporting shouldn't be impacted. Good catch!

**Comment by liseandtea** [comment]
@aparna-aot 
Completed steps to reproduce on 2 files and bug still happening. EDU-2022-25413 was backdated to Nov 4th and EDU-2022-16784 to Nov 6th. Both are showing as closed today (Nov 7th).
![1.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/be6b3ed8-c78d-46d0-8d33-c61884951fe2)
![2.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/a6433ba4-f724-429d-89c3-670700378f31)

**Comment by aparna-aot** [comment]
@liseandtea I think you have tested in test-marshal. This fix was directly to test environment and  that's why there is no **marshal** tag in the ticket. (https://test.foirequests.gov.bc.ca/foi). Can you test it there?

**Comment by aparna-aot** [comment]
@liseandtea I think you have tested in test-marshal. This fix was directly to test environment and  that's why there is no **marshal** tag in the ticket. (https://test.foirequests.gov.bc.ca/foi). Can you test it there?

**Comment by liseandtea** [comment]
@aparna-aot My apologies Aparna! You are correct and I was in the wrong environment. Retested again on EDU-2022-74125 (closed Nov 2) and EDU-2022-22925 closed Nov 5) , dates for both are showing correctly. We can close this!
![1.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/6e144544-8056-4eb1-ba42-8a8834f263f1)

![2.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/831886b0-2a04-495e-b959-765aff0c01e8)

**Comment by aparna-aot** [comment]
Thanks @liseandtea

**Comment by aparna-aot** [comment]
Thanks @liseandtea
