### ISSUE TITLE
Update Phone Number in Email Template

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3000]
Title of ticket: 
In training session - Intake flagged that the phone number for the email template is actually our fax number.

#### DOD
- [x] Update telephone number to 250-387-1321

**Comment by liseandtea** [comment]
Tested in fee estimate notification email, full payment email and partial payment email. All are showing the correct telephone number (250-387-1321). Issue resolved and closing ticket.

![1.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/f0820349-8489-475b-a850-5d4fc339bc54)
![2.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/c391e928-8cb6-41f0-bb89-66f8c71f8346)
![3.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/61336f36-099e-415f-98d0-b6d9b58a0539)
