### ISSUE TITLE
KeyCloak Custom realms Migration to Gold

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3002]
Title of ticket: 

#### Description

- At this stage (as 3/NOV/2022) with the known information , we need to find out how much work is involved 

- As per current info, we need to configure things on new KC  on Gold cluster and will need to move things by our own.

- There is deadline from their team like, this Dec End or max up to Jan end, 2023 

-  There are resources , support available on RocketChat and StackOverflow - effort depth need to be analyzed - Purely Devops though!
 -  https://stackoverflow.developer.gov.bc.ca/questions/864

- Please download this email/pdf for our next action from that team

[https://app.zenhub.com/files/358004325/2699af5b-13a5-4d16-b0a6-c53a001d5fbd/download](https://app.zenhub.com/files/358004325/2699af5b-13a5-4d16-b0a6-c53a001d5fbd/download)

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Configure REALM on Dev - @abin-aot has created same REALM name on GOLD as well, which was highlighted as an issue from KEYCLOAK - Need to follow up with Zorin and team
- [x]  Migrate Clients(Apps), Users Group on DEV/
- [x]  TEST first all functionalities LOCAL - For all Client Apps - FOI FLOW, FORMSWEB, API, CAMUNDA, Reporting etc. 
- [x] Confirm all integrations SSO , JWT Parsing on dev / dev-marshal. if there are any issues, revert to earlier KC set up
- [x] Comment below the steps taken on DEV, once the steps has been successful on DEV. 
- [x] Migrate Clients(Apps), Users Group on TEST. 
- [x] Confirm all integrations SSO , JWT Parsing on test/ test-marshal as per steps noted above(IMPORTANT!). if there are any issues, revert to earlier KC set up
- [x] Comment/Plan for the steps on PROD migration. Indicate any Adhoc steps

**Comment by sumathi-thirumani-aot** [comment]
@lmullane @m-prodan please close
