### ISSUE TITLE
New Issues found (Fee Processing)

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3004]
Title of ticket: 

#### Description
- [x] Camunda Migration issues fix
- [x] Sometimes the pay online form shows "Token Expired".
 
**Solution**
Show a modal to give user an option to refresh the page

- [x] Fee estimate and Outstanding Fee new validations

**Solution/Explanation**
If TotalActualsDue = 0 then show "Fee estimate" option in the contact applicant log

**Scenarios for Contact Applicant Log Options**

**Fee Estimate** Option will be enabled only if below conditions are true
1. Latest CFR Form should be in approved state
2. Balance remaining should be > 0
3. TotalActualDue <=0

**States allowed:** CFR, OnHold (User can use Fee Estimate option from contact applicant log only in these states)
Fee Estimate state is not allowed for contact applicant option

**Outstanding Fee** Option will be enabled only if below conditions are true
1. Latest CFR Form should be in approved state
2. Balance remaining should be > 0
3. TotalActualDue > 0

**States allowed:** OnHold (User can use Outstanding Fee option from contact applicant log only in these states)

- [x] Create CFR form is enabled in Response to On Hold state.

**Solution/Explanation**
Create CFR form should be disabled if the actuals are already entered. 

- [x]  AMOUNT PAID is enabled even after the outstanding balance is paid

**Solution/Explanation**
Disable amount paid if the balance payment method is populated/selected with value

- [x] Outstanding Fee payment receipt need to remove below part.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/7c4905a1-5618-4719-8769-1aa36d686693)

- [x] Update Estimate Amount Paid for the second time.
1. Pay online for the first time. 
2. create new CFR form version with more estimate amount
3. Applicant pay manually
4. Update the Amount paid. Only Balance Payment Method is editable.
Confirm the behavior. 

**Solution/Explanation**
As discussed in the standup, since this is a rare case, we created a separate ticket(#3080) to address the issue.

#### Dependencies
Are there any dependencies?

**Comment by divyav-aot** [comment]
@m-prodan - could you please review and comment on the scenario mentioned above related to contact applicant log.

**Comment by divyav-aot** [comment]
@m-prodan Could you please confirm on the last issue mentioned in the ticket.

**Comment by m-prodan** [comment]
These appear to all work as expected now - I did find some issues though that weren't related, and am going to write up some seperate bug tickets. Closing this ticket in the meantime.
