### ISSUE TITLE
Closed Requests - Days Remaining

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3008]
* As any user
* I want to see accurate metrics from the queue
* so that I don't need to click into the file to learn more

**Assumptions & Scope**	
This is a small feature relating to closed requests noticed during testing. When you search for closed requests, the days remaining appears to continue to count up, even though the request is closed.

It likely wasn't captured in the original story, but days remaining should become n/a since the request is closed, and days remaining is moot. 

What is IN scope?
Days remaining view on the queue for closed requests

**Acceptance Criteria**	

**Scenario 1: Days Remaining on Closed Requests**
* GIVEN a user is searching for closed requests
* AND the user has days remaining as a column for their queue
* WHEN  the queue populates
* THEN the days remaining will show n/a

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
Passes - closing ticket.
