### ISSUE TITLE
Restrict Request - Flagging (Ministry)

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3025]
* As a Ministry Coordinator/Manager
* I want the ability to restrict a request
* so that I can ensure access is controlled from the Ministry side

**Assumptions & Scope**
This story covers how a request can be flagged as restricted for Ministry users.

Flagging a request as restricted can ONLY be done by a specified position within the Ministry user group - this position may vary by Ministry

Flagging a request as restricted can occur at any request state from when the request is received and appears in the Ministry queue

The specified Ministry position will always see the restriction flag - users will only see the restriction flag if they are assigned to a request that is restricted.

Only the specified Ministry position, and Ministry users assigned to restricted requests, can see those requests in the system

Restricted Requests should not include any detail like request descriptions or other potential identifiers in the reports

What is IN scope?
Functionality to flag a request as restricted for the Ministry user group

What is NOT in scope?
Assignment Rules and Conditions (Covered in seperate user story # )
Reporting Rules and Conditions (Covered in Seperate user story # )
Comments and Tagging Rules and Conditions (Covered in separate user story # )

Acceptance Criteria

**Scenario 1: Restricted Request Setting - Specified Ministry Position**
* GIVEN the specified Ministry user is on the review request page
* WHEN the request is in 'Intake in Progress' or a later stage
* THEN the  specified Ministry user will see a flag indicating the request is Unrestricted

**Scenario 2: Activate Restriction Flag Dropdown**
* GIVEN a specified Ministry user is on the review request page
* AND the request is assigned to one user (not the team queue)
* WHEN they click on the "Unrestricted" Flag
* THEN a drop down will appear, and they will see the option to "Restrict" and "Unrestrict"
* AND Unrestrict will be greyed out and unselectable

**Scenario 3: Fail Activate Restriction Flag Dropdown**
* GIVEN a specified Ministry user is on the review request page
* AND the request is assigned to the team queue)
* WHEN they click on the "Unrestricted" Flag
* THEN a modal will appear, and they with the message "A request can only be restricted when it is assigned to one team member, not a team queue."

**Scenario 4: Select Restricted**
* GIVEN a specified Ministry user has activated the Restricted Drop down
* WHEN they selected "Restricted"
* THEN a modal will appear with the following message: [Design updated needed]
* AND There will be the option to Save Change or Cancel

**Scenario 5: Confirm Restricted**
* GIVEN a specified Ministry user is on the confirm restricted modal
* WHEN they selected Save Change
* THEN the modal will close, and the flag will update to Restricted

**Scenario 6: Cancel Restricted**
* GIVEN a specified Ministry user is on the confirm restricted modal
* WHEN they selected Cancel
* THEN the modal will close, and the flag will remain as unrestricted

**Scenario 7: UnRestrict**
* GIVEN a specified Ministry user has activated the Restricted Drop down
* WHEN they selected "UnRestrict"
* THEN a modal will appear with the following message: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/968974910/play
* AND There will be the option to Save Change or Cancel

**Scenario 8: Confirm UnRestrict**
* GIVEN a specified Ministry user is on the confirm restricted modal
* WHEN they selected Save Change
* THEN the modal will close, and the flag will update to Unrestricted

**Scenario 9: Cancel Unrestrict**
* GIVEN a specified Ministry user is on the confirm restricted modal
* WHEN they selected Cancel
* THEN the modal will close, and the flag will remain as Restricted

**Scenario 10: User other than Specified User Attempts to Unrestrict**
* GIVEN a user is assigned to a restricted request
* AND The user is NOT the  specified Ministry user
* WHEN they click on the restricted flag
* THEN a modal will pop out with the following message: [Design update needed - message update]
* AND the only option will be to cancel and close the modal

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
Could reduce estimate in future.

**Comment by aparna-aot** [comment]
KeyCloak Group Name : **Ministry Restricted Files Manager**. 

Steps to add users as Ministry Restricted Files Manager:
- Login to TEST-Keycloak : https://test.loginproxy.gov.bc.ca/auth/admin/foi-mod/console .
- Go to Users dashboard and search for the user whom you want to add as Ministry Restricted Files Manager.
- Click on the user and select Groups. From the Available Groups find Ministry Restricted Files Manager group and click Join.
- You can see "Ministry Restricted Files Manager" group in Group Membership.

**Comment by KyEggleston** [comment]
@aparna-aot - small text changes for update:

**Scenario 4**

From 
![image](https://user-images.githubusercontent.com/117312323/217962225-5e73dcdf-f2a1-4543-a875-d22dc52470c0.png)

To
![image](https://user-images.githubusercontent.com/117312323/217962365-af42032c-d025-4d2e-9f8c-ebc74496b149.png)


**Scenario 7**

From
![image](https://user-images.githubusercontent.com/117312323/217961538-87d4bbcf-0641-4b66-a9d6-1911edbedcb4.png)

To
![image](https://user-images.githubusercontent.com/117312323/217962566-4e8aa367-1307-4f1b-9c73-a1ab86873f27.png)

**Scenario 10**

We need a unique message for when a ministry user, who is not a Ministry Manager (Ministry Restricted Files Manager), tries to unrestrict a file. The current modal references the intake manager, but it should be the ministry manager. See images below. 

From
![image](https://user-images.githubusercontent.com/117312323/217961620-f2cb77c0-2263-4059-b123-9771bc0a0a51.png)

To
![image](https://user-images.githubusercontent.com/117312323/217961650-7ea579b8-3053-4e30-90be-7ccb2ad81b48.png)

**Comment by aparna-aot** [comment]
@KyEggleston Modal Text updates are pushed to TEST. Thanks!

**Comment by KyEggleston** [comment]
@aparna-aot - looks good, could we just remove "only" from the following modal (for grammatical correctness):

![image](https://user-images.githubusercontent.com/117312323/218531200-6db58822-582f-494c-ba24-4da2c0776bc4.png)


to read as:
![image](https://user-images.githubusercontent.com/117312323/218531508-e77e98e3-7b8c-40cf-9b1c-f585cf69103f.png)

Afterwards, I can close this ticket - thanks!

**Comment by aparna-aot** [comment]
@KyEggleston Oops! Missed 1 this time as well. Also a suggestion that it will be easy to identify the changes if you could highlight or underline the text like the above one . I will update this & let u know soon. Thank you!

**Comment by KyEggleston** [comment]
@aparna-aot - definitely, I was going to start doing that - thanks as always!

**Comment by aparna-aot** [comment]
@KyEggleston The update is pushed to TEST.

**Comment by KyEggleston** [comment]
Looks good - closing ticket.
