### ISSUE TITLE
API : Changes required to do server side pagination and search & sorting.

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#306]
Currently, all raw requests are fetched in a single call; and (search/sort) are being handled in client tier. This to be done on server side with pagination.

**Comment by abin-aot** [comment]
We might not require this , if we API calls are done based on conditions. We can discuss about this

**Comment by sumathi-thirumani-aot** [comment]
Refer https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/bcgov/foi-flow/1088
