### ISSUE TITLE
WF Reconciliation

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#3065]
#1) PROBLEM STATEMENT : WORK INSTANCES DOES NOT EXISTS OR HAVE INCOMPLETE WF INSTANCES to a CORRESPONDING FOI RESPONDING
CAUSES :#1 ) WF Create Issue , REDIS related  #2) FAST TRANSISTION #3) BECAUSE OF SOME ISSUE RELATED WITH UPGRADE/ MIGRATION/ ANYTHING ELSE

SOLUTION) 
AA) WE NEED TO DYNAMICALLY ATTACH A WF and/or CREATE A WF FROM BACKEND(REQUEST AMANGEMENT API) , using CAMUNDA API IF AN INSTANCE DOESNT EXISTS.
ST) : DO A CALL TO CAMUNDA DURING STATE TRANSISTION TO SEE WF INSTANCE

DOD 
- [x] create orphan WF or delete WF instances on an active FOI Requests, then while progressing with Request, see whether new WF instance is getting created or attached.

**Comment by divyav-aot** [comment]
closing this ticket as we already integrated the changes and pushed to test
