### ISSUE TITLE
Payment confirmation not sent when applicant's email updated

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3067]
**Describe the bug in current situation**

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
High
**Chance of Occurring (high/medium/low/very low)**
Medium. Confirm with Intake how often emails are updated.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to to a request in Fee Estimate with an approved CFR form
2. Click on the state dropdown menu and select 'On Hold'
3. Save Change. Request is now 'On Hold'
4. Confirm receipt of email to applicant
5. Go to Address and Contact Information. Change the applicant's email address
6. In email to applicant follow the steps to complete payment online. Successfully complete payment
7. No email received for confirmation of payment
8. The request remains 'On Hold' even though the applicant has paid. Test request TAC-2022-6658932
9. A system generated comment is posted that they paid
![Screen Shot 2022-11-18 at 7.59.07 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/3d9800a9-8aff-446c-a328-444da124c879)

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 
GIVEN an payment link has been sent to the applicant's email
WHEN an IAO analyst changes the applicant's email on the Address and Contact Information for the request
WHEN the applicant pays for the request on PayBC
THEN an email will be sent to the applicant's new email address
AND the applicant will be redirected to a page with a success message: "Payment Successful!
Transaction ID: FOITM00000207
 You have received an email regarding your request details and a copy of your receipt
If you would like to contact the Information Access Operations representative, please Email FOI at: FOI.Requests@gov.bc.ca, or call, Phone: 250-387-1321 | Toll Free: 833-283-8200"
AND the email will include the order ID, transaction number, amount and receipt of payment

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
Good morning @arielleandrews 

Question for you - how often do applicant's emails change?

**Comment by arielleandrews** [comment]
It's most common with law firm applicants. The lawyer might submit the initial request themselves but want their paralegal/admin support to receive any future correspondence or vice versa, or a different lawyer may take the file over later down the line. Similar situations come up with business or interest groups. It is less common with individuals but definitely happens.

**Comment by divyav-aot** [comment]
Hi @lmullane , We analyzed the issue and found that there was a migration error in the backend and also few requests where not migrated to the latest WF version. This issue shouldn't happen for the new requests. We will let you know once we are done with the fix. Also, the request will not change from OnHold to CFR as the user paid amount with correspondence email. 
@sumathi-thirumani-aot @abin-aot

**Comment by divyav-aot** [comment]
I have fixed the migration issue and WF instances are migrated to the latest version. You shouldn't face any issue with old request. Below requests are still in Fee Estimate states similar to the one you mentioned above.
EDU-2022-6652147
EDU-2022-6683214

**Comment by liseandtea** [comment]
Followed steps to reproduce and issue is resolved.
 
Used request EDU-2022-44574, original email was lise.mino@gov.bc.ca which was changed to liseandtea@yahoo.ca. After payment was made, the receipt email went to the yahoo email address.
![gov email.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/de8f1d90-a15d-4617-812d-1613ded76960)

![yahoo email.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/6755ea4a-982c-4a93-8d91-7bebb5d52f58)

After payment was made request status automatically updated from "On Hold" to "CFR" for IAO and EDU.

![IAO.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/a677a91b-4d06-458c-a43a-0ef4c9f51fd2)

![EDU.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/059f6094-cc8a-42d9-a506-276c81cf3e26)
