### ISSUE TITLE
Update your API Access Credentials for CHES and CDOGS

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3068]
Title of ticket: 

#### Description
What is happening?
Access to our hosted services is migrating to leverage the API Services Portal at api.gov.bc.ca.
The following two APIs are affected:

  *   Common Hosted Email Service (CHES)
  *   Common Document Generation Service (CDOGS)
If you currently use either of these services, you will need to request a new set of credentials using the API Services Portal.

Why?
We believe the API Services Portal and Gateway service offered by a dedicated team at the Ministry of Citizen Services will provide a better onboarding service for our API consumers. This move also allows us to reduce duplication of efforts and resources (such as Keycloak realms and the onboarding web interface)

When is this happening?
Please request access through the Portal at your earliest convenience. You are encouraged to start using the new credentials and endpoints as soon as possible.
At the end of December 2022, access to these services using your old credentials will no longer work.

What should You do?

  1.  Go to the API Services Portal<https://api.gov.bc.ca/devportal/api-directory> and find the CHES and/or CDOGS API in their Directory.
Click ‘Request Access’ and sign into the portal. Fill in our request form and choose the environment you want to access. Please provide contact information of the Product Owner as well.  This must be repeated for each environment.
  2.  The Common Service Showcase team will complete the request and notify you soon after and your credentials will become active.
  3.  Update your client application with the new credentials and API endpoints.
Important Notes:

  *   With this change, you will now require a separate set of credentials (Client ID and Client Secret) for each of our hosted services that you use. The token endpoint will be the same for both services.
  *   The API hostname is changing for both API’s. Please call these new endpoints:
     *   CHES:
        *   https://ches-dev.api.gov.bc.ca (dev)
        *   https://ches-test.api.gov.bc.ca (test)
        *   https://ches.api.gov.bc.ca (prod)
     *   CDOGS:
        *   https://cdogs-dev.api.gov.bc.ca (dev)
        *   https://cdogs-test.api.gov.bc.ca (test)
        *   https://cdogs.api.gov.bc.ca (prod)
  *   These new credentials will continue to use the same existing OIDC client credential grant flow.
If you have any questions, please feel free to contact us in the #nr-common-services-showcase RocketChat channel or by email **nrm.commonserviceshowcase@gov.bc.ca<mailto:nrm.commonserviceshowcase@gov.bc.ca>**

#### Dependencies
Are there any dependencies?

#### DOD
- [x]  Update the API Credentials on Common Service as per the email message above.
- [x]  Check Receipt generation for Fee payment - DEV, TEST, 
- [x] Check functionality on Angular App Payment API - DEV, TEST, 
- [x]  Plan for Prod. update - Angular
- [x]   Plan for Prod. update- Fee Payment
- [x] Add all Devs and @lmullane , @m-prodan into new CDOGS API client - DEV, TEST, PRD - As admins - This is NOT a show stopper for PROD release on Dec / 12

**Comment by divyav-aot** [comment]
Our application uses only CDOGS. 
dev - Received the API credentials and updated the ENVs. Receipt generation is working fine in Applicant facing application as well as foi-flow.

**Comment by m-prodan** [comment]
Plan to release to prod monday afternoon (Dec 12)

**Comment by abin-aot** [comment]
Added new DOD - @divyav-aot . As discussed we need all devs, Loren, Matt - But this wont stop our release!

**Comment by divyav-aot** [comment]
**Prod deployment notes:**

The below ENVs needs to updated for the prod release and restart the pods.
CDOGS_BASE_URL
CDOGS_SERVICE_CLIENT
CDOGS_SERVICE_CLIENT_SECRET
CDOGS_TOKEN_URL

**Comment by divyav-aot** [comment]
We had a discussion with Sharolyn from the common services team and found that there is no team management feature to the new api portal. Due to this I won't be able to add others to the new CDOGS client. They advised us that it would be better the PO create the credentials. 
**Drawbacks are:**
1. Only the person who creates the application has the access to that application.
     Application is needed to request for new CDOGS credentials.
2. You will not be able manage the existing credentials if you are not the owner of the request.
    That means, if any issue with the generated credentials, then only the owner of the request can re-generate the credentials.

cc. @lmullane @m-prodan @abin-aot

**Comment by divyav-aot** [comment]
Deployed to prod. hence closing the ticket
