### ISSUE TITLE
Conversion of .DOC, .MSG, .ICS type Attachments of .MSG, .ICS files

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#3075]
Title of ticket: 

#### Description
Save Attachments of .MSG, .ICS files back to Redis Stream. If any of the attachments is a .DOC, .MSG, .ICS file pass it back to the Redis Queue for conversion to pdf

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Get list of attachments from .MSG , .ICS files
- [x] Add producer logic in .net.
- [x] Code cleanup
- [ ] 
- [ ]

**Comment by KyEggleston** [comment]
.MSG and .ICS conversion issues are resolved in Test-Marshal, closing ticket.
