### ISSUE TITLE
Document reviewer - fetch document from S3

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#3078]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] fetch S3 credentials from mapper
- [x] fetch bucket based env
- [x] fetch document from S3
- [x] deploy to dev env

**Comment by m-prodan** [comment]
@richard-aot - can you provide an estimate for this task?
