### ISSUE TITLE
Backend work for saving document to S3 #3231

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#3079]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] logic for document version
- [x] workflow for saving edited (sorted, rotated, redacted, etc.) document
- [x] save edited document to S3

**Comment by m-prodan** [comment]
@richard-aot - can you put an estimate on this task?

**Comment by lmullane** [comment]
This task needs a user story.

As an IAO analyst
I want to be able to accept all redactions
So that I can save the response package (in the S3 bucket) so that the package can be released to the applicant.

This will happen after Ministry Sign Off (i.e., approval of the redline)
