### ISSUE TITLE
Fee Estimate Payment Method disabled for certain cases

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3080]
Title of ticket: 

#### Description
Estimate Payment Method disabled for certain cases. Below are the steps to reproduce the issue.
1. Pay online for the first time.
2. create new CFR form version with more estimate amount
3. Applicant pay manually
4. Update the Amount paid. Only Balance Payment Method is editable.

Estimate payment method should be editable when the user enter amount paid of a fee estimate.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by KyEggleston** [comment]
Resolved in #3004 - closing
