### ISSUE TITLE
Deployment of Dedupe Services to OCP SILVER , d106d6-*

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3081]
Title of ticket: 

#### Description
The purpose of this task is to deploy Dedupe services functionality till Rank1 Duplicate - #2835, which can be then easily integrated with Gathering records - Document statuses and Dedupe API endpoint

#### Dependencies
Are there any dependencies?

#### DOD
- [x]  Create YAML build, deploy templates for Dedupe Services
- [x]  Bug fix any issues related with communication, Redis Streams etc.
- [x]  Configure CI/CD for Dedupe Services
- [x]  Create build and deploy YAML templates and setup CI/CD for File Conversion
- [x]  Setup Patroni in d1
- [x]  Move all doc reviewer app in dev to d1-dev
- [x]  Move all doc reviewer app in test to d1-test
- [x]  Set up Dev, TEST - REDIS STREAMS and Integrate deployed Dedupe Services on d106d6-*

**Comment by m-prodan** [comment]
@richard-aot to connect with @divyav-aot before configuring CI/CD (step 3)

**Comment by m-prodan** [comment]
temporarily blocked waiting on resource increase request

**Comment by richard-aot** [comment]
We received more resources in d1 project. This task is completed.
