### ISSUE TITLE
UX Design - Customizations to Page Flags in PDF Tron

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#3088]
Title of ticket: UX Design - Customizations to Page Flags in PDF Tron

#### Description
Work through the first draft of customizations for PDF Tron for Page Flags

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Review existing list of Page Flags in AXIS
- [x] Create proposed list for new reaction app
- [x] Identify which pages flags need icons in custom left pain
- [x] Create icons/visual signifiers for page flags

**Comment by lmullane** [comment]
Good morning @JHarrietha-AOT, for these designs  I would like to mirror the design aesthetic of PDFTron. cc @m-prodan

**Comment by JHarrietha-AOT** [comment]
https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/975452421

**Comment by JHarrietha-AOT** [comment]
@m-prodan  @lmullane Designs for Page Flags with Icons - https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/975452421

Let me know if you have any questions
