### ISSUE TITLE
UX Design - Scanning Team in Gathering Records

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#3089]
Title of ticket: UX Design - Scanning Team in Gathering Records

#### Description
Creates designs and process flow for users on Scanning Team to have the ability to upload scanned physical records into the new system

#### Dependencies
Expectations of Scanning Team and Process walkthrough and UX Research will Scanning Team

#### DOD
- [x] Finish reviewing and documents provided by scanning Team
- [x] Work on User Flow for how we expect Scanning Team to work in out new system
- [ ] Run Flow by dev team
- [ ] Create design update for UX Changes based off of completed flow
- [ ] Demo design changes to Scanning Team for first level of approval
- [ ] Demo out design changes and Sprint Demo

**Comment by lmullane** [comment]
@JHarrietha-AOT, update DOD and split; close this ticket with a revised estimate and create a new ticket for the future in the backlog.
