### ISSUE TITLE
"Received Date" date picker selection not reflecting the change/picked up date

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3094]
**Describe the bug in current situation**
The "Received Date" date picker selection not reflecting the change/picked up date . It always display like below , even if I select a date from the pop out menu on date picker. But behind the scene its capturing selected date and once we click Save of FOI Request, it displays correct date. Causes a slight confusion!.

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/19746aec-0860-4a7d-8567-5946d975cc87)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
High - This will happen each time a new request is received and opened. 

**Pre Conditions: which Env, any pre-requisites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a FOI Request as IAO
2. Click on Received Date picker and select a date
3. After selecting a date, date field still shows date mm/dd/yyyyy. But behind the scene its capturing date

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherkin language. 

GIVEN an analyst is opening a request and is choosing the request received date
WHEN an IAO analyst clicks on the calendar icon to open the date options
AND the IAO analyst chooses the correct date option
THEN the date chosen will appear in the "Received Date" field

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You can use screengrab.

**Comment by m-prodan** [comment]
Issue appears to be fixed as expected - nice work @aparna-aot
