### ISSUE TITLE
Confirmation of Payment Email - Missing LDD

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3106]
**Describe the bug in current situation**
While testing scenarios, it was observed that the confirmation of payment email is no longer including the new legislated due date of the request. 

**Link bug to the User Story**
#2543

**Impact of this bug**
Applicants should receive the new legislated due date with confirmation of payment. This will require analysts to duplicate work and provide the confirmation of payment letter to the applicant and increase steps for them.

**Chance of Occurring (high/medium/low/very low)**
High - occurs anytime a payment is made. 

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Pay for a fee estimate, or outstanding balance using online pay
2. Receive confirmation email
4. New legislated due date no longer appears in the template

**Actual/ observed behaviour/ results**

**Expected behaviour**
Scenario 1: Receive Confirmation Email

* GIVEN the user is on the PayBC Credit Card Screen
* AND the user enters a valid CC number, Expiry, and CVD
* WHEN the user clicks 'Pay'
* THEN an email will be sent to the applicant
* AND the email will include the order ID, transaction number, amount and receipt of payment
(Receipt designs: https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922730570 - email confirmation design: https://jacklyn808742.invisionapp.com/console/share/RSBDPXJGKAW/922766192)

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/5709f0c1-e00d-40d8-ae31-fdcfa6a35814)If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by divyav-aot** [comment]
@m-prodan - As per the discussion, we removed the LDD from the email. This is due to the automated state transition is not happening if the applicant pay the amount from the correspondence mail. We will bring back the LDD as part of that user story.

**Comment by lmullane** [comment]
No estimate required as effort is covered in #3142
