### ISSUE TITLE
CFR Changes causes Extensions attachment upload to break

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#3125]
Some CFR code changes have caused extension attachment upload to break

**Link bug to the User Story**

**Impact of this bug**
low - confirmed users are currently only syncing extensions from AXIS and are not using attachment functionality

**Chance of Occurring (high/medium/low/very low)**
high - happens every time

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
right now only in dev - if proceed with release, will go to test and prod

**Steps to Reproduce**
- open any request in open state or after
- add extension
- choose oipc, approved
- add attachment in upload box
- try to save
- red toast

**Actual/ observed behaviour/ results**

**Expected behaviour**
should save

![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/d8ebeee1-dbc2-449c-85e9-c965a8c04d62)
![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/6c7201bc-0f69-4fe9-a193-285404717c23)

**Comment by divyav-aot** [comment]
This should be fixed along with Restricted File release if the extensions are handled in foi-flow
@abin-aot @lmullane @m-prodan

**Comment by nkan-aot** [comment]
this needs to be fixed as part of #3483 so moving to in progress

**Comment by KyEggleston** [comment]
This is resolved in [Dev](https://dev.foirequests.gov.bc.ca/). Still appears in Dev-Marshal, but I assume that is known.

**Comment by nkan-aot** [comment]
@KyEggleston it will be merged to dev-marshal after release to prod
