### ISSUE TITLE
Delete and download a record in the Gathering Records log

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3136]
* As a ministry coordinator 
* I want to delete a record
* so that records no longer in the package

* As a ministry coordinator or IAO analyst*
* I want to download record
* so that I can review the record on my deskstop in case the redaction app is unavailable

**Assumptions & Scope**	
What are the assumptions for this story?
IAO analysts or ministry coordinators may need to download or view a file. Sometimes they need to download the file in the original file format if the file has been converted to PDF.

Ministry coordinators may need to delete a record that is uploaded. For example, if a request is narrowed, the record may no longer be responsive. IAO will have this permission as well.

IAO sometimes may need to rename a record for ease of redaction, but this will happen in the redaction app, not the Gathering Records log.

The ellipsis will be active even if the record removal and conversion has not been completed.

These actions will be taken on the source files and will not include any redaction layers.

These actions are not restricted by the state of the request.

Delete will be a soft removal. 

What is IN scope?

What is NOT in scope?
Renaming a request.
Dedupe and file conversion, #3120
Downloading converted files in PDF or the original file format
Notifications when dedupe and file conversion is complete, #3119
Export All (i.e., bulk downloads)

**Acceptance Criteria**	

**Scenario 1: Ellipsis on Gathering Records Log**
* GIVEN a ministry coordinator or IAO analyst is on the Gathering Records log
* WHEN the records have been uploaded
* THEN there will a blue and active ellipsis for each record
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975255939

**Scenario 2: Click on Ellipsis for record that has not been converted**
* GIVEN a ministry coordinator or IAO analyst is on the Gathering Records log
* AND the records have been uploaded
* WHEN the user clicks on the ellipsis next to a record
* AND the file has not been converted to PDF
* THEN a dropdown will open with these options: Download, Delete

**Scenario 3: Download**
* GIVEN a ministry coordinator or IAO analyst has clicked on the ellipsis for a record
* WHEN the user clicks on 'Download'
* THEN the record will be downloaded to the the user's desktop in the original format

**Scenario 4: Download PDF**
* GIVEN a ministry coordinator or IAO analyst has clicked on the ellipsis for a record
* AND the record has been converted to a PDF
* WHEN the user clicks on 'Download PDF'
* THEN the record will be downloaded to the the user's desktop in PDF format

**Scenario 5: View PDF record in browser tab**
* GIVEN a ministry coordinator or IAO analyst is on the Gathering Records log
* AND the records is a PDF
* WHEN user clicks on the record title
* THEN the record will be displayed in a new browser tab

**Scenario 6: Delete record modal**
* GIVEN a ministry coordinator or IAO analyst has clicked on the ellipsis
* WHEN the user clicks on Delete
* THEN the a delete records modal will open
* AND there will be a 'Delete Record' and 'Cancel' button
* AND a message, "Are you sure you want to delete this record? If you delete this record, the record will not appear in the redaction app for review by IAO."
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/957399284

**Scenario 7: Delete record**
* GIVEN a ministry coordinator or IAO analyst is on the delete records modal
* WHEN the user clicks on Delete
* THEN the record will be deleted and removed from the Gathering Records log

**Scenario 8: Cancel delete record**
* GIVEN a ministry coordinator or IAO analyst is on the delete records modal
* WHEN the user clicks on Cancel
* THEN the delete record modal will close
* AND the user will remain on the Gathering Records modal

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Pre-deployment Steps**

- [ ] set env variables DEDUPE_STREAM_KEY and FILE_CONVERSION_STREAM_KEY to doc reviewer api in openshift

**Comment by lmullane** [comment]
@JHarrietha-AOT, @abin-aot, please review.

cc @m-prodan, @liseandtea, @KyEggleston

**Comment by m-prodan** [comment]
I assume the export button will be a seperate user story for batch download of records (ie: by division, or all records)?

Otherwise - looks good to me!

**Comment by JHarrietha-AOT** [comment]
@lmullane I think we need to add a modal for when a user selects delete in the ellipses just to explain this will delete the record from the Gather Records Log, but if it has been converted it will also be deleted from the redaction app. I'll get a design for this in before stand-up

**Comment by JHarrietha-AOT** [comment]
@lmullane here is a link when you can click on delete in the ellipse and get the modal I was referencing above that I think we should add. https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975255939

**Comment by lmullane** [comment]
Thanks, @JHarrietha-AOT. A modal is a good call.

Could we change the language in the modal to read:

"Are you sure you want to delete this record? If you delete this record, the record will not appear in the redaction app for review by IAO."

**Comment by JHarrietha-AOT** [comment]
@lmullane Message is updated in prototype

**Comment by sumathi-thirumani-aot** [comment]
Questions
----------
A) "Download PDF" : Our assumption is like, PDF of DOCX without any redliniing, comments etc.- even if the review in progress
B) "Relevance of Converted PDF from DOCX/XLSX/MSG/ICAL" - If we are providing original file to download/view then why PDF version "on FOI FLOW" - PDF will make sense more on Redaction viewer? 
C) "IF"(yes to B) Download for PDF FOR CONVERSION is requried ,  Is it possible to move "Download as PDF" for convered files to a different user story - this is because conversion services need to be deployed.


D) *Curiosity : Do we need AUDIT on deleting records? - WHO/WHEN/WHAT ??
E) *Curiosity : VALIDATION ON DELETE - What if someone is doing HARMS ASSESMENT/REDLINING/redacting ? STATE ? / REVIEW IN PROGRESS / Constrainsts?

F) DELETED FILES RETENTION POLICY ?

Backend
--------
1. Addiontional Column - Model, Migration script
2. Create new service for DELETE 
3. Create new API for DELETE


Frontend
-----
1. Service - API Integration
2. Download the API
 
Estimate - 8

**Comment by nkan-aot** [comment]
DB diagram for recording all dedupe and file conversion jobs in a batch
![batch_job_record.jpg](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/9c3c3467-5fa8-4718-8ab1-5b54ea992eb9)

**Comment by lmullane** [comment]
Scenario 3 and 4 are not testable currently as MS files do not appear to convert to PDF. @nkan-aot, let's discuss during standup.

**Comment by KyEggleston** [comment]
@nkan-aot a few things I noticed following testing the ACs. All testing done on a new request, EDU-2022-88776 in Test-Marshal.

<h3>Scenario 2</h3>
Currently, when a PDF file is uploaded to the Records tab (and doesn't need to be converted), the only options under the ellipsis are 'Download' and 'Delete', which is correct. However, I'm not sure how to test other file types (i.e., non-PDFs) which may be uploaded but not converted to PDFs. Presumably, if a non-PDF file is uploaded, and it is not converted to a PDF, it would have failed conversion and show up as an error. Maybe it's just the way this AC was written which was confusing, and it's only referring to when you upload a PDF that doesn't need file conversion. 

<h3>Scenario 5</h3>
When I click on the record title, the PDF does not open in a new browser tab.

<h3>Scenario 6</h3>
This AC passes, but the modal language needs to be updated. The modal language needs to be updated to match the updated design - https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/957399284.

<h4>Old</h4>

![image](https://user-images.githubusercontent.com/117312323/212185795-d539e100-c180-4a21-ad16-af99226193db.png)

<h4>New</h4>

![image](https://user-images.githubusercontent.com/117312323/212185305-da6195bb-3ea5-4ccf-82b0-319a2717240f.png)

<h3>Other</h3>

Through testing this ticket, and looking at #2977 and #2976, I noticed that .MSG and .ICS files, after they are converted to PDFs, are unable to be opened (as their PDF version). 

For example, an .MSG or .ICS file runs through dedup and file conversion successfully (green checkmark). After, when selecting ellipsis -> Download PDF, the PDF downloads, and then when trying to open the downloaded PDF I receive the following error when it tries to open in the browser:

![image](https://user-images.githubusercontent.com/117312323/212186865-6d430684-6d4f-40d3-9c4f-bccb04a77739.png)

When trying to open it in Adobe Acrobat:
![image](https://user-images.githubusercontent.com/117312323/212186972-7e09e691-c965-417d-90d9-15314275cb91.png)

**Comment by nkan-aot** [comment]
hey @KyEggleston For scenario 2 Jackie has mentioned there is another design coming for files which are incompatible with PDF tron

I will fix scenario 5 and 6 and I am looking into why converted msgs can't be opened

**Comment by KyEggleston** [comment]
@nkan-aot - this all passes, except one modal update:

<h2> Scenario 6</h2>
The modal that appears after selecting ellipsis -> Delete next to a records on the Records tab needs to be updated to match the updated design - https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/957399284.

It looks like it's using the same modal language as the 'Attachments' tab currently.

<h4>Old (to be changed)</h4>

![image](https://user-images.githubusercontent.com/117312323/212185795-d539e100-c180-4a21-ad16-af99226193db.png)

<h4>New</h4>

![image](https://user-images.githubusercontent.com/117312323/212185305-da6195bb-3ea5-4ccf-82b0-319a2717240f.png)

**Comment by KyEggleston** [comment]
All updates made, closing.
