### ISSUE TITLE
Disable any active payment link after request is closed

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#3137]
Need to ensure that any active payment links are disabled after a request is closed. Do not want applicant paying any outstanding fees if request is closed

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Add WF logic to update submission in forms flow if request is closed
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by KyEggleston** [comment]
Closing, as this appears to have been resolved with #3135 - confirmed payment links are inactive when request is moved to 'Closed' (in TEST)

![image](https://github.com/bcgov/foi-flow/assets/117312323/7deadc3e-478b-48b2-a803-c867fa30aa60)
