### ISSUE TITLE
Continue button not greyed out when 'Add Files' field is blank

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3152]
**Describe the bug in current situation**
Under the _Records_ tab, when a user uploads a file/folder through the 'Upload Records' modal, and then immediately selects 'Upload Records' again, the user is able to click 'Continue' without attaching a new file/folder.  If the user clicks 'Continue' without adding a new file/folder, the initial file/folder that was uploaded will be reuploaded. 

**Link bug to the User Story**
[User Story # 2779](https://github.com/bcgov/foi-flow/issues/2779)

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Low
**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Tested in TEST-MARSHAL on record # EDI-2022-01234, with user foiedu@idir (ministry coordinator role). Tested on Microsoft Edge, Chrome and Firefox. 

**Steps to Reproduce**
1. Under the _Records_ tab, click the 'Upload Records' button to open the Upload Records modal
2. Add a file/folder using the "Add Files" option, or by dragging and dropping a file/folder.
3. Click "Continue", and the file/folder should be uploaded.
4. Click the 'Upload Records' button again.
5. There should be no files/folders in the "Add Files" field, but the "Continue" button should be available to select (i.e., not greyed out). 
6. If you click the "Continue" button, the initial file/folder you uploaded will be uploaded again (it will be a duplicate). 

**Actual/ observed behaviour/ results**
GIVEN you have just uploaded a file/folder through the 'Upload Records' modal (under the _Records_ tab)
AND you have not left the _Records_ tab
WHEN you click 'Upload Records' to open the Upload Records modal
THEN the 'Continue' button is not greyed out, and you are not required to add a new file/folder
AND if you click 'Continue' when the 'Add Files' field is empty, the initial file/folder you uploaded will be reuploaded. 

**Expected behaviour**
GIVEN you have just uploaded a file/folder through the 'Upload Records' modal (under the _Records_ tab)
AND you have not left the _Records_ tab
WHEN you click 'Upload Records' to open the Upload Records modal
THEN the 'Continue' button should be greyed out until you must add a new file/folder. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

1. Below is the initial file/folder being uploaded. After the file was added to the 'Add Files' field, the continue button was clickable (i.e., no longer greyed out). After clicking 'Continue', the file is uploaded and posted on the _Records_ tab. This is expected functionality. 

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/deca4d9b-37a0-4618-b437-3a209d56a4bd)

2.  Without leaving the _Records_ tab, when you click the 'Upload Records' button again, the 'Continue' button is not greyed out when the 'Add Files' Field is empty. This is not the expected functionality. 

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/c110510f-7649-4b3e-9781-0975f8fc6255)

3. If you click 'Continue' when the 'Add Files' field is empty, the initial file/folder you uploaded (in Step 1 above) will be reuploaded. See the last four records in the image below. 

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/af837718-401c-4822-b861-ced0fca208ce)

**Comment by divyav-aot** [comment]
Thanks @KyEggleston.  @nkan-aot could you please look into this issue?

**Comment by nkan-aot** [comment]
i think it can be closed, cc @abin-aot @lmullane what do you think?

**Comment by lmullane** [comment]
I will close it and tag it to go with the Fees Release.

**Comment by divyav-aot** [comment]
@lmullane This is part of Gathering records. Hence changing the release tag to Gathering Records.
