### ISSUE TITLE
Remove attachments

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3162]
* As an IAO flex user
* I want to be able to bulk remove attachments after a ministry coordinator uploads a batch of records
* so that I can remove them from the records package when they are not responsive

**Assumptions & Scope**	
What are the assumptions for this story?

While IAO likely will be the only group removing attachments, the ministry will be able to remove Attachments too.

Include attachments in EML, PDFs, Calendar files, etc.

Often request descriptions exclude attachments from a request. In this case, IAO or the ministry manually removes attachments from files stored on the LAN.

We need a user action to ensure attachments loaded into the new system, do not become part of the records package when they are not responsive to the request.

Assumption is that more often attachments are included so the default will be to include attachments.

If attachments are to be removed, they do not need to be saved in Object Storage.

What is IN scope?
Bulk removal of all attachments

Backend - remove attachments if checkbox is not clicked and do not store in Object Storage.

What is NOT in scope?
Removal of individual attachments

**Acceptance Criteria**	

**Scenario 1: Remove attachments button**
* GIVEN a ministry coordinator uploads a batch of records
* AND there were attachments
* WHEN the IAO analyst or ministry coordinator is on the Records log
* THEN there will be a button for "Remove Attachments" 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975457479

**Scenario 2: No attachments, no Remove Attachments button**
* GIVEN a ministry coordinator uploads a batch of records
* AND there were no attachments
* WHEN the IAO analyst or ministry coordinator is on the Records log
* THEN there will be no button for "Remove Attachments" 

**Scenario 3: Remove Attachments modal**
* GIVEN an IAO analyst is on the Records log
* AND there were attachments uploaded
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975457479
* WHEN the IAO analyst clicks the button for "Remove Attachments" 
* THEN a modal will open with a message, "Are you sure you want to remove attachments from this request? This will remove all attachments from the Gathering Records log and the redaction app."
* AND there will be button for "Remove Attachments" and "Cancel"
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975457479

**Scenario 4: Cancel Remove Attachments**
* GIVEN the IAO analysts is on the Remove Attachments modal
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975457479
* WHEN the analyst clicks the "Cancel" button
* THEN the modal will close
* AND the analyst will remain on the Records log
* AND no attachments will be removed

**Scenario 5: Click Remove Attachments**
 * GIVEN the IAO analysts is on the Remove Attachments modal
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975457479
* WHEN the analyst clicks the "Remove Attachments" button
* THEN the modal will close
* AND the analyst will remain on the Records log
* AND all attachments will be removed from the Records log
* AND all attachments will be deleted from Object Storage
* AND all attachments will be removed from the records package in the redaction app

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/957399285

**Pre-Deployment Steps**
set forms-flow-web config map in openshift REACT_APP_DOCREVIEWER_BASE_API_URL
set cors config in docreviewer secret to accept requests from request management web url

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, here is the story to go with the designs. Let me know if the AC align with your thinking?

cc @m-prodan, @abin-aot, @nkan-aot, @aparna-aot

**Comment by JHarrietha-AOT** [comment]
@aparna-aot https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/957399285

**Comment by lmullane** [comment]
As discussed, @aparna-aot in Scenario 4 when attachments are removed then the records will not appear in the Records log. 

It will be the equivalent of when a user deletes a record. In both cases the records would be removed because they are unresponsive.

**Comment by KyEggleston** [comment]
@lmullane @m-prodan - confirm with flex team on Thursday (January 12) about applicants requesting to exclude email attachments from a request, and whether that includes excluding all embedded files as well. 

cc: @KyEggleston @liseandtea @JHarrietha-AOT

**Comment by lmullane** [comment]
@nkan-aot, have you done any work on this yet?

**Comment by nkan-aot** [comment]
no, very shortly after i started Jackie said the design was changing as a result of the meeting with flex team

**Comment by JHarrietha-AOT** [comment]
@lmullane Here is a link to the updated design for removed attachments. It will be a button that only appears for IAO users as suggested by the flex team https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975457479

**Comment by lmullane** [comment]
As discussed, I will update the AC.

**Comment by lmullane** [comment]
Hi @JHarrietha-AOT, thanks for the updated designs.

I have updated the AC. Couple of questions for you and @m-prodan. 

1. Should only IAO be able to remove attachments? See scenarios 1 &2
2. Should there be a button for remove attachments if there are no attachments in the records? 

cc @KyEggleston @liseandtea @nkan-aot

**Comment by m-prodan** [comment]
1 - I think we heard from demo/feedback that flex team/IAO wanted more control over the removal of attachments, there was concern that it could be done in error. Having that said, I don't think its unreasonable to also give that to the Ministry coordinators as well. Those that are keen may want to do so - in addition, it may be helpful for them from a harms assessment perspective to be able to remove the attachments before sending them out to the program areas after they gather.

2. Perhaps the button will just be inactive if there are no attachments?

**Comment by nkan-aot** [comment]
@lmullane @JHarrietha-AOT right now the button is not visible if there are no attachments, this is the same behaviour as the export button being not visible when there are no records uploaded. Let me know if you want it changed

**Comment by lmullane** [comment]
Thanks, @nkan-aot and @m-prodan 

I have updated scenario 1 and 2 to reflect that the ministry coordinator can remove attachments and that there will be no button when there is no attachments.

Allowing the ministry to remove the attachments gives us more flexibility for future business processes.

This ticket should be good as is.

**Comment by KyEggleston** [comment]
@nkan-aot - only update is to have the language in the 'Remove Attachments' modal under the 'Records' tab to be updated. 

Currently it reads:

![image](https://user-images.githubusercontent.com/117312323/218797628-9d85c801-dd5d-4019-8779-bb755f40b61b.png)


This needs to be updated to also mention the gathering records log: 

![image](https://user-images.githubusercontent.com/117312323/218798404-ee96bf46-7f96-422f-96c1-b5d9473232c4.png)

**Comment by KyEggleston** [comment]
@nkan-aot - sorry, one other minor thing I noticed. Attachments on the 'Records' tab show a user of 'conversionservice' as being the uploader. I believe this should be updated to reflect the user that uploaded the parent file? 

![image](https://user-images.githubusercontent.com/117312323/218803501-d39eddda-0cd4-46ca-84f5-ffb862f75d96.png)

**Comment by aparna-aot** [comment]
@KyEggleston Fixed the uploader issue. Please verify in test-marshal. Thanks!
![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/f1eba5f0-2677-4c13-b7e8-532c455b47f3)

**Comment by KyEggleston** [comment]
Thanks @aparna-aot! - this is fixed, and closing ticket
