### ISSUE TITLE
Tab Panel is missing the rounded corners in the bottom

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3168]
Title of ticket: 

#### Description
The tab panel bottom is missing the rounded corners.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/6433e50d-3ee3-455f-b165-ee2bc17fcf73)

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Fix the style
- [x] Test and deploy to dev
- [x] Test and deploy to test
- [x] Test and deploy to dev-marshal
- [ ] Test and deploy to test-marshal

**Comment by KyEggleston** [comment]
@divyav-aot - confirmed in TEST. Do you want me to close the ticket, or do you still have to test and deploy to dev and test marshal?
