### ISSUE TITLE
'On Hold' status not available when a request is in a status of 'Response' 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3175]
**Describe the bug in current situation**
When a request is in a status of 'Response', you are unable to change the request status to 'On Hold'. 

**Link bug to the User Story**
[User Story # 2691](https://github.com/bcgov/foi-flow/issues/2691), Scenario 1

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Medium

**Chance of Occurring (high/medium/low/very low)**
Medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
TEST environment
Logged in with IAO analyst role
Request is in a status of 'Response'
A balance is remaining to be paid for the request (as noted on the CFR form).

**Steps to Reproduce**

1. Go to a request (in the TEST environment) which is in a status of 'Response', and there is balance remaining (or create a new one)
2. In the left nav, click the status field (which should be in a status of 'Response')
3. The status options of 'Response', 'Records Review' and 'Closed' are available to select, but 'On Hold' is not

**Actual/ observed behaviour/ results**
GIVEN an applicant owes a balance for their processing fees
AND the request state in Response
WHEN the IAO analyst clicks the state dropdown
THEN the On Hold status **is not** an option

**Expected behaviour**
GIVEN an applicant owes a balance for their processing fees
AND the request state in Response
WHEN the IAO analyst clicks the state dropdown
THEN On Hold will be an option

**Screenshots/ Visual Reference/ Source**

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/8547f3f9-d18a-44b0-b72a-fd1f5a3c5a1d)

**Comment by divyav-aot** [comment]
Hi @KyEggleston , could you please share the request number? The only condition written to show On Hold in the list is, 
1. approved CFR form
2. balanceRemaining > 0

**Comment by KyEggleston** [comment]
@divyav-aot - an example request in TEST would be - EDU-2022-00057. But the 'On Hold' button now appears for this request when it is in a 'Response' status. 

If this was just recently fixed (prior to me commenting) feel free to drop this into Ready for QA pipeline and I can see if I find any edge cases on Monday. 

Thanks!

**Comment by divyav-aot** [comment]
@KyEggleston - we haven't pushed any changes. Could you please cross verify the request you were facing issue. May be the condition was not meeting.

**Comment by KyEggleston** [comment]
@divyav-aot - I just gave this another test in TEST on EDU-2022-09812, and in TEST-Marshal on MMA-2022-662277, and the 'On Hold' status was an available option when the record is in a 'Response' status and balanceRemaining > 0. Therefore, I think this must have been my mistake (perhaps I forgot to confirm there was a balance remaining). 

I will close this ticket, as I don't believe there is any bug, and it was likely due to me missing a precondition.
