### ISSUE TITLE
Fee Release: Pre-Deployment Activities

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3179]
Title of ticket: 

#### Description
Listing out the Pre-Deployment Activities.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Prepare the deployment document
- [x] Review Prod environment for forms-flow-ai and update ENV variables
- [x] HA setup for forms-flow-ai
- [x] Upload Email templates to S3 prod bucket
- [x] New route for Fee API
- [x]  Update ENVs of forms-flow-ai with new route for Fee API
- [x] Update ENVs of forms-flow-ai with new silver url
- [x] Upload all the forms (3 forms) to forms-flow-ai-web and make it as public
- [x] Keycloack setup for forms-flow-ai-web
- [x] Keycloack setup for forms-flow-bpm
- [x] Backup and restore of dev DB (This is to test if the backup and restore works fine for the rollback plan)

Attached is the latest(V 1.1) deployment document for the Fee release.
[https://app.zenhub.com/files/358004325/76902343-0413-4f71-8a5f-b3a9d05c31a1/download](https://app.zenhub.com/files/358004325/76902343-0413-4f71-8a5f-b3a9d05c31a1/download)
Attached is the V 1.0 deployment document for the Fee release.
 [https://app.zenhub.com/files/358004325/2ffafc14-efbc-4517-b151-848ead55466b/download](https://app.zenhub.com/files/358004325/2ffafc14-efbc-4517-b151-848ead55466b/download)

**Comment by abin-aot** [comment]
Vanity URL and related SSL updates is moving to another ticket, since its not ready as of Release date(15/12) . Plan is to go with default OCP route host address/url for this release. @divyav-aot  , @sumathi-thirumani-aot , @lmullane
