### ISSUE TITLE
Add Divisions - Post-Secondary Education and Future Skills

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3190]
Title of ticket: 

#### Description
Divisions for ministry formerly known as AEST

#### Dependencies
Are there any dependencies?

New ministry org code.

Reporting dashboard covered in #3192. Need to confirm if these are divisions or branches.

Divisions/branches to be added:

#### DOD
- [x] Deputy Minister’s Office
- [x] Minister’s Office
- [x] Finance, Technology & Management Services 
- [x] Governance & Corporate Planning
- [x] Post-Secondary Policy & Programs
- [x] Workforce Development & Skills Training

**Comment by lmullane** [comment]
Onboarding planned for Jan. 16th.

**Comment by sumathi-thirumani-aot** [comment]
Identified Technical Changes
1. Migration scripts
**Estimate - 3**
Question
1. Why no reporting for AEST ?

**Comment by liseandtea** [comment]
@abin-aot 

Tested on PSE-2023-30123 in the "TEST" environment (new login for PSE worked correctly) - All is working correctly and am closing this ticket.

On the IAO side:
Opened a new request, created a CFR and assigned it to the PSE queue.

ON the PSE side:
Received the CFR, and updated the divisional tracking section to include all of the divisions listed. This list matched the one submitted to IAO by PSE.

![Screenshot 2023-01-05 103419.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/d0a1300a-d89d-4357-8734-609ec94b25e8)

On the IAO side:
Refreshed request and all divisions are now showing in the divisional tracking section.

![Screenshot 2023-01-05 103507.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/c7a58a8e-213f-4fa1-99ec-95d2c7d03420)

**Comment by abin-aot** [comment]
PROD RELEASE STEPS Taken
1. Created DB back up of Camunda, FOI DB
	-  patroni-master-002-ffa-camunda_2023-01-10_15-41-16.sql.gz  
	- patroni-master-002-foidb_2023-01-10_15-41-15.sql.gz 
2. Backed images FormsFlowWeb and Requestmanagement api -002
	- oc tag forms-flow-web:prod forms-flow-web:prod-bu
        - oc tag request-management-api:prod-002 request-management-api:prod-002-bu

2. Tagging FormsFlowWeb and Request Managment API - 002
	- oc tag  request-management-api:test request-management-api:prod-002
	- oc tag  forms-flow-web:test forms-flow-web:prod
