### ISSUE TITLE
Add Divisions - TRA

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3191]
Title of ticket: 

#### Description
Summarize issue 
Add divisions to divisional stages in for TRA

#### Dependencies
Are there any dependencies?

While all of these are listed separately on the divisional stages list, for reporting some need to be consolidated under a division and reported on separately.

For reporting, TRA has requested they can report on the **Northern Region, South Coast Region** and the **Southern Interior Region** separately and as part of the stats for the **Highways & Regional Services Division.**

For reporting, TRA has requested they can report on **Corporate Writing Services** separately and as part of the stats for the **Strategic & Corporate Priorities Division.**

Reporting dashboard is covered #3194

#### DOD
Divisions/branches/Crowns listed in this order:
- [x] Deputy Minister’s Office
- [x] Minister’s Office
- [x] Minister of State
- [x] Corporate Writing Services
- [x] Finance & Risk Management Division
- [x] Highways & Regional Services Division
- [x] Northern Region
- [x] South Coast Region
- [x] Southern Interior Region
- [x] Integrated Transportation & Infrastructure Services Division
- [x] Policy, Programs, & Partnerships Division
- [x] Strategic & Corporate Priorities Division
- [x] BC Railway Company
- [x] BC Transit
- [x] BC Transportation Finance Authority
- [x] Transportation Investment Company

**Comment by lmullane** [comment]
Onboarding date for MOTI is January 23rd.

**Comment by sumathi-thirumani-aot** [comment]
Identified Technical Changes
1. migration script
**Estimate - 5**
Question
1. Why no reporting for AEST ?

**Comment by liseandtea** [comment]
@abin-aot

tested on TRA-2023-30123 in the "TEST" environment (new login for TRA worked correctly) - All is working correctly and am closing this ticket.

On the IAO side:
Opened a new request, created a CFR and assigned it to the TRA queue.

ON the TRA side:
Received the CFR, and updated the divisional tracking section to include all of the divisions listed. This list matched the one submitted to IAO by TRA.

![Screenshot 2023-01-05 104930.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/c9f533ab-c4eb-4042-b8a7-29fdea380541)

On the IAO side:
Refreshed request and all selected divisions are showing up in the divisional tracking section.

![Screenshot 2023-01-05 105049.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/db381024-790c-4477-a5ca-48a07b67ba47)

**Comment by abin-aot** [comment]
PROD RELEASE STEPS Taken
1. Created DB back up of Camunda, FOI DB
	-  patroni-master-002-ffa-camunda_2023-01-10_15-41-16.sql.gz  
	- patroni-master-002-foidb_2023-01-10_15-41-15.sql.gz 
2. Backed images FormsFlowWeb and Requestmanagement api -002
	- oc tag forms-flow-web:prod forms-flow-web:prod-bu
        - oc tag request-management-api:prod-002 request-management-api:prod-002-bu

2. Tagging FormsFlowWeb and Request Managment API - 002
	- oc tag  request-management-api:test request-management-api:prod-002
	- oc tag  forms-flow-web:test forms-flow-web:prod
