### ISSUE TITLE
File Conversion of MS Office Uploaded Records

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#3205]
This ticket is split off from #3120

As a IAO or ministry user 
I want to know when file conversion is completed
So that I can reconcile files uploaded versus files in the review/redaction package

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?
status for file conversion
number of file converted

Conversions will only cover these record types: MS Office files (i.e., msg, ppt, doc, docx, xls, xlsx) 

What is NOT in scope?
PDF scenarios covered in #3120

Conversions of GIS files (i.e, shp, kml, kmz), audio files, certain large Excel files or Excel with macros.

**Acceptance Criteria**	

**Scenario 1: File conversion is complete**
* GIVEN a batch of records have been uploaded
* WHEN the deduplication AND file conversion is complete
* THEN the uploaded records will be listed
* AND green check mark will be next to each unique record
* AND the number of converted to PDF files will be populated
* AND a red x next to each removed duplicate 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975255939

**Scenario 2: Number of batches uploaded**
* GIVEN a batch of non-PDF record has been uploaded
* WHEN dedupe and file conversion is complete on the batch
* THEN at the top of the page the 'Number of batches' uploaded will be increase: 1, 2, 3, etc.
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975255939

**Scenario 3: Number of files deduplicated**
* GIVEN a batch of record has been uploaded
* WHEN a non-PDF record(s) has been deduplicated
* THEN at the top of the page the 'Number of deduplicated files' will increase: 23, 32, 37 etc.
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975255939

**Scenario 4: Number of files deleted - NOW INVALID (as of 2023-01-12)**
* GIVEN a ministry coordinator click the ellipsis next to a non-PDF record
* WHEN the analyst clicks 'Delete'
* THEN at the top of the page the 'Number of deleted files' will increase: 4, 7, etc.
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975255939

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
#3119

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Pre-Deployment Steps**

- [ ] add DEDUPE_STREAM_KEY env variable to file conversion
- [ ] add NOTIFICATION_STREAM_KEY env variable to dedupe
- [ ] add DEDUPE_STREAM_KEY and FILE_CONVERSION_STREAM_KEY env to reviewer api
- [ ] add FOI_DOCREVIEWER_BASE_API_TIMEOUT to request management api

**Comment by lmullane** [comment]
As discussed, AC 4 is invalid as we will not count deleted files.

@nkan-aot in my testing I am not finding non-PDF files are being converted and deduplicated. Assumption is that eml. files can be uploaded?

I uploaded a number yesterday for request EDU-23232-222 and the file conversion remains incomplete.

Fo the same request, I also found that not all Word files were converted to PDF?

**Comment by lmullane** [comment]
As discussed, @nkan-aot is also fixing a bug so that:

GIVEN a record is a duplicate (File A)
AND the record is tagged with more than one division
WHEN a duplicate is deleted (File B)
THEN FIle B division should be taken off File A

QA, please ensure the expected behaviour above.

**Comment by nkan-aot** [comment]
added second edge case to above comment

**Comment by KyEggleston** [comment]
All ACs pass, closing ticket.
