### ISSUE TITLE
Download  or delete converted original file

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3207]
* As an IAO analyst
* I want to download or delete an original file that has been converted to PDF
* so that I can see the file in native format if the file is not readable in PDF

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?

What is NOT in scope?
Delete and download of not converted files, #3136

**Acceptance Criteria**	

**Scenario 1: Click on Ellipsis for record that has been converted**
* GIVEN a ministry coordinator or IAO analyst is on the Gathering Records log
* AND the records have been uploaded
* WHEN the user clicks on the ellipsis next to a record
* AND the file has been converted to PDF
* THEN a dropdown will open with these options: Download PDF, Download Original, Delete

**Scenario 2: Download Original**
* GIVEN a ministry coordinator or IAO analyst has clicked on the ellipsis for a record
* AND the record has been converted to a PDF
* WHEN the user clicks on 'Download Original'
* THEN the record will be downloaded to the the user's desktop in the original format
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
@nkan-aot - really minor update, but in the Records tab, when clicking the ellipsis next to a record, can we change "Download" to "Download Original"? 

Otherwise, ACs pass.

**Comment by KyEggleston** [comment]
> @nkan-aot - really minor update, but in the Records tab, when clicking the ellipsis next to a record, can we change "Download" to "Download Original"?
> 
> Otherwise, ACs pass.

@nkan-aot - hold off on this for the moment, needs discussion.

**Comment by KyEggleston** [comment]
@JHarrietha-AOT - just regarding Scenario 2 above, do you have a design for this? I.e., where a non-native PDF file is converted to a PDF, what should be displayed under the ellipsis?

Currently it has these options:
![image](https://user-images.githubusercontent.com/117312323/212200232-da4d8300-2f69-4600-8e8a-3e8bcbe82db3.png)

However, I believe 'Download' should be updated to 'Download Original' - is that right? 

I found some other designs (e.g., https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975449391), but nothing displaying just 'Download Original', 'Download PDF', and 'Delete'.

Thanks!

**Comment by JHarrietha-AOT** [comment]
@KyEggleston that is correct the design and the ticket itself says download original good. @nkan-aot I think this needs to be updated so it makes sense to the user what they are downloading

**Comment by JHarrietha-AOT** [comment]
For reference here is a screenshot if the designs: ***![Screen Shot 2023-01-13 at 12.08.24 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/c7e04f01-b79c-4fb9-be7b-bb935383be3d)*

**Comment by nkan-aot** [comment]
rename will be removed, duplicate will be a separate ticket

**Comment by KyEggleston** [comment]
'Rename' option may need more discussion on business side - interest in keeping this option at sprint demo today. Will meet with CFD Personals team (who brought it up) for further discussion.

**Comment by KyEggleston** [comment]
'Download PDF' changed to 'Download Converted' in new designs. 

ACs pass, closing ticket.
