### ISSUE TITLE
ETL - Applicant Type Not Populating

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3224]
**Describe the bug in current situation**
Report received from a user that the extracted requests report does not always show the applicant type on every request. It is unclear what is driving this behaviour.

Similar observations have been made with the Ministry of Education's dashboard upon closer inspection. 

Applicant type/category can be seen in the application itself, so it appears it could be an issue with the data warehouse or ETL.

**Link bug to the User Story**

**Impact of this bug**
Will impact reporting by applicant type, could skew numbers.

**Chance of Occurring (high/medium/low/very low)**
High - Issue can be observed across all dashboards, even on non-pilot requests (ie: performance/received dashboard)

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Production Redash, and go to the ECON Combined dashboard, or any dashboard of current data
3. Scroll down to excel sheet extract
4. Scroll through excel sheet, you will periodically see requests that are missing the applicant type

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN a requests details are in the data warehouse
WHEN the details are extracted in a report
THEN the details should also include the applicant type

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/7dd75e2d-1bd0-4a5b-97bb-fa735b81cb79)If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nkan-aot** [comment]
Investigated and there is a problem with ETL, applicant type, category and applicant name are not being saved from AXIS for certain requests. Needs further investigation

**Comment by abin-aot** [comment]
@m-prodan : ready for testing, Could you please check!

**Comment by KyEggleston** [comment]
Applicant Type field is populating on ECON combined dashboard (along with several other dashboards tested). No NULL 'Applicant Type' values appear, so this appears fixed. 

Closing ticket.
