### ISSUE TITLE
Accessibility Errors on Fee Payment Link! Non compliance reports from WAVE and accessBe.

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3229]
**Describe the bug in current situation**

Thanks @lmullane for the heads up.  Its been found that there are a few "accessibility" errors while evaluating payment url using WAVE tool. Also there is report generated with another online tool called "accessBe"  . please download below linked document to find the errors/non-compliance etc.
[https://app.zenhub.com/files/358004325/ffac6745-5807-4872-90e7-291a076caf95/download]

WAVE ERRORS- Browser plugin
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/54b0ab5d-b295-4934-bf05-565ca8bc49bb)

This is a unpaid fee payment url from TEST : https://payments.test.foirequests.gov.bc.ca/public/form/62e03bd75e0f9ddda4925058/submission/63a4d1e5a864adede7e2251e/edit

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by divyav-aot** [comment]
All aria reference and contrast issues shows in WAVE are fixed.
Accessibe issues shown in the report are fixed except one. Attaching the latest report here.
[accessibe_report_12292022.pdf](https://github.com/bcgov/foi-flow/files/10321466/accessibe_report_12292022.pdf)

**Comment by divyav-aot** [comment]
Steps to deploy to production,
1. Upload the updated forms
2. Tag the latest image of formsflow.ai.web
