### ISSUE TITLE
Batch export divisional records for harms review

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3230]
* As a ministry coordinator
* I want to export records in divisional batches
* so that I can send records to divisions to assess for harms

**Assumptions & Scope**	
What are the assumptions for this story?

Ministry coordinators need to export records tagged by a division so that these records can be reviewed my ministry branch staff for potential harms.

These reviews will occur outside the system for the initial releases of the Gathering Records feature.

By default the records exported will only include unique records that are tagged with the division. Duplicate records will not be included in the export. If a record has been tagged with more than one division, then a copy of that record will be exported when any tagged division is selected.

If a record has been converted into a PDF, the export will include the PDF version of the record, not the original.

Export will include all file types that have been uploaded into the Gathering Records log.

If the All tag is selected than all the records will be exported.

What is IN scope?

What is NOT in scope?
Tagging of records by division is covered in #2779
#download of individual records is covered in #3205, #3207
**Acceptance Criteria**	

**Scenario 1: 'Export Records' button**
* GIVEN records have been uploaded for a request
* WHEN the ministry coordinator or IAO analyst is on the Records log for the request
* THEN an 'Export Records' button will be at the top of the page

**Scenario 2: Export All Records**
* GIVEN the ministry coordinator or IAO analyst has selected the All tag
* WHEN they click the 'Export Records' button
* THEN all the records in the records log will be exported in a ZIP file

**Scenario 3: Export Records with a Division tag**
* GIVEN the ministry coordinator or IAO analyst has selected a Division tag
* WHEN they click the 'Export Records' button
* THEN all the records in the records log tagged by this Division will be exported in a ZIP file

**Scenario 4: No duplicates in export**
* GIVEN the ministry coordinator or IAO analyst has selected any tag
* WHEN they click the 'Export Records' button
* THEN duplicate records will not be included in the ZIP file

**Scenario 5: No duplicates in export**
* GIVEN the ministry coordinator or IAO analyst has selected any tag
* AND records under that tag have been converted to PDF
* WHEN they click the 'Export Records' button
* THEN converted records will be included in the ZIP file in PDF
* AND the original file type of the converted records will not be include in the ZIP file

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
Please review this story, @nkan-aot, @m-prodan, @liseandtea, @KyEggleston @abin-aot  

I see that some of this functionality has already been built!

**Comment by KyEggleston** [comment]
AC 4 and 5 need to be completed, the other ACs are done.
