### ISSUE TITLE
AXIS Sync - Subject Code #2969

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3243]
Title of ticket: 

#### Description
Bring Subject Code as part of AXIS Sync 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Analysis of Subject Code in AXIS 
    CUSTOMFIELD33 column in TBLREQUESTCUSTOMFIELDS has SubjectCode values. This can be accessed using iRequestID.
- [x] Design the BE table to save the Subject Code
   ![SubjectCode - ER Diagram.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/c75e0311-545c-4193-8743-1f8a825df170)
- [x] UI design of Subject code in FOI-FLOW
- [x] API to populate the subject code dropdown
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/10fa2772-4097-4009-a239-a7877e5b4703)
- [x] POST API changes to save selected subject code
- [x] GET API changes to get the saved subject code
- [x] Changes to AXIS API
- [x] Add conditions to include Subject code for the banner warning
- [x] Add conditions to include Subject code for the AXIS Sync modal
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/4e6b6c54-ed51-43d3-a2ab-778f786bec72)
- [x] Fix the encoding issue of AXIS SubjectCode with "space"

**Comment by divyav-aot** [comment]
dev-DV-2969 branch has all the changes.

**Comment by abin-aot** [comment]
@divyav-aot has provided the progress on development, there is a small issue which need to be resolved - related to encoding - means, same text like "BC Tech" show as different. Which need to be investigated and fixed. @abin-aot  to under master table of Subject Codes on AXIS,.

**Comment by richard-aot** [comment]
This is caused by "Non-breaking space". Currently 12783 records contains "Non-breaking space" on production AXIS database.
To resolve this we can replace the "Non-breaking space" with standard "space" in line 83 of axisintegrationapi/MCS.FOI.AXISIntegration/MCS.FOI.AXISIntegration.DAL/RequestsDA.cs.

**Comment by richard-aot** [comment]
Encoding (non breaking space) Issue is fixed. Sync API is tested on dev.
