### ISSUE TITLE
Update code for EDU

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3248]
Title of ticket: 

#### Description
Summarize issue 

Update code for EDU to ECC.

#### Dependencies
Are there any dependencies?

Need to confirm that code is changing. 

Need to update code in TEST AXIS.

#### DOD

- [x] Update org code in FOI Mod

**Comment by lmullane** [comment]
Confirmed code will be change to ECC.

**Comment by abin-aot** [comment]
@lmullane , I am moving Reporting Dashboard tasks/DOD with other existing task #3192 
"Map new org code to for reporting. Combine EDU and ECC for dashboards."

**Comment by abin-aot** [comment]
As discussed, New Key Cloak group has been created to accommodate ECC code . On Prod, We will keep same ministry users in EDU Ministry Team and ECC Ministry Team. @lmullane , @m-prodan 
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/5c97e1cf-5ae9-467e-ab39-4fbe2d11d772)

**Comment by KyEggleston** [comment]
Confirmed org code and 'Ministry Assigned To' updated in FOI Mod.

Confirmed ministry name updated in Angular app.

Closing ticket.

**Comment by abin-aot** [comment]
PROD RELEASE STEPS Taken
1. Created DB back up of Camunda, FOI DB
	-  patroni-master-002-ffa-camunda_2023-01-10_15-41-16.sql.gz  
	- patroni-master-002-foidb_2023-01-10_15-41-15.sql.gz 
2. Backed images FormsFlowWeb and Requestmanagement api -002
	- oc tag forms-flow-web:prod forms-flow-web:prod-bu
        - oc tag request-management-api:prod-002 request-management-api:prod-002-bu

2. Tagging FormsFlowWeb and Request Managment API - 002
	- oc tag  request-management-api:test request-management-api:prod-002
	- oc tag  forms-flow-web:test forms-flow-web:prod
