### ISSUE TITLE
Gathering Records - Records that are Incompatible or have Errors

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3266]
* As a Ministry Coordinator or Flex Team User
* I want to know when a record is incompatible with PDFTron or the conversion or deduplication of the record failed (i.e. errors)
* so that I can take action to correct it

**Assumptions & Scope**	
This story reflects the need for users to be able to see when there are errors or incompatible file types in the gathering records log

Records with an error or incompatible message will be kept in the Records log, but not included in the records package in PDFTron.

Flex team needs away to fix the error record with a new manually formatted record that has the same family date as the original. 

And they need to be able to still download the original error record, which will be kept in the Records log.

Attachments

What is IN scope?
Icon updates and messages to display when there is an error or incompatible file type. ,

What is NOT in scope?

Filtering the Records log by Errors or Incompatible; covered in #3288

Option to retry conversion or replace record.

Attachments and Embeds; covered in #3293

**Acceptance Criteria**	

**Scenario 1: Error on Conversion**
* GIVEN a user has uploaded a batch of records
* WHEN there is an error converting to PDF or removal of a duplicate
* THEN the file(s) listed that has the error will show an error icon with the following message "Error During File Conversion"
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/979666754

**Scenario 2: Error on Removal of Duplicates**
* GIVEN a user has uploaded a batch of records
* WHEN there is an error with the deduplication
* THEN the file(s) listed that has the error will show an icon (insert design) with the following message "Error During Deduplication"
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/979666754

**Scenario 3: Incompatible File Type**
* GIVEN a user has uploaded a batch of records
* WHEN there is upload of an incompatible file type
* THEN the file(s) listed that are incompatible will show an incompatible icon with the following message "Incompatible File Type"
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/979673724

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Rough draft of error log - need design updates from @JHarrietha-AOT when sessions with flex team is completed.

cc: @lmullane @liseandtea @KyEggleston

**Comment by nkan-aot** [comment]
add replace manually to AC based on design https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262

**Comment by m-prodan** [comment]
@nkan-aot - pls add estimate when you have a chance, and bring into sprint

**Comment by KyEggleston** [comment]
All ACs pass, closing ticket.
