### ISSUE TITLE
Filters on Records Log - Error and Incompatible

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3288]
* As a a Flex Team user 
* I want filters for records with an error or that are incompatible (i.e., not viewable in PDFTron)
* so that I can find the records easily

**Assumptions & Scope**	
What are the assumptions for this story?

Flex team users need to review the FOI records and identify any records:

- where conversion or dedupe failed (i.e., an error)
- where a record is not compatible with PDFTron (e.g., mpeg, shp, kmz, kml, etc.)

While Flex Team is the most likely user of this functionality, any user can use it.

Once errors are found, Flex Team will try to fix the error.

What is IN scope?

The ability to filter records by error or incompatible.

What is NOT in scope?

Tagging a record as incompatible or an error.

**Acceptance Criteria**	

**Scenario 1: Error and Incompatible filters**
* GIVEN the ministry coordinator or IAO analyst is on a request
* WHEN the user clicks on the Records log
* THEN there will be a filter for 'Errors' and 'Incompatible'
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/979673724

**Scenario 2: Click on Errors filter - with errors**
* GIVEN there were errors converting or removing duplicates
* WHEN the user clicks the 'Errors' filter
* THEN only records that had an error will be displayed:
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/979666754
* AND the error records will be displayed by record creation date

**Scenario 3: Click on Errors filter - with no errors**
* GIVEN there were NO errors converting or removing duplicates
* WHEN the user clicks the 'Errors' filter
* THEN no records will be listed

**Scenario 4: Click on Incompatible filter - with incompatible records**
* GIVEN there were records that were incompatible
* WHEN the user clicks the 'Incompatible' filter
* THEN only records that were incompatible will be displayed:
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/979673724
* AND the incompatible records will be displayed by record creation date

**Scenario 5: Click on Errors filter - with no incompatible**
* GIVEN there were no records that were incompatible
* WHEN the user clicks the 'Incompatible' filter
* THEN no records will be listed

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@nkan-aot - pls add estimate when you have a chance, and bring into sprint

**Comment by KyEggleston** [comment]
All ACs pass, closing ticket.
