### ISSUE TITLE
'Received Mode' automatically 'Online Form' for request received online

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#329]
* As an Intake analyst
* I want the 'Received Mode' for a request received online to be autofilled with 'Online Form'
* so that I do not need to select the Received Mode

**Assumptions & Scope**	
What are the assumptions for this story?

Auto-fill will only be for requests received through Online Form

What is in and not in scope?

Requests not received through Online Form are not in scope. 

The analyst cannot edit the 'Received Mode' for requests received online.

**Acceptance Criteria**	

**Scenario 1: Auto-fill Received Mode**
* GIVEN a request has been through the online form
* WHEN an analyst is on the Request View
* THEN the 'Received Mode' will be auto-filled with 'Online Form'
* AND the field will be greyed out and not editable

**Scenario 2: Cannot edit 'Received Mode' for requests received online**

* GIVEN a request has been through the online form
* AND the analyst is on the Request View
* WHEN the analyst clicks the greyed out field for 'Received Mode'
* THEN nothing will happen (consistent with other greyed out fields

**Scenario 3: Online Form not a selection option for 'Create a Request**
* GIVEN an analyst clicks 'Create Request"
* WHEN the analyst clicks dropdown for 'Received Mode'
* THEN the drop down will open
* AND the option of 'Online Form' will be greyed out and cannot be selected

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, should an analyst be able to select 'Online Form' as the Received Mode for a request that was not received through the online form?

@abin-aot, is there any recovery reason we would need to allow an analyst to do this? For example, if a the API from the webform captures the request into the database but not the UI. Assume we fix this on the backend so the requests were displayed in the UI, and no manual data entry would be necessary.

**Comment by m-prodan** [comment]
@lmullane - that makes sense to me. In the new system, there shouldn't be a need to select online form when they are creating a request.

That said, I suppose we could just have it at the bottom, but perhaps greyed out for now? I can't imagine a scenario where we'd use it, unless there was a temporary issue with requests not getting captured properly.

**Comment by abin-aot** [comment]
@lmullane @m-prodan  - Yes, we can make Received Mode default to Online, when a request is submitted through our Front End FOI Submission app. Sorry, we missed that!.

**Comment by lmullane** [comment]
Hey @divyav-aot, @abin-aot, looking to test this one, but looks like I'm not on the Intake team? If you update my permissions I can get this done tonight.

**Comment by divyav-aot** [comment]
@lmullane  - Add you as part of Intake team as well

**Comment by lmullane** [comment]
Thanks, @divyav-aot!

**Comment by lmullane** [comment]
@divyav-aot 

Scenario 3 passed, but 1 and 2 failed; Given a request is made online, while the Received Mode is pre-filled with Online, the user is able to edit the field and change it to something else. It shouldn't be editable.

**Comment by lmullane** [comment]
@divyav-aot, let me know if you want me to move this back to the Sprint Backlog?

cc @mpilchar

**Comment by divyav-aot** [comment]
@lmullane  - I will be pushing the changes today or early tomorrow. The changes are in review now.

**Comment by lmullane** [comment]
Thanks, @divyav-aot

**Comment by divyav-aot** [comment]
@lmullane  - The issue is fixed and pushed to test

**Comment by lmullane** [comment]
Issue fixed. All scenario pass QA.
