### ISSUE TITLE
AXIS Sync - Restricted Requests

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3291]
* As an IAO user
* I want to not inadvertently sync a restricted request
* so that the privacy of the restricted request can be maintained

**Assumptions & Scope**	
To improve security/access for restricted requests, need logic to ensure only the authorized people can sync a restricted request from AXIS. Right now, if you enter a restricted request ID from the add request screen, it will sync over to the system regardless of permissions.

The error message for non-intake manager users syncing over a restricted request  will appear in the banner: "You are not authorized to sync this request, please contact the Intake Manager for assistance."

Scenario 3 is there to cover the fact that after a request is opened and assigned, that the user does NOT need to be the intake manager to sync the request further.

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Add Request - Non-Intake Manager Syncs Restricted Requests**
* GIVEN a user is on the add request screen, and enters a valid restricted request ID from AXIS
* AND the user is NOT the intake manager
* WHEN the user clicks Sync
* THEN the error message will appear in the banner: "You are not authorized to sync this request, please contact the Intake Manager for assistance."

**Scenario 2: Intake Manager Syncs**
* GIVEN the Intake Manager is on the add request screen, and enters a valid restricted request ID from AXIS
* WHEN the user clicks Sync
* THEN the request will sync

**Scenario 3: Sync Restricted Request**
* GIVEN a user is on the review request screen, 
* AND the AXIS sync banner is active
* AND the user is assigned to the restricted request
* WHEN the user clicks Sync with AXIS
* THEN the review change modal will pop out
* AND the user can sync the request as normal
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
updated with scenarios, let me know if this makes sense @aparna-aot 

cc: @lmullane

**Comment by lmullane** [comment]
Thanks, @m-prodan. For scenario 3, assumption is that if the request is already in the new Mod system, when they sync it, they should be able to see it, correct?

**Comment by aparna-aot** [comment]
Moving this ticket back to Sprint Backlog due to the access issue with my _A account.

**Comment by m-prodan** [comment]
AC updated to display the error message in the banner, with suggested wording so it is more clear to the user why they can't sync the request, and how to resolve.

**Comment by abin-aot** [comment]
@m-prodan incorporated the validation/alert message  as indicated!. You can see once its moved to TEST for QA

**Comment by m-prodan** [comment]
Works as expected - nice work as always, @abin-aot
