### ISSUE TITLE
Gathering Records Log Ellipsis - Replace Manually and Retry

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3292]
* As a Flex user
* I want to be able to replace, delete and retry conversion of a file
* so that I can correct errors in a records package

**Assumptions & Scope**	
What are the assumptions for this story?

Flex team needs to fix records where there is an error in converting the file or removing the duplicate, so that the record can be redacted in PDFTron.

Records with an error will not be added to the Records package.

Only error records will have the Replace Manually and Re-try options on the ellipsis.

And they need to be able to still download the original error record, which will be kept in the Records log.

What is IN scope?

What is NOT in scope?
Filter by errors or incompatible; covered in #3288

Tagging records that have errors or that are incompatible; covered in #3266

**Acceptance Criteria**	

**Scenario 1: Ellipsis Options**
* GIVEN a listed record has an error
* WHEN the user clicks the ellipses
* THEN they will have the following options: Replace Manually, Download Original, Delete, Re-try
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262

**Scenario 2: Ellipsis Options**
* GIVEN a listed record has no error
* WHEN the user clicks the ellipses
* THEN options Replace Manually and Re-try will not be listed
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262

**Scenario 3: Click Retry - run file through conversion and dedupe again**
* GIVEN a user has activated the ellipsis on a file with an error
* WHEN the user clicks "Retry"
* THEN the file will be run through the dedupe/conversion process again, depending on which one failed
* AND the status will update when complete
* AND the dropdown will close

**Scenario 4: Click Replace Manually **
* GIVEN a user has activated the ellipsis on a file with an error
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262
* WHEN the user clicks "Replace Manually"
* THEN a modal will open where the user can upload a new file
* AND there will be a 'Continue' and 'Cancel' button
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262

**Scenario 5:  Replace Manually - Upload Record **
* GIVEN a user is on the Replace Manually modal
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262
* WHEN the user clicks "Replace Manually"
* THEN a modal will open where the user can upload a new file
* AND there will be a 'Continue' and 'Cancel' button
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262

**Scenario 6: Drag and Drop to add files or folders**
* GIVEN you are on the upload records modal
* WHEN you drag and drop file(s) that are less than 500 MB into the "drag and drop" space
* THEN the file name or folder name will appear Add Files box

**Scenario 7: Add files/folders using the Add Files Button**
* GIVEN you are on the upload records modal
* WHEN you click on the "Add File" button
* THEN the user will be able to select file(s) from their local machine to add to the upload records modal

**Scenario 8: Adding files from machine**
* GIVEN you are selecting a file from your local machine
* WHEN you open or add a file
* THEN the file name will appear Add Files box

**Scenario 9: Cancel back to Gathering Records Log**
* GIVEN you are on the upload records modal
* AND no files appear in the Add Files box
* WHEN you click on the cancel button
* THEN the modal will close and you will remain on the Gathering Records log

**Scenario 10: Clicking On Cancel Button when Attachments uploaded**
* GIVEN you are on the upload records modal
* AND files appear in the Add Files box
* WHEN the user clicks the 'Cancel' button
* Or closes the modal
* THEN a pop up will ask the user "Are you sure you want to cancel (x) number of attachments will NOT be uploaded"
* AND the options will be "Yes" and "Cancel"

**Scenario 11: Cancel back to Attachment Upload**
•	GIVEN the user has attempted to close the modal with an active attachment, and the pop up has warned the user 
•	WHEN the user clicks on 'Cancel'
•	THEN the window will close and they will remain on the upload records modal, with the attachment still present

**Scenario 12: “Yes” to cancel uploading attached records**
•	GIVEN the user has attempted to close the modal with an active attachment, and the pop up has warned the user 
•	WHEN the user clicks on 'Yes'
•	THEN the window and attachment upload window will close and the uploaded attachment will not be uploaded to the Gathering Records log

**Scenario 13: Save uploaded records to the Gathering Records log**
* GIVEN the user is on the upload records modal
* AND the user has one record only
* AND the total file size of the batch is 500MB or less
* WHEN the user clicks the active 'Continue' button
* THEN the modal will close
* AND the record will be uploaded
* AND the file(s) will be displayed from newest to oldest upload

**Scenario 14:  Replace Manually - Continue Upload Record **
* GIVEN a user is on the Replace Manually modal
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262
* WHEN the user clicks "Continue"
* THEN the new record will be uploaded 
* AND file conversion and dedupe will run
* AND the modal will close
* AND the user will remain on the Records log

**Scenario 15:  Replace Manually - Conversion complete **
* GIVEN a user has clicked "Continue' to replace a file manually
* WHEN file conversion and deduplication is completed successfully
* THEN the new record will be listed with the divisional tag(s) of the original file
* AND a message will state, "Record Manually Replaced Due to Error"
* AND the file will be listed with the Modified Date of the original file
* AND the new record will be included in the records package chronologically by the Modified Date of the original file
* AND the error record will no longer appear in the Records log

**Scenario 16:  Replace Manually - Download Original **
* GIVEN a user has manually replaced a record
* AND the user has clicked the ellipsis for the record:
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262
* WHEN the user clicks 'Download Original'
* THEN the original record with the error will be downloaded 

**Scenario 17: Batch limit of 500MB exceeded**
* GIVEN the user is on the Replace Manually modal
* WHEN the total file size of the batch is  greater than 500MB 
* THEN a warning will show "A maximum 500 MB can be uploaded at one time. Please remove some files and upload them separately"...
* AND the 'Continue' button will be disabled.

**Scenario 18: Attempts to upload more than one file**
* GIVEN the user is on the Replace Manually modal
* WHEN the user tries to upload more than one file 
* THEN a warning will show "Only one file can be uploaded when replacing a file. Please remove some files."

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, please review AC 13. Could you confirm if there is a message that this record is a replacement for a previous record? 

@nkan-aot, please review the AC and advise on any errors or missing AC?

cc @m-prodan

**Comment by lmullane** [comment]
@JHarrietha-AOT, @m-prodan, the Flex team stated they want the original record with the error retained. 

The way I have written AC 13 is that when replaced manually the error record will be removed from being listed in the Records log. However, it will still be accessible by downloading the original (AC 14) when the the user clicks on the ellipsis next to the Replacement record.

The benefit of this is that when the user filters by Errors they see the list getting smaller (aka the error has been fixed).

The downside if the replacement record is converted into a PDF download original will not get the replacement record in the original file format.

What do you think we should do here?

**Comment by nkan-aot** [comment]
added AC for menu options for records without error
add clarification for retry based on which service failed
@JHarrietha-AOT AC 13 is no AC 15

**Comment by JHarrietha-AOT** [comment]
Looks good, I just updated the status wording for records replaced manually

**Comment by lmullane** [comment]
Thanks, @nkan-aot and @JHarrietha-AOT

**Comment by nkan-aot** [comment]
@lmullane sorry I didn't see your latest comment before I commented
right now I have it so that replacement records can only be pdf, so they are only replacing what would have been the result of the failed conversion. So they will still be able to download the original and the replacement

**Comment by KyEggleston** [comment]
All ACs pass, closing ticket.
