### ISSUE TITLE
Gathering Records Log - Attachments in Records

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3293]
* As a Flex Team user
* I want all attached records displayed
* so that I can see the relationship between records (i.e. this record is attachment of this record)

**Assumptions & Scope**	
What are the assumptions for this story?

In the future, attachments and embeds within records will be treated the same way. However, only attachments will be dealt with in this story.

Currently, embeds are found by a manual review. Embeds will be handled in another story, but require rank 2 deduplication to find the links embedded in the records.

Flex team does not want the ministry to remove attachments. Reason is that sometimes the ministry sends records as an attachment to an email, and they are responsive. Greater risk is that we miss records (design needed). IAO will then remove attachments if needed; need to remove the checkbox for when the ministry uploads. 

Flex team wants all **attachments up to 5 layers** added to the Records log. Even if there is more than one layer there will be only one indent.

For example:
Record A has and attachment in Record B; Record C is an attachment of Record A.

Visually this would be displayed in the Records log like this:

Record A
> indent - Record B
> indent - Record C

What is IN scope?
Remove checkbox for removal of attachments when ministry uploads records. #3162

Upload up to 5 layers of attachments.

List attachments up to 5 layers on Records log.

What is NOT in scope?

Embeds.

**Acceptance Criteria**	

**Scenario 1: Up to 5 layers of attachments**
* GIVEN a ministry coordinator uploads a batch of records
* WHEN the records contain attached records
* THEN up to 5 layers of attachments will be processed (i.e., uploaded, converted, deduplicated) 

**Scenario 2: View attachments**
* GIVEN a ministry coordinator uploads a batch of records
* WHEN the records contain attached records
* THEN the attached records will be displayer with an indent under the next parent record (only need one indent even if there is more than one layer).
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423265

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
Hi @nkan-aot, @JHarrietha-AOT, @m-prodan ,

Please review this story and advise if I have missed anything?

Will estimate at next refinement.

**Comment by JHarrietha-AOT** [comment]
@lmullane The dev team asked for attachments and embedded files to be two different stories as they are two different chuck of technical work. They were also hoping for Rank 1 to be only attachments and Rank 2 to include embedded files. @abin-aot @nkan-aot  Let me know if thats true or has changes

**Comment by lmullane** [comment]
Will update story to separate out embeds. Currently, Flex Team finds embeds in quality assurance review of records package.

**Comment by lmullane** [comment]
@aparna-aot, this revised story is now ready for estimation.

Cc @m-prodan

**Comment by JHarrietha-AOT** [comment]
Updated design link in ticket - also here for reference: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423265

**Comment by KyEggleston** [comment]
@nkan-aot - when I tested the attachments under a parent file, going down different levels, it doesn't appear it is working correctly. 

For example, see # ABC-345345-34534. 

Direct attachments to a parent file appear to show up (indented), and run through conversion and dedup. See 'This is a test.msg' in the image below. This is working properly.

However, for the other parent file, 'testing.msg', the attachments should go down multiple levels, as there are child .msg files attached to the parent .msg file, which also have attachments. The attachments on these child .msg files are not being uploaded to the 'Records' tab, nor are the attachments directly associated to the parent .msg file.  

'Records' tab showing one parent file with direct attachments (this is a test.msg), and another showing a parent file that has multiple levels of attachments (testing.msg). No attachments show up for the parent file with multiple levels of attachments. 

![image](https://user-images.githubusercontent.com/117312323/219121007-7f233a83-7d48-459c-b603-03c4263c432c.png)

If you download the original testing.msg file, you can see there are direct attachments that should show up in the 'Records' tab. In addition, the attachments for the child files (which go down another level) also have attachments that don't show up.  

<h3>First Layer</h3>

![image](https://user-images.githubusercontent.com/117312323/219124041-f372da42-eb29-4084-bcb8-7744abeb32e7.png)

<h3>Second Layer</h3>

![image](https://user-images.githubusercontent.com/117312323/219123460-e62b745d-e0aa-4ccf-b1f2-6f759674d281.png)

Feel free to ping me if you need clarification!

**Comment by KyEggleston** [comment]
Confirmed attachments now being uploaded, at a minimum of 5 levels down. Closing ticket.
