### ISSUE TITLE
Ministry Restricted - Protections and Audit Trails

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3296]
* As a Ministry User
* I want all the same restrictions and customizations that IAO has for their restricted requests
* so that I can be confident the request has not been inappropriately accessed.

**Assumptions & Scope**	
This story will essentially duplicate all IAO restricted request restrictions/features, for Ministry restricted FOI requests.

Note: Requests that are restricted on the Ministry side, should NOT have the same restrictions on the IAO side of things. Only if it is restricted on BOTH the IAO and Ministry side, should the restrictions align across 

What is IN scope?
Ministry restricted requests

What is NOT in scope?
IAO restricted requests

**Acceptance Criteria**	

Scenario 1: Watcher Assigned
* GIVEN a user has been selected as a watcher to a restricted request
* WHEN the action is completed and the assignments updated
* THEN a system generated comment will be posted in the request history saying "[USER] has made [USER] a watcher"

**Scenario 2: Watcher Removed**
* GIVEN a user has been removed as a watcher to a restricted request
* WHEN the action is completed and the assignments updated
* THEN a system generated comment will be posted in the request history saying "[USER] has removed [USER] as a watcher"

**Scenario 3: Assign Request - Ministry Manager**
* GIVEN a Restricted Request is in any state 
* WHEN the Ministry manager clicks on the primary assignment
* THEN the names that will populate will be all Ministry users

**Scenario 4: Assign Request - Complete Action**
* GIVEN a Restricted Request is in any state
* WHEN a user is selected from the assignment list
* THEN a modal will pop out with the options to continue or cancel
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/978958615

**Scenario 5: Assign Request - Continue**
* GIVEN the Ministry manager is on the restricted assignment modal
* WHEN the manager selects continue
* THEN the modal will close, and the user assignment will update

**Scenario 6: Assign Request - Cancel**
* GIVEN a user is on the restricted assignment modal
* WHEN the user selects Cancel
* THEN the modal will close, and the user assignment will remain as it was

**Scenario 7: Assign Watcher**
* GIVEN a Restricted Request is in any state
* WHEN the Intake manager clicks on the watcher assignment drop down
* THEN they will see all active ministry users

**Scenario 8: Assign Watcher - Complete Action**
* GIVEN a Restricted Request is in any state
* WHEN the user is selected from the watcher list
* THEN a modal will pop out with the options to continue or cancel
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/978958614

**Scenario 9: Assign Watcher - Continue**
* GIVEN the Intake manager is on the restricted watcher modal
* WHEN the user selects continue
* THEN the modal will close, and the watcher assignment will update

**Scenario 10: Assign Watcher - Cancel**
* GIVEN a user is on the restricted watcher modal
* WHEN the user selects Cancel
* THEN the modal will close, and the watcher assignment will remain as it was

**Scenario 11: Un-Assign Watcher**
* GIVEN the Intake Manager is on a restricted request with the watcher drop down activated
* AND a user is already assigned as a watcher
* WHEN the user removes the assigned watcher as such
* THEN the user shall be removed as a watcher, and be unable to interact with the request.

**Scenario 12: Can't Assign to Team Queue**
* GIVEN a user is on a restricted request
* WHEN they activate the assignment drop down
* THEN any IAO team names will be greyed out an unselectable

**Scenario 13: User other than Intake Manager Unable to Assign**
* GIVEN a user is on a restricted request
* AND they are NOT the Intake manager
* THEN the assignment and watching functions will be disabled
* AND the user will be unable to change the assignment or watcher

**Scenario 14: Tagging user**
* GIVEN a user is on the comment tab and is entering a comment in the RT Editor
* WHEN they write an @ and the tag list populates
* THEN the only names that shall appear and can be tagged are users assigned to the request as watchers or primary assignees and the IAO users

**Scenario 15: Tagging user - Notification**
* GIVEN a user is tagging another assigned user in the comment
* WHEN they select an assigned user and save the comment
* THEN the user will receive a notification that they were tagged in the comment

**Scenario 16: Attempting to tag other user**
* GIVEN a user is on the comment tab and is entering a comment in the RT Editor
* WHEN they write an @ and they manually write out a name that is not in the tag list
* THEN the text will not trigger a notification to that user, and no tag will be embedded in the comment

**Scenario 17: View restricted requests on assignee 'My Requests' queue**
* GIVEN an assignee of a restricted request (ministry coordinator, IAO analyst, processing team manager)
* WHEN they are on their 'My Requests' queue
* THEN they will see only restricted requests that they are the assignee
* AND each restricted requests will have an 'R' icon in the row
* AND the applicant name will not appear; instead it was say restricted

**Scenario 18: Restricted request 'Watching Requests' queue**
* GIVEN an assignee of a restricted request (ministry coordinator, IAO analyst, processing team manager)
* WHEN they are on their 'Watching Requests' queue
* THEN they will see only restricted requests that they are a watcher
* AND each restricted requests will have an 'R' icon in the row
* AND the applicant name will not appear; instead it was say restricted

**Scenario 19: Search restricted requests on 'My Requests' queue**
* GIVEN an assignee of a restricted request (ministry coordinator, IAO analyst, processing team manager) is on their 'My Requests' queue
* WHEN they enter 'restricted' in the search bar  
* THEN the queue will filter to show only assigned restricted requests
* AND each restricted requests will have an 'R' icon in the row
* AND the applicant name will not appear; instead it was say restricted

**Scenario 20: Search restricted requests on 'Watching Requests' queue**
* GIVEN a watcher of a restricted request (ministry coordinator, IAO analyst, processing team manager) is on their 'Watching Requests' queue
* WHEN they enter 'restricted' in the search bar  
* THEN the queue will filter to show only watched restricted requests
* AND each restricted requests will have an 'R' icon in the row
* AND the applicant name will not appear; instead it was say restricted

**Scenario 21: No restricted requests on assignee 'My Requests' queue**
* GIVEN a user is not an assignee of any restricted requests (ministry coordinator, IAO analyst, processing team manager)
* WHEN they are on their 'My Requests' queue
* THEN they will NOT see any restricted requests

**Scenario 22: No restricted requests on 'Watching Requests' queue**
* GIVEN a user is not an watcher of any restricted requests (ministry coordinator, IAO analyst, processing team manager)
* WHEN they are on their 'Watching Requests' queue
* THEN they will NOT see any restricted requests

**Scenario 24: Not assigned or watching - no restricted requests on 'My Team' queue**
* GIVEN a user is NOT an assignee or watcher of a restricted request (ministry coordinator, IAO analyst, processing team manager)
* WHEN they are on their 'My Team' queue
* THEN they will NOT see any restricted requests

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
From sprint planning this morning - this is the amalgamated ticket of all remaining features needed for the Ministry restricted stories.

cc: @aparna-aot @richard-aot @lmullane

**Comment by m-prodan** [comment]
From sprint planning - devs asked we amalgamate all the AC's from the missing stories for Minisry side restrictions

**Comment by m-prodan** [comment]
Discussed with @aparna-aot around issue where potentially Ministry can tag IAO users if a request is restricted on the Ministry side - not realizing that its also restricted on the IAO side.

Decision: as long as the user that gets tagged can not access the request because they aren't assigned to it - it should be ok. Can revisit in a future user story if this is causing confusing or disruptive behaviour when in production.

cc: @lmullane

**Comment by m-prodan** [comment]
Note for testing - make sure cases where other users are inadvertently tagged by the other side, that they can't access the file itself if it ends up being a restricted file on their side. (ie: IAO is on a Ministry restricted request - attempt to tag a Ministry user thats not assigned to the request. Login as that Min user and confirm you are not able to access it)

**Comment by KyEggleston** [comment]
QA'd, but just a couple things I need to confirm on Monday I didn't have time to dig into.

**Comment by KyEggleston** [comment]
@aparna-aot - I'm not sure tagging is working correctly on ministry restricted requests (scenario 14). 

For example, see EDU-2022-39869 or EDU-2022-00319. 

When the request is restricted on the ministry side, I can only tag the following individuals when entering '@':

![image](https://user-images.githubusercontent.com/117312323/218546141-27d7ef8a-73c6-4d1f-82b3-8f368737f3cf.png)

However, I can search for the following users when doing a targeted search (in this case, for those starting with the letter 'F'). No other users come up from other targeted searching, even those that came up when entering '@':

![image](https://user-images.githubusercontent.com/117312323/218546398-c6febc65-d03d-43e5-9ee9-68037ef8f2b2.png)

These users appear to be constant across all ministry restricted requests, and are the only ones that can be tagged in comments. These requests are not restricted on the IAO side, and I believe the ministry coordinator should be able to tag any IAO user in the request comments - which they currently are unable to. In addition, I cannot tag the user(s) in the 'IAO Assigned To' or 'Watchers' fields either. 

Any thoughts? Happy to show you to clarify. 

Otherwise, no issues for the other scenarios.

**Comment by aparna-aot** [comment]
@KyEggleston Shall we connect quickly over call?

**Comment by KyEggleston** [comment]
Outstanding issues resolved, closing ticket.
