### ISSUE TITLE
FOI Request Received Date Not Calculating

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#330]
**Describe the bug in current situation**
FOI Request submitted through the form after 4:30 PM should reflect the next business day as the received date. 

**Link bug to the User Story**

**Impact of this bug**
Any request received after 4:30 PM will need to have the received date changed. Current UI does not allow intake to know time request was received though, so this should be handled in back-end.

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Request must be submitted after 4:30PM

**Steps to Reproduce**
Submit a test FOI Request after 4:30PM

**Actual/ observed behaviour/ results**
Received Date shows request being received same date

**Expected behaviour**
GIVEN an applicant has submitted a FOI Request
WHEN the FOI Request is submitted after 4:30PM
THEN the received date should be reflected as the next business day.

**Comment by lmullane** [comment]
I'll test after 430.

**Comment by m-prodan** [comment]
@lmullane - did you submit a request yesterday after 430? I neglected to do so, but have set a reminder to do so today!

Today will be a good test actually - the date should reflect the next business day, which would be monday - so received date should show as August 16th.

**Comment by m-prodan** [comment]
Submitted request at 4:34PM

Received date in review request is August 16th as expected.

BUT - @divyav-aot - I notice the date in the queue says August 13th, so there is a discrepancy between the queue and the received date on the request itself.

**Comment by divyav-aot** [comment]
@m-prodan - Either we can track it in this same bug or can create a new one. This need few more changes to the API. I will update the effort if we are keeping this bug open.

**Comment by m-prodan** [comment]
Request submitted past 430 showed the correct received date of the next business day. Closing ticket - nice work!
