### ISSUE TITLE
Download Redline for Ministry Sign Off

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3301]
* As a ministry coordinator
* I want to be able to download the redacted redline in PDF format
* so that I can give it (outside the system) to the ministry business area for sign off

**Assumptions & Scope**	
What are the assumptions for this story?

Redline will include all redactions.

Ministry coordinator will not have access to the Record Review app; download of the redline will be triggered from the Records log.

IAO analysts can also download the redline records package.

The Records log filters are independent of the download. Applying a filter (e.g.by a divisional, error, etc. tag) on the Records Log will have no impact on what is downloaded.

When downloading a redline you will get a ZIP file with one consolidated PDF for each Division. For example, if 4 divisions provided records there will be 4 redline PDFs in the ZIP file.

The ZIP file will also contain all the incompatible file types (i.e. non-PDFs), such as audio and GIS files.

What is IN scope?

Download the redline Records Package

What is NOT in scope?

Saving the redline records package.
Notifications when the Redline is ready. #3434
**Acceptance Criteria**	

**Scenario 1: Active "Download Redline for Sign Off"**
* GIVEN the analyst has already saved the Redline
* WHEN the analyst clicks the Download dropdown
* THEN the Download dropdown will open with 3 choices: Download for Harms, Download Redline for Sign Off, Download Final Package
* AND the "Download Redline for Sign Off" will be active

**Scenario 2: "Download Redline for Sign Off" by Division**
* GIVEN the analyst has clicked "Download Redline for Sign Off" 
* WHEN the system completes creating the PDFs 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262
* THEN PDF(s) will be exported in one consolidated, linear PDF for each Division organized by modified date
* AND the consolidated PDF(s) redline for each Division will be include in the ZIP file
* AND the ZIP file will download onto the users computer
* AND the ZIP file will also include incompatible files in the correct divisional folders (i.e., the division that provided them)

**Scenario 3: Inactive "Download Redline for Sign Off"**
* GIVEN the analyst has NOT saved the Redline
* WHEN the coordinator or analyst is on the Download dropdown
* THEN the "Download Redline for Sign Off" will be inactive

**Scenario 4: Download Redline for Sign-Off - Error**
* GIVEN the analyst has saved the Redline
* WHEN the job fails at any point, including during the zipping service
* THEN the download redline for sign-off feature will be inactive
* AND the user will be notified that the redline for sign-off had an error and should be re-tried

**Scenario 5: Download Redline for Sign-Off - Only Incompatible Files**
* GIVEN the analyst has saved the Redline
* AND there is a division that only provided incompatible files, and will not have a redline
* WHEN the analyst downloads the Redline for Sign Off
* THEN the division that only provided incompatible files will have their own folder in the ZIP file
* AND it will contain all their incompatible files

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, @abin-aot, @lmullane 

Please review. Comments welcome.

Note, I will write a separate story for saving the redline.

**Comment by m-prodan** [comment]
I think we should also have the option as a Ministry user to download a redline per division, as sometimes Ministries will send records package per division, instead of all as one. Having the option at least would be a good idea I think

**Comment by lmullane** [comment]
Good point, @m-prodan. 

@JHarrietha-AOT, we need some design reconciliation.

Users will need to be able to export the original records for Harms, including by division, and export the redline, including by divisions. Welcome your design magic here!

As noted in the assumptions, for the two releases of Records Review, ministry coordinators will have no access to the Records Review app.

**Comment by lmullane** [comment]
Hi @JHarrietha-AOT, checking in on this design challenge?

**Comment by JHarrietha-AOT** [comment]
@lmullane Just working on the contents of the export module, I was out sick yesterday so should have this done today. Also things button wording would be "Export Records" Instead of redline. But open to opinions

**Comment by lmullane** [comment]
Thanks, @JHarrietha-AOT 

I wonder if we need to differentiate on what each button does. The Export Records button would take the non-redacted records. Feels like we need something different to export a redline?

**Comment by m-prodan** [comment]
I will note that Ministries commonly refer to the package for sign-off as the redline, so that would definitely make things more clear - especially if we have a seperate function to export the non-redacted records

**Comment by JHarrietha-AOT** [comment]
@lmullane I'm thinking those options will be in the module. so its one button where a module with appear and they can select (or we create a preset) whether it is redline or not, any specific flags to send records for consult or divisions

**Comment by JHarrietha-AOT** [comment]
@lmullane @m-prodan 

Again, took a similar approach as #3231/#3437/#3302. to avoid a series of buttons I have combined into a dropdown so users can download separate versions of the records as need in the process. 

Design for #3301 & #3241
In process (if back end is compiling any of the download options)
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262

Active and ready to download: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423264

Download Harms - download in divisional folders with no redline
Download Redline for Sign Off - download in divisional folders with redline boxes and sections
Download Final Package - Final Package for ministry users to be able to access and see final redactions applied

**Comment by lmullane** [comment]
@m-prodan, can we have only redlines broken up by Division instead of offering one redline?

**Comment by lmullane** [comment]
As discussed at standup, the Records log filters are independent of the download. Applying a filter (e.g.by a divisional, error, etc. tag) on the Records Log will have no impact on what is downloaded.

**Comment by m-prodan** [comment]
Note from standup - we will likely need to revise/re-refine this ticket, effort will likely increase due to changes in approach (re: client side-stitching). We should put this on our next refinement to discuss any updated requirements/estimates.

cc: @abin-aot @richard-aot

**Comment by richard-aot** [comment]
@m-prodan @lmullane  This is the user story connecting 3437 (saving) and 3301 (download). When saving redline for ministry signoff, we will create one merged pdf file for each of the divisions. Then, a backend process will create one zip file for each division, including the merged pdf file and any incompatible files for that division. And send "ready for download" notification. The user story should including above features.

**Comment by m-prodan** [comment]
This will need the zipping microservice to be pushed. Work can be done on local

**Comment by lmullane** [comment]
@abin-aot to bring for refinement again with devs to see the impact of zipping.

**Comment by m-prodan** [comment]
Note: Add scenarios for when it completes successfully, and if it errors out.
Changes to flags/redactions are already covered in the "save redline" story so can remove those AC

**Comment by m-prodan** [comment]
Replaced scenarios 5 and 6 with complete and error scenarios after stitching. Please let me know if this reflects our discussion this morning at standup @divyav-aot

**Comment by divyav-aot** [comment]
Thanks @m-prodan . You can remove scenario 2(as we won't be having any "in progress" status for download redlines.) and 3 (Scenario 5 covered this)

**Comment by KyEggleston** [comment]
<h2>Bug 1</h2>

In the 'Redline for Sign Off' package, Excel files appear to have some conversion/formatting issues. 

For example, the Excel file below appears as the following in the Harms package:
![image](https://github.com/bcgov/foi-flow/assets/117312323/4b89e0c3-cb3a-4a66-a6d3-dfa07dcc0972)

In the Redaction App, it looks like the following:
![image](https://github.com/bcgov/foi-flow/assets/117312323/fd4f7444-b65e-4eec-958d-03ed3611a16d)

However, in the 'Redline for Sign Off' package, it appears to be cut off:
![image](https://github.com/bcgov/foi-flow/assets/117312323/54af59f7-d944-4693-9a98-b1165b2e0341)

<h2>Bug 2</h2>

It appears that the 'Redline for Sign Off' is not organizing the package based on modified date (e.g., like the Harms package).

For example, here are the three files organized based on modified date (oldest to newest):

![image](https://github.com/bcgov/foi-flow/assets/117312323/deeea7c7-eba2-44cf-a2ea-a1c58ef896f0)

In the Harms package, this ordering is maintained (first is _Scanned Notes.pdf_, then _TEST Records - CFD - ICM Report - Good.pdf_, then _Employee Spreadsheet.xlsx_:
![image](https://github.com/bcgov/foi-flow/assets/117312323/ab69bf2c-4485-4a96-9378-165a68fe2e14)

However, in the 'Redline for Sign Off', files appear to be organized by their upload date (to the Records tab). In the image below, the _Employee Spreadsheet.xlsx_ is showing up first in the package, then _TEST Records - CFD - ICM Report - Good.pdf_, _Scanned Notes.pdf_ :

![image](https://github.com/bcgov/foi-flow/assets/117312323/2499852d-0f51-4a7c-92e5-cd559e0be81a)

In the 'Redline for Sign Off' packages, the packages should continue to be organized based on file modified date (i.e., just like the Harms package)

**Comment by divyav-aot** [comment]
@richard-aot - can you look into above issues related to redline stitching?

**Comment by richard-aot** [comment]
@divyav-aot Sounds good. I'll look into this.

**Comment by divyav-aot** [comment]
As discussed in the standup, the probability of a request containing only incompatible files is low. If such a case does exist, IAO will handle it manually.
cc. @m-prodan @lmullane @KyEggleston

**Comment by divyav-aot** [comment]
@KyEggleston the above mentioned bugs are related to Save redlines (pdf stitching). @richard-aot will be working on this once he finishes his current task.

**Comment by abin-aot** [comment]
Bug #4461 need to be fixed before going to prod. this issue is happening with specific kind of excel/pdf combination

**Comment by abin-aot** [comment]
Error scenarios cant be easily created, that matches the real world situation , but I have updated status on one of the request as below and its displaying as error. Now, there is an idea to change the logic on the display side of the Download Response, Redline and harms to automatically display error icon if there is NO status udpate after a configured amount of time. @abin-aot  to create that task

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTh3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d81b92cda99abbbb36009666d2cf308a8f2f599e/image.png)

**Comment by abin-aot** [comment]
EDU-2023-11101457 on TEST-Marshal or https://test-marshal-foirequest.apps.silver.devops.gov.bc.ca/foi/foirequests/683/ministryrequest/683

**Comment by liseandtea** [comment]
Closing ticket as per Abin's comments above and at stand up this morning.
