### ISSUE TITLE
Add Indigenous Governing Entity

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3307]
* As an IAO user 
* I want Indigenous Governing Entity
* so that I can track this applicant category and not have a sync issue with AXIS

**Assumptions & Scope**	
What are the assumptions for this story?

Indigenous Governing Entity has been added as an applicant category in AXIS, but not FOI Mod. When a request has this applicant category, when the request is synced, the category show as 'blank' in FOI Mod.
 
What is IN scope?

Add Indigenous Governing Entity as an Applicant Category in FOI Mod.

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Sync IGE Applicant Category**
* GIVEN a request is an IGE in AXIS
* WHEN the request is synced
* THEN the applicant category in FOI Mod will read "Indigenous Governing Entity"

**Scenario 2: IGE Applicant Category**
* GIVEN an IAO analyst is on the request view
* WHEN the analyst clicks Category
* THEN "Indigenous Governing Entity" is an option on the drop down

**Scenario 3: IGE Applicant Category**
* GIVEN an IAO analyst has opened the Applicant Category drop down
* WHEN the analyst clicks "Indigenous Governing Entity" 
* THEN "Indigenous Governing Entity" will be selected
* AND be displayed in the category field
...
![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/b51e3f12-bff6-429b-8889-63d2822943c7)
![Screen Shot 2023-01-20 at 4.02.37 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/1b97573b-63e9-42a9-991d-9bccf7b99a10)

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by abin-aot** [comment]
@KyEggleston , @m-prodan  , @lmullane  this is ready for testing. if its TESTED good, we can push this to PROD EOD today!. Assuming this solve the issue with "ACTIVE=FALSE" / disappearing request from queue happened with requests like, TRA-2022-22426  on prod.

**Comment by KyEggleston** [comment]
@abin-aot - synching from the Axis request pulls the IGE category into the FOI Mod request, and all ACs pass. This is good for prod. 

cc: @lmullane, @m-prodan, @liseandtea
