### ISSUE TITLE
On Hold and Emails - No Email Box Checked can Trigger an Email to Send

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3315]
**Describe the bug in current situation**
It was found while onboarding activities were underway that emails would be sent to applicants during the on-hold state transition, even when no email is present. 

**Link bug to the User Story**

**Impact of this bug**
When staging in flight requests, this can cause emails to be inadvertently sent to applicants, which can cause confusion

**Chance of Occurring (high/medium/low/very low)**
Medium - onboarding in-flight requests occur monthly, and only requests that had prior fees will be impacted

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
TEST

**Steps to Reproduce**
1. Go to a synced general request and set it to fee estimate
2. Remove applicant's email address and save
3. Change state to on-hold, and check box confirming that letter has been sent to the applicant
4. Sync request to update applicant email
5. Applicant will receive the fee email

**Actual/ observed behaviour/ results**
Mailing service appears to be checking all requests that have gone on hold, and attempts to retry if there is no letter sent. Assumption is the mailer is detecting a new email added, and is automatically sending the correspondence even though the box was checked that a letter was already sent to the applicant.

**Expected behaviour**
GIVEN a user has checked the box confirming the letter has been sent to the applicant
* WHEN They click continue
* THEN The modal will close, the state will change, and the email service will NOT run on this request

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
Note: this will need to be fixed by April when more fee heavy Ministries begin onboarding

**Comment by sumathi-thirumani-aot** [comment]
Increased the effort to include the data capture (offline payment method) in the backend to cover the case of legacy applications.

**Comment by lmullane** [comment]
Tested with 2 requests. Removed emails and put both requests On Hold. No emails received or logged in Contact Applicant log.

Closing as complete. Thanks, @sumathi-thirumani-aot
