### ISSUE TITLE
PSE User unable to tag IAO users in comments

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3323]
**Describe the bug in current situation**
A bug was reported by a PSE user regarding tagging IAO users - originally it was reported as being unable to tag in reply comments, and when offered the workaround of submitting a new comment, the user noted it wasnt working.

Related to #3260

Testing shows that the foipse user also has this bug - but other Ministry user profiles do not, so it seems limited in scope to just this user group.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
High for PSE users specifically

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to any request in TEST as a PSE user
2. Go to comments 
3. Attempt to tag an IAO user

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
@sumathi-thirumani-aot to provide estimate

**Comment by KyEggleston** [comment]
@aparna-aot - Tested, and confirm this is working in TEST now, and all IAO users are able to be tagged by a ministry user in replies under the 'Comments' tab. Created and added release label for this hotfix/patch.
