### ISSUE TITLE
Onboarding update - Divisions for PSA

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3329]
Title of ticket: 

#### Description
After Training, PSA provided an updated list of divisions. Many divisions will remain, with a number to be added and removed. 

#### Dependencies
Are there any dependencies?

#### DOD
**To Add**
- [x] HRSS Records
- [x] HR Specialist Case Files
- [x] BCPSA Classifications
- [x] Contact Centre
- [x] Peoplesoft Reports
- [x] Performance Records
- [x] Job Competition Files
- [x] POD - Executive Talent Management
- [x] POD - Corporate Workforce Strategies
- [x] POD - Learning Centre
- [x] PIE - Policy and Research
- [x] PIE - Behavioural Insights Group
- [x] Employee Relations - Workforce Restructuring
- [x] Employee Relations - Investigations
- [x] Labour Relations - Grievances
- [x] Information Technology Services
- [x] Surveys and Measurement
- [x] Corporate Health Programs

**REMOVE from existing list**
- [x] Business Performance
- [x] Custom Research
- [x] Corporate Health Program
- [x] Employee Relations
- [x] Policy, Innovation & Engagement
- [x] People and Organizational Development

**Comment by m-prodan** [comment]
Divisions updated for onboarding activity

**Comment by KyEggleston** [comment]
Confirmed updates in Test, closing ticket.
