### ISSUE TITLE
Org Code Updates and Changes - Future Onboarding

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3345]
Title of ticket: Org Code Updates - Future Onboarding

#### Description
Upcoming onboarding will require some changes in existing codes from AXIS, with new codes being made for new Ministries

#### Dependencies
Are there any dependencies?

#### DOD
- [x] ADD new public body code for Ministry of Housing (AXIS Public Body Code: HSG)
- [x] UPDATE Existing public body code for EMB to EMC
- [x] UPDATE Ministry name for EMC/EMB to "Ministry of Emergency Management and Climate Readiness"
- [ ] REMOVE Linkage from EMC/EMB to PSS in stats for Redash - it is now its own Ministry
- [x] UPDATE Existing public body code for LWR to WLR
- [x] UPDATE Ministry name for LWR/WLR to "Ministry of Water, Land and Resource Stewardship"
- [x] ADD new action office "COR" as Corrections Branch
- [ ] Link Corrections Branch to PSS reporting (COR is sub-org of PSS)

**Comment by m-prodan** [comment]
Note: adding a task to create a new action office in AXIS (Andrew will handle this part) called COR - which we will then use as a child public body to the Ministry of Public Safety (PSS)

**Comment by abin-aot** [comment]
@m-prodan : Could you please let me the divisions required for HSG, WLR , EMC and  COR?

**Comment by KyEggleston** [comment]
@abin-aot - as discussed in standup, Housing (HSG) falls under Justice / Health Processing Team.

**Comment by abin-aot** [comment]
Thanks @KyEggleston . I pushed changes to TEST. Please have a look. The unlinking changes of PSS  EMC and linking on COR- PSS can be done as data get pushed after this test to TEST EDW.

**Comment by KyEggleston** [comment]
Thanks @abin-aot, and the updated codes/names look good in Test- I'll make a note of the remaining two items (unlinking PSS -EMC and linking COR-PSS) when I set up their reporting. I don't think there's anything else to do here, so I'll close. 

cc: @m-prodan

**Comment by abin-aot** [comment]
@KyEggleston @m-prodan , I am adding this to Justice 6.1 release ! Thoughts?

**Comment by KyEggleston** [comment]
@abin-aot - makes sense to me!

**Comment by KyEggleston** [comment]
Prod Redash queries/dashboards made for MAG, PSS, EMC and HSG. 

PSS queries include procorg 'COR'.

@abin-aot - let me know if anything needs to be done to ensure these reports are correct (outside the standard query/dashboard creation process)
