### ISSUE TITLE
Onboarding [Ministry Name]

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3355]
Title of ticket: This is an onboarding template

#### Description
Include any relevant information for onboarding

#### Dependencies
Are there any special requirements that need to be met?

#### DOD
- [ ] Onboarding Time Scheduled
- [ ] Bi-Weekly Onboarding Check ins set
- [ ] Divisions Received and Understood
- [ ] Dashboard setup
- [ ] User Training Scheduled
- [ ] Divisions added to application
- [ ] Training Completed
- [ ] Migration of Active Requests Complete

**Comment by KyEggleston** [comment]
Closing, as tracked elsewhere (onboarding spreadsheet)
