### ISSUE TITLE
Create S3 Buckets with Server Side Encryption ON

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3376]
Title of ticket: 

#### Description
As per task #3322  and decision on Data at rest for documents, all buckets(except few!) need to have Server Side Encryption ON. Refer comments on #3322.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Plan for scripting to create new S3 Buckets with Server Side encryption during creation - This includes all ministry level buckets (dev, test, prod) , form-attachments buckets!. We can leave Strapi/foi-help buckets and DB Back up , since those data wotn have Prot. C
- [x] Follow the naming convention lijke ECC-DEV-E or any other user friendly naming as per the situation. 
- [ ] 
- [ ] 
- [ ]

**Comment by m-prodan** [comment]
Note from sprint planning: Aparna to join Richard after FE task complete on FOIPPA section modal

**Comment by richard-aot** [comment]
Manually created new buckets instead of using script, because this is a one time job.
