### ISSUE TITLE
Develop script to migrate S3 files, documents to encrypted buckets using RCLONE

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3377]
Title of ticket: 

#### Description
Based on #3322 and #3336, the existing files need to be migrated to the new S3 buckets with Encryption ON. For this we need to use either Rclone(free!) with bash script or paid version of S3 Browser(50$) 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Script for dev buckets
- [x] Script for test buckets
- [x] Script for prod buckets
- [x] Resolve the empty folder name issue

**Comment by m-prodan** [comment]
Note from sprint planning: Aparna to join Richard after FE task complete on FOIPPA section modal

**Comment by richard-aot** [comment]
Ready for release
