### ISSUE TITLE
Search function incomplete in FOI Help

### ISSUE THREAD

**Issue by katrinaferacini** [bcgov/foi-flow#3382]
**Describe the bug in current situation**
Not all articles appear on help.foirequests.gov.bc.ca/help-articles, therefore the search bar in FOI Help does not pull up all results. Is it possible that there is a limit of 25 help articles to appear? The following help articles do not appear on the main list: Fees Training October 2022, Paid Fee - IAO and Ministry, Clarify Fee Estimate - Ministry, Outstanding Fee Payment - IAO, FOI Mod Overview with Trans January 2023.

Link bug to the User Story

**Impact of this bug**
Moderate - users might not be able to find a specific video, or think it is not available

**Chance of Occurring (high/medium/low/very low)**
High - The same videos are omitted from the search results each time. The same videos are omitted from the list of help articles.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Strapi Frontend Production: https://help.foirequests.gov.bc.ca/help-articles

**Steps to Reproduce**
Go to Strapi Frontend Production
Type in "Clarify" in the search bar.  
The "Clarify Fee Estimate - IAO" help article will populate as a search result. 
The "Clarify Fee Estimate - Ministry" help article does not populate, even though it should.

Expected behaviour
GIVEN a user types in a key word in the search bar 
WHEN the key word is contained in one of the help article titles or video descriptions
THEN the help article should populate as a search result

Screenshots/ Visual Reference/ Source![Example 1 - Clarify.PNG](https://images.zenhubusercontent.com/633318928b7f4e47a5d154ec/5d87cd06-c014-4158-b823-e4bde5da5a23)![Example 2 - Trans.PNG](https://images.zenhubusercontent.com/633318928b7f4e47a5d154ec/7f4b9a4f-c8c4-4aec-b6e7-a449f89b8b62)

**Comment by katrinaferacini** [comment]
**Describe the bug in current situation**
The search bar in FOI Help does not pull up all results. 

Link bug to the User Story

**Impact of this bug**
Moderate - users might not be able to find a specific video, or think it is not available

**Chance of Occurring (high/medium/low/very low)**
High - The same videos are omitted from the search results each time.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Strapi Frontend Production: https://help.foirequests.gov.bc.ca/help-articles

**Steps to Reproduce**
Go to Strapi Frontend Production
Type in "Clarify" in the search bar.  
The "Clarify Fee Estimate - IAO" help article will populate as a search result. 
The "Clarify Fee Estimate - Ministry" help article does not populate, even though it should.

Expected behaviour
GIVEN a user types in a key word in the search bar 
WHEN the key word is contained in one of the help article titles or video descriptions
THEN the help article should populate as a search result

Screenshots/ Visual Reference/ Source![Example 1 - Clarify.PNG](https://images.zenhubusercontent.com/633318928b7f4e47a5d154ec/5d87cd06-c014-4158-b823-e4bde5da5a23)![Example 2 - Trans.PNG](https://images.zenhubusercontent.com/633318928b7f4e47a5d154ec/7f4b9a4f-c8c4-4aec-b6e7-a449f89b8b62)

**Comment by KyEggleston** [comment]
Looks good, and I'll move to the top of the new issues so it's picked up for refinement

**Comment by KyEggleston** [comment]
@lmullane @m-prodan - just a note to look into bringing this in next sprint for Katrina (discuss at sprint planning tomorrow)

**Comment by katrinaferacini** [comment]
It might make sense to include task 3569 with 3473 and 3382.

**Comment by lmullane** [comment]
Look at increasing the number of help articles listed beyond the current cap of 25.

Client side search will only search the 25 articles on the page.

**Comment by lmullane** [comment]
@katrinaferacini , could you confirm this is working?

**Comment by katrinaferacini** [comment]
@richard-aot Thank you for working on this! I'm wondering what the new cap for articles appearing on the page is? Also, it looks like you have updated both the test and prod environment. Is this correct?

**Comment by katrinaferacini** [comment]
QA complete.

**Comment by richard-aot** [comment]
@katrinaferacini You are welcome. The new cap is 100. Let me know if you want to increase the limit. And yes, the updates have been pushed to test and prod env already.

**Comment by katrinaferacini** [comment]
@richard-aot If it's easy to do, I would say put 200 to prevent having to update in the future. :)

**Comment by richard-aot** [comment]
@katrinaferacini . Sounds good. It is updated to 200 now.

**Comment by katrinaferacini** [comment]
Thank you!
