### ISSUE TITLE
File Conversion: No pdf generated if email is dragged from Outlook to Test LAN (#138)

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#339]
**Describe the bug in current situation**
We were testing for emails containing excel or ical attachments. When the email is dragged directly from Outlook to a newly created folder on the LAN, File Watcher does not generate an output. Log registers the file upload but notes "exception" in the Comment column. See \\pelican\testfoishare\AED\Call for Records\AED-20210812-1607\Log for an example. File watcher works if the same files are dragged from the Outlook inbox to Desktop first, and then into the folder.

**Link bug to the User Story**
#138

**Impact of this bug**
Any users needing to upload requested files from their emails would first need to download email messages to their desktop, before being able to upload them to the LAN with the filewatcher

**Chance of Occurring (high/medium/low/very low)**
high

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
This would be a likely scenario for ministries with smaller file sizes, where files get sent through email
(Note: we did not test a drag and drop from other gov programs like eapps, though this would be another common place files get shared through)

**Steps to Reproduce**
1. Go to 'microsoft outlook inbox'
2. Click on 'any email containing an attachment.'
3. Create a new test folder on the LAN for file watcher
4. Drag email from inbox into newly created folder
4. Click on the Log subfolder that gets generated and open file. It will read "exception" under Comments column, and no Output folder will have been generated

**Comment by abin-aot** [comment]
Does this bug has significance now?

**Comment by lmullane** [comment]
Stale. Moving records from one LAN folder to another.
