### ISSUE TITLE
Analysis and Update , Fixes to  existing QA automation scripts

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3391]
Title of ticket: 

#### Description
The purpose of this task is to review the current state of Katalon QA Automation scripts and do necessary updates/fixes as per the review. @nkan-aot can help with current QA Automation Git Repo Branch and other related configurations. @nimya-aot can collect updated Business/ User acceptance Test Scripts from Business Team( @KyEggleston , @m-prodan , @lmullane , @liseandtea ) and cross check with QA automation scripts to find the gaps. Prior to this task, its better to understand the FOI FLOW App and related request management functional flow. 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Create a child branch from @nkan-aot  QA automation branch and Load the Katalon project locally
- [x] Execute the Test cases/Test Suites as per the logical order and/or as per UAT scripts. Say like, Queue Tests, Add Request Test etc. 
- [x]  Analyse and Tabulate the failures, gaps and efforts to be done to make the QA automation scripts update to date
- [x]  Review with Dev Team - @nkan-aot , @abin-aot and project the effort to Business
- [x] Either increase the estimate of this task and/or create new QA Automation Task as per the analysis

**Comment by nimya-aot** [comment]
Analysis of gap on automation
--------------------------------


1. Queue sorting - Logic updating - New one required
2. AXIS Sync - Need to create
3. CFR Fee Estimate and related - Need to create
3 a.contact applicant
4.System Generated comments - Update the scripts with new.
5.Extension testcases-Related LDD
6.FOI Request submission-payment calculation??






#########################################################################

Work update on #3391 , Test Suites

1. FOI-TEST-ATTACHMENTs - Done
2. FOI-test-CFR-state - 90% fixed, 1 test case need update  - Queue logic update required
3. FOI-TEST-CLOSED State - 4/5 are Failing, Need to update
4. FOI -TEST - COMMENTING - Completed, Need to verify
5. foi-test-create request and request-queue - In Progress , Received date issue
6. foi-test-failure - Failure working as expected,? DONE
7. foi-test-githubactions -  Consult
8. foi-test-homepage-and-login - DONE
9. foi-test-intake-in-progress-state - DONE
10.foi-test-notifications - Cant test in local - access required.
11.foi-test-remaining-state-changes- Need to rework (95% TS failing)
12.foi-test-request-form- DONE
13.foi-test-review-state- TODO - related with state changes
14.foi-test-watchers - Done ,

**Comment by nimya-aot** [comment]
Work update on #3391 , Test Suites

1. FOI-TEST-ATTACHMENTs - Done
2. FOI-test-CFR-state - DONE
3. FOI-TEST-CLOSED State - 3 working, Last 2 testcases with Fee estimate stateneeds CFR testcase updation
4. FOI -TEST - COMMENTING - DONE
5. foi-test-create request and request-queue - In Progress , Received date issue
6. foi-test-failure -  DONE
7. foi-test-githubactions -  Consult
8. foi-test-homepage-and-login - DONE
9. foi-test-intake-in-progress-state - DONE
10.foi-test-notifications -DONE
11.foi-test-remaining-state-changes- done -7/10 are passing,3 testcases rest needs update with CFR testcase updation
12.foi-test-request-form- DONE
13.foi-test-review-state- DONE
14.foi-test-watchers - DONE

**Comment by nimya-aot** [comment]
Work update on #3391 , Test Suites

1. FOI-TEST-ATTACHMENTs - Done
2. FOI-test-CFR-state - DONE
3. FOI-TEST-CLOSED State - 3 working, Last 2 testcases with Fee estimate state needs CFR updation
4. FOI -TEST - COMMENTING - DONE
5. foi-test-create request and request-queue-DONE
6. foi-test-failure -  DONE
7. foi-test-githubactions -  Consult
8. foi-test-homepage-and-login - DONE
9. foi-test-intake-in-progress-state - DONE
10.foi-test-notifications -DONE
11.foi-test-remaining-state-changes- done -7/10 are passing,3 testcases rest needs update with CFR testcase updation
12.foi-test-request-form- DONE
13.foi-test-review-state- DONE
14.foi-test-watchers - DONE
