### ISSUE TITLE
Justice Sector Onboarding - Divisions

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3392]
Title of ticket: 

#### Description
To onboard Justice - the following divisions need to be added to the divisional tracker for the following public bodies.
Note: Sort order should be as listed, and not alphabetical or otherwise

#### DOD - Ministry of Attorney General (MAG)
- [x] Minister's Office
- [x] Deputy Attorney General
- [x] Corporate Management Services Branch
- [x] Information Systems Branch
- [x] Multiculturalism
- [x] Court Services Branch
- [x] Legal Services Branch
- [x] Justice Services Branch
- [x] Investigation & Standards Office

#### DOD - Public Safety and Solicitor General (PSS)
- [x] Minister's Office
- [x] Deputy Solicitor General
- [x] RoadSafety BC
- [x] Corporate Management Services Branch
- [x] Information Systems Branch
- [x] Cannabis, Customer Protection and Corporate Policy
- [x] Community Safety and Crime Prevention
- [x] Victim Services and Crime Prevention
- [x] Civil Forfeiture Office
- [x] Liquor and Cannabis Regulation Branch
- [x] Policing and Security Branch
- [x] Gaming Enforcement and Policy Branch
- [x] Office of the Fire Commissioner
- [x] Corrections Branch

#### DOD - Housing (HSG)
- [x] Minister's Office
- [x] Deputy Minister's Office
- [x] Housing and Land Use Policy 
- [x] Strategy, Governance and Accountability
- [x] Homelessness, Partnership and Housing Support
- [x] Residential Tenancy Branch

#### DOD - Emergency Management and Climate Readiness (EMC)
- [x] Minister's Office
- [x] Deputy Minister's Office
- [x] Associate Deputy Minister's Office
- [x] Executive Operations
- [x] ADMO, Regional Operations
- [x] ADMO, Disaster Risk Management
- [x] ADMO, Disaster Recovery
- [x] ADMO, Corporate Support Services
- [x] Regional Ops Regions
- [x] Regional Ops Programs
- [x] Strategic Partnerships
- [x] Policy, Leg, and Enforcement
- [x] Corp. Planning and Priorities
- [x] Recovery and Resiliency Sec.

#### DOD - Corrections (COR)
- [x] Corrections

**Comment by KyEggleston** [comment]
Confirmed, closing ticket.
