### ISSUE TITLE
Develop SQL scripts to update S3 File Path

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3393]
Title of ticket: 

#### Description
After #3376 , we need to update File path on the data inside the FOI FLOW Database. The purpose of this task is to create a SQL script to the old bucket name to new one in DEV, TEST, PROD.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Develop scripts for S3FilePath references - Attachments, Gathering recording on Marshal?
- [x] Update FilePaths on DEV , TEST
- [x] Ready for prod migration
- [ ] 
- [ ]

**Comment by richard-aot** [comment]
Ready for release
