### ISSUE TITLE
GitHub Security Reports - DocReviewer 

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3394]
Title of ticket: 

#### Description
Alerts to be fixed

#### Dependencies
Are there any dependencies?

#### DOD
List the items that need to be completed for this ticket to be considered done (High & Critical). Potentially can include the version upgrades of medium or low (if any)
- [ ] https://github.com/bcgov/foi-flow/security/dependabot
- [x] https://github.com/bcgov/foi-docreviewer/security/dependabot

Note: https://github.com/bcgov/foi-requests 
Above link corresponds to the angular app (Low Prioritized)

**Comment by m-prodan** [comment]
@sumathi-thirumani-aot to define issues for ticket. Can you estimate and put in product backlog

**Comment by abin-aot** [comment]
Need to cover things from https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/3834

**Comment by abin-aot** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm9nQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9dbf3a6c27c095bab6d7406c007b774e7cffbfd5/image.png)
