### ISSUE TITLE
UPDATE ENV variables and testing - DEV, TEST and PROD

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3395]
Title of ticket: 

#### Description
The purpose of this task is to update the bucket name (new!) on the ENV VARs and test  the functionalities. - Refer #3376

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Updated on DEV
- [x] Updated on DEv-Marshal
- [x] Updated on TEST - Marshal
- [x] Updated on TEST
- [ ]

**Comment by richard-aot** [comment]
Ready for release
