### ISSUE TITLE
Update DELL GeoDrive configuration 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3396]
Title of ticket: 

#### Description
The purpose of this task is to update DELL GEO DRIVE CONFIGURATION for new S3 Encrypted buckets on PENGUIN. this is moving LAN archive files (CFR) to S3 buckets

#### Dependencies
Are there any dependencies? if @abin-aot not free, please take KT

#### DOD
- [x] Analyse the DELL Geodrive current state on PENGUIN
- [x] Backup local files on server
- [x] Delete current GEODRIVE mappings for old s3 buckets
- [x] Create new GEODRIVE mappings for new s3 buckets

**Comment by lmullane** [comment]
@abin-aot, does this need to be done for the 7.0 Release?

**Comment by richard-aot** [comment]
All GEODRIVE are mapping to new encrypted s3 buckets now.
