### ISSUE TITLE
Attachments - Reclassify File Tag 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3398]
* As a IAO or Ministry User
* I want the ability to update a file's file tag on the 'Attachment' tab
* so that I can ensure files are correctly tagged for tracking and auditing purposes

**Assumptions & Scope**	
What are the assumptions for this story?

This was raised by a user who noticed attachments were being uploaded with incorrect tags (i.e., they aren't reflective of what the actual attachment is). This can make it difficult to find attachments if many attachments have been uploaded, and can be confusing. 

User should have the ability to update/change a file's file tags in the 'Attachments' tab, rather than requiring them to reupload the file with the correct tag.

If a user changes a file tag to 'Applicant', then the visibility of the 'Applicant' file tag applies (as described under #3998)

If you reclassify an attachment, the upload date of the file should not change. 

What is IN scope?
Attachments log

What is NOT in scope?
Gathering records log 

**Acceptance Criteria**	

**Scenario 1: 'Reclassify' Option**
* GIVEN an IAO or ministry user is on the 'Attachments' tab
* AND there is an attachment uploaded by a user
* WHEN the user selects the ellipsis for an attachment
* THEN they will have the option to 'Reclassify'

**Scenario 2: 'Reclassify' Modal**
* GIVEN an IAO or ministry user is on the 'Attachments' tab
* AND there is an attachment uploaded 
* WHEN the user clicks the ellipsis and selects 'Reclassify'
* THEN a modal will appear displaying the available tags for attachments (e.g., General, Applicant, CFR, etc.)
* AND the tags will be selectable
* AND the options to 'Save' or 'Cancel'

**Scenario 3: 'Reclassify' Modal - No Tag Selected**
* GIVEN an IAO or ministry user is on the 'reclassify' modal
* WHEN no new tag has been selected
* THEN the 'Save' button will be greyed out
* And the 'Cancel' button will be active

**Scenario 4: 'Reclassify' Modal - Tag Selected - Cancel**
* GIVEN an IAO or ministry user is on the 'reclassify' modal with a new tag selected
* WHEN the 'Cancel' button is clicked
* THEN the modal closes
* AND the user is brought back to the 'Attachments' tab
* And no changes will be made

**Scenario 5: 'Reclassify' Modal - Tag Selected - Exit**
* GIVEN an IAO or ministry user is on the 'reclassify' modal with a new tag selected
* WHEN the 'Exit' (X) button is clicked
* THEN the modal closes
* AND the user is brought back to the 'Attachments' tab
* And no changes will be made

**Scenario 6: 'Reclassify' Modal - Tag Selected - Save**
* GIVEN an IAO or ministry user is on the 'reclassify' modal with a new tag selected
* WHEN the 'Save' button is clicked
* THEN the modal closes
* AND the user is brought back to the 'Attachments' tab
* AND the new tag will be associated to the attachment
 
**Scenario 7: System Tagged Files**
* GIVEN an IAO or ministry user is on the 'Attachments' tab
* AND there is an attachment that was uploaded and tagged by the system
* WHEN the user selects the ellipsis for an attachment
* THEN they will NOT have the option to 'Reclassify'

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	
Similar to when uploading an attachment, only one tag can be selected for an attachment. 

**Design**
Need design for modal?

@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
@lmullane @m-prodan @liseandtea - created based on user feedback in FOI Mod support channel.

**Comment by m-prodan** [comment]
Note: add validation/AC to not allow this for any system generated file tags (eg - state change, fee estimate sent etc.)

**Comment by divyav-aot** [comment]
**Refinement notes:** No need of comments/notifications for the re tagging.

**Comment by KyEggleston** [comment]
For QA - test ellipsis functions on a retagged attachment, preview in browser.

**Comment by m-prodan** [comment]
Tested additional items per @KyEggleston - all AC's pass. Nice work @milosdes
