### ISSUE TITLE
FOI Request Form (Angular App) - Double Charging on Environment and EAO

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3401]
**Describe the bug in current situation**
An issue was raised by our intake team, where they noticed the applicant may have been inadvertently charged twice for submitting a request to both the Ministry of Environment (MOE) and Environment Assessment Office (EAO)

**Link bug to the User Story**

**Impact of this bug**
Applicants will be extra charged, and IAO will have to process refunds.

**Chance of Occurring (high/medium/low/very low)**
Medium - behaviour happens every time an applicant selects both MOE and EAO, but only if the applicant makes such a choice.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to the test form and submit a general request
2. Click on Ministry of Environment and Environmental Assessment Office
3. Scroll down to Total
4. See value showing as $20 (wrong value)

**Actual/ observed behaviour/ results**
On receipt generation - when both are picked, it shows two lines for the Ministry of Environment:

Environment and Climate Change Strategy $10.00

Environment and Climate Change Strategy (and 
Minister Responsible for Translink) $10.00
 Environmental Assessment Office

**Expected behaviour**
GIVEN an applicant is submitting a general request
WHEN they select Ministry of Environment
AND Environmental Assessment Office
THEN they will only be charged the single 10 dollar value

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/fe50458c-6a1d-481e-ad40-d47eb6f9280d)

**Comment by m-prodan** [comment]
@abin-aot - appreciate the quick work! Couple things:
1) Emails aren't being sent to the inbox, so I can't confirm that part for QA - can you update the test inbox to me or the usual test inbox?

2) Issue appears to be fixed, but on the receipt there is an issue:

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/fc930d60-a714-4dbb-b2a4-ab02fa9b4c6b)

Can the correct name move up and replace the old name? Apologies for my drawing, hope it makes sense!

**Comment by abin-aot** [comment]
@m-prodan , I followed the same pattern of 'Finance' and others which has one charge for multiple public body selection. This one will be grouped under 'Environment' . Also updated TEST FOI Request Submission inbox with  yours
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/76e22a67-17b7-43ef-bf85-ee3634962ab6)

**Comment by m-prodan** [comment]
@abin-aot  - just did a quick check, it's getting there. - but there should only be Environmental Assessment Office grouped under "Environment and Climate Change Strategy" - right now the receipt just shows Environment, and groups both Environment and Climate Change Strategy, and Environmental Assessment Office.

It should look more like this:

Environment and Climate Change Strategy             $10.00

               Environmental Assessment Office

**Comment by m-prodan** [comment]
@abin-aot - QA Passed - created a new release, 5.1 emergency hotfix - shall we deploy around lunch time?

cc: @lmullane

**Comment by abin-aot** [comment]
@m-prodan , @lmullane : deployed!
