### ISSUE TITLE
Remove PDFTron functionality

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3408]
Title of ticket: 

#### Description
Summarize issue 
PDF Tron has a number of features that should never be used for FOI. Analysts should not be able to access the document editing tools, with the exception of replacing a deleting individual pages which remain an analyst decision.

These menu items will be removed from the PDFTron toolbar: insert, edit, edit text, fill and sign, forms
![Screen Shot 2023-02-21 at 11.37.33 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/6157eb9d-55bc-4a73-82a5-cb0618550f0b)

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Remove Insert
- [x] Remove Edit
- [x] Remove Edit Text
- [x] Remove Fill and Sign
- [x] Remove Forms

**Comment by abin-aot** [comment]
@lmullane  , @m-prodan : As mentioned on Teams, I am 'removing' the options(delete, INSERT, Replace page) on Thumbnail panel(left) , in addition to what is mentioned on ACs


![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/04d2107a-80b7-426a-afa5-399efb1c76a9)

**Comment by lmullane** [comment]
Good catch. Thanks, @abin-aot

**Comment by m-prodan** [comment]
As discussed at stand up - analysts still need to be able to make decisions to remove individual pages (eg - blank pages) as they review

**Comment by KyEggleston** [comment]
@m-prodan @abin-aot - do we still need the 'Replace' option in the thumbnail pane? We're keeping 'Delete' from what I understand, but not sure if 'Replace' should still be an option.  

![image](https://user-images.githubusercontent.com/117312323/225064064-e4dedca3-7f72-4d49-b266-9f536eae2297.png)

**Comment by KyEggleston** [comment]
Confirmed in standup to keep replace. Closing ticket.
