### ISSUE TITLE
Page Flag Filter and Views

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3417]
* As an IAO analyst
* I want to be able to filter by page flag and see my results
* so that I can better manage the records package

**Assumptions & Scope**	
What are the assumptions for this story?

All icons free from FontAwesome

What is IN scope?
Page flag filtering
Total filtered pages counter
Percentage of filtered pages vs total pages counter
Filtered Pane views/functionality

What is NOT in scope?
'Left Off Here' page flag functionality (#3409)
Page flags (#3413)
Page flags tooltip (#3413)
Percentage complete ((#3413)
Export page

**Acceptance Criteria**	

**Scenario 1: Filter By Section**
* GIVEN an IAO analyst is in the redaction app 
* WHEN they view the left pane under 'Organize by'
* THEN there will be an option to 'Filter by'
* AND all the page flag icons will be listed and selectable
* AND no filters will be selected by default

**Scenario 2: Select Page Flag Filters**
* GIVEN an IAO analyst is in the 'Filter by' section
* WHEN one or more page flag filters icons are selected
* THEN the selected page flag filters will change to blue and selected
* AND all the panes (left pane, preview pane, and working pane) will be filtered by the selected filters

**Scenario 3: Remove Page Flag Filters**
* GIVEN an IAO analyst has selected one or more page flag filters 
* WHEN the user unselects any page flag filter
* THEN the page flag filter icon will change to grey and unselected
* AND all the panes (left pane, preview pane, and working pane) will be updated according to the selected filters

**Scenario 4: Hover Over Tooltip**
* GIVEN an IAO analyst is in the 'Filter by' section
* WHEN they hover over one of the page flag icons
* THEN a tooltip will be displayed showing the page flag name that related to the icon

**Scenario 5: Select Both Filter By and Organize By**
* GIVEN an IAO analyst has selected one or more page flag filters
* AND has selected an 'Organize by' option
* WHEN they view the left pane
* THEN the records will be organized according the the 'Organize by' option selected
* AND the pages will be filtered by the 'Filter by' criteria

**Scenario 6: Filter By - Page Count**
* GIVEN an IAO analyst has selected one or more page flag filters
* WHEN they view the 'Total Pages' counter
* THEN the counter will show the number of filtered pages compared to the total number of pages 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/981498459

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
@lmullane @JHarrietha-AOT - please review

@JHarrietha-AOT - feel free to add designs to ACs 

cc: @abin-aot

**Comment by JHarrietha-AOT** [comment]
Looks great @KyEggleston I just added the design link so good to send for refinment

**Comment by m-prodan** [comment]
Note from refinement - flag filtering can only apply to the custom left hand panel navigation

**Comment by abin-aot** [comment]
? : Any chance for having multiple flag on a page ? - 1 flag per page
? : Why there is consult outside current ministry ? Curious! EDU ministry can have an email from another ministry , so to clarify
? Preview Click , Context - R&D / tech. spike -ANS :  Right now only with Left Pane
? Do we need Page flag context menu on Page - right , main pane - Not right now.
? What is the broken/incomplete icon ? Do we need a icon if nothing has done on a page? - this is pages with no flags on it.
? Can we Multi-Select pages and apply same Flag? - Yes
? if its a filter by Page Flag, then PDFTRON can't filter by pages , but we can SELECT or highlight on preview - Tech Spike, as of now its not required, due to increase in the effort.

**Comment by sumathi-thirumani-aot** [comment]
@JHarrietha-AOT Is this filter to be applied to at single document or all documents? Can you please clarify

**Comment by JHarrietha-AOT** [comment]
@sumathi-thirumani-aot I believe in refinment we said all documents. @m-prodan am I remembering correctly?

**Comment by aparna-aot** [comment]
As mentioned in the above comment by Abin, we can't display only the filtered pages on Preview & main doc view. So all the documents will be displayed in those 2 places.
Implemented filters in the Left Panel and users can click on those filtered pages to Select/Highlight the pages in preview and main document view.

**Comment by KyEggleston** [comment]
These ACs pass - I did encounter a bug related to using the 'Search' field when also filtering records, but will make bug ticket.
