### ISSUE TITLE
UX Assurance - Changes to UI for Document Tree in PDF Tron

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#3420]
Title of ticket: UX Assurance - Changes to UI for Document Tree in PDF Tron

#### Description
This ticket it to cover all of the UI changes for the custom panel in PDF Tron (Document Tree). In user research sessions we recieved feedback that users found that spacing and sizing to be difficult to navigate and doesn't feel as smooth as the user experience of the rest of PDF Tron

#### Images for Reference
Current UI
![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/ebcf7d43-49c3-4e08-970e-8ef391060aef)

Desired UI
![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/8cfff8e5-1797-44a6-bf2f-d7584582dd2c)
https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/981498459
#### DOD
- [x] Search Bar has padding around and is centered on bar
- [x] font changed to match font in PDF Tron - Lato
- [x] Space update between document name and pages
- [x] Pages text sized decrease
- [x] Remove bottom scrollbar
- [x] Organize by filter UI fix
- [x] Other

**Comment by m-prodan** [comment]
Note: This task should be covered while devs work on the context menu

**Comment by aparna-aot** [comment]
@KyEggleston - This ticket is also ready for QA.
