### ISSUE TITLE
Download linear PDF for Harms

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3421]
* As a ministry coordinator
* I want to download PDF records as one document in divisional batches
* so that I can send records to divisions to assess for harms

**Assumptions & Scope**	
What are the assumptions for this story?

Ministry coordinators need to export PDF records in one consolidated, linear PDF so that they can be easily reviewed by ministry branch staff for potential harms.

IAO analysts can also download the Harms package.

The Records log filters are independent of the download. Applying a filter (e.g.by a divisional, error, etc. tag) on the Records Log will have no impact on what is downloaded.

Only the consolidated PDF(s) should be included in the ZIP file, not the individual PDFs.

These reviews will occur outside the system for the initial releases of the Gathering Records feature.

By default the records exported will only include unique records. Duplicate records will not be included in the export. 

If a record has been converted into a PDF, the export will include the PDF version of the record, not the original.

The ZIP file will also contain all the incompatible file types (i.e. non-PDFs), such as audio and GIS files.

What is IN scope?

What is NOT in scope?
Tagging of records by division is covered in #2779
Export of all file types and removal of duplicates in the ZIP file is covered in #3230
#download of individual records is covered in #3205, #3207
Harms Download Notifications in #3433 
**Acceptance Criteria**	

**Scenario 1: Inactive Download dropdown**
* GIVEN the ministry coordinator is on the Records Log
* WHEN there are no records in the Log
* THEN the Download dropdown will not be shown

**Scenario 2: Active Download dropdown**
* GIVEN the ministry coordinator is on the Records Log
* WHEN there is records in the Log
* THEN the Download dropdown will be shown and active

**Scenario 3: Click active Download dropdown**
* GIVEN the ministry coordinator is on the Records Log
* AND there is records in the Log
* WHEN the coordinator clicks the Download dropdown
* THEN the Download dropdown will open with 3 choices: Download for Harms, Download Redline for Sign Off, Download Final Package

**Scenario 4: Download Harms PDF by with a Division in progress**
* GIVEN the ministry coordinator or IAO analyst is on the Record log
* AND the Download dropdown is open
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423264
* WHEN they click the 'Download for Harms' button
* THEN the download will be in progress
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262
* AND an orange toast will show: "In progress. You will be notified when the records are ready for download."

**Scenario 5: Download Harms PDF by with a Division in progress**
* GIVEN the system complete creating the harms PDFs
* WHEN ministry coordinator clicks "Download Harms PDF" again
* THEN PDF(s) will be exported in one consolidated, linear PDF for each Division organized by modified date
* AND the consolidated PDF(s) for each Division will be include in the ZIP file
* AND no individual PDF(s) will be included in the ZIP file (only PDFs consolidated by Division)
* AND the file name will be with following format: Request ID - Harms - Division (see comments below for eg)
* AND the ZIP file will be downloaded onto the user's computer

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@nkan-aot, this is story captures the change we discussed of the batch export of records into a ZIP file (#3230).

PDF records will be consolidated into one linear PDF organized by modification date. This will make it easier for ministry harms review.

 @JHarrietha-AOT, @m-prodan, please review and comment if you see any changes required.   

cc @abin-aot

**Comment by m-prodan** [comment]
Note - will need to update designs, as this will need to be a background job after upload of records.
AC will need to be re-written as well, we should produce a single linear pdf, per division - and not having just a single linear PDF inclusive of all divisions. This will address Ministry pain points

**Comment by m-prodan** [comment]
Early estimate of 8, but this needs to be discussed and potentially re-estimated at sprint planning based on discussion at refinement

**Comment by divyav-aot** [comment]
@m-prodan - as part of this US, you are expecting one zip file with the requestno right? In the zip file, you will find division wise folders and stitched files in it.
Example file structure for "PSA-2023-123356 - Harms - Deputy Ministers Office.pdf" is "PSA-2023-123356.zip\**DEPUTY MINISTER'S OFFICE**\PSA-2023-123356 - Harms - Deputy Ministers Office.pdf". Please confirm

**Comment by divyav-aot** [comment]
As discussed, below issues are not addressed in this user story. I will take these as separate task.

1. **Qn to business:** what is the expected behavior if the ministry uploads records after "download for harms" is triggered. - As discussed in the standup, business is going to create a new US to cover this scenario.
2. **TechDebt:** The page numbering is not appearing properly for lengthy excels as it is converted not in A4/Letter size. This may include few images.
3. The toast type is info(default color is blue). As per the US, it should be in Orange. The default color for warning toast is Orange/Yellow but it will show the warning symbol. Please confirm if you need the customization to Orange.

**Comment by divyav-aot** [comment]
@m-prodan Also, the download dropdown will not be visible until there is at lease 1 record to download. Please let me know of we can use this validation or keep the scenario 1, 2 and 3.

**Comment by KyEggleston** [comment]
All ACs pass - but will have discussion about notes/questions above before closing.

@divyav-aot - I did notice that adding the 'Download' button may have impacted the CSS, and the buttons being inline with the Request ID header. Regardless of the viewport, they do not show inline. 

![image](https://user-images.githubusercontent.com/117312323/228012698-2029af69-014f-461d-aca6-cbdff8a5f748.png)

Previously it was formatted inline, such as the following:
![image](https://user-images.githubusercontent.com/117312323/228018605-71fffea5-5b82-4b3b-90b8-d0dd1b3d3829.png)

If inline is possible, that would be ideal - if not, It's probably ok having them displayed underneath, but we may just need to increase the margins between the Request ID and the container for the buttons. Thoughts?

**Comment by divyav-aot** [comment]
@KyEggleston I can try to squeeze all the buttons inline. But, if any new button comes, we may have to relook the design. May be it is better show all the buttons down. I can add the margins as requested.

**Comment by KyEggleston** [comment]
@divyav-aot - Maybe for now lets just keep it is (showing the buttons below), and simply increase the margin, as that probably easier and will accommodate if any additional buttons or changes occur. 

We will chat more about it on the business side, but we can go with this for now.

**Comment by KyEggleston** [comment]
Confirmed blue toast is fine (rather than orange). 

Moving buttons to be below Request ID was done to accommodate viewport changes (As inline would cause UI issues), so this is ok. 

 "Download dropdown will not be visible until there is at lease 1 record to download" - confirmed ok. 

Closing ticket.
