### ISSUE TITLE
Flex Team - Personal Request Assignments

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3424]
* As an IAO analyst
* I want to be able to assign personal requests to the flex team
* so that they can assist with call for records activities

**Assumptions & Scope**	
This story is a precursor to the eventual re-alignment of IAO, and will also help a team in the interim.

Flex team will manage the call for records for personal requests for all Ministry requests after the IAO re-alignment, and in the interim will start managing PSA personal CFRs, so we want them to be able to be assigned to those kinds of requests.

What is IN scope?
Assignment, and watching assignments
Adjustment to sort order

What is NOT in scope?

Auto assignments will NOT be covered. We will address this in a separate user story.
No changes to how assignments are actually completed - this is just a change to who can be assigned to a request.

**Acceptance Criteria**	

**Scenario 1: Primary Assignment - Flex Team**
* GIVEN a user is on a personal FOI request
* AND the request is in any state from Open
* WHEN a user clicks on the primary assignment
* THEN the user will see the current IAO teams and that can be assigned to the request, as well as the Flex team and its users

**Scenario 2: Watching - Flex Team**
* GIVEN a user is on a personal FOI request
* AND the request is in any state from Open
* WHEN a user clicks on the Watching assignment
* THEN the user will see the current IAO teams and that can be assigned to the request, as well as the Flex team and its users

**Scenario 3 - Assignment Options, Sort Order**
* GIVEN a user is on a GENERAL or PERSONAL request
* WHEN they activate the Assignment, or Watcher dropdown lists
* THEN the order of users will be descending alphabetical (A-Z)

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@abin-aot - this is the user story I wrote up for the ticket you looked at for me, hoping we can get this in the next sprint.

I also added another AC around sort order in general for both request types - as it was something I was observing. Let me know if thats too much - I was wanting this to be a smaller task, but wasn't sure if this addition pushes that a bit more. Can discuss more at sprint planning.

cc: @lmullane

**Comment by m-prodan** [comment]
@sumathi-thirumani-aot - I have started the QA - most things are working as expected, but I have found one issue.

When I create a new personal request, and open it - it auto-assigns to the flex team. We will eventually need this - but not for this release, as flex team won't be handling all call for records. Can you fix this? Old auto-assignment rules should still be in place.

**Comment by m-prodan** [comment]
Hi @sumathi-thirumani-aot - as discussed at stand up, when I opened personal request COR-2023-30000 - instead of auto-assigning to Justice Heatlh, it auto assigned to Flex team.

I also observed same behaviour with  LBR-2023-012356 - it was a personal request, that should have been auto-assigned to the Central team, but was auto-assigned to Flex team instead.

**Comment by sumathi-thirumani-aot** [comment]
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/10f117b1-75e7-4073-a691-ca46ad79107b)

**Comment by m-prodan** [comment]
Nice work @sumathi-thirumani-aot - note that BRD does not require assignments, it is a redundant code now (is now CAS).

QA passed
