### ISSUE TITLE
Use for Vault for OpenShift secrets

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3425]
Title of ticket: 

#### Description
All OCP Project Namespaces, we need to transfer 'SECRETS' to OC Hashcorp Vaults. 

#### Dependencies
Are there any dependencies?  COnfirm the Emerald Vault support.

#### DOD
- [x] FOI Reporting - DEV, TEST
- [x]  FOI Reporting - PROD
- [x] FOI DOC Reviewer - DEV, TEST 
- [x] FOI Request Submission - Angular App - DEV, TEST
- [x] FOi REQUEST PROD
- [x]  FOI  FLOW - DEV -marshal ,  TEST-MARSHAL ,
- [x] FOI  FLOW - DEV, TEST , STAGING 
- [ ] FOI FLOW PROD
- [ ]  Emerald - ???
- [x] Integration testing on all apps

**Comment by lmullane** [comment]
As discussed @abin-aot , this is a security requirement. 

Please fill out the DOD and provide an estimate.

**Comment by lmullane** [comment]
Vault is not enabled for Emerald, so will put Vault in for Silver cluster for now.

**Comment by abin-aot** [comment]
![unknown_007.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/2373fa19-45de-4af1-8755-c475f2e3c1a4)
