### ISSUE TITLE
Configure ADMIN events on Keycloak

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3430]
Title of ticket: 

#### Description
Security requirement to configure events to be captured in KeyCloak logs (successful and unsuccessful logins).

Assumptions : At this moment, we dont need to log Authorization issues cc: @lmullane 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Configure KC Admin events
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by lmullane** [comment]
As discussed, please put in a DOD that includes configuring KeyCloak to log all useful events from a security perspective.

**Comment by aparna-aot** [comment]
In Keycloak, configured to save both Admin Events and Login Events in DEV & TEST.

- All data related to login will be logged in the Login events tab in the Events Section.
- All data related to Admin activities like changing realm settings, updating users, updating roles, clients etc. 
will be logged in the Admin events tab in Events section.

- We can filter the events by date, event type, resource type & authentication details.
- We can also set the expiry of **login events** and once the expiration time is reached all the login events will be cleared off.
    - In DEV Expiration for Login Events is set to be 1 hr.
    - In TEST Expiration for Login Events is set to be 2 hrs.
- In both DEV & TEST , the event type CLIENT_LOGIN is excluded from logging as there are multiple repetitive logs  
for the client- forms-flow-bpm by the service account(service-account-forms-flow-bpm).
PROD:
We haven’t setup the events yet in PROD. We need to discuss the expiration time with Nick Corcoran. 
@abin-aot  had already send an email and once we hear back from Nick, we can set up the events & expiry accordingly.

**Comment by aparna-aot** [comment]
@abin-aot  @m-prodan As per discussion during standup on 2023-03-10 , Admin events and login events are set up on PROD with an **Expiration  : 14 days**.
Until we hear back from Nick Corcoran, we will be keeping the expiration time to 14 days.
