### ISSUE TITLE
Remove Upload Requirement for Select State Transitions 

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3436]
Title of ticket: 

#### Description
Issue found regarding a file upload being pushed on users when moving from two different states:

Ministry Sign-Off to Review
Response to Review

Both cases shouldn't require an upload

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Remove document upload when transitioning from Ministry Sign-Off to Review
- [ ] Remove document upload when transitioning from Response to Review

**Comment by lmullane** [comment]
@m-prodan, confirm if this is already complete?

**Comment by KyEggleston** [comment]
This is resolved, and a file upload is not required to change state (optional)
