### ISSUE TITLE
Integration between FOI FLOW, FOI Doc reviewer - SSO

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3446]
Title of ticket: 

#### Description
The purpose of this task is to bring in SSO between FOI FLOW and FOI Doc reviewer app, and seamlessly switch over to the corresponding FOI Request. 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ]  Enable/Configure SSO between FOI Flow and FOI DocReviewer app - related KC configs
- [ ] Security Validation on FOI Document Reviewer App - if somebody update URL manually or else 
      RESTRICTED Request in particular - 
- [ ] Remove Hard coded Request #
- [ ] 
- [ ]

#### Pre-deployment
- add the following env variables in reviewer api: FOI_REQ_MANAGEMENT_API_URL, FOI_REQ_MANAGEMENT_API_TIMEOUT

**Comment by KyEggleston** [comment]
Confirmed unable to access restricted requests on IAO side or Ministry side when the request is restricted on your side, and you are not the Assignee or a Watcher.
