### ISSUE TITLE
Remaining File Types for Gathering Records Log

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3465]
Title of ticket: Remaining File Types for Gathering Records Log

#### Description

The Records Log and Object Storage will replace the current Shared LAN which stores all file types that are responsive to an FOI request.

To replace the LAN we need to support the upload of all file types into Object Storage and to have these file types accessible from the Records Log.

Currently, there are numerous file types that can not be uploaded to the Gathering Records log (i.e., Records tab). 

Duplicates will be removed with rank 1 (by the metadata hash).

Some of these file types must be supported for upload and file conversion/dedupe before a ministry is onboarded. For example, GIS and geospatial related files, such as .shx, .shp and .dbf, must be supported prior to onboarding resource teams (two of which are planned for April). 

We will need to decide which file types must be supported, and when (i.e., if a ministry requires it). 

Here is a non-exhaustive list of file types that are not supported in FOI Mod (at the moment):

**GIS/Geospatial**
.shx – I believe shapefiles always require a .shx, .shp and .dbf file
.shp -  I believe shapefiles always require a .shx, .shp and .dbf file
.dbf - I believe shapefiles always require a .shx, .shp and .dbf file
.kml/.kmz - 
.GEOJSON / .JSON 
.cpg
.prj
.sbn
.sbx
.gml
.GDB
.FREELIST
.ATX
.gpkg
.MBTILES
.MPK
.WKT

**LiDAR files**
.LAS/.LASD/.LAZ 

**CAD files** 
.DWF/DWG./DXF 

**Email**
.eml - Already have ticket for this (#3071)

**Text Files**
.csv - converted to PDF depending upon size
.txt - converted to PDF

**Image**
.png - can be uploaded, AND is compatible to be viewed in PDFTron
.jpg - can be uploaded, AND is compatible to be viewed in PDFTron

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by KyEggleston** [comment]
@m-prodan @lmullane @liseandtea - here is the task for the file types that are not supported in FOI Mod. With two resource teams being brought on soon, we may need to plan for some of their more sector-specific file types to be accepted and able to be uploaded to the Gathering Records log and run through dedupe/conversion.

**Comment by lmullane** [comment]
Decision is not to convert CSV files. Instead Flex team can convert CSVs by uploading them into Excel and converting to an xls, then uploading the xls file.

**Comment by abin-aot** [comment]
https://test-marshal-foirequest.apps.silver.devops.gov.bc.ca/foi/foirequests/300/ministryrequest/300 - for review!

**Comment by KyEggleston** [comment]
Looks good, tested some CAD and LiDAR as well, and they can be upload as incomp.

Note, we still need to make tickets for the following:

.txt - convert to PDF
.png - convert to PDF
.jpg - convert to PDF

@abin-aot - one ticket or a separate ticket for each file type?
