### ISSUE TITLE
Document stitching - Foundation task

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3469]
Title of ticket: 

#### Description
This is a technical task to stitch the documents divisional wise. This is a ground work for #3421. The producer will send the file names and the consumer will stitch the files together based on the division.
There will be separate technical task created for #3301 and #3302. This will concentrate blob stitching.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Create a test producer logic to send the message with a multiarray containing the divisions and corresponding files
- [x] Create a consumer service to read the message
- [x] Make the consumer service to read from last message
- [x] Read file from S3
- [x] Merge multiple pdfs and save the stitched document to S3
- [x] Multithreaded service to stitch the documents division wise
- [x] Add the newly created service to the foi-docreviewer
- [x] Update the docker-compose.yml to run the service locally
- [x] Merge zipping logic to the pdfstitch service
- [x] add page numbers to the stitched document
- [x] try stitching .png and .jpg files

**Comment by JHarrietha-AOT** [comment]
Design for page number placement

[https://app.zenhub.com/files/358004325/8aa8c669-93cc-4b56-8ad9-4b9b64490f0b/download](https://app.zenhub.com/files/358004325/8aa8c669-93cc-4b56-8ad9-4b9b64490f0b/download)

**Comment by divyav-aot** [comment]
Sample stitched PDF with page number. We can discuss on the filename along with #3421
[Uploading... EDU-2023-03070212div1.pdf]
