### ISSUE TITLE
Zip the document and save to S3 - Foundation Task

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3470]
Title of ticket: 

#### Description
This is a technical task to save the stitched files to s3. This is a ground work for #3421, #3301 and #3302

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Create a zip file for stitched divisional documents including the incompatible files
- [ ] Create a zip file for final applicant package including the incompatible files
- [ ] Save the zip files to S3

**Comment by nkan-aot** [comment]
3/14/2023 standup - code is merged task closed
