### ISSUE TITLE
Strapi Prod not saving paragraph breaks

### ISSUE THREAD

**Issue by katrinaferacini** [bcgov/foi-flow#3473]
**Describe the bug in current situation**
Published Help Article descriptions are not recognizing paragraph breaks, they are being published as one block of text despite being formatted with paragraph breaks in FOI Help backend. 

See first screen shot for text that was properly formatted before being edited. The second screen shot shows text that has not properly formatted after editing. The 3rd screen shot demonstrates the Strapi Dashboard preview showing text has been formatted with paragraph breaks.

**Impact of this bug**
Text is hard to read and inaccessible. Impacts all FOI Help website users (help.foirequests.gov.bc.ca/help-articles)

**Chance of Occurring (high/medium/low/very low)**
Is occurring for two video descriptions I have updated: Fees Training October 2022, and FOI Mod Overview with Trans January 2023

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Strapi backend, Strapi prod. 

**Steps to Reproduce**
1. Go to help.foirequests.gov.bc.ca/help-articles 
2. Click on Fees Training October 2022
3. Scroll down to video description
4. See error: block of text

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
![Previous state with paragraph breaks.PNG](https://images.zenhubusercontent.com/633318928b7f4e47a5d154ec/b59f19d8-042f-4b74-930a-1d19704497b9)![Current state with no paragraph breaks.PNG](https://images.zenhubusercontent.com/633318928b7f4e47a5d154ec/8adcb480-256c-4fe3-a5b7-0f03b218b1df)![Strapi dashboard Preview Mode.PNG](https://images.zenhubusercontent.com/633318928b7f4e47a5d154ec/097ebf6a-fe13-498d-b69e-4a442b069732)![Ideal view previewed via Developer Tool.PNG](https://images.zenhubusercontent.com/633318928b7f4e47a5d154ec/65d9c1aa-4013-44b6-a876-bd0884300fdc)

**Comment by KyEggleston** [comment]
@lmullane @m-prodan - just a note to look into bringing this in next sprint for Katrina (discuss at sprint planning tomorrow)

**Comment by KyEggleston** [comment]
Resolved this for Katrina - will show when Katrina back 
cc: @katrinaferacini @m-prodan @liseandtea
