### ISSUE TITLE
Attachment Log - Attachments unavailable/not working

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3483]
**Describe the bug in current situation**
Reported by users that attachments on certain requests were broken/not working.

Examples: 
PSA-2023-30612
PSE-2023-30322

**Link bug to the User Story**

**Impact of this bug**
Note: difficult to reproduce - some examples from PROD are listed above, but at least the PSA one have been resolved by the coordinate who reuploaded the impacted documents.

For PSE-2023-30322 - the impacted file is the one uploaded as part of the CFR > Review status change. It is still bugged in production. 

For PSA-2023-30612 - it was observed that the docx files were throwing the error. The coordinator had since replaced them and the issue was resolved

**Chance of Occurring (high/medium/low/very low)**
**UNCLEAR** - this issue seems to occur sporadically, either as part of a document upload state change, or when uploading forms in bulk

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
@nkan-aot @richard-aot - as discussed from stand up. Again - unclear how to replicate, some impacted files noted above with context added

**Comment by KyEggleston** [comment]
@nick-aot 

Note: when moving a request from Response -> On Hold, when you add attachments to the state change modal, these attachments **are not** added to the Attachments tab. See EDU-2023-99993 in Test. 

These two attachments were added to the state change modal (and sent to the applicant), but were not added to the Attachments tab:

![image](https://user-images.githubusercontent.com/117312323/226018159-658101bb-af1c-4625-97f4-ff6d1de823f5.png)

![image](https://user-images.githubusercontent.com/117312323/226018397-642303cf-ee7b-4e26-8dd5-b6001dc78906.png)

Didn't notice any issue on any of the other file upload/attachment scenarios. 

cc: @m-prodan

**Comment by nkan-aot** [comment]
@KyEggleston I believe any attachments shown in the contact applicant log will not be shown in attachment logs in order to not clutter. Logically any attachments in the attachment log are for iao and ministry to communicate with each other. As long as you can view and download the attachments in the applicant log, they have been uploaded properly

**Comment by KyEggleston** [comment]
@nkan-aot - when sending the initial fee estimate email to the applicant (Fee Estimate -> On Hold), the attachments uploaded to the state change modal (and are sent to the applicant) are added to the Attachments tab. This isn't happening for Response -> On Hold, where the attachments are also sent to the applicant. So it seems it's kind of a mixed bag. But otherwise, no issues uploading attachments. 

![image](https://user-images.githubusercontent.com/117312323/226049254-ec64866f-0f8d-4ac3-b013-4ab663b32731.png)

![image](https://user-images.githubusercontent.com/117312323/226049600-077d2d4f-7955-424e-8e65-06fd8216b830.png)

**Comment by nkan-aot** [comment]
just tested in dev-marshal and the behaviour is the same. Anyways I did not change any logic regarding which attachments are sent to attachment log and which are sent to contact applicant log, only the behind the scenes method of uploading them to s3. the end result should be that file uploads work exactly the same as they used to. If we want to add the response -> on hold documents to the attachment log or take out the fee estimate -> on hold documents, i suggest creating a new ticket

**Comment by KyEggleston** [comment]
I'll close this, and we can discuss the Response -> on hold outside the ticket @m-prodan @liseandtea

**Comment by KyEggleston** [comment]
@nkan-aot - sorry to reopen this, but this may be related to this ticket. 

I think I get what was happening on PSE-2023-30322 and can replicate. 

The ministry first uploaded their completed CFR Form directly to the Attachments tab (e.g., with the name "Call For Records.pdf".

However, afterwards they changed the request state from Call for Records -> Records Review, and uploaded that same file ("Call for Records.pdf") to the state change modal as an attachment. If a duplicate attachment is attempted to be added to the Attachments tab directly, the user receives an error, and is unable to upload the file. 

![image](https://user-images.githubusercontent.com/117312323/226058998-568e1a49-6723-45b8-8d9b-2a509ef3d12d.png)

However, when uploading attachments via a state change modal, duplicate attachments are not prevented (i.e.., no error such as the above is thrown). Instead, the file name is appended with a number, which is what happened on this request.

![image](https://user-images.githubusercontent.com/117312323/226059263-8e3fb74f-13a5-42ed-8337-68b480da963b.png)

The appended file is then uploaded to the Attachments tab, but when trying to view it, they receive an error:

![image](https://user-images.githubusercontent.com/117312323/226059586-8985fa4d-cce4-4a14-be67-46dc9777755b.png)

Here is an image of the attachments on PSE-2023-30322, with the appended file "G - Call for Records form - 30322(1).docx", which is the appended file name, is throwing an error when trying to view it through the Attachments tab -> ellipsis (...) -> View. 

![image](https://user-images.githubusercontent.com/117312323/226059952-a9e8c6f8-7ec6-4a9c-b246-b9542c5a4bcb.png)

I'm not sure if any action can be taken on this right now, but this may be the issue.

**Comment by KyEggleston** [comment]
You rock - thanks Nick!

**Comment by KyEggleston** [comment]
Confirmed fix - closing this ticket
