### ISSUE TITLE
Auto-flag Withheld in Full

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3487]
* As an IAO analyst
* I want a page to be automatically flagged as 'Withheld in Full' when I redact an entire page
* so that I can save time when redacting a package

**Assumptions & Scope**	
What are the assumptions for this story?

In AXIS when an analyst redacts an entire page, the 'Withheld in Full' flag is automatically added to the page.

In FOI Mod, when an analyst does the following, the 'Withheld in Full' flag will be automatically added:

- Selects a page number(s) using the redact by page number feature
- Right clicks on a page in the left hand viewer, and selected withheld in full flag

ACs 3 and 4 are only for one page at a time.

What is IN scope?

Disable the manual selection of the 'Withheld in Full' flag.

Auto flag 'Withheld in Full' when a full page is redacted.

What is NOT in scope?

Redacting a full page when a 'Withheld in Full' flag is applied to a page.

**Acceptance Criteria**	

**Scenario 1: Automatically add 'Withheld in Full' flag when analyst redacts an entire page by page number**
* GIVEN an IAO analyst is on the redact by page number modal
* WHEN the analyst redacts by page number(s)
* THEN the 'Withheld in Full' page flag will automatically be added to the page(s)
* AND the 'Withheld in Full' icon will be displayed beside the page(s) in the 'Organize By' pane

**Scenario 2: Automatically remove 'Withheld in Full' flag when analyst removes full redactions from a page**
* GIVEN an IAO analyst is on a page that is withheld in full, and has a full page redaction
* WHEN the analyst removes the full page redaction
* THEN the 'Withheld in Full' page flag will automatically be removed from the page
* AND the 'Withheld in Full' icon will no longer be displayed beside the page(s) in the 'Organize By' pane

**Scenario 3: Click on 'Withheld in Full' flag in left panel**
* GIVEN an IAO analyst in the Records Review
* WHEN the analyst clicks the 'Withheld in Full' page flag in the Organize by pane next to a page
* THEN the FOIPPA modal with sections will open 

**Scenario 4: Save FOIPPA section**
* GIVEN an IAO analyst is on the FOIPPA modal
* WHEN the analyst saves sections of the Act to apply
* THEN the FOIPPA modal close
* AND the 'Withheld in Full' icon will be displayed beside the page in the 'Organize By' pane
* AND the entire page will be redlined redaction

**Scenario 5: Manually Change Flag - Full Page Redaction**
* GIVEN an IAO analyst has applied a full page redaction
* AND the application has auto-flagged the page as withheld in full
* WHEN the IAO user has activated the page flag menu, when right-clicking on the page
* THEN the user will be able to manually change the flag to any other flag
* AND the full page redaction will persist

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team?s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, @JHarrietha-AOT

Please review the AC by end of day tomorrow and make any changes necessary.

Note, AC 5 to ensure that information is accurately redacted.

**Comment by m-prodan** [comment]
looks good to me

**Comment by m-prodan** [comment]
Updated AC's and revised assumptions and scope as per stand up this mroning

cc @aparna-aot

**Comment by KyEggleston** [comment]
@aparna-aot - These ACs pass.

The only small update, just to align with other redactions, is to change the default fill colour from black to white when applying a full page redaction. 

Currently black fill:
![image](https://user-images.githubusercontent.com/117312323/229546476-176ed968-08d5-466c-8976-b270e727ffce.png)

Other redactions are white:
![image](https://user-images.githubusercontent.com/117312323/229546679-002e40a9-7e6d-472f-8a69-172bd488d9df.png)

**Comment by aparna-aot** [comment]
@KyEggleston Sure. Will check and fix that soon. Thank you!

**Comment by KyEggleston** [comment]
Closing ticket, as all ACs pass - issue above regarding black fill in redaction box will be handled in a new bug ticket.
