### ISSUE TITLE
FOIPPA modal for redline by page number(s)

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3488]
* As an IAO analyst
* I want the FOIPPA modal to open when  I select by page number(s) for redlines
* so that I can ensure I have applied the section stamps to the redlined pages

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: FOIPPA Modal opens when analyst when analyst redacts an entire page by page number**
* GIVEN an IAO analyst is on the redact by page number modal
* WHEN the analyst selects a page number(s)
* THEN the FOIPPA modal will open to select the sections of the Act to apply for each  page to be redacted page(s)

**Scenario 1: FOIPPA Modal opens when analyst when analyst redlines an entire page by page number**
* GIVEN an IAO analyst is on the redact by page number modal
* AND has selected page number(s) for each page to be redlined
* AND the FOIPPA modal is open
* WHEN the analyst has selected section(s) of the Act for each page
* THEN redlines can be saved

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
This can be closed as complete, but @KyEggleston will add AC to QA Master List.

**Comment by KyEggleston** [comment]
@lmullane @liseandtea @m-prodan - These ACs pass, but note the following:

We should look into removing the 'Redact' button under the redact pages modal, as it has a similar function as the 'Redact All' functionality noted in #3506 (which we want to remove). 

![image](https://user-images.githubusercontent.com/117312323/226471469-92b84d56-4bb6-45ff-aadc-b88716a87177.png)

'Add Mark' applies a redaction the same way we currently do using the redaction tool, whereas the 'Redact' button irrevocably applies the redaction to the page, leaving it permanently black.

![image](https://user-images.githubusercontent.com/117312323/226471182-fedf456f-7531-41fb-aba1-0735d5ba8a66.png)

We should perhaps rename 'Add Mark' to read "Redact", and remove the 'Redact' button, which would look like this:

![image](https://user-images.githubusercontent.com/117312323/226472291-4fe16d1a-7ff0-49b1-8571-a0d09dd83a97.png)
