### ISSUE TITLE
CFR Form Update 

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3490]
Title of ticket: 
Need to make an update to CFR forms 

Have to update the field from Estimated number of  pages to estimated number of files. 

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/b4233509-df47-4145-b762-8fc0cde94478)

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Update: "Electronic Estimated Pages" to "Electronic Estimated Files"
- [ ]  Update in the value box, for Electronic Estimated Files: pg(s) to files
- [ ] Update Electronic Actual Pages to: Electronic Actual Files
- [ ]  Update in the value box for Electronic Actual Files: pg(s) to files

**Comment by m-prodan** [comment]
cc @JHarrietha-AOT - may need a quick design update on this

**Comment by KyEggleston** [comment]
Duplicate of #3534 - closing
