### ISSUE TITLE
Accessibility Critical Errors - PDF Tron

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#3496]
Title of ticket: Accessibility Critical Errors - PDF Tron

#### Description
This ticket is for the two Critical Accessibility Errors that have been identified in running accessibility tests on PDF Tron. These were run in multiple different testing services. I have included links to one that whichever dev is working on the task can easily download (https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd/related?hl=en-US&utm_term=wcag%20chrome%20extension&utm_campaign=Search%20-%20axe%20DevTools%20-%20Checker&utm_source=adwords&utm_medium=ppc&hsa_src=g&hsa_ad=552272061986&hsa_tgt=kwd-1005431164531&hsa_mt=e&hsa_ver=3&hsa_acc=7854167720&hsa_kw=wcag%20chrome%20extension&hsa_grp=135123751424&hsa_cam=14920961979&hsa_net=adwords&gclid=Cj0KCQiAx6ugBhCcARIsAGNmMbj_Ja2izfAnwa1sa2jxBLEjSEA92PhPLsUyh5q9mxXmV-foVIaHEAEaAsbFEALw_wcB)

#### Dependencies

![Screen Shot 2023-03-10 at 2.24.46 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/21c2bcd2-850f-444f-924b-80817c43a646)

![Screen Shot 2023-03-10 at 2.29.30 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/8156af61-7445-49b5-a92b-49f48723625a)

#### DOD
- [x] Fix for 'Buttons must have discernible text' - Search Icon
- [ ] Fix Form elements must have labels - Size bar in Thumbnail Panel
- [ ] 
- [ ] 
- [ ]

**Comment by m-prodan** [comment]
Unclear if second item can be addressed due to it being a core part of PDFTron

**Comment by JHarrietha-AOT** [comment]
Item 1 listed above have been fixed. Assuming Matt comments means item two was unable to be fixed. Closing ticket
