### ISSUE TITLE
Login to request to que

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#35]
As an intake analyst, I want to authenticate and login with IDIR, so that I can securely access FOI requests submitted

**Acceptance Criteria**	

**Scenario 1: Login**
* GIVEN the intake analyst is on the homepage 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932449
* WHEN the analyst clicks the 'Login' button
* THEN the analyst will be directed to the Keycloak IDIR login page:
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932450

**Scenario 2: Enter valid credentials**
* GIVEN the intake analyst is on the Keycloak login page:
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932450
* AND the analyst enters a valid IDIR email address and password
* WHEN the analyst clicks 'Continue'
* THEN the analyst will be logged into the application 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451

**Scenario 3: Sign out**
* GIVEN the intake analyst is on any page in the application 
* WHEN the analyst clicks 'Sign Out' in the header
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932451
* THEN the analyst will be logged out of the application 
*AND the analyst will be directed to the homepage
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/657932449

**Dependencies? 

Realm setup which is now complete.
#110

**Validation Rules? (If yes, list here)**	

**Design**
See designs in AC

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [x] Passes developer unit tests
2.    [x] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
As discussed in refinement, need to integrate with Forms Flow.

This Keycloak page comes from the Lab and we do not need to develop it or do exceptions: https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957812

**Comment by mpilchar** [comment]
Code merged and was reviewed along with homepage

**Comment by mpilchar** [comment]
Issues with test region. @acoard-aot is investigating and will update

**Comment by m-prodan** [comment]
I'm able to log in and see the queue, but found an issue when trying to sign out - the following error message displays:

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Client</faultcode><faultstring>SOAP Processing Error. Exception processing request</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

**Comment by JHarrietha-AOT** [comment]
@m-prodan Was happening for me too, just had a quick chat with @abin-aot seems like it is a quick fix. I will add a bug so we can solve it tomorrow and make sure it isn't an issue going forward.
