### ISSUE TITLE
IAO Assignment Function Update - IAO Re-alignment

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3500]
* As an IAO user
* I want to be able to assign any request, general or personal, to any other team/individual that is an IAO user
* so that I can manage requests that are assigned across teams

Assumptions and Scope:
With the upcoming IAO reorganization, we will require greater flexibility in assigning requests. During the transition period, there will be files being passed across teams, or remain with analysts where the mappings currently do not site.

To address this, and any future changes, we need to make it such that any request can be assigned to any IAO user, regardless of the team they belong to. 

There is also a new team, called the Coordinated Response Unit - which may assist other teams with requests when they need support. As such, there is a need for flexibility compared to how we currently manage assignments.

What is IN scope?
Updating who requests can be assigned to

What is NOT in scope?
Sort order of names should remain the same, with the exception of the position of the Ministry that is mapped to the team
Restricted requests will continue to have the same restrictions applied to them
Intake in Progress requests will continue to be managed by the Intake team
How assignments/watchers are added will not be changed 

**Acceptance Criteria**	

**Scenario 1: General FOI Request in Open State - Primary Assignment**
* GIVEN an IAO user is on a general request in any state from the Open state onwards
* WHEN they activate the assignment dropdown
* THEN they will be able to see all IAO teams and users in the list
* AND the team that is "mapped" to the Ministry code will appear at the top of the list

**Scenario 2: Personal FOI Request in Open State - Primary Assignment**
* GIVEN an IAO user is on a peneral request in any state from the Open state onwards
* WHEN they activate the assignment dropdown
* THEN they will be able to see all IAO teams and users in the list
* AND the team that is "mapped" to the Ministry code will appear at the top of the list

**Scenario 3: General FOI Request in Open State - Watcher**
* GIVEN an IAO user is on a general request in any state from the Open state onwards
* WHEN they activate the watcher dropdown
* THEN they will be able to see all IAO teams and users in the list
* AND the team that is "mapped" to the Ministry code will appear at the top of the list

**Scenario 4: Personal FOI Request in Open State - Watcher**
* GIVEN an IAO user is on a peneral request in any state from the Open state onwards
* WHEN they activate the watcher dropdown
* THEN they will be able to see all IAO teams and users in the list
* AND the team that is "mapped" to the Ministry code will appear at the top of the list

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
#3499

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Note to devs/team: if doing both 3499 and 3500 is going to be a lot of work, we could just do this one as a priority and I could modify the AC to remove the sort feature until after we do the remapping

**Comment by m-prodan** [comment]
Also discussed - @richard-aot will join Nick on this task after his bug ticket completes

**Comment by liseandtea** [comment]
All working as it should. closing ticket!
