### ISSUE TITLE
ETL Production Issue - Division Stages FACT tables

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3501]
**Describe the bug in current situation**
```
JOB RUN:        'FOIETL- JOBS' was run on 3/11/2023 at 7:30:00 PM
DURATION:       1 hours, 10 minutes, 22 seconds
STATUS:         Failed
MESSAGES:       The job failed.  The Job was invoked by Schedule 11 (FOI ETL Nightly Load).  The last step to run was step 36 (factrequestdivstages).
```

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
upgrading this ticket to high priority, this appears to be impacting prod

cc @lmullane @richard-aot

**Comment by KyEggleston** [comment]
Looks like the divisions are now being pulled for the 'Division' query/filter, resolving ticket.
