### ISSUE TITLE
Update/Add Divisions - PSE

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3502]
Title of ticket: 

#### Description
PSE needs an update to their divisions

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Add as a division selection: Corporate Planning & Projects - Director
- [ ]  Add as a division selection: Final Sign-Off

**Comment by m-prodan** [comment]
@nkan-aot - as discussed, you can pick this up when you are free. Feel free to slap an estimate on it - I will pin it to a different release with some other tickets that we probably end up bringing in this sprint

**Comment by KyEggleston** [comment]
@m-prodan - just sending a reminder for a release to be added to this ticket (as it sounds like you may make a new release label). But otherwise, this is done.
