### ISSUE TITLE
Lock FOIPPA modal by section numbers

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3505]
* As an IAO analyst
* I want to lock the FOIPPA modal by section numbers from lowest to highest
* so that the modal does not constantly update based on the section used most often.

**Assumptions & Scope**	
What are the assumptions for this story?

For each request, the FOIPPA modal automatically updates to display the most often selected sections of the Act at the top of the modal.

Analysts have communicated that they would like the option of the FOIPPA modal displaying sections in numerical order; the order will be from smallest section number to highest section number.

Even if the analyst has chosen to list numerically, the most used sections should be calculated in the back end so if they change to Most Used it is up-to-date with their most used sections of the Act.

Analysts want to sort by ascending and descending sections of the Act.

What is IN scope?

A radio button to lock the FOIPPA modal display by number.

Sorting the sections when listed numerically by descending or ascending order.

What is NOT in scope?
Other FOIPPA modal functions are captured in #3313

**Acceptance Criteria**	

**Scenario 1: Slider for Most Used or Numbered Order**
* GIVEN an analyst is doing a redaction on a request
* WHEN the FOIPPA modal opens
* THEN there will be a slider with 2 options: 'Most Used' and 'Numbered Order'
* AND 'Most Used' will be the default for the request

**Scenario 2: Click Number Order**
* GIVEN an analyst is on the FOIPPA modal 
* AND 'Most Used' is selected
* WHEN the analyst clicks Numbered Order
* THEN the modal will be reordered numerically from lowest section number to highest section number
* AND 'Number Order' will now be the default for the request

**Scenario 3: Sort by Descending Number Order**
* GIVEN an analyst is on the FOIPPA modal 
* AND 'Number Order' is selected
* AND the sections of the Act are listed by lowest to highest sections for the Act
* WHEN the analyst clicks the down arrow to the left of the sections list
* THEN the modal will be reordered numerically by highest section number to lowest section of the Act
* AND 'Number Order' will remain the default for the request

**Scenario 4: Sort by Ascending Number Order**
* GIVEN an analyst is on the FOIPPA modal 
* AND 'Number Order' is selected
* AND the sections of the Act are listed by highest section number to lowest section of the Act 
* WHEN the analyst clicks the down arrow to the left of the sections list
* THEN the modal will be reordered numerically by lowest to highest sections for the Act
* AND 'Number Order' will remain the default for the request

**Scenario 5: Click 'Most Used'**
* GIVEN an analyst is on the FOIPPA modal 
* AND 'Number Order' is selected
* WHEN the analyst clicks 'Most Used'
* THEN the modal will be reordered with most used in this request sections of the Act at the top
* AND 'Most Used' will now be the default for the request
* AND the Modal will be ordered with most used sections of the Act at the top (calculation includes the most recent sections of the Act applied when the modal was filtered by Number Order)

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/970284602

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, could you have a look at this story by end of the day? 

I'd like to get this to the developers for review by tomorrow morning

**Comment by m-prodan** [comment]
@nkan-aot - as discussed at stand up, will pick this next. Is on slate for refinement today, will give estimate of 8

**Comment by nkan-aot** [comment]
notes for QA: 
I could not find a material ui element exactly matching the design so I chose the closest thing
![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/0d8ff889-783e-4e0a-80db-ae691383b0bb)
@JHarrietha-AOT also the sort by number descending and ascending was added after the design so I just added where I thought it would fit best, let me know if you want anything changed

**Comment by KyEggleston** [comment]
All ACs pass, no issues - closing ticket.
