### ISSUE TITLE
PDF Tron - Remove 'Redact all' button

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3506]
Title of ticket: 

#### Description
Discovered during demo that you can click redact all, and it will apply redactions to pages while in the reviewer, and it is not reversible. 

Note: are there any other pathways to analysts triggering the 'redact all' feature?

See ticket #3488 (closed) - Kyle's comment has an observation that shows another way a page can be irreversibly redacted

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Remove Redact All Button
- [ ] Remove other pathways in app to redact all
- [ ] 
- [ ] 
- [ ]

**Comment by nkan-aot** [comment]
5/12/2023 standup - redact button in full page redaction modal is disabled through pdftron config, but redact all button in right panel is disabled with a workaround (directly changing pdftron files) If pdftron version is upgraded, need to apply fix again. need to decide as a team how often we are upgrading and/or if we need to make a feature request to pdftron to make that button officially configurable

**Comment by KyEggleston** [comment]
NOTE: another way to apply permanent redaction in redaction app - the 'Apply' checkmark icon/feature in toolbar - this is available when clicking on a redaction box/highlight.  

![image](https://github.com/bcgov/foi-flow/assets/117312323/83c54606-96a2-4ac1-bacb-fe0d2fffae41)

**Comment by KyEggleston** [comment]
Confirmed permanent redact functions in redaction app (three total, included out of box) have been removed. These will be replaced by the ability to create layers/packages which apply redactions.
