### ISSUE TITLE
UX Design Updates

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#3510]
Title of ticket: UX Design Updates

#### Description
General design updates requested at demo

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Lock in ascending order in FOIPPA Module
- [ ] Document status report - what is the best way to address this issue ( provide more streamlined way for Ministry Reviews to know what pages to focus on based on sections. - what pages are withheld in full)
- [ ] 
- [ ] 
- [ ]

**Comment by lmullane** [comment]
Looks good to me, @JHarrietha-AOT. Thanks for the quick turn-around!
