### ISSUE TITLE
Tech Debt - Gathering Records and Records Review

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3513]
Title of ticket: 

#### Description
The purpose of this task is to clean code, ENV VARs, Load/Volume Testing and make sure "Gathering Records" and its dependent components/apps like 'Dedupe Services', 'Conversion Services' and  Reviewer API, Redis and DB

#### Dependencies
Are there any dependencies?

#### DOD
- [x] #3521 - Tried to reproduce and find the Root cause, 
- [x]  Remove/Clean Commented code on all apps related to Gathering Records - Dedupe, Conversion, review api
- [x]  Remove/Clean Up ENV VARs on Reviewer API, and other services
- [x]  Reviewer API needs Authorization/ Security trimming based on Ministry Team and/or IAO
- [x]  Analysis and Plan for single source of truth for all File Format extension - COnfig Map , ENV VAR and / or S3 - 
    Rather that doing code build?
- [x] Analyse the code on related apps and fine tune the data fetching - For e.g : LOC39/documentservice.py

BUGS
====
- [x] Computing response does not respond error status
- [x] UI logic change for displaying icon based on failed property.
- [x] Replay for errored files is not working (Dependent on above)
- [x] Jobs communication (handshake) is not resilient
- [x] Document deleted needs to capture more info.
- [x] Duplicate info is not accurate (flag)
- [x] **Same document gets 2 different hashcode (**use-uploaded record**) Temporary work around till level 2 implementation**
- [x] Eliminate the default redaction ready "flag".
- [x] Do we allow delete attachment  ? If no; we should remove the option from UI; this feature never work
- [x] Hide or disable this button; if no records for redaction

#### Pre Deployment Steps 
- [x] set env variable in doc reviewer api and request management api FOI_RECORD_FORMATS
- [x] set config map in forms-flow-web REACT_APP_FOI_RECORD_FORMATS

**Comment by lmullane** [comment]
@divyav-aot to update the DOD.

**Comment by abin-aot** [comment]
@lmullane , we will need to do some level of Load/Volume testing and tech debt clearance for gathering records as well. DOD will be added accordingly

**Comment by abin-aot** [comment]
added DODs ! @lmullane , @m-prodan : Idea is like, everyone will join this task in the end to do a through testing(volume), optimisation on code and see how gathering records behaves. @nkan-aot will kickoff and rest of the team will join as they get freed from their tasks

**Comment by m-prodan** [comment]
Note from stand up - create seperate task for load testing (last DOD)

**Comment by m-prodan** [comment]
note for QA - this is a regression of the gathering/records review functions in test-marshall

**Comment by m-prodan** [comment]
From stand up - will do regression when load testing concludes and other tech debt is addressed to avoid duplication of work

**Comment by abin-aot** [comment]
moving back to in progress, if clean ups are still pending!

**Comment by abin-aot** [comment]
Added new DOD and started working,  as there is a need for `security` fix and clean up more unwanted objects on reviewer_api  - reported, informed to all DEVs

**Comment by abin-aot** [comment]
- [x]  Remove/Clean Up ENV VARs on Reviewer API, and other services
- [x]  Reviewer API needs Authorization/ Security trimming based on Ministry Team and/or IAO

Completed these 2 DODs
