### ISSUE TITLE
Update Text CFR Form

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3534]
Title of ticket: 

#### Description
It was observed during training that the first info bullet point for Producing records is incorrect, and should actually be moved to the Locating/Retrieving info bullet point - see highlighted bullet point in screenshot below. Users have also commented that the alignment of the tooltips are a bit off - shifting them upwards to more closely align with the first line of text should satisfy that. (eg - move tooltip for Locating/Retrieving to be on the same line as the text "Locating/Retrieving - This includes searching all relevant sources"

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/85a54190-d1ee-41e4-8f43-7a7c18163129)

In addition - Electronic Estimated Pages, and Electronic Actual Pages should instead be:
Electronic Estimated Files
Electronic Actual Files

and the data entry window should be changed from pg(s) to file(s) for both

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/187b35a3-b20d-4dc5-9a82-7ada0e97ad44)

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Move the first bullet point in the producing tooltip, to the locating/retrieving tooltip
- [x] Shift tooltips up - alignment can be somewhat confusing
- [x] Update Text for Volume of Electronic Files in both estimate and actual fields

**Comment by KyEggleston** [comment]
Updates made - closing.
