### ISSUE TITLE
Update "Deduplicated Files" Counter to Read "Duplicates Removed"

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3536]
Title of ticket: Update "Deduplicated Files" Counter to Read "Duplicates Removed"

#### Description
Under the Records tab, the "Deduplicated Files" counter should be updated to read "Duplicates Removed". This was based on user feedback during demo where we showed the gathering records log (Records tab).

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by nimya-aot** [comment]
Working as expected on Test-marshal, so closing this ticket
