### ISSUE TITLE
Download Records Package (Harms) - Changes Made

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3547]
* As a Ministry, or IAO user
* I want the records package download feature to also pick up any changes made to the package after the original download
* so that I can ensure I have the latest package

**Assumptions & Scope**	
This story is related to #3421, #3301, and #3231 - user stories related to saving records packages for various purposes

At stand up on March 24th, it was discussed and learned that the AC in these stories do not capture the scenario of what happens when changes are made to the package, after the download has been initiated - for example:

Download records for harms - if the Ministry creates the package for harms, and later adds additional records - the download link still pulls the old package. We need to ensure the download feature will trigger a new job, when there are changes made.

What is IN scope?
Updates to the download records feature

**Acceptance Criteria**	

**Scenario 1: Download for Harms - records added or removed**
* GIVEN a Ministry or IAO user has downloaded the records for harms
* WHEN additional records are uploaded to the request
* OR if records have been removed from the request
* THEN the download records for harms feature will revert to creating a new package, reflecting the changes to the records

**Scenario 2: Download for Harms - Error - System**
* GIVEN a Ministry or IAO user has selected to download/create the harms package
* WHEN an error occurs during the download/creation that is network/connection related
* THEN the system will automatically retry the download/creation function

**Scenario 3: Download for Harms - Error - Stitching**
* GIVEN a Ministry or IAO user has selected to download/create the harms package
* WHEN an error occurs during the stitching process (eg - file is not able to be stitched due to some kind of corruption)
* THEN the system will skip the file and continue the stitching process
* AND a notification will be sent to assigned users saying: [Filename] could not be added to package, please check record for errors
* AND a system generated comment will be posted to the request history saying: [Filename] could not be added to package, please check record for errors

**Scenario 4: Download for Harms - Notifications - User not Assigned**
* GIVEN a Ministry or IAO user has attempted to do any action with records upload or download
* AND the user is NOT assigned to the request or is watching the request
* AND that action results in a notification
* THEN the user will also receive the notification, in addition to the assignees

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
As discussed in refinement - moved scenarios 2 and 3 to their respective user stories re: redline for sign-off and response package for applicant

**Comment by m-prodan** [comment]
Notes from standup - What do we do about files that can't be stitched? No retry - rather skip and ensure there is an error message via notification (and sys generated comment) highlighting which file was corrupted. For other errors, like connection/network errors - system will auto-retry.

Will update AC

**Comment by m-prodan** [comment]
Also add AC that notifications will also trigger to user that initiates action related to records if the user is not assigned to the request.

Use case: Ministry user covering for other, but isn't a watcher or assignee, tries to download records for harms for their colleague. They should be notified

**Comment by m-prodan** [comment]
@divyav-aot - AC updated per discussion at stand up

cc: @lmullane @liseandtea @KyEggleston

**Comment by divyav-aot** [comment]
@m-prodan Updating the effort to 13 to incorporate all the changes discussed.

**Comment by KyEggleston** [comment]
@m-prodan - just checking regarding Scenario 4 - when a user who is not assigned the request, nor is a watcher, uploads new records to the gathering records log, we also want them to get the batch uploaded successfully notification and any error notification related to their upload or download? Right now they only get the notification that harms are ready for export. I think the answer is 'yes', they should get these notifications as well, but just want to confirm.

**Comment by liseandtea** [comment]
@KyEggleston I think that whoever the user is, assigned to a request or not, and they are completing an action involving the uploading/downloading of records they should receive any relevant notifications regarding their actions.

**Comment by KyEggleston** [comment]
Scenario 4 - user who is not assigned or a watcher on the request will also be notified when their records batch is uploaded. Otherwise, all other notifications are being sent and received. 

Will create task ticket to test this after load testing and other merges are done.
