### ISSUE TITLE
Load , Volume Testing - Gathering Records

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3560]
Title of ticket: 

#### Description
The purpose of this task is to check apps performance , behaviour while uploading various file types in a realistic volume, with a realistic level of concurrency agreed by business, and there by understand the UX, issues and breakpoint if possible. 

Note : The Idea is to do load/volume testing in different stages and/or  steps - This way we can relate the performance of each operations/feature!

1. Isolated/Exclusive Volume Test per feature -  TBD FileCount per test: ~ eg:  average of 60 Pdfs, 40 excels, 40 DOCx, 40 MSG and 20 Icals

   - `Exclusive Dedupe - only PDFs & addn. file types - JPGs, PNGs, SHP files etc`, 
    - `conversion and dedupe together`  

              - PDF
              - DOCX/DOC
              - XLS/XLSX
              - MSG
              - PNG. JPGS, Shape file , JSON etc

      - `stitching` etc.

2. Inclusive Load Testing : This is stage where we test more real life conditions - like mix and match of various file types and file sizes are uploaded in a concurrent manner! - say like, minimum 10 people uploading files concurrently. 100MB/ 300MB / 500 MB- @abin-aot to get stats from LAN and S3 archives

#### Dependencies
Are there any dependencies?

#### DOD
- [x]   XLSX/XLS - Isolated/Exclusive Volume Test 
- [x]   PDF - Isolated/Exclusive Volume Test 
- [ ]   DOCX/DOC - Isolated/Exclusive Volume Test 
- [x]   MSG -  Isolated/Exclusive Volume Test 
- [x]   100 MB each / 10 user concurrency  - Inclusive Load Testing  - Say Like, 60 PDFs, 40 XLSX, 30 DOC, 20 MSG, 30 JPEG, few shapes - idea is to have all file types in a go!
- [x]   300 MB each / 10 user concurrency  - Inclusive Load Testing  - Say Like, 60 PDFs, 40 XLSX, 30 DOC, 20 MSG, 30 JPEG, few shapes - idea is to have all file types in a go!
- [x]   500 MB each / 10 user concurrency  - Inclusive Load Testing  - Say Like, 60 PDFs, 40 XLSX, 30 DOC, 20 MSG, 30 JPEG, few shapes - idea is to have all file types in a go!
- [x] find the resource limits for normal and large file processing (dedupe, fileconversion and pdfstitch)

**Comment by m-prodan** [comment]
As discussed at sprint planning - start by isolating specific file types to confirm if there are any memory leaks, or issues with specific file types.

After individual file types pass, move towards a blended test that more mimic real conditions. Ex. have seen requests with 800+ excels, others with over/around 100 msg files, and combinations within.

**Comment by m-prodan** [comment]
Need to make sure files that throw errors do not impact other files/processes

**Comment by m-prodan** [comment]
if possible - try attempting to upload a locked file such as a PDF
