### ISSUE TITLE
Onboarding - Divisional Updates -  OCC, IIO, HLTH, LDB, MHA

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3561]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD - Office of the Chief Coroner (OCC)
- [x] Add - Coroner's Office

#### DOD - Independent Investigation's Office (IIO)
- [x] Add - Independent Investigation's Office

#### DOD - Liquor Distribution Branch (LDB)
- [x] Add - Human Resources
- [x] Add - Corporate Strategic Services
- [x] Add - Cannabis Operations
- [x] Add - GM Operations
- [x] Add - Finance
- [x] Add - Information Technology (IT)
- [x] Add - Liquor Retail Operations
- [x] Add - Corporate Operations
- [x] Add - Liquor Wholesale Operations

#### DOD - Health (HLTH)

- [x] Add - MO - Minister’s Office
- [x] Add -  DMO - Deputy Minister’s Office
- [x] Add - ADMO - Assoc. Deputy Ministers’ Office
- [x] Add - CICR - Corporate Issues & Client Relations
- [x] Add - FCS - Finance & Corporate Services 
- [x] Add - HIBC - Health Insurance BC
- [x] Add - HPHS - Hospital & Provincial Health Services 
- [x] Add - HSIAR - Health Sector Information, Analysis & Reporting
- [x] Add - HSIMT - Health Sector Digital IM/IT 
- [x] Add - HSWBS - Health Sector Workforce & Beneficiary Services 
- [x] Add - IGR - Inter-government Relations 
- [x] Add - IHR - Indigenous Health & Reconciliation
- [x] Add - MHAD - Mental Health & Addictions Division
- [x] Add - OSA - Office of the Seniors Advocate 
- [x] Add - PCD - Primacy Care Division
- [x] Add - PHO - Office of the Provincial Health Officer 
- [x] Add - PLBS - Pharmaceutical, Labs & Blood Services
- [x] Add - PPH - Population & Public Health Division
- [x] Add - SID - Strategic Innovation Division
- [x] Add - SMPO - Strategic Management & People Office Division
- [x] Add - SSD - Seniors' Services Division  

#### DOD - Mental Health and Addictions (MHA)
- [x] Add - Minister’s Office (MO)
- [x] Add - Deputy Minister’s Office (DMO)
- [x] Add - Child, Youth & Mental Health Policy (CYMHP)
- [x] Add - Substance Use Policy (SUP)
- [x] Add - Treatment & Recovery (T&R)
- [x] Add - Corporate Services (CS)

**Comment by m-prodan** [comment]
Preferred approach:
1) Integrate admin screen built by Leo, to allow business to update these

Secondary - if Admin screen requires extra work or reworki:
2) Have dev run scripts to update

**Comment by KyEggleston** [comment]
Added HLTH divisions as well

**Comment by KyEggleston** [comment]
Add MHA divisions

**Comment by KyEggleston** [comment]
HLTH, MHA, LDB and IIO divs added to test - waiting for admin dashboard moved to prod to add divisions to prod.

**Comment by m-prodan** [comment]
All divisions confirmed as added - closing ticket
