### ISSUE TITLE
Multiple consult flags for one page

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3564]
* As an IAO analyst
* I want to add multiple consult flags to one page 
* so that I can flag a page for more public bodies consults

**Assumptions & Scope**	
What are the assumptions for this story?

IAO often needs to consult with other public bodies on pages subject to an FOI. Best practice is to provide the public body a clean copy (i.e., no  redactions on the page).

Consult flags can be a one to many, not always a one to one. We heard at demo that the business needs to be able to flag one page with more than one public body for consult. 

While more than one consult flag can be made on a page, you still cannot flag the page with a different flag (e.g. Partial Disclosure, Withheld in Full, etc.,).

Other public bodies added will persist within the given request, after they have been added.

As this is a one to many, the design will change to always use a modal when selecting a public bodies to consult

There will be only one modal which will enable the selection of both the usual public bodies (with an org code, inside the system) and the less frequent public bodies (without an org code, outside the system).

If an IAO user enters a new Other Public Body but does not 'Save' the change in the modal, that Other Public Body will not appear in the list.

What is IN scope?
Page flags
Page flags tooltip
Percentage complete

What is NOT in scope?
Other page flags (#3413)
Page flag filtering (#3417)
Total filtered pages counter (#3417)
Filtered Pane views/functionality (#3417)
'Page Left Off' page flag functionality (#3409)

**Acceptance Criteria**	

**Scenario 1: Select Page Flag - Consult**
* GIVEN an IAO analyst has right-clicked a page in the left hand 'Organize By' 
* WHEN the analyst clicks the 'Consult' page flag in the context menu
* THEN a modal will open containing all ministry Org Codes (XXX) in alphabetical order
* AND there will be a check box beside each ministry
* AND at the top above there will be an open text field titled 'Other Public Body' with an 'Apply' button
* AND the modal will have a 'Save' and 'Cancel' button
* AND the 'save' option will be grey and inactive
* AND the 'cancel' option will be blue and active

**Scenario 2: Select a new Ministry Org Code - Consult**
* GIVEN an IAO analyst is on the Consult modal
* WHEN the analyst clicks an empty checkbox next to a ministry Org Code (XXX) or Other Public Body
* THEN the  checkbox will turn green and have white checkmark
* AND the 'Save' button will turn blue and active (when one or more Org code is selected)

**Scenario 3: Unselect a Ministry Org Code - Consult**
* GIVEN an IAO analyst is on the Consult modal
* AND there is a ministry Org Code already selected
* WHEN the analyst clicks a filled checkbox next to a ministry Org Code (XXX) or Other Public Body
* THEN the checkbox will become empty with no check mark
* AND the 'Save' button will turn grey and become inactive (when no Org code is selected)

**Scenario 4: Other Public Body - Enter Name in text field**
* GIVEN an IAO analyst is on the 'Consult' modal
* WHEN the analyst has entered any value (>=1 character) in the open text field for 'Other Public Body'
* THEN the 'Apply' button next to the text field will be blue and active

**Scenario 5: Other Public Body - Apply name entered**
* GIVEN an IAO analyst is on the 'Other Public Body' modal
* AND they have entered any value (>=1 character) in the open text field
* WHEN the analyst left-clicks 'Apply'
* THEN a new public body (NAME entered) will be listed at the top of the list of ministry Org Codes
* AND the the checkbox next to the new public body will be filled green with a white check mark
* AND the 'Save' button will turn blue and active
* AND the analyst can enter a new Other Public Body in the open text field

**Scenario 6: Select Consult Modal - Cancel**
* GIVEN an IAO analyst is on the 'Consult' modal
* WHEN the analyst left-clicks 'cancel'
* THEN the modal will close
* AND no changes to the consult flags will be saved

**Scenario 7: Display One Ministry Org Code**
* GIVEN an IAO analyst is on the 'Consult' modal
* AND the 'Save' button is active and blue
* AND only 1 ministry Org Code has been selected for consult
* WHEN the analyst left-clicks 'Save'
* THEN the modal will close
* AND the Consult icon will display next to the page
* AND the ministry Org Code will be displayed in line with the page

**Scenario 8: Display Other Public Body Modal**
* GIVEN an IAO analyst is on the 'Consult' modal
* AND the 'Save' button is active and blue
* AND only 1 Other Public Body has been selected for consult
* WHEN the analyst left-clicks 'Save'
* THEN the modal will close
* AND the Consult icon will display next to the page
* AND Other Public Body NAME will be displayed in line with the page will be displayed in line with the page

**Scenario 9: More than one Ministry Org Code or Other Public Body Selected**
* GIVEN an IAO analyst is on the 'Consult' modal
* AND the 'Save' button is active and blue
* AND more than 1 ministry Org Code or Other Public Body has been selected for consult
* WHEN the analyst left-clicks 'Save'
* THEN the modal will close
* AND the Consult icon will display next to the page
* AND the total number of consulted public bodies will be displayed (e.g. 1, 2, 3, etc.,)

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/981498459

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@KyEggleston, @m-prodan, @liseandtea please review and comment.

One item for discussion is how we display selected consulted public bodies in the 'Organize Pane.' If there is many selected we will not be able to display them all. Open to suggestions.

**Comment by m-prodan** [comment]
I like the idea of a number - I agree it's going to be hard to put more than a couple up on the panel visually... especially if one is an external PB which could require more characters. 

Otherwise - this looks good. I cleaned up some of the AC for clarity.

**Comment by lmullane** [comment]
Thanks, @liseandtea and @m-prodan, 

@KyEggleston, suggested the hover over as well, but may be sufficient for them to right click and open the modal again to see all the listed public bodies to be consulted. Thoughts?

**Comment by m-prodan** [comment]
Hover would be more of a nice to have - the multiple consult locations per page issue isn't rare on certain file types, but I wouldn't consider it common across most requests where consults are required, so re-opening the modal to confirm doesn't seem like it'd be too taxing on users.

**Comment by KyEggleston** [comment]
This looks good - just to note, currently when you hover over a page in the left pane with the consult flag, a tooltop is displayed reading: "Consult - [Org Code]". So this is already in there - so it may not be much effort to allow >1 Org code to be displayed in this tooltip. 

![image](https://user-images.githubusercontent.com/117312323/228892103-0da467ff-4dac-4a5f-b66c-3696f4f2b352.png)

**Comment by m-prodan** [comment]
@JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
@lmullane @m-prodan @liseandtea @KyEggleston 

https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/982914680

Here is a link to the design of the module for the above ticket. Made a couple of minor tweaks. 
- I have the add a new option at the bottom, for a couple of reasons. Along the top I find it visually minics a search bar which it is not, And we want to encourage users to look through the provided list first not default to adding ones that could be there so I figured this order makes more logical sense. 

Both Matt and Lise looked through the list of Ministry accornymns but feel free to tag me if it needs any additional changes. Lastly if you click to type a name and then click the + button then you will see how it will look when users add other Public Bodies. 

Let me know if anyone has any questions or changes.

**Comment by KyEggleston** [comment]
@nkan-aot - one thing I noticed is for scenario 3. When a public body / bodies are selected (and you save and close the modal), and then you reopen the consult modal and remove the public body / bodies selected (i.e., 0 public bodies selected), you are able to save. This leads to a consult flag with 0 public bodies selected. I think we need to prevent users from saving the consult menu when no public bodies are selected. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/65b91290-0385-478a-abb5-589287a42807)

![image](https://github.com/bcgov/foi-flow/assets/117312323/26093cbd-a8a8-4614-b046-5b53a99a1e95)

Also, minor UI issue with the 'Type Name of Other Public Body for Consult' field text overlapping:

![image](https://github.com/bcgov/foi-flow/assets/117312323/6c73bb92-36e7-4e03-b241-aaa9f5c0aeac)

**Comment by KyEggleston** [comment]
Both fixes above made, working properly - closing ticket.
