### ISSUE TITLE
Page numbering issue with landscape pages

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3565]
Title of ticket: 

#### Description
Some of the stitched pages are having issue placing the page numbers.
Below screenshot shows the issue.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/d4075453-678e-4dd2-ab1c-43db54c067b5)

After the fix,
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/65bdd0ea-7640-4b37-9ac0-1228124c8195)

**Comment by KyEggleston** [comment]
This is resolved for me, but will keep an eye out during other Gathering Records testing.
