### ISSUE TITLE
remove 'No video for article' text

### ISSUE THREAD

**Issue by katrinaferacini** [bcgov/foi-flow#3569]
**Describe the bug in current situation**
When a help article is published without an mp4 file in help.foirequests.gov.bc.ca, a red text saying "No video for article" is included in prod frontend. This task is to remove the red text, as there are situations where help articles will be published without an mp4 file. See screenshot for an example.

**Link bug to the User Story**

**Impact of this bug**
All users impacted as all users see the red text, but functionality is not affected. The help articles function as they are supposed to without mp4 files. 

**Chance of Occurring (high/medium/low/very low)**
high

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
production link: https://help.foirequests.gov.bc.ca/help-article/applicant-payment
backend link: https://foi-help-backend-test.apps.silver.devops.gov.bc.ca/admin/

**Steps to Reproduce**
1. Go to 'foi-help-backend'
2. Click on 'Content Manager', and then Help Article
3. Create new entry, then fill in body and slug.
4. Do not add media
5. Click Save 
6. Access https://github.com/bcgov/foi-help/actions/workflows/web-deploy.yaml and front end deploy

**Actual/ observed behaviour/ results**
Red text saying 'no video for article'

**Expected behaviour**
No red text saying 'no video for article'

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/633318928b7f4e47a5d154ec/fbce0ba4-90b0-40fd-a1f9-a465fd511aaf)

**Comment by lmullane** [comment]
Update with bug template.

**Comment by katrinaferacini** [comment]
Updated with bug template

**Comment by katrinaferacini** [comment]
@richard-aot Thanks for completing this one!!
