### ISSUE TITLE
Release planning - meetings and prep

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#357]
#### Description
There are a number of meetings and communications needed as part of release planning

#### DOD - meetings have been scheduled
- [x] Draft high level user stories for remaining epics (Th Aug 19, Matt and Molly)
- [x] Review above user stories (W Aug 25) - Loren, with Matt
- [ ] Meeting (~Th Aug 26): Review epics with IAO team leads (Matt to set up)
- [x] Meeting (~F Aug 27): Review epics with focus on architecture and design (Matt to set up - Matt, Loren, Abin, Jackie)
- [x] Meeting: Overview of release planning goals and epics (Mon Aug 30 for 1 hr - Product team)
- [x] Meeting: Release planning and estimation (Tue Aug 31 for 2 hrs - Product team)
- [x] Follow up with date calculation and graphing (Loren and Molly)
- [ ] Meeting: IAO Sr leadership (~F Sep 3)

**Comment by m-prodan** [comment]
Re; Meeting (~Th Aug 26): Review epics with IAO team leads (Matt to set up) - Ken is off this week, and I think I'd like to square off these epics with Loren first - I'll try to get meetings set up for the following week, or perhaps friday with Jamie O if that works for her.
