### ISSUE TITLE
UX Design Updates - Assorted 

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#3576]
Title of ticket: UX Design Updates 

#### Description
List of UX Design updates that came up while I was away.

#### Dependencies
Are there any dependencies?

#### DOD
- [x]  # 3437 - Update design option dropdown
- [x]  # 3564 - Multiple consult flags on one page
- [x]  # 3568 - Export/Download pages for consult
- [x]  Left of here filter feels clunky and not useful
- [x] FOIPPA Section organization feels clunky find better design solution
- [x]  Gathering Records Log - Retry all Button & Ability to Filter in Process

**Comment by JHarrietha-AOT** [comment]
@lmullane @m-prodan @liseandtea Sharing a link here for the design for the redaction filter dropdown, after talking this afternoon I was thinking this likely should be something an analysts decides or changes first when they open PDF Tron to ensure they are on the correct layer. Let me know what you think about the placement of it in the left panel. Comment if you have any changes or ideas and I can work through them before standup tomorrow morning

https://jacklyn808742.invisionapp.com/overview/Redaction-cla8feezv003o015h7op82c5c/screens

**Comment by m-prodan** [comment]
@JHarrietha-AOT the link doesn't take us to the right page, but I think we might have found it (https://jacklyn808742.invisionapp.com/console/Redaction-cla8feezv003o015h7op82c5c/cleg4xqe55wt3018ba31e3cvi/play) -when we poked around with it, it didn't seem to activate the toggle. Was that intentional? Happy to chat tomorrow.

cc: @lmullane

**Comment by JHarrietha-AOT** [comment]
@m-prodan @lmullane 

Yes that is the correct link! Sorry I didn't copy the correct one in the earlier comment

**Comment by JHarrietha-AOT** [comment]
@m-prodan @lmullane 

Should work now, let me know if you have any other issues
https://jacklyn808742.invisionapp.com/overview/Redaction-cla8feezv003o015h7op82c5c/screens

**Comment by lmullane** [comment]
@JHarrietha-AOT, how does the (+) OIPIC Layer and (+) Open Info work?
