### ISSUE TITLE
Display FOIPPA Sections in Redaction Box in Ascending 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3580]
* As a user of the redaction application 
* I want FOIPPA sections stamped in the redaction box to be sorted in ascending order (e.g., s.3, s.12, s.13, s.14)
* so that I can more easily identify the applied sections and ensure consistent FOIPPA section  application

**Assumptions & Scope**	

This is to update a small detail missed related to #3313.

Currently, when a user is in the FOIPPA section modal and has selected either the 'Most Used' organizer, or they have selected the 'Numbered Order' organizer (and has selected the descending arrow), the FOIPPA sections in the redaction box are organized based on how they are organized in the modal at the time of selection.

For example:

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/630c58fc-9559-4779-aa70-4cd903fe2135)

Shows up as:

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/de2f08eb-4c7f-45e5-b19c-cd4e49522df7)

However, regardless of which organizer is selected, the FOIPPA sections should **_always_** be displayed in ascending manner within a redaction box (regardless of the FOIPPA section modal organizer selected). That is to say, they should always be organized like the 'Numbered Order' organizer is selected, and the arrow is sorting in ascending. 

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/df08ece9-0671-46bb-add6-772b7010873b)

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/96d7023a-291b-4eeb-8668-2eed9284e042)

In addition, the annotation and comment in the 'Comments' pane should also display the FOIPPA sections in ascending order:

![image](https://github.com/bcgov/foi-flow/assets/117312323/f430e98b-a194-4b90-910c-e31c69b6672a)

NOTE - the 'Blank Code - CFD Personals' can be last in ascending order, as it won't have a number associated to it, and will not be used with other FOIPPA sections. See #3586 

What is IN scope?
Displaying FOIPPA sections in redaction box (in the 'Review' or middle pane)

What is NOT in scope?
Changing the FOIPPA section modal

**Acceptance Criteria**	

**Scenario 1: Section Stamp - 'Most Used'**
* GIVEN a redaction (box or highlight) has been created
* AND the FOIPPA section modal is open
* AND the 'Most Used' filter is selected
* WHEN multiple different FOIPPA sections are checked
* And the user clicks 'Select Code(s)'
* THEN the selected FOIPPA sections will be stamped in the redaction
* AND the stamped FOIPPA sections will be displayed in the redaction in ascending order 
* AND the associated annotation and comment in the 'Comments' pane will also display the FOIPPA sections in ascending order 

**Scenario 2: Section Stamp 'Numbered Order' DESC**
* GIVEN a redaction (box or highlight) has been created
* AND the FOIPPA section modal is open
* AND the 'Numbered Order' filter is selected in descending order (i.e., arrow pointing down)
* WHEN multiple different FOIPPA sections are checked
* And the user clicks 'Select Code(s)'
* THEN the selected FOIPPA sections will be stamped in the redaction
* AND the stamped FOIPPA sections will be displayed in the redaction in ascending order 
* AND the associated annotation and comment in the 'Comments' pane will also display the FOIPPA sections in ascending order 

**Scenario 3: Section Stamp 'Numbered Order' ASC**
* GIVEN a redaction (box or highlight) has been created
* AND the FOIPPA section modal is open
* AND the 'Numbered Order' filter is selected in ascending order (i.e., arrow pointing up)
* WHEN multiple different FOIPPA sections are checked
* And the user clicks 'Select Code(s)'
* THEN the selected FOIPPA sections will be stamped in the redaction
* AND the stamped FOIPPA sections will be displayed in the redaction in ascending order 
* AND the associated annotation and comment in the 'Comments' pane will also display the FOIPPA sections in ascending order 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
@lmullane @m-prodan - just a task to update the FOIPPA sections in the redaction box to be ordered in an ascending manner. We thought this was fixed (but weren't sure how), but it's come back up - so we should have an actual ticket to address it.

**Comment by KyEggleston** [comment]
Note for QA - when testing AC #1, make sure the FOIPPA section modal has the FOIPPA sections mixed around based on 'most used' before testing. 

Also note that the FOIPPA sections stamped in a redaction on the 'Review' or middle pane, and in the 'Comments' pane, should all be organized left to right in ascending order (i.e., s.3, s.12, s.13, s.22.1, etc.)

**Comment by abin-aot** [comment]
Refinement comments

- Business to provide sort order (1, 2, 3) of sections and subsections
- This is a Back end update on DB Table, and whenever a new section is added in between, order need to be update via a developer
- Ideal way to update is via Admin , which will be a new US and effort

**Comment by lmullane** [comment]
Thanks, @milosdes. All AC work as expected.
