### ISSUE TITLE
Colour Picker Always Opens on New Redaction 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3581]
**Describe the bug in current situation**
Currently in the test redaction application (when accessed via Test-Marshal), whenever a new a redaction is applied with a FOIPPA section, the colour picker is displayed automatically. This occurs when using the redaction drawing tool (e.g., drawing a square or rectangle) and when using text highlighting redaction (right-clicking and dragging over text). This was not happening prior to 2023-03-30. The request this was tested on is EDU-2023-10786.

This could be annoying for users when adding many redactions, as they will constantly have to click outside of the colour picker to cancel it. In most cases, a user will not change the colour anyway. 

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/d5ea9ee2-2cf3-4c95-be7c-ad39534c50fc)

This should not be displayed automatically after applying a redaction.

**Link bug to the User Story**
#3488 

**Impact of this bug**
Low

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a record/page in the test redaction app
2. Click on the redaction tool select an area for redaction 
3. In the FOIPPA sections modal, select FOIPPA sections, and select 'Select Code(s)'
4. The FOIPPA sections modal will close, the redaction will be stamped on the page, and the colour picker will be displayed automatically to change the FOIPPA section stamp colour

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a user is on the FOIPPA section modal
WHEN the user applies a redaction section code
THEN no colour picker will be displayed
AND the default will always be red

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
Dependent story is #3488

**Comment by liseandtea** [comment]
Tested on EDU-2022-06756 - Resolved: colour picker is not showing once a redaction choice has been made and is defaulting to red.
