### ISSUE TITLE
Withheld in Full - Black Redaction Box Fill

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3583]
#### Description
This came up during QA for #3487

To align with other redactions (which have white fill when hovered over), the default fill colour when a page is auto 'Withheld in Full' should be changed from black to white when applying a full page redaction.

When hovering over a full page redaction / auto 'Withheld in Full' (fill is black):
![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/a6263c66-0706-4aa9-b28d-2ef42f0d2d34)

When hovering over any other redaction (fill is white, which is correct):
![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/f37c07ff-e8f1-46d5-9176-ec6ad6e73012)

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Fill colour when a page is auto 'Withheld in Full' changed from black to white when applying a full page redaction
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by KyEggleston** [comment]
@aparna-aot - here is a placeholder ticket for the black fill - unfortunately I'm not here for the rest of the week to help narrow this down further or QA, but I'm sure others can help.

**Comment by KyEggleston** [comment]
I believe this has already been resolved

**Comment by lmullane** [comment]
Thanks, Kyle. Can we close this ticket?

**Comment by KyEggleston** [comment]
I believe this was resolved as a byproduct of #3506, but I will confirm in morning that there is no edge case I'm missing.

**Comment by KyEggleston** [comment]
Disregard, this is resolved as part of #3506. Closing.
