### ISSUE TITLE
Integration of Admin Dashboard

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#3585]
Title of ticket: 

#### Description
Integrate Admin dashboard code developed by Leo Dube to foi-flow and push to production.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Integration
- [x] Authentication
- [x] Testing
- [x] Cache clearing API integration (Optional)
- [x] Fix issues with APIs.
- [x] List all Program Areas while adding new divisions.
- [x] Fix filter issue.
- [x] Added Toasts for success/error messages

**Comment by KyEggleston** [comment]
This is functioning in Test as expected - closing.
