### ISSUE TITLE
Blank cannot be selected with a section of the Act

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3586]
* As an IAO analyst
* I want to only select Blank or a section for a redaction box
* so that I can apply the correct auto-flag (i.e., In Progress vs Partial Disclosure).

**Assumptions & Scope**	
What are the assumptions for this story?

Only one page flag can be selected for each page. 

The purpose of selecting Blank is to be able to go back later and stamp the page with all the sections of the Act which were applied.

There is no scenario where an analyst would mark a redaction as both Blank and by a section.

What is IN scope?
Page flags
Page flags tooltip
Percentage complete

What is NOT in scope?
Page flag filtering (#3417)
Total filtered pages counter (#3417)
Filtered Pane views/functionality (#3417)
'Page Left Off' page flag functionality (#3409)

**Acceptance Criteria**	

**Scenario 1: Redaction Modal Menu - select blank**
* GIVEN an IAO analyst is on the FOIPPA section modal: https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/970284600
* AND no boxes have been checked
* WHEN the analyst clicks the checkbox next to 'Blank'
* THEN the checkboxes for the sections of the Act will be grey and inactive

**Scenario 2: Redaction Modal Menu - blank already selected**
* GIVEN an IAO analyst is on the FOIPPA section modal: https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/970284600
* WHEN the 'Blank' box has already been selected
* THEN the checkboxes for the sections of the Act will be grey and inactive

**Scenario 3: Redaction Modal Menu - select section(s) of the Act**
* GIVEN an IAO analyst is on the FOIPPA section modal: https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/970284600
* AND no boxes have been checked
* WHEN the analyst clicks the checkbox next to any section of the Act
* THEN the checkbox for 'Blank' will be grey and inactive

**Scenario 4: Redaction Modal Menu - section(s) of the Act already selected**
* GIVEN an IAO analyst is on the FOIPPA section modal: https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/970284600
* WHEN a checkbox next to any section of the Act has already been selected
* THEN the checkbox for 'Blank' will be grey and inactive

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/981498459

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
@nkan-aot - There may be an issue with the FOIPPA section modal in Marshal - it doesn't appear when selecting a full page, or a portion of a page, for redaction. You can apply the redaction, but no option to select the FOIPPA section. 

When trying to edit the redaction to add a FOIPPA section, error thown:

![image](https://github.com/bcgov/foi-flow/assets/117312323/3b88c3e6-0477-4ce3-bd3a-110a5008c306)


![image](https://github.com/bcgov/foi-flow/assets/117312323/dbebe68a-c59c-4b6a-a76c-e0d87d0a6770)

**Comment by KyEggleston** [comment]
@nkan-aot - one observation:

1. Create a redaction
2. Select a blank code, or FOIPPA section, and click 'Select Code(s)'
3. Left-click on the redaction box and select the 'Edit' icon/option
4. Unselect the blank code or FOIPPA section you already selected
5. Note that all options do not become available after unselecting all checkboxes (e.g., If you originally selected the blank code, when you click edit and unselect it, all options, including the FOIPPA sections, do not become available to select). 
6. If you select and unselect the original code again, then all options become available to select. 

Originally select the blank code and clicked 'Select Code(s)'
![image](https://github.com/bcgov/foi-flow/assets/117312323/4102c280-0e03-4cea-ac33-f4ac0ec3129a)

Selected the 'Edit' icon/option
![image](https://github.com/bcgov/foi-flow/assets/117312323/6ab6005d-c4e7-48a2-88d7-093c6342dd50)

Unselected the blank code, but the other options do not become selectable (they are still greyed out, even when blank code is not selected)
![image](https://github.com/bcgov/foi-flow/assets/117312323/82e7b03f-856f-49f6-981d-d9fcd31d4bbd)

However, after selecting and unselecting blank code again, then all options become selectable
![image](https://github.com/bcgov/foi-flow/assets/117312323/f4cc1f28-d520-47ba-9f63-0bf93ac23a21)

How it should work:
GIVEN an analyst has applied a redaction
AND has selected either a FOIPPA section number(s) or blank code
WHEN the analyst left-clicks the redaction and selects 'Edit' 
AND the analyst removes all checkmarks next to a FOIPPA section or blank code
THEN all options in the FOIPPA section modal should be selectable

**Comment by KyEggleston** [comment]
Confirmed the above is resolved - closing ticket.
