### ISSUE TITLE
Division Update - FOR/EML

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3599]
Title of ticket: 

#### Description
Splitting #3561 so we can move ahead with FOR/EML faster, ahead of onboarding for Tuesday Apr 11

#### Dependencies
Are there any dependencies?

#### DOD - Energy and Mines (EML)
- [ ] Add - Minister's Office
- [ ] Add - Deputy Minister's Office
- [ ] Add - Electricity and Alternative Energy Division
- [ ] Add - LNG Canada Implementation Secretariat
- [ ] Add - Mines, Competitiveness and Authorizations Division
- [ ] Add - Oil and Gas Division
- [ ] Add - Strategic and Indigenous Affairs Division
- [ ] Add - Woodfibre Implementation Group

#### DOD - Forests (FOR)
- [ ] Add - Minister’s Office
- [ ] Add - Deputy Minister’s Office
- [ ] Add - DMO – Strategic Priorities Group
- [ ] Add - Associate Deputy Minister’s Office
- [ ] Add - Associate DM – Indigenous Relations
- [ ] Add - Associate DM – Operations
- [ ] Add - ADM – BC Wildfire Service
- [ ] Add - ADM – Office of the Chief Forester
- [ ] Add - ADM – Integrated Resource Operations
- [ ] Add - ADM – Timber, Range, and Economics
- [ ] Add - ADM – BC Timber Sales
- [ ] Add - ADM – Forest Renewal Initiative and Old Growth
- [ ] Add - ADM – Corporate Services for Natural Resources
- [ ] Add - ADM – North Region
- [ ] Add - ADM – South Region
- [ ] Add - ADM – Coast Region
- [ ] Add - RED – Northeast
- [ ] Add - RED – Omineca
- [ ] Add - RED – Skeena
- [ ] Add - RED – Cariboo
- [ ] Add - RED – Kootenay Boundary
- [ ] Add - RED – Thompson Okanagan
- [ ] Add - RED – South Coast
- [ ] Add - RED – West Coast

**Comment by m-prodan** [comment]
@aparna-aot - QA passed - tested against personal and generals, also tried adding all divisions and updates. No fail conditions - this can go to PROD, just going to tag it to a release

**Comment by aparna-aot** [comment]
@m-prodan Great. Will you be able to verify in PROD if I push this today evening by 4.00 pm?

**Comment by m-prodan** [comment]
Tagged to release 6.2.2 - yes I can check after 4PM today @aparna-aot
