### ISSUE TITLE
Filename length issue on Gathering records - above 115 or more its breaking the batch

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3603]
**Describe the bug in current situation**

While testing few type DOC/DOCX files its been observed that, file with certain characters on filenames are not getting uploaded and most important : 'when it is in a batch - the whole list of files on `GATHERING RECORDS` **disappear**
[https://app.zenhub.com/files/358004325/2d412041-adb4-488b-9657-ebea6a52ae54/download](https://app.zenhub.com/files/358004325/2d412041-adb4-488b-9657-ebea6a52ae54/download)

Note :

`Freedom of Information Modernization - Information Access and Operations - Project Arch & Design, Specification Document -version 1. docx `  - THE FILE NAME IS CAUSING ISSUE!!!!!! Might need to handle the character 'length' on the file name!!!. its breaking the functionalities above 115 character in  filename

Certain Logical File name that happen will be like this.

1. Software System, Design and Architecture - Health (and Minister Responsible for Francophone Affairs) - Project Specification Document v1. docx
2. Inter-governmental Relations Secretariat - Project Estimation - Freedom of Information and Protection of Privacy Act.docx
3. Statement of Work - Health (and Minister Responsible for Francophone Affairs) - Quote requesting Application System upgrade.docx

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/b2e25001-9231-4867-a3f4-f8a02e3a227d)

**Link bug to the User Story**

**Impact of this bug**
None of the files(Even the files with proper names in the list) will NOT be listed/displayed on GATHERING RECORDS tab

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Gathering Records as a Ministry user
2. Upload the DOCX files extracted from the above ZIP file link
3. None of the files will be listed/displayed on GATHERING RECORDS tab

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by abin-aot** [comment]
@lmullane , @m-prodan , @liseandtea , @KyEggleston  : Assuming above mentioned file name are logical and can happen with in ministries!!! Anyone can create filenames under 256 characters I guess

**Comment by sumathi-thirumani-aot** [comment]
Changes were made to increase the file length to support 500 characters. 
Moved to dev marshal.

**Comment by abin-aot** [comment]
Technically Filename length limit is  below ~256 !

**Comment by nimya-aot** [comment]
Working as expected.

**Comment by nimya-aot** [comment]
@m-prodan @lmullane I noticed that when we download harms for lengthy files(say more than 200 characters), unable to download the files in to the system. Not sure we need to increase our file length while creating zip file

.![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/f6e20db3-3c56-4b86-b151-be808d67a0da)
