### ISSUE TITLE
Gathering Records : Show retry option for records stuck in processing

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#3610]
**Describe the bug in current situation**
Considering any technical issues in the "conversion or dedupe" process. If the uploaded file has not been completed within a period of say X hrs. Show the option to retry from FE. Currently, the options shown are "Delete" , "Download Original".

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by sumathi-thirumani-aot** [comment]
@JHarrietha-AOT  @m-prodan @KyEggleston 

Can you please review this design, behavior and share feedback on the icon and color and etc?

![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/9e84d95c-6481-476b-a2b9-03af026789b5)

**Comment by sumathi-thirumani-aot** [comment]
@JHarrietha-AOT Can you please write on the message of the timeout scenario.
 Also, what have to be the hours for a timeout. ?

**Comment by JHarrietha-AOT** [comment]
@sumathi-thirumani-aot As discussed in stand-up

- We will keep the filter to just "Errors" to avoid confusion with analysts and because a time-out is especially a type of error
- Icon will stay the same as the "!" used for all other errors for consistency. 
- and the text will say "Error due to time out"

@m-prodan let me know if I missed anything

**Comment by nimya-aot** [comment]
Retry option is not working on dev-marshal when tested with @sumathi-thirumani-aot .Will test after fixing

**Comment by nimya-aot** [comment]
It is working as expected on dev-marshal by making server down and verifying the "Retry" option. So closing it
