### ISSUE TITLE
iCalendar with attachment is not getting converted

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3612]
**Describe the bug in current situation**

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/e68090bb-ebbf-4169-9eb6-e3c54bd9a670)If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nimya-aot** [comment]
Working as expected
