### ISSUE TITLE
Intake Team Queue Update and Auto-Assign Change

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3621]
Title of ticket: 

#### Description
As Intake is becoming a single entity, we need to consolidate the queue view to support the change.

To manage this, we should make it such that the view of the queue for the Intake team matches the flex team queue.

In addition, the auto-assign on open rule should now be de-activated, as Intake will eventually be managing all CFRs across all teams and types.

Once this is done, we will move all flex team members to Intake Team

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Disable auto-assign to teams on open
- [x] Update Intake queue columns to match flex team queue columns
- [x] Add Received Date column to Intake Queue
- [x] Move Restricted Flag to be beside ID Number

**Comment by divyav-aot** [comment]
**refinement comments:**

1. keep the assignee as is. remove auto-assignment for General and Personal requests
2. Replace intake team queue with Flex team queue 
3. keep the restricted flag beside the ID Number

**Comment by lmullane** [comment]
@m-prodan, I see that @divyav-aot list from the refinement in the comment above does not include Received Date.
 
Is the Received Date still been updated as part of this ticket or is that no longer part of the DOD?

**Comment by lmullane** [comment]
Confirmed that Received Date is added as a column on the Request Queue for the Intake Team.

**Comment by lmullane** [comment]
Intake queue updates are all validated as complete:![Screenshot 2023-06-08 at 11.10.43 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/292b04b6-c5bb-46bd-9947-a306ee0971dd)
