### ISSUE TITLE
Generate Access Key , Token for each ministry buckets

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3637]
Title of ticket: 

#### Description
The purpose of this task is to create DEDICATED access token, key for each ministry bucket on DEV, TEST and PROD and develop a script to insert into corresponding DBs ( Request Management , DocReviewer)

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

#### Pre deployment
- run sql scripts uploaded to teams dev channel under folder s3accesskeys

**Comment by m-prodan** [comment]
Note: Add - list of current Ministries in system, and Ministries expected to onboard for April and May

**Comment by nkan-aot** [comment]
The list of buckets will correspond to all current production ministry codes + the ministries listed in the screenshot below. Old codes need to be included in case a closed request with an old code is reopened. If a ministry changes their code again in the future a new bucket will need to be created

cc @abin-aot @KyEggleston 

Current Production ministry codes:
[https://app.zenhub.com/files/358004325/98c11e5a-c7ba-48cb-bc72-871739e14171/download]

Ministries onboarding in April and May:
![MicrosoftTeams-image (5).png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/59bedee4-2a27-4deb-9843-7f46fc663842)

**Comment by nkan-aot** [comment]
sql scripts for updating access keys uploaded to teams channel dev under folder s3accesskeys

**Comment by m-prodan** [comment]
@nkan-aot - can you confirm that for us to QA this, we just need to ensure we can upload records as Ministry users for the list above?

**Comment by KyEggleston** [comment]
@nkan-aot - just following up on @m-prodan comment above. Is there QA required for this (e.g., test uploading records to the Records tab for these ministries)?

**Comment by KyEggleston** [comment]
Confirmed gathering records working in test-marshal (spot checked MAG, PSE and EML)
