### ISSUE TITLE
ECON Sector Dashboard - JED Requests not Showing

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3646]
**Describe the bug in current situation**
An econ sector user reached out and asked why JED requests were not showing in their dashboard.

The issue is not happening in test, and it is unknown when this issue began. 

**Link bug to the User Story**

**Impact of this bug**
Ministry users can not accurately report/see their requests in Redash

**Chance of Occurring (high/)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to combined ECON sector dashboard
2. Try to filter to JED requests

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
This issue was raised to me by the new ED over at ECON sector.

cc: @lmullane @abin-aot @KyEggleston

**Comment by KyEggleston** [comment]
@m-prodan - I believe I resolved this, and confirm when you're back. Able to filter by JED now, and all widgets include JED requests now (assuming filter Ministry= 'All' OR Ministry= 'JED'). 

![image](https://user-images.githubusercontent.com/117312323/232162548-5dc13f75-c531-4e80-bd25-ed59f063396c.png)

![image](https://user-images.githubusercontent.com/117312323/232163371-43be0115-a1d4-490b-a36e-8617412d7612.png)

cc: @abin-aot @lmullane

**Comment by m-prodan** [comment]
Closing ticket as it appears to be working as expected again - thanks @KyEggleston
