### ISSUE TITLE
CORS handling - set up Origin of access

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#365]
Title of ticket: 

#### Description
Enables CORs on API side. Means, by implementing this technical design/component only required parties will call API endpoints(origins). we are doing this to restrict data hijacking and implement security for data in transit 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Implement a CORs framework,
- [x] Configure the origins comma separated, since there can be multiple callers fro same origins
- [x] Unit Testing [This to be covered from web unit testing and basic health check invocation exists.]

**Comment by sumathi-thirumani-aot** [comment]
Analysis in progress.

**Comment by sumathi-thirumani-aot** [comment]
Implementation approach:
Usage of library: Flask CORS
MUST: In the .env configure all allowed domains as comma separated.
Logic: The configured comma separated value of domains is translated as list and passed to extension decorator @cross_origin
