### ISSUE TITLE
Redaction Boxes: make the default setting translucent

### ISSUE THREAD

**Issue by liseandtea** [bcgov/foi-flow#3652]
* As an IAO analyst or peer reviewer
* I want a redaction box in the redline to be translucent 
* so I can easily see what information is being withheld or released. 

**Assumptions & Scope**	
What are the assumptions for this story?

User feedback is that CFD team wants and currently has translucent redaction.

This would be the default for all users, when they place their cursor on a redaction box, the content will appear translucent. This will allow user to see a 'preview' of the content under the redaction, without it being fully opaque / not visible. 

Currently the defaults are:

- When the cursor is placed on page WithHeld in Full, the page turns white: 

![image](https://github.com/bcgov/foi-flow/assets/117312323/3a15b21e-f263-439a-a29c-dc8d1cc33e71)

- When the cursor is placed within a redaction box (i.e. Partial Disclosure), the box turns white:

![image](https://github.com/bcgov/foi-flow/assets/117312323/e9bd3e1f-1860-436d-8470-9e89f5c5139c)

What is IN scope?

Translucent being the default fill.

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Partial Disclosure Redaction Box**
* GIVEN an IAO analyst is on a page where there is a redaction box(es)
* WHEN the user places their cursor within the box
* THEN the text within the redaction box will be displayed with a translucent appearance

**Scenario 2: Withheld in Full Redaction**
* GIVEN an analyst is on a page has a box for WithHeld in Full
* WHEN the user places their cursor within the box
* THEN the text within the redaction box will be displayed with a translucent appearance

**Scenario 3: Move cursor out of box**
* GIVEN an IAO analyst is on a page where there is a redaction box(es)
* AND the analyst has placed their cursor in the box
* WHEN the analyst removes the cursor from within the box
* THEN the text will appear with it's usual appearance![Screenshot 2023-04-14 at 11.32.39 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/9987ed59-2a14-47c9-acf8-cc236ec6df12)

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket and make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well-articulated User Story?
2. [ ] Is there Acceptance Criteria that cover all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, that passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by liseandtea** [comment]
@lmullane @KyEggleston @m-prodan let me know if I missed anything!

**Comment by lmullane** [comment]
Hi @liseandtea, I updated the AC to reflect that the fill is only visible after the redaction is complete. Let me know if I missed anything?

cc @KyEggleston

**Comment by KyEggleston** [comment]
Just added a note that the existing functionality of changing the fill for a single redaction (i.e., when you have the redaction box selected, and you select the paint icon -> fill) will remain the same. It will not affect other redactions. It will only change the fill for the selected redaction. 

We will also just need to determine what opacity level (0 -1.0) is best for users - for familiarity sake, we can probably just take the opacity property used in AXIS (assuming this works for users).

**Comment by m-prodan** [comment]
From refinement: Create separate bug ticket, estimate 5 to address full page redaction issue

**Comment by m-prodan** [comment]
@lmullane @JHarrietha-AOT @KyEggleston - note that this is listed in the Miro board for the release - did we for sure scope it in/out?

**Comment by KyEggleston** [comment]
Check if this resolves - #4358

**Comment by nkan-aot** [comment]
standup 9/1/2023 - translucent is not possible without a feature request to pdftron, agreed that disabling the white on hover is sufficient for now. reducing estimate to 3, can create new ticket in the future if translucent comes up again

**Comment by KyEggleston** [comment]
Test #4358 when this is in QA

**Comment by liseandtea** [comment]
@m-prodan @lmullane @KyEggleston 
While this functionality works, it is transparent not translucent. We need to update the title of this ticket and write a new one. Thoughts?

Translucent:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXVSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6db41fc3f9ba615ebd6f85926c64f8c9f6f63d18/Translucent.jpg)

Transparent:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXlSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0d70c637777f4f3921de3b3a0184c73c4f1b720f/Transparent.jpg)

**Comment by liseandtea** [comment]
@m-prodan @lmullane @KyEggleston 
Kyle filled me in on the transparent/translucent conversation that happened while I was away. I have updated this ticket to reflect that it is transparent that was qa'ed. All stories pass. 

For Nick's note, I think we should proceed with opeing a ticket with the vendor. Translucent is a tool that is needed.
