### ISSUE TITLE
Issue while submitting request on FOI Request form!

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3657]
**Describe the bug in current situation**
 @arielleandrews reported a bug (or from an end user!) that while submitting PERSONAL REQUESTS with only option for  `Your records as a child from a child protection investigation` checked, then after inputing `FOI Request description ` under ` /personal/childprotectionchild/description-timeframe` , then pressing on `continue` is not taking user to review page to `SUBMIT` entire request, rather its going back to start page. 

**Link bug to the User Story**

**Impact of this bug**
Unable to submit PERSONAL request with option `Your records as a child from a child protection investigation` checked - (only that particular one!) 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
Confirmed fixed in Test.

@abin-aot - when can this be released to Prod? do we need to add this to an existing Prod release or can we make a hot fix release? 

cc: @m-prodan @lmullane

**Comment by m-prodan** [comment]
Added release and closing - good to go to prod @abin-aot
