### ISSUE TITLE
Handling JWT - Authentication

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#366]
Title of ticket: 

#### Description
This task will implement JWT tokens on API , which is passed from Front end. Based on the token, roles further steps will be done, Say, authorization,  storing auditing(updated by, created by) info to DB. API updates can 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Handle JWT Tokens
- [x] Validate and Authenticate Token
- [x] Refine existing authorization check for members to use flas-jwt-oidc.
- [x] Unit tests

**Comment by abin-aot** [comment]
Re-estimated to 5 .

**Comment by sumathi-thirumani-aot** [comment]
Leverages flask-jwt-oidc for authentication.
