### ISSUE TITLE
Update size limit for attachments for harms

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#3665]
#### Description
 After harms assessment, Ministry coordinator can upload files to Attachment tag can mark them as "harms".

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Size limit of attachments for harms is 2GB
- [x] User can upload multiple files
- [x] Use toast library to show uploading progress
- [ ] 
- [ ]

#### Pre-Deployment Steps
 - add OSS_S3_CHUNK_SIZE env var/comfig map to web and api

**Comment by richard-aot** [comment]
@m-prodan , I have a question regarding the allowed file types for Attachment log.

There are some file types accepted in Attachment log, which are not allowed in Gathering Record, and vice versa. Shall I make Attachment log and Gathering Record accept all of the file types in below lists? Thanks.

Gathering Records not accepting:
xlt, xla, dot, bmp, gif, jpeg, svg, svgz, tiff, webp, xlsm

Attachment log not accepting:
json, shx, shp, dbf, kml, kmz, geojson, cpg, prj, sbn, sbx,
gml, gdb, freelist, atx, gpkg, mbtiles, mpk, wkt, las, lasd,
laz, dwf, dwg, dxf, csv, txt, ppt, pptx

**Comment by m-prodan** [comment]
Hi @richard-aot - sure - lets standardize the attachment types across both

**Comment by richard-aot** [comment]
Cool. Thanks, @m-prodan

**Comment by KyEggleston** [comment]
Tested on EDU-345-5 - confirmed toast, 2gb cap, multiple file upload, and updated accepted file types.
