### ISSUE TITLE
Upload PPT to Records Log

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3666]
Title of ticket: 

#### Description
Summarize issue 

PPTs are sometimes part of the records package. Need to support upload and marking of the PPT as an incompatible file type.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] PPT can be uploaded to Records log
- [ ] Mark PPT as incompatible file type
- [ ] 
- [ ] 
- [ ]

**Comment by KyEggleston** [comment]
Confirmed working, and works with other records gathering functionality (e.g., harms package download, deduplicate, etc.)
