### ISSUE TITLE
PDF Stitch Numbering issue

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3670]
Title of ticket: 

#### Description
There are 2 issues related to numbering.
1. The Numbers are showing in different order after Page number 15/20
2. Some of the PDFs, the Page number is not visible

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by nimya-aot** [comment]
Working as expected so closing the ticket
