### ISSUE TITLE
Sticky Memory issue with PDF Stitch

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3671]
Title of ticket: 

#### Description
The memory is not coming down once the stitching is over

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by m-prodan** [comment]
From stand up today - please add estimate to this ticket
