### ISSUE TITLE
Document Review Web App updates on UX, performance optimization

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3694]
Title of ticket: 

#### Description
When a requeust having hundreds of files, that are heavy we need measure the performance of UX, Front end and Client side  memory utilization. Technically, there can be multiple child tasks spliting given estimate - not a single task, hence a bulk estimate!! There are CASES that involves REDACTING, REDLINING all documents in a single GO and Saving it - There are high chances of issues here!! Design / Arch updates ??

Note - this likely needs to be split up in smaller tickets. This is essentially a load test for the records review to ensure we understand the performance as we try to simulate a live environment. 

#### Dependencies
Are there any dependencies?
 The request on test-marshal for this ticket is EDU-2023-1319
 https://test-reviewer-web-marshal.apps.silver.devops.gov.bc.ca/foi/558

#### DOD
- [x] Analyze, Prepare stats on current state on FOI Doc Reviewer for bulk actions - Search(Comments, Content) , REDLINE SAVE, RESPONSE 
- [x]  Decide on the stats and go forward!
- [ ] 
- [ ]

**Comment by lmullane** [comment]
Tentatively in Sprint June 21-July 5

**Comment by nimya-aot** [comment]
Needs to fix this issue as its happening for a large number of pages in the package https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4244

**Comment by nimya-aot** [comment]
Section search not working on  10k pages
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/1eaddc98-1429-4c68-b5be-4b4807219529)

**Comment by richard-aot** [comment]
Did some performance tests on saving redline over test-marshal. For over 10 thousand pages (https://test-reviewer-web-marshal.apps.silver.devops.gov.bc.ca/foi/558), it took about 4 - 5 minutes to save all the redline documents to object storage.

**Comment by sumathi-thirumani-aot** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3U5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c752785dc2a094b7b438eff3eb3c61eb90317e38/image.png)

**Comment by sumathi-thirumani-aot** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWk5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8c60391e791e05b8ffc377cfd81481b5e0f2d1c7/image.png)

**Comment by sumathi-thirumani-aot** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamU5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4698c13bc9ae4d979d6dc3d20c35e2ba582d78fb/image.png)

Refer ticket

**Comment by sumathi-thirumani-aot** [comment]
This activity cannot be taken for huge files with 3X of annotations. Created tech debt 4509; to resolve before this task continues.

**Comment by abin-aot** [comment]
Occasionally getting this, need to analyze , [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTRuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2bbcc37658081c02a60e69b77664fdde61fd4b7/image.png)

**Comment by sumathi-thirumani-aot** [comment]
This request mentioned above which was not loading in test-marshal is loading now (Resolution as part of 4509) https://test-reviewer-web-marshal.apps.silver.devops.gov.bc.ca/foi/558 (10878 pages in 42 seconds)

**Comment by abin-aot** [comment]
Observation#2 : Error on Zipper Service POD/ or with any POD that talks with Notification REDIS or service . [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVl1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38f4d854982e4336c3952b0731a599cd0642a926/image.png)

**Comment by milosdes** [comment]
test-marshal request with 1000 files, 1 page each with text only:
https://test-reviewer-web-marshal.apps.silver.devops.gov.bc.ca/foi/681
docreviewer takes a very long time to load, I haven't been able to actually load it yet. Browser runs really slowly when tab is open as well, and chrome dev tools become nearly unresponsive.

**Comment by antsand** [comment]
I got @milosdes link to load - https://test-reviewer-web-marshal.apps.silver.devops.gov.bc.ca/foi/681
But it took hours...

**Comment by milosdes** [comment]
Some more testing with simple text-only pdf files. It looks like docreviewer breaks if there are more than 999 files??

Loading times:
100 files - takes about 30 seconds to load.
200 files - just under a minute
400 files - under two minutes
800 files - about 5 minutes
999 files - 7 minutes
1001 files - error and does not load 

Other notes:
When it gets close to 1000 files, clicking on the "records" tab, it takes a few seconds to load files, and shows "No records are available to list, please confirm whether records are uploaded or not" while loading.

**Comment by nkan-aot** [comment]
I am having similar issues with docviewer (over 1000 files does not load) however there are no console errors for me and it is still loading fine in the records tab in foi flow. This is using test-marshal

**Comment by Aman-Hundal** [comment]
500 pdf files with simple text (created with the script milos sent) -> took 3.5 to 4mins to load. No errors or anything so far. Will edit this message if any future errors are found.

**Link to request:
https://test-reviewer-web-marshal.apps.silver.devops.gov.bc.ca/foi/688**

**Comment by milosdes** [comment]
I tried loading the same request a three times with removing/adding files to change from 999 to 1001, and each time was able to load it with 999 files, and got the error with 1001 files, so it looks like that is indeed causing an issue. 

In general, I'm thinking that it might make sense to combine single-page pdf files at some point in the upload process. Performance between 100 or 200 files vs 900 seems to be quite drastic.

**Comment by abin-aot** [comment]
https://test-marshal-foirequest.apps.silver.devops.gov.bc.ca/foi/foirequests/689/ministryrequest/689, or EDU-2023-12101643 on TEST-Marshal, uploaded ~3000 pdf records with only 1 page , size of 2KB each, means less than 4MB in total. Seems like Document count is problem, lets see with @nkan-aot PR merge to Test-marshal

**Comment by nimya-aot** [comment]
For this request that Aman created https://test-reviewer-web-marshal.apps.silver.devops.gov.bc.ca/foi/688 redaction box is missing on the page if we select from the left panel.(500 pages as 500 individual document)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78f027f4e1923e5a4b0f744de4e68c7ab6e70086/image.png)

**Comment by nimya-aot** [comment]
If we have more than 10 k pages, then getting unresponsive message and also 'Total pages' is blank.
[Uploading... image.png]

**Comment by abin-aot** [comment]
To Summarize, 

The first level of performance optimization and bench marking of Document Reviewer web has been done and its been decided to go ahead with this level of loading time. ie around 2 minutes for a request with 235 files uploaded, that has 1000 pages and 148 MB size in total. Refer this request, https://test-marshal-foirequest.apps.silver.devops.gov.bc.ca/foi/foirequests/655/ministryrequest/655  At the time of bench marking this was the records details
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekNOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04e75415c347567a7a9b523dd10b0e879ebc6041/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBektOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e5fe456360367c99bce1102fb7c3091e462abcf/image.png)

This load was decided and explained to the entire team on OCT-25th Sprint planning and it was decided based on the below stats from FOI FLOW after `gathering records` release and team know that this stats wont cover `CFD personals - Scanning scenario` for that we are planning an another approach of perf. optimization and there is a ticket (999+ single page doc. stitch issue) PDFTON open to get this fixed. Also, @abin-aot suggested an option to use `DOCUMENT SET` style or a kind of `PAGINATED` approach to load only a max up to 900 documents/ a max count of combination with file, page at a given point of time. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemlOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7634af66f2736c1bb73cc1da15457a1403a7ddf/image.png)

**Comment by abin-aot** [comment]
The above stats need to be reconfirmed  by @abin-aot after PDFTRON upgrade to 10.5
