### ISSUE TITLE
Conversion error happens while uploading message files(.MSG) with one of the attachment has file type (.MSG) 

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#3702]
**Describe the bug in current situation**
When a ministry coordinator try to upload a message file type having one of the attachment file type .msg file then conversion not happening for any of the files
**Link bug to the User Story**

**Impact of this bug**
Message file types with message file type attachments are not converting into pdf

**Chance of Occurring (high/medium/low/very low)**
Medium
**Pre Conditions: which Env, any pre-requisites or assumptions to execute steps?**
Test marshal
**Steps to Reproduce**
1. Login as Ministry coordinator
2. Click on records tab
3. Try to upload a message file with one of the attachment  as .msg file type
4. conversion error happens
5. No attachments are converting if one of the attachment is .msg file type

**Actual/ observed behaviour/ results**

**Expected behaviour**
All files except incompatible types are to be converted to pdf
**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/3df43401-4c0c-4cb5-92d1-74a7c8f3afb2)

**Comment by KyEggleston** [comment]
@nimya-aot - just saw this pop up in new issues and I thought it worked so I gave it a try - I didn't get an error, except when I used your file. Maybe something else within that file in particular? Just added these notes for triage.

EDU-2023-99990 in Test-Marshal

One example of .msg attached to another .msg (with other attachments)
![image](https://user-images.githubusercontent.com/117312323/234324601-d33d8627-8059-4c31-b74a-22218ad94bc1.png)

Here is a one for one, where I tested just a .msg attached to a .msg (and it was successful), and another example where I used your file.

![image](https://user-images.githubusercontent.com/117312323/234328009-910e24de-9cf0-4f7a-8b75-094b2b046f8d.png)

**Comment by nimya-aot** [comment]
@KyEggleston I noticed that this issue happens when uploading a message file with attachment as a message file (which has attachment .jpg file). Could you please check?

![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/e32424b9-7f17-4a39-b15b-184a1a7b1f3e)

![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/c58cf404-39d7-4641-aa4a-30d512cf9a65)

**Comment by KyEggleston** [comment]
@nimya-aot - will check in morning when I start if that's ok? Thanks!

**Comment by nimya-aot** [comment]
@KyEggleston ok, no problem.

**Comment by nimya-aot** [comment]
@KyEggleston ok, no problem.

**Comment by KyEggleston** [comment]
No issue with when I tested parent MSG file, with child MSG file, which has a JPG attachment in TEST:

![image](https://github.com/bcgov/foi-flow/assets/117312323/1ee16597-9028-479e-8b86-abc6c96ef878)

Also tried a couple other scenarios on this request above, but couldn't generate an error. Maybe something related to the MSG content when it's linked to a ticketing system (e.g., JIRA, Zendesk, etc.)? I see there is a nested message within the email content in your image above, so perhaps related to that? Maybe the email delimiter text? Don't have any samples at the moment, so just throwing out some thoughts.

**Comment by nimya-aot** [comment]
@KyEggleston Ok, I will check that

**Comment by nimya-aot** [comment]
This issue fixed now along with this fix.   https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/3920  So closing it
cc @KyEggleston
