### ISSUE TITLE
Regression Test - Gathering Records Release

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3713]
Title of ticket: 

#### Description
Regression Test - Gathering Records Release
When gathering records release are pushed to main branch/test, we will need to do a regression of the application to confirm functionality, including in-flight requests.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Book Meeting next week to discuss plan
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by nimya-aot** [comment]
Done regression test on test env
