### ISSUE TITLE
Incompatible file has wrong icon when file extension has upper letters

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#3715]
**Describe the bug in current situation**
When a ministry user try to upload a incompatible file with file extension in upper letters(.**KML instead of .kml**) then after uploading the file icon appears is wrong. It doesn't shows incompatible icon( **request number EDU-456-6**)

**Link bug to the User Story**

**Impact of this bug**
User unable to identify the incompatible files

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to test marshal and login as ministry user and add divisions
2. Try to upload any number of incompatible files. one with file extension in upper case letters
3. Then it wont show up as incompatible one

**Actual/ observed behaviour/ results**

**Expected behaviour**
Incompatible files has its own icon

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/4d57a707-c20e-4f06-9cf8-1814165a7e46)

**Comment by KyEggleston** [comment]
Tested on EDU-789-7 in test-marshal, and this is resolved. Closing ticket.
