### ISSUE TITLE
Email Conversion (.msg) - Sizing/Conversion Problem

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3728]
**Describe the bug in current situation**
It was observed in the records reviewer, and with the converted PDF, that email (.msg) files appear to have their resolution/sizing blown up so much that it is very difficult to read without increasing the zoom substantially (around 400%)

**Link bug to the User Story**

**Impact of this bug**
Users will be unable to easily read/review records for harms and severing

**Chance of Occurring (high)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to any request in TEST Marshal as Ministry user
2. Upload a .msg file with any amount of content in it
3. Download the converted file, or view the file in the redaction app

**Actual/ observed behaviour/ results**

**Expected behaviour**
Users should be given a readable copy of the email without having to adjust their zoom. Likely there are some issues with conversions that are increasing the margins or resolution too much.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
fyi - high priority bug found regarding email conversions and the readability of the converted product.

cc: @KyEggleston @lmullane @liseandtea @abin-aot

**Comment by liseandtea** [comment]
I tested this too on ECC-2023-39993 and got the same result Matt reported above. Only the ".msg" file types are showing up tiny. Documents that were saved and uploaded in their original formats (.doc, .xl, .pdf, .png, etc.) are downloaded as a readable size.

**Comment by KyEggleston** [comment]
Resolved - added to 7.0 release
