### ISSUE TITLE
Dependabot Critical Issues

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#3740]
Title of ticket: 

#### Description
Fix Dependabot critical Issues

#### Dependencies
Are there any dependencies?

#### DOD
FOI-FLOW
- [ ] Prototype pollution in webpack loader-utils
- [ ] Insufficient validation when decoding a Socket.IO packet
- [ ] ejs template injection vulnerability
FOI-DOCREVIEWER
- [ ] Bump System.Drawing.Common from 5.0.2 to 5.0.3 in /MCS.FOI.S3FileConversion/MCS.FOI.EMLToPDF

**Comment by aparna-aot** [comment]
Fixed Dependabot issues:
![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/e082e97e-6d98-4712-b099-4b385378fe04)

**Comment by nimya-aot** [comment]
Confirmed critical errors are not showing up on **dependabot** alerts and verified **Katalon** Reports as well. So closing the ticket
