### ISSUE TITLE
Attachment Log - Unable to Rename Attachment to start with 'CON', 'NUL' and 'PRN'

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3743]
**Describe the bug in current situation**
When renaming an attachment in the Attachment log, Mod is restricting the use of 'CON', 'NUL' and 'PRN' at the beginning of a file name (when renaming the file), even when it's used in conjunction with other characters (e.g., consult). These strings of characters are reserved in Windows, and restricted from use (when used alone) as a file name (e.g., CON.pdf). While it is unlikely a file name may start with 'NUL' or 'PRN', words starting with 'CON' are numerous. 

This is likely something we had in our file name validation check, which we do not require. We can still restrict the use of 'CON', 'NUL' and 'PRN' alone (e.g., CON.pdf, NUL.docx, etc.), but we should allow them to be used when supplemented by additional characters (e.g., consult.pdf).

**Link bug to the User Story**

**Impact of this bug**
Low

**Chance of Occurring (high/medium/low/very low)**
Medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test

**Steps to Reproduce**
1. Go to a request that has attachments in the Attachments log
2. Click on the ellipsis next to an attachment, and select to rename
3. Enter a file name starting in 'CON', 'NUL' and 'PRN' and click save
4. See error in red

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a user is on the Attachment log and renaming an attachment
WHEN the user enters a new file name starting with 'CON', 'NUL' or 'PRN'
AND the file name has additional characters entered after 'CON', 'NUL' or 'PRN'
THEN the user should be able to save the new file name

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/d74e8967-9158-4249-b4d8-b935d9e36d3a)

**Comment by KyEggleston** [comment]
@lmullane @m-prodan @liseandtea

**Comment by m-prodan** [comment]
High priority because 'CON' is a typical naming convention for IAO when uploading consults

**Comment by KyEggleston** [comment]
Passes QA - closing.
