### ISSUE TITLE
Technical Spike - Migrate MCFD Records

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3748]
Title of ticket: 

#### Description
Summarize issue 

There are a large volume of requests that need to be migrated over into the new system. 

Migration should include the records in the Correspondence Log.

Records are not organized into folders and file types.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Script to migrate over requests into Record Review
- [ ] Script to migrate records into Object Storage and the individual request Records Log.
- [ ] Folder structure
- [ ] 
- [ ]

**Comment by KyEggleston** [comment]
Handled through #4140 and #4141, closing
