### ISSUE TITLE
CFR Status - not actionable by IAO when 'In Review' for 0 dollar fees

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3749]
**Describe the bug in current situation**
A bug was observed where the CFR form status is unable to be actioned by IAO, if the fee estimate total is 0 dollars.

See EDU-2023-34093 in Test for example of bug. 

**Link bug to the User Story**
#2194 

**Impact of this bug**
low - Ministry users should not be sending 0 dollar fee estimates

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a general request as a Ministry user
2. Enter a fee for 0 dollars (search/locating 3 or lower)
3. Save CFR form and update state to fee estimate
4. Login as IAO user and go to request
5. Check CFR Form Status

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN a request is in the Fee Estimate state
AND the CFR status is in Review with IAO
WHEN an IAO user looks at the CFR form
THEN the CFR Status will be active

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
Two ways we could handle this - we could make it such that the Ministry can NOT move request to fee estimate if fee total is 0 dollars - OR we enable the dropdown.

**Comment by KyEggleston** [comment]
#3128 and #3338 are duplicate tickets of this ticket.

**Comment by m-prodan** [comment]
As discussed - original story #2194

**Comment by m-prodan** [comment]
Working as expected now - thank you @Aman-Hundal !

Note for patch notes - if CFR form gets shifted back to Clarification, and the Ministry user revises down to a 0 dollar fee estimate, the status is locked. This might be fine for now, as it would indicate there is no fee at that point. When the Ministry user updates it to over 0 dollars, the status becomes active again.
