### ISSUE TITLE
Dismiss All Notifications - Warning

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3757]
* As a user
* I want a warning to appear if I click dismiss all notifications 
* so that I do not inadvertently clear all notifications

**Assumptions & Scope**	
This story stems from feedback we heard around users accidentally dismissing all notifications. The lack of a warning, can result in unintended consequences for a user, and it is difficult to recall which requests had notifications.

What is IN scope?
Updating dismiss all notifications function

**Acceptance Criteria**	

**Scenario 1: Notifications - Dismiss All**
* GIVEN a user has activated their notification panel
* AND there are notifications
* WHEN they click 'Dismiss All'
* THEN a modal will appear with the following message: "Are you sure you want to dismiss all notifications? This is irreversible."
* AND there will be two options as buttons showing: "Continue" and "Cancel"

**Scenario 2: Dismiss All Notifications - Continue**
* GIVEN a user is on the dismiss all notifications modal
* WHEN they click Continue
* THEN the modal will close
* AND all active notifications will clear for the user

**Scenario 3: Dismiss All Notifications - Cancel**
* GIVEN a user is on the dismiss all notifications modal
* WHEN they click Cancel
* THEN the modal will close
* AND all active notifications will remain for the user

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@lmullane user story for refinement as discussed

cc @liseandtea @KyEggleston

**Comment by lmullane** [comment]
All AC passed for both 'My Notifications' and 'Watching Notifications.' Great job, @aparna-aot! 

cc @m-prodan
