### ISSUE TITLE
Reminder Notifications - Post to Request History

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3761]
* As a user
* I want to confirm that a reminder has been sent, by seeing it posted in the request history 
* so that I know the other user has been notified

**Assumptions & Scope**	
This story is meant to cover off any notification around due date reminders, to ensure they are logged as part of the request history. This is an important part of the audit trail and is a feature requested by users.

What is IN scope?
Any reminder related notification will be posted to the request history portion of the application

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: System Sends Reminder Notification**
* GIVEN a request has a due date associated with it
* WHEN the notification is sent to assigned users for that due date
* THEN the notification comment will also be posted to the request history as a system generated comment

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
Testing on EDU-2022-113355 - but must wait for tomorrow to confirm (can't spoof date or force notification on my end)

**Comment by KyEggleston** [comment]
Divisional due dates are showing up in the Request History Comments - however, I assume we also want CFR and LDD due dates be posted as well? To confirm.

**Comment by aparna-aot** [comment]
Yes @KyEggleston. CFR & LDD due dates also should be posted.

**Comment by KyEggleston** [comment]
Thanks @aparna-aot - found some requests to confirm notifications for CFR and LDD are posted (as I couldn't backdate or spoof a date to test). Closing ticket.
