### ISSUE TITLE
Update total upload size limit for records for harms

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#3768]
* As a ministry coordinator
* I want the system to stop  the upload of records for a request that in total are 2GB or more
* so that do not upload records only to find that I cannot download the Harms later

**Assumptions & Scope**	

Gathering Records feature does not handle large files (2GB or greater). The processing of records follow these steps:

1. Removal of duplicates
2. Conversion to PDF
3. Stitch PDF into consolidated PDF for each division tagged
4. Zip PDF(s) and incompatible files into a ZIP file for download onto the user's desktop

Currently, the Gathering Records file cannot support the create of ZIP files that are greater than 2 GB.

As a result, we need to stop the user from uploading records packages that are greater than 2GB, and instead redirect them to use the current process (i.e. LAN, Intella).

What is IN scope?
- Capturing the size of a records package in the DB for the request.
- Blocking the upload of a batch of records that exceeds the 2GB limit
-  Blocking the upload of a batch when the batch about to be uploaded, and a previous batch(es) uploaded, exceed the 2GB limit.

#### DOD
- [x] Limit the total upload size for records to 2 GB.
- [x] Create a new env variable for configuring the total size limit.
- [x] Avoid duplicate files while calculating the total file size already uploaded.
- [x] Add an error message on the modal once limit exceeds - Need wording.

#### Deployment Steps
- set REACT_APP_TOTAL_RECORDS_UPLOAD_LIMIT env config for web

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Batch limit of 2GB exceeded**
* GIVEN the user is on the upload records modal
* AND the user select 1 (1 tag maximum) tag for the new uploads: Division A, Division B, etc.
* AND the user has uploaded file(s) 
* WHEN the total file size of the batch is  greater than 2GB
* THEN a warning will show "A maximum 2GB or records can be uploaded per request. Please load the records for this request onto the LAN and notify IAO by updating the request state to Deduplication and posting a comment in the request."
* AND the 'Continue' button will be disabled.

**Scenario 2: Request record limit of 2GB exceeded**
* GIVEN the user is on the upload records modal
* AND the user select 1 (1 tag maximum) tag for the new uploads: Division A, Division B, etc.
* AND other batches for the request have already been uploaded 
* AND the user has uploaded file(s) 
* WHEN the total file size of the batch and previous batches is greater than 2GB
* THEN a warning will show "A maximum 2GB or records can be uploaded per request. Please load the records for this request onto the LAN and notify IAO by updating the request state to Deduplication and posting a comment in the request."
* AND the 'Continue' button will be disabled.

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/831805474
Click on 2nd Request ID from the top to see expected view on hover

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by aparna-aot** [comment]
@m-prodan @lmullane Can you update the error message to be shown on Frontend?

**Comment by aparna-aot** [comment]
Total Limit & Already uploaded record size design : 
![Size limit.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/20c4ca91-c965-417d-afde-cd8cd0c64b40)

**Comment by nimya-aot** [comment]
Working as expected

**Comment by nimya-aot** [comment]
@aparna-aot There was an issue if we try to upload a small file and a large file. Then system removes the large files(since it exceeds the 2 Gb limit), but user is unable to proceed with small file![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/901b7b22-4a37-4e85-8c7f-e22107397e78)

**Comment by nimya-aot** [comment]
small issue with showing the uploading limit as @Gb and allowing more files in the attachment modal  ![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/1979fa31-e174-470c-9658-f251e74d45b1) will test after @aparna-aot fixing that

**Comment by nimya-aot** [comment]
Needs to mention that some times after file conversion total size goes beyond 2 GB(like .0001GB ), but it wont allow user to add more files later. So closing the ticket. @m-prodan @lmullane ![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/47b5aac9-6069-45eb-942e-a6b4f961bf48)
