### ISSUE TITLE
Records Review - Allow other users to modify redactions

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3779]
* As an IAO analyst
* I want to be able to modify existing redactions by other analysts
* so that I don't need to duplicate work if a file is re-assigned to me

**Assumptions & Scope**	
This story reflects the need for the document reviewer to allow other IAO users to be able to modify redactions.

It is not uncommon for requests to be re-assigned, whether it be for leave coverage, or when an analyst moves on to a new job. If a file has active redlining on it, they may need to make adjustments to it, including changing sections, deleting the redaction box, or modifying it in some way. 

For other annotations, like shapes and comments - users should only be able to delete and not edit (due to the text capabilities of comments)

Currently PDFTron does not allow other users to make those changes. 

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Redaction Boxes - Changes by Other user**
* GIVEN a redaction box has been drawn by an IAO analyst
* WHEN a different IAO user logs into the records reviewer of the same request
* AND they make changes to the redaction box (eg - re-size box, change section marking)
* THEN the changes will be applied

**Scenario 2: Redaction Boxes - Deleted by Other User**
* GIVEN a redaction box has been drawn by an IAO analyst
* WHEN a different IAO user logs into the records reviewer of the same request
* AND they delete the redaction box drawn by another user
* THEN the redaction box will be removed. 

**Scenario 3: Annotations - Deleted by Other Users**
* GIVEN an annotation (shape, comment, other item etc.) has been drawn by an IAO analyst
* WHEN a different IAO user logs into the records reviewer of the same request
* AND they delete the annotation created by another user
* THEN the annotation will be removed. 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by liseandtea** [comment]
Going with 5 for now but analysis is needed which could increase or decrease - depends on PDFtron API.

**Comment by divyav-aot** [comment]
@m-prodan @lmullane Comments are editable for now. I will update that as part of #4039

**Comment by liseandtea** [comment]
Closing - All AC passes.
