### ISSUE TITLE
Create an Key cloak group for Flex Team and members(mock) - #292

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#378]
Title of ticket: 

#### Description
Create a Key cloak group for Flex team

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Creation of keycloak group for Flex team and add mock members
- [x] migrate the Flex team group creation to TEST env
- [x]  add mock team members for Flex on test and dev, who are not in Intake team

**Comment by sumathi-thirumani-aot** [comment]
Created 2 new groups: Flex Team , Processing Team.

**Comment by sumathi-thirumani-aot** [comment]
Added test users to both groups in dev and test.
