### ISSUE TITLE
Develop Assignee API endpoint (#292)

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#379]
Title of ticket: 

#### Description
development of assignee API endpoint which returns assignee list (Intake, Intake +Flex) as per the status

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Develop an Assignee Service with status as input on Method
- [x] Develop an Assignee Resource with status as route input calling above service
- [x] Configuration of the group id inside ENV VAR
- [x] Unit tests
- [x]  Update OC config.js/ENV VAR with Flex Team group id and other ENV VARs

**Comment by sumathi-thirumani-aot** [comment]
Mapping Details:
    def generalGroupMappings(self):        
        return [{"status":"Unopened", "groups":["Intake Team"]},
                {"status":"Intake In Progress","groups":["Intake Team"]},
                {"status":"Open","groups":["Intake Team","Flex Team"]},
            ]
        
    def personalGroupMappings(self):        
        return [{"status":"Unopened", "groups":["Intake Team"]},
                {"status":"Intake In Progress","groups":["Intake Team"]},
                {"status":"Open","groups":["Intake Team","Processing Team"]},
            ]

**Comment by sumathi-thirumani-aot** [comment]
URL: http://localhost:15000/api/foiassignees/{REQUEST TYPE}/{STATUS}
NOTE: Status will be formatted as lower case and remove spaces.
GET http://localhost:15000/api/foiassignees/general/open

[{"id": "8c27f200-9f3c-4242-afff-007ac70b685c", "name": "Flex Team", "members": [{"id":
"1fccd14f-dfb8-4e3c-bcf8-6d340eefdd89", "username": "aantony@idir", "email": "abin.antony@gov.bc.ca", "firstname":
"Abin", "lastname": "Antony"}, {"id": "2b3f3231-0cbd-4946-bf9e-b672bfcb4a2a", "username": "mprodan@idir", "email":
"matthew.prodan@gov.bc.ca", "firstname": "Matthew", "lastname": "Prodan"}, {"id":
"764c85a4-882b-45ff-b779-7aa86b838a0f", "username": "sumathi", "email": "sumathi.thirumani@aot-technologies.com",
"firstname": "Sumathi", "lastname": "T"}, {"id": "21e85a2b-8b5c-4860-8539-7e3f024e5238", "username": "suthirum@idir",
"email": "sumathi.thirumani@gov.bc.ca", "firstname": "Sumathi", "lastname": "Thirumani"}]}, {"id":
"e215497c-4214-4970-be32-3c3119164637", "name": "Intake Team", "members": [{"id":
"0388946d-4cfe-4f93-bbce-447c1ef3ac1e", "username": "aandrews@idir", "email": "arielle.andrews@gov.bc.ca", "firstname":
"Arielle", "lastname": "Andrews"}, {"id": "1fccd14f-dfb8-4e3c-bcf8-6d340eefdd89", "username": "aantony@idir", "email":
"abin.antony@gov.bc.ca", "firstname": "Abin", "lastname": "Antony"}, {"id": "07f8117e-3054-45cb-8ec8-d453dc60f793",
"username": "dviswana@idir", "email": "divya.viswanath@gov.bc.ca", "firstname": "Divya", "lastname": "Viswanath"},
{"id": "f7f55496-4e54-405a-b9f7-f1d0d3ff33b7", "username": "jharriet@idir", "email": "jacklyn.harrietha@gov.bc.ca",
"firstname": "Jacklyn", "lastname": "Harrietha"}, {"id": "fe1d571e-9bef-46dd-9052-564ad6069a66", "username":
"mpilchar@idir", "email": "molly.pilchar@gov.bc.ca", "firstname": "Molly", "lastname": "Pilchar"}, {"id":
"21e85a2b-8b5c-4860-8539-7e3f024e5238", "username": "suthirum@idir", "email": "sumathi.thirumani@gov.bc.ca",
"firstname": "Sumathi", "lastname": "Thirumani"}]}]

**Comment by sumathi-thirumani-aot** [comment]
We don't need maintenance of env property and there is a potential chance of leveraging camunda decisions for mapping.

**Comment by sumathi-thirumani-aot** [comment]
To get all groups and members : http://localhost:15000/api/foiassignees
Sample Response:
[{"id": "8c27f200-9f3c-4242-afff-007ac70b685c", "name": "Flex Team", "members": [{"id":
"1fccd14f-dfb8-4e3c-bcf8-6d340eefdd89", "username": "aantony@idir", "email": "abin.antony@gov.bc.ca", "firstname":
"Abin", "lastname": "Antony"}, {"id": "2b3f3231-0cbd-4946-bf9e-b672bfcb4a2a", "username": "mprodan@idir", "email":
"matthew.prodan@gov.bc.ca", "firstname": "Matthew", "lastname": "Prodan"}, {"id":
"764c85a4-882b-45ff-b779-7aa86b838a0f", "username": "sumathi", "email": "sumathi.thirumani@aot-technologies.com",
"firstname": "Sumathi", "lastname": "T"}, {"id": "21e85a2b-8b5c-4860-8539-7e3f024e5238", "username": "suthirum@idir",
"email": "sumathi.thirumani@gov.bc.ca", "firstname": "Sumathi", "lastname": "Thirumani"}]}, {"id":
"e215497c-4214-4970-be32-3c3119164637", "name": "Intake Team", "members": [{"id":
"0388946d-4cfe-4f93-bbce-447c1ef3ac1e", "username": "aandrews@idir", "email": "arielle.andrews@gov.bc.ca", "firstname":
"Arielle", "lastname": "Andrews"}, {"id": "1fccd14f-dfb8-4e3c-bcf8-6d340eefdd89", "username": "aantony@idir", "email":
"abin.antony@gov.bc.ca", "firstname": "Abin", "lastname": "Antony"}, {"id": "07f8117e-3054-45cb-8ec8-d453dc60f793",
"username": "dviswana@idir", "email": "divya.viswanath@gov.bc.ca", "firstname": "Divya", "lastname": "Viswanath"},
{"id": "f7f55496-4e54-405a-b9f7-f1d0d3ff33b7", "username": "jharriet@idir", "email": "jacklyn.harrietha@gov.bc.ca",
"firstname": "Jacklyn", "lastname": "Harrietha"}, {"id": "fe1d571e-9bef-46dd-9052-564ad6069a66", "username":
"mpilchar@idir", "email": "molly.pilchar@gov.bc.ca", "firstname": "Molly", "lastname": "Pilchar"}, {"id":
"21e85a2b-8b5c-4860-8539-7e3f024e5238", "username": "suthirum@idir", "email": "sumathi.thirumani@gov.bc.ca",
"firstname": "Sumathi", "lastname": "Thirumani"}]}, {"id": "05519234-c9dc-41de-bd88-0d3de47cc1fe", "name": "Processing
Team", "members": [{"id": "07f8117e-3054-45cb-8ec8-d453dc60f793", "username": "dviswana@idir", "email":
"divya.viswanath@gov.bc.ca", "firstname": "Divya", "lastname": "Viswanath"}, {"id":
"962d3f1d-1edb-4df9-b812-b39a75484e9e", "username": "lmullane@idir", "email": "loren.mullane@gov.bc.ca", "firstname":
"Loren", "lastname": "Mullane"}, {"id": "764c85a4-882b-45ff-b779-7aa86b838a0f", "username": "sumathi", "email":
"sumathi.thirumani@aot-technologies.com", "firstname": "Sumathi", "lastname": "T"}]}]
