### ISSUE TITLE
Incompatible files shows up on Error tab

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#3794]
**Describe the bug in current situation**
Incompatible files showing up on "Errors"  tab

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test -marshal
**Steps to Reproduce**
1. Go to request EDU-2023-1442
2. Go to records tab
3. Click on errors tab
4. Incompatible files also showing up there

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/5ae2f6d6-12d1-48c2-ae75-21aa6420437a)

**Comment by KyEggleston** [comment]
Confirmed this is fixed in test-marshal. Added to 7.0 release. Closing.
