### ISSUE TITLE
Architecture Context Diagram

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#38]
- [ ] Technical meeting
- [ ] Context diagram for solution
- [ ] PO approval

Maps overall solutions for file processing and conversion and webform database and que management.

DOD:
Inflows and outflows

Dependencies?

**Comment by sumathi-thirumani-aot** [comment]
Representation is expected to give clarity on
1. What are the new software components + changes coming in new platform
2. How the personas get benefited
3. Scope of the new solution + identify automation areas + system optimization.
