### ISSUE TITLE
Update POST, GET API to capturing Flex team assignment -(#292)

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#381]
Title of ticket: 

#### Description
This task is intended to update or for development changes on new Flex team assignments, Group Column implementation for both POST and GET

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Model Update with new group column, nullable, migrations
- [x] Mapping need to added on the Service level for POST, GET
- [x] Updates to GET API, Service of the request with group implementation
- [x] Unit tests

**Comment by sumathi-thirumani-aot** [comment]
Property "assignedGroup" introduced in raw request and FOI ministry table.

Changes on listed resources and services,
1. RawRequest
2. FOIRequest
3. dashboard
