### ISSUE TITLE
Update WF to assign the Open FOI request to Flex Team/Keycloak group(#292)

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#382]
Title of ticket: 

#### Description
This task is to accommodate changes to Camunda WorkFlow in relation  with Flex group assignment and individual flex team assignment 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Unclaim and reclaim with group only
- [x] Unclaim and reclaim with group and assignee

**Comment by sumathi-thirumani-aot** [comment]
Updated Raw Request Processing:
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/5790c28a-6ec9-407f-92bd-9caf32bddd0d)

**Comment by sumathi-thirumani-aot** [comment]
Updated API Handler
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/0c1dfce1-c257-46fa-a49e-cb77123249ac)
