### ISSUE TITLE
Event Queue

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3820]
* As a ministry coordinator or IAO analyst
* I want a queues to track all events for my assigned, watched and team requests
* so that I can easily view what is happening with requests and prioritize what actions I need to take

**Assumptions & Scope**	
What are the assumptions for this story?

Every user - ministry coordinator, IAO team - will have the same columns in their Event Queue.

Each event will a separate row in the event queue. There will likely be multiple events for each request listed.

Events are the same as what are already posted as a notification or comment: state changes, user comments, replies to comments, LDD and CFR due date notifications, fee payment notifications, etc. 

All events captured as notifications and comments will appear in the Event Queue.

All column date will be searchable. For example:
-  a user could go to My Team's Requests and search in the search bar by assignee (John Smith) to find all of the events with John Smith's assigned requests.
-  a user could do a keyword search of the event (e.g. harms); only one keyword at time.

What is IN scope?
An event queue for users to easily track events.
Character limit for events.

What is NOT in scope?
Task reminders
Bread crumbs for searches will be in another story.
Sorting the event queue is covered in #3821
Hover over for event that exceed character limit #3822

**Acceptance Criteria**	

**Scenario 1: Event Queue**
* GIVEN a ministry coordinator or IAO analyst is logged in
* WHEN they are on the home page
* THEN they will see three options: Request Queue, Event Queue and Advanced Search
* AND Request Queue will be the default
* https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/clgo696n228ja017k8nmvcje0/play

**Scenario 2: Click Event Queue**
* GIVEN a ministry coordinator or IAO analyst is on the Request Queue or Advanced Search
* WHEN they click Event Queue
* THEN the Event Queue will open on the My Requests (the default)
* AND up to 100 events will be listed by default
* AND requests in the 'Closed' state will not appear
* https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/clgo696n228jb017ke4vzhyx4/play
* AND there will a search bar
* AND there will be filters for 'My Requests, My Team's Requests, Watching Requests
* AND columns left to right: date, time stamp, ID-Number, From, To, Assignee, Event

**Scenario 3: My Requests Event Queue**
* GIVEN a ministry coordinator or IAO analyst is assigned to a request
* WHEN they are on their My Requests Event Queue
* THEN they will see all events for the requests assigned to them
* AND the most recent event by date/time stamp will appear at the top
* AND the oldest event by date/time stamp will appear at the bottom
* AND 100 events will be listed by default per page
* AND they will even see events that occurred on the request before it was assigned to them

**Scenario 4: My Team's Requests Event Queue**
* GIVEN a request is assigned to one of their team members or to their team
* WHEN a ministry coordinator or IAO analyst is on their My Team's Requests Event Queue
* THEN they will see all events for the requests assigned to their team
* AND the most recent event by date/time stamp will appear at the top
* AND the oldest event by date/time stamp will appear at the bottom
* AND 100 events will be listed by default per page
* AND they will even see events that occurred on the request before it was assigned to their team member or team

**Scenario 5: Watching Requests Event Queue**
* GIVEN a ministry coordinator or IAO analyst is watching a request
* WHEN they are on their Watching Requests Event Queue
* THEN they will see all events for the requests they are watching
* AND the most recent event by date/time stamp will appear at the top
* AND the oldest event by date/time stamp will appear at the bottom
* AND 100 events will be listed by default per page
* AND they will even see events that occurred on the request before they started watching the request

**Scenario 6: Click a User Comments Event**
* GIVEN a ministry coordinator or IAO analyst is on any Event Queue
* WHEN they click on the row for a User Comment event
* THEN they be redirected to the User Comments Log for that request 

**Scenario 7: Click any Event that is not a user comment**
* GIVEN a ministry coordinator or IAO analyst is on any Event Queue
* WHEN they click on the row for the event
* THEN they be redirected to the Request View for that request 

**Scenario 8: Meets character limit**
* GIVEN a ministry coordinator, IAO analyst or FOI Mod system posts a comment
* WHEN the comment is below the character limit of xx
* AND the screen is normal resolution
* THEN the entire event will be displayed in the event column

**Scenario 9: Exceeds character limit**
* GIVEN a ministry coordinator, IAO analyst or FOI Mod system posts a comment
* WHEN the comment is above the character limit of xx
* THEN the first xx characters of the event will be displayed in the event column
* AND a "..." will displayed to signify that there is more to review

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team's backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, @liseandtea, @KyEggleston, @JHarrietha-AOT  

For your review. Please see the related stories under the Epic as well: #3821, #3822.

What should be the character limit for an event to be displayed in full?

**Comment by KyEggleston** [comment]
- Do we want the same functionality as the 'Your FOI Request Queue', where if you hover over the Request # the full description is displayed in a tooltip? This came up a few time when we showed the event queue design (the ability to see request descriptions).

- In addition, similar to the request description being displayed in a tooltip when hovering over a Request # in your queue, if the comment exceeds the character limit, do we want the ability to hover over the comment to see the full comment? 

- Assumption - the 'Assignee' column is specific to the type of user that is on the event queue. E.g., if an IAO user is on the event queue, the IAO assignee for the request will be displayed under the 'Assignee' column. Alternatively, if a ministry user is on the event queue, the 'Assignee' column will show the ministry assignee.

- Do we need the 'Assignee' column under 'My Requests' for the event queue? It's already implied all the events will have that user as the assignee, and may take up real estate (which could instead display more of the comment/event).

**Comment by lmullane** [comment]
Good points, @KyEggleston. 

- I have the hover over for long comments in #3822 but could also include the hover over for request description.
- Good catch. The assignee should list the assigned ministry coordinator on the ministry queue and the assigned IAO analyst on the IAO queue
- True, but not sure what we use the space for instead? More development effort to have them different (i.e. no assignee) so would need a benefit.

**Comment by lmullane** [comment]
Events for Closed requests should be retained in case the request is reopened.

**Comment by divyav-aot** [comment]
**refinement comments:**
1. only user comments will redirect to the comments tab with default filter. All other events will redirect to request tab
2. No need to add the notification types column
3. Do not delete any notification irrespective of state

**Comment by m-prodan** [comment]
As discussed from stand-up - adding a column for "to" to provide added context for situations where multiple people may receive the same notification.

**Comment by sumathi-thirumani-aot** [comment]
Supported Date format (Search):
**Example:  2023 Jun 15**
- 2023 Jun 15
-         2023 Jun
-         Jun 15
-         2023
-         Jun
-         15

**Comment by divyav-aot** [comment]
As discussed, if a request created with multiple ministries and it is moved to open state then we will show multiple rows different ID NUMBER in the Event Queue. When you click on the request, it will redirect to the request review page with latest STATE selected.
@m-prodan @lmullane @sumathi-thirumani-aot

**Comment by lmullane** [comment]
Hi @divyav-aot, @sumathi-thirumani-aot 

This is looking good so far!

One bug to note - the search results seems to be variable. One of the use cases is to search for an assigned user, in event that person is away, to see events on their assigned requests.

When I search on an assignee name on the My Team's Requests in the Request Queue I see multiple assigned requests:![Screenshot 2023-06-19 at 2.43.39 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/b37f0236-96d8-4035-bfba-8b53587c0cb7)

I would expect even more rows returned on the Event Queue. But when I search on the same assignee name on the My Team's Requests in the Event Queue I see only one row:![Screenshot 2023-06-19 at 3.03.28 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/7101282c-3312-4086-a758-3ec27d03e1a2)

But when I search with a truncated assignee name on the My Team's Requests in the Event Queue I see many rows!:![Screenshot 2023-06-19 at 3.08.14 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/9b1d6692-fc9e-43bc-81c8-b6914414b32f)

I also see requests that show up in a search on the Request Queue but not the Event Queue, or searches for assignee names that produce no results.

Let me know how we can resolve these search issues.

**Comment by lmullane** [comment]
Another question for you @divyav-aot. What is the character limit we are using for events (aka Scenario 9)?

**Comment by lmullane** [comment]
One change required for the Bread Crumbs. 

Given I am an IAO user, when I navigate from the Event Queue to a request listed on the Event Queue, then the breadcrumb reads 'Event Queue':![Screenshot 2023-06-19 at 4.50.18 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/2f5856e4-ce20-48a9-af70-f3d90d0671b4)

Given I am a ministry user, when I navigate from the Event Queue to a request listed on the Event Queue, then the breadcrumb reads 'Request Queue':![Screenshot 2023-06-19 at 4.47.35 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/21de786f-b405-4a4c-b1e9-c74282dbb382)

Both breadcrumbs return the user to the Event Queue, so just a minor wording change so the ministry user also sees 'Event Queue' as the breadcrumb.

**Comment by lmullane** [comment]
It appears that not all assigned requests are appearing on the Event Queue.

For example, this request is assigned to me and appears in My Requests on the Request Queue:![Screenshot 2023-06-19 at 5.12.02 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/0160d893-b665-46d9-867c-954f91c2d262) 

The same request does not appear on My Requests in the Event Queue:![Screenshot 2023-06-19 at 5.11.47 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/8d428eee-01fb-401d-9159-00e0e169c51a)

**Comment by divyav-aot** [comment]
Thanks @lmullane for the feedback. We will look into the issues and update you back. 
for scenario 9, I added the limit as 50 characters.

**Comment by lmullane** [comment]
Thanks, @divyav-aot. Scenario 5 has failed in my initial tests. The Watching Queue for events is not being populated.

**Comment by divyav-aot** [comment]
As discussed, tagged comments/events will be shown as part of My Request in the Event Queue. Specially this applies when the tagged user is not part of the request (meaning, not assigned to, not watching and not part of the team)
@m-prodan @lmullane @sumathi-thirumani-aot @abin-aot

**Comment by m-prodan** [comment]
for clarity - if a user is not assigned to the request, only the tagged comments will appear under my requests as an event, any replies associated with it will not.

**Comment by divyav-aot** [comment]
@m-prodan @lmullane - we have a query regarding ministry event queue. Do we need to show the events before CFR in ministry event queue? for example, "Moved to Open State".

**Comment by m-prodan** [comment]
At that point (pre-CFR) - there's nothing really of value (for the most part) from the Ministry's perspective on events that have happened prior to CFR. What I would say is - if its more work to make sure they see (or not see) those events, let's not account for that and get user feedback after it is in production.

Thoughts on this @lmullane ?

**Comment by m-prodan** [comment]
Note for testing: can be tested now, but load testing also occurring. Consider testing from the user experience perspective, think about what they will be using it for and how easy it will be to find those details.

**Comment by liseandtea** [comment]
@sumathi-thirumani-aot Hello! all AC passes however there is one minor tweak for Scenario 2 "AND columns left to right: date, time stamp, ID-Number, From, To, Assignee, **Event**"  In Mod, EVENT is listed as CONTENT.

**Comment by liseandtea** [comment]
@sumathi-thirumani-aot @divyav-aot all AC passes however there is one minor tweak for Scenario 2. It states "AND columns left to right: date, time stamp, ID-Number, From, To, Assignee, _Event_" In Mod, **EVENT** is listed as **CONTENT**.

![image.png](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/e43eb376-2b6c-4af2-900c-9995610b18ad)
