### ISSUE TITLE
Sort Event Queue

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3821]
* As any user
* I want sort any Event Queue
* so that the columns will all sort ascending and descending

**Assumptions & Scope**	
What are the assumptions for this story?

Sort for the Event Queue will work the same as for the Request Queue.

What is IN scope?
Sorting columns on the event queue
Changing the number of events listed on a page

What is NOT in scope?
#2267 covers the sort for the Request Queue and Advanced Sort
**Acceptance Criteria**	

**Scenario 1:**
* GIVEN any user is on any queue in the Event Queue
* WHEN they click on the column the 1st time
* THEN the column will sort ascending

**Scenario 2:**
* GIVEN any user is on any queue in the Event Queue
* WHEN they click the column a 2nd time
* THEN the column will sort descending 

**Scenario 3: Option to change number of items in queue displayed**
*GIVEN the user is the Event Queue
*WHEN the user clicks on the arrow next to 100 results (the default)
*THEN the user will have an option to select other result amounts as well (10, 25, 50 100)
- DESIGN needed - 

**Scenario 4: Change number of items in queue displayed**
*GIVEN the user has opened the options to select other result amounts as well (10, 25, 50 100)
*WHEN the user clicks on an option (e.g. 25)
*THEN the number of events listed per page will change (e.g. 25)
- DESIGN needed -

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
Thoughts on a date picker, to further narrow down their results, rather than only having the option to sort date/time ASC or DESC? Trying to think of use cases for this, but it just came to mind.

**Comment by lmullane** [comment]
Could see that working, but not sure if is needed?

**Comment by lmullane** [comment]
All AC passed.

**Comment by liseandtea** [comment]
@divyav-aot Scenarios 3 and 4 do not pass

Scenario 3 states: "*THEN the user will have an option to select other result amounts as well (50, 100, 200, 300)"
Scenario 4 states:* GIVEN the user has opened the options to select other result amounts as well (50, 100, 200, 300)
*WHEN the user clicks on an option (e.g. 200)
*THEN the number of events listed per page will change (e.g. 200)

I cannot cannot complete these because drop-down menu amounts show 10, 25, 50 100.

![image.png](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/d2110449-14d0-4b3f-a20f-61f7c99d2bbe)

**Comment by KyEggleston** [comment]
Confirmed the event per page filter should be 10, 25, 50 100. 

Updated ACs. @nimya-aot

**Comment by lmullane** [comment]
Closing as complete.

**Comment by KyEggleston** [comment]
Note - search in Event Queue searches across all pages, not just the current page. This functionality should persist in the future, and should be checked if updated made to event queue
