### ISSUE TITLE
Hover over for events that exceed character limit

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3822]
* As a user
* I want to see the the full event for a request when I hover my cursor over the event 
* so that I can more easily differentiate and prioritize the requests in my queue

**Assumptions & Scope**	
* Applies to all event queues 
* Some user comments may exceed the character limit for what can displayed
* Full text of the event will display 

What is IN scope?
* Displaying and collapsing the event when hovering the cursor

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Move cursor over event**
* GIVEN I am a user on an event queue
* AND an event exceeds the character limit
* WHEN I move my cursor over the event 
* THEN a display window will appear that displays the full event 

**Scenario 2: Move cursor off event**
* GIVEN the cursor is hovered over the event
* WHEN I move the cursor off the event to anywhere else on the page 
* THEN the display window will disappear 

**Scenario 3: Move cursor over request ID Number**
* GIVEN I am a user on the Event Queue
* WHEN I move my cursor over the ID Number for a request 
* THEN a display window will appear that displays the full request description for that request
* AND the text window will also display the date range for the request at the end of the request description in parentheses e.g. This is the request description (Jan 1 2021 to Jan 31 2021) 

**Scenario 4: Move cursor off request ID Number**
* GIVEN the cursor is hovered over the ID number for a request
* WHEN I move the cursor off the ID number to anywhere else on the page 
* THEN the display window will disappear 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
Will include hover over for request description.

**Comment by lmullane** [comment]
Hi @divyav-aot , in the comments this ticket was going to include the hover over on the REQUEST ID to view the REQUEST DESCRIPTION.

Could we add that?

cc @aparna-aot

**Comment by divyav-aot** [comment]
Yes @lmullane . We can add that as well. Please add a scenario for the Request Description. Thanks!

**Comment by lmullane** [comment]
Thanks, @divyav-aot. I've added 2 scenarios for the Request Description hover over.

**Comment by liseandtea** [comment]
Closing: All AC passes

**Comment by liseandtea** [comment]
Closing: All AC passes in TEST
