### ISSUE TITLE
Analyze and Prioritize ACS and Dependabot Issues in DocumentReviewer web, api and computingservices (depupe, conversion etc)

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3834]
Title of ticket: 

#### Description
Summarize issue 
https://github.com/bcgov/foi-flow/security/dependabot?page=1&q=is%3Aopen

#### Dependencies
Are there any dependencies?

#### In scope

1.  DocumentReviewer web, api 
2.  computingservices (depupe, conversion , pdf stiching, zipper etc)

#### Out of scope

- FormsFlow.ai components analysis is not in scope for 9.0
- FOI WEB, Request management API , Angular apps(FOI REQUEST Submission)

#### DOD
- [x] Analyze issues
- [x]  Breakdown into small workable tasks as per module, component and use case
- [x]  Prioritize as per the condition
- [ ]  

Expectation is like we need to have a set of workable items!

**Comment by liseandtea** [comment]
Only for FOI-Flow the other ones will need a task created and a new estimate/priority.  We need to think about the fixes (high, medium, low) and prioritize the fixes.

**Comment by KyEggleston** [comment]
Duplicate of #3394?

**Comment by abin-aot** [comment]
@KyEggleston - Yes its a duplicate(kind of!)

**Comment by abin-aot** [comment]
@lmullane : Just to confirm, we are expected to complete all these Dependabot issues and ACS fixes (#4347, #4348)  **before** Release 9.0 , Right ?

cc: @m-prodan  , @sumathi-thirumani-aot  , @divyav-aot , @aparna-aot , @richard-aot , @nkan-aot , @KyEggleston

**Comment by aparna-aot** [comment]
@abin-aot  : After analyzing the ACS reports, it seems like addressing the vulnerabilities will require a gradual approach as the reports lack definitive solutions, such as upgrading a specific package to fix a particular issue. Instead, we might need to take an experimental approach, testing upgrades for certain libraries to their latest versions and recheck the reports.
To do this, we'll need to add upgrade commands for specific libraries / packages sourced from artifacts into the Dockerfiles of each image. This could lead to significant changes in the Dockerfiles, making them more complex & time consuming which requires thorough testing as well.
As a quick fix to mitigate some of these issues, we can consider upgrading all our Docker images to their latest versions and then re-evaluate the ACS report for which we have a task created already (#4559) .

**Comment by abin-aot** [comment]
Yes, that makes sense! Hence there is no one or two definitive solution to fix the TRUE vulnerabilities, lets try upgrading images one by one as per its availability BC GOV artificatory and see the  how ACS reports are highlighting the upgrade. Also, under a FALSE positive is another challenge! so by this effort we are concluding the Analysis of ACS reported issues . Also, we will be meeting Nick C from  Security side and conveying our strategy. ! cc: @lmullane , @m-prodan

**Comment by abin-aot** [comment]
All analysis tasks are over , created required upgrade tasks, meetings will be scheduled with Operations Teams/ Nick Cocoran  as per the comment above. hence closing! cc: @lmullane , @m-prodan

**Comment by abin-aot** [comment]
On 23-OCT-2022, a meeting happened between happened with Nick C (Security Architect) , @m-prodan , @aparna-aot , Avneet and @abin-aot . Below are the points we summarized

1.  The  `Top CVSS Score` marked in RED , can be ignored,  because fixing the libraries at the container / image level is cumbersome, since upgrading those libraries on a DOCKERFILE can cause other issues. 
2.  Only possible fixable issues need to be fixed, Nick indicated try to follow an `N-2` rule for image version, where `N` is the major version of the libraries. 
3.  Public facing Apps takes more priority over Backend / internal API or services.
4.  Participants agreed like the ACS dashboard issues are a moving target and fixes to those are as per priority . 
5.  
cc: @lmullane
