### ISSUE TITLE
Data loss happens for fillable pdfs during pdf stiching

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#3835]
**Describe the bug in current situation**
When a filled pdf uploaded on records tab and try to download harms after pdf stitching, it loss data  inside the pdf document

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
test env

**Steps to Reproduce**
1. Go to records tab for request LBR-2022-32315
2. Download the fillable PDF
3. Open the fillable PDF in Adobe or the browser and see the filled fields
4. Download the Harms Package
3. Check the downloaded document with original pdf
4. Its missing the filled data from the original pdf

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a fillable PDF is uploaded to the Records log
AND fields have been filled in the PDF
WHEN the user downloads the Harms Package
THEN the filled fields will appear in the Harms Package

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
**Original data**
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/1c818f7e-f97b-4e94-b8fc-a02b5f7ec7fa)
**After stitching**
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/7ae13b12-32e5-41d0-9404-ef7ae6eac1fe)

**Comment by lmullane** [comment]
@nimya-aot, is this bug still happening?

**Comment by nimya-aot** [comment]
@lmullane yes, its still exists

**Comment by lmullane** [comment]
Thanks, @aparna-aot 

This bug is fixed.

I tested with the fillable PDF from then Standard Testing Package and another fillable PDF.

The content from all 3 fillable PDFs, including the original, now show content in the Harms Package.
