### ISSUE TITLE
Division updates(additions of new divisions) using FOI FLOW Admin , need to Sync FOIDocumentreviewer DB as well

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3838]
Title of ticket: 

#### Description
As part of Regression testing for the release of Gathering records, its being found that Updates/ additions to Divisions on FOI FLOW DB using Admin Modules will also need to update FOI Document Reviewer DB, else Computing Services functionalities will get affected!

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by m-prodan** [comment]
Per comments on teams - I updated one of the WLRS Divisions - I didn't add or remove, just made an edit to update the name. Division was updated to 'Coastal Marine Stewardship'

cc @nkan-aot

**Comment by liseandtea** [comment]
No estimate yet because Emerald is still under discussion.

**Comment by m-prodan** [comment]
Note for this ticket - I've updated divisions for EMCR (Ministry of Emergency Management and Climate Readiness)

**Comment by KyEggleston** [comment]
Added divisions for MOE/ENV (Ministry of Environment and Climate Change Strategy). 

CARD – ADMO
CARD – Conservation Officer Service 
CARD – PSB – Exec Director
CARD – PSB – Capital Investment
CARD – PSB – Recreation Services
CARD – PSB – Visitor Services
CARD – PSB – Engagement, Education & Enhance
CARD – PSB – Conservation
CARD – PSB – Planning & Land Administration
CARD – PSB – Indigenous Relations
CARD – Recreation Sites & Trails
CARD – ROB – Exec Director
CARD – ROB – Interior Region – Kootenay/Okanagan
CARD – ROB – Interior Region – Thompson/Cariboo
CARD – ROB – Northern Region – Skeena
CARD – ROB – Northern Region – Omineca – Peace
CARD – ROB – South Coast Region – Coastal Mainland
CARD – ROB – West Coast Region – Vancouver Island
CAS – ADMO
CAS – CGB – Exec Director
CAS – CGB – Clean Investment
CAS – CGB – Industrial Reporting & Control
CAS – CGB – industrial Climate Policy
CAS – AEAB – Exec Director
CAS – AEAB – Economics & Analysis
CAS – AEAB – Climate Strategy Development
CAS – CPEB – Exec Director
CAS – CPEB – Policy Integration & Engagement
CAS – CPEB – Partnerships 
CAS – CPEB – Clean Government 
CAS – RIRB – Exec Director
CAS – RIRB – Climate Risk Management
DMO – Correspondence Unit
DMO – Deputy Minister’s Office
EPD – ADMO
EPD – CEEB – Exec Director
EPD – CEEB – Compliance & Enviro Enforcement
EPD – ESB – Exec Director
EPD – ESB – Clean Air, Integrated Pest Mgmt & Bonding
EPD – ESB – Clean Communities
EPD – ESB – Clean Technologies
EPD – ESB – Extended Producer Responsibility
EPD – EMAB – Exec Director
EPD – EMAB – Analysis & Reporting
EPD – EMAB – Environmental & Climate Monitoring
EPD – ROB – Exec Director
EPD – ROB – Authorizations – North
EPD – ROB – Authorizations – South
EPD – ROB – Monitoring, Assessment & Stewardship
EPD – ROB – Mining Operations
EPD – ROB – Digital Services
EPD – ROB – South East Coal Mining
EPD – Regulatory Effectiveness & Sector Integration
SSD – Indigenous Partnerships & Engagement
SSD – SPB – Exec Director
SSD – SPB – Legislation
SSD – SPB – Intergovernmental Relations
SSD – SPB – Planning, Evaluation & Performance Mgmt
SSD – STB – Service Transformation 
MO – Minister’s Office

**Comment by KyEggleston** [comment]
Added divisions for CFD (Ministry of Children and Family Development)

Minister’s Office
Deputy Minister’s Office
Client Relations Branch (DMO)
Finance and Corporate Services
Analytics (FCS)
Provincial Director of Child Welfare 
Partnership and Indigenous Engagement 
Service Delivery Division
Strategic Integration, Policy and Legislation
Litigation (SIPLD)
Strategic Services Branch

**Comment by m-prodan** [comment]
Note - I've tagged this as release 9.0 - changes to the DB for divisional updates will cause doc reviewer errors, this should be done prior to release, or very soon after

**Comment by KyEggleston** [comment]
**Code:**
EMLI

**Added:**
Energy Resources Division
Electricity and Utility Regulation Division
Energy Decarbonization Division
Corporate Service for the Natural Resources Sector (CSNR) 

**Updated:**
Mines, Competitiveness and Authorizations Division changed to Responsible Mining and Competitiveness Division
Strategic and Indigenous Affairs Division changed to Strategic and Indigenous Partnerships Division

**To be deleted when appropriate (there are records associated with these three divisions):**
Oil and Gas Division
LNG Canada Implementation Secretariat
Woodfibre Implementation Group

**Comment by KyEggleston** [comment]
Added:
'Corporate Management Services Branch'

Org Code:
HSG

**Comment by lmullane** [comment]
@abin-aot, is this still high priority for the 9.0 release?

Cc @KyEggleston @liseandtea

**Comment by KyEggleston** [comment]
Associated to #4183?

**Comment by abin-aot** [comment]
Yes! #4183, this ticket is related and can be concluded as duplicate . Also to indicate #4184 can be done along with this ticket @KyEggleston

**Comment by KyEggleston** [comment]
@abin-aot - are we good to link these tickets (#3838, #4183 and #4184) together, and I can close this ticket? Just want to make sure the information in this ticket isn't forgotten, especially if needed for the other tickets. Thanks!

**Comment by KyEggleston** [comment]
@Aman-Hundal @milosdes - review as part of #4183
