### ISSUE TITLE
Update all cornjobs with timeZone post May 29th

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3843]
Title of ticket: 

#### Description
The OS platform is getting upgraded to 4.12 version on May 29th. post that, we would be able to specify the timeZone in the cronjob yml.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Update the cronjob of d106d6-dev, test and prod (pod restarts)
- [ ] Update the cronjob of d7abee-test and prod (S3 backup)

**Comment by m-prodan** [comment]
closing as jobs confirmed to run at right time
