### ISSUE TITLE
Global search for keywords, redactions, comments in Records Review app

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3849]
* As an IAO analyst
* I want a global search for keyword, redactions and comments of all records in a request
* so that I can find the information I need and not miss anything

**Assumptions & Scope**	
What are the assumptions for this story?

IAO analyst need to be able to do a keyword search to find keywords in all responsive records with one search. 

The Records Review app has a keyword search and searchable comments and redactions that are requirements for Records Review. The preference is to use the UI in the Records Review app.

What is IN scope?
Global search for keywords, redactions and comments.

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Search**
* GIVEN a user is using the 'Search' pane
* WHEN the user searches for text, including using 'case sensitive' and 'whole word'
* THEN the accurate and responsive search results will be displayed

**Scenario 2: Search Comments**
* GIVEN a user is using the 'Search Comments' feature in the 'Comments' pane
* WHEN the user searches for text in comments
* THEN the accurate and responsive search results will be displayed

**Scenario 3: Redaction Panel - Search**
* GIVEN a user is using the 'Search Keyword' feature in the Redaction Panel
* WHEN the user searches for keywords in the responsive records
* THEN the accurate and responsive search results will be displayed

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
This needs ACs and testing, as technical task done.

**Comment by KyEggleston** [comment]
Will add ACs and test all search functionality

**Comment by KyEggleston** [comment]
All ACs pass
