### ISSUE TITLE
Divisional Tracking Enhancement - Combo Box

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3854]
* As a Ministry User
* I want to more easily navigate my divisions
* so that I can manage a large list of divisions

**Assumptions & Scope**	
Ministry of Forests is a very large, decentralized Ministry. At launch of the application, we ran with a high level divisional tracking view with a simple scroll and select process. Given the size and volume of divisions that are canvassed by this Ministry, and future Ministries, having an easier way to navigate the divisional tracking will be important in ease of use. 

As an example, here is a full list of Forests divisions https://bcgov.sharepoint.com/:w:/r/teams/03521/Shared%20Documents/General/Application%20Onboarding/Divisional%20Lists/Forests/NEW%20Draft%20List%20for%20FOI%20Modernization%20revised.docx?d=w6bb0b69cc17d4e4a9d106c897cc14013&csf=1&web=1&e=4Fj6qI 

By leveraging material UI's combo box feature, we believe we can deliver this more easily to the users:

https://mui.com/material-ui/react-autocomplete/

What is IN scope?
Update to the divisional tracking boxes, to allow for combo boxes

What is NOT in scope?
NO changes to other functionality  regarding divisional tracking

**Acceptance Criteria**	

**Scenario 1: Add New Division - Combo Box**
* GIVEN a Ministry user is on the request details page of a request
* WHEN they activate the division drop down
* THEN the full list of divisions will populate
* AND the division box will allow the user to enter text

**Scenario 2: Add New Division - Enter Text**
* GIVEN a Ministry has activated the division drop down
* WHEN they start adding text
* THEN the list of divisions will begin filtering based on the text entered
(example, as you start typing ''Office" - the divisional list will begin filtering to only show divisions with the word office in it)

**Scenario 3: Add New Division - Delete Text**
* GIVEN a Ministry has activated the division drop down, and have added text
* WHEN they delete the text
* THEN the list of divisions will begin revert back to default showing all

**Scenario 4: Add New Division - Make Selection**
* GIVEN a Ministry has activated the division drop down
* AND they have entered text
* OR they have left it blank
* WHEN they make a selection
* THEN the selected division will populate in the box

**Scenario 5: Divisional Stage - Combo Box**
* GIVEN a Ministry has selected a division
* WHEN they activate the divisional stage drop down
* THEN the divisional stages will appear in the drop down
* AND the division stage box will allow the user to enter text

**Scenario 6: Divisional Stage - Enter Text**
* GIVEN a Ministry has activated the divisional stage drop down
* WHEN they start adding text
* THEN the list of divisional stages will begin filtering based on the text entered
(example, as you start typing ''fee" - the divisional stage list will begin filtering to only show divisional stages with the word fee in it)

**Scenario 7: Divisional Stage - Delete Text**
* GIVEN a Ministry has activated the divisional stage drop down, and have added text
* WHEN they delete the text
* THEN the list of divisional stage will begin revert back to default showing all

**Scenario 8: Divisional Stage - Make Selection**
* GIVEN a Ministry has activated the divisional stage drop down
* AND they have entered text
* OR they have left it blank
* WHEN they make a selection
* THEN the selected divisional stage will populate in the box

**Validation Rules? (If yes, list here)**	

**Design**
Please use material UI combo box feature https://mui.com/material-ui/react-autocomplete/

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Category for Forests Tracking - could be a useful template for MCFD requirements.

cc: @JHarrietha-AOT @lmullane @KyEggleston @lmullane

**Comment by JHarrietha-AOT** [comment]
@m-prodan @lmullane @liseandtea @KyEggleston 

Here is the link to the design: https://jacklyn808742.invisionapp.com/overview/FOI---Intake-ckpq19frj032r013q6gpm8t1m/screens

Knowing how large the lists are for the categorized divisions I think the division selection box should be a combo box (https://mui.com/material-ui/react-autocomplete/) which you can see there instead of a scrolling dropdown.

Let me know if you have any questions or comments

**Comment by m-prodan** [comment]
AC updated - this will be a net benefit to all Ministries if we utilize the combo box feature of MUI. I am also including divisional stages as well for this enhancement.

**Comment by m-prodan** [comment]
Note from refinement: create separate ticket for assignments, there is a functional difference between div tracking and assignment lists

**Comment by liseandtea** [comment]
@nkan-aot Hey! In QA, scenarios 1 - 4 pass for the "select division" drop-down box (adding text etc.); however, scenarios 5 - 8 do not. I am not able to add any text to the "select division stage" box.

**Comment by nkan-aot** [comment]
apologies, i thought it was only for divisions not stages. I have created a PR to test and it is waiting for approval

**Comment by liseandtea** [comment]
@nkan-aot Thanks, Nick! It is working beautifully now :), all AC's have passed.

**Comment by liseandtea** [comment]
@nkan-aot Thanks, Nick! It is working beautifully now :), all AC's have passed.
