### ISSUE TITLE
Backend API - Changes to persist notifications [#3820]

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#3857]
DOD
=====
- [x] DB script to capture the delete "isdeleted" for unopened requests
- [x] DB script to capture the delete "isdeleted" for opened requests
- [x] Model changes to perform soft delete of record

**Comment by m-prodan** [comment]
To QA this - run through all notification scenarios and confirm with devs that notifications are being captured in back end

**Comment by m-prodan** [comment]
@nimya-aot

**Comment by nimya-aot** [comment]
Working as expected.
