### ISSUE TITLE
Request State - 'Peer Review' 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3864]
* As an IAO user
* I want the ability to change the Request Status to 'Peer Review'
* So that I can indicate when the request is being, or needs to be, peer reviewed 

**Assumptions & Scope**	
What are the assumptions for this story?

A request can be changed to the 'Peer Review' Request State from 'Intake In Progress', 'Open', 'Records Review', 'Consult', 'Response'. 

Only IAO users can change the Request State to 'Peer Review'

When a request is in the 'Peer Review' Request State, Ministry users will not be able to change the Request State (i.e., when they click the Request State dropdown, the only option will be to keep the request in 'Peer Review'). 

When a request is in the 'Peer Review' Request State, the options available in the Request State dropdown are dependent on the previous Request State (i.e., what the Request State was prior to being changed to 'Peer Review'). 

State Change notifications should be sent to all assignees and watchers on the request when it is changed to, or from, the 'Peer Review' Request State (standard with all state changes). In addition, this should be posted to the Comments tab (the same rules for notifications and comments being posted as other Request State changes). 

When a request is changed to a Request Status of 'Peer Review',  the actions available to the user depend on the previous Request State. 

When changing a request to 'Peer Review', from any other Request State, the Assignees and Watchers will remain the same. 

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Intake in Progress - Peer Review**
* GIVEN an IAO Intake user has a request in Intake in Progress
* WHEN they activate the request state drop down
* THEN they will see Options for Open, Peer Review, Redirect, and Closed

**Scenario 2: Intake in Progress - Peer Review**
* GIVEN an IAO user is on a request in Intake in Progress 
* AND the request state is activated
* WHEN they select 'Peer Review'
* THEN the change state modal will open

**Scenario 3: Peer Review Change State Modal**
* GIVEN an IAO user is on the peer review change state modal
* WHEN they select 'Save Change'
* THEN the state will update to Peer Review

**Scenario 4: Peer Review from Intake in Progress**
* GIVEN an IAO user is on a request in the Peer review state
* AND the previous state was 'Intake in Progress'
* WHEN they activate the request state dropdown
* THEN the state options they will have is: Intake in Progress, Open, Redirect, and Closed 

**Scenario 5: Open - Peer Review**
* GIVEN an IAO Intake user has a request in Open state
* WHEN they activate the request state drop down
* THEN they will see Options for Call for Records, Peer Review, and Closed

**Scenario 6: Open - Peer Review**
* GIVEN an IAO user is on a request in Open State
* AND the request state is activated
* WHEN they select 'Peer Review'
* THEN the change state modal will open

**Scenario 7: Peer Review from Open**
* GIVEN an IAO user is on a request in the Peer review state
* AND the previous state was  Open
* WHEN they activate the request state dropdown
* THEN the state options they will have is: Call for Records, Open and Closed

**Scenario 8: Records Review - Peer Review**
* GIVEN an IAO Intake user has a request in the Records Review state
* WHEN they activate the request state drop down
* THEN they will see Options for: Call for Records, Consult, Ministry Sign-Off, Peer Review, Response and Closed

**Scenario 9: Records Review - Peer Review**
* GIVEN an IAO user is on a request in Records Review
* AND the request state is activated
* WHEN they select 'Peer Review'
* THEN the change state modal will open

**Scenario 10: Peer Review from Records Review**
* GIVEN an IAO user is on a request in the Peer review state
* AND the previous state was Records Review
* WHEN they activate the request state dropdown
* THEN the state options they will have is: Call for Records, Consult, Ministry Sign Off, Records Review, Response and Closed

**Scenario 11: Consult - Peer Review**
* GIVEN an IAO Intake user has a request in the Consult state
* WHEN they activate the request state drop down
* THEN they will see Options for: Records Review, Ministry Sign Off, Peer Review and Closed

**Scenario 12: Consult - Peer Review**
* GIVEN an IAO user is on a request in Consult state
* AND the request state is activated
* WHEN they select 'Peer Review'
* THEN the change state modal will open

**Scenario 13: Peer Review from Consult**
* GIVEN an IAO user is on a request in the Peer review state
* AND the previous state was Consult
* WHEN they activate the request state dropdown
* THEN the state options they will have is: Consult, Records Review, Ministry Sign Off, and Closed

**Scenario 14: Response - Peer Review**
* GIVEN an IAO Intake user has a request in the Response state
* WHEN they activate the request state drop down
* THEN they will see Options for: Records Review, Peer Review and Closed, On Hold

**Scenario 15: Response - Peer Review**
* GIVEN an IAO user is on a request in Response
* AND the request state is activated
* WHEN they select 'Peer Review'
* THEN the change state modal will open

**Scenario 16: Peer Review from Response**
* GIVEN an IAO user is on a request in the Peer review state
* AND the previous state was Response
* WHEN they activate the request state dropdown
* THEN the state options they will have is: Records Review, Response and Closed, On Hold

**Scenario 17: Peer Review - Lock CFR Form**
* GIVEN a request is in Peer Review status
* AND the request has a CFR Form tab
* WHEN an IAO or Ministry user navigates to the CFR Form tab
* THEN the CFR Form tab will be locked for editing (i.e., the user will be unable to edit the form)
**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
@m-prodan @lmullane @liseandtea - FYI, just got this ticket started, but can complete further next week. May need some discussion.

**Comment by KyEggleston** [comment]
@m-prodan @lmullane - when a request in placed in 'Peer Review', should the users that show up under 'IAO Assignees' be all IAO users, or based on the previous request state? E.g., if we changes a request from 'Intake in Progress' -> 'Peer Review', should only Intake users be able to be assigned?

**Comment by liseandtea** [comment]
Who needs to see a request when it goes into the peer review state will be dependent on the action being taken. For example, if an analyst is moving it into the peer review state prior to the request moving into sign off then they need to be able to assign it to their team lead (or whomever on their team does the peer reviewing). So, I think much like we can assign requests now, where the currently assigned team's list defaults to the top and then you can see the rest of IAO, would probably work here too.

**Comment by KyEggleston** [comment]
@liseandtea - ok, that makes sense. So based on my example, if we're going from 'intake in Progress' -> 'Peer Review', only the Intake folks should be able to be assigned. Therefore, if it gets put back in 'Intake in Progress', or moved to 'Open, we can keep the assignee (i.e., it doesn't go into an unassigned state). This is pretty specific to 'Intake in Progress', as it's the only state where we restrict who in IAO can be assigned the request.

**Comment by KyEggleston** [comment]
In QA - test state change comments (#802) and state change notifications (#855) related to 'Peer Review' state.

**Comment by JHarrietha-AOT** [comment]
@aparna-aot Hex codes for States:

Peer Review: #096DD1
Response: #07437F

**Comment by KyEggleston** [comment]
@aparna-aot - looks like Scenarios 4, 10, 13, and 16 are failing, perhaps for similar reasons. 

All these ACs involve moving a request from 'Peer Review' back to its original state. 

For example, in scenario 4, when a request has been moved from 'Intake in Progress' to 'Peer Review', and the IAO analyst is wanting to move the request back to its previous state (i.e., Intake in Progress), this option isn't available. The only options from the 'Peer Review' state is 'Open', 'Call for Records' and 'Closed'. 

This is the same for the other three scenarios - you are unable to move the request back to its original state (whether it be 'Records Review', 'Consult' or 'Response'), and you are only given the options of 'Open', 'Call for Records' and 'Closed'. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/9f34afd1-0e35-464e-ae65-2fc7531c462f)

Scenario 7, which is moving a request from 'Peer Review' to 'Open' is correct, in that it should only show the options of 'Open', 'Call for Records' and 'Closed'. 

@m-prodan @liseandtea - one thing we may have missed is regarding the CFR Form. Should the CFR Form be locked when a request is in 'Peer Review' for both IAO and Ministry? Does it matter what previous state it was in? 

Still need to confirm state change notifications/comments.

**Comment by aparna-aot** [comment]
@KyEggleston Will check and update you. Thanks!

**Comment by KyEggleston** [comment]
@aparna-aot - additional observations (which admittedly weren't specified in original ticket):

<h2>Update 1</h2>
When a request is currently in 'Peer Review', and the request has been assigned to a ministry team or analyst (which occurs first when a request is moved to 'Call for Records'), the request is not showing up on the ministry assigned analyst's 'My Requests' queue, nor is it showing up in the 'My Team's Requests' queue for all ministry analysts for the given ministry. 

When a request has been moved to 'Call For Records' (a ministry team or analyst has been assigned the request), the request should always show up in the 'My Team's Requests' queue for analysts in the given ministry. 

If the ministry user is assigned the request, and the request is moved to 'Peer Review', the request should still appear in the ministry user's 'My Requests' queue. 

Not that if a ministry user is a watcher on a request in 'Peer Review', this does still show up in their 'Watching Requests' queue (which is correct). In addition, the request is still searchable through 'Advanced Search' by a ministry user when the request is in 'Peer Review' (which is correct).  

Ministry user assigned the request, and the request is in 'Peer Review' 
![image](https://github.com/bcgov/foi-flow/assets/117312323/beaa925d-daa6-4b8a-a2d7-bf0759c4eff5)

Doesn't show up in 'My Requests' when in 'Peer Review'
![image](https://github.com/bcgov/foi-flow/assets/117312323/c8c33355-3437-4858-85e1-6ab441172a46)

Doesn't show up in 'My Team's Requests' when in 'Peer Review'
![image](https://github.com/bcgov/foi-flow/assets/117312323/5f450ec7-3e8a-4dc1-b5bc-e771809eb559)


<h2>Update 2</h2>
When a request is moved to 'Peer Review' from either 'Records Review', 'Consult' or 'Response', the Ministry Assigned Analyst is not displaying for IAO users (i.e., as if it is no longer being actively treated as being assigned to the ministry user). This may be related to the issue in Update 1 (or the cause).

When a request is in 'Peer Review', and the request has been assigned to a ministry team or ministry analyst, the Ministry Assigned to should be displayed when a request is in 'Peer Review'. 

Below I'm logged in as IAO analyst, on a request in 'Peer Review'. Note the Ministry Assigned Analyst is not displayed. 
![image](https://github.com/bcgov/foi-flow/assets/117312323/c4ee966e-57da-40f8-9da2-52efb57489cf)

However, as a ministry analyst, when I search for the request in 'Advanced Search' and open it, I do see the Ministry Assigned Analyst. 
![image](https://github.com/bcgov/foi-flow/assets/117312323/9364ad1d-2f6d-4c3b-8346-89127d921b5f)

<h2>Update 3</h2>
When changing a request from 'Intake in Progress' -> 'Peer Review' -> 'Open', changing the request to 'Open' does not leave a comment in the Comments tab. 
<br></br>
See my terrible illustration below, where I changed a request from 'Intake in Progress' -> 'Peer Review' -> 'Open' -> 'Peer Review' -> 'Call for Records'. You can see that changing the request from 'Peer Review' to 'Open' did not leave a comment (Request History). 

![image](https://github.com/bcgov/foi-flow/assets/117312323/26c4e1ea-b24c-4b7f-ac2e-c1f9e9d2a988)

When changing a request from 'Peer Review' to 'Open', this should be included in the Comments tab. 

NOTE: All other notifications and comments related to Peer Review are working.

**Comment by KyEggleston** [comment]
As discussed in standup, the CFR Form tab will be locked for editing, for both IAO and Ministry users, when a request is in 'Peer Review'.

**Comment by KyEggleston** [comment]
Confirmed  Scenarios 4, 10, 13, and 16 are now working. In addition, Updates 1 and 2 above are resolved. Update 3 is a bug, not specific to this Peer Review ticket, logged in #4203.

**Comment by KyEggleston** [comment]
Confirmed CFR Form is now locked for IAO and ministry when in 'Peer Review'. All ACs pass, closing ticket.
