### ISSUE TITLE
Divisional Tracking Due Date Notification - Sent When Request is 'Closed' 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3865]
**Describe the bug in current situation**
On request MHA-2023-31151, which was/is in a request state of 'Closed', the assignees were sent a due date notification (Gathering Records due) that resulted from the Divisional Tracking. 

Shortly afterwards, we made a fix so IAO users do not receive Divisional Tracking-related notifications (#3537) - so this won't be an issue for IAO users. However, Ministry users will still receive Divisional Tracking notifications, and this appears to be occurring even when requests are in a Request State of 'Closed'. 

When a request is in a Request State of 'Closed', assignees and watchers should not be sent Divisional Tracking due date notifications. 

**Link bug to the User Story**

**Impact of this bug**
low

**Chance of Occurring (high/medium/low/very low)**
low

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
@sumathi-thirumani-aot - fyi for this one too

**Comment by KyEggleston** [comment]
Confirmed - closing ticket.
