### ISSUE TITLE
Request moved to 'Call For Records' - No Notification for Ministry user

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3866]
**Describe the bug in current situation**
A ministry user indicated that they are not receiving a notification when a request is moved to a Request State of 'Call For Records', and shows up in their 'My Team's Requests' queue (and the 'Ministry Assigned To' is "Unassigned"). 

I confirmed with the user that these requests weren't being picked up (assigned to someone in their team), which would subsequently remove the notification from a ministry user's notifications. 

When a request is moved to 'Call for Records' and shows up in your team queue, the ministry users for that team should be notified. 

I have confirmed this is working in Test, so if this is an issue, it may be specific to Prod. 

User stated this happened on PSA-2023-31255, on May 18, at roughly 3:09pm PST. 

**Link bug to the User Story**
#2306

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Low

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Occurring in PROD

**Steps to Reproduce**
1. As an IAO user, go to a request in the 'Open' Request State
2. Change the Request State to 'Call For Records'
3. As a ministry user for the selected ministry (i.e., the ministry the request is assigned to), do not assign the request 
4. Look under your notifications, and there should be a notification stating: "New request is in Call for Records". This is not occurring in Prod, or is occurring sporadically. 

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

Scenario 1: Automated notification for unassigned Call for Records request

GIVEN an request is in the Open state
WHEN IAO user changes the request state to CFR
THEN a notification will trigger to all ministry coordinators with the following message: "New request is in Call for Records"
AND the ministry coordinators will not yet be assigned or watchers for the request.
Scenario 2: Notifications auto-dismiss upon assignment

GIVEN a request is in the Call For Records State
AND the request is unassigned
WHEN the request is assigned to a Ministry user
THEN any notifications sent to users notifying the new request is in Call for Records that have not been dismissed, will be automatically dismissed

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
Adding to this ticket - I have heard at the Forests check-in of this same bug. 

FOR-2023-31312, and FOR-2023-31287 - both were set to CFR approximately 16 minutes apart from each other, Forests Team Lead noted they only received one notification.

**Comment by m-prodan** [comment]
@sumathi-thirumani-aot - can you look into this as part of the event queue logic/work

**Comment by KyEggleston** [comment]
Can we link this to any notification task(s) so it doesn't get lost/stale in the icebox?

**Comment by m-prodan** [comment]
Associate to notification manager, include retry logic

**Comment by KyEggleston** [comment]
@sumathi-thirumani-aot - wasn't able to look at this today, but it was reported by another ministry (CFD) today, in addition to a user (ECC) yesterday. I'm going on a limb that this was wasn't fixed with Event Queue release, and is occurring after July 20 (when we released Event Queue). Didn't have time to confirm by looking at event queue for ECC or CFD, or at the requests opened since July 20. I'm off Friday, but just in case you want to look into this. Could raise at standup and see priority with Loren.

**Comment by KyEggleston** [comment]
@sumathi-thirumani-aot - took a look more into this issue. 

For ECC and CFD, it looks like these notifications stopped on July 27. After July 27, these notifications were not being sent to ECC or CFD - it also looks like this applies to other ministries as well. We release Release 8.0.1 on July 27, so it may have reintroduced it? 

![image](https://github.com/bcgov/foi-flow/assets/117312323/fbf7a27c-9634-4b8a-a206-aa085e18e105)

**Comment by sumathi-thirumani-aot** [comment]
Newly introduced bug after events release.. Fixed

**Comment by lmullane** [comment]
This is now working as expected. Thanks, @sumathi-thirumani-aot! 

cc @m-prodan
