### ISSUE TITLE
"Download Replaced" always shows for attachments

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3875]
**Describe the bug in current situation**
On attachments in the Records tab, the ellipsis shows 'Download Replaced' available for each attachment, even when there were not replaced. This doesn't occur for the same file that was uploaded, but is not an attachment. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Records tab
2. Click on Attachment's ellipsis
3. You can see the option "Download Replaced" even though the file is not replaced

**Actual/ observed behaviour/ results**
"Download Replaced" always visible for Attachments
**Expected behaviour**
"Download Replaced" should be visible only when the file is replaced

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/8bcd2c5e-ef19-4de0-9241-ee07f775ff09)

**Comment by KyEggleston** [comment]
@abin-aot - confirmed working in test - assumption this includes disabling the 'Replace Manually'  temporarily, as I noticed it wasn't available

**Comment by abin-aot** [comment]
Thanks @KyEggleston

**Comment by m-prodan** [comment]
Working as expected now  - only observation is that when I replace an attachment, I think it should say 'Download Original' as the last option for clarity.

**Comment by m-prodan** [comment]
This was released to PROD yesterday.
