### ISSUE TITLE
Error on Signed PDF's Dedupe issue

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3901]
**Describe the bug in current situation**
Dedupe errored for 2 files for the scenario of retry. Both files belong to request "MUNI-2023-1091073454" and assigned ministry is "lrioux@idir".
Files:
271109 Metro Vancouver Signed Final.pdf
270692 Dhaliwal Signed Final.pdf
Reason:
pypdf.errors.DependencyError: PyCryptodome is required for AES algorithm

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by abin-aot** [comment]
@lmullane  , @m-prodan : I created few PDF Document Digitally signed (self signed ) and Hand drawn once, both working fine. Also, Password protected throwing a different error than the above. So, I would like to see the actual file to replicate the problem. Assuming its related with Digital signature cert. or Encryption of that file - need to analyze the original file.

**Comment by m-prodan** [comment]
@abin-aot - I've been given access to the files in question. One item of interest - @KyEggleston had the request raised to him from IAO Intake team - when they downloaded the package for harms, the two files in question were included in the harms package... wondering if this might be a FE issue? I have both files on our teams site - folder can be found here: https://bcgov.sharepoint.com/:f:/t/03521/EqSiXij8BLZLpXVx1rNGlnUBGF_Sy1GqJkWvD_nFkLxb1A?e=bzNbDj

**Comment by m-prodan** [comment]
PDFs are being recognized and added to harms packages as expected.

Tried multiple scenarios, including as stand-alone files, as attachments to emails, and attachments within attachments - no fail cases.

Used the original files that threw the errors, as replication is difficult.
