### ISSUE TITLE
Download for Harms - Inactive while documents processing

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3903]
* As a Ministry or IAO User
* I want to not trigger download for harms while files are still processing
* so that I can get the benefit of the full contents of the records package

**Assumptions & Scope**	
This story arised from the fact that a user uploaded a single document, and then immediately activated the download for harms.

This resulted in the original file being exported, and not the PDF'd version.

To address this and any future issues, we should disable download for harms until all in-progress files are complete.

Original story: #3421

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Files uploading/in progress**
* GIVEN a Ministry coordinator has uploaded a batch of records
* AND the batch of records is still in progress (dedupe/conversion)
* WHEN a user activates the download drop down
* THEN the download options will be greyed out

**Scenario 2: No files uploading in progress**
* GIVEN a user is on the records log
* AND there are records uploaded
* AND there is no active job uploading/processing the records (dedupe/conversion)
* WHEN a user activates the download drop down
* THEN the download for harms will be active

**Scenario 3: xxxxxx**
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
Do we need a icon or message when a user goes to select 'Download for Harms' when files are still running through dedupe and conversion (in progress)? E.g., like a warning icon/tooltip explaining the 'Download for Harms' is not available while files conversion and dedupe are in progress?

**Comment by nimya-aot** [comment]
Working as expected, so closing it
