### ISSUE TITLE
Zipping Microservice that works based on the EVENT - REDIS for package download, REDLINE, HARMS, Applicant 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3908]
Title of ticket: 

#### Description
From the observation on current PDF Stitching and Zipping operations , its evident that we can move `ZIPPING` logic to a different standalone microservice so that we can have dedicated resources allocated for zipping. 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Analyze and create/plan  JSON Producer message format, attributes for different Zipping Requirements - harms, redline and applicant package etc. - review all user stories related with Zipping - past and futuristic, if possible
- [x] Create a standalone computing services for Zipping, on the same level as Conversion, Dedupe , pdf stitching etc. - Dockerize , Typer based, REDIS Stream Consumer based on the dedicated KEY(s) - small vs large - for now.
- [x] Need to monitor it as a new JOB, related notifications
- [x]  Create / Update PRODUCER Integration for Zipping - PDFStitiching services(Harms), Any new - SAVE Redline package? 
- [x]  Build, Deployment YAML updates -
- [x] Integration testing - Analyze for inflight requests where Zipper component dont exists, plan for switch over.

**Comment by abin-aot** [comment]
Removed from sprint Jul5-Jul18, since its waiting for other tasks gate clearance to do further testing - Load , integration.

**Comment by abin-aot** [comment]
Removed from sprint Jul18-Aug1 since its waiting for other tasks gate clearance to do further testing - Load , integration.

**Comment by nimya-aot** [comment]
working as expected so closing the ticket
