### ISSUE TITLE
Replace Attachment - All Types

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3915]
**Describe the bug in current situation**
This is a continuation of #3883 - while we fixed the ability to replace attachments with PDFs, it was found to only work on certain, but not all file types - including incompatible file types. 

Confirmed that the replace works with .docx files, .xlsx files, .msg files

It does not work with incompatible file types, and it does not work so far with image files like jpgs and png (possibly others)

Overall we need to just enable replace attachments for ALL file types to give users flexibility to fix issues as they come up.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Significant impact as users may have to manually convert a number of attachments that are not yet converted automatically (eg txt files, ppt, etc.)

In addition, an incompatible file that is replaced with a PDF should no longer show as incompatible. 

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
@nkan-aot

**Comment by KyEggleston** [comment]
@nkan-aot - quickly tested in TEST on EDU-2023-1349, for variety of attachment file types (img below). However, could not replace any attachment with a PDF and have it replace the attachment, be downloadable, nor was it added to the stitched harms package All files I tried to replace show up as their native format in harms package.

![image](https://github.com/bcgov/foi-flow/assets/117312323/a28df2b5-a8d3-41a8-b637-aed083a64317)

**Comment by KyEggleston** [comment]
I also noticed (on EDU-2023-1349 in TEST) that no attachments show the option to 'Download Replaced' (incl. docx, xlsx, pdf), which is our standard option to download the replaced file that was uploaded when non-attachments are replaced manually. 

Normal file that was replaced showing 'Download Replaced'

![image](https://github.com/bcgov/foi-flow/assets/117312323/1af3608e-afb2-43c0-b697-c7222f1fd431)

This attachment (child file) below was replaced using 'Replace Attachment', but no 'Download Converted' option

![image](https://github.com/bcgov/foi-flow/assets/117312323/a3564474-896c-4bc0-9bc9-3fba1bfc2e1d)

**Comment by KyEggleston** [comment]
Waiting 'Download Replaced' update above - otherwise, this is functioning.

**Comment by KyEggleston** [comment]
Closing ticket, this passes now,
