### ISSUE TITLE
Conversion issues with MSG/Email message files related with MS Teams  collaboration notification services 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3920]
**Describe the bug in current situation**
An issue has been reported by an IAO Analyst on June 07 ,2023 mentioning there are way too many PDF pages created for an MSG file  compared with the conversion on Intella! - ~800 pages from Intella output and 1400 with our FOI MOD MSG Conversion output.  On the primary analysis by @lmullane and the analyst, its evident there are more gaps between the content /sentences on FOI MOD conversion o/p  compared with the Intella one!. Also, on FOI MOD conversion output, there are many additional attachments listed underneath with duplicate icon, but with NO  file extension specified. This particular issue has nothing to do FOI MOD, since Intella indicates attachments with no specific file extension. 

So, idea is to replicate this issue with an MSG file that is related with an MS Teams Collaboration on a MS WORD document and we need to make sure there are many contributors for that file!

Once reproduced and *ANALYZED* the extensionless attachments,  we need to eliminate or DISCARD attachments as per the findings on it. Also, we need to work HTML TABLE styles to reduce the spacing between the content lines 

**Link bug to the User Story**

**Impact of this bug**
Additional Pages on converted document creates confusion and more work for IAO FOI Analysts.

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
Avoid extra spacing and reduce pages. Discard unnecessary attachments 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
One area for a fix is to have less padding around email content as this makes the Records Package longer. Mod adds more padding then is in the original email and Intella conversions.

**Comment by abin-aot** [comment]
Whoever confirms this fix, please refer the PROD Request ` HTH-2023-31315 `  and in my personal observation  , the file ` FW_ Question 1.msg ` has padding issue between the content and the file `Pennington_ Shaina HLTH_EX replied to a comment in _DBN - Care2Talk V1 2023-03-13_.msg` - has the attachments without file extensions! - which was a MS Teams notifications. Please refer to PROD issue and confirm the fix. @lmullane , @m-prodan , @KyEggleston

**Comment by nimya-aot** [comment]
working as expected , so closing
