### ISSUE TITLE
Gathering Records - Unable to Upload PDF - PROD

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3921]
**Describe the bug in current situation**
A user has reported that they were unable to upload a PDF to the records log. Unclear why the error occurred - screenshot of the console error in the dev tool below.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
low - minimal reports of failed PDFs. PDF is not locked, and does not appear to have any objects or encryption.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/ca3c14e8-a7c5-42b3-8f90-9fa28b6accfe)

**Comment by m-prodan** [comment]
Impacted request: JED-2023-31379

**Comment by KyEggleston** [comment]
Stale bug, and records are not available on request to test. This may have been resolved through various hotfixes and patches, as it has not resurfaced. Closing.
