### ISSUE TITLE
Keep duplicate records that are attachments (Pdftron display change as part of #3744)

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3924]
Title of ticket: 

#### Description
Show the non duplicated records in pdftron. Currently the attachments also get deduped while fetching records for the pdftron.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Update or rewrite the API GetDocuments to fetch non duplicated records
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by m-prodan** [comment]
note: per discussion at stand up. Attachments to follow parent files in a listed order, nesting not required at this time.

**Comment by KyEggleston** [comment]
Confirmed working - closing.
