### ISSUE TITLE
While replacing an attachment,  replacement file's name is not showing up

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#3954]
**Describe the bug in current situation**

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-Marshal

**Steps to Reproduce**
1. Go to ministry login
2. Upload some msg records
3. Replace an attachment inside the msg file
4. After replacing ,the replacement file's name is not showing up at the frond end. Issue #1
5. Also, if replaced with the same file with all the attachment childs its not showing duplicates

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/f7e93b7e-99e8-4267-81c0-be1569d54a50)
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nimya-aot** [comment]
Adding to this ,when we replace a file, and its name change wont happen right away at the frond end  makes end user confusing for the following scenario



 when we add a duplicate file with same attachments but one of the attachment is replaced ,so it will show up as it is not duplicate
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/4101723c-eec1-4d68-930d-5a9030a17ba4)
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/d04ccd20-ba71-4c4d-8782-42f8d73b7257)

Needs to check this scenario as well once this issue fixed

**Comment by abin-aot** [comment]
@nimya-aot , On June 16th stand up - @m-prodan advised that the attachment 's filename can persist (original file name) even though it is replaced with other file with new name. So, item #4 can be removed. 

Also, point to note here is - PARENT FILE REPLACEMENT always updates the file name

**Comment by nkan-aot** [comment]
discussed on 6/15 standup, no need to change attachment filename on replace, attachment  replacement dedupe fix is not high priority since users should not be uploading identical attachments as replacement anyways
