### ISSUE TITLE
Formatting issue on pdf stich if a large image is stitched first

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#3957]
**Describe the bug in current situation**
When a large image is stitched first then following documents,(excel, docx etc) appears to be small, needs to be zoom in to see properly

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-marshal

**Steps to Reproduce**
1. request # EDU-2023-1205 on test-marshal
**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/47dac4e6-eb75-4367-8808-85933e240575)
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
To check: has been observed that a high-resolution image, regardless of where it falls, will increase the resolution of all pages following the image (not necessarily the top)

**Comment by lmullane** [comment]
We need to confirm what the impact is when these files are loaded into AXIS. Can they be read?

@liseandtea could you connect with @nimya-aot to load one of these file examples into TEST AXIS and view the document to see if it can be read?

**Comment by nimya-aot** [comment]
Connected with @liseandtea to check these files are readable or not while loading in to AXIS . So the pdf  is readable when zoom the individual pages(I thought if we need to take the print out of the whole package then  it will be problem but @liseandtea mentioned that  that will be a rare scenario) so closing the ticket
FYI @lmullane @m-prodan
