### ISSUE TITLE
Attachments list with title on Email MSG Content

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3959]
**Describe the bug in current situation**
As @lmullane indicated on 16/June , we need to list `Attachments` by its title on PDF converted file of an Email / MSG , so that user know that there are attachments on MSG/Email. 

Currently, attachments show up in the Harms Package after the parent email, but there is no visual reference for the user to know that they are are attachments to the email.

**Link bug to the User Story**

**Impact of this bug**
Users are unable to understand whether there are any attachments on the MSG./Email. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1.   Upload few MSG files with 2-3 unique attachments, upload that as part of `Gathering Records`
2.  Once successfully uploaded, and Please do `Download for Harms`
3.  Observe the MSG file content on the stitched PDFs - 
4.   See error - Unable to relate attachments with the Parent MSG

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a parent email has one or more attachments
WHEN the user views the email in the Harms Package
THEN all the attachments will be listed on the parent email

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nimya-aot** [comment]
working as expected, so closing
