### ISSUE TITLE
Create Backup container for doc-reviewer DB

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3966]
Title of ticket: 

#### Description
Create Backup container for doc-reviewer DB

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Create Backup container (Dev)
- [x] Create Backup container (Test)
- [x] Create Backup container (Prod)
- [x]  Create Upload to S3 container (Dev)
- [x] Create Upload to S3 container (Test)
- [x] Create Upload to S3 container (Prod)

**Comment by sumathi-thirumani-aot** [comment]
Needed upgrade to quay.io/fedora/postgresql-14:14
RESOLVED

**Comment by sumathi-thirumani-aot** [comment]
suspended jobs and had shut down backup containers in dev and test.

**Comment by m-prodan** [comment]
has been pushed to production
