### ISSUE TITLE
Request Description End Date Loses Value On Opening 

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#397]
**Describe the bug in current situation**
When a user creates a request, an action occurred that resulted in the end date of the request description losing part of its value and extending to all opened requests. Exact actions leading to this bug is unknown at this time. Creating this ticket for awareness/tracking purposes, and should be updated when conditions can be replicated. 

**Link bug to the User Story**
#33

**Impact of this bug**
When opening a request, end date of the request description experienced data loss, month and day no longer appeared, and it looked like "2021-mm-dd"

**Chance of Occurring (high/medium/low/very low)**

**very low - replication of bug TBD**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**TBD**

**Steps to Reproduce**
TBD

**Actual/ observed behaviour/ results**
When request was opened, end date of request description lost month and day values

**Expected behaviour**
All values, month day and year should have been shown. 

**Screenshots/ Visual Reference/ Source**
Screenshot of request description impacted:
![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/301d8500-fdb9-4ea7-8984-dcf730a40e6f)

In TEST - these requests were all opened by "Jack Daniels" - see LDB-2021-92313 as an example, all other requests by this applicant have same behaviour. Archived copy was also updated

**Comment by mpilchar** [comment]
No longer able to replicate; doesn't appear to be an issue. Closing this ticket
