### ISSUE TITLE
File Counts more than N (~ 500+) , causing timeout error or Gathering Records are not displaying records, while count > N

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3976]
**Describe the bug in current situation**
When there are Records more than 500 or  with a file count more than a certain limit above 500 , its been observed that `GATHERING RECORDS` are NOT loading . Underlying issue is related with an API called to Reviewer_API microservice and certain code operations need performance optimization / clean up

**Link bug to the User Story**

**Impact of this bug**
When records count are more than certain higher limit, entire RECORDS tab is NOT listing any records

**Chance of Occurring (high/medium/low/very low)** Medium!

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to any request
2. Upload any count of records above 500, take 500 as the lower limit we found. But for testing, we need to do  rounds like 500, 600, 800, 1200, 1500 and so on. Size does not matter! - Count is the issue here!
3.  See whether , records are listed or not. 

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by abin-aot** [comment]
Demonstrated the current performance to the business, it was taking ~15-20 secs max to load 2000 records on `GATHERING RECORDS` tab. Also,, mentioned that systems **fails** to load records more than  2200 !  To achieve best performance above this level, we need to re-engineer the code and task has been created for that purpose.  https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/3996 .

cc: @lmullane , @m-prodan , @KyEggleston , @nimya-aot , @divyav-aot

**Comment by m-prodan** [comment]
closing as released to prod last night
