### ISSUE TITLE
Replies to comments in PDF not visible

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3982]
**Describe the bug in current situation**

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Upload a PDF with a comment and a reply into FOI Mod
2. Download the same PDF from FOI Mod
3. See that the parent comment is in the PDF, but that the reply is gone
4. Download the Harms Package
5. See that the parent comment is in the PDF, but that the reply is gone

**Actual/ observed behaviour/ results**

**Screenshots/ Visual Reference/ Source**

PDF has parent comment and reply:
![Screenshot 2023-06-20 at 11.22.24 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/80469960-0918-409b-a37a-e4b7037aa323)

In FOI Mod Harms Package, the same PDF shows there has been a comment:![Screenshot 2023-06-20 at 11.27.08 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/5e79bb69-7c0a-44ea-8318-cd3e49308f0b)

When you scroll over you can see the original comment but not the reply:![Screenshot 2023-06-20 at 11.22.44 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/97aaa406-9249-40a4-aaf3-783f12542ceb)

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

* GIVEN a PDF has replies to comments
* WHEN the PDF is uploaded into FOI Mod
* THEN the replies to comments will be visible in the PDF

**Comment by KyEggleston** [comment]
This is being resolved through #4748 / #4708, or we will investigate an ideal option in #4870. Closing.
