### ISSUE TITLE
Attachment Log - Applicant Tag

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3998]
* As an IAO user
* I want to be able to upload relevant applicant-related attachments to my file, while protecting their privacy
* so that I can keep more of my relevant files in the same application

**Assumptions & Scope**	
FOI Mod will eventually replace AXIS, and we need to be able to safely store applicant related items that the Ministry should not see. This was the intention behind the "applicant" tag, but we did not fully define that story to include the Ministry protections. 

Given the larger number of users into and accessing the platform, it is important for us to ensure any inadvertent uploads can be adequately protected. (to date, messaging has been to keep applicant related items in AXIS for now).

This feature already exists with how we handle the attachment for fee estimates, but it is not working for manual uploads by IAO users..

For personal requests - this will not be an issue as the Ministry should be able to see the applicant name/info.

What is IN scope?
Ministry ability to access attachments with the applicant tag

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: File uploaded with Applicant tag - General Requests**
* GIVEN a file has been uploaded to the attachment log of aGENERAL request with the 'Applicant tag'
* WHEN a Ministry user views the attachment log of that request
* THEN any attachment with the applicant tag WILL NOT be visible or accessible by the Ministry user

**Scenario 2: File uploaded with Applicant tag - Personal Requests**
* GIVEN a file has been uploaded to the attachment log of a PERSONAL with the 'Applicant tag'
* WHEN a Ministry user views the attachment log
* THEN any attachment with the applicant tag WILL be visible and accessible by the Ministry user

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by sumathi-thirumani-aot** [comment]
Question # Visible and/or accessible 

Visible & Not accessible 
Backend -> NA
FE -> 3


Not Visible (Finalized)
Backend -> 3
FE -> NA

**Comment by KyEggleston** [comment]
Passes - closing ticket.
