### ISSUE TITLE
Tagged comments appear in My Requests Event Queue

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#4003]
* As a ministry coordinator or IAO analyst
* I want comments that I am tagged in to appear as an event in My Requests Event Queue
* so that I do not miss comments in which I am tagged

**Assumptions & Scope**	
What are the assumptions for this story?
When a user is assigned to a request they will see all event for that request on their My Requests Event Queue.

When a user is a watcher for a request they will see all event for that request on their Watching Event Queue.

When a user is tagged in a comment and they are not an assignee or a watcher for that request, the event (tagged user comment) will be displayed on the My Requests Event Queue.

The assumption is that tagged comments are important, so even though the user is not assigned to the request, the tagged comment should appear on their My Requests, the default Event Queue, so that it is not missed.

If a user is an assignee and they are tagged in a comment, the event will only appear in the My Requests queue once.

If a user is a watcher and they are tagged in a comment, the event will appear once in the Watching queue and once in the My Requests event queue.

What is IN scope?

Need to do some load testing for this story.
What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Unassigned user is tagged in a comment**
* GIVEN a user is not assigned or a watcher for a request
* WHEN the user is tagged in a comment 
* THEN the tagged comment will appear in the user's My Requests Event Queue
* AND other events unrelated to the tagged comment will not appear in the user's My Requests Event Queue

**Scenario 2: Reply to a comment where a user is tagged**
* GIVEN a user is not assigned or a watcher for a request
* AND the user is tagged in a comment 
* WHEN there is a reply to the comment where the user is tagged
* THEN the reply to the tagged comment will appear in the user's My Requests Event Queue
* AND other events unrelated to the tagged comment will not appear in the user's My Requests Event Queue

**Scenario 3: Assigned user is tagged in a comment**
* GIVEN a user is assigned but not a watcher for a request
* WHEN the user is tagged in a comment 
* THEN the tagged comment will appear in the user's My Requests Event Queue
* AND the tagged comment will only appear once in the user's My Requests Event Queue
* AND all other events for the assigned request will appear in the user's My Requests Event Queue

**Scenario 4: Unassigned user is tagged in a comment and also a watcher for the request**
* GIVEN a user is not assigned but is a watcher for a request
* WHEN the user is tagged in a comment 
* THEN the tagged comment will appear in the user's My Requests Event Queue
* AND other events unrelated to the tagged comment will not appear in the user's My Requests Event Queue
* AND the tagged comment will also appear in the user's Watching Event Queue
* AND all other events for the watched request will appear in the user's Watching Event Queue

**Scenario 5: Reply to a comment where an unassigned user is tagged and also a watcher for the request**
* GIVEN a user is not assigned but is a watcher for a request
* AND the user is tagged in a comment 
* WHEN there is a reply to the comment where the user is tagged
* THEN the reply to the tagged comment will appear in the user's My Requests Event Queue
* AND other events unrelated to the tagged comment will not appear in the user's My Requests Event Queue
* AND the tagged comment will also appear in the user's Watching Event Queue
* AND all other events for the watched request will appear in the user's Watching Event Queue
* 
**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
Hey @sumathi-thirumani-aot 

Please see the AC above and let me know if I captured everything.

**Comment by liseandtea** [comment]
Closing: all ACs pass

**Comment by liseandtea** [comment]
Closing: all ACs pass in TEST
