### ISSUE TITLE
Records Log - Nested Attachment Sort Order

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4004]
* As an IAO or Ministry user
* I want to clearly know which file is an attachment to what
* so that I can more easily see what files are connected to what

**Assumptions & Scope**	
This is connected to the bulk updates story, and includes a feature to ensure records sorting remains logical to help the user identify linked records. 

Essentially we want to ensure that records that have attachments, and those attachments also have attachments follow a similar logic as we currently do with parent-level records, where the attachments will always follow the parent. 

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: File Order - Attachments of Attachments**
* GIVEN a Ministry user has uploaded a file that has attachments
* AND one of the attachments also has attachments
* WHEN the upload and processing is complete
* THEN the files will appear in the following order: "Primary Parent - attachment(s) - sub parent - sub parent attachment(s)
* AND if the sub parent attachments also have attachments, the sorting will continue the same logic

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@nkan-aot - moving this to the top of the product backlog.... I think this is only a one-scenario kind of ticket, but let me know if you think I need to clarify or break it out further... it's a bit tough to write this one out given the fact that attachments could theoretically run many levels deep, but I've tried to capture it in that single AC

**Comment by KyEggleston** [comment]
Will have to QA next week, unless @nimya-aot you have free time tomorrow. This is slated for release 8.1, so we have some time

**Comment by nimya-aot** [comment]
@KyEggleston Yes, I can test it on tomorrow

**Comment by nimya-aot** [comment]
Working as expected, so closing it
