### ISSUE TITLE
Flag words related to legal review for analyst review

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#4008]
* As an IAO analyst
* I want common keywords related to legal reviews to be automatically flagged by the system
* so that I can review for purposes of redaction

**Assumptions & Scope**	
What are the assumptions for this story?

Use the pre-set search in the Records Review app.

All IAO analysts need the same preset keywords for purposes of reviewing legal advice.

What is IN scope?
Store pre-set keywords in database.
Automatically search records packages for keywords and flag for user review using the pre-set search feature.

Keywords are: Legal counsel, legal advice, legal advise, solicitor client privilege, privileged, lawyer, LSB, DAG, "Legal Service Branch", "Deputy Attorney General", "Legal Services Branch", litigation, privilege

Keywords are applicable for all FOI requests.

What is NOT in scope?
Load testing to ensure the performance with large number of pages and concurrent users.

**Acceptance Criteria**	

**Scenario 1: Automated search for records package**
* GIVEN a records package is loaded into the Records Log
* WHEN the analyst opens the Records Review app
* AND the records load
* THEN the preset search will automatically run to find legal keywords

**Scenario 2: Found keyword**
* GIVEN the preset search has run to find legal keywords
* WHEN keyword(s) are found
* THEN the keyword will be automatically annotated and displayed in the search results

**Scenario 3: Click Keyword**
* GIVEN keyword(s) are found
* WHEN the analyst clicks on a search result found in the right search panel 
* THEN the package will be updated to display the page with that search result

**Scenario 4: No keyword found**
* GIVEN the preset search has run to find legal keywords
* WHEN keyword(s) are NOT found
* THEN the keyword will not be automatically annotated and displayed in the search results
* 
**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@abin-aot, please review the AC and let me know if I captured how this would work correctly?

cc @m-prodan , @JHarrietha-AOT , @liseandtea , @KyEggleston

**Comment by m-prodan** [comment]
The only question I have is on scenario 2 - if this is limited to legal advice/review, then it should only be s. 14.

S. 12 (cabinet) and s. 21 (extremely sensitive third party info - not personal) will dramatically increase the number of keywords that would need to be searched. S. 21 may be too broad, but there is some keywords we could certainly manage from a s.12 perspective - which might be better reflected in a separate user story.

**Comment by lmullane** [comment]
@m-prodan , content was PC's suggestion so we could change it. 

Tagging this as high priority; would like to get this into the next sprint.

**Comment by lmullane** [comment]
Add, edit or modify will be separate story in the future.

**Comment by sumathi-thirumani-aot** [comment]
https://apryse.com/blog/redaction/automated-redaction-with-javascript

==========================================

4008 = 21 (Potential chance to be 13)
=====
Keywords -> Is it common for all program areas & Types of Requests?

Keywords maintenance -> s3, db 
(3).

Is this maintenance expected to be part of FOI Admin (DB)

FE -> Core logic

==========================================

**Comment by lmullane** [comment]
As discussed, these keywords will be saved under a 'Legal' column in the DB.

**Comment by lmullane** [comment]
@aparna-aot , do you have a PDF with the legal terms that I can use for testing?

**Comment by aparna-aot** [comment]
@lmullane Yeah. I tested the functionality with the following sample docs.:
[https://app.zenhub.com/files/358004325/6404d09b-14ce-4df1-8a88-ecbfe411a9ce/download](https://app.zenhub.com/files/358004325/6404d09b-14ce-4df1-8a88-ecbfe411a9ce/download)[https://app.zenhub.com/files/358004325/8af21fac-140d-481a-a6f0-5a43dcbeb2e0/download](https://app.zenhub.com/files/358004325/8af21fac-140d-481a-a6f0-5a43dcbeb2e0/download)

**Comment by KyEggleston** [comment]
This story/ACs pass, but may need to write separate ticket for changes to this based on feedback. (I.e., find and highlight all legal terms, apply highlight annotation, this only happens once when the request is first opened in doc reviewer).

**Comment by KyEggleston** [comment]
Closing this, as it technically passes - but new ticket will need to be created based on comment above.
