### ISSUE TITLE
Records Not Uploading on COR-2023-32090

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4011]
**Describe the bug in current situation**
User reported records are not being uploaded on COR-2023-32090 in the Records tab. 

[Link to Teams chat](https://teams.microsoft.com/l/message/19:3575f01db96a45e6b44223fc199492be@thread.tacv2/1687807321380?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be&parentMessageId=1687807321380&teamName=External%3A%20FOI%20Modernization&channelName=Alerts&createdTime=1687807321380&allowXTenantAccess=false).

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/7c0e470e-518b-43c0-beaf-32c3b28015a3)

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/e378f2d5-2e2e-45b4-b5dc-31d58e8e87b1)

**Comment by abin-aot** [comment]
Is it related with #3994 - @KyEggleston , @lmullane @m-prodan ?

**Comment by KyEggleston** [comment]
This appears to be different than #3994, as this is occurring when trying to upload large and small (4 file) packages. The initial upload on this request was large, however.

**Comment by KyEggleston** [comment]
Believe this may be related to the files they uploaded, and not Mod - waiting for confirmation with analyst.

**Comment by lmullane** [comment]
Keep us posted, @KyEggleston

**Comment by KyEggleston** [comment]
closing this ticket out. Sat with the user and confirmed this was an issue with the files, and not Mod. Looks like the error is related to them uploading zipped files. When they used the native files from their origin, this resolved the issue. All files causing issues, which we tested, were zipped.
