### ISSUE TITLE
'Replace Manually' - new file not listed in Harms Package with the Modified Date of the original file 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4018]
**Describe the bug in current situation**
It appears files that are added to the Records tab through 'Replace Manually' are not listed in Harms Package with the Modified Date of the original file. It does not appear the position of the original file is being retained in the Harms Package when a file replaces it. Instead, when a file is replaced manually, the replace file is being inserted in the harms package based on its own modified date (i.e., not the original files modified date). 

See EDU-2022-96633 in TEST. TestXLS (3).xlsx replaced the original file (which had the second oldest modified date, and showed up near the top of the harms package). The replaced file, TestXLS (3).xlsx, now appears at the end of the package, and appears to use its own modified date rather than the original file's modified date. 

This came up on FOR-2023-31027 in PROD as well, and I observed two original files uploaded, both get replaced manually, and having their position in the harms package move (to the end of the package, as their modified date was the most recent because they files were edited and reformatted prior to replacing manually). 

**Link bug to the User Story**
#3661 - see AC 15

**Impact of this bug**
Medium

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to any request that has records in the Records tab and download the Harms Package
2. Find the file that appears at the top of the Harms Package (oldest modified date)
3. Download this file (and edit if needed), and ensure the modified date is automatically updated to the current date/time
4. Replace the original file with the new file (i.e., the file with the updated modified date)
5. Download the Harms Package again, and the file will likely show up at the bottom of the Harms Package, rather than retaining the original position/modified date of the original file in the Harms Package

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherkin language. 

**Scenario 15:  Replace Manually - Conversion complete **
* GIVEN a user has clicked "Continue' to replace a file manually
* WHEN file conversion and deduplication is completed successfully
* THEN the new record will be listed with the divisional tag(s) of the original file
* AND a message will state, "Ready for Redaction"
* AND the file will be listed with the Modified Date of the original file
* AND the new record will be included in the records package chronologically by the Modified Date of the original file
* AND the record ellipsis options will be Replace Manually, Download Converted, Download Replacement, Download Original and Delete
* AND the record that was replaced will not be retained or downloadable

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
Going to go ahead and label as high-priority, if we have to do multiple replaces, it could get really tricky!

**Comment by lmullane** [comment]
Need to confirm if this is happening for all file types. May be occurring with replacement PDFs as well that do not need to be converted.

**Comment by KyEggleston** [comment]
Example in original post was primarily on .xlsx files, but this appears to also occur for PDF to PDF replace manually situations - see EDU-2022-96633 in TEST for Scanned Notes.pdf. Original file was first in harms package, and replaced file now showing at end of package.

**Comment by lmullane** [comment]
@nkan-aot I found a bug when replacing a record that had a duplicate.

I followed the "Steps to reproduce."
- I downloaded the Harms Package.
- I downloaded the record that appeared first in the Harms Package (this record had a duplicate)
- I replaced manually the record with the record I downloaded that had the new modified date

![Screenshot 2023-07-07 at 11.25.30 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/7d74f4f9-4b9c-4ccf-9c3d-f3ada4a72680)




When I replaced manually the original record with the record with the new modified date the following occurred.

- The record was not replaced

![Screenshot 2023-07-07 at 11.30.46 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/59f2d737-1e6d-4237-afbb-0a5c8ed14cb9)- 

- A new record was added to the Records Log
![Screenshot 2023-07-07 at 11.32.48 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/c1ae72c4-9755-4be3-8018-29087e7c6861)

- The new record is placed directly after the original in the new Harms Package as it is not being removed as a duplicate

![Screenshot 2023-07-07 at 11.45.56 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/a5ec49e8-2fd9-4a52-8124-38432da74c32)

**Comment by lmullane** [comment]
Moving back to In Progress for your investigation, @nkan-aot

**Comment by nkan-aot** [comment]
@lmullane i tried in both dev and test with your Policy Summary.msg and I was unable to reproduce this issue. Just to confirm the steps you took were:
1) upload Policy Summary.msg once
2) upload Policy Summary.msg again to a different division
3) replace the original Policy Summary.msg with a pdf

I also tried replacing with a pdf, docx, uploading the duplicate to same and different division but I am not getting this issue

**Comment by lmullane** [comment]
Reviewed and determined bug was likely due to a stale request. Closing as complete.
