### ISSUE TITLE
Production - Records upload successfully, but not displaying in Records tab

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4020]
**Describe the bug in current situation**
FOR-2023-31312 is not displayed records in Records tab FE - the records appear to upload successfully, but are not displayed in Records tab.

Confirmed no errors during and after upload. User noted that originally they were able to upload records to the request, but then deleted a significant number of records. Afterwards, subsequent batch uploads were getting hung up in 'Uploading File(s)' (i.e., the modal got stuck on a file and kept spinning). This occurred several times, and the user manually refreshing the browser to 'clear' the file uploads each time. NOTE - this may be related specifically to a file they were trying to upload, rather than being part of this broader issue. 

Eventually, the user was able to upload records successfully, but they aren't being displayed in Records tab. They estimated their biggest batch upload as 300 files. Total package would be approx. 600 files, and under 2gb.  

May have some relation to #3994 and #3947

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
In TEST, but can only be re-produced in production.

**Comment by divyav-aot** [comment]
Also test #3744 functionalities.

**Comment by m-prodan** [comment]
As discussed at standup - QA this against 3744, and leave in QA in progress if pass. Once 7.3.0 goes to PROD - check prod request ID, if resolved, it can be closed.

**Comment by m-prodan** [comment]
FOR-2023-31312's records are now showing, closing ticket as completed with PROD release
