### ISSUE TITLE
Divisional Ministry Coordinator

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#4026]
* As a ministry coordinator
* I want to add divisional ministry coordinators to my team
* so that I can save time communicating with them

**Assumptions & Scope**	
What are the assumptions for this story?

Currently, all communication between ministry coordinators and divisional coordinator happens outside the Mod system. Many divisional ministry coordinators keep there own Excel list of active FOI requests for their division.

Some ministry coordinators are used to forwarding CFR emails from IAO directly to the coordinators. They now need to create these emails themselves.

As a result less time is saved by:
- streamlining communication within the ministry
- reducing data entry with one source of truth

Ministry coordinators do not want divisional coordinators to have the ability to update the state of the request in Mod; only ministry coordinators should have this permission.

Divisional ministry coordinators will have the ability to update divisional tracking, upload attachments, upload records, edit digital CFRs and make comments. 

They will also be able to action restricted requested but not assign restricted requests.

What is IN scope?
Create a Keycloak group for divisional ministry coordinators.

This group will not have permission to edit the Request State (view only).

They will have access to the same ministry queue, advanced search and requests for the ministry.

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: View Request State**
* GIVEN a divisional coordinator is logged in
* WHEN the divisional coordinator is on a request view
* THEN the divisional coordinator will see the Request State
* AND the State will be greyed out (not editable)

**Scenario 2: Click on Request State**
* GIVEN a divisional coordinator is on a request view
* WHEN they click on the Request State
* THEN no drop down will open (the state will not be editable)
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
As discussed at refinement - this doesn't require additional customizations to the experience, just disabling the state. Assumption: we will make a KC group - Divisional coordinator. User will be a member of the Ministry team AND the divisional coordinator group, If a user has both roles, they will be unable to update a state on a request.

Will be re-estimated at standup on July 6

**Comment by abin-aot** [comment]
@m-prodan : Idea is NOT to create additional KC group for Divisional Coordinators, rather control it with the user level as ROLES, and/or attributes cc: @m-prodan , @divyav-aot , @sumathi-thirumani-aot

**Comment by sumathi-thirumani-aot** [comment]
As informed; Detailing the steps (Output from refinement - Very similar to Restricted"
1. Role "DivisionCoordinator" will be created under client "forms-flow-web".
2.  The above created role will be mapped to group created "Divisional Coordinator". 
3.  Users will join to the group  "Divisional Coordinator" ; so there is no need to every time search and add role.

**Comment by m-prodan** [comment]
Release label added - moving back to 'Waiting for Dev Release'

**Comment by KyEggleston** [comment]
This passes - but future tickets may be needed to enhance.
