### ISSUE TITLE
Syncfusion Ticket - Display comments/reply in converted Excel doc

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#4036]
Title of ticket: 

#### Description
Display comments/reply in converted Excel doc. Syncfusion is working on this feature will be released only by sept, 2023.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Upgrade to new version of syncfusion
- [x] Update the code based on the upgraded version
- [ ] 
- [ ] 
- [ ]

**Comment by divyav-aot** [comment]
Syncfusion has fixed this issue. reference ticket: https://support.syncfusion.com/support/tickets/475638
Documentation related to triggeredComments.
https://help.syncfusion.com/file-formats/xlsio/excel-to-pdf-conversion#convert-comments-as-displayed-in-place

**Comment by abin-aot** [comment]
Discussed with @lmullane , @m-prodan - Tagging with 9.1 release for now! . Yes, as per @divyav-aot and technical team's knowledge this is only a small effort(~ 1 day) - but temp. tagging to 9.1 and if we have time before 9.0 release we can reconsider.

**Comment by richard-aot** [comment]
Upgraded Syncfusion to 23.1.40. PrintInPlace option does not work for threaded comment, so keep using PrintSheetEnd option.

**Comment by nimya-aot** [comment]
working as expected, so closing
