### ISSUE TITLE
Document Reviewer - comment added to annotation not saving

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4045]
**Describe the bug in current situation**

In the 'Comments' pane, when you are the same user that made the annotation, you are able to enter a comment on the annotation and save. The comment then appears in red text under the annotation. (NOTE:  a 'comment' is different from a 'reply' in the the document reviewer -  this ticket is referring to a 'comment').

However, when leaving the redaction app and then returning, the comment is not saved. See screenshots below (EDU-2022-21052 in TEST)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Medium

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
TEST

**Steps to Reproduce**
1. Go to a request with records in the Records tab, and access the redaction application through the Records tab
2. Create a redaction and apply a FOIPPA section
3. In the 'Comments' pane, under the redaction annotation, add a comment and 'Save' it 
4. Exit the redaction application completely, and follows step 1 again.
5. Navigate to the 'Comments' pane, and see error where the comment is not saved (i.e., it has disappeared). 

**Actual/ observed behaviour/ results**
When entering a comment on an annotation, and then exiting the request in the redaction application and returning to it, the comment disappears. 

**Expected behaviour**

GIVEN an IAO analyst has added a comment to an annotation in the 'Comments' pane
WHEN the user clicks 'Save', thereby saving the comment
AND the user exits out of the redaction app, and returns to the request in the redaction app
THEN the comment will continue to be visible and saved in the 'Comments' pane under the annotation

**Screenshots/ Visual Reference/ Source**

Enter a 'comment' on an annotation that I have made

![image](https://github.com/bcgov/foi-flow/assets/117312323/5d3437d0-b3cc-4fe3-80c2-a3b177aa8936)

Initial comment entered and saved,  and then exited out of document reviewer

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/6693e35e-22c4-41ca-ae80-d35d70927910)

After opening the request again in the document reviewer, comment gone

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/93ec5827-9291-462b-87b8-69a4b23e472c)

**Comment by lmullane** [comment]
@KyEggleston, to update bug with steps to reproduce and expected behaviour.

Does not appear this is due to our story, but is out-of-the-box from PDFTron.

**Comment by KyEggleston** [comment]
This is resolved - closing ticket.
