### ISSUE TITLE
Document Reviewer - 'Complete' % counter can be >100%

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4047]
**Describe the bug in current situation**
When page flags are applied to pages in the document reviewer, and then the records (that have pages with page flags) are removed from the 'Records ' tab, it appears these are still being counted towards the completion percentage. This is leading to the 'Complete %' counter going above 100%. 

See EDU-2022-21052 or EDU-2022-202020 in TEST.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Low

**Chance of Occurring (high/medium/low/very low)**
Medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
TEST

**Steps to Reproduce**
1. Go to any request with records uploaded to the Records tab, and enter the redaction app
2. Add page flags to all pages in the package (i.e., so completion percentage = 100%)
3. Exit the redaction app, go back to the request and Records tab
4. Delete one file from the package, and add one file that has more pages than the deleted file
5. Go in the redaction app and add page flags for all pages on that new file
6. See the 'Complete %' counter, which should now be over 100%

**Actual/ observed behaviour/ results**

'Complete %' can exceed 100% when files with page flags are deleted from the package, and new files are added.  

**Expected behaviour**

GIVEN records have been uploaded to the Records tab
AND page flags have been applied to pages in the redaction app
WHEN records are deleted from the package, which may contain pages with page flags
AND new records are added to the request
THEN the 'Complete %' counter will update accordingly based on the new number of pages, and how many pages have a page flag which counts towards the completion %. 
AND the 'Complete %' should not exceed 100%

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

Under
![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/8887e3f9-04fc-40e2-855a-d0776141ca8d)

Over
![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/f3501eb8-3881-47c9-9728-1e8e4f62fadd)

**Comment by KyEggleston** [comment]
NOTE - for QA, test a variety of scenarios and combinations related to adding and removing files from the Records tab, and the corresponding implications in the redaction app to 'Complete %'. 

E.g., completion % is at 100%. Delete a file with 5 pages, and each page has a page flag. Then add a file to the Records tab that is 6 pages. Add a page flag to each page, and see if the 'Complete %' counter updates accordingly, and does not exceed 100%.

You can also test the reverse of the above. 

In addition, you should test situations where the 'Complete %' is not already at 100%, and then having records deleted and added and seeing if it ever exceed 100%.

**Comment by abin-aot** [comment]
@aparna-aot if you haven't started, please take only as per the release priority cc: @lmullane

**Comment by aparna-aot** [comment]
@abin-aot I haven't started as I'm currently working on #3864.

**Comment by m-prodan** [comment]
@KyEggleston - to QA as this may already be fixed

**Comment by KyEggleston** [comment]
Tested, and this has been resolved. Closing.
