### ISSUE TITLE
.MSG files not showing email body in Harms Package

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4053]
**Describe the bug in current situation**
On COR-2023-32090, multiple .msg conversions are not showing the message body in the Harms Package (however, it does show the message body when selecting 'Download Converted'. 

See pages 249 - 255 or pages 256-262 in the Harms Package as examples. When searching for these files in the Records tab, and downloading the original or converted, they do have content in the message body (but showing empty in the Harms Package). 

This will need further investigation to determine cause. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
- Go to request COR-2023-32090 in prod
- download msg file with name beginning with "UC - kitchen pay" (others may have the same problem)
- upload to a request in test
- download converted file
- message body is missing
- Note: up to business' discretion if they want to upload production data to test environment. This issue is related to specific msg files, unfortunately msg files created by devs do not have this problem

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
@lmullane @m-prodan @liseandtea

**Comment by KyEggleston** [comment]
This doesn't appear to be occurring on requests with a batch of records uploaded before June 23 - see .msg conversions, where it does retain the message body. See PSA-2023-31981 and FOR-2023-32152

**Comment by KyEggleston** [comment]
Looking for requesting with batch after July 23 with .msg files

**Comment by m-prodan** [comment]
I can't seem to replicate on test... it will be hard to know exactly which files have msg files uploaded post june 23rd to do a check. Maybe someone can run a report tomorrow to help narrow it down?

**Comment by KyEggleston** [comment]
HTH-2023-31580 has .msg files uploaded after June 23, no issues. So it may be something particular to COR-2023-32090 and the .msg files in it.

**Comment by lmullane** [comment]
@nkan-aot, please fill out the bug template, including steps to re-produce and the expected behaviour.

As noted, there is still an error - now the body of the email is showing in the converted file but on a separate page. We have a ticket open with Syncfusion.

**Comment by KyEggleston** [comment]
Message body displayed on separate page resolved this morning

@nkan-aot - I noticed that on some .msg files, the message body has an exaggerated indent. For example, see EDU-2022-21054 in TEST (images below). Matt also said it's occurring on FIN-2023-22345 

![image](https://github.com/bcgov/foi-flow/assets/117312323/7d655899-9881-4434-a754-c875e34b7cf5)
![image](https://github.com/bcgov/foi-flow/assets/117312323/ae690633-aede-47fc-b3ab-fe3c434a5d46)

Not sure if this is a side effect of the resolution, as I haven't noticed it on other files in the past. Any thoughts?

**Comment by nkan-aot** [comment]
@KyEggleston I've made a PR to main for a bandaid fix, just waiting for approval. Also made a support ticket with syncfusion to see if they can fix it.

**Comment by KyEggleston** [comment]
Retested files in question - formatting (indentation is resolved). Closing ticket.
