### ISSUE TITLE
Remove 'Redact' option in Redaction Pane 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4089]
#### Description

This is similar to #3506.

The 'Redact' option needs to be removed from the Redaction Pane, as it permanently applies a redaction, which may cause issues. This appears to be an OOTB feature, which is sufficiently addressed by the existing 'Add Mark' option. 

In addition, 'Add Mark' can be renamed to 'Add Redline'. 

In order to replicate this:

1. Go to the redaction app through a request which has records in the Records tab
2. Click on the Redaction Pane under 'Redact'
3. In the Redaction Pane, in the search field stating "Add by keyword search or patterns",  search for a keyword that appears in the record/request - you will notice 'Redact' appears as a greyed out option
4. When results appear, click the checkbox next to one or more of the keyword occurrences
5. See the 'Redact' option become available

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/b791d713-812d-4302-b5a0-c19aadd4e713)

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/23b6c7da-7b99-4a63-a261-c40188a83ac7)

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] 'Redact' option removed
- [ ] 'Add Mark' renamed to 'Add Redline'.

**Comment by lmullane** [comment]
The Redact button out-off-the box is irreversible and cannot be undone, so we want to remove this.

Add Mark is what we need to apply a section of the Act for redaction. Change 'Add Mark' to 'Redact'

**Comment by abin-aot** [comment]
Refinement comments

- Redact button can be hidden
- Add Mark will be updated to a text that business decides ( Add Red line~)

**Comment by nkan-aot** [comment]
Unfortunately Add Mark text cannot be updated. That button is dynamically generated every time a user puts focus into the redaction search bar, so we cannot set the text on page load. It is also not possible to add a focus event handler to the search bar because it is not a simple input, rather it is a custom element made of divs. There is also no existing pdftron event for on focus for the search bar.

**Comment by nkan-aot** [comment]
decreasing estimate to 1 becuase we only hide the redact button

**Comment by KyEggleston** [comment]
Resolved
