### ISSUE TITLE
Edit/Resize Redaction

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#4092]
Title of ticket: 

#### Description
Edit/Resize Redaction by creator and another user 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Handle modify action
- [ ] 
- [ ]

**Comment by m-prodan** [comment]
to be re-written as a user story

**Comment by KyEggleston** [comment]
Related to #3779 and #4086

**Comment by liseandtea** [comment]
Closing - AC passes.
