### ISSUE TITLE
Team email for applicant correspondence

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#4099]
* As an IAO analyst
* I want my team email address inserted in email templates sent to applicants
* so that the applicant can contact the team in case I am away

**Assumptions & Scope**	
What are the assumptions for this story?

Currently, email addresses inserted into email templates for applicants are the individual analyst's emails. 

Preference is to use the team's shared email address instead, as the individual analyst may be away.

Examples:
- the analyst is on the CRU team; then the email address used will be the CRU team email
- the analyst is on the Central team; then the email address used will be the Central team email

What is IN scope?
Mapping IAO users to their team's shared email address

Inserting the team email in ALL correspondence with applicants.

What is NOT in scope?
Ministry coordinators are out of scope.

**Acceptance Criteria**	

**Scenario 1: xxxxxx**
* GIVEN an IAO analyst is contacting an applicant
* WHEN the email template is generated
* AND the email template includes an email address
* THEN the email address will be the shared email address for the analyst's team
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Note - update AC for multiple team scenario (edge case)

**Comment by m-prodan** [comment]
As promised, mapping ema[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVpzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d469b945bd56ad168074981470554b024e983021/image.png)
ils to IAO teams:

* Intake Team: IAOIntakeTeam@gov.bc.ca
* Community and Health Team: FOI.SocialEducationTeam@gov.bc.ca
* Resource and Justice Team: IAOResourceTeam@gov.bc.ca
* Children and Family Team: IAOCFD.PersonalsTeam@gov.bc.ca
* Children and Education Team: IAOCFD.PersonalsTeam@gov.bc.ca
* Central and Economy Team: IAOCentralTeam@gov.bc.ca
* Open Information: Open.InfoGroup@gov.bc.ca
* Coordinated Response Unit: IAO.CoordinatedResponseUnit@gov.bc.ca

Let me know if you need anything else @antsand

**Comment by abin-aot** [comment]
Need to note , plan and execute manual steps for this ticket on PROD. Like, adding group emails to Keycloak Group attributes, Copying latest correspondence  TEMPLATES on S3 Bucket from DEV/TEST to PROD. cc: @antsand  , @divyav-aot

**Comment by nimya-aot** [comment]
@antsand Following teams emails are showing with FOI.SocialEducationTeam@gov.bc.ca email address. Could you please check?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGpjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f905f9020af67d99183ca95c15a1337c24873440/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcG5jIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5383d2319a60598294adfffaafbf197952364196/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHJjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1892d02d90e814168730e6faaababf9a629e85d5/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDdjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--14d91cabb831946a67456fccacf69255c27a9124/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXJjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dbb6f6657e1e0095797019a75cc82b41a904be09/image.png)

**Comment by nimya-aot** [comment]
@antsand For central and economy team email is wrong. could you please check? 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlhxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b1729dadaa69d40afb35ad193ebe8dc9d3eadd91/image.png)

**Comment by nimya-aot** [comment]
@antsand For central and economy team email is wrong. could you please check? 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlhxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b1729dadaa69d40afb35ad193ebe8dc9d3eadd91/image.png)

**Comment by nimya-aot** [comment]
@antsand For central and economy team email is wrong. could you please check? 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlhxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b1729dadaa69d40afb35ad193ebe8dc9d3eadd91/image.png)

**Comment by nimya-aot** [comment]
Currently scanning team, MCFD Personals Team  have no email addresses on test. @m-prodan could you please add those email addresses?

**Comment by nimya-aot** [comment]
@m-prodan confirmed on today's stand up that we dont need emails for MCFD personal team and scanning team . So closing this one as everything working as expected

**Comment by lmullane** [comment]
I was going through this ticket in prep for demo.

There appears to be a bug with the templates in the Contact Applicants Log. As noted in story #2687, an IAO user should be able to access the Fee Estimate template to send another email if the first email is lost. 

The template is not accessible:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnNVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40f33cfeceed8a38bf027415a6791c0833389916/Screenshot%202023-10-06%20at%204.14.42%20PM.png)

@m-prodan, could I confirm that IAO should be able to send another email?

**Comment by m-prodan** [comment]
Yes - we are supposed to be able to generate another email while a request is on hold to re-send the fee estimate.

**Comment by lmullane** [comment]
Thanks for the confirmation, @m-prodan. Will write a bug ticket.
