### ISSUE TITLE
Records Tab - .MSG files displaying in Unicode and HTML Tags 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4109]
**Describe the bug in current situation**
After Release 7.3.0, special characters in .MSG files are, at times, displaying in Unicode in converted files and harms packages.

It also appears that hyperlinks are displaying the HTML tags associated to them (e.g., </a>, <span>, </b>) are also being displayed in the converted files and harms package. 

See original converted files in TAC-2023-31654 in PROD as an example. 

I could not replicate this, to certain extent, in TEST on EDU-2022-00045.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

High

**Chance of Occurring (high/medium/low/very low)**

High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a request with .msg files that have been converted and deduped
2. Click on 'Download Converted' for each converted .msg file
3. Look at the email 'From', 'To', and 'CC' fields, along with email signatures, of all .msg files
4. See unicode and html tags displayed in the files

**Actual/ observed behaviour/ results**

Unicode and html tags displayed in the .msg files converted to PDF

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN email files are uploaded to the Records tab
AND successfully go through deduplication and file conversion
WHEN reviewing the converted files (whether individually or the harms package)
THEN the converted files should not display unicode or html tags

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/78c4f7e3-4980-452a-bf99-0ef93583a66f)

![image.png](https://images.zenhubusercontent.com/636ac0ea6aad1b5dd6b181ee/9a06f5d5-5352-4f6d-a47b-bc45f3e4e78f)

**Comment by nkan-aot** [comment]
Fixed the latter issue with "<" and ">" but html tags in hyperlink is still outstanding. Asked syncfusion but they are saying it is not feasible for them to fix since the rtf generated from msg body is not well formed

**Comment by KyEggleston** [comment]
Most .msg files are going into error after upload in TEST, so unable to test at the moment - may need to get looked into further. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/f7261bd8-e050-4272-a11a-196438d03315)

**Comment by KyEggleston** [comment]
Appears resolved - closed.
