### ISSUE TITLE
UX Design - Summary of Sections

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#4110]
Title of ticket: UX Design - Summary of Sections

#### Description
Pull into front end - sections applied in Redaction App to show in list. 
Visible to both Ministry and IAO Users
Only shows sections listed once - when they were applied
It is info that is needed by users when they are not actively redactions records

Section showing in "Request Details" will be independent of state - will appear once a FOIPPA section has been added in Redaction App and update accordingly - don't need repeats and will show in numbered order 

#### Dependencies
Devs will need to build and API to pull data from Redaction App into Front-End of FOI Mod
In building the API we need to see what other data we should be pulling out of Redaction App

- Sections Applied
- Consults conducted
- ? Others

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by JHarrietha-AOT** [comment]
@m-prodan @lmullane @liseandtea @KyEggleston 

Sections of Summary
Added to Request Details page in Records Review will only show sections that have been applied in Redaction App - one place for IAO or Ministries to copy sections applied into letters as needed
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/813687854

Added to Request Details in Closed as well with additional section for all Applied during Open Info sections too
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/813713061

Reach out if you have any questions or comments

Su

**Comment by m-prodan** [comment]
Thanks Jackie - I like these. I wonder if we should call it 'summary of redactions' instead? Also, I don't think it necessarily needs to be viewable by the Ministry, at least not at anytime. The only time it might make sense is Ministry sign-off and/or closed state, if they wanted a reference. I could handle that with the AC though.

**Comment by JHarrietha-AOT** [comment]
@m-prodan that name change makes sense to me, I will update the designs later today so they're are consistent
