### ISSUE TITLE
Bulk actions on pages (i.e. assign page flags)

### ISSUE THREAD

**Issue by liseandtea** [bcgov/foi-flow#4124]
* As an IAO analyst
* I want to be able to take bulk actions on pages (i.e. assign page flags)
* so that I am able to reassign page flags to a multiple pages at a single time. 

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Selecting a bulk Page Range**
* GIVEN an IAO Analyst is in the records review app, on the left-hand nav panel
* WHEN they hold shift
* THEN they can select a range of pages

**Scenario 2: Selecting bulk pages that are not in a Range**
* GIVEN an IAO Analyst is in the records review app, on the left-hand nav panel
* WHEN they hold CTRL 
* THEN they will be able to make selections on pages not necessarily in a range (e.g. 1, 2, 7 - 9, 25, 34, 48 - 50)

**Scenario 3: Selecting a page flag to a bulk range**
* GIVEN an IAO analyst has selected multiple pages on the left hand nav panel
* WHEN they right click with their mouse
* THEN the page flag menu will appear at their cursor

**Scenario 4: Applying a page flag to a bulk range**
* GIVEN an analyst has the page flag menu open
* AND they have selected a range of pages
* WHEN they have chosen a page flag to apply
* AND  those pages are active to apply a page flag
* THEN the page flag menu will close 
* AND all of the pages selected will be marked with that flag

**Scenario 5: Page Left Off Flag Inactive**
* GIVEN an analyst has selected >=2 pages using multi-select
* WHEN they have the page flag context menu open
* THEN the 'Page Left Off' flag will be inactive/disabled, and unable to be selected (as it can only be applied to one page)

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by liseandtea** [comment]
@lmullane @m-prodan @KyEggleston Feedback please!

**Comment by m-prodan** [comment]
Hi Lise - I updated this one, as I think it could be a bit more simplified. I retained your original AC's in a separate doc and can go over my thinking with you on friday.

**Comment by m-prodan** [comment]
Add AC for page left off (disable it when multiple pgs selected)

**Comment by KyEggleston** [comment]
Added AC (Scenario 5) for 'Page Left Off' disabled when multi-pages selected

**Comment by sumathi-thirumani-aot** [comment]
Assumption made that page flags selection of bulk could be across documents.
@m-prodan @KyEggleston  Please acknowledge.

**Comment by KyEggleston** [comment]
@sumathi-thirumani-aot - that's correct. You can bulk select any page(s), across multiple files - you are not confined to just one document.

**Comment by m-prodan** [comment]
Note from stand-up - when multi-selecting, only the original page selected will display. Will await user feedback to determine further enhancements.

**Comment by KyEggleston** [comment]
From standup - if selecting individual page with consult (and consultees), will show the consultees selected. If select >1 pages with consult flag, and different consultees, Consult modal will show with no consultees selected.

**Comment by nimya-aot** [comment]
It is working as expected so closing it
