### ISSUE TITLE
OCP Resource Allocation Optimization - suggestion from Jason/ Platform Team

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#4129]
Title of ticket: 

#### Description

Jason from Platform suggested us to reduce the `request` resources on our deployments. There was meeting held on July 12th and understanding is to fix resource by resource on all namespaces - d7abee-*, d106d6-*, c84b95-*, 04d1a3-* , eeced3-*

Here is the message from Jason

Hey Team,  

I’m working with Platform Services to help teams better utilize resources on the OpenShift platform. The pods in your project set d7abee are using about 5% of the CPU resources requested. When resources are requested but not used, colloquially known as “slack”, it prevents any other teams in the community from using them, limits teams on-boarding to the platform, or requires us to unnecessarily purchase additional hardware. Below are some instructions on how to identify and correct slack.

Want to meet at your convenience? Use this link to book some time. I can do a presentation on resource optimization for your team.

How to spot waste (Slack)?  

Here's a simple guide on how to identify resource waste (slack) within your project namespaces:
Open the OpenShift Web console and navigate to your dev, test, or prod namespace.
Locate the CPU graph and click on it.
Expand the graph view to cover a period of two weeks (2w), as shown in the image below (and attached).
Observe the graph closely, focusing on the blue and yellow lines.
If you notice a significant gap between the two lines, it indicates the presence of resource waste.

By following these steps, you can easily identify instances where resources are being underutilized, resulting in waste. Taking note of these gaps will help you understand where improvements can be made to optimize resource allocation and enhance efficiency.

Slack

How to better use CPU resources?  

To help eliminate waste and optimize resource allocation within your pods, here are some simple yet effective best practices:
 
Align requested CPU with usage: Ensure that the CPU resources requested by your pod (request.cpu) are no more than 1.6 times its actual usage. This allows for efficient resource utilization. Additionally, consider using “limit” values to account for occasional spikes of heavy usage. You will need to change your deployment manifets to make these changes permanent.
Focus on `limit.cpu` for performance: It's important to note that only the `limit.cpu` setting directly impacts performance. If your pods are experiencing slow performance, over-allocating `request.cpu` will not address the underlying issue.
Tailor CPU allocation for different environments: Dev and Test pods do not require provisioning on the same scale as production. Be more aggressive with the requested CPU allocation in the development and testing stages, while being slightly more generous in production.
Put unused environments to sleep: If certain environments (dev, test, tools) are no longer actively under development, consider putting them to sleep. This helps conserve resources. Instructions for this can be found in the Pro Tips section.
Set `limit.cpu` higher than `request.cpu`: To account for usage spikes, latency, or performance-related issues, it's advisable to set the `limit.cpu` noticeably higher than the `request.cpu`. As others optimize resource usage, and given our available capacity, you should consistently obtain your desired `limit.cpu` values. OpenShift will make every effort to accommodate the `limit.cpu` value you specify.
Differentiate request and limit values for environments: Tailor the `request` and `limit` values based on the specific requirements of each environment (dev, test, and prod). Dev and test environments do not need to be provisioned to the same extent as production. Consider keeping only one pod for services in dev, up to two in test, and three or more in production. Additionally, you can leverage a Horizontal Pod Autoscaler (HPA) to automatically create new pods when others are busy.

Implementing these best practices will help streamline resource utilization and promote efficient allocation across your pods. If you have any questions or need further guidance, please don't hesitate to reach out. Together, we can optimize resource usage and enhance overall performance.
 
Pro Tips 🤓
 
Put a service to sleep until it detects network traffic. This is a great way to conserve resources if you’re no longer actively using dev, test or tools. Use the command `oc idle service-name-here` or see an example here.
If you won’t be using the environment for an extended period scale down the deployments with the command `oc scale --replicas=0 deployment-config-name-here` Use your `limit` more aggressively. It's only oversized `request` values that are causing us issues.

Thank you for your commitment to resource efficiency.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] 04d1a3-dev (Nick)
- [x] 04d1a3-test (Nick)
- [ ] 04d1a3-prod (Nick)
- [x] d7abee-dev (Sumathi)
- [x] d7abee-test (Sumathi)
- [ ] d7abee-prod (Sumathi)
- [x] d106d6-dev (Divya)
- [x] d106d6-test (Divya)
- [ ] d106d6-prod (Divya)
- [x] eeced3-dev
- [x] eeced3-test
- [ ] eeced3-prod
- [x] c84b95-dev
- [x] c84b95-test
- [ ] c84b95-prod

**Comment by sumathi-thirumani-aot** [comment]
Presentation from Jason with information on optimization is attached herewith [latency-and-throttling.pptx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBallGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cc10207a57d8f3d1b9250113b96f7f46b0fd41c6/latency-and-throttling.pptx)

**Comment by sumathi-thirumani-aot** [comment]
IMPORTANT NOTE: Please note that the containers with dependency of vault (init container) overrides the defined memory and cpu values.

**Comment by m-prodan** [comment]
Closing ticket as work is completed - still awaiting confirmation from someone at platforms. If not resolved we can re-open.

**Comment by sumathi-thirumani-aot** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGhUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a5f7af93eb2f6eb919c64113cdf0d782e8e41765/image.png)
