### ISSUE TITLE
Bulk action - Change Full Page Redactions

### ISSUE THREAD

**Issue by liseandtea** [bcgov/foi-flow#4130]
* As an IAO analyst
* I want to be able to make bulk changes to my full page redactions
* so that I can work more quickly and efficiently

Assumptions & Scope
This is an update from the prior story - per discussion at refinement, it was too challenging to handle all use cases on its own. We are instead splitting this into two stories - one to handle redaction code updates using the redact by page feature, and the other story to update the comments panel to include an edit button, to allow for easy updates as a bulk action through the comment panel.

What is IN scope?
Updates to redaction codes via redact by page, and page flag actions

What is NOT in scope?

Acceptance Criteria

Scenario 1: Updating redaction sections in Bulk - Redact by Page

* GIVEN an IAO user is in the redaction app
* AND they have opened the 'Redact Pages' module
* WHEN they select the current page, or a range of pages, that are currently redacted in full, marked with a section, and flagged as 'Withheld in Full'
* AND select new sections under 'Add Mark'
* THEN the prior redactions will clear 
* AND the current page, or the page range, will be redacted in full, and marked with the new section number
* AND the pages will be flagged as 'Withheld in Full'

Scenario 2: Updating redaction sections in Bulk - Page Flag
* GIVEN an IAO user is in the redaction app
* AND in the left pane they have selected page(s) that have already been flagged as 'Withheld in Full'
* WHEN they right-click and select the 'Withheld in Full' flag from the left pane
* AND select new sections
* THEN the prior redactions will clear 
* AND the page(s) will be marked for redaction with the new section

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

#4124 

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by liseandtea** [comment]
@lmullane @m-prodan @KyEggleston Feedback please!

**Comment by KyEggleston** [comment]
#4125 a dependency?

**Comment by liseandtea** [comment]
@KyEggleston Yes, I agree that is a dependency.

**Comment by m-prodan** [comment]
Re-write this to only handle overwriting of full page redactions (clear prior sections ,add new), and to bring foippa modal into comments selection for mass selecting partial disclosure

**Comment by m-prodan** [comment]
Story updated to only cover redact by page scenario, using both the page flag example, and the redact by page scenario. Separate story to be written for comments panel feature

**Comment by KyEggleston** [comment]
Regarding Scenario 2 - are we planning to allow users to select more than one page in the left pane so they can 'bulk' change the section number(s) for 'Withheld in Full' pages? 

If we are restricting it just to the 'Withheld in Full' page flag, presumably users will only be allowed to bulk select pages that have the 'Withheld in Full' page flag, and all other pages will be unavailable to bulk select (e.g., when one page is selected, all other pages that aren't flagged as 'Withheld in Full' will be unavailable to select). 

If we're planning to allow bulk select and change page flag for the other page flags in the future, this may influence how we approach this.

**Comment by nimya-aot** [comment]
Working as expected, so closing it
