### ISSUE TITLE
Records tab - Watcher/Assignee Notifications Sent to Previous Request Watchers/Assignees

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4138]
**Describe the bug in current situation**

Notifications related to the Records tab (e.g., "A batch of records has been uploaded", "Harms are ready for export") are being sent to previous watchers and Assignees on a request when the user is no longer a watcher or assignee. 

For example, if a user adds themselves as a watcher on a request for a period of time, and is then removed - when records are uploaded to the Records tab after the fact, the user is still receiving the "A batch of records has been uploaded" notification under their 'Watching Notifications', even when they are not a watcher (nor are they assigned to the request). 

This occurred on FOR-2023-31219 in PROD to Monica (IAO)
Replicated in TEST on EDU-2022-99556

**Link bug to the User Story**

**Impact of this bug**

Low

**Chance of Occurring (high/medium/low/very low)**

Medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

This occurred on FOR-2023-31219 in PROD to Monica (IAO)
Replicated in TEST on EDU-2022-99556

**Steps to Reproduce**
1. As User A, go to a request where you are not a watcher or assignee, that has the Records tab available
2. Add yourself as a watcher on the request and refresh
3. Remove yourself as a watcher on the request and refresh
4. As a different user (User B), upload records to the Records tab
5. As User B, select 'Download for Harms'
6. Log in as User A - see notification under 'Watching Notifications' 

**Actual/ observed behaviour/ results**

User A, who was added and removed as a watcher on a request, is still receiving watching notifications related to the Records tab.

**Expected behaviour**
GIVEN a user has been removed as a watcher or assignee on a request
WHEN another user adds records to the request, or creates the harms package
THEN the user removed as a watcher or assignee should not receive a notification

**Screenshots/ Visual Reference/ Source**

Here is an example of a request when I added myself as a watcher, then removed myself, then had another user upload a batch of records and create the harms package. Note the two notifications when I am not a watcher or assignee.

![image](https://github.com/bcgov/foi-flow/assets/117312323/6d1dcde0-7e26-4c3d-979c-1750361ef4c4)

**Comment by KyEggleston** [comment]
Need to test other watcher notifications - when user has been added and removed as watcher, make sure no other notifications are sent to them.

**Comment by KyEggleston** [comment]
This also appears to occur for previous assignees as well, not just previous watchers.

**Comment by lmullane** [comment]
Tested as an assignee and a watcher following the Steps. This is fixed.
