### ISSUE TITLE
8.0

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#4167]
**Place-in the release name**
https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvOTI3Nzk&invite=true

#### Activity start time
4:10 PM

#### Activity end time
5:25PM

#### Step-1: Database Backup (Check the desired components)
Capture the backup details 
- [x] FOI DB (xxx)
- [x] BPM DB

#### Step-2: Image Backup (Check the desired components)
Capture the image details 
- [x] request-management-api (yyy)
- [x] forms-flow-web

#### Step-3: Production - Tagging of image (Check the desired components)
- [x] request-management-api
- [x] forms-flow-web

#### Step-4: Signoff from business
- [ ] Yes
- [ ] No
- [ ] Not Applicable

#### Step-5: Healthcheck (Check the desired components)
- [x] FOI DB
- [x] BPM DB
- [x] Docreviewer DB
- [x] redis-foi-cache
- [x] redis-foi-msgbroker
- [x] redis-reviewer
- [x] request-management-api
- [x] forms-flow-web
- [x] notification-manager
- [x] reviewer-api
- [x] reviewer-web
- [x] reviewer-conversion
- [x] reviewer-conversion-largefiles
- [x] reviewer-dedupe
- [x] reviewer-dedupe-largefiles
- [x] reviewer-pdfstitch
- [x] reviewer-pdfstitch-largefiles

#### Step-6: Staging - Tagging of image (Check the desired components)
- [ ] request-management-api
- [ ] forms-flow-web

**Observations**
List down the observations of incidents which happened in release window

**Overall Rating**
- [ ] Good (No change)
- [x] OK (With observations)
- [ ] Bad(Rollback)

**Special Instructions**
- [x] Run views
- [x] Manual api call
- [x] Manual cron execution
**- [ ]  Verify the FOI Users data
- [x]  Verify the FOI event indexes**
- [x] Cron Job setup

**Comment by m-prodan** [comment]
Confirmed - Event Queue can be released to prod as the last tickets for 8.0 has closed

**Comment by sumathi-thirumani-aot** [comment]
DB backup :
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/20dcfee8-4df3-4d07-8a3f-d9f8068c2312)

**Comment by sumathi-thirumani-aot** [comment]
Backup commands:
oc tag request-management-api:prod-002 request-management-api:prod-002-bu
oc tag forms-flow-web:prod forms-flow-web:prod-bu

**Comment by sumathi-thirumani-aot** [comment]
Tagging Image:
oc tag request-management-api:test request-management-api:prod-002
oc tag forms-flow-web:test forms-flow-web:prod

**Comment by divyav-aot** [comment]
Added below groups to KeyCloak which are active in BE.
1. Central Team
2. Flex Team
3. Justice Health Team
4. Resource Team
5. Social Education

**Comment by sumathi-thirumani-aot** [comment]
This move has an followup tasks
1. Additional check on user service to handle scenario (Groups not present) 
2.  Migration script to de active unused groups 
3.  Execute views as migration script
