### ISSUE TITLE
Harms Package - Files showing in Native File Format in Package, Even When Converted to PDF

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4171]
**Describe the bug in current situation**
Parent .msg files, their attachments (children),  and duplicates of attachments (although they are not marked as duplicates), are showing up in the Harms Package as their native file formats, and are not being included in the consolidated Harms PDF. All these files are compatible, and are converted to PDF.

For example, see IAO-2021-11383 OR  FIN-2022-123123 in TEST, look at the 'Child Care' harms package/folder. 

This looks like it's occurring in Prod on FOR-2023-31526 (see the 'RED - South Coast' harms package/folder). Or see PSS-2023-31509 in Prod (see 'Deputy Solicitor General')

**Link bug to the User Story**

**Impact of this bug**
High

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

PROD and TEST

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
When the Harms Package is created, files converted to PDF should show up in the consolidated harms PDF for the division, and the native files should not be included as a separate file in the folder.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

DOD
====

- [x] Change the GET of recordsformats.json
- [ ] Toast Error for recordsformats.json not loading.
- [x] Disable option "Upload Records"
- [x] Disable options of download.

**Comment by m-prodan** [comment]
From testing on thursday afternoon - this appears to be a caching issue. Clearing browser cache resolves the bug - but we should still find a more permanent solution for this

**Comment by m-prodan** [comment]
Appears to be an issue related to our application allowing client side caching to occur. We had set it to not cache, but it is still caching

**Comment by KyEggleston** [comment]
Needs further investigation

**Comment by sumathi-thirumani-aot** [comment]
@KyEggleston Does this issue happens for IAO or ministry login ?
Can you please give the browser details.

**Comment by KyEggleston** [comment]
I can't reproduce at the moment, but it was raised through ministry role users (in PROD and TEST). This occurred for me in Chrome (for myself and the other user). As noted, appeared to be client-side caching issue after a previous release, which is resolved through a cache clear from users.

**Comment by sumathi-thirumani-aot** [comment]
GET /records-upload-formats/test/recordsuploadformats.json undefined
Host: citz-foi-prod.objectstore.gov.bc.ca
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0
Accept: application/json, text/plain, */*
Accept-Language: en-CA,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://test-marshal-foirequest.apps.silver.devops.gov.bc.ca/
Origin: https://test-marshal-foirequest.apps.silver.devops.gov.bc.ca
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

**Comment by lmullane** [comment]
Tested with FIN-2022-123123 and a new request. All parent msg and attachments were converted to PDF and appeared in the Harms PDFs as expected.

Thank you, @sumathi-thirumani-aot
