### ISSUE TITLE
get isportfolio bug

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#4176]
**Describe the bug in current situation**
Right now, if a user uploads record but for whatever reason the request cannot contact docreviewer api, the records tab will be permanently stuck in a error state. 

ERROR Happened while fetching records :.'str' object has no attribute 'get'
44070[2023-07-20 21:35:56,957] ERROR (request_api) <app.py:app.py:1455>.log_exception: Exception on /api/foirecord/548/ministryrequest/548 [GET]
44071Traceback (most recent call last):
44072File "/app/request_api/resources/foirecord.py", line 47, in get
44073result = recordservice().fetch(requestid, ministryrequestid)
44074File "/app/request_api/services/recordservice.py", line 39, in fetch
44075return recordservicegetter().fetch(requestid, ministryrequestid)
44076File "/app/request_api/services/records/recordservicegetter.py", line 47, in fetch
44077raise exp
44078File "/app/request_api/services/records/recordservicegetter.py", line 33, in fetch
44079if not _record['attributes'].get('isportfolio', False):
44080AttributeError: 'str' object has no attribute 'get'

This is because after inserting into docreviewer db, attributes comes back from docreviewer api as python dict, but if we fetch from foiflow db it comes as a string.
Solution is to convert attributes to dict after fetching from foiflow db

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Shutdown docreviewer api
2. upload record
3. restart docreviewer api
4. refresh or wait

**Actual/ observed behaviour/ results**

**Expected behaviour**
User should still be able to use records tab, so they can delete and reupload problem record

**Screenshots/ Visual Reference/ Source**

**Comment by m-prodan** [comment]
To QA - use a variety of files, including PDF portfolios and check for dedupe/conversion issues in regular test

**Comment by m-prodan** [comment]
QA Passed - tried variety of file types including different portfolio types. Error files and replacement and tested download for harms. All working as expected.
