### ISSUE TITLE
Error/corrupted files duplicating on redaction app while filtering the flags

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4177]
**Describe the bug in current situation**
When a error file is included in the records package , then its duplicating while filtering the flags each time

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-marshal

**Steps to Reproduce**
1. Login as Ministry user
2. Try to upload few records including error/corrupted files
3. Then go to IAO login
4. Go to redaction app and try to filter flags 
5. Each time when we try to filter flags, error file duplicates

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/752c6278-d0ca-4076-8591-a05dbd0269c1)

**Comment by m-prodan** [comment]
Note: error files should not be appearing in the doc reviewer anyways, which may be the crux of this bug

**Comment by KyEggleston** [comment]
NOTE - we will need to add release label before close

**Comment by nimya-aot** [comment]
@nkan-aot Please let me know once portfolio issue fix pushed to test-marshal. Record upload is not working on test-marshal now

**Comment by nimya-aot** [comment]
It is working as expected so closing
