### ISSUE TITLE
UX Assurance - Flip Icons for Page Flags

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#4179]
Title of ticket: UX Assurance - Flip Icons for Page Flags

#### Description
The icons for Withheld in Full and Disclose Disclosure needed to be adjusted/flipped in the redaction app.

#### Dependencies
None

#### DOD
- [x] Withheld in Full icon should be solid circle 
![image](https://github.com/bcgov/foi-flow/assets/117312323/fc44f09d-04c0-4ffe-866c-4d745e465d22)

- [x] Full Disclosure icon should be open circle
![image](https://github.com/bcgov/foi-flow/assets/117312323/03a3bc97-ecf3-4415-a78a-470a60af3338)

**Comment by KyEggleston** [comment]
Updated - closing.
