### ISSUE TITLE
Summary of Redactions - IAO

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4186]
* As an IAO User
* I want to quickly know what redaction sections have been applied to a request
* so that I can easily reference them for approvals and letters

**Assumptions & Scope**	
This is a new requirement out of the redaction app needs raised by users. Users would like to be able to quickly see which sections of the act have been applied for severing. Note that BLANK is the one section that should NOT display as a section used. 

The summary will appear below the request details, once the analyst has begun applying sections of the act through the record reviewer. 

Ministry users do not need to see this at all times, it would be most useful to them at sign-off, but for the purposes of this, this will just be an IAO view for now. 

There are designs for an OI summary, but as this will not be in scope for the first release, it will be handled in a separate user story. 

What is IN scope?
Summary of sections, viewable by IAO users

What is NOT in scope?
Summary of sections viewable by Ministry users
OI sections

**Acceptance Criteria**	

**Scenario 1: Request Details Page - No Redactions**
* GIVEN an IAO user is on the request details of a page
* WHEN there have been no redaction sections applied
* THEN the summary of sections will not be visible

**Scenario 2: Request Details Page - Redactions Added**
* GIVEN an IAO user is on the request details of a page
* WHEN there has been a redaction added to the documents associated with the request
* AND a section of the Act has been associated with the redaction marks
* THEN the summary of sections will be visible
* AND the sections will be sorted in ascending order
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/813687854

**Scenario 3: Request Details Page - Redactions Added - Blank Section**
* GIVEN an IAO user is on the request details of a page
* WHEN there has been redactions added to the documents associated with the request
* AND at least one of the section of the Act chosen is blank
* THEN the summary of sections will display
* AND it will NOT include the section "Blank"

**Scenario 4: Request Details Page - Redactions Changed**
* GIVEN an IAO user is on the request details of a page
* WHEN sections selected have been changed to the documents associated with the request
* THEN the summary of sections will also update
* AND the sections will be sorted in ascending order

**Scenario 5: Request Details Page - Redactions Deleted**
* GIVEN an IAO user is on the request details of a page
* WHEN all redactions with a specific FOIPPA section are deleted from the request (Or the records containing them are removed)
* THEN the summary of sections will also update, removing that FOIPPA section
* AND the sections will be sorted in ascending order

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/813687854

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Note: risk with this one for emerald migration. may need to additional work post-emerald migration

**Comment by KyEggleston** [comment]
One case we didn't cover is, what happens when a user deletes records from the Records tab, which had FOIPPA sections applied? Currently, if I delete a record from the Records tab, which has FOIPPA section / redactions in the redaction app, these are preserved in the Summary of Redactions. 

For example, see EDU-2023-44221 in Test-Marshal. I added one large file to the Records tab, added FOIPPA sections / redactions in the redaction app, and then delete the record from the Records tab. However, these FOIPPA sections are still displayed in the Summary of Redactions.

![image](https://github.com/bcgov/foi-flow/assets/117312323/73568101-de6f-4a95-8203-5a1cb546c04f)

![image](https://github.com/bcgov/foi-flow/assets/117312323/d549bca9-c6f0-4d84-bdc8-06f5f5c83436)

I believe the business would expect these FOIPPA sections to clear from the Summary of Redactions, unless we build some validation that you cannot delete records with redactions/sections applied (which would likely be more work). 

How feasible would it be to have these FOIPPA sections in the Summary of Redactions be updated/cleared if a record(s) containing all those sections is deleted?

**Comment by KyEggleston** [comment]
@nkan-aot - just let me know when that update related to my last comment is done and I can confirm / add to ticket.

**Comment by nkan-aot** [comment]
the above change should be reflected in test-marshal now

**Comment by KyEggleston** [comment]
Added AC 5 to this ticket and QA Master sheet. This is resolved now, and closing ticket.
