### ISSUE TITLE
(FireFox) Home Button on Navigation Pane (FOI) Prompts for Save

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#419]
**Describe the bug in current situation**
When in firefox, and in the review request view, clicking on the home page function of the left panel (FOI), the application gives the user a prompt warning that changes made may not be saved, even though no changes have not been made to the request.

**Link bug to the User Story**
#361

**Impact of this bug**
Minimal impact - will require users to click out of prompt before they can return to queue.

**Chance of Occurring (high/medium/low/very low)**
High - this occurs anytime the home button is pressed, even when no changes are made to the request. 

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Must be in review request view

**Steps to Reproduce**
1. Go to the FOI Request Queue in FireFox
2. Click on Any request (behaviour is replicable across all states - unopened, intake in progress, and open)
3. Click on FOI (Home button) on left hand navigation pane
4. See prompt pop up, despite no changes being made to the request.

**Expected behaviour**
When no changes are made, the user should not receive a prompt when trying to return to the queue

**Comment by arielleandrews** [comment]
QA completed, bug issue is resolved.
