### ISSUE TITLE
Change/Create Review Layer - OIPC

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4191]
* As an IAO analyst
* I want to be able to create new OIPC Redaction layer
* so that I can preserve the original severing
* and create a new layer to edit for managing an OIPC review

**Assumptions & Scope**	
This is an offshoot of #3575 in an attempt to lower the scope of work required. For release 1, we will just need an OIPC review layer, since Open Information will not be in the system yet. 

In addition - we want to further limit the complexity by only allowing a single layer (eg - only 1 OIPC review layer, and only 1 OIPC review layer). We are also going to stick with standardized naming - it will just be called OIPC layer. 

Since we will only allow a single layer, a scenario to delete is not necessary. 

What is IN scope?
* Creating a new OIPC review Layer
* Toggling between layers

What is NOT in scope?
* OI review layer
* Naming layers
* Multiple Layers

**Acceptance Criteria**	

**Scenario 1: Redaction Layer dropdown**
* GIVEN an IAO analyst is in a request, with records added
* WHEN the analyst is in the Records Review app
* THEN there will be a dropdown in the organize pane title Redaction Layer
https://jacklyn808742.invisionapp.com/console/Redaction-cla8feezv003o015h7op82c5c/cleg4xqe55wt3018ba31e3cvi/play

**Scenario 2: Click Redaction Layer dropdown**
* GIVEN an IAO analyst is in the Records Review app
* WHEN the analyst clicks the Redaction Layer dropdown
* THEN dropdown will open with these options in this order: Redline, Response Package, OIPC
* AND the Redline layer will have no (+) as the layer is created by default
* AND the Response Package layer will have a (+) 
* AND the OIPC will have a (+)
https://jacklyn808742.invisionapp.com/console/Redaction-cla8feezv003o015h7op82c5c/cleg4xqe55wt3018ba31e3cvi/play

**Scenario 3 - Create OIPC Layer - Modal**
* GIVEN an IAO analyst is in the Redaction Layer dropdown
* WHEN the analyst clicks the (+) next to OIPC
* THEN a modal will pop up asking the user if they are sure they want to create an OIPC review layer
* AND they will have the options to 'Continue' and 'Cancel'

**Scenario 4: Create OIPC Layer - Cancel**
* GIVEN an IAO analyst has clicked the + next to OIPC
* WHEN the analyst clicks Cancel in the Modal
* THEN the modal will close
* AND they will be returned to the redaction app

**Scenario 5: Create OIPC Layer - Continue**
* GIVEN an IAO analyst has clicked the + next to OIPC
* WHEN the analyst clicks Continue in the Modal
* THEN a new OIPC layer will be created
* AND the new OIPC layer will now be shown and be editable in the Records Review app
* AND all comments and annotations will be included
* AND all redlines will be shown with section stamps
* AND all page flags will be retained
* AND the OIPC layer can be filtered by the retained page flags (e.g. Partial Disclosure, Withheld in Full, etc.)

**Scenario 6: Click active OIPC in Redaction Layer dropdown**
* GIVEN an IAO analyst has opened the Redaction Layer dropdown
* AND the analyst is not on the OIPC layer
* AND a OIPC Layer has been created
* WHEN the analyst clicks 'OIPC' in the Redaction Layer dropdown
* THEN the OIPC layer will be displayed in the Records Review app

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Note: add scenario for modal - are you sure?

**Comment by m-prodan** [comment]
This is kind of a 'high 13'

**Comment by divyav-aot** [comment]
is there any - for oipc? **no delete**
once created, can we create more oipc layer? - **no**
after creating OIPC layer, whatever changes happened in redline layer should reflect in OIPC layer? - **No**
take out effort from #3735 - we will refine it later.
**refinement comments:**
once an OIPC layer is created, the default load should be to the OIPC Layer

**Comment by nkan-aot** [comment]
clarified at standup and refinement 11/08/2023 - if a user makes changes to redline layer after new layer is created, these changes need to be reflected in all subsequent layers. This is because if there is material that should have been redacted, it needs to be added to the original redline layer, not just the new oipc layer. Meaning - no restriction on redline layer even after OI/OIPC layer created.

**Comment by abin-aot** [comment]
1. We can restrict creating OIPC,OI layer before status closed. Means no OPIC,OI layer before Closed status
2. REDLINE layer updates is required only when statuses are below Closed status ( e.g. Data Breaches --> ReOpen)
3.  Edits to OIPC layer will not bubble up to REDLINE layer. Means, we need to retain the original annotations on each layer.

**Comment by m-prodan** [comment]
From stand up - response package layer should restrict actions ie - cannot add/remove or change anything with package. It is just a view of the redacted package

**Comment by nkan-aot** [comment]
stand up 8/14/2023 - page flags need to be by layer as well. e.g. a page flagged as partial disclosure in redline, then changed to withheld in full in oipc, should still say partial disclosure when user goes back to redline layer

**Comment by nkan-aot** [comment]
standup 8/21/2023 - validations 1 and 2 in Abin's comment above will be captured in a separate ticket after the entire process workflow has been mapped and discussed

**Comment by KyEggleston** [comment]
> stand up 8/14/2023 - page flags need to be by layer as well. e.g. a page flagged as partial disclosure in redline, then changed to withheld in full in oipc, should still say partial disclosure when user goes back to redline layer

This was raised in super user session as being needed, so just bringing this forward for testing

**Comment by nimya-aot** [comment]
>From stand up - response package layer should restrict actions ie - cannot add/remove or change anything with package. It is just a view of the redacted package

When I change some redaction on OIPC layer, changes reflected on Response package layer as well. Could you please check

**Comment by lmullane** [comment]
Can test this based on the AC, but need another task on the relationship between layers, likely after 9.0.

Need a workflow to map out the relationships between layers.

**Comment by nimya-aot** [comment]
AC s working good, so closing the ticket
