### ISSUE TITLE
Delete Annotation and Redaction Box

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4193]
* As an IAO user
* I want to be able to easily delete redaction boxes
* so that I don't have to repeat tasks

**Assumptions & Scope**	
This is related to a user story written for refinement around wanting to make a redaction region and the annotation a single object. Making them a single object was not possible, but it was possible to make it so both the annotation and box would always delete.

During usability tests, it was determined that if a user inadvertently selected the FOIPPA section annotation instead of the redaction box/mark, and deleted it, they would just delete the annotation and leave the redaction box. If the user selects the redaction box/mark, and deletes it, it will delete both the redaction box/mark and the FOIPPA section annotation.

For clarity in the scenarios below:

Redaction box/mark:
![image](https://github.com/bcgov/foi-flow/assets/117312323/7018d1e3-7ef9-4e33-b992-744d4bf6daf9)

FOIPPA section annotation:
![image](https://github.com/bcgov/foi-flow/assets/117312323/d905beee-69c6-48df-a741-26cb00865e81)

Redaction panel, with redaction box/mark
![image](https://github.com/bcgov/foi-flow/assets/117312323/d4f8eb5d-5822-4f25-adcd-3bf2c0c80a23)

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: User Deletes Redaction - Annotation**
* GIVEN an IAO user is on the redaction app
* WHEN they select a FOIPPA section annotation and delete it
* THEN both the redaction box/mark and FOIPPA section annotation will be deleted

**Scenario 2: User Deletes Redaction - Panel**
* GIVEN an IAO user is on the redaction app
* AND the redaction panel is open
* WHEN they select a redaction box/mark from the panel 
* AND they delete it
* THEN both the redaction box/mark and FOIPPA section annotation will be deleted

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
Added images and edited verbiage for clarity

**Comment by KyEggleston** [comment]
I'm wondering if we want to consider changing the icon in the redaction panel, next to a redaction box/mark, to a trash can icon? It's possible users could misinterpret this as being a sort of notification and thinking the X will clear it, rather than it being an actual redaction that will be deleted once clicked one. 
![image](https://github.com/bcgov/foi-flow/assets/117312323/0f0c3a50-c8ba-4fe2-9525-aff9fc9c7fb0)

**Comment by m-prodan** [comment]
Note: remove scenario 1 - app already works as expected. For scenario 2 (soon to be 1) - selecting the annotation will ultimately remove the edit panel, which will not allow them to delete it and will force the user to click on the box instead.

**Comment by divyav-aot** [comment]
**refinement notes:** 
we will disable the selection of section annotation.

**Comment by divyav-aot** [comment]
@KyEggleston @m-prodan  @liseandtea - Group and Ungroup buttons are disabled/removed for now as discussed.

**Comment by KyEggleston** [comment]
These ACs pass, following the decision to use the group feature (i.e., any time a redaction is drawn, and a FOIPPA section applied, these two annotations will be grouped together in the Comments pane, thereby allowing them to be deleted together)
