### ISSUE TITLE
New CFR Notification - Specify File Type

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4195]
* As a Ministry User
* I want to know what type of new request is in CFR
* so that I can know if I should ignore it

**Assumptions & Scope**	
Some Ministry groups have different processes for how they handle personal requests. One client in particular requires only the leadership of the team to have access to those personal requests. While they will leverage the restricted function to handle this, they also want to avoid staff inadvertently clicking into a personal request when a new CFR is received. This change will update the notification to indicate if it is a general, or personal FOI Request.

What is IN scope?
Changes to the notification message for new request in CFR, depending on type.

What is NOT in scope?
All other features/functionality will remain the same regarding new CFR notifications.

**Acceptance Criteria**	

**Scenario 1: New General Request in CFR**
* GIVEN a general request is in the Open state
* WHEN IAO user changes the request state to CFR
* THEN a notification will trigger to all ministry coordinators with the following message: "New General request is in Call for Records"
* AND the ministry coordinators will not yet be assigned or watchers for the request.

**Scenario 2: New Personal Request in CFR**
* GIVEN a personal request is in the Open state
* WHEN IAO user changes the request state to CFR
* THEN a notification will trigger to all ministry coordinators with the following message: "New Personal request is in Call for Records"
* AND the ministry coordinators will not yet be assigned or watchers for the request.

**Scenario 3: Auto-Dismiss Notification Upon Assignment**
* GIVEN a request is in the Call For Records State
* AND the request is unassigned
* WHEN the request is assigned to a Ministry user
* THEN any notifications sent to users notifying the new request is in Call for Records that have not been dismissed, will be automatically dismissed

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by sumathi-thirumani-aot** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBak1XIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bc6ce6b09ffef9ff9d8ebf5a69c432ac552f9143/image.png)

**Comment by lmullane** [comment]
Complete as well!
