### ISSUE TITLE
Bulk Action - Change Redactions in Bulk via Comments Panel

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4196]
* As an IAO user
* I want to be able to change multiple redactions with a single action
* so that I can work more efficiently

**Assumptions & Scope**	
This is a branch-off from 4130. It was discussed it may be easier to just include the edit redaction button in the comment panel to make multiple changes easy to do within the comment panel

For Scenario 4, when a user has selected one or more redaction (using the multi-select feature) in the Comments pane, and selects the 'Edit' icon (which opens the FOIPPA modal), the FOIPPA modal should have no FOIPPA sections selected.

What is IN scope?
Changes to the comment panel to include the edit feature
Updating redactions in bulk through selections in the comment log

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Comments Panel – Edit Symbol**
* GIVEN an IAO user is in the redaction app
* AND they have the comments panel open
* WHEN they click on multi-select
* THEN the edit button will appear in addition to the other options
* AND the edit button will be inactive

**Scenario 2: Comments Panel – Edit Symbol - Active**
* GIVEN an IAO user is in the redaction app
* AND they have the comments panel open
* WHEN they filter to just redactions
* THEN the edit button will become active

**Scenario 3 – Comments Panel – Activate Edit**
* GIVEN an IAO user has selected one or more redactions from the comment panel
* AND the edit button is active
* WHEN they click on the edit button
* THEN the FOIPPA modal will appear

**Scenario 4 – Make FOIPPA Selection**
* GIVEN an IAO user has selected one or more redactions from the comment panel
* AND they are in the FOIPPA modal after clicking edit
* WHEN they make a new selection of codes
* AND click select codes
* THEN the previous redaction codes will disappear 
* AND the new redaction codes will appear

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
<h3>Question 1</h3>
How do we want to handle when a user multi-selects a redaction box, but also selects a non-redaction (e.g., annotation, FOIPPA section text, etc.) along with it?

For example, in the image below a redaction box has been selected, but a highlight annotation and FOIPPA section text has also been selected:
![image](https://github.com/bcgov/foi-flow/assets/117312323/f5639842-47b9-4d2f-8488-f6f18957e3fc)

Should we disable the edit icon when a non-redaction is multi-selected? Or allow it, but just ignore them, and still present the FOIPPA section modal if >=1 redaction has been multi-selected? 

<h3>Question 2</h3>
Also, are we requiring users to multi-select redaction boxes in order to change the FOIPPA section, or do we also want them to be able to select the FOIPPA section text annotation to change the FOIPPA section number? 

For example, should they be able to multi-select this to change the FOIPPA section?
![image](https://github.com/bcgov/foi-flow/assets/117312323/3be8edee-4f59-41a2-b24b-764da439c92c)

Or must they select an actual redaction to change the FOIPPA section?
![image](https://github.com/bcgov/foi-flow/assets/117312323/663ee302-1d39-4201-a301-70683a93822a)

<h3>Question 3</h3>
Do we want the edit icon to be called "Edit FOIPPA Section(s)"? Or just "Edit"? Having it called "Edit" may be misleading, as editing of redactions and annotations can be done through other mechanisms.

**Comment by m-prodan** [comment]
Good flags, Kyle.

I wonder if #4193 could address the issue you raise in question 2 - if not, we may need to be more proscriptive in terms of how you can change multiple redactions.... which leads me back to question 1 - good catch. I think we have to be somewhat deliberate to avoid issues... like if a highlight or comment is selected, it should grey out the edit feature.  It might be a little annoying for users, but will avoid trouble when wrong objects are selected.

Perhaps something the devs can discuss and raise for us in refinement

**Comment by m-prodan** [comment]
Note: add validation - will require filter to just redaction region to enable edit via multi-select. And include that FOIPPA modal will be fresh (ie no boxes will be pre-checked based on selections)

**Comment by divyav-aot** [comment]
Ctrl+click → edit multiple redaction? - **no need to over complicate**

**Comment by divyav-aot** [comment]
I am putting this ticket on hold until we get a response from pdftron support team. reference tickets.
support ticket - https://support.apryse.com/support/tickets/58575
pdftron forum - https://discord.com/channels/1083135872427376670/1083788813421260900/threads/1136715516237586493
**Issue:** 
When clicking on individual annotations from the NotesPanel, the "annotationSelected" event is successfully triggered. However, clicking on the checkbox does not trigger any events, leading to the inability to retrieve the selectedAnnotations. In case pdftron does not provide the "annotationSelected" event, we will have to manage this using a custom event trigger. Consequently, during the upgrade to the latest version, it will be essential to thoroughly review and verify this functionality.

**Comment by divyav-aot** [comment]
Created another ticket with PDFTron related to the auto-selection of grouped annotations. 
ticket reference: https://support.apryse.com/support/tickets/59019
https://discord.com/channels/1083135872427376670/1083788813421260900/threads/1138928780388356126

**Comment by divyav-aot** [comment]
As discussed in the standup, after performing a multi-edit for a set of redactions, click on the multi-select button or the close button to clear the current selection. Then, proceed to perform the multi-edit again for another set of redactions. Do not continue with the current selection.
cc. @m-prodan

**Comment by nimya-aot** [comment]
@divyav-aot I noticed that after we search some content on the search tab and switch back to comment panel and try to multiselect two redactions for editing, then  edit option is not appearing. Could you please check? [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmdpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--be2868d4fc0a5296899e882951ec4bb1748f0991/image.png)

**Comment by nimya-aot** [comment]
Needs to confirm one thing with business. When we edit redaction section from the main page previous section will be selected as default, but when we select just one redaction (using multiselect)  previous selection wont be selected by default on FOIPPA modal. Is it ok? @m-prodan 
cc @divyav-aot 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0F3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8fdfb183225424d28067197fcbc5752de71cf8bb/image.png)

**Comment by KyEggleston** [comment]
Check if #4376 occurs when back in Ready for QA

**Comment by divyav-aot** [comment]
Moved back to "Review" as pdftron version upgrade has fixed the auto select of grouped annotations in the comments panel. This need an addition code change to remove/update certain code.

**Comment by divyav-aot** [comment]
discuss with business on Ctrl+click edit

**Comment by divyav-aot** [comment]
As discussed in the standup, created a low priority bug related to ctrl + click.
https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4457

**Comment by divyav-aot** [comment]
Increased the effort to incorporate the apryse ticket fixes.

**Comment by nimya-aot** [comment]
I noticed some issues on bulk action. They are the following

- When we do bulk "status" update 'status' option not working 
- 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUVOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48b140a50cd0b53be12c37b56d64aaec99945723/image.png)

Also 'Group ' button enabled when bulk select two redactions
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ea28b89ec23a09802a8b1342ea060ddb5c281b0/Group_button.jpg)

**Comment by m-prodan** [comment]
Per decision at standup - we will disable the grouping option as it could cause problems. We will ignore the status button as we are not training users on it nor is it a feature we expect them to use. Lastly - the multi-select redaction issue is noted in another ticket, and will not be priority for 9,0 release

**Comment by divyav-aot** [comment]
@nimya-aot  as discussed, groupbutton has been disabled. Please clear the cache and check again.

**Comment by nimya-aot** [comment]
working as expected, so closing
