### ISSUE TITLE
Delete/Remove Redundant Groups from KeyCloak

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4201]
Title of ticket: 

#### Description
During Release 8.0 - it was determined that there were syncing issues with our DB. This was due to the manual deletion of user groups in Keycloak.

We need to be able to delete these groups so they no longer appear in the assignment drop down list, and can then be removed from keycloak. 

#### Dependencies
Are there any dependencies?

#### DOD - Ensure the following groups can be removed:
- [ ] Central Team
- [ ] Flex Team
- [ ] Justice Health Team
- [ ] Resource Team
- [ ] Social Education team

**Comment by aparna-aot** [comment]
1. Checked PROD KeyCloak and confirmed no members present on the above group.
2. Checked PROD DB to check if any requests exists with the above groups - Found 1 request(PSS-2023-32709). But @m-prodan confirmed it's ok to remove the groups. And also confirmed its okay to push the updates to test even though there are some users already in those groups.

**Comment by m-prodan** [comment]
Added release label 8.3.1 - confirmed old team names no longer appear in the application drop down.
