### ISSUE TITLE
8.0.1

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#4209]
**Place-in the release name**
8.0.1 - Small Feature Updates/Bug Fixes
https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvOTM3OTI

#### Activity start time
4:00PM

#### Activity end time
4:30PM

#### Special Instructions
Image tagging is needed only for forms-flow-web, request-management-api and reviewer-conversion
- [x] Create role and group (Divisional Coordinator) in keycloak

#### Step-1: Database Backup (Check the desired components)
Capture the backup details 
- [x] FOI DB (xxx)
- [x] BPM DB
- [x] Docreviewer DB

#### Step-2: Image Backup (Check the desired components)
Capture the image details 
- [x] request-management-api (yyy)
- [x] forms-flow-web
- [x] reviewer-conversion

#### Step-3: Production - Tagging of image (Check the desired components)
- [x] request-management-api
- [x] forms-flow-web
- [x] reviewer-conversion

#### Step-4: Signoff from business
- [x] Yes
- [ ] No
- [ ] Not Applicable

#### Step-5: Healthcheck (Check the desired components)
- [x] FOI DB
- [x] BPM DB
- [x] Docreviewer DB
- [x] redis
- [x] request-management-api
- [x] forms-flow-web
- [x] notification-manager
- [x] reviewer-api
- [x] reviewer-web
- [x] reviewer-conversion
- [x] reviewer-conversion-largefiles
- [x] reviewer-dedupe
- [x] reviewer-dedupe-largefiles
- [x] reviewer-pdfstitch
- [x] reviewer-pdfstitch-largefiles

#### Step-6: Staging - Tagging of image (Check the desired components)
- [ ] request-management-api
- [ ] forms-flow-web
- [ ] notification-manager
- [ ] reviewer-api
- [ ] reviewer-web
- [ ] reviewer-conversion
- [ ] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

**Observations**
List down the observations of incidents which happened in release window

**Overall Rating**
- [x] Good (No change)
- [ ] OK (With observations)
- [ ] Bad(Rollback)

**Comment by divyav-aot** [comment]
FOI and BPM DB backup:
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/5a3c3142-0b64-47fa-91b0-72a5ba1b02b2)
Doc reviewer DB Backup:
[Uploading... image.png]

**Comment by sumathi-thirumani-aot** [comment]
Manual reindexing of ID happened for table FOIRequestStatus
Select setval(pg_get_serial_sequence('public."FOIRequestStatuses"', 'requeststatusid'), 17) ;

**Comment by divyav-aot** [comment]
Backup Images:
oc tag request-management-api:prod-002 request-management-api:prod-002-bu
oc tag forms-flow-web:prod forms-flow-web:prod-bu
oc tag reviewer-conversion:prod reviewer-conversion:prod-bu

Prod tagging:
oc tag request-management-api:test request-management-api:prod-002
oc tag forms-flow-web:test forms-flow-web:prod
oc tag reviewer-conversion:test reviewer-conversion:prod
