### ISSUE TITLE
Allow for Saving a Request after Assignment Selected

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#423]
* As an Intake Analyst
* I want to assign a request more quickly
* so that I can help ensure I will be the only one working on a request

**Assumptions & Scope**	
This story is meant to address the potential issue of multiple analysts working on the same request by allowing a user to save an assignment before working on a request.

What is in and not in scope?
This should apply to requests in the unopened state, but could also apply in other states where the behaviour could also occur. 

**Acceptance Criteria**	

**Scenario 1: Save Button Active**
* GIVEN an analyst is on the review request view
* WHEN an assignee is selected
* THEN the Save button will become active   (Note for refinement - should we have a seperate save button next to the assignment? May need an updated design... perhaps have it as "Save assignment")

**Scenario 2: Assignment and State Update**
* GIVEN an analyst has selected an assignee
* WHEN the save button is pushed
* THEN the assignment will be saved, and the status of the request will update to "Intake in Progress"

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
** To be designed ** 

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
This is complete already.
