### ISSUE TITLE
Ministry Sign-Off to Response - Mandatory Criteria

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4245]
* As a Ministry user
* I want to ensure my sign off approval is clearly documented
* so that I can trace back when and whom approved a request

**Assumptions & Scope**	
This is likely a high-priority ticket to address a gap in how we capture sign-off approvals. We want to ensure Ministry coordinators are clearly indicating whom has approved a request and when - it is too easy now for this to be missed in the current process.

What is IN scope?
Any transition from Ministry Sign-Off to Response
System generated comment update

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Ministry Sign-Off to Response**
* GIVEN a Ministry coordinator is on a request in Ministry sign-off
* WHEN they update the state to response
* THEN the change state modal will appear
* AND there will be a space to upload a file
* AND there will be a mandatory field for: Approver Name
* AND there will be a mandatory field for: Approver Title
* AND there will be a mandatory calendar picker for: Date Approved
* AND the save change button will be inactive

**Scenario 2: Save Active**
* GIVEN a Ministry coordinator is on the Sign-Off to Response Modal
* WHEN they have entered information in the Approver Name/Title field
* AND they have entered a date from the "Date approved" picker
* THEN the save button will become active

**Scenario 3: Save**
* GIVEN a Ministry coordinator is on the Sign-Off to Response Modal
* AND the save button is active
* WHEN they click save
* THEN the modal will close and the state will update to response
 
**Scenario 4: System Generated Comment**
* GIVEN a Ministry coordinator has updated the state of a request to response
* WHEN the state change completes
* THEN a system generated comment will indicate [user] has changed the state of the request to response. Approved by [approver name/title] on [date approved]

**Scenario 5: System Generated Notification**
* GIVEN a Ministry coordinator has updated the state of a request to response
* WHEN the state change completes
* THEN a system generated notification will indicate [user] has changed the state of the request to response. Approved by [approver name/title] on [date approved]
**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/986540416

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
cc: @liseandtea - as discussed, and @lmullane as per my handover material to you.

Note @JHarrietha-AOT - we will need a design for this, but I am hoping we can get an estimate of effort in absence of design for now.

**Comment by liseandtea** [comment]
All AC pass. Closing this story.
