### ISSUE TITLE
Help Icon/Button

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4246]
* As a user
* I want to access the FOI Mod Help site from within FOI Mod 
* so that I can quickly find the help resources I need

**Assumptions & Scope**	
What are the assumptions for this story?

Users need an easy way to access the training/help videos from within FOI Mod. By embedding a link to the Help site in FOI Mod, we will make it easier for users to access the Help site, and show the connection between FOI Mod and the Help site. 

This entails adding an icon in the FOI Mod (including the Doc Reviewer) header / top nav bar to link to the FOI Mod Help site.
![image](https://github.com/bcgov/foi-flow/assets/117312323/edf0c22a-17cc-4608-900a-6be5fca753ae)

What is IN scope?
Header / top nav bar icon linked to FOI Mod Help site

What is NOT in scope?
Updating FOI Mod Help site

**Acceptance Criteria**	

**Scenario 1: Help Button/Icon**
* GIVEN a user is in FOI Mod / Doc Reviewer
* WHEN the user is on any page with the FOI Mod header / top nav bar
* THEN an icon will be displayed for the FOI Mod Help site

**Scenario 2: Open FOI Mod Help Site**
* GIVEN a user is in FOI Mod / Doc Reviewer
* AND the header / top nav bar is displayed
* WHEN a user clicks the help icon/button
* THEN then a new tab will open to the [FOI Mod Help site](https://[help.foirequests.gov.bc.ca](https://help.foirequests.gov.bc.ca/)/)

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/ckpx6mtxp0128013ecxv9f3nw/play

#1991

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by katrinaferacini** [comment]
@m-prodan @Aman-Hundal This is great! One suggestion: I would recommend linking directly to the 'home' page https://help.foirequests.gov.bc.ca/help-articles as opposed to the current page. It's an extra step for users to click and is not needed.
