### ISSUE TITLE
Original LDD Needs to Not Change

### ISSUE THREAD

**Issue by liseandtea** [bcgov/foi-flow#4256]
**Describe the bug in current situation**
When a request is migrated from AXIS, the original legislated due date is being updated to match the legislated due date when it needs to not change. 

**Link bug to the User Story**
This is linked to #2685
While this is not written in the AC it is in the "Assumptions and Scope" (assumption copied below) of the ticket.

- This ticket will require a small design update to include these fields on the request details page
- Original Due Date will display the original legislated due date from the time the request is opened and will not be editable
- Legislated due date will update after extensions and/or after a request comes off On Hold
- Date fields will always be visible but will show blank or N/A until populated following the relevant state change

**Impact of this bug**
The impact of this bug is that the original legislated due date is not accurately reflected. This is important information to base timeline calculations on especially when there is involvement from the OIPC.

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requisites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to FOI Mod user page 
2. Click on add request
3. Enter a request number that exists in AXIS and has had an extension applied
4. Click on sync with AXIS
4. Scroll down to Request Details

**Actual/ observed behaviour/ results**

Incorrectly displayed in Mod: Original LDD and Legislated Due Date are showing as March 7, 2022 after the application of extensions.  The Original LDD should state September 9, 2021.

![image.png](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/b708c3eb-2c5b-47b0-8fbb-ec8b5de7dc54)

**Expected behaviour**

- GIVEN an extension has been applied to a request 
- WHEN a user has migrated or synced a request from AXIS to Mod
- THEN the Legislated Due Date will be migrated/synced with the new Legislated Due Date 
- AND the Original Legislated Due Date will remain the same

**Screenshots/ Visual Reference/ Source**

Correctly displayed in AXIS: Original LDD is showing as September 9, 2021 and Legislated Due Date is showing as March 7, 2022 after the application of extensions.

![image.png](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/a1854fba-d4f7-4f92-972c-e70ff92aee80)

**Comment by liseandtea** [comment]
@lmullane @KyEggleston Anything to add?

**Comment by KyEggleston** [comment]
Can be completed with #4258, as both involve AXIS sync

**Comment by m-prodan** [comment]
Note for QA - do a simple regression around due dates, extensions, notifications/comments etc.

**Comment by m-prodan** [comment]
Functioning as expected, simple regression with sync and notifications/comments appear to be working too. Closing ticket - thank you @aparna-aot
