### ISSUE TITLE
Identity Verified Field - Sync with AXIS

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4258]
* As a user in FOI Mod
* I want have the 'Identity Verified' field on Personal requests synced with AXIS
* so that the request details in FOI Mod are accurate 

**Assumptions & Scope**	
What are the assumptions for this story?

Currently, there is the 'Identity Verified' field in MOD and 'Identity Verification' field in AXIS. However, the 'Identity Verified' field is not syncing with AXIS in FOI Mod. We need the 'Identity Verified' field in FOI Mod to be synced with the AXIS 'Identity Verification' field to get this data. This will be a temporary fix, where this data will come from AXIS. In the future, this data may come from the Angular app. 

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Sync Identity Verified**
* GIVEN a request has been created in FOI Mod and AXIS
* AND the 'Identity Verification' field in AXIS is populated with data on the request
* WHEN an FOI Mod user syncs the request in FOI Mod with AXIS
* THEN the 'Identity Verification' field/data will be pulled from AXIS
* AND this data will be populated in the 'Identity Verified' field in FOI Mod

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
Can be completed with #4256, as both involve AXIS sync

**Comment by aparna-aot** [comment]
As discussed during standup (2023-08-15), we will be disabling the Identity Verified text field on the Front End of a request.
![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/ed9b32be-302f-4032-95ae-f3aa8642b9d9)

**Comment by m-prodan** [comment]
sync is now pulling the ID verified as expected. Master QA manual updated, thank you @aparna-aot
