### ISSUE TITLE
Unable to see the page when we select pages from the left panel

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4265]
**Describe the bug in current situation**
If ministry coordinator uploads more documents  after generating redline pdf , then the pages not showing up on redaction app when click on each page on the left panel

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-marshal

**Steps to Reproduce**
1. Go to Ministry login
2. Click on upload documents
3. Generate redline pdf after redacting all the pages
4. Then come back to ministry login and upload  more documents
5. Return back to IAO login and on the redaction app ,pages are not showing up when we click on the left panel

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/4dc5efc7-f3f4-423b-852e-1c57df50717d)

**Comment by m-prodan** [comment]
@richard-aot - to test/reproduce, can you add an estimate of effort as well?

**Comment by nimya-aot** [comment]
@richard-aot The request link is as follows https://test-reviewer-web-marshal.apps.silver.devops.gov.bc.ca/foi/562
EDU-2023-1108 on test-marshal
