### ISSUE TITLE
IAO Scanning Team - Records Upload - CFD Personals

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4292]
* As an IAO scanning team user or CFD coordinator
* I want to be able to tag and upload records for CFD Personal Requests
* so that the records will be ready to review for the analyst

**Assumptions & Scope**	
This is the first user story to capture the requirements/needs of the IAO scanning team to upload records to the application for redaction.

Unlike other Ministries, the MCFD team mostly sends physical records to IAO, who scans the records and uploads them for review. This means that we will need the ability to upload records from the IAO side.

If files are digital (i.e., ICM), CFD users will upload the Records directly into the Records log (replacing the SharePoint).

In addition - CFD records are unique in that they are not typically tracked or severed by division, but rather the specific file type. 

The scanning team will therefore scan a file type of records, and "tag" the file type appropriately before they upload it to the system.

CFD coordinators will tag records that are digital on upload.

Technically, PDF conversion and dedupe is not necessarily required since all records will be unique due to scanning and likely already in PDF Format. 

This is only required on CFD personals (and later, MSD Personals #4303)

Any records uploaded to the records log will have the same functionality (eg - being able to delete/replace records, change tags etc)

They upload physical files into folders based on manilla folders so the number of pages uploaded at once is limited by how many pages can fit in a manilla folder.

**Download for harms will work, and follow the file tag logic like division tag logic.**

What is IN scope?
Upload of records by IAO scanning team on CFD personals

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: IAO Scanning Team - Upload Records**
* GIVEN a user is on a MCFD Personals Request
* AND they are a member of the IAO scanning team
* WHEN they click on the "Records" tab
* THEN they will see a button to "Upload Records"

**Scenario 2: Upload Records**
* GIVEN a scanning user is on the Records Tab
* AND the request is a MCFD Personals
* WHEN they click on the 'Upload Records' Button
* THEN a modal will pop up (https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/clkd1ctsg83vs01ai2q4p8me7/play)
* AND the continue button will be disabled

**Scenario 3: Activate Files**
* GIVEN a scanning user is on the "Add scanned records" modal
* WHEN they select a file type (link to finalized list)
* THEN a space to upload records will appear (https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/clkd1ctsg83vu01aiaa9950q7/play)

**Scenario 4: Select Different Tag**
* GIVEN a scanning user is on the "Add scanned records" modal
* AND a tag has been selected
* WHEN they select a different tag
* THEN the prior tag will be de-selected
* AND the new tag will be selected

**Scenario 5: Activate Continue**
* GIVEN a scanning user is on the "Add scanned records" modal
* WHEN they drag or drop files into the file upload 
* OR they add files by selecting through their computer via the Add File button
* THEN the continue button will become acive

**Scenario 6: Click Continue**
* GIVEN a scanning user is on the "Add scanned records" modal
* AND the continue button is active
* WHEN the continue button is clicked
* THEN the modal will close, and the files will be uploaded to the records log with the associated tag

**Scenario 7: Search Additional**
* GIVEN a scanning user is on the "Add scanned records" modal
* AND a tag has not been selected
* WHEN the user types in the "search" field
* THEN any tags that start matching the entered text will begin appearing (link to full list here)

**Scenario 8: Search Additional selected**
* GIVENan Additional tag has been applied to uploaded records
* WHEN the user is on the "Add scanned records" modal
* THEN the selected/applied tag will automatically appear under the Search additional field

**Scenario 9: Click Cancel**
* GIVEN a scanning user is on the "Add scanned records" modal
* WHEN they click cancel
* THEN the modal will close and the user will be returned to the records section

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/clkd1ctsg83vu01aiaa9950q7/play

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
scanning story 1 - cc @lmullane @JHarrietha-AOT

**Comment by lmullane** [comment]
Hey @m-prodan , looks good. 

A few questions:
- Can the analyst select only one tag at time? If yes, we should add the AC.
- When the records are uploaded, will the system be required to remove duplicates and convert records to PDF?
- Can the records be replaced or deleted in the Records Log once they are uploaded?
- When the Harms Package is downloaded, there will be one PDF for each tag, correct?

**Comment by m-prodan** [comment]
1) Will add AC for the one tag at a time restriction.

2) Since this is scanning - records should already be PDF'd from the scan job. Rank 1 dedupe doesn't make sense since the hash values will all be different, so I don't think it needs to but it might anyways as part of our existing component.

3) Yes - records log functionality should remain consistent across, with users being able to delete/change tags. I will include that in assumptions

4) Maybe a question of if we need a separate story? I will add to the assumptions for now and see from refinement discussion

**Comment by lmullane** [comment]
Ministry users will have access to the Records log and be able to see all uploaded Records.

**Comment by richard-aot** [comment]
@m-prodan According to our discussion, ministry users are able to upload records for CFD Personals as well. Could you please add Ministry user to this ticket or create a separate ticket for Ministry user? Thanks.

**Comment by JHarrietha-AOT** [comment]
@richard-aot @m-prodan 

Adding the list of section names provided by CFD. The comment stack is what is in the design and the section names that we see all the time. The big list stack are the options that will be searchable

[SECTION NAMING .txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2M0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6587a0ec2524a786d37425d4715eaee03bf47da4/SECTION%20NAMING%20.txt)

**Comment by JHarrietha-AOT** [comment]
@richard-aot for uploading scanned records for a CFD request the module needs an update - the options that show up all the time should end at "inside back cover" all options after that should only show up in the search bar

For reference I have included the TXT doc only the ones are the common stack should be viewable all the time. everything else should only be viewable under search

MSD Module looks great!

[SECTION NAMING .txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBci9pIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f1083632e911515eb364ac9c7d85cf6c4c79d844/SECTION%20NAMING%20.txt)

**Comment by JHarrietha-AOT** [comment]
@richard-aot was just on dev and see that this has been updated - thanks for the quick change moving into Ready for QA

**Comment by liseandtea** [comment]
All AC pass, closing this story.
