### ISSUE TITLE
Request status missing on Edge

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4293]
**Describe the bug in current situation**
When a request is move to 'open' state then the status is missing on the request

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Browser: Edge
DEV, Test

**Steps to Reproduce**
1.Login as a IAO user and create a request
2. Move the request to open state
3. Then on the edge browser login as assignee and can see status missing on the request

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUlXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b1a749e3ee3fe956a2e289e1cb031696403fa1fa/image.png)

**Comment by KyEggleston** [comment]
This has been resolved previously - closing.
