### ISSUE TITLE
Blank code and page flag issues

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#4299]
**Describe the bug in current situation**
Currently the system allows to add multiple withheld in full pageflag for a page. The findings related to this are listed below.

Steps followed:

1. Select a page and right click to add withheld in full with blank code - (page number shows with "in progress" icon  as expected) **This is the expected behavior.**
2. Use normal edit and update to s. 15 (or any section other than blank code) - (page number shows with "in progress" icon) -  page flag change is not happening for non full page redactions as well - **steps to reproduce mentioned below**
3. Again select the page and add withheld in full page flag with another section, say s. 14 (not the one mentioned in step 2.) - (page number shows with withheld in full icon, but the page has 2 redactions now s. 15 from step 2 and s. 14 from step 3)  - **based on the requirement, the latest redaction will be showing in the page. There won't be multiple withheld in full sections on a page**
4. if step 3 is the right behavior then, when you try to edit the s. 15, the default selection shows the sections selected in step 3. - **since step 3 is not a valid case, this is not an issue**

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
**Bug #1**
1. Go to Doc reviewer
2. Click on a page and add withheld in full flag with blank code section
3. The page flag automatically updates to "in progress"
4. Now edit the section to any meaningful section number

**Actual/ observed behaviour/ results**
The page flag stays as "in progress"

**Expected behaviour**
The page flag should show "withheld in full"

**Bug #2**
1. Go to Doc reviewer
2. Click on a page and add a redaction with blank code section
3. The page flag automatically updates to "in progress"
4. Now edit the section to any meaningful section number

**Actual/ observed behaviour/ results**
The page flag stays as "in progress"

**Expected behaviour**
The page flag should show "partial disclosure"

**Bug #3**
1. Go to Doc reviewer
2. Click on a page and add withheld in full flag with a section number
3. The page flag automatically updates to "withheld in full"
4. Now edit the section to blank code

**Actual/ observed behaviour/ results**
The page flag stays as "withheld in full"

**Expected behaviour**
The page flag should show  "in progress"

**Bug #4**
1. Go to Doc reviewer
2. Click on a page and add a redaction with section number
3. The page flag automatically updates to "partial disclosure"
4. Now edit the section to blank code

**Actual/ observed behaviour/ results**
The page flag stays as "partial disclosure"

**Expected behaviour**
The page flag should show  "in progress"

**Bug #5**
1. Go to Doc reviewer
2. Shift + Click on multiple pages and add withheld in full flag with blank code section
3. Only the first page got updated with "in progress" flag. All other pages shows "withheld in full"

**Actual/ observed behaviour/ results**
Only the first page got updated with "in progress" flag. All other pages shows "withheld in full"

**Expected behaviour**
All selected page's page flag should update to "in progress" 

**Bug #6**
1. Go to Doc reviewer
2. Select all full page redactions with blank code from NotesPanel Multiselect
3. Edit and add meaningful section
4. see the error

**Actual/ observed behaviour/ results**
Page flag stays as is

**Expected behaviour**
All selected redactions pages should update to "withheld in full"

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
May be resolved now - QA

**Comment by nimya-aot** [comment]
Right now, when we select a page and right click to add "withheld in full"  flag with blank code ,it is showing "withheld in full icon" instead of "in progress" icon. Also while editing  the FOIPPA section it still shows the wrong section as the default one. @divyav-aot  mentioned these issue are fixed on dev-marshal. So once it is pushed to test-marshal, will test again

**Comment by divyav-aot** [comment]
refer: #3579, #3578

**Comment by divyav-aot** [comment]
@m-prodan - could you please confirm the expected behavior for above mentioned bugs. Currently automatic flag change is not happening on edit of redaction sections from blank code to any other code and vise versa.

**Comment by m-prodan** [comment]
Thanks Divya - in reality, users should not be redacting in full with a blank code; however, they may do so by accident. This may be better if we keep this as a known issue than try to solve all these edge cases around it.

When CFD team uses the blank redaction code, they will sever all of the information they need with the blank codes - when they complete the page though, they will draw another box at the bottom and actually tag it to a meaningful section. But I can also see them having blank code saved as default, and then editing the box at the bottom to have meaningful sections - in which case, I think if we needed to prioritize any of these bugs, I would prioritize:

Bug #2
Steps to reproduce the behavior:

Go to Doc reviewer
Click on a page and add a redaction with blank code section
The page flag automatically updates to "in progress"
Now edit the section to any meaningful section number
The page flag stays as "in progress"

All other bugs seem more like edge cases, that we should note as known issues so users know how to resolve (eg - remove all of the blank redaction boxes and redraw)

**Comment by m-prodan** [comment]
Expected behaviour when we change from a blank code, to a meaningful section should be that it updates the page flag to partial disclosure, or withheld in full where appropriate. But if I had to prioritize the bug fix, I would do so for the partial disclosure scenario noted in bug #2 - as most CFD analysts know they shouldn't use blank code to redact in full.

**Comment by divyav-aot** [comment]
Thanks @m-prodan for the clarification. I will focus on bug #2.

**Comment by nimya-aot** [comment]
working as expected, so closing
