### ISSUE TITLE
Ministry Signoff option not showing up when a request in Peer Review state from Record Review

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#4300]
**Describe the bug in current situation**
For some requests Ministry Signoff option not showing up when a request is in Peer Review state when moved from Records Review.

**Link bug to the User Story**
#3864

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
Medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

1. Take a request and move it until Records Review.
2. Make some updates to the request other than state change.
3. And then move to Peer Review
4. THEN check the state options: 

**Actual/ observed behaviour/ results**
State Options currently showing : Call for Records, Open and Closed

**Expected behaviour**
State Options should be : Call for Records, Consult, Ministry Sign Off, Records Review, Response and Closed

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
This appears to be fixed now, closing ticket. Thank you @aparna-aot
