### ISSUE TITLE
CFD Personals Requests - Records Sort Order Redaction App

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4302]
* As a an IAO User
* I want my scanned records to show with their tags in the redaction app
* so that I know how I will approach my severing

**Assumptions & Scope**	
This is related to #4292 - this essentially covers how the tagged records uploaded by the CFD scanning team should be displayed in the redaction app.

The tags for the scanned records are essentially divisions. Since most of the records processed are scanned, the modified date may not be helpful. As such, for CFD personal requests, the default view of the records app should be by "tag" (division)

Changes to records after they are uploaded (eg added/removed) will function as expected with general requests (eg, deleted records from the records tab will no longer show in the redaction app etc...)

What is IN scope?
How records are displayed/organized in the left-hand panel of the redaction app

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Tagged Records - Redaction App**
* GIVEN an IAO user is on a CFD Personals Request
* AND there are records tagged by the scanning team
* WHEN the analyst opens the redaction app
* THEN the default filter will be Division

**Scenario 2: Add Files To Division - Document Reviewer**
* GIVEN a MCFD Ministry user has uploaded files to a selected division
* WHEN the IAO user accesses the document reviewer
* THEN the records will be present for redlining in the document reviewer

**Scenario 3: Records Sort Order - Division**
* GIVEN an IAO user is in the redaction app of a CFD Personals request
* WHEN the filter is set to division
* THEN the records will appear in the order they were uploaded, below the relevant tags

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
CFD Records sort order in redaction app after uploading.

cc @lmullane @KyEggleston @JHarrietha-AOT

**Comment by lmullane** [comment]
@m-prodan, for personal requests should we change the filter from "Division" to "Record Type"?

If not, feels like there is no development effort for this other than removing the Modified Date filter.

**Comment by richard-aot** [comment]
According to the discussion in refinement meeting, there is no need to show hierarchy on left panel for divisions/sections.

**Comment by nimya-aot** [comment]
@m-prodan Just want to confirm this. So the records will be appear in the order they uploaded first either by section/division.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUdHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e9873b23c6b477801f190b0eea5b072c971bc18/image.png)

**Comment by liseandtea** [comment]
@KyEggleston @nimya-aot @m-prodan 

Currently in AXIS, scanning uploads all records for a request, however the electronic records (which are going to be the ones the Ministry will begin to load into Mod) are generally put last. Honestly, I don't know if we need to still keep that order, it is simply what the CFD processing team is used to.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d60675c780cab9e354b4e6aa795d0f877c614772/image.png)

**Comment by nimya-aot** [comment]
@liseandtea ok, But right now, in our redaction app it **wont** show up all the records that scanning team uploads first and then Ministry.( screenshot shows the order which I uploaded). It will be like document which uploaded first will be appear at the top (whether it is uploaded by ministry/scanning team ) and so on. Bottom document will be the last document which uploaded either by ministry/scanning team. It will be in a mixed fashion

**Comment by m-prodan** [comment]
That might just have to be a process change on their part then. Presumably going forward, Ministry will upload ICM records first since scanning always has a lag - so it will be reversed now - ICM first, then physically scanned records next.

**Comment by m-prodan** [comment]
I think the sort order is fine - if ICM comes first, because the Ministry uploads it first (which will be the case most of the time when there are ICM records) - that will just be something that will be different. I am comfortable with it as is.

**Comment by nimya-aot** [comment]
As per the above comment , it is working good, so closing this ticket
