### ISSUE TITLE
IAO Scanning Team - Records Upload - MSD Personals

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4303]
* As an IAO scanner
* I want to tag and upload my scanned physical records to a request
* so that analysts can identify what type of file they will review

**Assumptions & Scope**	
This is related to #4292 - but is relevant for MSD personal requests specifically.
Occasionally, IAO will scan records for the Ministry, and so IAO needs an avenue to upload records to the system and tag them by the file type. For this function to be enabled, the ministry coordinator needs to have the SDD selected in the divisional tracker. 

Uploading of records for MSD personal requests will still utilize the core functionality of the records tab -  the ability to make changes to the records through delete/replace, changing tags etc...

Dedupe and conversion is likely not required given that these are scanned records. 

The download for harms feature will also work as usual, allowing users to download a separate PDF for each tag.

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: IAO Scanning Team - Upload Records**
* GIVEN a user is on a MSD Personals Request where the Ministry has selected SDD Division
* AND they are a member of the IAO scanning team
* WHEN they click on the "Records" tab
* THEN they will see a button to "Upload Records"

**Scenario 2: Upload Records**
* GIVEN a scanning user is on the Records Tab
* AND the request is a MSD Personals
* WHEN they click on the 'Upload Records' Button
* THEN a modal will pop up (INSERT UPDATED MSD DESIGN LINK)
* AND the continue button will be disabled

**Scenario 3: SDD Division Selected**
* GIVEN a scanning user has clicked on upload records button
* AND the SDD division has been selected by the Ministry for the tracking
* WHEN the modal opens
* THEN the modal will include the divisions and a list of tags for the SDD division (INSERT UPDATED MSD DESIGN LINK)

**Scenario 4: Activate Files**
* GIVEN a scanning user is on the "Add scanned records" modal
* WHEN they select a division (link to finalized list)
* OR they select a file type from the SDD division
* THEN a space to upload records will appear (INSErT UPDATED MSD DESIGN LINK)

**Scenario 5: Activate Continue**
* GIVEN a scanning user is on the "Add scanned records" modal
* WHEN they drag or drop files into the file upload
* OR they add files by selecting through their computer via the Add File button
* THEN the continue button will become active

**Scenario 6: Click Continue**
* GIVEN a scanning user is on the "Add scanned records" modal
* AND the continue button is active
* WHEN the continue button is clicked
* THEN the modal will close, and the files will be uploaded to the records log with the associated tag

**Scenario 7: Search Additional**
* GIVEN a scanning user is on the "Add scanned records" modal
* AND the SDD Division was selected from the divisional tracking
* WHEN the user types in the "search" field
* THEN any tags that start matching the entered text will begin appearing (link to full list here)

**Scenario 8: Click Cancel**
* GIVEN a scanning user is on the "Add scanned records" modal
* WHEN they click cancel
* THEN the modal will close and the user will be returned to the records section

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
MSD IAO Scanning Team user story

cc @JHarrietha-AOT @lmullane @KyEggleston

**Comment by lmullane** [comment]
@m-prodan, do these scanned files need to go through the dedupe and PDF conversion process? Assumption is no.

**Comment by JHarrietha-AOT** [comment]
@richard-aot @abin-aot @divyav-aot @sumathi-thirumani-aot @nick-aot Adding the design here for MSD[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbll4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--822e118862ca0b5e0a560cae12d885bd0d4af291/MSD%20Updated%20Design.jpeg)

**Comment by JHarrietha-AOT** [comment]
@richard-aot for uploading scanned records for a CFD request the module needs an update - the options that show up all the time should end at "inside back cover" all options after that should only show up in the search bar

For reference I have included the TXT doc only the ones are the common stack should be viewable all the time. everything else should only be viewable under search

MSD Module looks great!

[SECTION NAMING .txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBci9pIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f1083632e911515eb364ac9c7d85cf6c4c79d844/SECTION%20NAMING%20.txt)

**Comment by JHarrietha-AOT** [comment]
Moving this to ready for QA as MSD module is good to go - updated needs for CFD Upload Module so above comment has been added to #4292

**Comment by liseandtea** [comment]
@richard-aot 
Hey Richard! 
Can you please have a look at this one? I am signed in as an IAO scanning analyst, however no records tab is showing on MSD personal requests. It is showing up for CFD requests. Thank you!
MSD:
[Private Zenhub Image]
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1BzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--183aabd7ab2bb4838c04a79fb11a4a640066f617/image.png)

CFD: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1RzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9adefd5be3807a0b3d6414f19c758d5ee3ebb599/image.png)

**Comment by liseandtea** [comment]
@richard-aot 
Hey Richard, I tested in both TEST (MSD-2023-58467) and in Marshal (MSD-2023-58583). The functionality for this story should be the same as the one for CFD #4292. It is not dependent on the Ministry adding divisions before adding records. It is so a member of the IAO scanning team is able to upload the records.

**Comment by liseandtea** [comment]
@richard-aot Hey! There was information missing from the AC which has now been added. Let me re-test and get back to you if there are any issues!

**Comment by richard-aot** [comment]
Sounds good. Thanks @liseandtea

**Comment by liseandtea** [comment]
All ac pass with the missing info added to the story. I am closing this ticket.
