### ISSUE TITLE
MSD Personal Requests - Records Sort Order - Redaction App

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4304]
* As a an IAO User
* I want my scanned records to show with their tags in the redaction app
* so that I know how I will approach my severing

**Assumptions & Scope**	
This is related to #4303 - this essentially covers how the tagged records uploaded by the scanning team should be displayed in the redaction app.

The tags for the scanned records are essentially divisions. Since most of the records processed are scanned, the modified date may not be helpful. As such, for MSD personal requests, the default view of the records app should be by "tag" (division)

Changes to records after they are uploaded (eg added/removed) will function as expected with general requests (eg, deleted records from the records tab will no longer show in the redaction app etc...)

What is IN scope?
How records are displayed/organized in the left-hand panel of the redaction app

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Tagged Records - Redaction App**
* GIVEN an IAO user is on a MSD Personals Request
* AND there are records tagged by the scanning team
* WHEN the analyst opens the redaction app
* THEN the default filter will be Division

**Scenario 2: Add Files To Division - Document Reviewer**
* GIVEN a MSD Ministry user has uploaded files to a selected division
* WHEN the IAO user accesses the document reviewer
* THEN the records will be present for redlining in the document reviewer

**Scenario 3: Records Sort Order - Division**
* GIVEN an IAO user is in the redaction app of a MSD Personals request
* WHEN the filter is set to division
* THEN the records will appear in the order they were uploaded, below the relevant tags

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
MSD sort order for records in the redaction app

cc @lmullane @KyEggleston @JHarrietha-AOT

**Comment by lmullane** [comment]
Hey @m-prodan, I heard that the analyst redact records differently depending on who the records belong too. For example, the spouse vs the key player. 

Do we need to consider grouping all the records that belong to a person together (i.e. filter by Key Player)?

**Comment by m-prodan** [comment]
I think just the fact that users can sort by tags might suffice as a first release, since we have distinct tags for key player vs others. However, you are right in that it might not show things in the order they necessarily expect. Bundling by type might be something we could look at in a future release? Perhaps a replacement of modified date? I will write up a separate story

**Comment by richard-aot** [comment]
According to discussion in refinement meeting, this sorting updates will be applied to left document list panel. The sorting/stitching on main window will not change. (sort/stitch by modified date)

**Comment by nimya-aot** [comment]
@richard-aot The last uploaded document is(section FM4) not showing at the bottom in redaction app. Could you please check?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c206dfe7d97420bd940e29466e2f07065df42b5/image.png)

**Comment by nimya-aot** [comment]
It is working as expected, so closing
