### ISSUE TITLE
MSD Personal Requests - Ministry Upload and Tagging

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4305]
* As a MSD ministry coordinator
* I want to tag records by division or record type
* so that they can be organized for redaction

**Assumptions & Scope**	
Uploading of records for MSD personal requests will still utilize the core functionality of the records tab - automated conversions and deduplication, as well as the ability to make changes to the records through delete/replace, changing tags etc...

The download for harms feature will also work as usual, allowing users to download a separate PDF for each tag.

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: MSD Ministry Team - Upload Records**
* GIVEN a user is on a MSD Personals Request
* AND they are a member of the MSD Ministry Team
* WHEN they click on the "Records" tab
* THEN they will see a button to "Upload Records"

**Scenario 2: Upload Records**
* GIVEN a MSD Ministry user is on the Records Tab
* AND the request is a MSD Personals
* WHEN they click on the 'Upload Records' Button
* THEN a modal will pop up (INSERT UPDATED MSD DESIGN LINK)
* AND the continue button will be disabled

**Scenario 3: SDD Division Selected**
* GIVEN a Ministry user has clicked on upload records button
* AND the SDD division has been selected by the Ministry for the tracking
* WHEN the modal opens
* THEN the modal will include the divisions and a list of tags for the SDD division (INSERT UPDATED MSD DESIGN LINK)

**Scenario 4: Activate Files**
* GIVEN a Ministry user is on the "Upload records" modal
* WHEN they select a division (link to finalized list)
* OR they select a file type from the SDD division
* THEN a space to upload records will appear (INSErT UPDATED MSD DESIGN LINK)

**Scenario 5: Select Different Tag**
* GIVEN a Ministry user is on the "Add scanned records" modal
* AND a tag has been selected
* WHEN they select a different tag
* THEN the prior tag will be de-selected
* AND the new tag will be selected

**Scenario 6: Activate Continue**
* GIVEN a Ministry user is on the "Upload records" modal
* WHEN they drag or drop files into the file upload
* OR they add files by selecting through their computer via the Add File button
* THEN the continue button will become active

**Scenario 7: Click Continue**
* GIVEN a Ministry user is on the "Upload Records" modal
* AND the continue button is active
* WHEN the continue button is clicked
* THEN the modal will close, and the files will be uploaded to the records log with the associated tag

**Scenario 8: Search Additional**
* GIVEN a Ministry user is on the "Upload records" modal
* AND the SDD Division was selected from the divisional tracking
* WHEN the user types in the "search" field
* THEN any tags that start matching the entered text will begin appearing (link to full list here)

**Scenario 9: Click Cancel**
* GIVEN a Ministry user is on the "Upload Records" modal
* WHEN they click cancel
* THEN the modal will close and the user will be returned to the records section

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
MSD Ministry user - upload records story (personals) 

cc @lmullane @JHarrietha-AOT @KyEggleston

**Comment by lmullane** [comment]
Similar questions to #@4292:

- Likely we should specify that only one tag can be selected.
- Should the system remove duplicates and convert to PDF? Assume the answer is yes for MSD files
-  I have heard that Scanning sometimes need to upload records too. Should they have that option as well for MSD records?

**Comment by m-prodan** [comment]
updated

**Comment by JHarrietha-AOT** [comment]
Passed UX Assurance

**Comment by nimya-aot** [comment]
@richard-aot For MSD Ministry user, record upload modal has wrong title. it should be 'Add Record' instead of "add Attachment'. Could you please check?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXZyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--158c7ec1e5d6398e6b1e357f1937804ce67e0f70/image.png)

**Comment by nimya-aot** [comment]
@abin-aot  Following sections are missing on the upload modal. could you please check?
FM4 AHR
GA2 SPOUSE PHYSICAL
GA2 DEPENDENT PHYSICAL
FM5 PHYSICAL

**Comment by richard-aot** [comment]
@nimya-aot The following bugs are fixed and ready for testing:
1. Upload modal title
2. Typos for sections

**Comment by liseandtea** [comment]
All AC pass, closing ticket.
