### ISSUE TITLE
Redactions created in the morning has wrong time stamp

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4310]
**Describe the bug in current situation**
Redactions created in the morning time has wrong time stamp.
**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Medium

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-marshal

**Steps to Reproduce**
1. Go to redaction app
2. Create some redactions before 12 pm( in the morning 10 .18 am)
3. Time stamp shows 7 hr behind the current time(PST)

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnNpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--18eec5f0c457252208eb4b2e138fd5573ad4c9ef/image.png)

**Comment by aparna-aot** [comment]
Apryse is adding an additional system time zone calculation while displaying the date and time of a redaction on comments panel (after you add redaction & refresh the page) . So we have created a ticket with Apryse for the same. Still I have added our own fix by implementing a UTC time conversion in backend and is working fine.
But if Apryse is fixing this bug, we might need to remove our fix in backend. So we might need to check this ticket again if Apryse comes up with a solution.

**Comment by nimya-aot** [comment]
@aparna-aot when we check the redactions on redaction panel, the time stamp is still wrong . could you please check that?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmExIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5a026d292516e0cbb0ba0540091cb2b780ad827a/image.png)

**Comment by aparna-aot** [comment]
Thanks for noticing that @nimya-aot . Will push the fix soon.

**Comment by aparna-aot** [comment]
Fixed and pushed to test-marshal @nimya-aot .

**Comment by nimya-aot** [comment]
working as expected, so closing
