### ISSUE TITLE
Redactions moved from one page to other - breaks grouping and other issues

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4311]
**Describe the bug in current situation**
When redactions are dragged across pages, you are prompted to select a new FOIPPA section. If you select a new section, you will have a FOIPPA section created that is not associated to a redaction. If you do not select a new FOIPPA section, the redaction and FOIPPA section are 'Ungrouped', and become their own annotations. Both behaviours can cause confusion for users.   

See EDU-2023-74647 in Test-Marshal for examples. 

**Link bug to the User Story**

**Impact of this bug**
Medium

**Chance of Occurring (high/medium/low/very low)**
Low

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-Marshal

**Steps to Reproduce**
1. Create a redaction, with FOIPPA section, on a page
2. Drag the redaction to another page
3. You will be prompted to select another FOIPPA section - select a FOIPPA section and click 'Select Code(s)'

AND

1. Create a redaction, with FOIPPA section, on a page
2. Drag the redaction to another page
3. You will be prompted to select another FOIPPA section - DO NOT select a FOIPPA section and click 'Cancel'

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a redaction has been created with a FOIPPA section on a page
WHEN the user drags the redaction box / FOIPPA section to another page
THEN the redaction and FOIPPA section will show up on the new page, in the selected location
AND the redaction and the FOIPPA section will still be 'Grouped'
AND a user will not be prompted to select a new FOIPPA section 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

If no new FOIPPA section is selected when the redaction moved to a new page, redaction boxes and FOIPPA sections become their own annotations, where they can be moved independently of one another. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUVpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--27b963b71cfd05fbe87aeb9b2757ef53609a1300/image.png)

If a new FOIPPA section is selected when the redaction is moved to a new page, the redaction boxes and new FOIPPA sections become 'Grouped', but the old FOIPPA section become it's own annotation. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUlpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2eef5d71d061bc96fa5a700603ac5d45900593ca/image.png)

**Comment by KyEggleston** [comment]
Complete with #4399 and add estimate

**Comment by aparna-aot** [comment]
It seems like the expected behavior has not been correctly captured or updated following our previous discussions. Had a chat with @JHarrietha-AOT . The actual requirement for this ticket is to disable the MOVE option for the redaction boxes (as users will not need to move the redaction boxes across pages), but to keep the RESIZE option enabled so that users can resize and adjust the positions of redaction boxes on the same page. However, users should not be able to move the existing redaction boxes to other pages. cc. @lmullane .

**Comment by lmullane** [comment]
Agreed that users should not be able to move redlines between pages.

**Comment by nimya-aot** [comment]
Confirmed that redactions are not able to move to other pages . Working as expected so closing it
