### ISSUE TITLE
Redactions not working on JPG/PNG files

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4322]
**Describe the bug in current situation**
Redactions not working on jpg/png files 
**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-marshal

**Steps to Reproduce**
1. Go to Records tab
2. Upload few image files
3. Login to redaction app and try to redact image files(jpg/png) 
4. Unable to redact

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdE12IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5514cf51410b5c7648a0d64db93731f4beafd03d/image.png)

**Comment by aparna-aot** [comment]
Redaction of image files is fixed. 
Annotate - Underline is not working for both PNG & JPG/JPEG files in pdftron's demo as well.

**Comment by lmullane** [comment]
Confirmed that this is now fixed.
