### ISSUE TITLE
Doc Reviewer - Findings

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#4325]
- [x] Duplicate page flag calls. After saving the page flag; as an subsequent action page flag APIs are called twice. (Refer snapshot)[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb293IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f845455b787a12dd53be3effa53cb69c60ad2795/image.png)

- [x] Invalid ministry ID passed during edit of sections (Refer screenshot) [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2N4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3cd06c932bece99621336e72614d2b222ce6209d/image.png)

- [x] Document version is hardcoded as "1"
- [x] Multiple annotation call goes for redaction with InReplyTo and without this attribute. Add a condition, if InReplyTo is not there in xml, not call the BE api to save.

**Comment by m-prodan** [comment]
@aparna-aot - can you put an estimate on this when you start investigating

**Comment by m-prodan** [comment]
@aparna-aot - can you put an estimate on this when you start investigating

**Comment by nimya-aot** [comment]
working good, so closing it
