### ISSUE TITLE
Response Layer -> OIPC Layer - Breaks Grouping of All Redactions 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4328]
**Describe the bug in current situation**

When redactions are made on the Redline layer, the redactions show up in the Comments pane as being grouped, which is correct (i.e., the FOIPPA section number is the parent, with the redaction box being grouped with it as an annotation, or child).

![image](https://github.com/bcgov/foi-flow/assets/117312323/1dc37b81-d77d-43bc-a8da-e1bc468e7864)

However, when you change to the Response layer, this grouping broken, and the redaction box and FOIPPA section number are displayed as separate annotations:

![image](https://github.com/bcgov/foi-flow/assets/117312323/a9148c66-f89a-4219-8d0f-7148b6cf5d94)

Then, if you go to the OIPC layer from the Response layer, this grouping is broken:

![image](https://github.com/bcgov/foi-flow/assets/117312323/8afd81a0-8df1-4c3e-a4e1-ed9d7e3d04f3)

This broken grouping is carried over to the Redline layer as well:

![image](https://github.com/bcgov/foi-flow/assets/117312323/7822e84c-2206-469d-93d7-15b2f53b2a3e)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Medium

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-Marshal

**Steps to Reproduce**
1. Under the Redline or OIPC layer, apply a redaction w/ FOIPPA section number to a page (these will be grouped together in Comments pane)
2. Change to the Response layer, and see the error where the grouping is broken (these will show up as separate annotations in the Comments pane)
3. Change to the OIPC layer, and see the error where the grouping as now broken in this layer
4. If you made redactions in the Redline, change to the Redline layer, and see the error where the grouping as now broken in this layer

**Actual/ observed behaviour/ results**

When redactions are made in the OIPC or Redline layer, and you change to the Response layer the groupings are broken. Then, if you go to the OIPC layer next, it will permanently break the existing redaction's grouping in both the OIPC and Redline layers.

**Expected behaviour**

GIVEN a user has applied redactions to the Redline and/or OIPC layer
WHEN the layer is changed to the Response layer
THEN the redaction groupings are maintained in the OIPC and Redline layers

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
@divyav-aot - not specifically related to the 'Group' feature for the redactions (making free text parent of redaction boxes, and grouping them together), but it appears the addition of layers may have impacted the functionality of #4255

**Comment by KyEggleston** [comment]
Standup 2023-08-29 - Response layer broken grouping  - to bring up in super user session, and create new ticket if action needed. Other bugs in this ticket, around other broken grouping in OIPC and Redline layer, will be handled in this ticket and QA'd.

**Comment by m-prodan** [comment]
Note: grouping is fine to break for response package as a possible fix, real issue is that the grouping breaks across all layers.

**Comment by nimya-aot** [comment]
As per @KyEggleston 's comment ,grouping works good for other layers except Response package layer.
