### ISSUE TITLE
PayBC Test - Taking to Wrong Page

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4332]
Title of ticket: 
Noticed in Test that PayBC is in TEST is not taking to the expected page - it is taking to a "cart" page instead and user is not able to complete payment.

Not an issue in prod but should be researched and fixed in test for testing purposes. Awaiting additional info from PayBC Team

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by nimya-aot** [comment]
It is showing up on Katalon reports as well. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDArIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a2487d33460a62318a059b3325f2fc60a869faf6/image.png)

**Comment by lmullane** [comment]
This is resolved.
