### ISSUE TITLE
Attachments - Applicant Tag - Personal Requests

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4333]
* As a an IAO user
* I want attachments with the personal tag to not be visible to Ministry users
* so that I don't inadvertently share more information with the Ministry than I am supposed to

**Assumptions & Scope**	
This is an update to user story #3998

We had received feedback that the applicant tag should remain hidden across both generals AND personal requests.

In addition - our planned migration of historical data will have us tag all records from the correspondence log as "Applicant" as the Ministry does not necessarily need to see all of that information.

What is IN scope?
Updates to accessibility of the applicant tag in personal requests

**Acceptance Criteria**	

Scenario 1: File uploaded with Applicant tag - Personal Requests

* GIVEN a file has been uploaded to the attachment log of a PERSONAL request with the 'Applicant tag'
* WHEN a Ministry user views the attachment log of that request
* THEN any attachment with the applicant tag WILL NOT be visible or accessible by the Ministry user

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@milosdes - can you put an estimate on effort for this one once you have a chance to review?

**Comment by milosdes** [comment]
Is this more of a UX concern or privacy concern? Would probably be a bit simpler to stop ministry users from seeing the 'applicant' tagged documents in their view in the app, and leave everything else as is. Technically then they would still be receiving the data, so if it's a privacy issue it would probably need to be handled differently.

**Comment by m-prodan** [comment]
Sorry for the late reply here @milosdes - it's less a privacy issue and more a "need to know" thing. For personal requests, Ministrys are allowed to know who the applicant is but they don't necessarily need to see all the communication to/from the applicant. 

We did something similar for general requests, I assume just hiding it and making it not visible and therefore not accesible would suffice to meet the need here.

**Comment by lmullane** [comment]
@milosdes as discussed with @m-prodan, putting this request back in progress to resolve the bug.

**Comment by milosdes** [comment]
@m-prodan @lmullane Patch for the bug has been pushed, it should work now in test.

**Comment by lmullane** [comment]
@milosdes, @m-prodan  

The bug we discussed is now resolved. 

And the AC has passed as attachments tagged 'applicant' are not visible to the ministry user for personal requests.

However, #3998 is no longer working; an attachment with an the 'applicant' tag is visible to the ministry user in a general request: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnA4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--97408e095c9cd0933cc82e2b04fc3089c27fa7b4/Screenshot%202023-09-07%20at%204.24.32%20PM.png)

But only 1 of 2 'applicant' tagged attachments are displaying for the ministry user. There is 2 - see below:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0o4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--edf90cff575437fdd3ba5bb2a18b5e9729d65219/Screenshot%202023-09-07%20at%204.40.11%20PM.png)

**Comment by lmullane** [comment]
@m-prodan, lets discuss tomorrow. #3998 may have already been broken.

**Comment by nimya-aot** [comment]
@milosdes  For the personal requests, attachments with applicant tag is still visible to ministry users. Could you please check? 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXlRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3851eab60785b8e7f7e2c7dd6a24708b876c2f64/applicant_tag.png)



[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckNRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1d743e51f2a51c97b9c7aeea682616493ebcb706/applicant_tag1.png)

**Comment by m-prodan** [comment]
Hi @nimya-aot - I was actually looking at closing this ticket... did you do your QA in test marshall? This is actually in regular test - it seems to work there as expected

**Comment by nimya-aot** [comment]
@m-prodan Sorry, I tested it on test-marshal. You are free to close this one then

**Comment by m-prodan** [comment]
QA passed - closing ticket.
