### ISSUE TITLE
Intake in Progress - Section 5 Pending State

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4334]
* As an Intake User
* I want better visibility into the state of my request
* so that I can tell quickly what I am waiting for on each request

**Assumptions & Scope**	
This story comes from feedback from the Intake team where they are finding the 'Intake in Progress' state alone does not give their team valuable insight into what is actually happening with a request. 

This story will add additional state options from the 'Intake in Progress' state to allow Intake analysts to better manage their caseload.

When users shift to these states, they will have the same options available to them as Intake in Progress when they activate the state drop down.

Shifting to these states will also trigger an automated notification as Intake has standard follow up times before they close requests as abandoned.

These additional states from Intake in Progress can have the same colour pallette as Intake in progress

What is IN scope?
New state and state changes from Intake in Progress. on Personals

What is NOT in scope?
Notification reminder for the on-hold state - covered in a separate story.

**Acceptance Criteria**	

**Scenario 1: Intake in Progress - Personal Request - State Change Options**
* GIVEN an IAO user is on a PERSONAL request in the state 'Intake in Progress'
* WHEN they select the state drop down
* THEN they will see the following options: Open, Peer Review, Redirect, Section 5 Pending, Closed

**Scenario 2: Intake in Progress - Personal Request - Section 5 Pending**
* GIVEN an IAO user is on a PERSONAL request in the state 'Intake in Progress'
* AND they have activated the state drop down
* WHEN they select Section 5 Pending
* THEN the state change modal will appear with the option to continue or cancel

**Scenario 3: Intake in Progress - Personal Request - Section 5 Pending**
* GIVEN an IAO user is on a PERSONAL request in the state  change modal for Section 5 Pending
* WHEN they click continue
* THEN the state change modal will close
* AND the state will update to "Section 5 Pending"

**Scenario 4: Section 5 Pending - State Change Options**
* GIVEN an IAO user is on a request with the state Section 5 pending
* WHEN they activate the state drop down menu
* THEN they will see the following options: Open, Peer Review, Redirect, Closed

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Section 5 and app fee states from Intake in progress. Shouldn't really need a design update for this one, I figure we can use existing color scheme for intake in progress for these two.

cc @JHarrietha-AOT @arielleandrews @lmullane

**Comment by lmullane** [comment]
@-prodan, nicely written AC.

- Do we need AC for changing the state to Peer Review or is that covered in an earlier ticket?
- Can I confirm that On Hold - Application Fees will be a different state than On Hold - Processing Fees? Either way we will likely need a story to update the On Hold state to say Processing Fees to be consistent.
- Scenario 4 for the notification should also include posting the notice as a comment. Usually we put the notification and comment for a state change as a separate story. Suggest we do so here too.

**Comment by m-prodan** [comment]
There is an AC that includes Peer review as an option to update the state from Section 5 pending, so that should be covered.

Agreed that we'll likely want to update the processing fee state to be more clear as well.

And as discussed - there is now a separate story to address notifications and comments on their own ticket

**Comment by sumathi-thirumani-aot** [comment]
Need a confirmation (personal + intake in progress) brings the state "pending".

**Comment by sumathi-thirumani-aot** [comment]
Tech Info:
1. FE
2. BE: Scripts to support data capture + adhoc

**Comment by m-prodan** [comment]
Yes confirming section 5 pending is a personals state

**Comment by nimya-aot** [comment]
working as expected , so closing
