### ISSUE TITLE
Records Tab - Email Files - Show Embedded Images In Message Body When Converted to PDF

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4339]
* As a user
* I want embedded images in email files to show up in the message body when converted to PDF
* so that the integrity and structure of the records is maintained

**Assumptions & Scope**	
What are the assumptions for this story?

Currently, when email file types (e.g., .msg) are converted to PDF, the embedded images that show up in the message body are pulled out of the message body, and show up on the separate page (under the parent email file) in the Records tab, and in the consolidated harms PDF. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTFFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b7995f1f96e4578fd25058d5c8b05609361281dc/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTVFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bed1a148257c89ff88d92e85bf5c3611f432536/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakZFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--54a91669f73578d73b9de2dc9c98a7f3ece151fc/image.png)

To ensure records maintain their integrity when being sent to the applicant, embedded images in email files need to be retained in the message body of the the email file when it is converted to PDF, rather than being pulled out and displayed on a separate page. 

Embedded files that are not image file types will continue to be treated the same (i.e., pulled out and displayed on a separate page). 

What is IN scope?
Embedded images (image file types) in the message body of email files

What is NOT in scope?
Email file attachments
Other embedded file types (i.e., file types that are not image files)

**Acceptance Criteria**	

**Scenario 1: Embed Image in Email - Conversion**
* GIVEN a user has uploaded an email file to the Records tab
* AND the email file has an image embedded in the message body
* WHEN the email file is converted to PDF
* THEN the embedded image will show up in the message body of the converted email file
* AND the embedded image file name will show up in the 'Attachments' line of the email file in the converted PDF and consolidated harms PDF
* AND the embedded image will not show up on a separate page in the converted PDF or consolidated harms PDF
* AND the embedded image file / file name will not show up as a child file in the Records tab

**Scenario 2: Other Embedded Files in Email**
* GIVEN a user has uploaded an email file to the Records tab
* AND the email file has file types embedded in the message body that are NOT image file types
* WHEN the email file is converted to PDF
* THEN the other embedded file types will show up with a flattened file icon in the message body of the converted email file (see image below)
* AND the embedded file name will show up in the 'Attachments' line of the email file in the converted PDF and consolidated harms PDF
* AND the embedded file will show up on a separate page in the converted PDF or consolidated harms PDF
* AND the embedded file will show up as a child file in the Records tab

![image](https://github.com/bcgov/foi-flow/assets/117312323/975b7e51-1960-4dca-9909-e31282d66cbb)

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KyEggleston** [comment]
@m-prodan - I've updated this now

**Comment by KyEggleston** [comment]
Will need to broadly test Records tab file upload functionality (specifically, parent/child files, such as email file types), file conversion, and the harms package (including consolidated harms PDF)

**Comment by sumathi-thirumani-aot** [comment]
To discuss
=======
1. More details required on the [insert of attachments] in outlook.
2. Embedded images are already resolved as part of sprint : [link]
3. MVP for attachment information[Is icon necessary; since it is flattened ?]

**Comment by m-prodan** [comment]
For scenario 2 - as discussed, icon would be preferred, but if this is too difficult technically we can go with text indicating there was embedded files there.

**Comment by liseandtea** [comment]
@nkan-aot Hey! Are these supposed to convert to PDF after uploading the native file into Mod and then downloading it for harm? If so, that is only happening for the division whose records are an email with no images as attachments. I tested this in marshal with ECC-2023-40010 and got the same results whether I was an IAO user or Ministry Coordinator.
[Uploading... 1.jpg]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9VQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7dcb716bfc675d164cc3d77642d1eb27fb6c4c05/2.jpg)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82c72906efb1e5dd0ac870116a0a1a3382b5697c/3.jpg)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a10e14a8a20c342aa2461b9e8c3c611f970294b9/4.jpg)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2df8a3cd26367e1d79aad07d888e60dff9093edc/5.jpg)

**Comment by nkan-aot** [comment]
it should convert automatically when you upload and then you can check using the "download converted"
I did not change any code related to harms zipping so if there are issues there it might be a separate bug
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGNmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--505b38dae7a710b198c73e1e3be8ba35c5b63560/image.png)

**Comment by KyEggleston** [comment]
@nkan-aot 

See EDU-2023-66774 in Test-Marshal for examples. 

Looks like the embeds are being retained in the message body for emails with no attachments or children email files. So the simple files/conversions are working. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/ed55b211-9145-4ad1-926e-30dacfa4421e)

Showing up correctly in message body:

![image](https://github.com/bcgov/foi-flow/assets/117312323/4410095f-c70f-45e7-8a25-8b6c3cb124a1)

In addition, there are no issues when a parent email file containing embeds has attachments that are not email files (e.g., it has PDF, XLS or DOCX attachments).

![image](https://github.com/bcgov/foi-flow/assets/117312323/5e804751-d318-44b9-a2f8-57bf36a0f30a)

When a parent email file has no embeds, but it has a child email file with embeds, this is being uploaded and converted successfully.

![image](https://github.com/bcgov/foi-flow/assets/117312323/937e2db5-4c6e-49dc-8175-3fb1388c0f7f)

However, when a parent email file has embeds, and it also has a child email file with embeds, this is not being uploaded and converted successfully, and is going into error.

![image](https://github.com/bcgov/foi-flow/assets/117312323/7891bc69-b386-43a9-a0b8-03d1bec35bd6)

In addition, when a parent email file has embeds, but the child email file does not have embeds, this is still being thrown into error. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/1484875c-7d6f-40c8-95f1-0c0fa0381aa2)

It looks like there's an issue when a parent email file has an embed, and then have a child email file attached to it (level 2 and beyond) 

Will add any other findings here, but just wanted to note this.

**Comment by KyEggleston** [comment]
@nkan-aot - errors above appear resolved. However, I noticed that emails that are in draft, and uploaded to the Records tab, are being thrown into error. See EDU-2023-67435, and the files below.  I've confirmed in TEST that emails in draft that are uploaded to the Records tab are being converted and deduped successfully. So just want to make sure this wasn't introduced. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/be20b7ba-5fc2-4315-83ff-b8835211f26b)

Can make new bug ticket if needed, as it may be unrelated to this.

**Comment by KyEggleston** [comment]
Samples added to EDU-2023-559988 in DEV

**Comment by nimya-aot** [comment]
@nkan-aot Embedded images still appears on next page when we download the harms. Could you please check this request?
https://test-marshal-foirequest.apps.silver.devops.gov.bc.ca/foi/foirequests/743/ministryrequest/743

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkVIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51494ebcc3f42f063e2d1b3714635ac9614b5a8a/image.png)

**Comment by nimya-aot** [comment]
@nick-aot If we have 2 images embedded on a msg file horizontally, then only one image is showing up while downloading the harms. Could you please check?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzhJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e3db3c2f737f925fe9f024e0ef68638198f3b7f/image.png)



Please check the request  
 https://test-marshal-foirequest.apps.silver.devops.gov.bc.ca/foi/foirequests/744/ministryrequest/744    on test -marshal

**Comment by nkan-aot** [comment]
I was able to get both images to show up but they are on different lines, just wanted to check with business if this is acceptable. Reason is they are too wide to fit in one line. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXNOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80db2c0ae7fe568f477783df1fce408e9bbb2ee8/image.png)

**Comment by nimya-aot** [comment]
@nkan-aot Msg files with images embedded is failing when upload to records tab. Could you please check?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2dQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90d8cebd99bd4b79a505499fe35a4729d385ce4c/image.png)

**Comment by nimya-aot** [comment]
@nkan-aot The attachment file name not replacing for this one. Could you please check ?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0FVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c8d8dc17e9c2f7720e4245acc822b6f9d1d3883/image.png)

**Comment by nimya-aot** [comment]
@nkan-aot The attachment file name not replacing for this one. Could you please check ?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0FVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c8d8dc17e9c2f7720e4245acc822b6f9d1d3883/image.png)

**Comment by m-prodan** [comment]
Sorry just responding late to this - if they show up on different lines, that is fine with me.

**Comment by nimya-aot** [comment]
@nkan-aot yesterday' s rich text file is failing today. Could you please check?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEVjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--848b591f067dddbd8a84bed3d0ab345343fddc4d/image.png)

**Comment by KyEggleston** [comment]
I also added the heavily formatted emails to our TEST package of files - nothing confidential!

**Comment by KyEggleston** [comment]
@nkan-aot - I did find an email sample from PROD throwing errors as well - its on FOR-2023-30509. Happy to connect outside Github to give details

**Comment by KyEggleston** [comment]
On EDU-2023-994433 in Test-Marshal, no errors with the test package of .msg files, and the samples from PROD (including those previously causing errors) are all fine now. I did note that .jpeg files aren't being stitched into the harms package in Test-Marshal, but in Test it's fine... I'm sure we didn't do anything to that logic, so it may just be a Test-Marshal issue.

**Comment by nimya-aot** [comment]
@nkan-aot I used the test file "Parent in draft with embed and child with embed.msg" from our testing package. I noticed that on harms pdf, I am unable to find the attachment named as "image002.jpg". Also "imageoo1.jpg" is an attachment of other msg file. Could you please check?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemtqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e8f9ede2ebfe2b968c6dd36d5a6ad25c2649a54/image.png)

**Comment by KyEggleston** [comment]
I think what's happening is embedded images are still being considered attachments in the email, and therefore, their file name is listed under the 'Attachments' line. However, the embedded images are not being pulled out as separate pages. So, I suppose the question is whether embedded image file name can be removed from the 'Attachments' line after the file is converted to PDF, and only child files are listed in the 'Attachments' line.

**Comment by nimya-aot** [comment]
@nkan-aot on this msg file , no embedded image file name on the attachments list. We need to make it consistence, either embedded name on the attachment list or else needs to pull it from attachment list
<img width="1114" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1VwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b13a3c190900f6e6018fdceca9cda3cbf34ff0a/image.png" alt="image.png" />

**Comment by KyEggleston** [comment]
Chatted with Intake - embedded image names not being included in the 'Attachments' line after conversion seems to be the best practice. Best to only have actual attachments listed in the Attachments line.

**Comment by nimya-aot** [comment]
working as expected, so closing

**Comment by KyEggleston** [comment]
This needs a new release label - removed from 9.2 release and will be added to subsequent release.

**Comment by nimya-aot** [comment]
working as expected, so closing
