### ISSUE TITLE
Redaction App - Unable to Specify Pages in 'Save As' 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4343]
**Describe the bug in current situation**

In the redaction app / doc reviewer, the OOTB 'Save As' functionality is not allowing users to specify pages to include in the save file. See images below. 

This may have been introduced when we implemented the stitching. The 'Save As' option will be valuable to have working come go-live, as it was intended to be used to produce packages for consultations (as we will not have this functionality built yet). To produce consultation pages, users will need the ability to specify what pages to include (i.e., those flagged with the 'Consult' page flag and consultee).

Currently, the 'Specify Pages' in the 'Print' menu option works correctly (in that you can select specific pages from across the package). This is how the 'Specify Pages' under the 'Save As' menu option should work. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Medium

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

Test-Marshal
See EDU-2023-889944

**Steps to Reproduce**
1. Select 'Save As' on a request in the redaction app
2. Select 'Specify Pages' and enter several page numbers or page ranges
3. Click off the open text field

**Actual/ observed behaviour/ results**

Unable to use 'Specify Pages' to select a range of pages to save. This may also only be looking at the pages in the first file in the package.

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a user has selected 'Save As'
AND selected 'Specify Pages'
WHEN the user enters multiple pages or page ranges from across various files in the package
THEN the pages will be accepted
AND when the file is saved, only the specified pages will be included

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanBMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1c959b1deee0a614f0f5d5be9641e841ce62af31/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaU5MIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb1867a887e56f015f73785d1f6e445357c8de7d/image.png)

This is working correctly in the 'Print' menu option, where I can specify pages throughout the package to include. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/0246ee88-94ce-449b-9e96-a949b2e1c644)

**Comment by nkan-aot** [comment]
bumping estimate to 5, as the fix for this involved updating pdftron to latest version and testing + fixing bugs related to the update

**Comment by nimya-aot** [comment]
working good , so closing it
