### ISSUE TITLE
Bulk operation optimization [DocReviewer]

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#4351]
DOD
===
- [x] Limit pageflags bulk operation to 250 [FE Validation]
- [x] Limit Annotation bulk operation to 250  [FE Validation]
- [x] Changes in Annotation model to support bulk
- [x] Changes in Annotation Section model to support bulk
- [x] Changes in PageFlag to support bulk (Audit) (NA)
- [x] Load Testing

**Comment by sumathi-thirumani-aot** [comment]
Bulk page flag (Testing)
50 -> 129ms
100 -> 203ms

**Comment by sumathi-thirumani-aot** [comment]
Bulk page flag Testing [No. of pages - 3781/3781]
50 -> 470ms
100 -> 1.5s
200 -> 
250 ->

**Comment by sumathi-thirumani-aot** [comment]
Bulk page flag Testing [No. of pages - 3781/3781]

**Comment by sumathi-thirumani-aot** [comment]
Bulk page flag Testing [No. of pages - 3781/3781]
50 -> 
100 -> 
150 ->
200 -> 
250 -> 6.31s (sections) 5.42s(annotation)

**Comment by sumathi-thirumani-aot** [comment]
Bulk Comment update sections [No. of pages - 3781/3781]
50 ->
100 ->
150 ->
200 ->
250 ->

**Comment by sumathi-thirumani-aot** [comment]
Bulk redaction [No. of pages - 3781/3781]
50 -> 
100 ->
150 ->
200 ->
250 ->

**Comment by sumathi-thirumani-aot** [comment]
Option-1: Disable after selection of 250.
Option-2: Show Modal.

**Comment by nimya-aot** [comment]
@sumathi-thirumani-aot created the following  bug while regression testing. https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4574

**Comment by nimya-aot** [comment]
closing it as completed
