### ISSUE TITLE
Intake in Progress - Assignment/View Permission Update

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4352]
* As an Intake analyst
* I want to be able to assign an intake in progress request to another team
* so that they can continue the intake process

**Assumptions & Scope**	
This story comes from the fact that certain Ministry requests are going to have intake functions handled by the processing team for the foreseeable future. As a result, and with some of the additional features we will enable for Intake in Progress the Intake team will need the ability to assign requests in Intake in Progress to the processing team. 

While this requirement is mainly for the MSD and CFD teams, we should not restrict to any one team to account for any future changes to processing team responsibilities (eg - MSD moving to a different team).

In addition - this should only be for personal requests, as IAO Intake will continue to manage intakes of general requests since they have lesser complexity.  

What is IN scope?
IAO Assignments for Intake in Progress and related states (section 5), for personal request type only.

What is NOT in scope?
General request type is not in scope of this ticket

**Acceptance Criteria**	

**Scenario 1: Intake in Progress - Assignment Options**
* GIVEN an Intake user is on a Personal request in Intake in Progress
* WHEN they activate the assignment drop down
* THEN they will see the Intake team
* AND all other processing teams available to assign.

**Scenario 2: s. 5 Pending - Assignment Options**
* GIVEN an Intake user is on a Personal request in s. 5 pending state
* WHEN they activate the assignment drop down
* THEN they will see the Intake team
* AND all other processing teams available to assign.

**Scenario 3: xxxxxx**
* GIVEN an Intake user is on a Personal request in s. 5 pending state or Intake in Progress state
* AND they have activated the assignment drop down
* WHEN they select a user or team
* THEN the request will be assigned to the user/team

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by sumathi-thirumani-aot** [comment]
Need confirmation on the processing team names to be considered for "pending" state.
Reference:
Scanning Team
Central Team
Justice Health Team
MCFD Personals Team
Resource Team
Intake Team
Flex Team
Social Education
Business Team

**Comment by sumathi-thirumani-aot** [comment]
Tech info:
BE changes
1. Migration script

**Comment by m-prodan** [comment]
Processing Teams that need to be able to assigned Intake in Progress requests:
* Children and Family Team
* Children and Education Team
* Community and Health Team

**Comment by sumathi-thirumani-aot** [comment]
MSD and CFD  + Personal (Assumption)

**Comment by nkan-aot** [comment]
chatted with @m-prodan and processing teams will be available in peer review state as well but not redirect

**Comment by lmullane** [comment]
Thanks, @nkan-aot. Closing as complete.
