### ISSUE TITLE
.PPTX files in Redaction App - Not displaying all pages in left pane

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4355]
**Describe the bug in current situation**

When .PPTX files are uploaded to the Records tab, and displayed in the Redaction App, the full list of pages for each .PPTX file is not displayed in the left pane. 

For example, see the image below. There are three .PPTX files in this package, which have more than one page. However, when you look at the left pane, you will note that only one page is displayed under each file. In addition, you will note that the other pages in the .PPTX file are not displayed in the left pane. 

Because of this, you will also notice the page counts in the left pane 'jumps' from one file to the next. For example, you will see it jump from Page 23 -> Page 27 -> Page 31 -> Page 35. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcU5VIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--27e32f15c44ff34ba93c7e3c2911c49e9c9ed912/image.png)

The other pages in the PPTX files are not displayed in the left pane, but they are still counted as pages. It's important to note, in the middle or 'working' pane, you can access and scroll through these pages. So it appears the issue may be specifically with the left pane.

For example, in the below image I can correctly go to Page 32 in the package in the working or middle pane, but this page is not reflected in the left pane.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXhVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1347a99c51e09a1fad32fe003f51cc6a882fe60a/image.png)

**Link bug to the User Story**

**Impact of this bug**
Medium

**Chance of Occurring (high/medium/low/very low)**
Low

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

Test-Marshal
See EDU-2023-22226

**Steps to Reproduce**
1. Upload PPTX files to the Records tab for a request, which have >2 pages
2. Access the Redaction App through the request
3. See the left pane, where the page counts 'jump', and pages are not displayed in the left pane under the PPTX files
4. In the working or middle pane, you will still be able to access these pages

**Actual/ observed behaviour/ results**

Aside from the first page in a PPTX file, the other pages are not listed in the left pane

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language.

GIVEN pptx files have been uploaded to the Records tab, converted to PDF, and show up in the Redaction App 
WHEN view the files and pages in the left pane
All pages for a given PPTX file are displayed

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Pre-Deployment Steps**
set env for dedupe and dedupe large files DEDUPE_RECORD_FORMATS

**Comment by sumathi-thirumani-aot** [comment]
Estimated already as 2 and "in-review"

**Comment by nimya-aot** [comment]
@nkan-aot The last page of the pptx file is missing on the left pane. Could you please check that again? It is for request number #EDU-2023-1021 on test-marshal.
 [Uploading... image.png]

**Comment by m-prodan** [comment]
moved back to review @nkan-aot

**Comment by nimya-aot** [comment]
It is working good. So closing the ticket
