### ISSUE TITLE
Download For Harms - Including Original File types (and consolidated PDF)

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4356]
**Describe the bug in current situation**

**Link bug to the User Story**
User report a production bug. When they downloaded for harms, they get a consolidated PDF, which appears to include all converted records, but it also still included the original file types. 

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. Impacted prod files include IRR-2023-32191, 32200, 32208

See MS Teams Thread: https://teams.microsoft.com/l/message/19:NpzE5fJOWvS_q3nLc1CPx88d_H0ajz4XUViwklJSMkE1@thread.tacv2/1693418306937?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=6cfce8ce-4358-4cd5-aff0-9e1420e189be&parentMessageId=1693418306937&teamName=External%3A%20FOI%20Modernization%20Support&channelName=General&createdTime=1693418306937&allowXTenantAccess=false

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
This is a stale bug. and has since likely been resolved through numerous hotfixes/patches. Closing.
