### ISSUE TITLE
Save Redline pdf is not working if record package has jpg files

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4359]
**Describe the bug in current situation**
If the record package has jpg files, then unable to save redline pdf for ministry sign off

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
High

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-marshal

**Steps to Reproduce**
1. Go to Ministry login
2. Upload some documents including jpg files
3. Login to IAO login and try to save redline pdf for Ministry sign off
4. It is in loading state for a long time

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckJXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1deb8af06e2aab90c6de2506f333bb59e38f8c31/image.png)

**Comment by richard-aot** [comment]
This bug is fixed in dev-marshal. Waiting for pushing to test-marshal.

**Comment by lmullane** [comment]
Confirmed this is now fixed in TEST marshal.
