### ISSUE TITLE
MCFD Personals Requests - Tagging and Scanning States

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4362]
* As an IAO MCFD User
* I want to be able to flag requests for tagging or scanning
* so that I can better understand what actions need to be taken on requests

**Assumptions & Scope**	
This story is a need for the MCFD team to be able to better identify where their specific requests are at once physical copies of the records are received.

In this story, unlike the typical flow, IAO users will be able to update the request state from Call For Records to the relevant state to flag the next stag of processing. This will be specific to CFD and MSD requests only, as these are the only two Ministries with scanning activities for their records.

IAO will also be able to update the request state to "Records Review" from the scanning states, as scanning is often the final activity prior to the packages being ready to review.

**Note: The auto-reassigning to the scanning team only occurs when the analyst is not currently a scanning team member. If they are a scanning team member the request will remain assigned to them.**

**Note: The CFR countdown clock will stop counting down when it moves to scanning or tagging**

What is IN scope?
State change updates specific to CFD and MSD Personal requests

What is NOT in scope?
Any other Ministry

**Acceptance Criteria**	

**Scenario 1: MCFD or MSD Personal Request in Call For Records**
* GIVEN an IAO user is on a MSD or MCFD Personal Request in Call For Records
* WHEN they activate the state change drop down
* THEN they will see the following options: Open, Tagging, Ready to Scan, and Closed

**Scenario 2: CFD/MSD Personal Request - Tagging**
* GIVEN an IAO user is on a MSD or MCFD Personal Request in Call For Records
* AND the state change drop down is active
* WHEN they click on 'Tagging'
* THEN the state change modal will appear

**Scenario 3: CFD/MSD Personal Request - Tagging - Activate Continue**
* GIVEN an IAO user is on a MSD or MCFD Personal Request in Call For Records
* AND the state change modal for tagging is active
* WHEN they click on 'Continue'
* THEN the state change modal will disappear
* AND the state of the request will update to tagging
* AND the CFR countdown will no longer show on the left-nav tab

**Scenario 4: Tagging - State Change Options**
* GIVEN an IAO user is on a MSD or MCFD Personal Request in Tagging
* WHEN they activate the state change drop down
* THEN they will see the following options: Call for Records, Ready to Scan, Records Review and Closed

**Scenario 5: CFD/MSD Personal Request - Ready to Scan**
* GIVEN an IAO user is on a MSD or MCFD Personal Request in Call For Records or Tagging
* AND the state change drop down is active
* WHEN they click on 'Ready to Scan'
* THEN the state change modal will appear
* AND the CFR countdown will no longer show on the left-nav tab

**Scenario 6: CFD/MSD Personal Request - Ready to Scan - Activate Continue**
* GIVEN an IAO user is on a MSD or MCFD Personal Request in Call For Records
* AND the state change modal for 'Ready to Scan' is active
* WHEN they click on 'Continue'
* THEN the state change modal will disappear
* AND the state of the request will update to 'Ready to Scan'
* AND the request will auto-assign to the IAO Scanning Team

**Scenario 7: Ready to Scan - State Change Options**
* GIVEN an IAO user is on a MSD or MCFD Personal Request in Ready to Scan
* WHEN they activate the state change drop down
* THEN they will see the following options: Call for Records, Tagging, Records Review and Closed

**Scenario 8: Records Review - State Change Options**
* GIVEN an IAO user is on a MSD or MCFD Personal Request in Records Review
* WHEN they activate the state change drop down
* THEN they will see the following options: Call for Records, Tagging, Consult, Ministry Sign Off, Peer Review, Response and Closed

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Took a run at these scanning/tagging states - tried to keep it relatively flexible so that states can be changed more easily. Note - these states will be limited to MSD and CFD Personal requests only. I added the last scenario to account for the potential of a file being strictly electronic records, Ministry would update to records review, and analyst can determine if e-tagging is required and flip it to tagging.

**Comment by m-prodan** [comment]
cc @JHarrietha-AOT @lmullane

**Comment by lmullane** [comment]
Looks good, Matt. 

Do we need to run this by anyone or are we good to proceed? Might be nice to loop in the processing and Intake managers.

**Comment by sumathi-thirumani-aot** [comment]
CFR Clock information required

**Comment by sumathi-thirumani-aot** [comment]
Tech Info
1. FE
2. BE
- Migration script
- WF behavior check

**Comment by sumathi-thirumani-aot** [comment]
CFR clock will be keep running.

**Comment by lmullane** [comment]
@JHarrietha-AOT, will need colour codes for the new states.

**Comment by lmullane** [comment]
We need to update the ACs to show the new request states in the ministry queue and the IAO queue.

cc @m-prodan

**Comment by JHarrietha-AOT** [comment]
Passed UX Assurance

**Comment by nimya-aot** [comment]
@abin-aot When we move the request to 'Ready to scan' then request is not auto assigning to ' Scanning team'. Could you please check? 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGJyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0f56dd3f9a3c67b4ad90e0a61f9bd96324f9e5b4/image.png)

**Comment by m-prodan** [comment]
note from release planning - there is no need to put request on hold, assumption was more around the CFR countdown will no longer appear on left-nav tab, I have updated AC to make this more clear

**Comment by liseandtea** [comment]
@abin-aot Hey! All AC pass with the exception of scenario 8 where tagging needs to be added as a potential state change. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3N2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df8200276b6eadeef437516ebc46f234f054806e/Screenshot%202023-10-12%20134556.jpg)

**Comment by abin-aot** [comment]
[Uploading... image.png]

Updated @liseandtea

**Comment by abin-aot** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXcyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1723889850552fc3ee349c18ccfded85ed317f82/image.png)
Updated @liseandtea

**Comment by liseandtea** [comment]
Closing ticket - all AC pass.
