### ISSUE TITLE
RequestDocuments' updated_at attribute being updated for all previous versions

### ISSUE THREAD

**Issue by milosdes** [bcgov/foi-flow#4366]
**NOTE: This bug has already been fixed as part of 4200**
**Describe the bug in current situation**
Whenever a new version of a document is created, all of the previous versions have their updated_at attributes updated with the current time as well. 

**Link bug to the User Story**

**Impact of this bug**
It looks like all documents of all users are being impacted. 

**Chance of Occurring (high/medium/low/very low)**
high (100%)

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
In local development and test-marshall/dev-marshall.

**Steps to Reproduce**
Happens whenever a new version of a document is created. For example, when 'renaming' an uploaded attachment. 

**Actual/ observed behaviour/ results**

**Expected behaviour**
The updated_at attributes for all previous versions of the document should remain unchanged.

**Screenshots/ Visual Reference/ Source**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalpoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c74751d2f6f5d63b6bc925a66922979ad7b55f2a/Screenshot%202023-09-01%20at%2011.00.11%20AM.png)

**Comment by milosdes** [comment]
This bug has already been fixed as part of ticket 4200

**Comment by m-prodan** [comment]
Closing with 4200
