### ISSUE TITLE
Notification Reminder and Comment - On-Hold Application Fee

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4369]
* As an Intake User
* I want a notification reminder/comment when 20 business days has passed
* so that I know when I need to take action to close my request

**Assumptions & Scope**	
This is related to 4368 - Intake users give applicants 20 business days to pay the outstanding application fee. After 20 business days, the request can be closed as abandoned.

What is IN scope?
Notifications and sys-generated comments related to the On-Hold Application Fee State

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: On-Hold - Application Fee - Notification Reminder**
* GIVEN an IAO user has changed the state of a general request to On-Hold - Application Fee
* WHEN 20 business days have elapsed from the date the state change was made
* THEN a notification will send to all assigned users and watchers with the message: "Request ID - 20 business days has passed awaiting payment, you can consider closing the request as abandoned 

**Scenario 2: On-Hold - Application Fee - System Generated Comment**
* GIVEN an IAO user has changed the state of a general request to On-Hold - Application Fee
* WHEN 20 business days have elapsed from the date the state change was made
* THEN a comment will be posted to the request history: Request ID - 20 business days has passed awaiting payment, you can consider closing the request as abandoned 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Notification and comment re: on hold app fees.

cc @lmullane

**Comment by sumathi-thirumani-aot** [comment]
Duplicate of 4368 (ACs)

**Comment by milosdes** [comment]
The "Request ID" in the message "Request ID - 20 business days has passed awaiting payment, you can consider closing the request as abandoned"

Is this referring to the axisrequestid eg. EDU-2023-09112314 or the actual requestid which appears at the end of the URL when viewing a request eg. 1717 from the url: test.foirequests.gov.bc.ca/foi/reviewrequest/**1717**  ?

**Comment by milosdes** [comment]
@m-prodan @aparna-aot  what should "createdby" be on the backend for the comments and notifications?
I put "System" for the moment. When a payment is made though, the createdby shows as "Online Payment". Just want to confirm this
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbERzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4b6370f405c729d504a96d4c85da3d48fd8b4399/Screenshot%202023-09-28%20at%203.51.10%20PM.png)

**Comment by aparna-aot** [comment]
@milosdes 

- The "Request ID" in the comment "Request ID - 20 business days has passed awaiting payment, you can consider closing the request as abandoned" is the axisRequest Id like this : 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXpzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--10e6b9f067f87c76e9c996005059bf30d2a392fb/image.png)

- what should "createdby" be on the backend for the comments and notifications? - System should be fine as the comment and notifications are shown as generated by the system. You can refer to other reminder notifications in the db.

**Comment by m-prodan** [comment]
per a clarifying question - the business day calculation should exclude weekends and holidays in factoring the 20 days.

**Comment by m-prodan** [comment]
confirmed via request queue and checking the comments that notifications have triggered. Before moving to prod - make sure we update the configured value to 20 business days from 1.

cc @milosdes @Aman-Hundal
