### ISSUE TITLE
Notification Reminder and Comment - Section 5 Pending

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4370]
* As an Intake User
* I want a notification reminder/comment for section 5 pending when 10 business days has passed
* so that I know when I need to take action to close my request

**Assumptions & Scope**	
This is related to 4334 - Intake users give applicants 10 business days to meet section 5. After 10 business days, the request can be closed as abandoned.

What is IN scope?
Notifications and sys-generated comments related to the On-Hold Application Fee State

**Acceptance Criteria**	

**Scenario 1: Section 5 Pending - Notification Reminder**
* GIVEN an IAO user has changed the state of a personal request to Section 5 Pending
* WHEN 10 business days have elapsed from the date the state change was made
* THEN a notification will send to all assigned users and watchers with the message: "Request ID - 10 business days has passed awaiting section 5, you can consider closing the request as abandoned 

**Scenario 2: Section 5 Pending Reminder - System Generated Comment**
* GIVEN an IAO user has changed the state of a personall request to Section 5 Pending
* WHEN 10 business days have elapsed from the date the state change was made
* THEN a comment will be posted to the request history: Request ID - 10 business days has passed awaiting section 5, you can consider closing the request as abandoned

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by sumathi-thirumani-aot** [comment]
Tech Info:
1. BE (Changes in reminder service)

**Comment by nimya-aot** [comment]
@m-prodan Do we need to send notification  to watchers/assignees when the state changes to "Section 5 Pending"?(like   'Moved to 'Section 5 Pending')

**Comment by m-prodan** [comment]
confirmed via request queue and checking the comments that notifications have triggered. Before moving to prod - make sure we update the configured value to 10 business days from 1.

cc @milosdes @Aman-Hundal

**Comment by Aman-Hundal** [comment]
@m-prodan will do - thanks Matt!
