### ISSUE TITLE
Blank Code - Entering Comment/Reply in Comments Tab Adds it as FOIPPA Section Stamp Text

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4372]
**Describe the bug in current situation**

When you apply a blank code to a redaction, add a comment/reply for the redaction, it will add the comment/reply as the FOIPPA section. This was an unintended consequence from #4255.
 
**Link bug to the User Story**

**Impact of this bug**
High

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-Marshal

**Steps to Reproduce**

Add blank FOIPPA section.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTFoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6416151585c7278de03c8266acaff261c0b82eb0/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTVoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a77a00b1c091b544473c31600beb02cbbf782d09/image.png)

Add a comment or reply related to the redaction

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckJoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--afc02ad73e91cd08315cf8b4366dbfae26d5daf8/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0poIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6a8870588c5a9e8b1079ba0618f92e0aad85f1f1/image.png)

The comment or reply will show up in the FOIPPA section box

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBck5oIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e5514582b810d145ebf33c1a84a5a40efa16e4bc/image.png)

As a result, this will show up when you produce a package

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnhoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26e29daeaf32a6836741ed83ea6d615e0e0dc27f/image.png)

**Actual/ observed behaviour/ results**

Comment or reply to 'Blank' code redaction adds comment or reply in FOIPPA section textbox

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a blank code has been applied for a redaction
WHEN a user comments or replies to the redaction in the Comments pane
THEN the comment or reply is posted
AND the FOIPPA section textbox in the middle/working pane remains blank.

**Comment by KyEggleston** [comment]
Assumption is this also affects the redline and response packages saved and download as well.

**Comment by nimya-aot** [comment]
Working on test-marshal, so closing it
