### ISSUE TITLE
Multi-Select automatically selected when clicking redaction

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4374]
**Describe the bug in current situation**

At the pilot user session, many users noted that the multi-select always becoming 'activated' was very jarring and annoying, and may lead to errors. 

E.g., Multi-select is automatically selected/activated when clicking on redaction box in middle working pane, or after adding a redaction and clicking off it. This stops users from adding comments, at least until they unselect multi-select, and may lead to inadvertent actions.

I recall discussion that this may be difficult to address, so may need discussion around how to handle. This is just a consequence of implementing #4255 

Ideally, multi-select only activated when it is triggered by clicking the 'Multi Select' icon, and is deactivated when clicking the 'Multi Select' icon.

**Link bug to the User Story**
#4255

**Impact of this bug**

Medium

**Chance of Occurring (high/medium/low/very low)**

High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-Marshal

**Steps to Reproduce**

1. Apply a redaction to a page, select a FOIPPA section, and click 'Select Code(s)'
2. Click off the redaction
3. See issue, where redaction is automatically selected

AND

1. Access a request that has redactions/redlines, where multi-select is not active
2. Click a redaction in the middle 'working' pane
3. See issue, where multi-select is automatically activated

**Actual/ observed behaviour/ results**

Multi-select activated when not needed or expected

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a user has applied redactions on a page
WHEN a user selects a redaction in the middle 'working' pane
THEN the multi-select remains inactive

GIVEN a user applies and redaction and FOIPPA section, and selects 'Select Codes'
WHEN the user left-clicks off the redaction after it's applied
THEN the multi-select remains inactive

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
Ticket open with Apryse for this issue. Iceboxing for now until update from Apryse.

**Comment by divyav-aot** [comment]
This issue has been fixed with pdftron webviewer 10.3 version

**Comment by nimya-aot** [comment]
working as expected , so closing it
