### ISSUE TITLE
'Total Pages' calculation is incorrect when choosing consultee page flag filter

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4377]
**Describe the bug in current situation**

May not be a bug, but rather a missed AC in #4133.

When a user applies the consult page flag to numerous pages, with different consultees, when the user filters down the package by a specific consultee (using the consult page flag filter), the 'Total Pages' counter is inaccurate. 

When filtering by a specific consultee, rather than the 'Total Pages' counter only reflecting the pages flagged with the selected consultee (in the consult page flag filter), it shows the total pages flagged with ANY consultee selected. The 'Total Pages' counter should be responsive to the specific consultees selected in the consult page flag filter. 

**Link bug to the User Story**
#4133

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

Medium

**Chance of Occurring (high/medium/low/very low)**

Low

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-Marshal

**Steps to Reproduce**
1. Apply the consult page flag to numerous pages, with different consultees selected

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGRpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4952728441269bb7a1280c73247e5efcf4821283/image.png)

2. Select the consult page flag filter, and checkmark one consultee

3. See the 'Total Pages' counter, where it show ALL pages flagged with a consult page flag, rather than only counter the pages flagged with that specific consultee selected.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGhpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ed8eb5cfec80f9f1d8d818d6fdd4d2200883e210/image.png)

**Actual/ observed behaviour/ results**

Consult page flag filter counts all pages flagged with consult page flag, rather than only pages flagged with the specific consultee selected

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a user has applied consult page flags with various different consultees selected
WHEN the user filters the package by a specific consultee
THEN only the pages flagged with that specific consultee with be counted in the 'Total Pages' counter

**Comment by nimya-aot** [comment]
It is working as expected on Test-marshal, so closing
