### ISSUE TITLE
Full Page Redactions on multiple pages shows the section name twice on the redaction box

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#4378]
**Describe the bug in current situation**
Whenever full Page redactions are applied on multiple pages, some pages shows the section name twice on the redaction box. But it will go away after refreshing the page.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
High
**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to the redaction app
2. Click on the Redact pages icon on the top.
3. Specify multiple page numbers for eg: 3-6 and choose the section.

**Actual/ observed behaviour/ results**
You can see the section name showing twice on some of the pages(not all).

**Expected behaviour**
The section name should be shown just once. (You can be seen expected behavior when u refresh)

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVZyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--32290d0fa0442d410bdd0012c34e3771286ed787/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVpyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d35623503a7d1961dd55d4afbe0147813a4f13b9/image.png)

**Comment by aparna-aot** [comment]
Fixed as part of my task : #4385.

**Comment by nimya-aot** [comment]
Working as expected on test-marshal. So closing
