### ISSUE TITLE
Recruitment For Ministry Prototype Testing

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#438]
Title of ticket: Recruitment For Ministry Prototype Testing

#### Description
Recruiting Pilot Ministries to Participant in User Testing Sessions for Next Sprint. 5 
Recruiting 3 additional ministries 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Book sessions with all 5 Ministries involved in Pilot
- [x] Review Notes and select 3 additional Ministries to include in testing
- [x] Book sessions with 3 additional Ministries

**Comment by JHarrietha-AOT** [comment]
As per scoped down MVP - these user tests should only be booked with Ministries who are participating in the pilot and will be to do a walk-though of what is in scope for the pilot. With questions focusing on whether this is enough for Ministries to want to change to a new system? If not, what would need to be included for them to want to change?

**Comment by lmullane** [comment]
@JHarrietha-AOT, we should have some user tests with non pilot participants to ensure we still have representative research.

Let's discuss further at our meeting tomorrow.

**Comment by mpilchar** [comment]
During a meeting with IAO Flex lead today, the following ministries could be worth including due to unique complexities each possess:
- Office of the Premier (legislative requirements)
- Finance
- PSSG/AG (decentralized structure for FOI processing)
- Health (unique process)

cc: @lmullane

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Just wanted to recorded the discuss we had earlier today with the list of Ministries we will be recruiting from for these sessions.

- [ ] MUNI
- [ ] JERI
- [ ] LBR
- [ ] TACS
- [ ] EDUC
- [ ] FIN
- [ ] HTH
- [ ] ENV
