### ISSUE TITLE
Unable to select comments

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#4382]
If the redaction document has more than 1000 annotations in 1000 pages. In the comments; unable to select the annotation in page-1. The comments automatically jumps to last comment.

**Comment by abin-aot** [comment]
@sumathi-thirumani-aot to reconfirm on DEV-Marshal & TEST-Marshal

**Comment by sumathi-thirumani-aot** [comment]
This is not reproducible anymore in listed environments. I believe @nkan-aot  worked on this finding and also removing the legal filter has could have been an additional reason..

- Test Marshal -> OK
- Dev Marshal -> OK

**Comment by sumathi-thirumani-aot** [comment]
New observation; that the Multiselect of comments gets automatically disabled in test-marshal; whereas it works fine in dev-marshal.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXZsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b7f172d3ca1243b89d24a2ec3d8ad02ed8986dfd/scrnli_9_27_2023_4-55-16%20PM.webm)
