### ISSUE TITLE
Find and Redact - Applies Two FOIPPA Sections

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4385]
**Describe the bug in current situation**

When using the 'Find and Redact' feature to find keywords in the package and bulk redact the keywords - when you enter a keyword, select one or more occurrence of the keyword, and add a FOIPPA section, it applies the FOIPPA section twice. This will cause issues in all the packages, because these FOIPPA sections will show up outside the redactions, in random locations. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkp6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e52c8a40d149037fa32c5b9e8e04dc3e64ec9ae2/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjF6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--24c2b74a4a116548d871bc7d18087fb53c1ac564/image.png)

![image](https://github.com/bcgov/foi-flow/assets/117312323/28d9ad3e-67bf-4362-80c1-13f9015bab38)

![image](https://github.com/bcgov/foi-flow/assets/117312323/af1b8b91-7d85-42b7-b295-997aa2575e0e)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTV6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--24a72fb98bda6a40cfca499c13279bd41ec36aba/image.png)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

Medium

**Chance of Occurring (high/medium/low/very low)**

Medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

Test-Marshal
See EDU-2023-929394

**Steps to Reproduce**
1. Go to a request in the Redaction App with records that can be searched by keyword 
2. Click on the Redaction Panel menu option (find and redact)
3. Enter a keyword found in the package in the keyword search field
4. Search and select one or more instances of the keyword
5. Select 'Add Mark' and apply a FOIPPA Section(s)
6. Save, and view the redactions applied - see error of duplicated FOIPPA Section

**Actual/ observed behaviour/ results**

FOIPPA sections are added twice for a redaction when using Find and Redact

**Expected behaviour**

GIVEN a user has entered a keyword(s) in the Redaction Panel (find and redact)
AND selected one or more occurrence of that keyword
WHEN the user selects a FOIPPA Section(s) under 'Add Mark'
AND clicks 'Select Code(s)'
THEN the redactions will be applied, with the FOIPPA Section will be stamped once in the top-left of the redaction box

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by aparna-aot** [comment]
@KyEggleston This issue seems to have fixed along with the recent task updates we have pushed. Can you please retest this? Thanks!

**Comment by nimya-aot** [comment]
Working good on test-marshal, so closing it
