### ISSUE TITLE
Find and Redact - Unable to Change Page Flag

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4386]
**Describe the bug in current situation**

After using find and redact to redact keywords in a package (see #4385 for this process), the pages with the keyword redacted will automatically be flagged as 'Partial Disclosure'. However, after applying these redactions, you are unable to change the page flag on pages with the keyword redacted. 

Keyword redacted using find and redact, and pages flagged as 'Partial Disclosure' automatically.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGh6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b57b991e0eca6c7f8a21aeb39ee4c6cc9bb1ef76/image.png)

When I right-click on one of the pages, and select another page flag, nothing happens. The page remains flagged as 'Partial Disclosure'

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHR6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a1cf79541fe299046b7c5083cf82ee31f961f593/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHh6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ceb2e63ad1d062a23d84dde597a4b5075b696964/image.png)

I am also unable to automatically clear the 'Partial Disclosure' flag by removing all redactions on a page. In addition, changing the page flag on the page to 'Withheld in Full', and choosing a FOIPPA Section, applies the full page redaction, but does not change the page flag to 'Withheld in Full'. The only war to clear the page flag is to delete the record(s) and reupload them. 
**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

High

**Chance of Occurring (high/medium/low/very low)**

Medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-Marshal
EDU-2023-929394

**Steps to Reproduce**
1. Use find and redact to redact a keyword on a page(s), which will auto-flag them as 'Partial Disclosure'
2. Right-click on a page flagged as 'Partial Disclosure' through the find and redact, and select a new page flag
3. See error, where you are unable to change the page flag, or remove the page flag by deleting all redaction

**Actual/ observed behaviour/ results**

Unable to change page flag

**Expected behaviour**

GIVEN a user has used find and redact to redact keywords in the package
AND the pages are automatically flagged as 'Partial Redaction' 
WHEN the user selects a new page flag to apply to the page
THEN the page flag for the page is updated to the selected page flag

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by aparna-aot** [comment]
@KyEggleston Fixed the issue : Automatically clear the 'Partial Disclosure' flag by removing all redactions on a page. Rest of the issues mentioned like updating page flags was working for me. Please retest the same and let me know if u find any issues. Thanks!

**Comment by nimya-aot** [comment]
working as expected on test-marshal, so closing it
