### ISSUE TITLE
Redaction App - "No Flag" Filter Option

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4396]
* As an IAO user
* I want to be able to filter the pages in the redaction app to those with no flags
* so that I can more easily complete pages that still need actioning

**Assumptions & Scope**	
This is from feedback we received during our super user usability testing sessions. This is a critical piece of feedback that should be addressed to help make our users time more manageable, especially on larger FOI packages.

What is IN scope?
Adding an additional page flag filter

What is NOT in scope?
No changes to existing page flags/functionality

**Acceptance Criteria**	

**Scenario 1: Filter to No Flag**
* GIVEN an IAO user is on the redaction application's left-hand nav panel
* WHEN they click on the 'No Flag' filter
* THEN the pages displayed in the panel will only show pages that do NOT have a redaction flag.

**Scenario 2: De-Activate No Flag Filter**
* GIVEN an IAO user has the no flag filter active
* WHEN they click on the 'No Flag' filter
* THEN the filter will clear
* AND all pages will display again

**Scenario 3: "No Flag" Flag - not included in completion or redline/response package**
* GIVEN a records package has multiple pages with flags
* WHEN there are pages unflagged
* THEN they will not contribute to % complete
* AND redline or response package PDF cannot be created 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
No flag filter per feedback from super user session, may need a quick icon design update.

cc @JHarrietha-AOT @KyEggleston @lmullane

**Comment by lmullane** [comment]
Assumption is that on the back-end technically this will be a new flag even if there is no visible flag (i.e. icon) on the front-end.

If that is technically true, will need to ensure any pages that have this non-flag flag are never included in the redline or response package.

**Comment by m-prodan** [comment]
added scenario 3, even if unnecessary, to ensure nothing funny happens based on your comment Loren

**Comment by JHarrietha-AOT** [comment]
@sumathi-thirumani-aot tagging you for icon choice for the filter - https://fontawesome.com/icons/exclamation?f=classic&s=solid

Let me know if you have any other questions

**Comment by lmullane** [comment]
Thanks for your good work, @sumathi-thirumani-aot 

All AC passed.
