### ISSUE TITLE
Dragging full page redaction box

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#4399]
**Describe the bug in current situation**

When an analyst does a full-page redaction, the analyst can drag the redaction box so that it does not cover the whole page either by track pad or the pan feature. 

Full page redaction boxes should not be movable or resizable. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
High. Risk is a breach as the page is flagged as Withheld in Full.

**Chance of Occurring (high/medium/low/very low)**
High. A number of analysts replicated this during training.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
Complete with #4311

**Comment by nimya-aot** [comment]
working as expected, so closing
