### ISSUE TITLE
Full page redaction box does not cover entire scanned page

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#4405]
**Describe the bug in current situation**

The redaction box is not covering the entire scanned page when it is applied. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
High. A breach would occur as analyst and peer reviewer would think all the contents of the page were redacted

**Chance of Occurring (high/medium/low/very low)**
High - seems to occur with all Full Page redactions of scanned pages

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to to a scanned page
2. Click on the 'Withheld in Full' page flag or the redact by page feature
3. Select Code for Section Stamp 
4. See that redaction box does not cover entire page

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0tDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--030aa99a9327672b9a2d84f2193218115ba3ffab/Screenshot%202023-09-08%20at%202.44.58%20PM.png)

**Actual/ observed behaviour/ results**

**Expected bge ehaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 
GIVEN a user is on a scanned page
WHEN a full page redaction is applied
THEN the entire scanned page will be covered by the redaction box

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nkan-aot** [comment]
example EDU-2023-99920

**Comment by KyEggleston** [comment]
Ticket created with PDFTron

**Comment by KyEggleston** [comment]
Appears to occur only when using 'Redact Page(s)' feature

**Comment by nkan-aot** [comment]
https://support.apryse.com/support/tickets/61440

**Comment by abin-aot** [comment]
Seems to be working on Apryse 10.5, Will be soon on TEST-Marshal, to confirm after 10.5 upgrade

**Comment by abin-aot** [comment]
Full page redaction issue is solved, which is the major part of this bug with 10.5 apryse version, but the alignment of section is vertical though!- Is that a blocker? cc: @lmullane

**Comment by nimya-aot** [comment]
working as expected, so closing
