### ISSUE TITLE
Records Review app crashes when trying to edit full page redaction with no section stamp

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#4406]
**Describe the bug in current situation**

 A super user found a bug with request EDU-2023-99911 in TEST MARSHAL.

The bug was making the app crash. Precondition is that the redaction box does not have a section stamp.

Appears linked to another bug
**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
High

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to EDU-2023-99911
2. Click Redact Records
3. Go to page in the Review Records app
2. Click on on where the section should be to edit
3. Click on the pencil
4. See error - screen goes white
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUNJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7b56ca7d22d558c6390e34e49b8cae2daed72f33/Screenshot%202023-09-08%20at%203.15.48%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbENJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7ba777ee1df9c8623a52fb2741b274136c9c919c/Screenshot%202023-09-08%20at%203.32.01%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU9JIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bb22f278718fb2857618898fea2811c9c4c6e42b/Screenshot%202023-09-08%20at%203.32.33%20PM.png)

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
Should be fixed by resolving pre-condition in #4324

**Comment by KyEggleston** [comment]
Confirmed resolved via #4324 - closing
