### ISSUE TITLE
UX Study Guide - Ministry User Testing with Prototype

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#441]
**Description:**
Draft of script we will use including questions/tasks we will ask users to complete.

**DOD:**

- [x] Draft of Study Guide
- [x] Review from SME
- [x] Review from PO

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Could you review this if you have time today. Happy to have you make changes within the document itself if you feel comfortable to do so. Otherwise leaving comments works as well. Thanks

https://bcgov.sharepoint.com/:w:/t/03521/EWCqeRCI9CZCpJZwIdRHgcEBEiNMLa0sB0UJuQISfOH3jA?e=r6Kx2q

**Comment by JHarrietha-AOT** [comment]
Please review when you have a chance @lmullane @mpilchar @m-prodan 

https://teams.microsoft.com/l/file/F5900162-50BE-442D-B172-B413E609D1EE?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FSprint%209%20%26%2010%20-%20Ministry%20CFR%2FUX%20Research%20-%20Sprint%2010%20-%20Plan.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by mpilchar** [comment]
made a couple minor comments. Looks great Jackie, thanks!

**Comment by JHarrietha-AOT** [comment]
Study Guide has been updated based on feedback provided from the team. Moving to close prior to starting sessions with Ministries Today.
