### ISSUE TITLE
Bulk Change Redaction Section - FOIPPA Section Text Box Resized Too Small

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4410]
**Describe the bug in current situation**
When bulk changing the FOIPPA sections on redactions (using Multi Select), the FOIPPA sections are able to be changed. However, when you leave the Redaction App and return, all the new FOIPPA sections, and the accompanying text box, are resized too small, and only show "s.".

If the analyst or user doesn't notice this, they could send out package without some FOIPPA sections being displayed.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

Test-Marshal
See EDU-2023-929394

**Steps to Reproduce**
1. Go to a new request in the redaction app
2. Apply several different redactions to pages with FOIPPA sections

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnVLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--00f5b1bf67c1bed489d167da28c7d374db4933b8/image.png)

3. In the Comments Pane, use Multi Select to select several redactions

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnlLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c1cd0a298f15ef924a82bdaba95347df8dff2703/image.png)

4. Click the 'Edit' icon open the FOIPPA Section Model, and select a new FOIPPA section(s), and click 'Select Code(s)'

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjZLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b496db7a76e5277ecd10fc1d4441ea83aaf74ac2/image.png)

5. The redactions update with the new FOIPPA section

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcitLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3a5c9f47e704d4600eaeefc26e2ef691c419363b/image.png)

6. Exit the redaction app, and reopen the redaction app for the same request
7. Look at the redactions you changed the FOIPPA section for in steps 3-5
8. See error, where the FOIPPA sections are not displaying in full in the middle working pane.  It appears the text boxes are automatically resized after exiting, and being resized too small.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0dLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--081f9511c457eb4840a4173a241ccb64d8f95ffc/image.png)

**Actual/ observed behaviour/ results**

The FOPPA section text box is being resized after bulk changing FOIPPA sections, exiting the Redaction App, and then reopening the request in the Redaction App.

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a user has bulk changed FOIPPA sections
AND has left the Redaction App
WHEN the user reopens the Redaction App on the request
THEN the bulk changed FOIPPA sections are fully displayed in the top-left of the redaction box, and the textbox is automatically sized to display all FOIPPA sections

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
Appears to be working in test-marshal - but more investigation needed for edge case that may produce this issue.

**Comment by KyEggleston** [comment]
This is resolved now, as part of other bug fixes in the redaction app. Closing ticket.

**Comment by lmullane** [comment]
All fixed. Thanks, team.
