### ISSUE TITLE
Delete using multiselect checkbox in comments panel fails

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#4412]
Delete using multiselect checkbox in comments panel fails due to issue with pdftron. Occurs after upgrade to 10.3.0. Currently only in dev-marshal

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3FMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--01dfccb14b86771d341e1e7488262b5323530996/Screenshot%202023-09-11%20160931.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3VMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e3afef629d49bc3346dc64df11c364a541402eef/Screenshot%202023-09-11%20160854.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3lMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f22885d8fcaa5007e9eac83f0d3cde41f7209e73/Screenshot%202023-09-11%20160849.png)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
- create a redaction
- open comments panel
- select redaction using multiselect checkbox
- delete using the actions icons at the bottom of the panel
- confirm popup

**Actual/ observed behaviour/ results**
annotation will be deleted in ui but if page is refreshed annotation will return

**Expected behaviour**
annotation should be permanently deleted

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
Ticket was opened with PDFTron; they said they fixed it, but we need to verify.

**Comment by nimya-aot** [comment]
working as expected , so closing
