### ISSUE TITLE
Annotation Section Modal does not  show updated value

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#4414]
Steps to reproduce

1. Create Annotation with any section
2. Change the section by clicking the edit icon
3. Again change the section to Blank code.
4. Now try to change again; old values are retained.

**Comment by sumathi-thirumani-aot** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaW1MIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3d5d3bf659e8200893acf284f7135cd7e060ff74/image.png)

**Comment by sumathi-thirumani-aot** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXFMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1685f16f64cbad8d19106dc859f5e641735f5968/image.png)

**Comment by nimya-aot** [comment]
working good so closing it
