### ISSUE TITLE
Disable automated legal search term

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4415]
Title of ticket: 

#### Description
Based on feedback, at this time we need to disable the automated legal search term. There are additional considerations we need to more fully explore and it will not be a useful feature at launch.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Disable the automated search terms upon every launch of the redaction app

**Comment by nimya-aot** [comment]
It is working good, so closing it
