### ISSUE TITLE
Delete Page From Redaction App - Multiple Bugs

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4418]
**Describe the bug in current situation**
There are several issues that occur when deleting pages in the Redaction App. When deleting a page in the Redaction App through the 'Preview' pane, the page appears to be deleted from the package. However, afterwards the organization of the left pane is affected, leading to incorrect page counts, pages showing up under the wrong file name, and pages you deleted causing white screen errors. In addition, deleting pages from the Redaction App doe snot appear to be be maintained after exiting the Redaction App and returning (the deleted pages are back in the package).

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

High

**Chance of Occurring (high/medium/low/very low)**

Medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test Marshal
Files on EDU-2023-99920 to replicate

**Steps to Reproduce**

<h2> Bug 1 </h2>

1. Go to the 'Preview' Pane and delete a page

![image](https://github.com/bcgov/foi-flow/assets/117312323/1b67e0d1-4872-424e-8b4a-f98f88d5cf4a)

2. The page doesn't disappear from the left pane, and appears deleted from Redaction App

![image](https://github.com/bcgov/foi-flow/assets/117312323/789c48ef-35ad-41d1-bcc7-e256fbb9be9d)

3. Exit the Redaction App, and reopen the Redaction App for the same request.
4. See error, where the deleted page reappears

![image](https://github.com/bcgov/foi-flow/assets/117312323/b0bd9e70-da40-4944-9de5-e7e97fe431ca)

<h2> Bug 2 </h2>

1. Go to the 'Preview' Pane and delete a page

![image](https://github.com/bcgov/foi-flow/assets/117312323/1b67e0d1-4872-424e-8b4a-f98f88d5cf4a)

2. The page doesn't disappear in the left pane, and appears deleted from Redaction App (but see Bug 1 for permanency of deleting). However, note that the previous "Page 2" has now been bumped up to be "Page 1". This is acceptable - however, note that this page now shows up as being part of the wrong record in the left pane. It is part of the 'Policy and Procedures Manual.PDF', but due to the page reordering, it has been moved to, incorrectly, be under the 'cat.pdf.jpg' file. Solution to this may need discussion.

![image](https://github.com/bcgov/foi-flow/assets/117312323/01a26e77-eec9-4f60-b60e-15e3f92cb4e1)

<h2> Bug 3 </h2>

1. Go to the 'Preview' Pane and delete a page (from an Excel file in this case)

![image](https://github.com/bcgov/foi-flow/assets/117312323/51378e94-8b2f-467e-bfd7-c07c7c92dae5)

2. After deleting the redaction, the page doesn't appear to be deleted, as the 'Total Pages' counter does not update to "113". 

![image](https://github.com/bcgov/foi-flow/assets/117312323/8710d7a5-01a7-4090-85ae-036d1b65aebf)

3. When you click on 'Page 113' again, you are brought to a white screen error. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/5cec49f2-e0e2-4919-9624-c54ead566292)

![image](https://github.com/bcgov/foi-flow/assets/117312323/c25a792b-c7d7-41ba-885b-173de55ad28e)

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Pre Deployment Steps **
Add "thumbDelete,deletePage" to REACT_APP_PDFVIEWERDISABLED configmap in openshift for docreviewer web

**Comment by KyEggleston** [comment]
cc: @lmullane @JHarrietha-AOT @m-prodan @liseandtea

**Comment by KyEggleston** [comment]
Discussion may be needed on this, if we even want to allow users to delete for pilot launch.

**Comment by KyEggleston** [comment]
Decision - disable delete option

**Comment by KyEggleston** [comment]
Add estimates

**Comment by m-prodan** [comment]
confirming that the delete page function appears to be disabled/inaccessible now from the preview pane - so this should be good to go now.
