### ISSUE TITLE
"Release Package ready for download" message is replaced by the wrong message "Batch of records uploaded by User"

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4420]
**Describe the bug in current situation**
when the final package is ready for download, then wrong message notification comes up for the user

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-Marshal

**Steps to Reproduce**
1. Go to Ministry login
2. Upload few records on records tab
3. Then go to IAO login and make redactions and create redline
4. Then download final package, then watcher/assignee getting wrong notification message on notification bar

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalNTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b5d9a410fdb6cb51f009a1c868ef2bf0530d23f4/image.png)

**Comment by divyav-aot** [comment]
The latest changes related notifications were not pushed to test-marshal. Created the PR and pushed the changes to test-marshal. @nimya-aot  please confirm.

**Comment by nimya-aot** [comment]
It is working as expected on test-marshal. So closing it
