### ISSUE TITLE
TEST - Divisions not Available - HSG

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4426]
**Describe the bug in current situation**
During QA of 4183, I was trying out different divisions to add across various Ministries. It was observered that HSG's divisional tracking keeps returning the message "Divisions do not exist for this Ministry"

I confirmed with the Ministry user that in PROD the divisions are there and working fine. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaytYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--034d33dc3ed6d00db1af31d91521e7c2ea916a00/image.png)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
bug fixed - divisional updates with and without the sort order aren't causing the division screen to bug out.

**Comment by nimya-aot** [comment]
@m-prodan This issue happened again today for the "Ministry of Education and Childcare 'on test env. But after a refresh divisional stages came up. Do we need to check it again?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmUrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6b384e3029a32dd1078f1c3f06d1b74e04020ccf/image.png)

**Comment by m-prodan** [comment]
Hmm - I just checked and am not getting the same error. I also went and tried to reproduce the bug on another Ministry and couldn't reproduce the bug... may have been an old caching issue if refresh worked? I think we are ok to keep this one closed.
