### ISSUE TITLE
Update Admin App for Section, Personal, Hierarchy Flag 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#4427]
Title of ticket: 

#### Description
The purpose of this task is to update the Admin module for the new flags added for `sections` and `division - section` hierarchy for the changes @abin-aot has made for #4292 

#### Dependencies
Are there any dependencies?

#### DOD
- [x]  Update the CRUD operations for Divisions Module to capture new 3 flags - `issection`, `isspecifictopersonal` and `parentid`
- [x] Update REST API endpoints
- [x]  Update UX - react components - Search, Add, Edit
- [ ] 
- [ ]

**Comment by lmullane** [comment]
Thanks, @abin-aot

**Comment by nimya-aot** [comment]
created a separate ticket for the above issue.
https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4556

**Comment by Aman-Hundal** [comment]
Fixed! Pending merge to main/test from dev

**Comment by nimya-aot** [comment]
@Aman-Hundal Please let me know once it is pushed to test.

**Comment by nimya-aot** [comment]
@Aman-Hundal informed there is flag issue on Admin app. Once its fixed I can test it again

**Comment by Aman-Hundal** [comment]
Flags in the admin panel have been adjusted. good to test!

**Comment by Aman-Hundal** [comment]
Hey @abin-aot a note for you and the team -> we will need to make sure the sections field in the programareadivisions table must be false for all divisions besides mcd/cfd (if a none value or null value exists, divisional tracking will break)

**Comment by nimya-aot** [comment]
created a ticket for unable to delete a section from admin dashboard. https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4568

**Comment by Aman-Hundal** [comment]
Ticket for above completed and pending review / merge to main

**Comment by nimya-aot** [comment]
working as expected, so closing it
