### ISSUE TITLE
Auto refresh page when redline is created

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#4428]
* As an IAO user
* I want the page to automatically refresh when I create the redline
* so that I can edit the redline if I need too

**Assumptions & Scope**	
What are the assumptions for this story?

This story resolves the bug #4422 by automatically refreshing the page when a redline is created.

Unlikely that the analysts will need to edit the redline right after they create the redline as most edits will happen after the ministry comes back with requested changes.

What is IN scope?

Auto refreshing the redline layer in the redaction app when the redline is created.

What is NOT in scope?

Most of the create redline functionality is already built as part of #3437

**Acceptance Criteria**	

**Scenario 1: Click active "Redline for Sign Off"**
* GIVEN the "Create Records Package" dropdown is open
* AND the request is in Records Review, Ministry Sign Off or Peer Review
https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/981498459
* WHEN the IAO analyst clicks the active "Redline for Sign Off"
* THEN a modal will open with the message, "Are you sure want to create the redline PDF for ministry sign off?". 
* AND the modal will have the message, "When you create the redline PDF, your web browser page will automatically refresh."
* AND a "Create Redline PDF" and "Cancel" button
https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/981498459

**Scenario 2: Click "Create Redline PDF" button**
* GIVEN an analyst is on the "Redline for Sign Off" modal
* WHEN the IAO analyst clicks the "Create Redline PDF" button
* THEN a modal will close
* AND the web browser page will automatically refresh

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by nimya-aot** [comment]
It is working as expected, so closing it
