### ISSUE TITLE
Page Stamping - Response Package

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4431]
* As an IAO User
* I want my response packages to have page numbering and file ID stamped on each page
* so that I can comply with existing policy and practices with response packages

**Assumptions & Scope**	
This is related to user feedback and consistent with some research previously conducted around practices for IAO. When a response package is produced, IAO includes a page stamping that has the request ID, and the page count. 

EG - OOP-2023-12345 Page 1 of 10

What is IN scope?
Page stamping on response packages

What is NOT in scope?
Does not include detailed summary of full pages removed - will handle in a separate user story

**Acceptance Criteria**	

**Scenario 1: Response Package Created**
* GIVEN an IAO user has created a response package
* WHEN the package is downloaded
* THEN each page will be stamped with the request ID and page number
*  AND page numbers will follow this convention - page number out of the total pages (e.g. OOP-2023-12345, Page 1 of 10)

**Scenario 2: Not Responsive Pages - not included in page count**
* GIVEN an IAO user has created a response package
* WHEN there are pages flagged as 'Not Responsive'
* THEN they will NOT be included on the page count

**Scenario 3: Duplicate Pages - not included in page count**
* GIVEN an IAO user has created a response package
* WHEN there are pages flagged as 'Duplicate'
* THEN they will NOT be included on the page count

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Page stamping user story @lmullane @KyEggleston @JHarrietha-AOT

**Comment by lmullane** [comment]
Hi @abin-aot, I have updated AC 1 to follow the same page count convention as in the Redline Page Stamping story (#4446).

Could you please make that change.

cc @m-prodan

**Comment by abin-aot** [comment]
Yes @lmullane , updated as per the new AC
[Uploading... image.png]

**Comment by nimya-aot** [comment]
@abin-aot  @lmullane Not sure the following issue is related to this ticket or not. The response package pdf has both 'Duplicate' and 'Not responsive' pages now.
https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4575

**Comment by abin-aot** [comment]
@nimya-aot  Page Stamping works on top existing Download Response package code, if page exists my logic will stamp on it. So IMO its unrelated, issue need to be fixed on that ticket or as separate ticket

**Comment by nimya-aot** [comment]
@abin-aot ok. but needs to check scenario 2,3 after the bug fix

**Comment by nimya-aot** [comment]
since the bug mentioned above https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4575 is created by the confusion happened by means of sorting takes place soon after the final package creation that resulting the page number change( Refresh needed to identify the duplicate/NR pages to show up correctly). That refresh is covering on the ticket #4582. 

working good , so closing it
