### ISSUE TITLE
Attachments - Add Consult Tag

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4434]
* As a user of FOI Mod
* I want to be able to tag an attachment as 'Consult'
* so that I can ensure the attachments are properly tagged 

**Assumptions & Scope**	
What are the assumptions for this story?

The need for this was identified through the super user engagement sessions. 

All broad functionality related to the Attachments tab, Attachments modal, and other attachment tags, will also be applied to the 'Consult' tag (unless otherwise specified). I.e., functionality part of #2489, #2470, #1974.

The colour of the 'consult' tag will be the same as the 'consult' Request State colour 

The 'Consult' tag should be available to both IAO and Ministry users.

IAO and Ministry users should be able to see attachments tagged with 'Consult'.

**Acceptance Criteria**	

**Scenario 1: 'Consult' Tag Available**
* GIVEN a user is on the Attachments tab
* WHEN they click the 'Add Attachment' button
* THEN the 'Add Attachment' modal will open
* AND there will be a tag for 'Consult' in addition to all other available options

**Scenario 2: Select 'Consult' Tag**
* GIVEN a user is on the 'Add Attachment' modal
* WHEN they click the 'Consult' tag
* THEN the 'Consult' tag will be selected (blue fill, white text)

**Scenario 3: Save Attachment with 'Consult' Tag**
* GIVEN a user has selected the 'Consult' tag
* AND the user has uploaded one or more attachment(s)
* WHEN the user clicks 'Continue'
* THEN the attachment(s) will be uploaded to the Attachments tab
* AND the 'Consult' tag will be under the attachment name(s)

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Consult tag: @KyEggleston @JHarrietha-AOT @lmullane @liseandtea

**Comment by abin-aot** [comment]
Whoever picks this task , please branch out from regular DEV , Main Branch (Not Marshal Branch!!) . So that we can release faster to PROD without mixing with major releases

**Comment by JHarrietha-AOT** [comment]
@m-prodan @liseandtea workflow wise I am thinking that the consult tag should be between CFD and Records Review. Curious if you both think that spot makes sense

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVhpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58e9f278dee517bc1793cbc2a3dd59a0d1081db9/image.png)

**Comment by JHarrietha-AOT** [comment]
@milosdes @abin-aot 

Given what the happy path process if for a request we would like to have the order updated for these tags as consults being at the end doesn't make sense.

Can we update the order to be as follows for the taggs:

General, Applicant, CFR, Harms, Fees, Records Review, Consult, Extensions, Ministry Sign Off, Response, OIPC

**Comment by milosdes** [comment]
@JHarrietha-AOT the reordered tags should be visible in dev now, but they haven't been pushed to test yet.

**Comment by JHarrietha-AOT** [comment]
@milosdes Thanks for making the updated so quickly looks great - this has passed UX Assurance is ready to be moved to test - I'll move the ticket itself into ready for QA

**Comment by lmullane** [comment]
Works as expected. Great work, @milosdes

**Comment by liseandtea** [comment]
@JHarrietha-AOT @m-prodan Hey! I agree that between CFR and Records review is a good spot for the consult tag.
