### ISSUE TITLE
Bulk Selected Pages - Deselects When Expanding or Collapsing File/Record in Left Pane

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4435]
**Describe the bug in current situation**
When selecting pages to bulk select in the left (navigation) pane, if you click a file name to expand a file, while you already have pages bulk selected, it clears your bulk selections. This can cause a lot of frustration for users.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

Low

**Chance of Occurring (high/medium/low/very low)**

High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test Marshal

**Steps to Reproduce**

1. Bulk select several pages under a file/record

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbitaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1e671364c2e601ecd061fd2ce8b011463d2c4394/image.png)

2. Click on another file/record name to expand the file. See error where it deselects your previous bulk selections

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0NaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--71cec97d1199110cad35974023ff2663e5b787d3/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2FaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--33e6f3606ffb299a3fa1f6eef6690be8313fbe39/image.png)

**Actual/ observed behaviour/ results**

Bulk selections are cleared when expanding and collapsing a file in left pane. 

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a user has bulk selected pages (using Ctrl + left click or Shift + left click)
WHEN the user clicks on a file/record name in the left (navigation) pane to expand or collapse the file
THEN the bulk selections are retained
AND bulk selections are only 'cleared' when the user left clicks on an individual page number in the left (navigation) pane

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbytaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fb5d2c6fd4da87ef6e92ab0c9c8e11341070a3e2/image.png)

**Screenshots/ Visual Reference/ Source**

If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
@m-prodan @liseandtea @lmullane @JHarrietha-AOT - ticket for bug raised in pilot user discussion today.

**Comment by m-prodan** [comment]
Works really nicely now - you can expand and recollapse files without having lost your ctrl selections - should address user feedback well.

Tests various flags without issue. Did observe some unexpected behavior when trying the withheld in full flag, will likely create another ticket regarding that but nothing showstopping.
