### ISSUE TITLE
Bugs related default code and FOIPPA Modal

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#4437]
There are multiple related bugs dealing with default code and FOIPPA Modal. Solving one may also solve some of the other ones so using this ticket to track all of them. Will update with multiple scenarios as we discover them and will finalize before moving to QA

Scenario 1)
- create a new redaction
- select blank code
- save as default
- edit the redaction just created
- deselect blank code and select some other codes, click "Select Codes"
- edit the same annotation again
- Blank code is selected, should be the new codes

Scenario 2)
- create a new redaction
- select any code
- save as default
- edit any redaction
- clear default, and select any new sections in addition to existing section
- click save as default again
- new sections are not saved
- now create a new redaction and try to edit it
- crash

Scenario 3)
- edit any existing redaction
- save as default
- use left panel to add a withheld in full flag
- newly created full page redaction has no section, try to edit it
- crash

**Comment by nimya-aot** [comment]
working as expected, so closing it
