### ISSUE TITLE
Page Stamping - Redline

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4446]
* As an IAO User
* I want my redline packages to have page numbering and file ID stamped on each page
* so that I can easily refer to them in the redaction app if I need to make changes

**Assumptions & Scope**	
This is related to user feedback and consistent with some research previously conducted around practices for IAO. When a redline package is produced, IAO analysts want to be able to match the pages to the records review app, especially when the Ministry provides revisions to a sign-off package

EG - OOP-2023-12345 Page 1 of 10

Note that unlike #4431 - the page count should account for and include the not responvie and duplicate flagged pages. NOTE that these pages will continue to be removed from the package, however, the numbering of the pages should account for them. This will allow IAO analysts to easily cross-reference revisions from the Ministry during sign-off back to the redaction app so they can make changes more quickly. 

What is IN scope?
Page stamping on redline packages

What is NOT in scope?
Does not include detailed summary of full pages removed - future story.

**Acceptance Criteria**	

**Scenario 1: Redline Created**
* GIVEN an IAO user has created a response package
* WHEN the package is downloaded
* THEN each page will be stamped with the request ID and page number
* AND page numbers will follow this convention - page number out of the total pages (e.g. OOP-2023-12345, Page 1 of 10)

**Scenario 2: Not Responsive Pages - included in page count**
* GIVEN an IAO user has created a response package
* WHEN there are pages flagged as 'Not Responsive'
* THEN they will be included on the page count

**Scenario 3: Duplicate Pages - included in page count**
* GIVEN an IAO user has created a response package
* WHEN there are pages flagged as 'Duplicate'
* THEN they will be included on the page count

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by abin-aot** [comment]
From the refinement, its confirmed by business that Page Numbering on Left panel(consolidated) can be followed

**Comment by lmullane** [comment]
Hi @m-prodan, looking at the assumptions, the convention should be to say page x of x pages.

EG - OOP-2023-12345 Page 1 of 10

Is that correct?

Page stamps are in the PDF there but appear like this (note AC was silent on the convention):

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f56ab1744adb4db14f467705db017e5c4665f8ab/Screenshot%202023-10-06%20at%2011.50.02%20AM.png)

cc @abin-aot @JHarrietha-AOT

**Comment by m-prodan** [comment]
Yes - what I have in the assumption is consistent with how page counts currently appear now - we typically include it as Page X out of Y(total). It looks like that wasn't entirely clear in the AC itself.

**Comment by lmullane** [comment]
Thanks for the confirmation, @m-prodan 

@abin-aot, could we add the page x out of page Y (total). I've updated the AC

**Comment by abin-aot** [comment]
@lmullane , Yes updated as per the updated AC, [Uploading... image.png]

**Comment by nimya-aot** [comment]
working as expected so closing it
