### ISSUE TITLE
Redline Package - Error When Redline Package with No Pages

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4447]
**Describe the bug in current situation**
In the Redaction App, when all pages under a division are flagged with 'Duplicate' or 'Not Responsive' (i.e., there will be no pages included in the redline for this division), and error is thrown, likely due to no error handling/exception for this scenario. 

When this error occurs, a user is able to save the redline in the Redaction App. However, when the user goes to the 'Records' tab in FOI Mod, and selects 'Download', the 'Download Redline for Sign Off' is not available. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
High

**Chance of Occurring (high/medium/low/very low)**
Low

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-Marshal
See EDU-2023-74322 

**Steps to Reproduce**
1. Ensure a request is in Records Review, Peer Review or Ministry Sign Off (which is required to save a redline), and records have been uploaded for at least two divisions in the 'Records' tab.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHltIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--277081317e32a18cfd0835d36e9b812342461d53/image.png)

2. In the Redaction App for the request, apply page flags to all pages in the package (i.e., 'Complete %' counter shows "100%"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaCttIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--34c4fc146d01cbdc63956f731a1cfde86559b9c5/image.png)

3. For one division, ensure all pages under that division are flagged with either 'Not Responsive' or 'Duplicate. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUttIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bd896ce210d3b14c7a3ae6ef5ed9aa230bf62cc5/image.png)

4. Click 'Create Response PDF' and select 'Redline for Sign Off'. Create/save the redline

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVNtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--43f6326a51b4852ec4678a01069b35b6005f297a/image.png)

5. After the package has been created/saved, and the success toast comes up. However, see error message in console.

![image](https://github.com/bcgov/foi-flow/assets/117312323/dd941812-e858-43c3-8dbe-64a9fc4e744b)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaG1tIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7802ec24ae6b89a2f5bd42109e51b2cbfe57f7fc/image.png)

7. Also, see issue in in 'Records' tab, where the 'Download Redline for Sign Off' is not available

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHFtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--03539d17e60a62e84d60e8a17253f93c18969509/image.png)

**Actual/ observed behaviour/ results**

When a redline for a division will have no pages (based on the page flags applied), the 'Download Redline for Sign Off' in the Records tab is not available, even if another division does have a redline with pages, or the division that will have no redline has incompatible files for sign off. 

**Expected behaviour**

GIVEN a division has all pages flagged with 'Not Responsive' or 'Duplicate' page flags in the Redaction App (and therefore, won't have any pages in a redline for sign off)
AND there are other divisions with pages that are flagged to be included in a redline package
WHEN a user selects to create/save the redline for sign off in the Redaction App
THEN the redline(s) will be created/saved, and downloadable through the Records tab under 'Download Redline for Sign Off'
AND the division which has all pages flagged as 'Not Responsive' or 'Duplicate' will not receive a redline in the folder for their division
AND all incompatible files will be included in the folder for this division
AND any division that does have pages flagged to be included in a redline will receive a redline PDF in the folder for their division
AND all their incompatible files will be included in the folder for this division

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by Aman-Hundal** [comment]
Hey Kyle and Team,

By replicating what Kyle did in the dev-marshal -> the download for redline
sign off works in the dev-marshal environment (where these changes exist as
well). There appears to be a issue in regards to save to redline that is
unrelated to this ticket. Will take a look.

**Comment by Aman-Hundal** [comment]
@KyEggleston For the issue noted above, the download redline signoff slecetion is available again -> there was a devOps related issue which the dev team fixed. Please continue QA testing when you have time again Kyle - thanks!

**Comment by nimya-aot** [comment]
Working as expected, so closing it
