### ISSUE TITLE
Redline Package - Full Page Redline Visibility in Adobe and Browser

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4450]
**Describe the bug in current situation**
After a redline has been saved/created in the Redaction App, and the Redline is downloaded through the 'Records' tab, when the redline is viewed in Adobe or in browser, full page redactions are having intermittent visibility based on the zoom %. 

**Link bug to the User Story**

**Impact of this bug**

??

**Chance of Occurring (high/medium/low/very low)**

High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test Marshal

**Steps to Reproduce**
1. Flag pages as 'Withheld in Full' in the Redaction App

![image](https://github.com/bcgov/foi-flow/assets/117312323/428aab6e-51c4-40f7-83d4-abfb7a14aa66)

2. Prepare the package to where you can create/save the redline for sign off (e.g., in the appropriate request state, and all pages flagged with an acceptable page flag

3.. Create/save the redline for sign off through the Redaction App

![image](https://github.com/bcgov/foi-flow/assets/117312323/e4038b90-d58c-40b6-a4fd-7f0364025887)

4. In the 'Records' tab, download the redline for sign off

![image](https://github.com/bcgov/foi-flow/assets/117312323/dc835523-da54-486d-8cc7-9a5d60362570)

5. In the redlines, view pages that are 'Withheld in Full' in the browser or Adobe. See issue where when zooming in and out of the PDF, the redline box surrounding a full page redaction does not always display, or it is not visible at certain zoom %s. 

In the images below, see the red line is hard to see around the full page based on zoom %.

![image](https://github.com/bcgov/foi-flow/assets/117312323/7b064d49-b6f2-4cc4-9642-d946225c9e33)

![image](https://github.com/bcgov/foi-flow/assets/117312323/f5377e18-67a4-4df2-af6d-f1ba9cee3143)

![image](https://github.com/bcgov/foi-flow/assets/117312323/bcf53175-6b61-41e7-b1b3-10df488f696b)

**Actual/ observed behaviour/ results**

On full page redactions, the visibility of the redline around page i affected based on the page zoom % in browser and Adobe. 

Redline boxes around full page redactions are not always visible/displayed in Adobe or in browser. 

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
Thanks for the fix, @nkan-aot
