### ISSUE TITLE
Image breaks after upgrading PDFTron Webviewer to 10.3

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#4451]
After upgrading PDFTron to 10.3, our previous code to add images to document no longer works.
It is happening even in pdftron's own demo code
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkdtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--316f362bb6c096e8af3e3119b6ef4a8fdebb12ed/image.png)
only way this error doesn't happen is if I comment out the await createImageScaled (line 1136 in screenshot)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmFtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2400f77260c2ea3538431cffaf3b4a84b30eae0c/image.png)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
upload image in records upload tab
wait for dedupe to run
open request in doc reviewer
request is unable to load

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN an image file is uploaded into the request Records log
WHEN the user clicks on the Redact button
AND the redaction app opens for that request
THEN the records will load and be visible/editable for redaction

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
This is now working as expected. Thanks team.
