### ISSUE TITLE
Webviewer error when performing certain actions after newly created redaction

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#4478]
After reating a new redaction,  when we perform certain actions without refreshing, the webviewer will throw an error.
There is no noticable functional impact, however we should still try to solve this issue. I have tried to reproduce this error using a simpler sample code from pdftron but so far have been unable to do so. So we need more investigation on this bug 

**Impact of this bug**
Low - medium: no noticable impact so far, but could cause other errors if user stays on page

**Chance of Occurring (high/medium/low/very low)**
high - happens every time

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
- create a new redaction
- do not refresh
- either change layer or save final package
- check console for error

The error is coming from some property in their code being set to null. I have added screenshots below. In the case of change layer, the call is ultimately coming from deleteAnnotations. When saving final package, it is due to applyRedactions

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczdGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--023a42ca0545c28809e273f7ba92155f6f5be121/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcy9GIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f039d9bc53f54fa2e070dad3d6aa2f8f347cf755/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdERGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b015f9d17ae19d8495e8ae6e604be4dd5045e4b3/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdExGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--881f295af6ae615076e6003165a8eb75a8bbae26/image.png)

**Comment by nimya-aot** [comment]
webviewer error is not showing up after creating a redaction and then changing the layer. So closing it
