### ISSUE TITLE
UI Changes to Left Nav Panel

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#448]
**Describe the bug in current situation**
Design Updates for Left Nav Panel to be more inline with design

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
Occurs every time users goes into page with side panel. Low priority as left nav panel functions correctly. 

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**UI Changes:**

- [ ] Ensure text on tabs is aligned, whether it is selected tab or not
- [ ] Ensure text on selected tab appears in same colour as bar itself
- [ ] Remove circles ( I will remove from design as well, I was thinking about adding icons but they aren't required)
- [ ] Increase height of side nav bar to cover page. 
- [ ] Make header and footer NOT sticky. If user scrolls all the way up then it appears, and if user scrolls all the way down then footer appears
- [ ] 

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/d0a543f5-b957-42e9-8f09-1610701bd8e1)

**Comment by abin-aot** [comment]
Does this override the latest UX bugs on Request @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
@abin-aot These alignment issues and changes have been fixed, I think this ticket can be closed. The new tickets would take priority as they are based off of the app today, this was relevant a while ago. 

I will close ticket with this comment
