### ISSUE TITLE
[#3694] Pagination support for annotations 

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#4509]
Backend:
- [x] New endpoint to support pagination
- [x] Changes to remove the joins DocumentMaster to identify deleted
- [x] Changes in service layer to support pagination
- [x] Configurable size for pagination

Frontend:
- [x] Changes to logic for /GET of annotations
- [x] Streaming logic based on performance ?
- [x] Integration testing with Pagination API endpoints , aka Unit testing
- [x] Inclusion of error toast "Error occurred while fetching redaction details, please refresh browser and try again"

**Comment by sumathi-thirumani-aot** [comment]
GET http://localhost:15500/api/annotation/36/Redline/2/1

Response:
{
    "data": [
        {
            "annotation": "<freetext page=\"0\" rect=\"0,752.497,99.922,774.960\" flags=\"print\" name=\"79fa629f-cc76-cbd8-13b7-38ece55e9ac3\" title=\"Sumathi Thirumani\" subject=\"Free Text\" date=\"D:20230919202520\" width=\"0\" creationdate=\"D:20230919202520\" TextColor=\"#FF0000\" FontSize=\"18\"><trn-custom-data bytes=\"{&quot;trn-auto-size-type&quot;:&quot;auto&quot;,&quot;parentRedaction&quot;:&quot;ddc2b7aa-d5b8-2004-1813-3a8e55529d82&quot;,&quot;sections&quot;:&quot;[{\\&quot;id\\&quot;:1,\\&quot;section\\&quot;:\\&quot;s. 12\\&quot;},{\\&quot;id\\&quot;:2,\\&quot;section\\&quot;:\\&quot;s. 13\\&quot;}]&quot;,&quot;trn-redaction-type&quot;:&quot;fullPage&quot;,&quot;existingId&quot;:&quot;48d100b4-2bac-016d-54de-e43a1c841d26&quot;,&quot;originalPageNo&quot;:&quot;0&quot;,&quot;trn-wrapped-text-lines&quot;:&quot;[\\&quot;s. 12, s. 13 \\&quot;]&quot;,&quot;docid&quot;:&quot;22&quot;,&quot;docversion&quot;:&quot;1&quot;,&quot;redactionlayerid&quot;:&quot;1&quot;}\"/><contents>s. 12, s. 13</contents><defaultappearance>0 0 0 rg /Helvetica 18 Tf</defaultappearance><defaultstyle>font: Helvetica 18pt; text-align: left; text-vertical-align: top; color: #FF0000</defaultstyle></freetext>",
            "documentid": 22,
            "pagenumber": 0
        }
    ],
    "meta": {
        "has_next": true,
        "has_prev": true,
        "next_num": 3,
        "page": 2,
        "pages": 500,
        "prev_num": 1,
        "total": 500
    }
}

**Comment by sumathi-thirumani-aot** [comment]
As part of this usecase; there has been discussion with @JHarrietha-AOT  and included toast error as "Error occurred while fetching redaction details, please refresh browser and try again"

**Comment by nimya-aot** [comment]
Tested the performance adding more pages with more annotations on dev-marshal.

**Comment by nimya-aot** [comment]
working as expected, so closing it
