### ISSUE TITLE
Redactions not applied in Response Package

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#4512]
**Describe the bug in current situation**

EDU-2023-99903

A number of super users encountered a bug. The redactions were 
**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to records in the Redaction app
2. Ensure all pages are flagged in Redline layer
3. Click on Response Layer in the layers dropdown
4. Click download Response Package PDF
4. Go to Records log
5. Download the Response Package
6. See that no redactions are applied

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a user is on the Response layer
WHEN the user creates the Response Package PDF
AND the user downloads the Response Package PDF
THEN all redactions will be applied

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
Other requests:
EDU-2023-99901
EDU-2023-99916
EDU-2023-99907

**Comment by lmullane** [comment]
Thanks, @aparna-aot
