### ISSUE TITLE
Redline as one consolidated PDF 

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#4514]
* As a ministry or IAO analyst
* I want a default for all redlines for my public body
* so that I can get a redline that fits my ministry needs (consolidated or by division)

**Assumptions & Scope**	
What are the assumptions for this story?

Assumption is that all redlines are split by division by default

- Some public bodies want redlines consolidated: PSA and LDB only have one ADM who does Ministry Sign Off of the redline.
- PSA and LDB do want Harms split by division
- PSA and LDB want the redline consolidated into one PDF as they only have one reviewer
- The default can be switched by a configuration by Org Code

What is IN scope?
Stitching redline PDF into one consolidated PDF for public bodies that have that configuration

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: PSA or LDB**
* GIVEN I am a ministry coordinator or IAO analyst
* WHEN I download a PSA or LDB redline
* THEN the redline will be consolidated into one PDF ordered by modified date of the records

**Scenario 2: Not PSA or LDB**
GIVEN I am a ministry coordinator or IAO analyst
* WHEN I download a redline for a public body (ORG Code) that is not PSA or LDB
* THEN the redline will be broken into PDFs for each division and ordered by modified date of the records

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT , we may need a design if this is a user choice between whether to split redline by division or to consolidate the redline into one PDF.

@m-prodan, one of the improvements for ministry reviewers is to split redline by division, so perhaps the default should be that unless the coordinator changes the default?

**Comment by lmullane** [comment]
@abin-aot to connect with @richard-aot 

This should be a configuration by ORG code, not a user choice in the UI for each download.

**Comment by abin-aot** [comment]
@lmullane : Could you please update the ticket description and AC , to avoid `radio button`

**Comment by lmullane** [comment]
@abin-aot , please review the updates.

**Comment by KyEggleston** [comment]
Ministry of Agriculture (AGR) raised that they would also like to be set up so that they receive the redline as a single whole document, rather than separated into parts by division.

**Comment by m-prodan** [comment]
Finance (FIN) has indicated the same. I expect some of the Economy Sector would like to as well, but I will await final word from the ECON team.

Matt

**Comment by KyEggleston** [comment]
FIN, JED, LBR, MUNI and TACS all confirmed they want the redline as one consolidated PDF.

So the list now for ministries wanting this configuration is: 

- FIN
- JED
- LBR
- MUNI
- TACS
- AGR
- PSA
- LDB

**Comment by sumathi-thirumani-aot** [comment]
Above given list is configured in test-marshal. Please note we will be using the bcgovcode representation of ministries in configuration. List maintained in system drafted for reference
**AGR,LDB,PSA,FIN,JED,LBR,MUNI,TACS**

@KyEggleston

**Comment by KyEggleston** [comment]
Consolidated Redline PDF is generated, and it is organized by modified date (matching page organization in Harms Package, and the 'Modified Date' page ordering in the Redaction App). Therefore, this passes, and closing ticket.
