### ISSUE TITLE
Update link to FOI Help site

### ISSUE THREAD

**Issue by katrinaferacini** [bcgov/foi-flow#4515]
Title of ticket: Update link to FOI Help site

#### Description
Refer to original ticket #4246. The link to the website should be updated to bring users directly to the Help articles site. Update supported by Matthew and Loren. 
#### Dependencies
 None
#### DOD
- [Update link from https://help.foirequests.gov.bc.ca/ to https://help.foirequests.gov.bc.ca/help-articles
 ]
- [ ] 
- [ ] 
- [ ]   
- [ ]

**Comment by nimya-aot** [comment]
working good, so closing it
