### ISSUE TITLE
Request ID in Redaction App Tab

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4522]
* As an IAO User
* I want to see the request ID on the browser tab of the doc reviewer
* so that I know which request I am redacting

**Assumptions & Scope**	
Feedback from super user session - having the request ID in the tab will be very helpful. Users also want a way to distinguish it from our typical tab numbering.

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Open Redaction App**
* GIVEN a user is on a request
* WHEN they open the redaction app
* THEN the redaction app will open on a new tab
* AND the tab will be labeled "Request ID - Reviewer"

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Tab labelling from super user session - open to feedback on the tab format... I went with Michelle's suggestion, but am mindful if someone has multiple tabs open they will not see it at a glance anyways. 

cc @lmullane @liseandtea @JHarrietha-AOT

**Comment by Aman-Hundal** [comment]
FE Change only

**Comment by lmullane** [comment]
Thanks, @Aman-Hundal

**Comment by Aman-Hundal** [comment]
Hi @lmullane I dont believe this has been completed as of yet by me or the other devs... Should we move this back to the backlog?
