### ISSUE TITLE
 DocReviewer Browser console  Error :  Refused to get unsafe header "Content-Range"

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#4526]
**Describe the bug in cu[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFBkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2def1197ecd9e424ddb25024b9463748edcf080d/image.png)
rrent situation**

There is an error   `Refused to get unsafe header "Content-Range"`  constantly happening few times on client side. Need to analyze the cause and find the fix 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbERkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9b0a2e7e0e63dfd55bd9896ae38dd066a06e4123/image.png)

**Link bug to the User Story**

**Impact of this bug**
Less impact on the functionality, but its not good hold errors on console.

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to Document Reviewer Web on any FOI REQUEST 
2. Click on Dev tool bar, console
3. See error
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFhkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--83762e8674d3bc985a9ea5a3c28ae8fcd3ee74b3/image.png)

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by milosdes** [comment]
@abin-aot @richard-aot added ```<ExposeHeader>Content-Range</ExposeHeader>``` to ```edu-dev-e``` bucket and it resolved the issue. Adding the header still needs to be done for the other buckets.

Console now shows ```{message: 'The file is not linearized.'}``` which is expected from WebViewer. May want to consider linearizing pdf files at some point in the future?
https://apryse.com/blog/pdf-format/what-is-pdf-linearization

**Comment by abin-aot** [comment]
Whoever tests this, we updated this config to eliminate this bug for EDU, MMA, TAC, HTH on test. once confirmed, we can close this for now, and for PROD 9.0 release , this will config update will be MANUAL task on updating the ALL S3 buckets cc: @richard-aot , @milosdes , @Aman-Hundal ,@antsand, @divyav-aot , @nkan-aot , @aparna-aot

**Comment by nimya-aot** [comment]
@milosdes i am still getting this console error on MMA request MMA-2023-12331016 on test-marshal. Could you please check?

**Comment by milosdes** [comment]
The header was applied to mmha-test-e bucket. The correct MMA bucket is muni-test-e. Applied the header to that as well now. 
So far the header is applied for:
EDU, MMA (which is muni-test-e), TAC, HTH, and mmha-test-e

**Comment by nimya-aot** [comment]
working good , so closing
