### ISSUE TITLE
Issue in generation of Final Package for Applicant

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#4529]
**Describe the bug in current situation**
For some requests, when you click on the Final Package for Applicant from the dropdown it just shows the toast message "Saving section stamps" and getting stuck there.
Requests with issue : 
EDU-2023-99901
EDU-2023-99903 

**Link bug to the User Story**

**Impact of this bug**
High

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to redaction app.
2. Do all redlines and annotations
3. Try to click on the Final Package for Applicant option from the create Response PDF dropdown

**Actual/ observed behaviour/ results**
Shows a toast message - Saving section stamps.. and won't proceed furthermore.

**Expected behaviour**
Should show the success toast and the final package should be ready to download.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2ZpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--265c0c3041043f7e4be49afb9a1b5e46ed6b4005/image.png)

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzdpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e4b87b9ede0cd98c9db0e34c9e0b3f46805eb807/Finalpackage.webm)

**Comment by aparna-aot** [comment]
Seems like this issue is happening only in test-marshal and is already fixed in dev-marshal. So please retest once all the changes in dev-marshal is moved to test-marshal.

**Comment by nimya-aot** [comment]
working good, so closing it
