### ISSUE TITLE
Change state of Intake in Progress request

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#453]
* As Intake Analyst
* I want a dropdown menu with the stages of a request cycle
* so that I can change the state of the request to Open

**Assumptions & Scope**	
Modal will appear whenever a change of state is selected

What is in and not in scope?
- In scope - Remove Open button
- Out of scope - Assignments at this point

**Acceptance Criteria**	

**Scenario 1: Intake in Progress request Dropdown menu**
* GIVEN I am an intake analyst
* WHEN I I am on 'Intake in Progress' request
* THEN the state menu at the top of the request  will say 'Intake in Progress'

**Scenario 2: Click on Dropdown menu for 'Intake in Progress' request**
* GIVEN an analyst is on an 'Intake in Progress' request
* WHEN click the state dropdown menu
* THEN they will see these options: Open, Closed, Redirect

**Scenario 3: Change to Open**
* GIVEN the Intake Analyst has clicked on the dropdown menu
* WHEN ... I select "Open" from the dropdown menu
* THEN the state of the request will be update to "Open"
* AND the drop menu will close
* AND the menu will read "Open"

**Scenario 4: Change to Redirect**
* GIVEN the Intake Analyst has clicked on the dropdown menu
* WHEN ... I select "Redirect" from the dropdown menu
* THEN the state of the request will be update to "Redirect"
* AND the drop menu will close
* AND the menu will read "Redirect"
* AND the request will remain on the Intake Team queue under Redirect

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [x] Is there a well articulated User Story?
2. [x] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [x] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [x] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [x] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
Passed QA test as expected
