### ISSUE TITLE
Issue in Exception handling, Exception Types trying to access invalid properties

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#4539]
**Describe the bug in current situation**
This is a technical bug/debt. Its being observed that on many locations on BACKEND PYTHON components particularly on 
`requestmanagementapi` and `reviewerapi` while printing and/or logging `exception` message , an invalid property is being used as below image. This causes an exception to occur again with that !.  This happens on PROD as well.  Issue is like, `messages` property does not exists for exception type `KeyError` . Important , `KeyError` is only a particular instance for this issue, but there will many other. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTdrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--72a278b72040bdfefd11166564d226ffe796ecc4/image.png)

**Link bug to the User Story**

**Impact of this bug**
There is no functional impact as such! But troubleshooting for any issues might get diverted due to the unwanted messages. 

**Chance of Occurring (high/medium/low/very low)** : HIGH

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcS9rIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bade72bc2ceca372e9dfab98d6d61f072d51abaa/image.png)

**Comment by abin-aot** [comment]
@Aman-Hundal  - Please check all computing services as well

**Comment by Aman-Hundal** [comment]
No functional testing needed / QA needed. Ticket closed.
