### ISSUE TITLE
Section number is cutting off on final package if word redaction happens

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4540]
**Describe the bug in current situation**
When redact single word  then section number is cutting off on final package

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-Marshal

**Steps to Reproduce**
1. Go to redaction app
2. Search a word on redaction panel to redact
3. Make redaction to that particular word
4. On final package section number is cutting off

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclRsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d196e78f718865c77bce6b7512c6418dffeaad62/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclBsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--06e6fdf607554a83a7e3297a3c21639eda435974/image.png)

**Comment by nkan-aot** [comment]
issue is only happening when using search and redact functionality. Ticket created with pdf tron https://support.apryse.com/support/tickets/63114

**Comment by lmullane** [comment]
@nkan-aot, I tested this ticket. Section numbers are still cut off in the Final Package PDF if more than one sections stamp has been applied.

[Uploading... Screenshot 2023-10-06 at 3.43.07 PM.png]

It does not seem possible for more than once section to be displayed where the word is if only 1 or 2 words are being redacted.

Would welcome @m-prodan and @liseandtea input here on how often a single word is redacted?

**Comment by m-prodan** [comment]
Single words can be redacted relatively frequently - the most common occurrence being IDIRs - that said, something like an IDIR would generally only be a single section. Other examples could include someones first or last name.... but again, this would likely only often draw one section, like section 22

**Comment by nimya-aot** [comment]
@nkan-aot If its a pdf tron ticket can we move back to sprint backlog?

**Comment by nimya-aot** [comment]
@nkan-aot Some places still section number is cutting of on final package. Could you please check ?

**Comment by nimya-aot** [comment]
@nkan-aot could you please fix the filling colour(it should be white) issue as well as @KyEggleston mentioned in the stand up

**Comment by nimya-aot** [comment]
working as expected, so closing
