### ISSUE TITLE
Section numbers on comments section  missing after flattening the redline pdf 

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4541]
**Describe the bug in current situation**
As the part of #4450 bug fix(flattening the redline pdf), section numbers are missing on the comment section now

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
test-marshal

**Steps to Reproduce**
1. Go to redaction app and make some redactions
2. Create Redline package
3. Download the redline package pdf
4. Earlier on the comment section, section numbers were present on the pdf

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGJxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--877f179782643dd31fcaa4a2b39d5f6ac81d4204/image.png)

Earlier it was look like this

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHJxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2970e0d5f9ce291822c489a4c8b5687caf7627b5/image.png)

**Comment by KyEggleston** [comment]
This has since been resolved - closing.
