### ISSUE TITLE
Dependabot Issues - Document Reviewer Web 

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#4542]
Title of ticket: 

#### Description
This ticket is to list and work on all the dependabot issues related to Document Reviewer Web.

#### Dependencies
Are there any dependencies?

#### DOD
**Priority-HIGH:**
- [ ] Cross-realm object access in Webpack 5 - Bump webpack from 5.74.0 to 5.76.1.
- [ ] Prototype Pollution in JSON5 via Parse Method - Bump json5 from 1.0.1 to 1.0.2.
- [ ] Prototype Pollution in JSON5 via Parse Method - Bump json5 from 1.0.1 to 1.0.2 .
- [ ] loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable - Bump loader-utils from 2.0.3 to 2.0.4.
- [ ] Inefficient Regular Expression Complexity in nth-check - The earliest fixed version is 2.0.1. But the latest possible version that can be installed is 1.0.2 because of the following conflicting dependencies: react-scripts@5.0.1 requires nth-check@^1.0.2 via a transitive dependency on css-select@2.1.0. No patched version available for nth-check.

**Priority-MEDIUM:** - NO need to fix now
- [ ] @adobe/css-tools Regular Expression Denial of Service (ReDOS) while Parsing CSS - Upgrade @adobe/css-tools to version 4.3.1 or later.
- [ ] word-wrap vulnerable to Regular Expression Denial of Service - Upgrade word-wrap to version 1.2.4 or later.
- [ ] semver vulnerable to Regular Expression Denial of Service - Upgrade semver to version 7.5.2 or later.
- [ ] tough-cookie Prototype Pollution vulnerability - Upgrade tough-cookie to version 4.1.3 or later.

**Comment by nkan-aot** [comment]
needs revisit after upgrade to 10.4
