### ISSUE TITLE
Sonarcloud Security Hotspot - Document Reviewer API

### ISSUE THREAD

**Issue by aparna-aot** [bcgov/foi-flow#4545]
Title of ticket: 

#### Description
This ticket is to list and work on all the Sonarcloud Security Hotspot issues related to Document Reviewer API.

Sonar cloud URL: https://sonarcloud.io/project/security_hotspots?id=bcgov_foi-docreviewer
#### Dependencies
Are there any dependencies?

#### DOD
**Review priority: HIGH :**

- [x] Cross-site request forgery (CSRF) - Make sure disabling CSRF protection is safe in api/reviewer_api/__init__.py . 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by abin-aot** [comment]
as per team's decision - we just need to check on local VSCODE plugin !

**Comment by sumathi-thirumani-aot** [comment]
Snapshot of headers
[Uploading... image.png]

**Comment by sumathi-thirumani-aot** [comment]
# Security Response headers
csp = (
    secure.ContentSecurityPolicy()
    .default_src("'self'")
    .script_src("'self'","'unsafe-inline'")
    .style_src("'self'","'unsafe-inline'")
)
hsts = secure.StrictTransportSecurity().include_subdomains().preload().max_age(31536000)
referrer = secure.ReferrerPolicy().no_referrer()
cache_value = secure.CacheControl().no_store().max_age(0)
xfo_value = secure.XFrameOptions().deny()
content_value = secure.XContentTypeOptions().set('False')
secure_headers = secure.Secure(
    csp=csp,
    hsts=hsts,
    referrer=referrer,
    cache=cache_value,
    content=content_value,
    xfo=xfo_value
)

@app.after_request
def set_secure_headers(response):
    secure_headers.framework.flask(response)
    response.headers.add('Cross-Origin-Resource-Policy','same-origin')
    response.headers['Cross-Origin-Opener-Policy'] = 'same-origin'
    response.headers['Cross-Origin-Embedder-Policy'] = 'unsafe-none'
    return response

**Comment by sumathi-thirumani-aot** [comment]
Can be closed.
