### ISSUE TITLE
Server Side Caching : Nice to implement for master data (keycloak data)

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#455]
Currently; the masterdata is queried often. This has a potential opportunity to have server side caching to avoid querying tables.

**Acceptance Criteria**

**Scenario 1: Author names on notifications takes time to load.**

GIVEN a user logs in and has already received a notification
WHEN the user views the notification
THEN the notification should show the author full name without any delay.

**Comment by mpilchar** [comment]
This should be fixed as part of HA work so no estimate is needed. Adding it to the Product Backlog so we test it cc: @aparna-aot @sumathi-thirumani-aot

**Comment by mpilchar** [comment]
Load time decreased from multiple seconds to milliseconds. Closing
