### ISSUE TITLE
Divisions are not showing up for MSD General  and CFD General/personal request

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4556]
**Describe the bug in cu[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3YrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--62f5684f08e3c59232588f62efcd35ad646df1b7/image.png)
rrent situation**
When MSD Ministry coordinator try to add divisions for General request, user is unable to see the division dropdown list
**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test

**Steps to Reproduce**
1. Create a MSD general request
2. Login as MSD ministry coordinator
3. Unable to add divisions

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
**MSD General**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcC8rIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--141f27d7e4339ed6d64bfc700ff3b9f870ef6598/image.png)
**CFD General**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclQrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2735e8c2229df6dee6a0d8c3467e96020d86c6d6/image.png)
**CFD personal**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc24rIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2ce407fd7e37ad36b69caf43a10d87af139ce360/image.png)

**Comment by nimya-aot** [comment]
@Aman-Hundal informed there is flag issue on Admin app. Once its fixed I can test it again

**Comment by Aman-Hundal** [comment]
Flags in the admin panel have been adjusted. Good to tesT!

**Comment by nimya-aot** [comment]
It is working good. So closing it
