### ISSUE TITLE
Disable options on PDFTRON/Apryse  WebViewer that generate comments

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#4565]
Title of ticket: 

#### Description
It was decided to disable the options/annotations/highlights/underline OR in simple terms whatever  causes the autogenerating of comments **_with_** the content on the document.  Reason is like, these information on comments can have Protected C data and that is not advisable to store inside our Transaction Database

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0lPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83c45b484c6ab1c7fb5bf505a8d32c64ec97efcd/image.png)

Refer to the DocumentID on TEST Marshal DocReviewer DB, as per the below query and see the `annotation` field for the information stored from the document.
`SELECT annotation FROM public."Annotations" WHERE documentid=7043 ORDER BY created_at DESC`

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Disable Underline, Highlight (not freehand highlight)
- [x]  Tryout, Use and Analyze all the options on REDACTION, ANNOTATION, SHAPE, COMMENT , if anything else auto-generate comments on the right panel.
- [x]  Configure the element on CONFIG MAP(existing , `REACT_APP_PDFVIEWERDISABLED`) on Document Reviewer FE, if not, lets discuss
- [ ] 
- [ ]

**Comment by m-prodan** [comment]
Per discussion at standup - the text selection redaction feature is also saving the content of the records, and should therefore be disabled too - the free form redaction is not saving the content

**Comment by aparna-aot** [comment]
**Features disabled as part of this ticket :** 

- Options text selection toolbar : Link URL or Page , Mark for Redaction, Strikeout, Squiggly, Underline, Highlight.
- Options from Annotate toolbar (top) : Underline, Highlight, Strikeout, Squiggly, Insert Text, Replace Text.
- Disabled text selection redaction feature - User can try to draw a redaction around words but it won't retain. Confirmed this case with @m-prodan .
Attaching a screen share for reference (In the video 1st 2 redactions are text selected redactions) : 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekVpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--367fdb3a9d9a2035771418081c03e54c868e7eb3/Textselection-redaction.webm)

**Comment by nimya-aot** [comment]
working as expected. so closing

**Comment by abin-aot** [comment]
re-opening this ticket in order to analyse the search from REDACT PANEL, then ADD mark option...

**Comment by abin-aot** [comment]
Additional Option from REDACTION PANEL ( Search -- > Multi Select --> Add Mark) , which copies search key word into the Annotation comment (a.k.a Document Content) has been handled in such way that copied content will be cleared, so that content wont show under "View All Annotations" , in turn wont be stored inside the DB. PR has created and merged, deployed to TEST- Marshal.  cc: @KyEggleston , @lmullane , @m-prodan

**Comment by KyEggleston** [comment]
Looks good on FE, no text displayed in annotation in Comments pane. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/85840162-c689-4f06-916f-fc49d799ee97)

@nimya-aot @aparna-aot - pinging in case there's anything for you to check.

**Comment by abin-aot** [comment]
@nimya-aot - This seems to be another issue where time on `Mark for Redaction` panel getting updated as current time, which by mistake thought as selection comment. Kindly try on a new request , investigate and/or log a new bug for the time update problem

**Comment by nimya-aot** [comment]
@abin-aot closing this ticket as the issue I mentioned above is not related to this one . I created another ticket for that issue.
https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4603
