### ISSUE TITLE
Redaction app shows as complete '100%' even though one page has no flag

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4574]
**Describe the bug in current situation**
On the redaction app, complete shows '100%' even though one page has no flag

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-marshal

**Steps to Reproduce**
1. Login as Ministry user and upload some documents
2. Login as IAO user and redact all those uploaded records and create flags to every pages, It shows '100%' as complete
3. After that upload one png file and doc file
4. Set flag to newly added doc file ,except png file
5. Then complete level shows '100%'
6. see error on request EDU-2023-1228

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0ViQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8a81ee9570f6103e4989babcb99eda9e48d2917/image.png)

**Comment by antsand** [comment]
It is a rounding issue. There are 201 pages and 200 pages had a flag. 200/201 == 99.5%  The system rounds it to the nearest higher value. 

One solution is to round it to the nearest lower value.

**Comment by nimya-aot** [comment]
Working good, so closing it
