### ISSUE TITLE
Response package has 'Duplicate' and 'Not Responsive ' files 

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4575]
**Describe the bug in current situation**
When we generate final package, it includes 'duplicate' and 'not responsive' files

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-marshal

**Steps to Reproduce**
1. Go to redaction app for request EDU-2023-2230
2. Try to download final package pdf
3. It includes both 'duplicate ' and 'not responsive' pages on the final package(Page 50 is a duplicate one)

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzhnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c258ff0e8daf3d083663183b261490efe5da1e1/image.png)

**Comment by aparna-aot** [comment]
This is not an issue rather a confusion caused by rearranging of pages on the left panel after final package download.
@nimya-aot  was comparing the pages of final package with the updated documents with rearranged/removed pages in left panel. This confusion can be addressed by the task - **Refresh page after creating final package#4582** .

**Comment by nimya-aot** [comment]
Closing it since it happened by the confusions
