### ISSUE TITLE
Release planning - scoping down & next steps

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#458]
Description
Determining scope that can be achieved by end of fiscal 

DOD
By Sept 3: 
https://miro.com/app/board/o9J_l48Pzcw=/
[ ] Revise stories in miro - Loren
[x ] Revise stories in miro - Arielle
[x ] Revise stories in miro - Molly
[x] Set up meeting with team for week of Sep 7 (Molly)
[x ] Prelim discussion with Chad (Loren)

Week of Sept 7:
[x ] Re-estimate new stories (team)
[ ] Prepare a report out

**Comment by arielleandrews** [comment]
User stories for CFR have been updated. No change to user stories for Extensions - after reading them closer, they are already written for manual entry.

**Comment by lmullane** [comment]
Thanks, @arielleandrews

**Comment by mpilchar** [comment]
Updated state change scenarios:  
- Changed all automated scenarios to manual state change
- Added ability to manually stop clock during fee estimate stage
- Added "close - incomplete" as a scenario

**Comment by mpilchar** [comment]
Pilot vision/scope shared at Sept 14 demo
