### ISSUE TITLE
Refresh page after creating final package

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#4582]
Because redacting in pdftron is a permanent change, once the final package is created the document is no longer in a state where it can be worked. We need to prompt or force the user to refresh after final package is created

**Link bug to the User Story**

**Impact of this bug**
high

**Chance of Occurring (high/medium/low/very low)**
high

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
- create final package
- try to add new redactions
- foippa modal does not popup

**Comment by milosdes** [comment]
fix should be visible in test-marshal.

**Comment by nimya-aot** [comment]
working as expected, so closing it
