### ISSUE TITLE
Deployment set up of additional components on d106d6-PROD  (Web, Zipper )

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#4584]
Title of ticket: 

#### Description
The purpose of this task is to analyze, re-organize the resources, and set up deployment for  Document Reviewer Web, Zipper and/or any other components missing( technically all other components are already on PROD)

Tip :  Can consider #4585 as well with this task

Note : As discussed during the sprint planning on 11-OCT, @abin-aot 's personal suggestion is to have vanity URL for FOI Document Reviewer Web app after 9.0 release. since it  updates for SSL for the new vanity URL affects existing PROD, DEV, TEST set up , as showed on the meeting. We can plan/request it after 9.0 release , and aim for 9.1 release, till then Business will be seeing regular OCP provisioned URL , similar to what we have with TEST-Marshal URL on the browser address  bar
cc: @sumathi-thirumani-aot , @m-prodan @lmullane 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Analyze the resource usage(existing) on Dedupe, Conversion, API , DB on d106d5-prod - Update the team!
- [x] Regular DEV, TEST!!
- [x]  if any one of them has more than 60-70% unused we can release and reuse it on new or any existing components - Need to discuss. Don't think we need to request more resources! - but confirm!
- [x]  Set up yaml, ENV VAR, Vault integrations 
- [x]  Can be do deployment for Web, Zipper Ahead of time ? I feel yes, but do an impact analysis, update team then we can action.
- [x] Update CORS setting on S3 Buckets with the new Web URL. Can consider #4585 as well with this task

Step-1 (Resource Optimization & Request)
--------
- [x] Resource Optimization Analysis d1***-prod & propose values
- [x] Adjust existing resources in d1***-prod
- [x] Request to raise 8G of limit memory (Matt)

Step-2 (Deployment of components in non-prod)
--------
- [x] Setup zipperservice in dev
- [x] Setup zipperservice in test

Step-2 (Deployment of components in prod)
--------
- [x] Setup reviewer-web in d1***-prod
- [x] Setup reviewer-zippingservice in d1***-prod

**Comment by sumathi-thirumani-aot** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek4rQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54cd634a03c10fc2e10b85ed419a27c71687e019/image.png)

**Comment by abin-aot** [comment]
Updated all S3 Buckets with new Web URL for CORs Config
