### ISSUE TITLE
Withheld in Full - Unable to Select from 'Divison' filter 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4601]
**Describe the bug in current situation**

Unable to select the 'Withheld in Full' page flag in the left navigation pane when the 'Organize By' is set to 'Division'. 

Tested on EDU-2023-191988 in Test-Marshal

![image](https://github.com/bcgov/foi-flow/assets/117312323/a66d6fd4-1083-4a27-8e66-1d833e028053)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

Medium - may affect CFD and MSD primarily. When records are tagged by type rather division (in the Records tab, and may be redacted and flagged under the 'Division' filter 

**Chance of Occurring (high/medium/low/very low)**

High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a request in the redaction app with pages
2. Click on 'Division' filter under 'Organize By'
3. Right-click a page and select 'Withheld in Full'
4. See error, where the page flag is not applied, and no FOIPPA section modal appears

**Actual/ observed behaviour/ results**

Withheld in Full page flag is not applied, and no FOIPPA section modal appears

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a user is in the redaction app, on selected 'Division' in the 'Organize By'
WHEN the user right-clicks and tries to apply the 'Withheld in Full' flag
THEN the flag is applied, and the FOIPPA section modal is displayed

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nimya-aot** [comment]
working as expected, so closing
