### ISSUE TITLE
Release 8.4.0 - MCFD/MSD Records Scanning and Uploads

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#4602]
**Place-in the release name**
Release 8.4.0 - MCFD/MSD Records Scanning and Uploads
1. IAO Scanning Team - Records Upload - CFD Personals - #4292
2. IAO Scanning Team - Records Upload - MSD Personals - #4303
3. MCFD Personal Request - Ministry User - Upload by Division - #4569
4. MCFD Personals Requests - Tagging and Scanning States - #4362
5. MSD Personal Requests - Ministry Upload and Tagging - #4305
6. Team email for applicant correspondence - #4099
7. Update Admin App for Section, Personal, Hierarchy Flag - #4427
8. Attachments - Add Consult Tag - #4434
9. Ministry Sign-Off to Response - Mandatory Criteria - #4245
10. Python version update 3.8 to 3.10.8

#### Activity start time
Summarize issue 

#### Activity end time
Summarize issue 

#### Step-1: Database Backup (Check the desired components)
Capture the backup details 
- [x] FOI DB (xxx)
- [ ] BPM DB
- [ ] Docreviewer DB

#### Step-2: Image Backup (Check the desired components)
Capture the image details 
- [x] request-management-api (yyy)
- [x] forms-flow-web
- [ ] notification-manager
- [ ] reviewer-api
- [ ] reviewer-web
- [ ] reviewer-conversion
- [ ] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

#### Step-3: Production - Tagging of image (Check the desired components)
- [x] request-management-api
- [x] forms-flow-web
- [ ] notification-manager
- [ ] reviewer-api
- [ ] reviewer-web
- [ ] reviewer-conversion
- [ ] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

#### Step-4: Signoff from business
- [x] Yes
- [ ] No
- [ ] Not Applicable

#### Step-5: Healthcheck (Check the desired components)
- [x] FOI DB
- [ ] BPM DB
- [ ] Docreviewer DB
- [ ] redis-
- [ ] redis-
- [ ] redis-
- [x] request-management-api
- [x] forms-flow-web
- [ ] notification-manager
- [ ] reviewer-api
- [ ] reviewer-web
- [ ] reviewer-conversion
- [ ] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

#### Step-6: Staging - Tagging of image (Check the desired components)
- [ ] request-management-api
- [ ] forms-flow-web
- [ ] notification-manager
- [ ] reviewer-api
- [ ] reviewer-web
- [ ] reviewer-conversion
- [ ] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

**Observations**
List down the observations of incidents which happened in release window

**Overall Rating**
- [ ] Good (No change)
- [ ] OK (With observations)
- [ ] Bad(Rollback)

[Uploading... release 8.4.0 deployment steps.txt]

**Comment by abin-aot** [comment]
@richard-aot  - Manual steps for Keycloak group email has been done, but need to COPY email templates from TEST TO PPROD forms bucket and a SQL script need to be run to make `issection` and 'isspecifictopersonalrequests' to false for the existing DIVISIONs on PROD

**Comment by milosdes** [comment]
### DB BACKUPS
In pod "foi-bkup-4-hhx8m" on "d7abee-prod" namespace
```
 ./backup.sh -1
```
### IMAGE BACKUPS
```command
oc tag request-management-api:prod-002 request-management-api:prod-002-bu -n d7abee-tools
oc tag forms-flow-web:prod forms-flow-web:prod-bu -n d7abee-tools
oc tag reviewer-api:prod reviewer-api:prod-bu -n d106d6-tools
```
DEPLOYMENT
```command
oc tag request-management-api:test request-management-api:prod-002 -n d7abee-tools
oc tag forms-flow-web:test forms-flow-web:prod -n d7abee-tools
```

note: reviewer-api was backed up but not deployed as there were no changes on it
