### ISSUE TITLE
Request moved to CFR - did not Auto-Assign to Ministry Queue - Need to Reproduce/Analyze

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4606]
**Describe the bug in current situation**
A user reported in the support channel a concern with a request, they noticed the Ministry assigned to field was blank, but was in CFR. We confirmed with the Ministry user that the request was not showing up in their queue.

Moving the request back to open, and then to 'CFR" seems to have resolved this, but we are unsure how this happened in the first place.

Request ID is MAG-2023-33262, COR-2023-33415

**Link bug to the User Story**

**Impact of this bug**
High impact if not caught, request could lose a significant number of days before it is noticed. 

**Chance of Occurring (very low)**
To date, we've not gotten a bug report like this - it is unclear how to replicate this exactly, or how it even occurred in the first place. Request ID from prod was MAG-2023-33262, COR-2023-33415

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nimya-aot** [comment]
working as expected, so closing
