### ISSUE TITLE
Redactions created on one page is showing up on next page in the 'Redline pdf'

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4627]
**Describe the bug in current situation**
when a user created redactions on one page, but on the 'redline package' it shows up on the next page

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Every users

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Request EDU-2023-09561024 on test-marshal

**Steps to Reproduce**
1. Go to records tab and upload an excel file as a ministry user
2. Login as IAO user and go to redaction app for the request
3. Set 'duplicate ' flag on first page
4. Create 'with held in full' flag on the next page
5. Then generate 'Redline pdf' for the request
6. See full page redaction is showing up on the 3rd page instead of 2nd

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nimya-aot** [comment]
@richard-aot I noticed that this issue happens if a page is set for a Duplicate/Not responsive flag, then following page's redaction is moving to next page and so on

**Comment by richard-aot** [comment]
Thanks, @nimya-aot. I can reproduce this issue on test-marshal. Will do some investigation.

**Comment by nimya-aot** [comment]
working as expected, so closing it
