### ISSUE TITLE
Cancel FOIPPA Modal is calling delete redaction/annotation api

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#4635]
Pressing cancel on the FOIPPA modal is making unnecessary call to backend api. At this point no redaction has been saved to backend yet so no need to call delete api

**Impact of this bug**
Unwanted api call

**Chance of Occurring (high/medium/low/very low)**
high - happens everytime

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
dev-marshal, test-marshal

**Steps to Reproduce**
- open dev tools to monitor api calls
- Draw redaction
- click cancel on FOIPPA modal

**Actual/ observed behaviour/ results**
- delete redaction api calls even though no save annotation api has been called

**Expected behaviour**
- no delete api call should go

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

Also maybe a related issue, if a user performs the same action on a request with no annotations/pageflags created yet, the delete redaction call will throw a backend error. Need to make sure this doesn't happen even after the above bug is fixed

**Comment by nimya-aot** [comment]
working good, so closing

**Comment by nkan-aot** [comment]
confirmed not happening anymore
