### ISSUE TITLE
Set up additional deployment environment for FOI FLOW, FOI DOCREVIEWER Apps

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#4637]
Title of ticket: 

#### Description
The purpose of this ticket is to set up deployment environment  on OCP project namespace(d7abee,d106d6) for all `required` apps, microservices . Also, includes integration of the the new additional github branch(dev-<newname>, test-<newname>) with CI/CD pipelines, image tagging etc. 

#### Exclusions
- Angular App - FOI REQUEST Submission App
- No forms flow Payment components needed! - Unless we have a solid reason
- No reporting apps required - redash, EDW etc.
- No HA required as of now, Large truck computing services needed - this is for Dedupe Service, Conversion etc.

#### Dependencies
Are there any dependencies? 

Might require more infrastructure level resources - Memory, CPU ? So need to request, Added as a DOD

#### DOD
- [x] Analyze the existing OCP namespace and review the resource usage of components on  Marshal env(Dev, Test)
- [x] Prepare foi-docreviewer deployment yml
- [x] Prepare foi-flow and notification-manager deployment yml
- [x] Set up FOI FLOW Apps for dev-rook- Req. management API, FOI _WEB, BPMN , Patroni DB etc.
- [x] Set up FOI FLOW Apps for test-rook- Req. management API, FOI _WEB, BPMN , Patroni DB etc.  
- [x]  Need for a request to platform team to increase the memory, CPU - Inform @lmullane ?  Can we BORROW from existing marshal components(dev-marshal, test-marshal) and set up a parallel deployment with that and/or with remaining resources in the OCP ? 
- [x]  Ready with naming conventions
- [x]  Set up FOI FLOW Apps - Req. management API, FOI _WEB, BPMN , Patroni DB etc.
- [x]  Set up Document Review apps - Doc Review Web, API, Dedupe, Conversion, Zippier, PDFStitch etc. - All computing services
- [x] Integration testing - confirm fuctionality, CI/CD pushes, triggers etc.

**Comment by sumathi-thirumani-aot** [comment]
**Environment Name Meaning,**
marshal -> organize  things, esp. in order to achieve a particular aim.
rook (Idea from Chess) -> Go-To warriors. They get the job done quickly and efficiently. The rook is a piece in the game of chess. It may move any number of squares horizontally or vertically without jumping. Also a bird name : extremely intelligent and able to solve complex puzzles using objects and teamwork.

**Comment by abin-aot** [comment]
@sumathi-thirumani-aot @milosdes @Aman-Hundal @divyav-aot completed this task, hence closing
