### ISSUE TITLE
Apryse 10.5 upgrade and check all Docreviewer functionalities, open issue with Apryse

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#4640]
Title of ticket: 

#### Description
The purpose of this task is to upgrade the PDFTRN/Apryse version to 10.5 as per the directions on this support ticket, https://support.apryse.com/support/tickets/63510. I assume they are other tickets as well which indicated 10.5 upgrade, so whoever takes this task, please have a look on to the OPEN apryse tickets and read comments for 10.5 upgrade. Then strategize the upgrade and functionality testing.

#### Dependencies
Are there any dependencies? 
The idea is to safeguard FOIFLOW 9.0 release with PDTRON 4.0 first (a hardbinded major-minor version) as per the package.json, then handle 10.5 upgrade and further confirmations, quality on test-marshal. Need to coordinate/inform the team members, before this action on TEST-marshal

#### DOD
- [x]  Start with LOCAL dev machine upgrade to PDFTON 10.5
- [x]  Test locally all functionalities, including the support ticket fixes - with 2KB files x 900 and 1/2 300 page file to comfortably test on local dev machine
- [x]  Inform and coordinate with team 
- [ ]  Release it to TEST-Marshal, if Dev-marshal is occupied ! Coordination required
- [ ] Integration, regression testing

**Comment by abin-aot** [comment]
As part of this exercise , below issues with PDFTRON are resolved

1. https://support.apryse.com/support/tickets/63625 - Page Blank issue 
2. https://support.apryse.com/support/tickets/63510 - RedactionBox not drawing at the right position
3. https://support.apryse.com/support/tickets/61440 - Full Page Redaction Does Not Hide Entire Page/Is Rotated. This one has minor issue with  section label alignment , but main part of issue is resolved

**Comment by nimya-aot** [comment]
working as expected, so closing
