### ISSUE TITLE
Annotation limit (250) not working as expected

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#4649]
**Describe the bug in current situation**
The page flag selection more than 250 pages or the annotation add using the page selection/redaction based on pages are not working as expected. It shows the popup, but after clicking on the popup, it allows the user to perform operations again on the selected pages. Sometimes, it applies the freetext/redact box for the pages.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to doc reviewer
2. Click on more than 250 pages/ using redact pages give more than 250 pages
3. right click or click on add mark

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
Tested selecting >250 pages in left pane (document tree), 'Redact Pages', and in find and redact ('Redaction Panel'). All displayed message that select pages or redactions reached limit. Unable to select >250 pages afterwards, playing around with different possibilities. Appears resolved, closing ticket.
