### ISSUE TITLE
AssignedTo in dashboard shows username instead of LastName, FirstName

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#465]
Title of ticket: 

#### Description
AssignedTo in dashboard shows username instead of LastName, FirstName

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] function to form Assigned to in "LastName, FirstName" format
- [ ] Pass the updated assignedTo in the dashboard GET API
- [ ] Update the mapping of assignedTo field in the FE

**Comment by m-prodan** [comment]
This appears to be addressed - closing this ticket, names (including group names ie: flex team) are now appearing in the queue instead of IDIR login names.
