### ISSUE TITLE
Redline stitch with single page document marked as Duplicate/Not Responsive is not excluded

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#4652]
**Describe the bug in current situation**
Redline stitch with single page document marked as Duplicate/Not Responsive is also included in downloaded file

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Every users

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Acceptance Criteria**
Scenario#1:
1. Mark one of the document's all pages as duplicate or not responsive
2. Expected this document to be not included in "Redline Package"

Scenario#1:
1. Mark all of the documents and its pages as duplicate or not responsive
2. Expected the "Redline Download Option" to be disabled.

**Steps to Reproduce**
1. Go to records tab and upload an single page document as a ministry user
2. Login as IAO user and go to redaction app for the request
3. Set 'duplicate ' flag on that page
4. Then generate 'Redline pdf' for the request
5. See the page is shown up in downloaded file.

**Actual/ observed behaviour/ results**

**Expected behaviour**
The page marked as duplicate or not responsive; should not be included.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nimya-aot** [comment]
@sumathi-thirumani-aot When I tried to upload one page document, its trying to upload the page  to s3 browser for a long time. Could you please disable the 'Redline for pdf" button if we have only one division with one document
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGQrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c21b178a19dfaa5d1e20178e1059db6eb8e0544/image.png)

**Comment by nimya-aot** [comment]
working as expected, so closing
