### ISSUE TITLE
Change of state to Call for Records

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#467]
* As a Flex team user
* I want to be able to change the state of an Open Request to Call For Records
* so that I can assign it to the responsible ministry team

**Assumptions & Scope**	
What are the assumptions for this story?

What is in and not in scope?
 **Comments are not in scope, editing ministry team and waters also not in scope**

Editing watchers in not in scope

Editing the selected ministry is not in scope
 
 Assigning to responsible ministry team is in scope

**Acceptance Criteria**	

**Scenario 1: Change to Call for Records 1**
* GIVEN the Flex Analyst has clicked on the dropdown menu for an Open request
* WHEN ... I select "Call for Records" from the dropdown menu
* THEN a modal will open:
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088420
* AND the responsible ministry team will be pre-selected
* AND there will options to 'Save' and 'Cancel'

**Scenario 2: Cancel change to Call for Records**
* GIVEN the Flex Analyst is on the modal
*  https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088420
* WHEN ... I select 'Cancel'
* THEN a modal will close
* AND the request will be remain in an Open state
* AND the dropdown menu will read Open

**Scenario 3: Save change to Call for Records 1**
* GIVEN the Flex Analyst is on the modal
*  https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088420
* WHEN ... I select 'Save'
* THEN a modal will close
* AND the request state will change to Call for Records
* AND the dropdown menu will read Call for Records
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088423

**Scenario 4: Assigning Call for Records to ministry team**
* GIVEN the Flex Analyst has saved the change of a request to Call for Records
* THEN the request will be assigned to the responsible ministry team
* AND the request will appear in the ministry team queue under the state of Call for Records
* AND the request will appear in the flex team queue and IAO assignee queue under the state of Call for Records
* AND the assigned to dropdown on the request will read xxxx ministry team

Dependencies: 

What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@arielleandrews, @JHarrietha-AOT, as discussed:

- Comments are not in scope
- Editing watchers in not in scope (can be taken off completely)
- Editing the selected ministry is not in scope

@JHarrietha-AOT, please update the designs accordingly.

cc @mpilchar

**Comment by arielleandrews** [comment]
Looks good @lmullane. One question - for Scenario 1, with the Ministry being pre-selected, would it make sense to make that field display only and not give the option to assign it to any other user?

**Comment by JHarrietha-AOT** [comment]
Would agree with @arielleandrews, of just added that the Ministry will be automatically selected based off of the Ministry of the Request, and that the field is uneditable/display only.

**Comment by lmullane** [comment]
Duplicate of #360
