### ISSUE TITLE
OIPC - Create Complaint Flag on Open Requests

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4671]
* As an IAO user
* I want to be able to mark a request as receiving an OIPC Review or Complaint
* so that I, and the Ministry coordinator can know which requests have active complaints/reviews

**Assumptions & Scope**	
This is the first of several stories aimed at allowing IAO users to flag requests as being subject to an OIPC review or complaint.

There can be multiple complaints or reviews associated to a request.

Applicants can complain about any decision government makes - issuing a fee estimate, a fee waiver decision, the adequacy of a search for records, the decision to take an extension, not responding by the legislated due date, application of severing etc.

**Calendar pickers for date fields should all use the same functionality as elsewhere in the app**

What is IN scope?
For this ticket, this will cover the creation of the OIPC complaint, and how to add separate complaints on requests that are currently open.

What is NOT in scope?
Behaviour to enter an OIPC review on a closed request will be covered in a separate user story
Queue updates and OIPC review flags will be covered in a separate user story
Notifications and system generated comments will be covered in a separate user story

**Acceptance Criteria**	

**Scenario 1: Create OIPC Review**
* GIVEN an IAO user is in the request details view of a general or personal request
* WHEN they click on the Review Flag button
* THEN a drop down will appear with the values: OIPC Review and No Review
* AND No Review will be inactive

**Scenario 2: Create OIPC Review - Select OIPC Review**
* GIVEN an IAO user has activated the Review flag drop down
* WHEN they click OIPC review
* THEN the drop down will close
* AND they will be brought to the OIPC tracking section on the request view

**Scenario 4: Mandatory Fields - Basic**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN the review is first made
* THEN the mandatory fields will be: OIPC No., Received Date, Review Type, Reason, Status

**Scenario 5: OIPC Number Field**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN they select the 'OIPC No.' open-text field
* THEN they will have the ability to enter the OIPC number

**Scenario 6: Received Date Field**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN they select they click on the calendar picker for the received date field
* THEN the calendar picker will open
* AND the user can pick any date from the date today, to a date in the past

**Scenario 7: Received Date Field - Complete Selection**
* GIVEN an IAO user has the received date calendar picker open
* WHEN they select they select a valid date
* THEN the calendar picker will close
* AND the date will appear with the format YYYY-MM-DD

**Scenario 8: Review Type Drop Down**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN they activate the drop down for review type
* THEN they will see the following options: Complaint, Review, and Investigation

**Scenario 9: Reason Drop Down - Complaint**
* GIVEN an IAO user is at the OIPC tracking details section
* AND the review type selected is Complaint
* WHEN they activate the drop down for Reason
* THEN they will see the following options: Adequate search, Extension, Fee Amount, Fee Waiver, Duty to Assist, Other

**Scenario 10: Reason Drop Down - Review**
* GIVEN an IAO user is at the OIPC tracking details section
* AND the review type selected is Review
* WHEN they activate the drop down for Reason
* THEN they will see the following options: Application of Exceptions, Deemed Refusal, TPN - 22, TPN - 21, TPN - 18.1, Reg 3, Reg 4, Reg 5, s. 43, Other

**Scenario 11: Reason Drop Down - Investigation**
* GIVEN an IAO user is at the OIPC tracking details section
* AND the review type selected is Investigation
* WHEN they activate the drop down for Reason
* THEN they will see the following options: Other

**Scenario 12: Status Drop Down**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN they activate the drop down for Status
* THEN they will see the following options: Mediation, Investigation, Inquiry, Awaiting Order, Closed

**Scenario 13: Outcome Drop Down**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN they activate the drop down for Status
* THEN they will see the following options: Abandoned, Withdrawn, Resolved in Mediation, Closed

**Scenario 14: Inquiry Fields**
* GIVEN an IAO user has added an OIPC Flag to the file
* WHEN they view the OIPC Details section
* THEN the following sections will default to 'No': In Inquiry, In Judicial Review, Subsequent Appeal

**Scenario 15: Inquiry Field - Yes**
* GIVEN an IAO user is on the OIPC Details section
* WHEN they check 'Yes' for the Inquiry section
* THEN the following additional fields will appear: Order Comply Date, Order No., Inquiry Outcome

**Scenario 16: Mandatory Fields - Inquiry**
* GIVEN an IAO user is at the OIPC tracking details section for Inquiry
* WHEN they enter information into any field
* THEN all other inquiry fields will become mandatory

**Scenario 17: Inquiry Outcome Drop Down**
* GIVEN an IAO user is at the OIPC tracking details section for Inquiry
* WHEN they activate the drop down for Inquiry Outcome
* THEN they will see the following options: Decision Upheld, Decision Partially Upheld, Decision Overturned

**Scenario 18: Comply Date Field**
* GIVEN an IAO user is at the OIPC tracking details section for Inquiry
* WHEN they select they click on the calendar picker for the Order Comply Date
* THEN the calendar picker will open
* AND the user can pick any date from the date the OIPC review was received to any date in the future

**Scenario 19: Received Date Field - Complete Selection**
* GIVEN an IAO user has the Order Comply Date calendar picker open
* WHEN they select a valid date
* THEN the calendar picker will close
* AND the date will appear with the format YYYY-MM-DD

**Scenario 20: Judicial Review Field - Yes**
* GIVEN an IAO user is on the OIPC Details section
* WHEN they check 'Yes' for the Judicial section
* THEN the Yes box will be checked
* AND the save button will be active

**Scenario 21: Subsequent Appeal Field - Yes**
* GIVEN an IAO user is on the OIPC Details section
* WHEN they check 'Yes' for the Subsequent Appeal
* THEN the Yes box will be checked
* AND the save button will be active

**Scenario 22: Save button inactive**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN all of the mandatory fields do not have values in them
* THEN the common save button for the request will be disabled

**Scenario 23: Save button active**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN all of the mandatory fields have valued in them
* THEN the common save button for the request will be enabled

**Scenario 24: Save button activate**
* GIVEN an IAO user is at the OIPC tracking details section
* AND the save button is active
* WHEN the user clicks save
* THEN the OIPC details will be saved

**Scenario 25: Add Review/Complaint**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN they click on the + symbol
* THEN an additional OIPC detail section will appear
* AND the save button will become inactive

**Scenario 26: Remove Review/Complaint**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN they click on the trash can symbol of a saved OIPC complaint or review
* THEN a modal will appear with the text "Are you sure you want to delete this OIPC Review?"
* AND the options will be continue or cancel

**Scenario 27: Remove Review/Complaint - Continue**
* GIVEN an IAO user is on the modal for removing an OIPC Review
* WHEN they click on the continue button
* THEN the modal will close
* AND the OIPC review details will be removed

**Scenario 28: Remove Review/Complaint - Cancel**
* GIVEN an IAO user is on the modal for removing an OIPC Review
* WHEN they click on the cancel button
* THEN the modal will close
* AND the OIPC review details will remain

**Scenario 29: Remove Review/Complaint - Last OIPC Review**
* GIVEN an IAO user is on the modal for removing an OIPC Review
* AND it is the ONLY OIPC review complaint
* WHEN they click on the continue button
* THEN the modal will close
* AND the OIPC review details will be removed
* AND the OIPC review details section will disappear

**Scenario 30: Closed Date Field**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN they select they click on the calendar picker for the Closed date field
* THEN the calendar picker will open
* AND the user can pick any date from the date today, to a date in the past

**Scenario 31: Closed Date Field - Complete Selection**
* GIVEN an IAO user has the Closed date calendar picker open
* WHEN they select they select a valid date
* THEN the calendar picker will close
* AND the date will appear with the format YYYY-MM-DD

**Scenario 32: Outcome Selection - Open and Closed Request**
* GIVEN an IAO user has activated the Outcome Selection
* AND the request is open or closed
* WHEN they select the outcome 
* THEN a modal will appear asking: "Are you sure you are ready to select an outcome? This will complete the review and lock all fields" and the options will be to continue and cancel

**Scenario 33: Outcome Selection Modal - Continue**
* GIVEN an IAO user has activated the Outcome Selection Modal
* WHEN they select Continue
* THEN the modal will close
* AND all fields for the OIPC review will be inactive EXCEPT for the Outcome drop down

**Scenario 34: Outcome Selection Modal - Cancel**
* GIVEN an IAO user has activated the Outcome Selection Modal
* WHEN they select Cancel
* THEN the modal will close
* AND the outcome field will be blank

**Scenario 35: Edit - Completed OIPC Review**
* GIVEN an IAO user is on the tracking section of a completed OIPC review
* WHEN they click on the outcome dropdown
* THEN the only Option will be amend

**Scenario 36: Edit - Completed OIPC Review - Amend**
* GIVEN an IAO user is on the outcome dropdown of a completed OIPC review
* WHEN they select 'amend'
* THEN a modal will pop up asking: "Are you sure you want to amend this completed OIPC review? You will need to re-select an outcome to close it again." with the options to Continue or Cancel

**Scenario 37: Amend OIPC Review - Continue**
* GIVEN an IAO user has activated the Amend OIPC Review modal
* WHEN they select Continue
* THEN the modal will close
* AND all fields for the OIPC review will become active again
* AND the outcome field will be empty and revert to its original selections

**Scenario 38:  Amend OIPC Review - Cancel**
* GIVEN an IAO user has activated the Amend OIPC Review modal
* WHEN they select Cancel
* THEN the modal will close

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/987204834

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@JHarrietha-AOT - this might be the biggest user story I've ever put together - and its mostly because of all the darn drop downs.

Based on some early feedback I've received - I've made some changes to some of the drop down options. Also note that if something goes to judicial review, or subsequent appeal, I think there should be additional fields to fill in to further break things down (eg - Judicial review will have a court number, a decision date, and a specific outcome that differs from Inquiry)

Give it a read, may need some design changes, happy to find time to discuss further.

cc @liseandtea  @lmullane @KyEggleston

**Comment by JHarrietha-AOT** [comment]
Designs with versions following AC can be found here - link included in ticket with all fields (Adding all here for easy access)

OIPC Queue Design: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975255940
OIPC Flag In-Active: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975255941
OIPC Flag Active: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/987195648
Single OIPC Details w Investigator Field: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/987195649
Multi OIPC Details w Investigator Field: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/987195650
Single OIPC Details w-out Investigator Field: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/987204833
Multi OIPC Details w-out Investigator Field: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/987204834
Module for (last) Outcome Selected: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/987195651

**Comment by m-prodan** [comment]
Note from refinement: Judicial review and subsequent appeal - develop to be flexible for future fields, but not necessary right now.

**Comment by divyav-aot** [comment]
**Refinement Comments:**
**ReviewType:** Complaint, Review, and Investigation

**Reason:** Adequate search, Application of Exceptions, Deemed Refusal, Extension, Fee Amount, Fee Waiver, Records do Not Exist, Duty to Assist, TPN - 22, TPN - 21, TPN - 18.1, Reg 3, Reg 4, Reg 5, s. 43, Other

**Status:** Mediation, Investigation, Inquiry, Awaiting Order, Closed

**Outcome:** Abandoned, Withdrawn, Resolved in Mediation, Closed, Amend - **default “Select Outcome”**

**InquiryOutcome:** Decision Upheld, Decision Partially Upheld, Decision Overturned

the position of the flags? - **restricted below the watchers. OIPC review beside the watchers**

what are the OIPC flag dropdown values? - **No Review, OIPC Review. No Review is the default.**

can we just enable OIPC flag alone without filling the OIPC review section? - **No. They should fill in the OIPC details**

is there any relation between review type and reason? any validation is needed? - **Yes. a pdf will be shared for the validation**

do we have any additional fields for In Judicial Review, Subsequent Appeal? - **No for now. But, in future there are chances so build the BE accordingly.** 

do we have a separate save button for OIPC? - **No. The common save button is used for OIPC**

inquiry date validation - can enter only dates > today - **The label should change to Order Comply Date. Validation is  with future dates. There will be a new field called RecievedDate added with validation of that day and past days.**

can the OIPC complaint have more than 1 state(In Inquiry/Judicial Review/ Sub appeal)? - **Yes, all can be selected as Yes**

when the outcomes are closed for all sections, do we need the OIPC flag on? - **it is not connected to outcome so it will be always on if at least 1 complaint added**

How the edit should work? if the review already closed, should we allow them to edit again? - **in general when the outcome is not selected, they should be able to edit. If the outcome is selected then all columns will be disabled, and if a change is needed, then select the "Amend" outcome and change the values.**

**No restriction in creating OIPC complaint even if there is an OIPC complaint exists without outcome**

can ministry edit the OIPC review section? for ministry, we will just disable all the fields. - **Separate US for Ministry View as the details should be flat text**

can we close a request if there is OIPC review in progress? - **should be able to close but it should be visible in the both dashboard. If all Complaints outcome has been entered, then no need to show in the dashboard** 

How the delete should work? any validation based on outcome or any other values? - **No validations. Keep the delete button active all the time.**

is there any axis sync? - **Not using the existing axis sync option. A separate ticket will be created to bring all the historical OIPC requests to foi-flow**

**if they delete all the OIPC complaints, then change the flag to No Review**

**if they change the OIPC Review to No Review, then show a modal to delete all the OIPC  Details related that request**

**Comment by divyav-aot** [comment]
**PDFs shared during the refinement:**
https://bcgov-my.sharepoint.com/:b:/g/personal/lise_mino_gov_bc_ca/ESvBsZmrIvdEh_eStCWZIpIBssBb324wqRAcCgmJPrNM-w?e=zm71IX

https://bcgov-my.sharepoint.com/:b:/g/personal/lise_mino_gov_bc_ca/EVzMiVgBYhJMmu2RR1DpBHcBsA9sjlDlXwvRh7X5iO3jmQ?e=Z4o5AD

**Comment by m-prodan** [comment]
I've updated the AC For this based on the refinement discussion and notes I have.

**Comment by nimya-aot** [comment]
@m-prodan @liseandtea  
Do we need validations for OIPC No and order No? Currently it allows symbols and special characters. What is the format normally?
<img width="1259" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFEwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72aa6be1b95e5515d5b965435406f7042900b8a7/image.png" alt="image.png" />

**Comment by liseandtea** [comment]
@nimya-aot The format for "OIPC No" and "Order No" is F23-00000. There will always be the capital "F" followed by the last 2 digits of the year, dash, then the number the order is in their sequencing. The number sequence is dependent on the amount received/orders created, e.g. F23-01 vs F23-123. Note that  "OIPC No" tends to have 5 numbers in the sequence F23-12345.

**Comment by nimya-aot** [comment]
@Aman-Hundal Could you please add validations for OIPC No and Order No as Lise mentioned. Also currently ministry can flag the request as OIPV review. Could you please remove?
<img width="1472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekkxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e358f121815abd0417ed830c3cb966b97645fd1/image.png" alt="image.png" />

**Comment by nimya-aot** [comment]
@Aman-Hundal Labels needs to be changed .could you please check scenario 15?
<img width="1362" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmcxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e22298cd895ed3fd430df8f172a60dc55bd1c814/image.png" alt="image.png" />

**Comment by nimya-aot** [comment]
@m-prodan Do we need to include the closed state scenario on the AC's as per @JHarrietha-AOT design below?
<img width="1597" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWc2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a8450ac4f52019c9908b90d15049dc81e40b8aa/image.png" alt="image.png" />

**Comment by Aman-Hundal** [comment]
Ministry view is currently being worked on and will get that done soon!. Will adjust labels as well.

In terms of the OIPC No and Order No ->Just want to confirm that validation for these two numbers is required from business/Lise/Jackie? It was not mentioned in the original AC's.

**Comment by KyEggleston** [comment]
@nimya-aot @Aman-Hundal - Added Scenario 39 to account for when a request is closed, and a user updates the 'Outcome' field, the following modal should appear. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/617d1179-c86a-46bc-b54d-3f5c6ba2042a)

Afterwards, Scenario 33 and 34 would still apply.

**Comment by KyEggleston** [comment]
@Aman-Hundal - disregard previous message which I deleted related to Nimya's question above. 

Regarding OIPC No. and Order No. format validation. I think these can just be VARCHAR with no formatting restrictions (just to acknowledge that these could be different among themselves, or the OIPC may change their numbering standards). Not sure we need to be too restrictive over length or format. @liseandtea thoughts?

**Comment by KyEggleston** [comment]
> @nimya-aot Ministry view is currently being worked on and will get that done soon (ticket 4776). Labelling will be adjusted based on ticket information.
> 
> Also for the modal Nimya mentioned, I talked to Jackie and the Modal in her designs (even though different from the code) serves the same purpose as the modal that pops up when an outcome is selected (scenario 32). So the modal is not needed as its already created.
> 
> In terms of the OIPC No and Order No ->Just want to confirm that format validation for these two numbers is required from business @m-prodan @liseandtea It was not mentioned in the original AC's (besides these fields just being mandatory/not empty)
> 
> Also in terms of recieved date in the refinement notes -> I talked to Divya, the notes were just referring to the Received Date Field (which is currently available in the current code. This did not exist at the time of the dicsussion)
> 
> Let me know if there are any other questions.

@Aman-Hundal - see Lise reply above:

"The format for "OIPC No" and "Order No" is F23-00000. There will always be the capital "F" followed by the last 2 digits of the year, dash, then the number the order is in their sequencing. The number sequence is dependent on the amount received/orders created, e.g. F23-01 vs F23-123. Note that "OIPC No" tends to have 5 numbers in the sequence F23-12345."

**Comment by JHarrietha-AOT** [comment]
@Aman-Hundal @sumathi-thirumani-aot Things things I noticed in doing UX Assurance,

1. Outline on OIPC Flag at the top of the page should be outlined in orange not red like it is now
2. OIPC Flag should be moved up in line with the watcher and to the left to be slightly closer
3. When a user clicks "Add Additional OIPC" they are automatically moved up the screen to a place that doesn't make sense (They're should be no auto-scrolling it should stay where they are so they can input the data in the newly added files. There is also a "Please Fill out this field" tooltip that doesn't tie to any section. I have included a screenshot of where it auto scrolls to and the tooltip not being attached to any field.

<img width="1323" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekpCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b590759c9abf806afc9d9cdd6dc80101c766398/Screenshot%202023-12-07%20at%202.19.10%20PM.png" alt="Screenshot 2023-12-07 at 2.19.10 PM.png" />

**Comment by JHarrietha-AOT** [comment]
@milosdes I am in test-rook not dev. In test it is happening in 0000001, 11141026. But is not happening in 09521205 and 11501205. I am in chrome. Is it not happening in any request in dev?

**Comment by nimya-aot** [comment]
working as expected, so closing

**Comment by milosdes** [comment]
@JHarrietha-AOT I don't think you had a chance to go over points 1,2 and 3 from your last comment. This ticket has already been through QA, so if the UX is good it can go straight back to closed.

**Comment by JHarrietha-AOT** [comment]
@milosdes thanks for flagging this. Two things

There should be padding between Watcher and OIPC Flag at the top of the page.
And there are still requests where I am getting auto-scrolled up when I add an additional OIPC, has this been looked into and fixed?

**Comment by JHarrietha-AOT** [comment]
@milosdes just chatting with @Aman-Hundal he said the two issues I listed above are something he has fixed and will be pushing to test shortly. So no need to action this and moving this to closed
