### ISSUE TITLE
Request Queue Updates - Flags and Search (OIPC, Restricted)

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4677]
* As any user of FOI Mod
* I want to know when a request is flagged as an OIPC review or other flagged request type
* so that I can tell from a glance the urgency of my requests

**Assumptions & Scope**	
This story represents request queue updates that will be needed to support OIPC review flags, as well as some search features to help users easily filter to request types.

What is IN scope?
Update to request column flag location (to left side of queue)
Flags appearing when a file is restricted, or has OIPC reviews associated with it
All queues will be updated to include this - Ministry, Intake, Processing Team, Scanning Team

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Queue Column Updates - Dashboard**
* GIVEN a user is in the FOI Mod app
* WHEN they return to their queue
* THEN the first column from the left will contain the request flags (see design)

**Scenario 2: Queue Column Updates - Advanced Search**
* GIVEN a user is in the FOI Mod app
* WHEN they go to the advanced search
* AND complete a search
* THEN the first column from the left will contain the request flags (see design)

**Scenario 3: OIPC Review/Complaint**
* GIVEN a user is in their dashboard of the FOI Mod app
* WHEN a request has an OIPC complaint or review is saved to the file
* THEN the OIPC review flag will appear in the flag column (see design)

**Scenario 4: OIPC Review/Complaint Deleted/Not Present**
* GIVEN a user is in their dashboard of the FOI Mod app
* WHEN the request has no OIPC review or complaint associated with it
* THEN the OIPC review flag will NOT appear in the flag column

**Scenario 5: Restricted Request**
* GIVEN a user is in their dashboard of the FOI Mod app
* WHEN a request has been flagged as a restricted request for that team
* THEN the Restricted flag will appear in the flag column (see design)

**Scenario 6: Restricted and OIPC Review Request**
* GIVEN a user is in their dashboard of the FOI Mod app
* WHEN a request has been flagged as a restricted request for that team
* AND it has an OIPC Review or Complaint with it
* THEN the Restricted flag AND the OIPC flag will appear in the flag column (see design)

**Scenario 7: Hover over OIPC flag - description**
* GIVEN a user is in their dashboard of the FOI Mod app
* WHEN a user hovers over an OIPC flag on a request
* THEN a text bubble will appear with the following text: "OIPC"

**Scenario 8: Hover over restricted flag - description**
* GIVEN a user is in their dashboard of the FOI Mod app
* WHEN a user hovers over an OIPC flag on a request
* THEN a text bubble will appear, with the following text: "Restricted"

**Scenario 9: Queue Search - OIPC**
* GIVEN a user is on the request dashboard
* WHEN they enter "OIPC" in the search field
* THEN the queue will filter to only show requests with the OIPC flag

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
#4671 - Create Complaint Flag

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975255940

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Queue updates based on Jackie's designs. @JHarrietha-AOT - can you link the designs in this one? I didn't change too much, but I added a hover over... thoughts on that?

cc @liseandtea @lmullane @KyEggleston

**Comment by KyEggleston** [comment]
Clarified/updated Scenario 7

**Comment by divyav-aot** [comment]
Hover over popup design is needed. - **Only the flag name (Restricted, OIPC)**

**flag column should not have any sort** 

do we have any search filter for advance search? - **yes. But separate ticket will be created.**

**Comment by lmullane** [comment]
@m-prodan, will we have a separate story for searching OIPC Reviews in Advanced Search?

Possibly that may be a check box.

cc @JHarrietha-AOT @liseandtea @KyEggleston

**Comment by liseandtea** [comment]
@lmullane @m-prodan @KyEggleston @JHarrietha-AOT I think that is one of the AC and design updates needed that came out of refinement yesterday.

**Comment by nimya-aot** [comment]
working as expected so closing
