### ISSUE TITLE
OIPC - Create Complaint/Review Flag on Closed Requests

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4679]
* As an IAO user
* I want closed requests that receive OIPC reviews to re-appear in my queue
* so that I know I have to take action on them

**Assumptions & Scope**	
This is related to #4671 - but the functionality is slightly different so I am capturing it on a separate user story.

A closed request can receive a request for review by the OIPC - this is often in the case where a request has been closed due to fees and the applicant complains about the fee, when an applicant challenges the severing decision, or they challenge the adequacy of search. These will not be the only reasons this could happen - this is just the most common. 

When a closed request receives an OIPC review, the request should technically "re-open" - but it must not continue to count processing days, or count as an overdue request due to passage of time (unless it was originally closed past the LDD) 

What is IN scope?
Creating an OIPC Complaint on a closed request

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Create OIPC Review**
* GIVEN an IAO user is in the request details view of a closed general or personal request
* WHEN they click on the Review Flag button
* THEN a a drop down will show OIPC Review and No Review
* AND No review will be inactive

**Scenario 2: Create OIPC Review - Continue**
* GIVEN an IAO user is on the create OIPC review modal
* WHEN they click continue
* THEN the modal will close
* AND they will be brought to the OIPC tracking section on the request view

**Scenario 3: Create OIPC Review - Cancel**
* GIVEN an IAO user is on the create OIPC review modal
* WHEN they click cancel
* THEN the modal will close
* AND they will be returned to the request details page

**Scenario 4: Save button inactive**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN all of the mandatory fields do not have values in them
* THEN the save button will be disabled

**Scenario 5: Save button active**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN all of the mandatory fields have valued in them
* THEN the save button will be enabled

**Scenario 6: Save button activate**
* GIVEN an IAO user is at the OIPC tracking details section
* AND the save button is active
* WHEN the user clicks save
* THEN the OIPC details will be saved
* AND the request will re-appear on the users and Ministry's queue with the OIPC Flag active

**Scenario 7: Add Additional Review/Complaint**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN they click on the + symbol
* THEN an additional OIPC detail section will appear
* AND the save button will become inactive

**Scenario 8: Remove Review/Complaint**
* GIVEN an IAO user is at the OIPC tracking details section
* WHEN they click on the trash can symbol of a saved OIPC complaint or review
* THEN a modal will appear with the text "Are you sure you want to delete this OIPC Review?"
* AND the options will be continue or cancel

**Scenario 9: Remove Review/Complaint - Continue**
* GIVEN an IAO user is on the modal for removing an OIPC Review
* WHEN they click on the continue button
* THEN the modal will close
* AND the OIPC review details will be removed

**Scenario 10: Remove Review/Complaint - Cancel**
* GIVEN an IAO user is on the modal for removing an OIPC Review
* WHEN they click on the cancel button
* THEN the modal will close
* AND the OIPC review details will remain

**Scenario 11: Remove Review/Complaint - Last OIPC Review**
* GIVEN an IAO user is on the modal for removing an OIPC Review of a closed request
* AND it is the ONLY OIPC review complaint
* WHEN they click on the continue button
* THEN the modal will close
* AND the OIPC review details will be removed
* AND the OIPC review details section will disappear
* AND the request will no longer show in the active queue of the processing team and Ministry

**Scenario 12: Processing Days No Longer Count**
* GIVEN an IAO user has activated an OIPC review on a closed request
* WHEN additional business day(s) has passed
* THEN the system will no longer count those days against the legislated due date
* OR record them as days active/processing
* AND the days remaining will no longer appear on the left nav tab

**Scenario 13: Request State Update When OIPC Review Active**
* GIVEN an IAO user has flagged a closed request for OIPC Review
* WHEN they complete the action to flag the request
* THEN the request state will remain closed
* AND the request will appear in their queue
* AND the option to move the request into "Records Review" will become active

**Scenario 14: Closed Request and OIPC Review(s) - Retain OIPC Review Flag**
* GIVEN a request is in a request state of 'Closed' 
* WHEN all OIPC Review(s) on the request have the 'Outcome' field populated (i.e., the OIPC Reviews are complete/closed)
* THEN the request will no longer appear on the 'My Requests' or 'My Team's Requests' queues
* AND the OIPC Review page flag will be retained on the request

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/987195649

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Sibling story to #4671 - avoiding all of the AC's from that one, it should follow the same logic, I just structured it more around a closed request.

cc @JHarrietha-AOT @liseandtea @lmullane @KyEggleston

**Comment by divyav-aot** [comment]
re-open always to records review? if yes, what happens if the request closed at open of CFR state? - **The state stays as closed and flag to OIPC review. But, the request should show in the dashboard if OIPC review is active and at lease one of the complaint's outcome is not set. IAO should be able to re-open the request to any state listed and the clock should stop calculating.**

do we need a separate state for OIPC review? - **No need.** 

can we close a request if OIPC review pending? if yes, how does it work when we re-open the request? - **Yes. It works same as normal open OIPC requests except the clock will be stopped.** 

if OIPC complaint has been marked as complete, should we still mark the flag as yes or no? - **No. Keep the flag On. Just add the new complaint using “Add” button**

if a request closed with OIPC review complete, again re-opened with another OIPC, then how the flag should behave? - **It should be ON.**

Also, should we need to show all the history of OIPC? - **Yes** 

Should we allow them to delete historical OIPC complaints ?- **yes**

if an OIPC complaint is complete and IAO starts working on the request, then should we restart the LDD calculations or the days count? - **No need**

Processing Days No Longer Count - should we stop showing the days count in the left panel if it is re-opened for OIPC - **yes remove it**

**Comment by sumathi-thirumani-aot** [comment]
@m-prodan @KyEggleston @liseandtea @JHarrietha-AOT

**Comment by Aman-Hundal** [comment]
Follow up on above notes by Sumathi:

1. The second option is preferred **(Do you want the OIPC dropdown to be always available for selection to be made before state change action.
In this case; the clock will never show from the moment of state change.)**
2. Logic of Closed/Reopened states and OIPC =  A. State is closed + isoipcreivew = In the request details FrontEnd component -> Right hand side request details are all disabled EXCEPT for Assignees and assignment of the request + OIPC Flag and OIPCDetails are enabled. Left Hand side request details have no dates and timers active/showing and no date and reminders are sent to users.  B. State is reopened + isoipcreview= Left Hand side request details have no dates and timers active/showing and no date and reminders are sent to users. 
3. OIPC Flag should always be accessible in all states from "Open" onward.

**Comment by milosdes** [comment]
@JHarrietha-AOT I think in our discussion last week you mentioned that creating OIPC reviews will not trigger any automated state changes. Just wanted to confirm that scenario 13 (updating to Records Review when creating OIPC review flag) is not necessary for this ticket anymore in this case.
Also for scenario 2 and 3, currently we aren't displaying a modal upon selecting 'OIPC review', instead this displays and navigates to the 'OIPC details' section. Then they will need to click the 'save' button of the request to save the details, and a modal will appear for that.
However for scenario 8/9/10/11 (removing OIPC details) we do display a modal asking for confirmation. This might give the impression that the change is being saved , but they still actually need to click the 'save' button for the request for the change to be saved. 
This might not make sense until you actually go through the app, but let me know if you want to connect about this.

**Comment by nimya-aot** [comment]
currently the request is duplicaing on "My Requests" queue. Could anyone please check that? @Aman-Hundal @milosdes 
<img width="1608" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmhIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--546ed6af9b186d2b0b03f5eb2bf277dade78fe87/image.png" alt="image.png" />

**Comment by Aman-Hundal** [comment]
@nimya-aot Taking a look !

**Comment by nimya-aot** [comment]
Also my request is not showing up on "My requests".  @Aman-Hundal 
<img width="1677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFpIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4455fe8d34c555c3308b3be4eb9d6def1fd49285/image.png" alt="image.png" />

<img width="1555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHBIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06c4074f73f432089c876f9b7debee45c9807e16/image.png" alt="image.png" />

**Comment by nimya-aot** [comment]
@Aman-Hundal scenario 13 is failing. When a closed request receives "OIPC complaint" state change to "Records Review" is not happening automatically.
Also I am unable to create OIPC complaint for closed request EDU-2023-15281211

<img width="1678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDFPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f9a0a394bce4da0fdcf3aec51bd5c8e51dd9c2c/image.png" alt="image.png" />

**Comment by nimya-aot** [comment]
@milosdes  When I create a OIPC complaint on closed request, Its not automatically go back to "Records Review" state. Could you please check?

**Comment by nimya-aot** [comment]
@JHarrietha-AOT  Could you please reply to @milosdes question below?
<<
@JHarrietha-AOT I think in our discussion last week you mentioned that creating OIPC reviews will not trigger any automated state changes. Just wanted to confirm that scenario 13 (updating to Records Review when creating OIPC review flag) is not necessary for this ticket anymore in this case.
Also for scenario 2 and 3, currently we aren't displaying a modal upon selecting 'OIPC review', instead this displays and navigates to the 'OIPC details' section. Then they will need to click the 'save' button of the request to save the details, and a modal will appear for that.
However for scenario 8/9/10/11 (removing OIPC details) we do display a modal asking for confirmation. This might give the impression that the change is being saved , but they still actually need to click the 'save' button for the request for the change to be saved. 
This might not make sense until you actually go through the app, but let me know if you want to connect about this.
>>

**Comment by JHarrietha-AOT** [comment]
@nimya-aot @milosdes I am confirming the question about automatically changing states with Lise. I will add comment when I hear back from her - I want to confirm my thinking with her.

As for the second question about the modules and saving, I remember discussing it earlier with either @milosdes or @Aman-Hundal I believe. And it doesn't make sense for a user to need to hit save again in the Request Details. Can we make it so that when they hit save in the module it does the save and reloads the page when the button is clicked and closed? They should not need to click save twice and it will lead to errors and people not knowing they need to save in two places.

**Comment by JHarrietha-AOT** [comment]
@nimya-aot @milosdes @Aman-Hundal I have confirmed with @liseandtea any request that is flagged as OIPC should not be automatically moved to any request state. It should stay in the state it is currently in (including closed) to allow for the analysts to move states when it is time to do so - which wouldn't be when they are flagging the file. 

@liseandtea will update the AC by EOD today.

Reach out if there are any further clarifications needed.

**Comment by Aman-Hundal** [comment]
Above are completed. Will be pushed to test-rook soon! Thanks

**Comment by nimya-aot** [comment]
@Aman-Hundal scenario 6 is failing. When an OIPC complaint flag is created on a closed request it is not appearing on ministry's queue. Could you please check?
<img width="1556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFp0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af89958cf8163c751c97e1c6878d5841494c364f/image.png" alt="image.png" />

**Comment by milosdes** [comment]
Good catch @nimya-aot. Took a while to find the issue - there was a ministry filter on the backend that was also filtering out any inactive requests. It should be working in dev-rook now, we will try and get the changes to test-rook tomorrow.

**Comment by nimya-aot** [comment]
@KyEggleston If OIPC outcome is closed/decided on a closed request, then do we need to appear those requests still  on "My Requests" queue?

**Comment by nimya-aot** [comment]
@Aman-Hundal If there is only one OIPC complaint on a closed request, then after removing the complaint, "save " button is disabled. So unable to test scenario 11. could you please check?
<img width="1558" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWFHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--574fbfaa142cf50cec65a3cb0c403e0683351962/image.png" alt="image.png" />

**Comment by KyEggleston** [comment]
> f OIPC outcome is closed/decided on a closed request, then do we need to appear those requests still on "My Requests" queue?

If the 'Outcome' field of an OIPC review is populated, the OIPC review is considered complete/closed. If a request is in the 'Closed' status, and all OIPC reviews on the request have the 'Outcome' field populated, the request should no longer appear on the 'My Requests' or 'My Team's Requests' queues.

**Comment by KyEggleston** [comment]
From standup - the OIPC flag should be retained on the request as long as there is =>1 OIPC review on the request. If the request is closed, and the OIPC review(s) have the 'Outcome' field populated, the request will disappear from the queues (as per above comment), but the OIPC Review flag will be retained. 

If you delete all OIPC Reviews from the request, the OIPC Review flag will be removed.

**Comment by KyEggleston** [comment]
Added scenario 14 -  When all OIPC Review(s) are complete/closed, and the request is in a 'Closed' status, the requests will no longer show up on a user's queue.

**Comment by m-prodan** [comment]
This has passed all AC criteria - I did notice that when I adjusted the request state, the clock started counting on the queue level. This wasn't explicitly addressed in the AC, so I will need to handle it with a new user story.
