### ISSUE TITLE
Unable to save Redline pdf if only page exists after duplicate removal

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4681]
**Describe the bug in current situation**
When an IAO user flagged all the pages with duplicate flag except one page, then Redline pdf is not generating. It shows loading state

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Request MSD-2023-10061031 on Test-marshal
**Steps to Reproduce**
1. Go to redaction app
2. Set all the pages flag as 'Duplicate except one flag
3. Redline pdf is not generating

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUdOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3e607a4630a5aa23286bb121d9c45c6bafde890/image.png)

**Comment by sumathi-thirumani-aot** [comment]
Fixed as part of https://github.com/bcgov/foi-docreviewer/pull/604

**Comment by nimya-aot** [comment]
working as expected, so closing
