### ISSUE TITLE
Pre req for 9.0 release

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#4682]
Title of ticket: 

#### Description
This ticket will list all the manual steps and prerequisites for the 9.0 release

#### Dependencies
Are there any dependencies?

#### DOD
- [x] restart pods job to be updated with zipping service
DocumentPathMapper table s3 secrets update for MSD, GCP and OOP - NOT required
- [x] check the ticket #3434 for manual step on keycloak - mappers (foi_preferred_username, identity_provider)
- [x] web url needs to be added in keycloak
- [x]  Keycloack client updates - mapper- Refer #3434
Notification Manager Env changes - @divyav-aot  to confirm ?? Checked but didnt find any!  - NOT required
- [x] S3 Configuation with new web endpoint on OCP need to be IP Restrcit on N/W policies OCP - Preq. PRD
- [x] S3 Configuation with new web endpoint for header CORs CONFG

**Comment by nkan-aot** [comment]
update forms flow web config map 
- REACT_APP_DISABLE_REDACT_WEBLINK false to true
update zipper all envs
- REDIS_HOST
- REDIS_PASSWORD
- REDIS_PORT
- ZIPPER_STREAM_KEY
- S3_ENV
- DB_HOST
- DB_NAME
- DB_PORT
- DB_USER
- DB_PASSWORD
- S3_HOST
- S3_REGION
- S3_SERVICE
- NOTIFICATION_REDIS_HOST
- NOTIFICATION_REDIS_PASSWORD
- NOTIFICATION_REDIS_PORT
- NOTIFICATION_STREAM_KEY
- FAILUREATTEMPT - 2
update pdf stitch add following envs
- ZIPPER_REDIS_HOST 
- ZIPPER_REDIS_PASSWORD 
- ZIPPER_REDIS_PORT 
- ZIPPER_STREAM_KEY ZIPPERSERVICE
	the following envs need to be moved from env to vault in dev
- NOTIFICATION_REDIS_HOST redis
- NOTIFICATION_REDIS_PASSWORD 
- NOTIFICATION_REDIS_PORT 
- NOTIFICATION_ENABLED True
- MESSAGE_BLOCK_TIME 0
- HEALTH_CHECK_INTERVAL 15

update reviewer api add env
- ZIPPER_REDIS_HOST 
- ZIPPER_REDIS_PASSWORD 
- ZIPPER_REDIS_PORT 
- ZIPPER_STREAM_KEY ZIPPERSERVICE
- PDFTRON_WEBVIEWER_LICENSE
- REDLINE_SINGLE_PKG_MINISTRIES AGR,LDB,PSA,FIN,JED,LBR,MUNI,TACS

**Comment by abin-aot** [comment]
Doc Reviewer Web :
"REACT_APP_PDFVIEWERDISABLED"
"REACT_APP_ANNOTATION_PAGE_SIZE": 500,
    "REACT_APP_PAGE_SELECT_LIMIT": 250,
    "REACT_APP_REDACTION_SELECT_LIMIT": 250

**Comment by sumathi-thirumani-aot** [comment]
redis 
=====
Req Memory = 750Mi
Limit Memory = 1Gi
Req CPU = 1
Limit CPU = 1



reviewer-api 
=====
Req Memory = 500Mi
Limit Memory = 1Gi
Req CPU = 1
Limit CPU = 1


reviewer-conversion
===================
Request CPU = 1
Limit CPU = 3

reviewer-dedupe 
===================
Request CPU = 1


reviewer-pdfstitch-largefiles  
===================
Request CPU = 1
