### ISSUE TITLE
Dependabot issues on foi-flow and foi-docreviewer

### ISSUE THREAD

**Issue by milosdes** [bcgov/foi-flow#4689]
There are currently 3 critical dependabot issues in the foi-flow repo (forms-flow-web), and 4 in the docreviewer repo (mostly in /web). 

**[crypto-js](https://github.com/bcgov/foi-docreviewer/security/dependabot/27) - upgrade to 4.2.0** 

[Cross-realm object access in Webpack 5 ](https://github.com/bcgov/foi-docreviewer/security/dependabot/11)- upgrade webpack to 5.76.1
[babel vulnerability](https://github.com/bcgov/foi-docreviewer/security/dependabot/26) - upgrade to 7.23.2
**Note: the babel alert states "Users that only compile trusted code are not impacted.” - I think we are in this category?** 

[.NET core remote code](https://github.com/bcgov/foi-docreviewer/security/dependabot/12) (docreviewer only)- upgrade to 5.0.3 or higher - **DO NOT DO THIS** - chatted with Nick, and we need to use 5.0.2 or older on Linux, thus the previous downgrade - so no immediate fix for this for now. 

Q: Using npm package.json "overrides" as a way of addressing these.

**Comment by milosdes** [comment]
Upgrading react-scripts from 4.0.3 to 5.0.1 should take care of the cross-realm and babel issues.

In foi-flow/forms-flow-web/src/services/UserService.js, line 22: `const jwt = require("jsonwebtoken");` looks like it is not being used - is it okay to uninstall jsonwebtoken package instead of upgrading it? The package has a dependency jws@3.2.2 that is incompatible with the required upgrade to webpack 5 and would require more work to maintain.

**Comment by abin-aot** [comment]
@abin-aot , need to check with @milosdes , for .NET core blocker

**Comment by nimya-aot** [comment]
working as expected so closing
