### ISSUE TITLE
Closing a request

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#469]
* As an IAO analyst
* I want to be able to Close a request that is any state except 'Unopened' 
* so that I can remove assignments from a request that no longer needs to be actioned

**Assumptions & Scope**	
What are the assumptions for this story?

Closing will work the same way on any request state

A request can be closed in any state, except Unopened and Publish, as per our workflow:
https://miro.com/app/board/o9J_l9AKkos=/

Closing a request can only be accomplished by a IAO analyst

**A Ministry coordinator cannot close a FOI Request**

What is in and not in scope?

**Not in Scope**
Notifications a request has been closed
Number of pages released, Number of pages reviewed, Fee Waiver and Total Fee Remaining not included in MVP

**Acceptance Criteria**	

**Scenario 1: Dropdown to close a request**
* GIVEN an IAO Analyst is on the request view of a request in any state except Unopened or Publish
* WHEN ... I click the left side dropdown menu
* THEN the Closed state will be an option

**Scenario 2: Analyst Selected Closed State**
* GIVEN the IAO Analyst has clicked on the dropdown menu for a request in any state except Unopened or Publish
* WHEN ... I select "Closed" from the dropdown menu
* THEN a modal will open up showing the "Close Request" window, showing the following information: Applicant Name, Organization, Fee Waiver, Total Fee Remaining, Start Date of Request, Closing Date of Request. Reason for Closing Request, Number of Pages Released, Number of Pages Reviewed, and a Save and Cancel button.
* AND Start date, applicant name, organization, fee waiver, total fee remaining will be auto-filled (if no data, display N/A), and the closed date will default to today's date.
* AND the save function will not be active
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/813713058

**Scenario 3 Cancel Back to Prior State:** 
* GIVEN the IAO Analyst has opened the close request modal
* WHEN I click the cancel button
* THEN the modal will close, and that state of the request will remain as it was before selecting the close state

**Scenario 4: Calendar picker for Closing date:**
* GIVEN the IAO Analyst has opened the close request modal
* WHEN the Closing Date calendar picker has been selected 
* THEN a calendar picker will appear to select a date
* AND when a date is selected, it will appear as the value for the close date

**Scenario 5: Closing Date Cannot be in the Future**
* GIVEN the IAO Analyst has opened the close request modal, 
* WHEN they have activated the calendar picker for Close Date
* THEN the analyst will be unavailable to pick a date in the future

**Scenario 6: Reason for Closing Request**
* Given the IAO analyst has opened the close request modal
* WHEN the "Reason for Close" drop down is selected
* THEN the following options will be available to select: Abandoned, Access Denied, Application Fee - Abandoned, Full Disclosure, No Resp. Records Exist/Located, Outside Scope of Act, Partial Disclosure, Records in Another Min/Org, Refuse to Confirm or Deny, Routinely Releasable, Section 43, Transferred, Withdrawn
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/813713059

**Scenario 7: Reason for Closing Request**
* Given the IAO analyst has opened the close request modal
* WHEN the "reason for close" drop down is selected
* AND an option is selected
* THEN the option will be displayed in the field
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/813713060

**Scenario 8: Save Change button becomes Active**
* GIVEN the IAO Analyst has opened the close request modal
* WHEN the mandatory fields have any value filled in: Closing date, Reason for Closing Request, Number of Pages Release, and Number of pages reviewed
* THEN the Save Change button will become active
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/813713060

**Scenario 9: Clicking Save Change button**
* GIVEN the IAO Analyst has opened the close request modal
* WHEN all mandatory fields are filled in
* AND the save change button is clicked
* THEN the modal will close
* AND state of the request will be update to "Closed"
* AND colour of the left navigation tab will turn to black
* AND the request will be removed from all assigned queues
* AND the request details will be Read Only

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
We need to include the "Final Disposition" when closing a request. This is an important field that is reported out on, I can pull the list from AXIS. A dropdown would be fine, you would only ever select one reason.

**Comment by lmullane** [comment]
@JHarrietha-AOT, I will update the scenarios to reflect @arielleandrews comment above. And move this story down until we have updated designs. 

Another update required to the designs is that 'Closed' should be an option for an IAO analyst only for every state except 'Unopened' and or 'Publish'

**Comment by lmullane** [comment]
@JHarrietha-AOT, we should probably have a modal for this requiring them to be sure they want to close the request. Thoughts?

**Comment by JHarrietha-AOT** [comment]
@lmullane agreed there should be a modal. Thinking it would make sense if in the modal they have to select or type the reason for closing the request so there is a record of why. Which could be added as the last comment in the request. @arielleandrews Thoughts? I havn't seen the existing process for closing a request

**Comment by arielleandrews** [comment]
Agree with the modal. @JHarrietha-AOT I can walk you through the close request process in the test environment in AXIS whenever you would like to see this process

**Comment by JHarrietha-AOT** [comment]
@m-prodan thanks, designs added

**Comment by arielleandrews** [comment]
Hey @richard-aot or @abin-aot, can one of you fix the text that displays in the Close modal? Highlighted texts should be 'Applicant' and 'Outside'
![image](https://user-images.githubusercontent.com/82615839/140187735-05bbab32-6691-4a56-bfe0-e2f167f07018.png)

**Comment by richard-aot** [comment]
Good catch @arielleandrews. I'm working on the fix now.

**Comment by arielleandrews** [comment]
Thank you @richard-aot! Re the calendar picker noted in Scenarios 4 and 5: the default the user should not be able to select a date in the future, but should be able to select a date in the past. Right now the user can only select the current date. Having the current date as the default selection is perfect but we will need the ability to backdate. Can this be fixed as well?

**Comment by richard-aot** [comment]
That's a good question, @arielleandrews . For closing date, the range of calendar picker is from the date of the last state change to current date.

I guess that you can only choose current date is because you are testing a request which is created today. If you try to close some existing requests, you will see the difference. Let me know if you have any questions.

**Comment by arielleandrews** [comment]
Thank you for the clarification @richard-aot!

**Comment by richard-aot** [comment]
@arielleandrews, bug fixes for "Applicant" and "Outside Scope of Act" are pushed to test env.

**Comment by arielleandrews** [comment]
QA completed. All scenarios passed in Edge and Chrome. Scenarios 1-8 passed in Firefox, scenario 9 failed. Bug ticket #824 created to document this issue.
