### ISSUE TITLE
Division folder is not showing up on the redline package if it has only incompatible files

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4690]
**Describe the bug in current situation**
If a division has only incompatible files, its not showing up on redline pdf package

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Request EDU-2023-09591102 on Test-marshal

**Steps to Reproduce**
1. Go to records tab
2. Upload records for two divisions, one division only with incompatible files
3. Generate redline pdf package
4. Division with incompatible files are missing on the redline pdf package

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by abin-aot** [comment]
HTH-2023-011111251 - https://dev.foirequests.gov.bc.ca/foi/foirequests/15509/ministryrequest/15532 - Reprodcued on dev. Theere are 4 divisions, and 3 of them as documents, and 1 div has only incompactible files including PPT, JSON which is not part of redline

**Comment by nimya-aot** [comment]
working as expected, so closing
