### ISSUE TITLE
9.0

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#4693]
**Place-in the release name**
Release name & link

#### Activity start time
4:00pm

#### Activity end time
5:14pm

#### Step-1: Database Backup (Check the desired components)
Capture the backup details 
- [x] FOI DB (xxx)
- [x] BPM DB
- [x] Docreviewer DB

#### Step-2: Image Backup (Check the desired components)
Capture the image details 
- [x] request-management-api 
- [x] forms-flow-web
- [x] notification-manager
- [x] reviewer-api

- [x] reviewer-conversion
- [x] reviewer-dedupe
- [x] reviewer-pdfstitch

#### Step-3: Production - Tagging of image (Check the desired components)
- [x] request-management-api 
- [x] forms-flow-web
- [x] notification-manager
- [x] reviewer-api
- [x] reviewer-web
- [x] reviewer-conversion
- [x] reviewer-dedupe
- [x] reviewer-pdfstitch
- [x] reviewer-zipper

#### Step-4: Signoff from business
- [ ] Yes
- [ ] No
- [ ] Not Applicable

#### Step-5: Healthcheck (Check the desired components)
- [x] Completed

#### Step-6: Staging - Tagging of image (Check the desired components)
- [ ] request-management-api
- [ ] forms-flow-web
- [ ] notification-manager
- [ ] reviewer-api
- [ ] reviewer-web
- [ ] reviewer-conversion
- [ ] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

**Observations**
List down the observations of incidents which happened in release window

**Overall Rating**
- [ ] Good (No change)
- [x] OK (With observations)
- [ ] Bad(Rollback)

**Comment by sumathi-thirumani-aot** [comment]
Tagging:
d106d6-tools
==============
1. reviewer-zippingservice
oc tag reviewer-zippingservice:test reviewer-zippingservice:prod
2. reviewer-api
oc tag reviewer-api:test reviewer-api:prod
3. reviewer-web
oc tag reviewer-web:test reviewer-web:prod
4. reviewer-conversion
oc tag reviewer-conversion:test reviewer-conversion:prod
5. reviewer-dedupe
oc tag reviewer-dedupe:test reviewer-dedupe:prod
6. reviewer-pdfstitch
oc tag reviewer-pdfstitch:test reviewer-pdfstitch:prod
d7abee-tools
=============
7.request-management-api
oc tag request-management-api:test request-management-api:prod-002
8. forms-flow-web
oc tag forms-flow-web:test forms-flow-web:prod
9. notification-manager
oc tag notification-manager:test notification-manager:prod


Backup
d106d6-tools
=============
1. reviewer-zippingservice : NA
2. reviewer-api
oc tag reviewer-api:prod reviewer-api:prod-bu
3. reviewer-web : NA
4. reviewer-conversion
oc tag reviewer-conversion:prod reviewer-conversion:prod-bu
5. reviewer-dedupe
oc tag reviewer-dedupe:prod reviewer-dedupe:prod-bu
6. reviewer-pdfstitch
oc tag reviewer-pdfstitch:prod reviewer-pdfstitch:prod-bu
d7abee-tools
===============
7.request-management-api
oc tag request-management-api:prod-002 request-management-api:prod-002-bu
8. forms-flow-web
oc tag forms-flow-web:prod forms-flow-web:prod-bu
9. notification-manager
oc tag notification-manager:prod notification-manager:prod-bu

**Comment by sumathi-thirumani-aot** [comment]
C:\sumi\softwares\oc>oc project
Using project "d106d6-tools" on server "https://api.silver.devops.gov.bc.ca:6443".

C:\sumi\softwares\oc>oc tag reviewer-api:prod reviewer-api:prod-bu
Tag reviewer-api:prod-bu set to reviewer-api@sha256:fe62fb2549e8d5ad32b5ec886933a6eaca518755ea6d628c525e60a0abd8a6c4.

C:\sumi\softwares\oc>oc tag reviewer-conversion:prod reviewer-conversion:prod-bu
Tag reviewer-conversion:prod-bu set to reviewer-conversion@sha256:b7abdad910c432edb9250f84b0b61db48ac3eb62cc99d57d1a254271ff480274.

C:\sumi\softwares\oc>oc tag reviewer-dedupe:prod reviewer-dedupe:prod-bu
Tag reviewer-dedupe:prod-bu set to reviewer-dedupe@sha256:7ec06465dda38e0b1922970ca189af971dc8cdf5edc356847f6183594d81fe2d.

C:\sumi\softwares\oc>oc tag reviewer-pdfstitch:prod reviewer-pdfstitch:prod-bu
Tag reviewer-pdfstitch:prod-bu set to reviewer-pdfstitch@sha256:3d4831e2bf70dac079f40b72ab4df2aa3be38200a55fa7a760d8c7552c7efc6c.

**Comment by sumathi-thirumani-aot** [comment]
C:\sumi\softwares\oc>oc project d7abee-tools
Now using project "d7abee-tools" on server "https://api.silver.devops.gov.bc.ca:6443".

C:\sumi\softwares\oc>oc tag request-management-api:prod-002 request-management-api:prod-002-bu
Tag request-management-api:prod-002-bu set to request-management-api@sha256:0d87deed90ee209f1138e5e7e8916c6f1fa5d743c3ef644bc063e8aa6e6fef35.

C:\sumi\softwares\oc>oc tag forms-flow-web:prod forms-flow-web:prod-bu
Tag forms-flow-web:prod-bu set to forms-flow-web@sha256:8d635987507a858190a19110a9829d6d322089fc013eb33689a0ac90fffa6e8d.

C:\sumi\softwares\oc>oc tag notification-manager:prod notification-manager:prod-bu
Tag notification-manager:prod-bu set to notification-manager@sha256:ced921aacd4dae55dbd993ed9d4f9dbb867dbf011f7db6534e85ae059bf05980.

**Comment by sumathi-thirumani-aot** [comment]
Observation: Environment variable "DIVISION_PDF_STITCH_SERVICE_KEY" from notification-manager to be removed in both code and configmap.

**Comment by sumathi-thirumani-aot** [comment]
redis 
=====
Req Memory = 750Mi
Limit Memory = 1Gi
Req CPU = 1
Limit CPU = 1



reviewer-api 
=====
Req Memory = 500Mi
Limit Memory = 1Gi
Req CPU = 1
Limit CPU = 1


reviewer-conversion
===================
Request CPU = 1
Limit CPU = 3

reviewer-dedupe 
===================
Request CPU = 1


reviewer-pdfstitch-largefiles  
===================
Request CPU = 1

**Comment by sumathi-thirumani-aot** [comment]
./backup.sh -1

**Comment by divyav-aot** [comment]
Back up of foi-flow DB.
/backups/daily/2023-11-08/patroni-master-002-ffa-camunda_2023-11-08_16-05-07.sql.gz
 /backups/daily/2023-11-08/patroni-master-002-foidb_2023-11-08_16-04-58.sql.gz

**Comment by sumathi-thirumani-aot** [comment]
New Tech Debt created -> https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4706

**Comment by abin-aot** [comment]
Issue with Syncfusion found with license - ticket raised, https://support.syncfusion.com/support/tickets/520740
