### ISSUE TITLE
Issue with saving redline when there are duplicate files

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#4698]
When saving redline and there are duplicate files, in the generated redline package, divisions/sections contains the duplicated file will have the same redline pdf file. That means one division is receiving a redline pdf which belongs to another division.

You can found the issue in this request MCF-2023-101201 (test env): 
https://test.foirequests.gov.bc.ca/foi/foirequests/1372/ministryrequest/1599
https://test-reviewer-web.apps.silver.devops.gov.bc.ca/foi/1599

**Comment by nimya-aot** [comment]
working as expected, so closing
