### ISSUE TITLE
Request form optimization

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#470]
Title of ticket: 

#### Description
As part of #386 the Status change on request form need to validate(open status onwards) the form as state and if no errors. Earlier there was a performance issue on input fields of the form. Technically, the React component should have the proper object propagation comparing the performance of the form input fields

Update : Clubbing it with User Story #484 , #453

#### Dependencies
Are there any dependencies? 

#### DOD
- [x] Validation should work as per the related user stories - conditional and regular
- [x]  Tab(tabindex), Mouse click and change of input fields should be captured and ready for validation
- [ ] 
- [ ]

**Comment by abin-aot** [comment]
Technically, we have to recreate Tabpanel with Custom JS based logic from our earlier Material UI design. Moved TabControl inside FOIRequest React Component
