### ISSUE TITLE
LDD Miscalculated After Fee Estimate Paid - Sent in Email

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4702]
**Describe the bug in current situation**

Occasionally, after fee estimates are paid online by an applicant, an incorrect LDD is calculated in FOI Mod and sent to the applicant in the 'fee estimate paid' email. When this has occurred, it has been where there is a revised fee estimate (i.e., >=2 CFR Forms in FOI Mod). This is leading to analysts needing to contact the applicant about in incorrect LDD, and providing them the correct LDD from AXIS. The analyst then syncs the request with AXIS to correct the LDD in FOI Mod. 

Possibly happens on requests that have also been 'On Hold' several days, or over a weekend. Test this case as well when trying to replicate.

If the applicant pays the fee estimate online, the analyst cannot preview the LDD sent to the applicant before it is sent. (as it's an automated email) Therefore, the analyst can't catch this before it is sent to remedy it, leading to them needing to contact the applicant. 

This occurred on HTH-2023-32396, MSD-2023-32438 and FIN-2023-32319 in PROD. The applicant was sent an incorrect LDD in their 'fee estimate paid' email, which is automatically sent after the applicant paid online. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

Medium

**Chance of Occurring (high/medium/low/very low)**

Medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

PROD

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
@m-prodan @liseandtea @lmullane - need to reproduce in TEST

**Comment by m-prodan** [comment]
Difficult to reproduce in test so far, assumption is request needs to be on hold for a certain number of days - and probably needs to crossover at least a weekend. The three requests above don't have a lot in common - the HLTH request had 33 on hold days in total, MSD had 25 hold days in total, and FIN had 15 hold days in total.

The hold days for FIN did not cross any stat holidays, but they did for the HLTH and MSD so not technically being trigger by an on hold occuring over a long weekend either. The revised fee estimate was sent after a minimum of 15 days on hold (15 for FIN, 21 MSD, 32 for HLTH)

**Comment by nimya-aot** [comment]
it is working as expected, so closing it
