### ISSUE TITLE
Replacement of attachments on MSG file causing error/ functional issue with redline download

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#4704]
**Describe the bug in current situation**

There are multiple issues(check #4705 as well) when there is a replacement to an attachment file on ,MSG file. This scenario is with the REDLINE download after a replacement happened on attachment document which has `any page flags` applied on it, even `in progress` or `left off here`. 

Issue part#1 ) The issue is like after replacing an attachment under a .msg file which has page flag already applied, the `Redline for Sign off` is disabled and/or download wont work! - Refer screen shot1 below

Issue Part#2) Mark all the attachment with proper flags like, `full disclosure` or else and make the progress to 100%, which in turn enable - `Redline Download`. Now go and replace any of the attachment ! But we will see the progress still with 100% and make download enabled, even work is yet to complete

**Link bug to the User Story**

**Impact of this bug**
Unable to process further on the request

**Chance of Occurring (high/medium/low/very low)** Medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
Steps to reproduce the behavior Issue #1:
1. Create a FOI request , and upload any .MSG file with multiple attachments on it. and move to the `RECORD Review` state
2. Navigate to  Document reviewer app, and apply page flags on the attachment. I would suggest, mark the attachment to replace with "Left Off here" flag - this is just to mimic real world scenario
3. Now replace that particular file and / or technically any file of our choice with flag with another document. 
4. Apply the flag to the new replaced document
5. Even though, it shows 100% complete, Download option is disabled.

Steps to reproduce the behavior Issue #2:
1. Create a FOI request , and upload any .MSG file with multiple attachments on it. and move to the `RECORD Review` state
2. Navigate to  Document reviewer app, and apply page flags on the attachment, and make the work completion to 100% and see the enabled Redline Download
3. Now replace that particular file and / or technically any file of our choice with flag with another document. 
4. You can see even without any page flags, its still showing 100% and can  see Download enabled

**Actual/ observed behaviour/ results**

**Expected behaviour**
Download option should be enabled , if all success conditions are met

**Screenshots/ Visual Reference/ Source**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekc1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0bb8880a3b549735a4edf663264a58a28a29615/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenE1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b95a138de65e51d3426d0029d8c01de625776e77/image.png)

**Comment by nimya-aot** [comment]
working as expected so closing
