### ISSUE TITLE
Replacement of attachments for .msg files removes annotations/redactions for all attachments for .msg file

### ISSUE THREAD

**Issue by Aman-Hundal** [bcgov/foi-flow#4705]
**Describe the bug in current situation**
In the Docreviewer App, when a page flag (and/or redaction) is applied to an attachment of a .msg file, and then the attachment is subsequently REPLACED in the records tab in foi flow -> the annotations and page flag for the attachment is removed (this is good/working as intended) but the annotations for all other attachments associated with the .msg file are remov0de as well (page flag is retained though). This will require the user to reapply all the annotations again for files they did not want to replace, and additionally cause an error with % of completion/redline package creation (see Abin's related bug ticket in the Dependencies tab)

**Link bug to the User Story**
https://dev.foirequests.gov.bc.ca/foi/foirequests/15724/ministryrequest/15747

**Impact of this bug**
High

**Chance of Occurring (high/medium/low/very low)**
Medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
dev, test and all marshalls

**Steps to Reproduce**
1. Go to a foi request (or my linked request) and add a .msg file with multiple attachments. Then select redact record and apply page flags + annotations to all the attachments associated with the .msg.
2. Go to the records tab in the foi flow app and replace one of the attachments with a new file. 
3. Go back to the documentreviewer app and notice that all page flags and annotations are removed for the replaced attachment (this is good) but also notice that all of the annotations are removed for the other .msg attachments (and that the page flags are still retained). This is an error/bug.

**Actual/ observed behaviour/ results**
For a .msg file, when one attachment is replaced, the replaced attachments annotations and page flags are removed as well as all the other attachments annotations (page flags are retained though)

**Expected behaviour**
For a .msg file, when one attachment is replaced, the replaced attachments annotations and page flags are removed and all other attachments associated with the .msg file should retain its annotations and page flags.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nimya-aot** [comment]
working as expected so closing
