### ISSUE TITLE
Response status is missing in OnHold State list

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#4721]
**Describe the bug in current situation**
If the request has gone through response and then on hold. There should be an option to IAO to change the state back to response. Currently only CFR and Closed is listed when you are on OnHold state.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to foi-flow request
2. Traverse through Response and then OnHold state
3. Check the status dropdown

**Actual/ observed behaviour/ results**
The dropdown shows CFR and Closed

**Expected behaviour**
The dropdown should show Response and Closed

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
Don't forget to add an estimate to this when you push the fix to test @divyav-aot

**Comment by nimya-aot** [comment]
working as expected, so closing it
