### ISSUE TITLE
Replace Attachment Not Working

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4762]
**Describe the bug in current situation**
When trying to replace and attachment in PROD (using 'Replace Attachment'), error is thrown (and you subsequently can't replace the attachment). This doesn't appear to be occurring in TEST? This appear to occur on all requests in PROD. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1A1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c7cf26e6e0b2582e02f0555453f0f07305f829d/image.png)

PSA-2023-33480 is example. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
PROD

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nimya-aot** [comment]
working as expected, so closing
