### ISSUE TITLE
OIPC Request Details - Ministry View

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4776]
* As a Ministry Coordinator
* I want to be able to see the details of an OIPC review of a request
* so that I am informed on the status of the review

**Assumptions & Scope**	
This user story is related to #4671/ #4679 - when IAO flags a request as subject to OIPC review, the Ministry user should also have the ability to view the details IAO saves and updates throughout the life. Even when a review is closed, the details should still be present.

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Ministry Request View - No OIPC Review/Complaint**
* GIVEN a Ministry user is on the request view of a request
* AND there is NO OIPC review or complaint attached to it
* WHEN they scroll down through the page
* THEN they will NOT see a section for OIPC

**Scenario 2: Ministry Request View - Active OIPC Review/Complaint**
* GIVEN a Ministry user is on the request view of a request
* AND there is an active OIPC review or complaint attached to it
* WHEN they scroll through the page
* THEN they will see a section for OIPC Request details
* AND the view will be read-only (eg - there will be nothing for them to edit)

**Scenario 3: Ministry Request View - Closed OIPC Review/Complaint**
* GIVEN a Ministry useris on the request view of a request
* AND the OIPC review(s) or complaint(s) attached to it are closed
* WHEN they scroll through the page
* THEN they will see a section for OIPC Request details
* AND the view will be read-only (eg - there will be nothing for them to edit)

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@JHarrietha-AOT  - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
OIPC review details - Ministry view. 

cc @JHarrietha-AOT to post designs.

If there is time to review, please do so @lmullane @KyEggleston @liseandtea

**Comment by JHarrietha-AOT** [comment]
@Aman-Hundal As per our discussion we would like to update the UI so that only fields that are filled out or have been checked as YES will show for Ministry Users. This ensures that Ministry users don't have to sort through the section and only see the fields that are relevant to the request.  I will leave this UX Assurance - feel free to move back if you don't think this will be completed before EOD otherwise just ping when the change is updated in test

**Comment by Aman-Hundal** [comment]
Above fixes are completed, will be pushed to test-rook soon.

**Comment by JHarrietha-AOT** [comment]
@Aman-Hundal Fixes look great! Thanks for making them move onto Ready for QA

**Comment by Aman-Hundal** [comment]
@JHarrietha-AOT Np, thanks for the input Jackie
