### ISSUE TITLE
Advanced Search - OIPC 

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4783]
* As a user
* I want to be able to search for OIPC reviews
* so that I can refer back to them when needed, even when closed

**Assumptions & Scope**	
This is a general update to the advanced search feature to include searching abilities for requests subject to OIPC reviews/complaints

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Advanced Search - OIPC Number**
* GIVEN an IAO user is on the Advanced Search
* WHEN they click on the 'OIPC Number' filter
* THEN the 'OIPC Number' filter will be selected

**Scenario 2: Advanced Search - OIPC Number**
* GIVEN a user is on the Advanced Search 
* AND the 'OIPC Number' filter is selected
* WHEN they enter any text into the search bar
* THEN the 'Apply Search' button will be active

**Scenario 3: Activate Search - Match**
* GIVEN a user has entered an OIPC number in the search field
* AND the 'OIPC Number' filter is selected
* AND there is an OIPC number on a request that matches the search field
* WHEN they click on 'Apply Search'
* THEN any request with matching OIPC numbers will appear in the search results

**Scenario 4: Activate Search - No Match**
* GIVEN a user has entered an OIPC number in the search field
* AND the 'OIPC Number' filter is selected
* AND there is not an OIPC number that matches
* WHEN they click on 'Apply Search'
* THEN the results will return with no requests

**Scenario 5: Advanced Search - OIPC Review**
* GIVEN an IAO user is on the Advanced Search
* WHEN they click on the check box for 'OIPC' under 'Request Flags'
* THEN the OIPC checkbox will be selected
* AND the 'Apply Search' button will be active

**Scenario 6: Advanced Search - OIPC Review**
* GIVEN an IAO user has checked the box for 'OIPC' under 'Request Flags'
* WHEN they click on 'Apply Search'
* THEN any request that has an OIPC Review flag will return as a result, subject to any other search filters

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/987477708

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
OIPC Review - Advanced Search.

CC @JHarrietha-AOT to enter designs. Jackie - please look at scenario 5 and 6 - I am thinking we should add a generic OIPC review check box so TLs and Mgrs can do more high level searching, instead of by a specific OIPC number... thoughts?

**Comment by m-prodan** [comment]
Also tagging @lmullane @liseandtea @KyEggleston for review as time permits :)

**Comment by m-prodan** [comment]
Note - will update AC to be user agnostic - both Min and IAO can do advanced search.

**Comment by m-prodan** [comment]
Note to add scenario confirming restricted requests can only be searched if user is assigned to request.

**Comment by m-prodan** [comment]
Small update to design - separate out from request type - Phased, OIPC and Restricted as they are technically not a request type.

**Comment by nimya-aot** [comment]
@KyEggleston Could you please update the scenario 6  "click on the check box for OIPC review under request type" since OIPC checkbox come under Request Flags, not under Request type.
<img width="1409" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODFVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72400bc9b652eae9f6a1a95c4ca4ad73a010e600/image.png" alt="image.png" />

**Comment by KyEggleston** [comment]
@nimya-aot - Updated Scenario 6, along with clarifying a few others.

**Comment by nimya-aot** [comment]
working as expected, so closing
