### ISSUE TITLE
Image / Email Signature Stalling Initial Loading in Redaction App

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4796]
**Describe the bug in current situation**

An email signature, and it's associated images, is throwing an error in the Redaction App, and thereby stalling the initial load and preventing users from proceeding working in the Redaction App until the file in question/issue is resolved. 

See EDU-2023-1112 in Test as example. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzBiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f81382430e56b1a266ae90b349217f7d96e4e006/image.png)

This can be worked around on some email messages by manually converting it to PDF, and manually replacing it. If the file has attachments, however, this may be more difficult (as we would lose the attachments, and their parent/child relationship). 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

PROD - GCP-2023-32974 (record in question has since been replaced manually with a PDF version, which resolved it). 
TEST - EDU-2023-1112

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
Thanks for documenting this... I wonder if #4339 will resolve this? It seems to have something to do with the margins of the conversion on the attached images from the signature block, or at least that's what my initial look at the GCP file had me thinking.

**Comment by KyEggleston** [comment]
Resolved as part of #4339, confirmed it's working. Closing ticket.
