### ISSUE TITLE
Include GREEN Comments/Annotations in Redline

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4799]
* As an IAO user
* I want certain comments to appear in the redline package
* so that I can ensure the Ministry has context for decisions to sever/not sever

**Assumptions & Scope**	
PDFTron has a feature to select comments, and highlights of certain colours. It is also noted through the comment view panel that there is an ability to filter to just specific annotation types and colours.

Some processing teams have an established practice of including comments on redlines to explain decisions to Ministry reviewers. While we eventually want to be able to have Ministry reviewers access the application directly, that may be too far off to be acceptable given some teams existing practices with their clients.

We'd like to explore the idea of including in the redline, comments and annotations of a certain colour, specifically green, in the redline produced for the Ministry.

What is IN scope?
Updates to the redline to include annotations of the green colour

What is NOT in scope?
NO changes to the response package, or other functions of the creation of the redline.

**Acceptance Criteria**	

**Scenario 1: Create Redline - Green Comments**
* GIVEN an IAO user has 100% completion of the record flags complete
* AND there are green coloured comments throughout the package
* WHEN they create the Redline PDF
* THEN the green comment tags will be included in the redline

**Scenario 2: Create Redline - Other Colour Comments**
* GIVEN an IAO user has 100% completion of the record flags complete
* AND there are  comments throughout the package that are NOT green
* WHEN they create the Redline PDF
* THEN any green comment tags will be included in the redline
* AND any comment tags that are NOT green will NOT be included in the redline

**Scenario 3: Create Redline - Green Highlights**
* GIVEN an IAO user has 100% completion of the record flags complete
* AND there are green coloured highlights throughout the package
* WHEN they create the Redline PDF
* THEN the green highlights will be included in the redline

**Scenario 4: Create Redline - Other Colour Highlights**
* GIVEN an IAO user has 100% completion of the record flags complete
* AND there are highlights throughout the package that are NOT green
* WHEN they create the Redline PDF
* THEN any green highlights will be included in the redline
* AND any highlights that are NOT green will NOT be included in the redline

**Scenario 5: Create Redline - Green Highlight - Comments**
* GIVEN an IAO user has 100% completion of the record flags complete
* AND there are green coloured highlights throughout the package with comments attached to them
* WHEN they create the Redline PDF
* THEN the green highlights will be included in the redline with the associated comments

**Scenario 6: Create Redline - Other Colour Highlights - Comments**
* GIVEN an IAO user has 100% completion of the record flags complete
* AND there are highlights throughout the package that are NOT green with comments
* WHEN they create the Redline PDF
* THEN any green highlights with comments will be included in the redline
* AND any highlights with comments that are NOT green will NOT be included in the redline

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@lmullane - this came from the meeting with Central/Economy team. Scenarios 1 and 2 are probably most important (and will be useful outside of central team) - 3,4, 5 and 6 are all nice to haves, in order of importance, and I figure if its not much additional effort to capture these other possibilities we could do it at once. 

cc @JHarrietha-AOT @KyEggleston @liseandtea

**Comment by KyEggleston** [comment]
This will be addressed through 4862 now.
