### ISSUE TITLE
Prototype Update Based on Ministry Research 

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#482]
Title of ticket: Prototype Update Based on Ministry Research

#### Description
Updating prototype based off of feedback and changes suggested from Ministry Research Sessions. 

#### Dependencies
Depends on the amount of changes requested/suggested from our Ministries. If changes are small we will complete in Sprint 10, if there are larger changes to Prototype they will be completed in Sprint 11.

#### DOD

Ministry Queue Changes
- [x] Remove XGOV
- [x] Change order to have Request#  as First Column
- [x] All Request Filter - Ability to see who is assigned to better help manager
- [ ] Ability to hover over request and have description appear? - Two people said this is a deal breaker what to think about more

Request Review Changes
- [x] Adding overall Request Status Updates
- [x] Add Save Button at end of Divisional dropdown
- [x] Update Divisional Dropdown based on Ministry Feedback
- [x] Have Authorization removed if General Request/if not required
- [x] Rearrange Request Details Dates
- [x] Add option to see what other Ministries have been sent request

**Comment by JHarrietha-AOT** [comment]
@lmullane update queue design based on feedback 

![Call for Records Copy.jpg](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/ebe68fa8-6ed4-4cef-9115-96461ec6b56a)

**Comment by JHarrietha-AOT** [comment]
Just want to leave a comment here, based on this discussion yesterday we will be leaving out the description from the queue at this time. 2/8 said it was required due to others emailing and calling and referencing the content of the request and not the number. In order to better in-force best practice and not try and rebuilt the existing tracker we will not include the description at this time.

**Comment by lmullane** [comment]
Agreed, @JHarrietha-AOT
