### ISSUE TITLE
Fee Waiver - Online Pay Form Not Updating 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4828]
**Describe the bug in current situation**

Not sure if this is so much a bug, as apposed to being a missed requirement / assumption on #2772.

If a user enters a fee waiver before an applicant has paid a fee estimate or outstanding fee, when the analyst sends a revised fee estimate through the 'Contact Applicant' tab, the online pay form is showing an incorrect amount. 

Request is 'On Hold', and a fee waiver is entered. Estimate amount is not updated, and still shows $180, when it is actually $110. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/3e382dd6-a75c-4fdc-ab3f-cc61d46efe49)

When the user resends the fee estimate through the 'Contact Applicant' tab, and the applicant open the payment link, the estimate amount is not including the fee waiver, and still shows $180.

![image](https://github.com/bcgov/foi-flow/assets/117312323/fa3995c5-1c62-46d3-b7bf-df0cc55f3dd9)

However, when the applicant goes to PayBC to pay, the amount is correct. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/2eda65e5-81bf-447a-8d9e-a9d6270a53c7)

This occurs for outstanding fees too:, when a request goes from 'Response' -> 'On Hold'

![image](https://github.com/bcgov/foi-flow/assets/117312323/523502de-a2c8-419b-9a4a-8705df194370)

![image](https://github.com/bcgov/foi-flow/assets/117312323/cc2be32d-fd32-41eb-bcfc-e01fc159936d)

![image](https://github.com/bcgov/foi-flow/assets/117312323/e9b89d14-5be9-43a9-84be-02b8ce0b81d0)

This issue can lead to confusion for the applicant and/or the analyst. 

**Link bug to the User Story**
#2772

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

TEST (and likely PROD as well). 

**Steps to Reproduce**
1. Create a general request, bring the request up to Call for Records state, and enter estimate hours so the fee estimate is >0$
2. Change the request to 'Fee Estimate', and as an IAO analyst, approve the CFR Form/estimates
3. Move the request to 'On Hold' 
4. The fee estimate email will automatically be sent to the applicant, with the correct estimate amount
5. Next, add a fee waiver as IAO to the CFR Form, and save
6. Resend the fee estimate using the 'Contact Applicant' tab
7. Open the new fee estimate email, open the payment link, and see error (where the estimate amount on the initial page is inaccurate and not including the fee estimate, but the PayBC page does show the correct estimate amount)

**Expected behaviour**

GIVEN a request has a fee estimate or outstanding balance
AND a fee waiver has been applied
WHEN the applicant is emailed the fee estimate or outstanding balance to pay
THEN the online payment link/page and PayBC page will show the correct fee estimate or outstanding balance amount (balance remaining), which includes any fee waivers applied
AND the PayBC page will also show the correct fee estimate or outstanding balance amount (which includes any fee waivers applied)

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nimya-aot** [comment]
It is working as expected, but not closing as @KyEggleston mentioned in other ticket #4899 that he needs to check it

**Comment by KyEggleston** [comment]
This was resolved in #4899 - Confirmed this is a duplicate issue, and it is working now. Closing.
