### ISSUE TITLE
xls conversion issue if it comes as part of msg attachments

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4829]
**Describe the bug in current situation**
When an xls file is attached to an msg file , then during conversion ,tabular columns missing on the pdf
**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
test env

**Steps to Reproduce**
1. Go to records tab
2. Upload msg file "Test Other File Embeds.msg" from the testing package
3. Try to download harms

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
<img width="1413" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHN1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7664503caf9dd1e4cf6a23068d5c198853d07d2/image.png" alt="image.png" />

<img width="894" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG91QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4a2837418a0a4a2e5b69cfd6d29a59df8c7a5ea/image.png" alt="image.png" />

**Comment by KyEggleston** [comment]
Checked this functionality / tried to reproduce - appears to be fixed now. Closing.
