### ISSUE TITLE
Change state of request to Open

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#484]
* As an Intake Analyst
* I want to change a request from Intake in Progress to Open
* so that the request can be actioned

**Assumptions & Scope**	
What are the assumptions for this story?

What is in and not in scope?
Closing and redirecting a request are not in scope.
Out of scope: fields within the request are out of scope. 

Assigning a request?

**Acceptance Criteria**	

**Scenario 1: Open a request**
* GIVEN a flex team analyst is on a request in Intake in Progress:
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/663873012
* AND all the mandatory fields are filled
* WHEN the analyst clicks on the dropdown menu for state
* THEN the options will be Open, Redirect, Closed

**Scenario 2: Click on Open**
* GIVEN has clicked the State update dropdown
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/663873013
* WHEN the analyst clicks Open
* THEN a modal will open:
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088424
AND the assignee will be selected
AND the options will be to 'Save Change' or 'Cancel'
AND the analyst will see who is assigned (i.e. Flex Team/Flex analyst)

**Scenario 3: Cancel to Call for Records**
* GIVEN the Flex Analyst has opened the modal for 'Open'
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088424
* WHEN ... I select "Cancel" in the modal
* THEN the state of the request will remain "Intake In Progress"
* AND the drop menu and modal will close
* AND the request will remain in the the Flex Team queue under 'Intake in Progress' state

**Scenario 4: Save request into 'Open' state**
* GIVEN the Flex Analyst has opened the modal for 'Open'
* * https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088424
* WHEN ... I select "Save Change" in the modal
* THEN the state of the request will become "Open"
* AND the drop menu and modal will close
* AND the request will remain in the the Flex Team/analyst queue under Open state
* AND the request will be assigned to the Flex Team/flex team analyst
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
Please reference scenarios for the main source of truth, as some designs are outdated

**Comment by mpilchar** [comment]
Open button at bottom will be removed

**Comment by mpilchar** [comment]
Estimate factors in view change, stage management in front end, rule changes, data capture spread between two components

**Comment by JHarrietha-AOT** [comment]
Design Update of Modal with removed dropdowns as discussed earlier this week

![Screen Shot 2021-09-15 at 5.16.06 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/1e0b9d53-aa35-462d-9b53-97dbc7de439e)

**Comment by m-prodan** [comment]
All AC's passed - closing ticket :)
