### ISSUE TITLE
Striked text is missing during pdf stich

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4853]
**Describe the bug in current situation**
When we do pdf stitching, the strikeout text in the original docx  is missing 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test env
This is for request test.foirequests.gov.bc.ca/foi/ministryreview/2331/ministryrequest/2439

**Steps to Reproduce**
1. Go to records tab and upload any docx file with strikeout text
2. Try this sample  'Test Other file Embeds.msg' from test package. It has a file named "Policy Summary .docx"
3. Try to download the Harms
5. Strikeout text is missing on the consolidated pdf

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
<img width="1339" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFJHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15c67eb86692788c2a4a662fe735ad230a207275/image.png" alt="image.png" />

<img width="1326" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHBHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58f316e2f4f8b96bde38bf19401395fe360ec177/image.png" alt="image.png" />

After conversion, strikeout text is missing on the consolidated one

<img width="1095" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHRHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--750bea39adf1fbd72c8663b19b07e0a2b300af18/image.png" alt="image.png" />

**Comment by nimya-aot** [comment]
Tables are overlapping each other during word doc conversion. Please check that issue as well. This is for request https://test.foirequests.gov.bc.ca/foi/foirequests/2335/ministryrequest/2443.

<img width="1244" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4810cdb74c6f4988c56e971e1752302d3e695b9/image.png" alt="image.png" />

**Comment by nimya-aot** [comment]
>Tables are overlapping each other during word doc conversion. Please check that issue as well. This is for request https://test.foirequests.gov.bc.ca/foi/foirequests/2335/ministryrequest/2443.

<img width="1244" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4810cdb74c6f4988c56e971e1752302d3e695b9/image.png" alt="image.png" />
>
This issue is fixed. But during conversion the striked text is still missing.  Discussed with @divyav-aot @KyEggleston @liseandtea  and @divyav-aot mentioned we need to investigate this issue and may be fix later

**Comment by divyav-aot** [comment]
The normal strikethrough is working as expected. The issue is with revision tracking.  The markups are not preserving after the conversion.

**Comment by divyav-aot** [comment]
As discussed in the standup, this issue has been fixed. Below is the sample screenshot for the same. (deletions will be shows as balloon. Insertions will show in blue color underlined text. tracking of formatting is not captured as discussed)
<img width="1076" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTJBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0bcc8a498feca9f83eaa7b357b874c1c6f57e191/image.png" alt="image.png" />

**Comment by nimya-aot** [comment]
It is working as expected, so closing
