### ISSUE TITLE
Word -> PDF Conversion - Include Comments and Replies

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4859]
* As a ministry or IAO analyst
* I want comments/replies on Word documents to be visible when converted to PDFs in FOI Mod
* So that I can flag the comments for harms in the Harms Package or redact the comment in the Redaction App

**Assumptions & Scope**	
What are the assumptions for this story?

This is to build off #3981 and #4036. In #3981 we handled Excel file notes, and in #4036 we handled Excel file comments/replies. However, we never implemented the feature when Word documents are converted to PDF, to retain the comments/replies. 

For example, here is an example of a Word documents with comments/replies:

<img width="1451" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODFNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca191f29197ab6fff2bb22bc17f0b8c5b93564f7/image.png" alt="image.png" />

When this is converted to PDF through the 'Records' tab, we are losing the comments/replies:

<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUZNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adb5815dd1aaef56f26dd7269c3d798f5f1bb82f/image.png" alt="image.png" />

We need to retain the comments/replies when a Word document is converted to PDF in FOI Mod. 

Ideally, after being converted to PDF, comments/replies would be displayed as the following: 

![image](https://github.com/bcgov/foi-flow/assets/117312323/e620e6c2-659a-40e9-8b4f-dc596740e625)

Some of this similar work is already being done for PDFs in #4708. 

What is IN scope?

Word -> PDF conversion to include comments

What is NOT in scope?

**Acceptance Criteria**	

Scenario 1: Display comments in converted Word documents

GIVEN a Word document has comments or replies
WHEN the Word document is uploaded into FOI Mod
AND the Word document is converted to PDF
Then the comments will be visible in the PDF (under 'Download Converted', in the Harms Package, and in the Redaction App)

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by divyav-aot** [comment]
Effort added to upgrade the syncfusion libraries and testing/fixing all filetype conversions.

**Comment by divyav-aot** [comment]
Issue with **You have 2 mentions.msg** and **attachment.msg** from the test package. This will be fixed as part of the ticket.

**Comment by divyav-aot** [comment]
Please test file type conversions

**Comment by nimya-aot** [comment]
working as expected, so closing
