### ISSUE TITLE
9.2.1 and 9.2.2

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#4871]
**Place-in the release name**
9.2.2 - https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4854
9.2.1 - https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4339

#### Activity start time
4:30 pm

#### Activity end time
Summarize issue 

#### Step-1: Database Backup (Check the desired components)
Capture the backup details 
- [x] FOI DB (xxx)
- [x] BPM DB
- [x] Docreviewer DB

#### Step-2: Image Backup (Check the desired components)
Capture the image details 
- [x] request-management-api (yyy)
- [ ] forms-flow-web
- [ ] notification-manager
- [ ] reviewer-api
- [ ] reviewer-web
- [x] reviewer-conversion
- [x] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

#### Step-3: Production - Tagging of image (Check the desired components)
- [x] request-management-api
- [ ] forms-flow-web
- [ ] notification-manager
- [ ] reviewer-api
- [ ] reviewer-web
- [x] reviewer-conversion
- [x] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

#### Step-4: Signoff from business
- [ ] Yes
- [ ] No
- [ ] Not Applicable

#### Step-5: Healthcheck (Check the desired components)
- [ ] FOI DB
- [ ] BPM DB
- [ ] Docreviewer DB
- [ ] redis-
- [ ] redis-
- [ ] redis-
- [ ] request-management-api
- [ ] forms-flow-web
- [ ] notification-manager
- [ ] reviewer-api
- [ ] reviewer-web
- [ ] reviewer-conversion
- [ ] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

#### Step-6: Staging - Tagging of image (Check the desired components)
- [ ] request-management-api
- [ ] forms-flow-web
- [ ] notification-manager
- [ ] reviewer-api
- [ ] reviewer-web
- [ ] reviewer-conversion
- [ ] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

**Observations**
List down the observations of incidents which happened in release window

**Overall Rating**
- [x] Good (No change)
- [ ] OK (With observations)
- [ ] Bad(Rollback)

**Comment by divyav-aot** [comment]
DB backups:
4.4M  - /backups/daily/2023-12-12/patroni-master-002-ffa-camunda_2023-12-12_16-27-24.sql.gz
62M  -  /backups/daily/2023-12-12/patroni-master-002-foidb_2023-12-12_16-27-13.sql.gz
