### ISSUE TITLE
Change state to redirect

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#488]
* As an Intake Analyst
* I want to be able to mark a request as Redirect
* so that I can action it and close it

**Assumptions & Scope**	
What are the assumptions for this story?
We do not need a modal for this

What is in and not in scope?

Closing a request in Redirect state - that is covered in #469

**Acceptance Criteria**	

**Scenario 1: Intake in Progress request**
* GIVEN a request is in Intake in Progress state
* WHEN the intake analyst clicks on the state update dropdown
* THEN Redirect will be an option

**Scenario 2: Redirect request**
* GIVEN an intake analyst has clicked the state dropdown for an Intake in Progress request
* WHEN the analyst clicks Redirect
* THEN the dropdown will close
* AND the state will change to Redirect 
* AND the dropdown will read Redirect

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@arielleandrews, @JHarrietha-AOT, do you think we need a modal for this state change? I think it's not necessary.

Note, any state changes will require the analyst to first save the request in an Unopened state with all the before they can select Redirect.

**Comment by lmullane** [comment]
Duplicate

**Comment by arielleandrews** [comment]
I agree it's not a necessity, but I wonder about the consistent user experience. Would love to hear from your design perspective @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @lmullane for the MVP I don't think this is required. Give the user flow we are expecting users to go through for the MVP this won't be needed. I think it should be included post MVP when we are looking at the Split and Redirect for Intact that we tested a little while ago.
