### ISSUE TITLE
No notification messages for harms download and upload error 

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4895]
**Describe the bug in current situation**
When a ministry user try to download the harms and if harms are ready for export then " Records for harms are ready for export" notification message is not coming up
Also if any file fails to upload then failure message .,say example like this "50mb.pdf file(s) could not be added to package, please check record for errors" also not coming up
**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test

**Steps to Reproduce**
1. Go to records tab
2. Upload files as ministry user
3. Try to download the harms and notification message is not coming if they are ready to export
4. Also notification for failed upload also missing on notification messages

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by antsand** [comment]
The notification message is incorrect. Currently fixing the issue.

**Comment by divyav-aot** [comment]
@antsand  - below are the messages for harms download.
if stitching successful: "Records for harms are ready for export"
if error: "Preparing records for harms export failed. Please Try Again"
if skipped files while stitching : "[skipped file names] file(s) could not be added to package, please check record for errors"

**Comment by m-prodan** [comment]
Confirmed these notifications are working for Ministry users as expected now
