### ISSUE TITLE
Payment page shows wrong payment fee if  user received fee waiver amount

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4899]
**Describe the bug in current situation**
When a user receives 50% fee waiver for the total amount of $330, then payment page shows $330 instead of $165. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Production

**Steps to Reproduce**
1. Go to CFR form as a ministry user and add 14 hours as estimate(Total will be $330)
2. Login as IAO user and approves the CFR and change the request to 'on Hold' state
3. Enter the fee waiver amount as $165
4. Send the fee estimate to applicant
5. Applicant receives payment link which directs to payment page having amount $330 instead of $165
6. Because of this credit card info page  shows $82.50

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.
<img width="1455" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3RqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe51ecefe3b81da970d62d95846461effe5b46ca/image.png" alt="image.png" />

<img width="1164" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzVqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfd1e88077de5ee024420847971f02229df970ed/image.png" alt="image.png" />

**Comment by KyEggleston** [comment]
Kyle to check if related to #4828

**Comment by nimya-aot** [comment]
It is working as expected, so closing
