### ISSUE TITLE
DueDate refinement

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#490]

**Comment by sumathi-thirumani-aot** [comment]
1. Code optimization from recursive loop to recursive function
2. Changes to observance day calculation.

**Comment by sumathi-thirumani-aot** [comment]
PR: https://github.com/bcgov/foi-flow/pull/495

**Comment by abin-aot** [comment]
New Holiday has come! - "National Day for Truth and reconciliation": we need to check the package  or having static logic json to add the holidays
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/4ac5f1c6-8c66-4009-8382-31ae0514b6c0)
