### ISSUE TITLE
No Personal Information checkbox for Request Description

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#491]
* As an Intake Analyst
* I want a checkbox to indicate when any personal information has been removed from a request description
* so that no personal information of the applicant's is shared with Ministry Coordinators or published in reports

**Assumptions & Scope**	
Checkbox will appear for General requests only

What is in and not in scope?

**Acceptance Criteria**	

**Scenario 1: Checkbox checked on Unopened Request**
* GIVEN an Intake Analyst is reviewing a request in Unopened state
* WHEN the analyst has checked the "Description contains NO Personal Information" checkbox
* AND has completed all other mandatory fields 
* THEN the Save button will be enabled
* AND the request description will be saved as a new version known as the Redacted Request Description

**Scenario 2: Checkbox unchecked on Unopened Request**
* GIVEN an Intake Analyst is reviewing a request in Unopened state
* WHEN the analyst has NOT checked the "Description contains NO Personal Information" checkbox
* THEN the Save button will be disabled (greyed out)

**Scenario 3: Unable to remove checkbox once saved**
* GIVEN an IAO analyst is reviewing a request that has been Saved
* WHEN the analyst views the "Contains NO Personal Information" checkbox
* THEN the checkbox will be disabled (greyed out)
* AND will remain disabled in all subsequent states (Intake in Progress, Open, Call For Records, etc.)

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
@JHarrietha-AOT please add the design link when ready.
@lmullane FYI - if this is redundant we can close it but wanted to capture the story just in case

**Comment by lmullane** [comment]
Thanks, @arielleandrews 

Are these scenarios captured in #31?

**Comment by JHarrietha-AOT** [comment]
Checkbox design has been added to "Intake in Progress". Below is a screenshot as well for reference

![Screen Shot 2021-09-15 at 2.12.08 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/38e4758b-2ee4-404f-b811-728bc0e705be)

**Comment by arielleandrews** [comment]
duplicate
