### ISSUE TITLE
Onboarding to Object storage

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#492]
Title of ticket: Onboarding to Object storage

#### DOD
- [x] Review information found on: https://github-wiki-see.page/m/bcgov/nr-get-token/wiki/Object-Storage
- [x] Review attached OCIO object storage info - [https://app.zenhub.com/files/358004325/51888df8-fae2-42d8-9c75-ef57337f4e3e/download](https://app.zenhub.com/files/358004325/51888df8-fae2-42d8-9c75-ef57337f4e3e/download)
- [x] Complete onboarding forms

**Comment by mpilchar** [comment]
Please update DOD for this one @lmullane or @VineetBala-AOT if you get a chance

**Comment by VineetBala-AOT** [comment]
Hi @mpilchar  , I have updated as all three are completed.
CC: @lmullane

**Comment by mpilchar** [comment]
What will next steps be to onboard to object storage? Do we wish to expand on this DOD, or close and create a new issue for next sprint? @VineetBala-AOT
