### ISSUE TITLE
MSD Files in Records Tab - Missing from Harms Package

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4930]
**Describe the bug in current situation**

On MSD-2023-34361, one file / file type was not being included in the Harms Package. The file upload date is Dec 22, 2023, 9:45 AM, uploaded (fixed) by me (Kyle Eggleston). If you need further help identifying the file let me know, but keeping out of this ticket for confidentiality reasons. 

This file in question was a native PDF file, which is believed to be exported out of a system used by MSD called 'ICM'. It was successfully uploaded and went through dedupe. However, when you select to 'Download for Harms', and produce and download the Harms Package, this file is not included. 

I will note, when checking the Redaction App, this file was correctly displayed in the Redaction App. 

Therefore, this issue appears to be confined to the specific file / file type, and how it's treated when being stitched into the Harms Package. 

I was able to manually resolve this issue for the users, so they could produce an accurate Harms Package. However, this could have also been easily missed, and may lead to a responsive record not being sent to an applicant. Therefore, this is a high priority. 

NOTE: this also occurred on the same file type on MSD-2023-34269. The file in question was uploaded on December 22, 2023, 11:44 AM. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

High - may lead to missing responsive records that may be sent to applicant

**Chance of Occurring (high/medium/low/very low)**

Medium

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

PROD

Reproduced in TEST as well - file is not included in Harms Package

**Steps to Reproduce**
1. Upload the file, indicated above, to the Records tab on a request
2. Select 'Download for Harms'
3. Download the Harms Package
4. See error, where the file is not included in the Harms Package (but it does show up in the Redaction App)

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment]
Per comment in JIRA - tested and closed, working as expected against the files noted.
