### ISSUE TITLE
Changing the Assignee of IAO; clears the group notification of Ministry Members

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#4984]
**Describe the bug in current situation**
When the request is moved from open to CFR. 
The system generated the intended notification; but when the IAO changes the assignment; it clears the group notification of members.

**Link bug to the User Story**

**Impact of this bug**
In this kind of scenario; the ministry members will miss the notification.

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Create a new request and move to CFR state
2. In the ministry login; you can see the notifications. Now change the assignment of IAO.
3. This clears the ministry specific assignments.

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
Closing as duplicate.
