### ISSUE TITLE
Convert iCalender to PDF

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#50]
As a Flex team analyst, I want iCalendar files pre-processed so that I can load them into Intella to create one PDF for redaction that can easily be created with no errors or delays

**Acceptance Criteria**

**Scenario 1: Convert iCalendar file to a PDF**
GIVEN iCalendar files are LAN folder for the Call for Records
WHEN the iCalender files are loaded into the file processor
THEN the files will be converted to PDF
AND the each meeting will include date, time, priority, attendees, organizer, description, place and attachments
AND the PDFs can be loaded into Intella for deduplication

**Scenario 2: Calender meetings include Excel attachments** 
GIVEN a calendar invite includes an attachment
WHEN the iCalender file is processed
THEN the Excel file will be processed according to story 6
AND the processed Excel file will be saved in order with the meeting

 **Scenario 3: Create Output folder**

GIVEN a Call for Records folder on the LAN contained Excel or iCalendar files
WHEN these files are processed and converted to PDF
THEN a subfolder called 'Output' will be saved as a subfolder of the original folder on the LAN
Scenario 2: Save processed files in Output folder

 **Scenario 4: Save in Output folder**

GIVEN a Call for Records folder on the LAN contained Excel or iCalendar files
WHEN these files are processed and converted to PDF
THEN these processed PDFs are saved in the 'Output' folder
 

**Dependencies?**

**Technical:**

 - As there is no UI, file conversion is dependent upon the file watcher to pull records into the app for conversion.
- AXIS requires files to be in PDF for redaction.

Design
This is a backend process with no user interface.**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.     [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@abin-aot, @divyav-aot, please review the AC.

**Comment by m-prodan** [comment]
Similar to my comments on the excel conversion AC - do we need to include the Intella/de-dupe criteria?
Additionally, will need to be careful with stand-alone calendar requests - for those particular subset of requests, applicant requests the calendar records to be in "calendar detail style". I'll need to confirm my assumption, but I believe the Ministries are still printing those records in the requested way, so it may not be an issue, but it is something to think about. I can elaborate at the refinement session.  Otherwise, looks good, I would just add the following if it makes sense:

THEN the files will be converted to PDF with the required formatting

**Comment by lmullane** [comment]
Thanks, @m-prodan . I was spitballing on what the format should be.

Will add to the AC on Intella ready PDFs.

**Comment by m-prodan** [comment]
Per QA Testing - all icalendar formats I tested including ones with attachments converted without issue.
