### ISSUE TITLE
Watch a request

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#503]
* As an IAO analyst or ministry coordinator
* I want to be able watch a request
* so that I can be informed of what's happening with a request

**Assumptions & Scope**	
What are the assumptions for this story?

- Ministry coordinators will only be able to watch a request specific to their ministry (i.e. they will not see requests in an 'Unopened' or 'Intake in Progress' state or requests for another ministry 
- Ministry coordinators can make only members of their ministry team be watchers of a request
- IAO analyst can watch any request
- IAO analyst can make any other IAO analyst a request watcher and any ministry coordinator for the relevant ministry a watcher

What is in and not in scope?
- Display of the watched request on the ministry or IAO queue - will be handled in a separate story
- Automated notification for watched request
- Display of number of watchers and making others a watcher - that is covered in a separate story

**Acceptance Criteria**	

**Scenario 1:See watcher functionality**
* GIVEN an IAO analyst or ministry coordinator is on the queue
* WHEN they click on the a request in any state (as noted above ministry coordinators can only see requests assigned to their ministry)
* THEN they will see a field to watch a request view:
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/775202206
* AND the field will list if he or she is currently a watcher ('Watch' vs Unwatch') and the number of watchers: 0 to X

**Scenario 2: Read 'Watch'**
* GIVEN the ministry coordinator or IAO analyst is on a request view
* WHEN the ministry coordinator or IAO analyst is not already a watcher
* THEN the watcher field will read 'Watch"

**Scenario 3: Click 'Watch'**
* GIVEN the ministry coordinator or IAO analyst is on a request view
* AND the ministry coordinator or IAO analyst is not already a watcher
* WHEN they click 'Watch"
* THEN they will become a watcher'
* AND the field will read 'Unwatch'

**Scenario 4: Read 'Unwatch'**
* GIVEN the ministry coordinator or IAO analyst is on a request view
* WHEN the ministry coordinator or IAO analyst is already a watcher
* THEN the watcher field will read 'Unwatch"

**Scenario 5: Click 'Unwatch'**
* GIVEN the ministry coordinator or IAO analyst is on a request view
* AND the ministry coordinator or IAO analyst is already a watcher
* WHEN they click 'Unwatch"
* THEN they will not longer be a watcher'
* AND the field will read 'Watch'

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, I've written up the scenarios of how a user either watches or unwatches a request following the pattern in GitHub.

What I like about the GitHub pattern is the primary action is for a user to either watch or unwatch a request, and can be done with one click. Making others a watcher is secondary and takes more time.

Please review and advise if this is what you were thinking?

Note, viewing who is currently watching a request and making another user a watcher for a request is not in scope for this story. That will be covered in #504 

Note we will probably need a search functionality for IAO if we are agreed that a user can make anyone in IAO a watcher. Even if it's narrowed to only your team, we may need a search for the user, as some teams may be large. A user search can be a component that is also used when making assignments.

@arielleandrews, welcome your thought on this as well.

cc @arielleandrews

**Comment by arielleandrews** [comment]
To clarify @lmullane - are these written so that the light blue side of the button will read Watcher or Unwatch based on the user who is viewing the request and whether or not they are a watcher, and can be used to switch that user only from Watch to Unwatch? And then the dark blue side of the button will be used to expand and assign other users as Watchers?

**Comment by lmullane** [comment]
Yes, that's correct. See the Watch function at the top of this Github page on the right.

The premise is that an individual does not want to search for their name on a dropdown to watch or unwatch a request. They know who they are and so does the app!

**Comment by lmullane** [comment]
#504 has the scenarios for adding someone else to be a watcher.

**Comment by lmullane** [comment]
@arielleandrews, yes, that is how they are written.

My thought is that I want to quickly make myself a watcher or a non-watcher for a request with one click. My assumption is the user will prefer this to clicking to open a drop down, scrolling to find his or her name, click to check a box, then clicking a 'Done' or 'Save' button to save the change.

**Comment by arielleandrews** [comment]
Makes sense @lmullane, I like it. Scenarios look good to me

**Comment by divyav-aot** [comment]
@arielleandrews @m-prodan @JHarrietha-AOT @lmullane @mpilchar - Just wanted to inform you that, you will not be able to add a watcher from "Add Request". We will be hiding the watcher from "Add request" as we cannot tag the watcher until the request has an ID to track. Watcher can be added once this request is in "Intake in progress".  Hope this is fine with you. Let us know if you have any concern. 
Note: There is no issue with request submitted online.
