### ISSUE TITLE
Log conversion file

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#51]
* As an flex analyst
* I want a log file 
* so that I know what files successfully converted and any that failed

**Acceptance Criteria**	

**Scenario 1 : Create log text file** 
GIVEN a folder on the LAN contained Excel or iCalendar files
WHEN the conversion is successful or fails
THEN a text file with the log on success, failure of file conversions will be created 
AND the text file will be saved in the request folder
AND the log will be saved in the database

**Scenario 2: Data on log file**
* GIVEN a file conversion is started
* WHEN the log file is created
* THEN the log file will include the time stamp of log file created, files that successfully converted and time stamp of conversion and location of converted file, files that did not convert and time stamp of file that did not convert 

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.     [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
My QA has concluded, all relevant tests produced accurate logs as expected in the log folder.

**Comment by mpilchar** [comment]
Props on thorough testing @m-prodan !
