### ISSUE TITLE
Change of state from Ministry Sign Off to Response

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#512]
** As a ministry coordinator
* I want to be able to change the state of a request from Ministry Sign Off to Response
* so that I can inform the IAO team the records are ready for release

**Assumptions & Scope**	
What are the assumptions for this story?

- Only a ministry coordinator can change a request from Ministry Sign Off into a Response state

Not in scope:
- Getting sign off from Exec; that happens outside app
- This story assumes that we have built the ministry specific queue under a different story. So building the queue is not in scope. 
- Notifications that the state has change; coordinator could make a comment in the request and upload the approval doc, but that will be handled in a separate story
- Closing request is covered in #469 

In scope:
- Displaying the updated request state is in scope.
- Confirmation, including documentation, that ministry exec have approved the response.

**Acceptance Criteria**	

**Scenario 1: Ministry Sign Off request Dropdown menu**
* GIVEN I am an ministry coordinator
* WHEN I I am on 'Ministry Sign-off'
* THEN the state menu at the top of the request will say 'Ministry Sign Off'
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/813687581

**Scenario 2: Click dropdown for request in a 'Ministry Sign Off' state**
* GIVEN the ministry coordinator is on a request in the 'Ministry Sign Off' state
* WHEN I click the state dropdown menu
* THEN Review, Response and Closed are the Options

**Scenario 3: Ministry Sign Off request Dropdown menu - Select Response**
* GIVEN I am a ministry coordinator on a request in 'Ministry Sign Off' state
* AND I have clicked on the state dropdown menu
* WHEN I click on 'Response' from the dropdown menu
* THEN a modal will open with the options to 'Save Change' or 'Cancel' and Include a space to upload an attachment
* AND the option to save change will be unavailable without an attachment. 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/813687576

**Scenario 4: Cancel to Response**
* GIVEN the ministry coordinator has opened the modal for 'Response'
* WHEN ... I select "Cancel" in the modal
* THEN the state of the request will remain "Ministry Sign Off"
* AND the drop menu and modal will close
* AND the request will remain in the the ministry queue under the Ministry Sign Off state
* AND the request will remain in the the IAO queue under the Ministry Sign Off state

**Scenario 5: Save Change to Response Becomes Active**
* GIVEN the ministry coordinator has opened the modal for 'Response'
* WHEN ... the Ministry coordinator uploads a file, from either dragging and dropping, or selecting through the 'Add File' button
* THEN the Save button will become active

**Scenario 6: Save Change to Response Selected**
* GIVEN the Ministry coordinator has opened the modal for 'Response'
* AND a file has been uploaded
* AND the coordinator presses the 'Save' button
* THEN the request will remain in the the ministry team queue but now in the Response state
* AND the request will remain in the IAO queue but now in the Response state

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@arielleandrews, @m-prodan and @JHarrietha-AOT, should we require the ministry coordinator to click a box confirming they have exec sign off and/or upload an attached proof of sign off within the modal/view before they can click 'Save Change' to complete the state change to Response.

I think we should. 

The time stamped approval confirmation and attached document could be captured as a posted comment.

**Comment by arielleandrews** [comment]
I agree @lmullane, I think that's best practice. We'll need to be mindful in the design to ensure IAO receives the proper documentation - depending on the response type a full sign form is required vs. some where only a written statement from a coordinator is necessary. But I agree an action to confirm approval has been obtained will reduce risk

**Comment by lmullane** [comment]
Perfect. I will revise the scenarios once @JHarrietha-AOT does a design to capture this requirement to confirm proof of approval.

**Comment by m-prodan** [comment]
Updated scenario to require attachments before save can be activated. Please add/link design when you have it completed @JHarrietha-AOT

**Comment by lmullane** [comment]
All scenarios passed.
