### ISSUE TITLE
File conversion for iCalendar attachments

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#52]
* As a Flex team analyst
* I want attachments to single meeting iCalendars to be saved in the output folder
* so that the attachments can be deduplicated

**Acceptance Criteria**	

**Scenario 1: Calender meetings include attachments that are not Excel** 
GIVEN a calendar invite includes an attachment other than Excel (i.e. PDF, Word, etc.)
WHEN the iCalender file is processed
THEN the attached files will be put in the Native formats in the output folder

**Scenario 2: Excel attachment **
* GIVEN the attached file is an excel file
* WHEN the file is processed
* THEN the file will be put into pdf format and put in the Output folder

**Scenario 4: iCalendar attachment**
* GIVEN the attached file is an iCalendar 
* WHEN the iCalender meeting as iCalendar attachment
* THEN the iCalendar file will be processed into a PDF and put in the output folder

**Scenario 3: iCalendar attachment with additional attachments**
* GIVEN the attached file is an iCalendar 
* WHEN the iCalender meeting as iCalendar attachment
* AND the iCalendar attachment also has attachment
* THEN the only the iCalendar attachment will be processed into a PDF and put in the output folder
* And the attachments to the second iCalender will not be processed

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.     [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
QA Tests concluded on each call for records folder. Service acted as expected, the specific icalendar and excel files I used to test were all converted as expected with no issues.
