### ISSUE TITLE
Flickering state when review request

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#526]
Title of ticket: 

#### Description
Steps to reproduce:
1. login to the application
2. from the dashboard click on any Open/Redirect/Closed request
3. review request page load with Unopened State and suddenly changes to Open/Redirect/Closed
4. the color change is visible

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by mpilchar** [comment]
Noting that the flicker was present when QAing #453. When closing out of a modal, it will flicker back to whatever the previous state was on dropdown menu (including colour change), before landing on the intended state
