### ISSUE TITLE
Resolve SonarQube CodeSmells

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/foi-flow#539]
Title of ticket: Resolve SonarQube CodeSmells

#### Description
Resolve SonarQube CodeSmells here: https://sonarcloud.io/project/issues?id=bcgov_foi-flow&resolved=false&types=CODE_SMELL

307 CodeSmells at time of ticket creation.

#### Dependencies
None.

#### DOD
- [ ] Critical CodeSmells resolved
- [ ] Major CodeSmells resolved
- [ ] Minor CodeSmells resolved

**Comment by mpilchar** [comment]
This is underway this sprint - closing ticket
