### ISSUE TITLE
iStore request: Create a Service account to access Test LAN

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#54]
Work with Michelle sinnott on iStore orders needed to support technical architecture and ability to create space for testing:

- Service account to access the Test LAN

**Comment by mpilchar** [comment]
This is a single service account that will be used by the development team to access the Test LAN

**Comment by m-prodan** [comment]
Currently w/ Michelle Sinnott and iStore

**Comment by m-prodan** [comment]
Service accounts created - awaiting consult w/ technical team to determine specifics of how to give it the unique permissions to function as needed on the test LAN.

**Comment by m-prodan** [comment]
Service account request credentials received today. Order needed to be resubmitted, as the original service accounts received were not the correct ones.
