### ISSUE TITLE
Working Group admin

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#543]
#### Description
These are the follow up actions to the Sep 23 working group meeitng

#### DOD
- [x] Molly to create a shared space where working group team members can populate an agenda
- [x] Add Karla's replacement to attendance list
- [x] Matt to schedule 30 min recurring monthly meeting until Dec 2021, share link to agenda with invitation for members to drive future agendas with topics they wish to cover. If barriers to technology, email Molly with agenda ideas.

**Comment by mpilchar** [comment]
cc: @arielleandrews @lmullane

**Comment by mpilchar** [comment]
I have created blank agendas in miro @m-prodan https://miro.com/app/board/o9J_lwDMCMs=/

**Comment by lmullane** [comment]
Thanks for tracking this , @mpilchar

**Comment by m-prodan** [comment]
Meetings have been scheduled for third thursday of a given month at 3PM until the end of the year. I've included the link to the Miro board, but I also advised that we would send out a reminder ahead of time. I'll set calendar reminders for myself for the Monday of our WG meeting week.

**Comment by m-prodan** [comment]
Also updated our membership list on the WG TOR - is there a separate space for an attendance list somewhere, or can we consider this one closed @mpilchar?
