### ISSUE TITLE
Request CFR Stage Dropdown menu

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#567]
* As a ministry coordinator
* I want an overall status of the CFR for a request
* So that I have an overview of records gathering at a divisional level

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?
"Request CFR Stage" Dropdown menu only, and changes in the ministry queue

What is NOT in scope?
Creating the front end for this dropdown menu is covered in #566 with the rest of the "request tracking" section

**Acceptance Criteria**	

**Scenario 1: VIew options in "Request CFR Stage" Dropdown menu**
* GIVEN ... I am a ministry coordinator and am on the ministry view of the request page
* WHEN ... I select the "Request CFR stage" dropdown menu
* THEN ... I see the following options: With IAO, Fees sent to IAO, Gathering Records, Harms Assessment, Deduplication, CFR Complete, No Records Sign Off
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088423

**Scenario 2: Select option in "Request CFR Stage" Dropdown men**
* GIVEN ... I am a ministry coordinator and have clicked on the "Request CFR stage" dropdown menu
* WHEN ... I select one of the menu options
* THEN ... the dropdown menu collapses and will display the item selected
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088423
* AND the status will appear in the CFR Status on the ministry queue

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
#570 - ministry queue

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088423

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
I've created this as an issue in order to discuss it but since this evolved out of the user sessions and there's not yet a design for it, I don't have enough information to develop the scenarios. 

For discussion: 
- What are the menu options? (ie: In progress, on hold, completed)
- Does this dropdown menu change manually or automatically? If auto, what triggers it?
- What is the impact on the status shown in the ministry queue? 

cc: @lmullane @JHarrietha-AOT @m-prodan @arielleandrews

**Comment by lmullane** [comment]
Sounds reasonable, @mpilchar 

That would mean scenario 6 in story #566 should be part of this story instead, right?

cc @JHarrietha-AOT @arielleandrews @m-prodan

**Comment by m-prodan** [comment]
This isn't quite the same as scenario 6 in story #566 - this was something we heard where a Ministry was tracking multiple program areas - they wanted a higher level means to track the overall status of a given stage (ie: Call for Records, Harms Assessment, Review, Sign-Off). So for example, a request's overall status is call for records, divsion 1 and 3 are gathering records (as noted in the drop downs), and division 2 has provided a no records response.

Re: Molly's points for discussion:

What are the menu options? (ie: In progress, on hold, completed)
I would suggest the following: Call for Records, Fee Estimation, Harms Assessment, Records Review, Sign-Off

Does this dropdown menu change manually or automatically? If auto, what triggers it?
I think it may need to be manual - but were it to be automatic, it would probably depend on the triggers of the divisional tracking drop downs. It could get complicated so we'd want to be mindful of how or if we actually incorporate this. 

What is the impact on the status shown in the ministry queue?
I would think it doesn't change - call for records encompasses fee estimation, gathering of records, and harms assessment - so it still makes sense as a status for the request itself.

**Comment by arielleandrews** [comment]
Agree with @m-prodan's points. For the last item, I see the "overall request status" being what displays in the Ministry queue. It makes sense to me what the person sees in the queue listing is the overall status at a glance.

**Comment by mpilchar** [comment]
@lmullane for your review and consideration for refinement on Tuesday.

**Comment by mpilchar** [comment]
I think we probably want to have "save" as it's own story and move Scenario #3 to that issue - thoughts?

**Comment by m-prodan** [comment]
It probably doesn't need to function much differently than our current save when an analyst is on the review request view. I think the save makes sense after everything is built out - the overall tracker from this story, and the divisional tracking in #566 - we could tack on saving to 566 potentially, and have both stories proceed in a future sprint so it all gets tackled at once.

**Comment by lmullane** [comment]
@m-prodan, updated the AC to reflect the states in the designs, but think we need to discuss the working and the states. 

As this is a one selection only dropdown we don't need a save button. That was required for 566 as the division selection was a one to many. Without a save button for the division selection, the dropdown would close each time a selection was made. Possible we may want an 'Ok' button instead and then make them still click 'Save' at the bottom.  Let's discuss with @abin-aot during refinement.

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan and I are going to have a meeting discuss a finalized list to then test with Ministries. Ticket can move forward with caveat that list with need to be updated

**Comment by mpilchar** [comment]
No longer needed - covered by divisional tracking. closing.
