### ISSUE TITLE
Setup Keycloak access

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#57]
Title of ticket: 

#### Description
Take over Keycloak from BCGOV/foi-requests

#### Dependencies
Who has the admin rights and ID?

#### DOD
- [ ] Admin access
- [ ] Check configuration

**Comment by acoard-aot** [comment]
https://dev.oidc.gov.bc.ca/auth/admin/5k8dbl4h/console/#/realms/5k8dbl4h/identity-provider-settings

https://test.oidc.gov.bc.ca/auth/admin/5k8dbl4h/console/#/realms/5k8dbl4h/identity-provider-settings

https://oidc.gov.bc.ca/auth/admin/5k8dbl4h/console/#/realms/5k8dbl4h/identity-provider-settings

**Comment by acoard-aot** [comment]
All developers have keycloak access as of Friday, just forgot to update task.

**Comment by mpilchar** [comment]
Thanks @acoard-aot !
