### ISSUE TITLE
Automatic assignment  to Flex Team for Open Requests 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#579]
Title of ticket: 

#### Description
As per the discussion on Sept 29th, discussion came up to auto-assign to Flex Team after changing from "Intake In Progress" to "Open" . Leaving discussion to @m-prodan  @arielleandrews 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by lmullane** [comment]
@arielleandrews , @m-prodan, could you confirm whether we want an open request to be automatically assigned to the Flex Team?

**Comment by arielleandrews** [comment]
Thanks for the nudge @lmullane. We'll connect with James and Patrick about the preference here and advise.

**Comment by arielleandrews** [comment]
Confirmed during Nov 22nd meeting with Patrick and James they are in favor of automatic assignment to the Flex Team when a General request is moved from Intake in Progress to Open. Will draft user story for this functionality.

**Comment by lmullane** [comment]
Great! This will provide consistency.

**Comment by arielleandrews** [comment]
Task completed. Requirement document in user story #935
