### ISSUE TITLE
Setup Code Scanning

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#58]
Title of ticket: 

#### Description
Setup code scanning tool

#### Dependencies
Set up pipeline (ie Jenkyns)

#### DOD
- [x] Select tool (aka SonarQube, CodeCov)
- [x] Setup the tool in the tools environment
- [x] Ready to integrate
- [x] OpenShift configuration
- [x] Integrate with pipeline

**Comment by mpilchar** [comment]
How to incorporate code scanning into acceptance criteria? AC to be discussed prior to sprint commitment

**Comment by acoard-aot** [comment]
Quick update, will discuss more at next standup.

SonarQube is up and running in tools environment.

![image.png](https://images.zenhubusercontent.com/6081a3d1bee65b11f6b36f46/e0d23c33-9266-4ea4-a3cf-c238824e3ef4)


There are some issues with integrating with Github Actions though. The good news is we still can still run scans locally and get value out of it even if not as much as full integration.  From what I can tell, BCGov documentation officially supports Jenkins integrations.  

It looks like the "official" way of integrating SonarQube with GitHub actions requires me to i) be the BCDevOps organization administrator  ii) would use up a lot of our free GitHub action minutes.  (Potentially spending more on scanning than building/testing/etc).  This is why the Jenkins approach makes sense, as Jenkins i) doesn't require organization admin ii) already has the spare CPU idling to spend on the scanning.

I'm continuing to look into it and asking other AOT members who've worked on similar setups.  I can think of a few workarounds to still integrate it with our Pipeline that should work (i.e. a more "manual" integration similar to how I've already integrated OpenShift and GitHub).

**Comment by lmullane** [comment]
Thanks for the update, @acoard-aot 

Suggest following up with @saravanpa-aot. He can give the lowdown on the Registries use of GitHub actions.

**Comment by acoard-aot** [comment]
You're one step ahead of me! Right after this I touched base with Sararvan.  He said they were using SonarSource, and apparently it's free for OpenShift projects.  I'm looking into self service now, I think I have to open a ticket, but I'll go through with it.

https://sonarcloud.io/organizations/bcgov-sonarcloud/projects

**Comment by lmullane** [comment]
Great, thanks

**Comment by lmullane** [comment]
@acoard-aot. btw, when we get this all setup it would be great to get a demo.

**Comment by acoard-aot** [comment]
Integration completed, marking task as complete.

Future SonarQube devops work in #544 (test integration / code coverage)
