### ISSUE TITLE
Posting a comment

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#584]
* As a Ministry Coordinator and IAO analyst
* I want a post a comment
* so that I can share information on a file for better tracking on a request 

**Assumptions & Scope**	
This story is the first step for developing our notes section for the review request view of a particular FOI request. This first build will be focused on the Ministry coordinator view for the purpose of a MVP. 
Character limit: 1000

What is IN scope?
This will be the space where the notes will appear on the review request view for Ministry coordinators
This will include the functionality to enter and save a request note by a user

What is NOT in scope?
Editing/deleting of notes by a user will be covered in a separate user story #
System generated messages from the application will be covered in a separate user stories #586, #

**Acceptance Criteria**	

**Scenario 1: Add a Comment**
* GIVEN a Ministry coordinator or IAO analyst is on the Comment page
* WHEN he or she clicks on the t"Add a Comment" button at the top
* THEN the field will become editable to add text

**Scenario 2: Entering text**
* GIVEN the user has clicked 'Add a Comment'
* WHEN the user has has entered text into the notes field
* THEN the paper airplane icon turns blue and becomes active

**Scenario 3: Posting a Comment**
* GIVEN the user has has entered text into the notes field
* WHEN they click on the paper airplane symbol
* THEN the comment will be posted and saved to the request
* AND the posted comment will show: the full name of the user (LAST NAME, FIRST NAME, the date and time the comment was created, and the contents of the comment
* AND Parent comments will displayed will be from newest to oldest

**Scenario 4: Character Limit counter when posting a Comment**
* GIVEN the user has clicked 'Add a Comment'
* WHEN the user has clicked into the text field
* THEN a counter will display below the text field stating 'Characters remaining: XXX'
* AND the counter will count down as the user adds characters
* AND the counter will turn red when there are 25 characters remaining

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/775202206

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by JHarrietha-AOT** [comment]
Just wanted to post here for awareness, spaces and line breaks are currently being counted towards the character count, not sure who is doing QA on this tickets but this is not a show stopper just should be added to a bug

**Comment by mpilchar** [comment]
Functioned as expected!
