### ISSUE TITLE
Deploy code S2I and database

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#60]
Title of ticket: 

#### Description
Source 2 image

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Setup Patroni database
- [ ] Deploy OpenShift .Net Core
- [ ] Automated backup for database

**Comment by acoard-aot** [comment]
Marking this as CLOSED / WONTFIX as we are not proceeding with OpenShift<->LAN integration. This is no longer relevant.
