### ISSUE TITLE
UX Research on Open Info publishing

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#63]
Title of ticket: 

#### Description
UX Research on Open Info Tracker and publishing general requests on Open Info.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] 1-2 page UX Research Plan with research goals, tactics, and participants

**Comment by JHarrietha-AOT** [comment]
General research notes and existing flow can be found here: https://miro.com/app/board/o9J_lFQ2oaU=/

**Comment by JHarrietha-AOT** [comment]
https://bcgov.sharepoint.com/:w:/t/03521/EZpQwdEBO4VBsadawNUcPXABfKmIcn_gTbN9XUGidz2SYg?e=D0fEWY

**Comment by m-prodan** [comment]
Research plan looks good to me!

**Comment by arielleandrews** [comment]
Good from my end too @JHarrietha-AOT

**Comment by lmullane** [comment]
This is complete. Good work, @JHarrietha-AOT
