### ISSUE TITLE
Backend API Changes for Watchers (#503)

### ISSUE THREAD

**Issue by sumathi-thirumani** [bcgov/foi-flow#639]
Implementation for watchers

DOD
===
- [x] Create DB Model to manage the watchers of raw requests
- [x] Create DB Model to manage the watchers of ministry requests
- [x] Create new rest authenticated endpoint to add and remove watcher of raw request
- [x] Create new rest authenticated endpoint to add and remove watcher of ministry request
- [x] Create new rest authenticated endpoint to disable all watchers of raw request
- [x] Create new rest authenticated endpoint to disable all watchers of ministry request
- [x] Unit Testing

**Comment by sumathi-thirumani-aot** [comment]
To remove raw request watcher
=====================

POST http://localhost:15000/api/foiwatcher/rawrequest
{
    "requestid":1,
    "watchedbygroup": "Intake Team",
    "watchedby": "sumathi",
    "isactive": false
}

Response:
{
    "id": 4,
    "message": "Request added",
    "status": true
}

**Comment by sumathi-thirumani-aot** [comment]
To get raw request watchers
=====================
GET http://localhost:15000/api/foiwatcher/rawrequest/1

Sample Response:
[{"watchedby": "sumathi"}, {"watchedby": "testidir"}]

**Comment by sumathi-thirumani-aot** [comment]
To add ministry request watcher
=====================

POST http://localhost:15000/api/foiwatcher/ministryrequest
{
    "ministryrequestid":1,
    "watchedbygroup": "Intake Team",
    "watchedby": "sumathi",
    "isactive": true
}
    

Response:
{
    "id": 6,
    "message": "Request added",
    "status": true
}

**Comment by sumathi-thirumani-aot** [comment]
To remove ministry request watcher
=====================

POST http://localhost:15000/api/foiwatcher/ministryrequest
{
    "requestid":1,
    "watchedbygroup": "Intake Team",
    "watchedby": "sumathi",
    "isactive": false
}

Response:
{
    "id": 7,
    "message": "Request added",
    "status": true
}

**Comment by sumathi-thirumani-aot** [comment]
To get ministry request watchers
=====================
GET http://localhost:15000/api/foiwatcher/ministryrequest/1

Sample Response:
[{"watchedby": "sumathi"}]
