### ISSUE TITLE
Recruit participants for Open Info research

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#64]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD

- [ ]  Identify recruits
- [ ]  Contact recruits
- [ ]  Book online sessions

**Comment by JHarrietha-AOT** [comment]
@m-prodan Can we book in Katherine for anytime after backlog refinement on Thursday? If we can leave a 30 minute window between backlog and her session that would be great.
