### ISSUE TITLE
Prepare for Fee Payment Solutioning

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#644]
Title of ticket: Prepare for Fee Payment Solutioning

#### Description
Prep needed for Fee Payment Solutioning

#### DOD
- [ ] Set-up Kick-off Meeting with James, Patrick, Jacklyn and Team
- [ ] Set-up weekly checkin meetings with team and Cindy Kukucska/James Pinske

**Comment by mpilchar** [comment]
duplicate - closing

**Comment by mpilchar** [comment]
@m-prodan Ok to close? Have we addressed the stuff Cindy K needed, re: fees?

**Comment by m-prodan** [comment]
Yep - good to close! We did all of this stuff throughout
