### ISSUE TITLE
UX research study guide for Open Info publishing

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#65]
Title of ticket: 

#### Description
Study guide with script

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Draft intro and questions
- [ ] Review by SME or PO

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan @lmullane 

Here is a link to the draft script for the UX Research session with the Open Information Team. Feel free to leave any comments for changes or reach out if you want to review anything.

 https://teams.microsoft.com/l/file/EDE9897D-9D7E-417F-B8B1-63EFAB1C7CDF?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FSprint%201%20-%20Research%20-%20Open%20Information%2FUX%20STUDY%20Research%20GUIDE%20-%20Sprint%201.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by arielleandrews** [comment]
@JHarrietha-AOT I've reviewed and it makes good sense to me, I left one comment on the document. Suggest @m-prodan takes a look before we move this to done.

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan @lmullane 

I have added a couple more questions based off your feedback! Thanks for having a read through feel free to leave any additional comments for further changes. 

https://bcgov.sharepoint.com/:w:/t/03521/EX2J6e1-nX9BuLFj76scfN8BDfe1pLuzOV6lwgh8Zb3t5Q?e=wcWAyB

**Comment by arielleandrews** [comment]
Thanks @JHarrietha-AOT! I left one more comment, otherwise looks good from my end

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Good point, I consolidated b,c,d and into one question.

**Comment by m-prodan** [comment]
I made the same comment in another ticket - but the study guide looks good to me @JHarrietha-AOT  :)

**Comment by lmullane** [comment]
@JHarrietha-AOT, looks good to me too. I will move to closed.
