### ISSUE TITLE
Open Info publishing research sessions

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#66]
Title of ticket: 

#### Description
Conduct research sessions with participants. Each session will have a note taker. Synthezing results is a separate ticket.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Session 1
- [ ] Session 2
- [ ] 
- [ ] 
- [ ]

**Comment by JHarrietha-AOT** [comment]
Session completed with Katherine on May 20th about Open Information Process.

Recording can be found here: https://bcgov.sharepoint.com/teams/03521/Shared%20Documents/General/User%20Research/Sprint%201%20-%20Research%20Recordings/Open%20Information%20User%20Research%20Session-20210520_150134-Meeting%20Recording.mp4
