### ISSUE TITLE
Change state from Sign Off to Records Review

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#663]
* As a Ministry Coordinator
* I want to be able to change the state of a request from Ministry Sign Off to Review 
* so that I can ask to have changes to severing completed that were requested during Sign Off 

**Assumptions & Scope**	
* Only a Ministry Coordinator can change a request from Ministry Sign Off back to Review
* IAO Analyst cannot change a request from Ministry Sign Off to Review

What is IN scope?
* Displaying the updated request state is in scope

What is NOT in scope?
* Change from Review to Ministry Sign Off, covered in #510
* Change from Ministry to Sign Off, covered in #469
* Ministry queue, covered in #570
* Notifications that the state has changed

**Acceptance Criteria**	

**Scenario 1: Ministry Sign Off request dropdown menu**
* GIVEN I am a Ministry Coordinator
* WHEN I am on a request in the Ministry Sign Off state 
* THEN the state menu at the top of the request will say 'Ministry Sign Off'

**Scenario 2: Click dropdown for request in Ministry Sign Off state**
* GIVEN the Ministry Coordinator is on a request in the Ministry Sign Off state
* WHEN the Ministry Coordinator clicks on the state dropdown menu 
* THEN the state options will be 'Review' and 'Response' 

**Scenario 3: Click 'Review' in dropdown menu**
* GIVEN the Ministry Coordinator is on a request in the Ministry Sign Off state
* AND the Ministry Coordinator has clicked on the state dropdown menu
* WHEN the Ministry Coordinator clicks on 'Review' from the dropdown menu
* THEN a modal will open with the options to 'Save Change' or 'Cancel'
* AND the modal will display the assigned IAO user and the assigned Ministry user

**Scenario 4: Cancel change to 'Review'**
* GIVEN the Ministry Coordinator has opened the modal for 'Review'
* WHEN the Ministry Coordinator selects 'Cancel' in the modal
* THEN the state of the request will remain in Ministry Sign Off
* AND the dropdown menu and modal will close
* AND the request will remain in the IAO queue and Ministry queue under the Ministry Sign Off state

**Scenario 5: Save change to 'Review' from 'Ministry Sign Off'**
* GIVEN the Ministry Coordinator has opened the modal for 'Review'
* WHEN the Ministry Coordinator selects 'Save Changes' in the modal
* THEN the state of the request will change to 'Review'
* AND the dropdown menu and modal will close
* AND the request will remain in the IAO queue and Ministry queue now in the Review state

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@richard-aot, I'm not seeing the option for the ministry coordinator to select either 'Records Review' or 'Response.'

Both are greyed out in the drop down:

<img width="1098" alt="Screen Shot 2021-11-04 at 8 38 51 PM" src="https://user-images.githubusercontent.com/12040839/140454748-05f30c40-8616-410a-a755-f37378fb18a0.png">

**Comment by lmullane** [comment]
I am signed in with the ministry coordinator test user fyi.

**Comment by richard-aot** [comment]
@lmullane , this looks like an old request with invalid data. You may want to create a new request and test from there.

On CFR state, ministry coordinator has to select ministry assignee and division, in order to move to the next state.

**Comment by lmullane** [comment]
Thanks, @richard-aot. Will do

**Comment by lmullane** [comment]
All scenarios passed.
