### ISSUE TITLE
PIA for new system

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#68]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Draft PIA
- [x] Review by team
- [x] Submit to PCT for review
- [x] PCT sign-off
- [ ] ADM sign-off

**Comment by lmullane** [comment]
Meeting booked for May 25th with IMB reps for privacy and STRA.

**Comment by m-prodan** [comment]
Expected to be sent to PCT for review by EOD today (July 9th)

**Comment by m-prodan** [comment]
Met with PCT today, August 5th - PIA is currently awaiting sign-off. Expectation: this may just be an initiative update to the existing PIA, as collect use and disclosure are not changing, just the technology to support that. Mindy Attwood now assigned to the PIA, expect resolution soon, but no significant concerns raised from PCT perspective. Sign-off may be dependent on STRA.

**Comment by mpilchar** [comment]
@lmullane What's the current status of this?

**Comment by mpilchar** [comment]
Awaiting ADM sign off. New ticket will be created
