### ISSUE TITLE
Update content on fees

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#682]
Title of ticket: 

#### Description
The content on the webform related needs to be updated both on the submission page and the fee page.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Draft content
- [x] PO approval
- [ ] Business approval
- [ ] Confirm regulation has come into force
- [ ] Update text changes and deploy on OpenShift

**Comment by m-prodan** [comment]
Link to content put on teams here: https://bcgov.sharepoint.com/:b:/t/03521/EVBu6JcSnQNMvCHFKCjYy-YBvwSOib-MCmjEL09N3yHLEA?e=nURQdC
