### ISSUE TITLE
Change State from Fee Estimate to On Hold

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#684]
* As an IAO Analyst
* I want to change the request state to On Hold after I have sent an applicant a fee estimate 
* so that the clock stops 

**Assumptions & Scope**	
* Only an IAO Analyst can change the state to On Hold

What is IN scope?
* Reflecting state change in IAO and Ministry queues
* Stopping the clock for the legislated due date

What is NOT in scope?
* Stopping the CFR clock - this is covered in #679
* Processing team assignment will be covered in separate user story

**Acceptance Criteria**	

**Scenario 1: IAO Analyst 'Fee Estimate' dropdown menu**
* GIVEN I am an IAO analyst
* WHEN the state of the request is in 'Fee Estimate' state
* AND I have clicked the state dropdown menu
* THEN the options will be 'On Hold' and 'Closed' 

**Scenario 2: Select 'On Hold' in dropdown menu**
* GIVEN the IAO analyst has clicked the state dropdown menu
* WHEN I click on 'On Hold' from the dropdown menu 
* THEN a modal will open with the options to 'Save Change' or 'Cancel'
* AND the IAO assignee and the ministry assignee will display in the modal
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812304852

**Scenario 3: Save change to 'On Hold'**
* GIVEN the IAO analyst has opened to modal for 'On Hold'
* WHEN I select 'Save Change' in the modal
* THEN the state of the request will become 'On Hold'
* AND the dropdown menu and modal will close
* AND the legislated due date clock will stop
* AND the days remaining field on the left navigation panel will no longer display
* AND the request will remain in the IAO and Ministry queue but now in 'On Hold' state 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812304852
* AND on the Request View the 'Records Due Date' and 'LDD' fields will display as 'N/A'
* AND on the ministry queue the 'Records Due Date' and 'LDD' fields will display as 'N/A'

**Scenario 4: Cancel change to 'On Hold'**
* GIVEN the IAO analyst has opened the modal for 'On Hold'
* WHEN I select 'Cancel' in the modal
* THEN the state of the request will remain 'Fee Estimate'
* AND the dropdown menu and modal will close
* AND the request will remain in the IAO and Ministry queue in 'Fee Estimate' state

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Links added, I would agree it should be displayed as N/A when in Oh Hold State. I think that could be added here as it is a result of the hold state

**Comment by divyav-aot** [comment]
@JHarrietha-AOT , @arielleandrews  and @m-prodan - What should be displayed in IAO review page due date, if the state is "On Hold". is it N/A?
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/fe93e52e-1892-4f1d-b6ac-f2c029caddf6)

**Comment by m-prodan** [comment]
I think that makes good sense @divyav-aot - thanks for catching that

**Comment by lmullane** [comment]
@arielleandrews , @m-prodan when the request is put on hold should the Records Due Date' and 'LDD' fields Do not display as 'N/A' on the Ministry Queue as well as the request view?

Currently it does not.

**Comment by arielleandrews** [comment]
@lmullane correct, good catch. I missed that in the AC. Yes once on hold both the CFR due date and the LDD should display as N/A in the queue.

**Comment by lmullane** [comment]
@divyav-aot, as discussed please update to have dates in show NA on the ministry queue for a request that goes 'On Hold.'

**Comment by lmullane** [comment]
Dates on ministry queue now are listed as NA. Thanks, @divyav-aot
