### ISSUE TITLE
Change State from On Hold to Call For Records

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#685]
* As an IAO analyst
* I want to change the request state to Call for Records after a fee has been resolved 
* so that I can restart the legislated due date and CFR clock and alert the Ministry to resume gathering records 

**Assumptions & Scope**	
* Start Date field will be inactiver
* Only an IAO Analyst can change the state from On Hold to Call for Records
* When the clock is restarted, the day the request was moved to On Hold state and then the day the request was moved to Call for Records are **NOT** included in the days countdown
* The day the state is changed to On Hold AND the day the state is changed back to Call for Records are both considered On Hold days
* Legislated due date will be recalculated based on how many days the file was in 'On Hold' state

What is IN scope?
* Reflecting state change in IAO and Ministry queues
* Resuming the legislated due date clock and recalculating the legislated due date
* Resuming the CFR clock from where it was stopped (not restarting the 10 day countdown)

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: IAO Analyst 'On Hold' dropdown menu**
* GIVEN I am an IAO analyst
* WHEN the state of the request is in 'On Hold' state
* AND I have clicked the state dropdown menu
* THEN the options will be 'Call for Records' and 'Closed'

**Scenario 2: Select 'Call for Records' in the dropdown menu**
* GIVEN the IAO analyst has clicked the state dropdown menu
* WHEN I click on 'Call for Records' from the dropdown menu 
* THEN a modal will open with the options to 'Save Change' or 'Cancel'
* AND the IAO assignee and the ministry assignee will display in the modal 

**Scenario 3: Cancel change to 'Call for Records'*
* GIVEN the IAO analyst has opened the modal for 'Call for Records'
* WHEN I select 'Cancel' in the modal
* THEN the state of the request will remain 'On Hold'
* AND the dropdown menu and modal will close
* AND the request will remain in the IAO and Ministry queue in 'On Hold' state

**Scenario 4: Save change to 'Call for Records'**
* GIVEN the IAO analyst has opened to modal for 'Call for Records'
* WHEN I select 'Save Change' in the modal
* THEN the state of the request will become 'Call for Records'
* AND the dropdown menu and modal will close
* AND the legislated due date will recalculate to exclude the number of days the file was in 'On Hold' state
* AND the days remaining field on the left navigation panel will now display
* AND the request will remain in the IAO and Ministry queue but now in 'Call for Records' state 
* AND the 'Records Due Date' and 'LDD' fields will display with new dates 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088420

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
To finish testing scenario 4 need to have a request 'On Hold/ for some business days to see if the due date recalculates correctly.

**Comment by lmullane** [comment]
@arielleandrews, Hulk Hogan is the applicant for the 'On Hold' request. Others are stale.
