### ISSUE TITLE
Change State from CFR to Deduplication

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#687]
* As a Ministry Coordinator
* I want to be able to change the state of a request to Deduplication 
* so that I know records gathering is complete and that IAO is responsible for the next state of the request 

**Assumptions & Scope**	
* Only a Ministry Coordinator can change the state to Deduplication
* No change to CFR clock when changed to Deduplication

What is IN scope?
* Reflecting the state change in IAO and Ministry queues

What is NOT in scope?
* Notifications
* Attaching and saving files

**Acceptance Criteria**	

**Scenario 1: Ministry Coordinator 'Call for Records' dropdown menu**
* GIVEN I am a Ministry Coordinator
* WHEN the state of the request is in 'Call for Records' state 
* AND I have clicked on the state dropdown menu
* THEN the options will be 'Deduplication', 'Fee Estimate', 'Review' and 'Sign Off'

**Scenario 2: Select 'Deduplication' in dropdown menu**
* GIVEN the Ministry user has clicked the state dropdown menu
* WHEN I click on 'Deduplication' from the dropdown menu 
* THEN a modal will open with the options to 'Save Change' or 'Cancel' as active buttons

**Scenario 3: Cancel change to 'Deduplication'**
* GIVEN the Ministry user has opened the modal for 'Deduplication'
* WHEN I select 'Cancel' in the modal
* THEN the state of the request will remain 'Call for Records'
* AND the dropdown menu and modal will close
* AND the request will remain in the IAO and Ministry queue in 'Call for Records' state

**Scenario 4: Save change to 'Deduplication'**
* GIVEN the Ministry user has opened to modal for 'Deduplication'
* WHEN I select 'Save Change' in the modal
* THEN the state of the request will become 'Deduplication'
* AND the dropdown menu and modal will close
* AND the request will remain in the IAO and Ministry queue but now in 'Deduplication' state 
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/813687572

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
All scenarios passed as expected.
