### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#697]
* As a ministry coordinator
* I want to upload a file to the request
* so that I can save and share completed documentation for the request

**Assumptions & Scope**	
* For MVP only a Ministry Coordinator can upload files to the request
* All versions of files will need to be saved
* File Upload functionality will be utilized and mandatory in multiple state changes (Call for Records to Records Review, Call for Records to Fee Estimate, Ministry Sign Off to Response)
* Valid file types will be Excel, Word and PDF files
* Users will be limited to uploading one file at a time
* File uploads will have a size limit of 50mb
* Categories of file uploads: Call for Records form, Sign Off form

Estimated at 13 during Oct 19 Refinement

What is IN scope?
* number of uploads (limit to 1)
* file types permitted - pdf, excel, word
* file size limit - what's the threshold? 50MB

What is NOT in scope?
* The attachments page, where the attachments can be viewed/downloaded

**Acceptance Criteria**	

**Scenario 1: Upload Attachment Modal**
* GIVEN a Ministry coordinator is on the review request page of a request
* WHEN they change the state from: Call for Records to Records Review; or Call for Records to Fee Estimate; or Ministry Sign Off to Response
* THEN the upload attachment modal will open

**Scenario 2: Drag and Drop a valid file type**
* GIVEN a Ministry Coordinator is on the file upload modal: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088423
* WHEN I drag and drop a single pdf, Word or Excel file under 50 MB
* THEN the filename will be visible within the Drag and Drop space
* AND the Save Change button will be enabled

**Scenario 3: Drag and Drop an invalid file type**
* GIVEN a Ministry Coordinator is on the file upload modal
* WHEN I drag and drop a single file that is not a pdf, Word or Excel file, or is greater than 50 MB
* THEN the user will receive an error message stating the selected file type is invalid
* AND the Save Change button will remain disabled 

**Scenario 4: Click 'Add Files' button to browse files**
* GIVEN a Ministry Coordinator is on the file upload modal
* WHEN I click the 'Add Files' button 
* THEN a window will open to browse files on my local machine

**Scenario 5: Upload a valid file type using 'Add Files'**
* GIVEN I have selected 'Add Files' from the upload modal
* WHEN I select a single pdf, Word or Excel file under 50 MB
* AND select 'Ok'
* THEN the browse files window will close
* AND the filename will be visible within the Drag and Drop space
* AND the Save Change button will be enabled

**Scenario 6: Upload an invalid file type using 'Add Files'**
* GIVEN I have selected 'Add Files' from the upload modal
* WHEN I select a file that is not a pdf, Word or Excel file, or is greater than 50 MB
* THEN the user will receive an error message stating the selected file type is invalid
* AND the Save Change button will remain disabled 

**Scenario 7: Cancel upload of a valid file type using 'Add Files'**
* GIVEN I have selected to add a single valid file type under 50 MB from the browse files window
* WHEN I select 'Cancel'
* THEN the browse files window will close
* AND no filenames will be visible within the Drag and Drop space
* AND the Save Change button will remain disabled

**Scenario 8: Cancel Back to Review Request View"**
* GIVEN a Ministry Coordinator is on the upload file modal
* WHEN I select 'Cancel'
* THEN the upload file modal will close, and the request state will remain as it was prior to opening the modal

**Scenario 9: Activate the Save Change button**
* GIVEN a Ministry Coordinator is on the upload file modal
* WHEN a valid filetype has been uploaded
* AND the Save Change button has been clicked on
* THEN the upload file modal will close, and the state will update to the state selected

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by JHarrietha-AOT** [comment]
Need to know:

- [ ] Number of files we can upload at once (1 at a time)

- [ ] File types to be able to upload (PDF, EXCEL, WORD DOC) 

- [ ] File Size Limit (NEED TO LOOK INTO IT) @arielleandrews @m-prodan

**Comment by lmullane** [comment]
As discussed, error messages are not appearing for invalid or too large files. 

Moving back to in progress.

**Comment by lmullane** [comment]
Just need to test with a valid file over 50 MB; all other scenarios have past.

**Comment by arielleandrews** [comment]
Tested Excel file over 50MB, scenario passed. All scenarios now passed.
