### ISSUE TITLE
PayBC integration

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#700]
Description
A list of the technical steps needed to complete the PayBC integration

- PayBC API Key
- PayBC reference number
- PayBC API OAuth Client ID
- PayBC API OAuth Client Secret

This is assuming FOI will be using same TEST region as BC Registries. If not, then we will need URLs too.

#### DOD
- [ ] Deloitte to advise on which environment is available
- [ ] QA performed in test with auditors
- [ ] 
- [ ] 
- [ ]

**Comment by acoard-aot** [comment]
I'm making this task as closed as the work has been completed and broken out in smaller tickets.
