### ISSUE TITLE
Research pipeline securities for webform/angular app

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#706]
#### Description
Some recommendations have been made at Oct 19 STRA with CITZ MISO to guard against vulnerabilities.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] What is the guidance from other devops on openshift?
- [ ] Determine if DAST tool, OWASP ZAP, be added to the DevOps pipeline for the application.  
- [ ] Sonar cloud for angular app (Manual or integrated into pipeline)
- [ ] Third party vulnerability scans
- [ ] 
- [ ]

**Comment by KyEggleston** [comment]
@lmullane @m-prodan - closing as this has either been addressed, or can be handled outside of this ticket (e.g., a new ticket)
