### ISSUE TITLE
Bug Fix - UX of Watcher

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#714]
Watcher font and icon to be updated to match design. Related to #503 

**Copy of Design**
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/65359345-b68b-416c-ab42-0b0e9a234728)

**Changes to be made**

- [ ] Eye icon 
- [ ] Font style of Watch/Unwatch
- [ ] Font colour of Watch/Unwatch
- [ ] Display Notifications bell again
- [ ] Expand size of dropdown user list so there's less scrolling

**Comment by KyEggleston** [comment]
Closing this as it's stale / has already been implemented.
