### ISSUE TITLE
Security Threat Assessment

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#72]
#### Description
STRA for new system

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Meet with MISO
- [x] Draft STRA
- [x] Team review
- [ ] MISO review and signoff
- [ ] ADM signoff

**Comment by lmullane** [comment]
Meeting booked for May 25th with IMB reps for privacy and STRA.

**Comment by lmullane** [comment]
Presented architecture to Security. They will be creating a framework discussion to be discussed at meeting on June 11th.

**Comment by lmullane** [comment]
STRA is saved [here.](https://teams.microsoft.com/l/file/D353F147-CAF6-4842-B49C-92E7D923FB46?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FSTRAs%20and%20PIAs%2FCITZ000816%20-%20FOI%20System%20-%20STRA%20Report%20v0.2.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be)

**Comment by abin-aot** [comment]
Please have a look into comments on https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/bcgov/foi-flow/151

**Comment by lmullane** [comment]
STRA and SOAR drafted and reviewed.

Next step should be eApprovals.
