### ISSUE TITLE
Setup Keycloak group

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#74]
Title of ticket: 

#### Description
Set up our users and the groups for those users within keycloak

#### Dependencies
A related task will be developing the permissions model (ie: different users will have different permissions levels)

#### DOD
- [x] Keycloak group for product team 
- [x] Keycloak group for intake

**Comment by mpilchar** [comment]
Groups have been created. Users are not known at this time and will be added at a later date
