### ISSUE TITLE
Set up Demo for PCT Agile Team 

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#744]
Title of ticket: Set up Demo for PCT Agile Team 

#### Description
Bethany Frei is setting up an agile project for PCT improvements. After an initial meeting, she was interested in seeing the work we've done/how we work.

#### DOD
- [ ] Set up meeting for demo
- [ ] Put together slides/content and Agenda
- [ ] Review/Approve content with PO 
- [ ] Complete Presentation

**Comment by mpilchar** [comment]
@m-prodan Is this still needed? I can set something up for january if so

**Comment by m-prodan** [comment]
Yes - thanks for the poke, let's try and set something up for then.

**Comment by mpilchar** [comment]
This has been underway for sometime and that team now attends our sprint reviews. Closing
