### ISSUE TITLE
Regression Testing FOI Request Form - Personals Flow 

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#745]
Title of ticket: Regression Testing FOI Request Form - Personals Flow 

#### Description
Need to put together a comprehensive regression testing of the personals request form in anticipation of the new payBC integration

#### DOD
- [ ] Draft regression test (see LM's completed suite for generals as reference)
- [ ] Review/approve by PO/Team
- [ ] Incorporate testing into future activities

**Comment by arielleandrews** [comment]
Closing - this was completed prior to launch
