### ISSUE TITLE
Update Colour Scheme for State Changes

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#751]
Title of ticket: Update Colour Scheme for State Changes

#### Description
Update all colours associated with State Chanes

#### DOD

Update all State Changes colours based on list of HEX Codes provided below:

- [ ] Unopened: #FAA915
- [ ] Intake in Progress: #EC7D10
- [ ] Open: #00A676
- [ ] Redirect: #1B8103
- [ ] Call for Records: #F25489
- [ ] Deduplication: #DD2255
- [ ] Fee Estimate: #A0192F
- [ ] On Hold: #808080
- [ ] Harms Assessment: #B988D3
- [ ] Consult: #9448BC
- [ ] Ministry Sign Off: #683286
- [ ] Records Review: #248BA8
- [ ] Response: #0A4454
- [ ] Close: #000000

**Comment by mpilchar** [comment]
@JHarrietha-AOT Is this still needed or can it be closed?

**Comment by JHarrietha-AOT** [comment]
@mpilchar looks like these have been updated elsewhere. Closing this ticket, thanks for flagging.
