### ISSUE TITLE
Attachment Log

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#752]
* As an Intake/Flex/IAO Analyst or Ministry Coordinator
* I want a place to review or download attachments on a request
* so that I can review relevant documentation relating to a request

**Assumptions & Scope**	
* This story covers the attachment log including how it will look, the arrangement of the files, the ability to manually add files.
* We are assuming that attachments do not contain personal information - applicant information will be in a separate area of the application

Requirements for file upload will be different. Users will be limited to a 1GB upload limit, and have minimal restrictions on file types. 

What is IN scope?
- Includes files uploaded to a FOI request through state changes, as well as manual uploads
- Includes any personal documentation attached to a request received through a web form

**NOT in Scope**
- Downloading files - separate story (#778)
- Renaming files - separate story (#779)
- Deleting Files - separate story (#780)
- Replacing Files - separate story (#782)
- Multi file upload - separate story (#783)
- Opening/previewing files - separate story (to be written)

**Acceptance Criteria**	 

- Overall design here: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Scenario 1: Left Hand Nav Panel View**
* GIVEN you are on the review request view of a request
* WHEN the left side navigation panel appears
* THEN you will see an option for "Attachments"
* AND if there are any attachments uploaded to a request
* THEN the number of attachments will appear in parentheses (ie: Attachments (2) )

**Scenario 2: Navigate to Attachment Page**
* GIVEN you are on the review request view of a request
* WHEN you click on the "attachments" panel of the left side navigation panel
* THEN you will be directed to the attachment page
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Scenario 3: Attachment Page View**
* GIVEN you have clicked on the attachments panel on the left side navigation panel
* WHEN the attachments log populates
* THEN any attachments uploaded to the file will appear in an ordered list, sorted by newest uploads first
* AND each entry will include: the user that uploaded the file, the date/time the file was uploaded, and the title of the attachment
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Scenario 4: Add an Attachment**
* GIVEN you are on the attachment page of a request
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
* WHEN you click on the "Add Attachment" button
* THEN the upload attachment modal will Open
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Scenario 5: Cancel back to Attachment Page**
* GIVEN you are on the add attachment modal from the Attachment Page
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
* WHEN you click on the cancel button
* THEN the modal will close and you will remain on the attachments page
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Scenario 6: Drag and Drop to add files**
* GIVEN you are on the add attachment modal from the Attachment Page
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
* WHEN you drag and drop a file that is less than 500 mb into the "drag and drop" space
* THEN the file name will appear when it is uploaded, and the add attachments button will be active

**Scenario 7: Add files using the Add Files Button**
* GIVEN you are on the add attachment modal from the Attachment Page
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
* WHEN you click on the "add file" button
* THEN the user will be able to select a file from their local machine to add to the upload file modal
* AND when the user selects a file and clicks "upload"
* THEN the file will appear and the "Add attachments" button will be active

**Scenario 8: Clicking On Add Attachments Button**
* GIVEN you are on the add attachment modal from the attachment page
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
* WHEN the "Add Attachments" button is active
* AND the user has clicked on the button
* THEN the modal will close, and the attachment will be added to the attachment log in the manner described in scenario 3

**Scenario 9: Clicking On Cancel Button when Attachments uploaded**
* GIVEN you are on the add attachment modal from the attachment page
* WHEN the "Add Attachments" button is active
* AND the user has clicked the cancel button
* OR closes the modal in some other way
* THEN a pop up will ask the user "Are you sure you want to cancel (x) number of attachments will NOT be uploaded"
* AND the options will be "Yes" and "Cancel"

**Scenario 10: Cancel back to Attachment Upload**
•	GIVEN the user has attempted to close the modal with an active attachment, and the pop up has prompted the user to continue
•	WHEN the user clicks on cancel
•	THEN the window will close and they will remain on the upload attachment page, with the attachment still present

**Scenario 11: “Continue” Out of Attachment Upload**
•	GIVEN the user has attempted to close the modal with an active attachment, and the pop up has prompted the user to continue
•	WHEN the user clicks on Continue
•	THEN the window and attachment upload window will close and the uploaded attachment will not be uploaded to the log

**Scenario 12: State Transition Uploads**
* GIVEN a request has changed states where a file upload has a occurred
* WHEN the file is uploaded through the state transition modal
* THEN the file will be added to the attachment log in the manner described in scenario 3

**Scenario 13: Ellipsis Options On Attachment Log for Files Added**
* GIVEN a file is in the attachment log that was not uploaded as part of a state update
* WHEN a user clicks on the ellipsis of the file on the log
* THEN the user will see options to: Download, Rename, Delete
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Scenario 14: Ellipsis Options On Attachment Log for State Update Files**
* GIVEN a file is in the attachment log that was uploaded as part of a state update
* WHEN a user clicks on the ellipsis of the file on the log
* THEN the user will see options to: Download, Rename, Replace* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727 

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
I now realize scenarios 11 and 12 were indeed different (i.e. Delete vs Replace). I've updated accordingly.

Agree with breaking these into 6 stories as proposed.

**Comment by m-prodan** [comment]
Thanks all! I'll work on breaking them up now so we can get them on the dev's radar for refinement next week

**Comment by m-prodan** [comment]
Thanks again for the feedback - this story has now been very much pared down! New stories written out seperately       * download an attachment #780 
* rename attachment #779
* Delete an attachment #780
* Replace attachment #782

Still need to write out multiple file uploads. Also wondering about opening a file - @arielleandrews and I touched on this briefly, how it might be nice to be able to preview/view a file as opposed to downloading it. I suspect it would need designs though. I think this could be a nice feature to have, but maybe something we put in a backpocket for later? Happy to write out the user story for it in the absence of designs for now.

**Comment by richard-aot** [comment]
@m-prodan @arielleandrews @JHarrietha-AOT, can user upload Attachments in "Intake in Progress" state? Or it is only available after "Open" state? Thanks.

**Comment by arielleandrews** [comment]
@richard-aot Yes to uploads in 'Intake in Progress' state. A lot of what happens during that state involves collecting documents from the applicant in order to be able to move forward with the request. Let us know if you have further questions about this!

**Comment by richard-aot** [comment]
@arielleandrews, that makes sense. Thanks for clarifying it.

**Comment by divyav-aot** [comment]
@arielleandrews @m-prodan , in #783 total number of files can be uploaded at a time is 10(100 MB each). #752 it is mentioned 500MB in Scenario 6 and 1GB in Assumptions.  Can you confirm what will be the total file size allowed. Is it 1000MB (10*100MB) or 500MB or 1 GB?

**Comment by arielleandrews** [comment]
Thanks @divyav-aot for the flag. For the purposes of MVP, I think 500MB would be plenty for the types of attachments we expect users to be uploading so I would be comfortable with that. @m-prodan your thoughts?

**Comment by mpilchar** [comment]
Awesome job on this! One thing to flag while looking at it in test - I tried uploading a couple of high-res photos (larger files). There was a 10 second delay before the spinny load wheel appeared. So it was initially unclear if it worked or not. Same result in multiple browsers.

**Comment by mpilchar** [comment]
All scenarios have passed in chrome
