### ISSUE TITLE
UX Recruitment for IAO Extensions

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#756]
Title of ticket: UX Recruitment for IAO Extensions

#### Description
Recruitment of IAO processing teams for pilot ministries, along with other IAO Processing Team Members for end of this sprint or following sprint. 

30 Minute sessions

#### DOD
- [x] Book 5-8 UX Research Sessions with IAO

**Comment by arielleandrews** [comment]
1. Peter Raskovsky, Flex Team - Mon Nov 15 1:00-1:30PM PST
2. Kimberly Kennedy, Resource Team - Mon Nov 15 2:00-2:30PM PST
3. Chantal Gibbs, Business Team - Mon Nov 15 3:00-3:30PM PST
4. Lorie McLeod, MCFD Personals Team - Tue Nov 16 2:00-2:30PM PST

**Comment by mpilchar** [comment]
Nice work @arielleandrews
