### ISSUE TITLE
IAO Assign Requests to/from Processing Team

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#761]
* As an intake/flex team analyst 
* I want to be able to assign a request to a processing team
* so that the request can continue through the FOI process

**Assumptions & Scope**	
What are the assumptions for this story?
"Group" queues for IAO processing teams include many types of users (intake, flex, etc) and are as follows:
Central Team
Business Team - process requests for Economy sector
Justice and Health Team
Social Tech Team
CFD Personals Team
Resource Team

What is IN scope?
- Group queue assignments for IAO processing teams for the PILOT (Business Team, and Social Tech Team)
- Assignments to/from processing teams from Intake/Flex teams to the Pilot teams.

What is NOT in scope?
- FOI Request Queue for processing analyst
- User assignments within those teams
- Assignments from Ministry Coordinators (separate story)
- Assignments to/from the remaining processing teams

**Acceptance Criteria**	

**Scenario 1: Intake changes a personal request to open, automatically assigning to processing team (not CFD)**
* GIVEN a request is in 'Intake In Progress'
* AND the request is a personal request
* AND the request is NOT a CFD Request
* WHEN the the Intake Analyst clicks 'Open'
* THEN a modal will open and say "IAO Assigned to > processing team (e.g. Business Team)"

**Scenario 2: Intake changes a personal request to open, automatically assigning to processing team (not CFD)**
* GIVEN the 'Open' modal is open and says "IAO Assigned to > Processing Team (e.g. Business Team)"
* WHEN the the Intake Analyst clicks 'Save Change'
* THEN the request will assigned to the processing team (e.g. Business Team)"
* AND the request will appear in the processing team's queue
* AND the request will still appear on the Intake Team queue

**Scenario 3: Intake Assign Personals Request from Open to Processing Team (not CFD)**
* GIVEN an Intake analyst has opened a request
* AND the request is a personal request
* AND the request is NOT a CFD Request
* WHEN the analyst clicks on the IAO assignment drop down
* THEN the options will include the group queues for the corresponding processing team.

**Scenario 4: Intake Assign Personals Request from Open to Processing Team (not CFD)**
* GIVEN an Intake analyst has clicked 'Assign a Request' for an open, personal request
* WHEN the Intake analyst selects one of the processing teams on the drop down menu
* THEN the selected team will be assigned
* AND the request will appear in that team's queue
* AND the request will no longer appear in the intake queue

**Scenario 5: Assign back to Intake Team from Processing Team**
* GIVEN a processing team analyst is on the review request view of a personals request
* WHEN the processing team analyst clicks on the IAO assignment dropdown
* THEN the processing team analyst will have the options: Intake Team, Social Tech Team, and Business Team

**Scenario 6: Assign Back to Intake Team from Processing Team**
* GIVEN a processing team analyst has activated the IAO assignment dropdown of a personal request
* WHEN the processing team analyst clicks on the IAO Intake Team
* THEN the IAO Intake Team will be assigned
* AND the request will appear in that team's queue
* AND the request will no longer appear in the processing team's queue

**Scenario 7: Flex Team Assign General Requests to Processing Team**
* GIVEN  a general request is in a Records Response
* WHEN the analyst clicks on the IAO assignment drop down
* THEN the options will include the group queues the appropriate processing team (e.g. Business Team)

**Scenario 8: Flex Team Assign Generals Requests to Processing Team**
* GIVEN a flex team analyst has clicked 'Assign a Request' for an assigned, general request
* WHEN the flex team's analyst selects the processing teams on the drop down menu
* AND clicks 'Save Change' 
* THEN the selected team will be assigned
* AND the request will appear in that team's queue
* AND the request will no longer appear in the flex team's queue

**Scenario 9: Assign back to Flex Team from Processing Team**
* GIVEN a processing team analyst is the review request view of a generals request
* WHEN the processing team analyst clicks on the IAO assignment dropdown
* THEN the processing team analyst will have the options: Flex Team, Social Tech Team, Intake Team and Business Team

**Scenario 10: Assign to Team from Processing Team**
* GIVEN a processing team analyst has activated the IAO assignment dropdown of a general request
* WHEN the processing team analyst clicks on an IAO Team
* THEN the selected IAO Team will be assigned
* AND the request will appear in that team's queue
* AND the request will no longer appear in the processing team's queue

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@arielleandrews @lmullane @JHarrietha-AOT - I think I've completed the processing team assignment and groups story here. What we'll need next is the FOI Request Queue for processing team. I think we may need some designs for that, and I wonder if we should consider user research for that as well?

**Comment by mpilchar** [comment]
@m-prodan and @arielleandrews - Please add a flow diagram to this one and we will review and estimate as a team during Sprint Planning Jan 18

**Comment by mpilchar** [comment]
This can be scoped down to just Processing teams involved in the Pilot launch for Release 2.1

**Comment by mpilchar** [comment]
![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/3bd9727f-ac3e-4f1e-8797-d691a1960c81) - https://miro.com/app/board/o9J_l9AKkos=/

**Comment by arielleandrews** [comment]
![image](https://user-images.githubusercontent.com/82615839/151605974-c3d111e9-cae0-4b00-b81f-d14d58190165.png)
This one might be easier to read

**Comment by sumathi-thirumani-aot** [comment]
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/92206345-69db-46d5-ae7e-5e9e58a868d4)

**Comment by sumathi-thirumani-aot** [comment]
Updated the excel for open state onwards for intake queue.

**Comment by sumathi-thirumani-aot** [comment]
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/3006f42d-f9e6-47ab-823f-6e56e855dcae)

**Comment by sumathi-thirumani-aot** [comment]
[https://app.zenhub.com/files/358004325/48e0d8b3-e311-417b-890a-072235b6539e/download](https://app.zenhub.com/files/358004325/48e0d8b3-e311-417b-890a-072235b6539e/download)

**Comment by m-prodan** [comment]
Hi Sumathi - we will respond formally tomorrow, I just want to share my edits with @arielleandrews first and discuss

**Comment by m-prodan** [comment]
Hi @sumathi-thirumani-aot - please see attached response.

One of the things Arielle and I talked about was that there may be some flexibility required for when things show up in queues, these could be perceived as the default/typical pathway of requests, but we also want something like a primary assignment to supercede these default visibility items. For example, if someone on the Intake team is helping process files - they would be assigned to a request that could go through various states like Records Review, Ministry Sign-off, response etc... 

We may have to write up a different ticket to address that, we can discuss further with a meeting if need be.

[https://app.zenhub.com/files/358004325/fdef6057-5c89-42e9-ac0e-41f14428bd30/download](https://app.zenhub.com/files/358004325/fdef6057-5c89-42e9-ac0e-41f14428bd30/download)

**Comment by sumathi-thirumani-aot** [comment]
Test Accounts:

Group: Social Tech Team
foisocialtech1@idir
foisocialtech2@idir
Foi!123

Group: Resource Team
foiresource1@idir
foiresource2@idir
Foi!123

Group: MCFD Personals Team
foimcfd1@idir
foimcfd2@idir
Foi!123

Group: Justice Health Team
foijustice1@idir
foijustice2@idir
Foi!123

Group: Central Team
foicentral1@idir
foicentral2@idir
Foi!123

Group: Business Team
foibusiness1@idir
foibusiness2@idir
Foi!123

Group: Scanning Team
foiscanning1@idir
foiscanning2@idir
Foi!123

**Comment by nkan-aot** [comment]
Just want to confirm, one of the ministries, Board Resourcing and Development Office code BRD, isn't listed in the diagram above. I assume it would fall under Resource Team?

**Comment by lmullane** [comment]
Updated AC to reflect that request is automatically assigned to the processing team when Intake changes the state of the request to open.

**Comment by lmullane** [comment]
AC was out of date. This passed as expected. Great job!
