### ISSUE TITLE
Unsaved Changes Prompt

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#762]
**Describe the bug in current situation**
Users are able to navigate away from the request details screen without a warning when there are unsaved changes

**Link bug to the User Story**
Noticed in testing of #566 however this behaviour is expected to be consistent for all personas for unsaved changes

**Impact of this bug**
Impact is high. Users are not given a warning that their changes have not been saved and will lose work with no knowledge of what has happened. 

**Chance of Occurring (high/medium/low/very low)**
High. Behaviour occurs with several changes and may not be noticed by the user.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to request details page as a Ministry user
2. Click on a Select Division and make a selection, and Select Division Stage and make a selection
3. Click on 'FOI' at the top of the left nav bar to return to the queue
4. See that user is returned to queue without a warning that there are unsaved changes

**Actual/ observed behaviour/ results**

**Expected behaviour**
When a user has made changes and not saved these changes, then the application should prompt with a warning that unsaved changes will be lost when the user tries to navigate away from the current page 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by divyav-aot** [comment]
@aparna-aot  - please test #1669

**Comment by nkan-aot** [comment]
handled as part of #1669

**Comment by JHarrietha-AOT** [comment]
Bug has been fixed. Users are prompted with a pop-up that there changes will not be saved if they try to navigate away from the form after making changes. Moving to closed
