### ISSUE TITLE
Remaining State Changes

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#765]
* As a user
* I want to change the state of the request 
* so that I can move the request along the appropriate states of the request 

**Assumptions & Scope**	
- AC is written for generic actions - state changes will follow Excel sheet: https://teams.microsoft.com/l/file/4BB4D87F-1238-4B26-AD9E-E6AD49914542?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=xlsx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FIAO%20and%20Ministry%20State%20Options.xlsx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be
- State Updates will follow the same behaviour as in previous user stories for specific state changes
- State Update options will be specific to user groups
- Some state updates will include mandatory file uploads - dependency on file upload #697
- Dev team will default this to the Flex team queue

What is IN scope?
- All remaining state changes not previously completed
- Confirming state change options in previously completed state changes follow the personas and options outlined in the Excel sheet

What is NOT in scope?
- File Upload is not in scope - covered in user story #697

**Acceptance Criteria**	

**Scenario 1: View Current State**
* GIVEN I am a user
* WHEN I am on the request details page 
* THEN the left navigation bar will display the current state 

**Scenario 2: State dropdown menu options**
* GIVEN I am on the request details page
* WHEN I click on the dropdown menu for the request state 
* THEN I will see the options that are appropriate to the current state and my user group

**Scenario 3: Select new state from dropdown menu**
* GIVEN I am on the state dropdown menu
* WHEN I select a new state
* THEN a modal will open asking to confirm the state change
* AND the modal will ask to Save Change or Cancel

**Scenario 4: Cancel state change**
* GIVEN I have selected a new state
* WHEN I click Cancel on the modal
* THEN the modal will close
* AND the request will remain in the same state
* AND the request will display in the appropriate queues in the same state

**Scenario 5: Save state change**
* GIVEN I have selected a new state
* WHEN I click Save Change on the modal
* THEN the modal will close
* AND the request will display in the new state
* AND the request will in the appropriate queues in the new state

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@arielleandrews, @m-prodan, as the spreadsheet includes all the state updates, suggest we add a status column and mark the ones already complete as 'Complete.'

And then close tickets #688 and #689. Let's keep #521 open and we can figure out if we need a date entry or not.

**Comment by mpilchar** [comment]
QA complete. All scenarios passed. Tested the following in Chrome, with spot checks in Edge: 

1. CFR to Ministry Sign off
2. Fee estimate to CFR
3. Fee estimate to Closed
4. On hold to Closed
5. Dedupe to Harms
6. Dedupe to Records Review
7. Dedupe to Closed
8. Harms to Closed
9. Harms to CFR
10. Harms to Record Review
11. Records Review to Response
12. Response to On hold
13. Response to Records Review
14. Response to Closed
