### ISSUE TITLE
Applicant download receipt

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#768]
* As an applicant
* I want a receipt of my payment to download when I successfully pay for my online FOI request
* so that I have proof of payment

**Assumptions & Scope**	
What are the assumptions for this story?

Applicants will want a copy of their receipt for tracking, reimbursement in some cases from their employer, or to ask for a refund.

We will generate a PDF on demand from the database when the applicant clicks the Download Receipt link.

What is IN scope?
Document generation. Connect with @divyav-aot on tool to use.

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Receipt link on Payment Complete Screen**
* GIVEN an applicant has successful paid through PayBC
* WHEN the applicant is redirected back to the payment complete screen
https://pay-integration-foi-request-form.apps.silver.devops.gov.bc.ca/general/payment-complete/
* THEN there is the option to download the receipt (secondary action, primary action is 'Continue')

**Scenario 2: Download Receipt**
* GIVEN the applicant is on the payment complete screen
https://pay-integration-foi-request-form.apps.silver.devops.gov.bc.ca/general/payment-complete/
* WHEN the applicant clicks 'Download Receipt'
* THEN the receipt will be generated from the database
* AND the receipt will be downloaded onto the applicants device

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
Approval of receipt template

**Validation Rules? (If yes, list here)**	

**Design**
See #650 for template.

No design for UI

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
@lmullane @m-prodan - I'm closing this - did the testing for this one get documented?
