### ISSUE TITLE
Attach payment receipt to FOI request email

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#769]
* As an Intake Analyst
* I want a payment receipt attached as a PDF to the the email I receive for the applicant's FOI request
* so that I can find the receipt in the shared Intake Inbox if the applicant requests it

**Assumptions & Scope**	
What are the assumptions for this story?

Applicants may lose their receipt and request IAO provide them a copy.

The Angular web app already sends attachments to the Inbox for authorizations, so we can reuse this functionality.
What is IN scope?

What is NOT in scope?
Downloading receipts is in story #768, which will also cover document generation

**Acceptance Criteria**	

**Scenario 1: Send payment receipt**
* GIVEN a payment is successfully completed for a general request
* WHEN the email is sent for a general request to the Intake inbox 
* THEN a payment receipt will be attached as a PDF to the email

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
Template design is waiting for approval - see #650 

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@jadmsaadaot - same behaviour as with other story - I will move both back to review
