### ISSUE TITLE
Edit request dates

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#77]
* As an intake analyst
* I want to be able to edit the start date, received date and date range of a request
* so that if the request had all the required information when it was submitted I can make the submission date the start date and I can update the date range if the applicant agrees to narrow his or her request

**Assumptions & Scope**	
What are the assumptions for this story?
Intake analsyts need to be able to edit the start date for a request.

For requests not received through the webform the Received Date should be editable.

Once the request is Closed dates are no longer editable.

What is in and not in scope?
Only includes editing date (out of scope: time). Other scenarios are in ticket 21.

**Acceptance Criteria**	

**Scenario 1: Edit Date 1**
* GIVEN the analyst is on a request: 
https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957829
* WHEN the analyst clicks the calendar icon next to the Start Date or Received Date (Due Date is greyed out an not editable)
* THEN the calender view will open
* https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957829
* AND the default date will be the 'Received Date' (received after 4:30 PM PST the submission date will be logged as the next business day - should be handled by web form logic)
* AND the analyst cannot select a date before the 'Received Date'

**Scenario 2: Edit  Date 2**
* GIVEN the analyst has opened the calendar for the Start Date, Received Date or Date Range (Start Date, End Date)
* https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957829
* WHEN the analyst clicks on a date in the calendar (standard material UI function)
* THEN that date will be selected

**Scenario 3: Edit Date Range Start Date 3**
* GIVEN the analyst has selected a date
* WHEN the analyst clicks 'anywhere on the screen outside the calendar
* THEN the calender will closed
* AND the selected date will be displayed
* AND the selected date will be the new received date, start date or date range (start date, open date) for the request

**Scenario 4: Edit Date Range Start Date**
* GIVEN the analyst is on a request received via the webform
* https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957829
* WHEN the analyst clicks 'Date Range Start Date' calendar icon
* THEN the calender will open
*https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957829
* AND the date selected will be auto-populated from the webform

**Scenario 5: Edit Date Range End Date**
* GIVEN the analyst is on a request received via the webform
* https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957829
* WHEN the analyst clicks 'Date Range End Date' calendar icon
* THEN the calender will open
* https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957829
* AND the date selected will be auto-populated from the webform
* AND the dates before the Start Date will be greyed out

**Scenario 6: Edit Date Range End Date 2**
* GIVEN the analyst has opened the calendar
*https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957829
* WHEN the analyst clicks a date before the 'Start Date' or a date in the future
* THEN date will not be able to be selected
* AND a message will appear that you cannot select a date before the start date or in the future

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
See design links in Scenarios.

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.     [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@m-prodan, do intake analysts ever need to edit the date range for the request? cc @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
Calendar in Material UI - https://material-ui.com/components/pickers/

UI is based off the option, birthday as it allows for easy navigation between years

**Comment by lmullane** [comment]
@divyav-aot, Looks like Scenario 5 and 6 haven't been met. The user should not be able to select an 'End Date' before the 'Start Date,' but when I tested this in Chrome and Brave I was able to do this.
