### ISSUE TITLE
Edit a Comment

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#777]
* As a user (all user types)
* I want the ability to edit comments I have posted  
* so that I can correct or update my own posted comments 

**Assumptions & Scope**	
What are the assumptions for this story?
- All users will have the ability to edit their own comments
- Users cannot edit another user's comments
- Users cannot edit system generated comments

What is IN scope?
- Editing a comment (parent)
- Editing a reply to a comment (child)

What is NOT in scope?
- Posting a comment, Replying to a comment (covered in separate user stories)
- Tagging another user in a comment (covered in separate user story)

**Acceptance Criteria**	

**Scenario 1: Ellipsis active for User's own comments**
* GIVEN I am on the Comments page
* WHEN I have posted a comment 
* THEN the ellipsis on the top right of the comment will be coloured blue and will be active 

**Scenario 2: Ellipsis options**
* GIVEN I am a user on the Comments tab of a request
* WHEN I click on the ellipsis for my comment 
* THEN a selection window will appear
* AND the options will be 'Edit' and 'Delete' 

**Scenario 3: Select Edit**
* GIVEN I have clicked on the ellipsis for my comment
* WHEN I click 'Edit'
* THEN the selection window will close
* AND my comment will turn to an editable text field populated with the existing comment
* AND a paper airplane icon and X will be at the end of the field

**Scenario 4: Save edited comment**
* GIVEN I have edited the comment text
* WHEN I click the paper airplane icon at the end of the text field
* THEN the edited comment will be saved
* AND the comment will remain in its original chronological placement

**Scenario 5: Cancel editing comment**
* GIVEN I have edited the comment text
* WHEN I click on the X at the end of the text field
* THEN the edited comment will not be saved
* AND the original comment text will be restored
* AND the comment will remain in its original chronological placement

**Scenario 6: Ellipsis  not active for other user's comments**
* GIVEN I am on the Comments page
* WHEN I am viewing a comment posted by another user
* THEN the ellipsis on the top right of the comment will be coloured grey and will be inactive 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
- Requires posting a comment and posting a reply

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, just confirming that to post the comment the icon the user clicks is a paper airplane, correct? cc @m-prodan

**Comment by JHarrietha-AOT** [comment]
@lmullane In the existing designs it is an airplane. This is again something that should change based on the library chosen by the devs

**Comment by m-prodan** [comment]
I think it's good to be flexible if we are going with a library just to keep it simple. I'm good with the AC for this story

**Comment by lmullane** [comment]
Thanks, I've updated the AC accordingly.

**Comment by mpilchar** [comment]
Functions as expected except Scenario 4 - Currently when a comment is edited, there is no "edited" text that appears indicating that it has been edited. "

**Comment by mpilchar** [comment]
@abin-aot @lmullane - The last AC in Scenario 4 is not met. Please determine if it's needed/DOD can be revised or not

**Comment by abin-aot** [comment]
@lmullane @mpilchar  - As I mentioned on the first day DEMO - Definition of "Viewed" cannot be easily meet, unless the user interacts with the comment. This was indicated earlier. If we are referring to  MS Teams - that is a Desktop application and only active chat room/chats/IM apps  will only make sense with this feature. Open to discussions

**Comment by mpilchar** [comment]
@abin-aot Sorry I missed that. I have revised A/C and moved to closed. cc: @lmullane
