### ISSUE TITLE
Attachment Log - Rename an Attachment

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#779]
* As an Intake/Flex/IAO Analyst or Ministry Coordinator
* I want to be able to rename attachments I upload
* so that it can be better understood what the attachment is

**Assumptions & Scope**	
What are the assumptions for this story?
This covers the ability to rename an attachment uploaded to the attachment log (#752)

What is IN scope?
This focuses only on renaming attachments through the attachment log

**Acceptance Criteria**	

**Scenario 1: Rename an attachment**
•	GIVEN the ellipsis of a file on the attachment log has been activated
•	https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
•	WHEN rename is selected
•	THEN a modal will open, with the original file name in a text space, and a save and cancel button
•	https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
•	AND the User will be able to edit the name in the text, using valid filename characters

**Scenario 2: Cancel back to Attachment Log from Rename**
•	GIVEN you are on the rename attachment modal
•	WHEN the cancel button is pressed
•	THEN the modal will close and the user will remain on the attachment log
•	https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Scenario 3: Rename Attachment - Save with Valid characters**
•	GIVEN you are on the rename attachment modal
•	WHEN changes have been made to the file name
•	AND the changes are valid characters for a file path
•	AND the save button has been clicked
•	THEN the modal will close, and the user will remain on the attachment log
•	https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
•	AND the name of the attachment will be updated

**Scenario 4: Rename Attachment - Save with invalid characters**
•	GIVEN you are on the rename attachment modal
•	WHEN changes have been made to the file name
•	AND the changes include invalid characters for a file path
•	AND the save button has been clicked
•	THEN an error message will appear advising the user it can not be saved due to invalid characters

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
#752 - Attachment log needs to be created first

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
@abin-aot @VineetBala-AOT - I am testing scenario 3 "testing valid characters" right now. Double checking if there are any limitations to file naming for future database(s)? The current settings pass based on / : * ? " < > |  but I would also have expected the following to be invalid: . - & % $ etc. cc: @lmullane

**Comment by mpilchar** [comment]
One scenario not covered under the A/C but that I tested was what happens after changing a file name, and then selecting cancel on the modal. A textbox comes up that says "are you sure you want to leave". I find this to be confusing...makes me think of leaving the page and not just cancelling out of the modal cc @JHarrietha-AOT for a second opinion  ![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/223ef254-65cf-46e0-a97a-64b18249f4aa)

**Comment by mpilchar** [comment]
Closing this based on a) Confirmation that the allowable symbols I mentioned above are compatible and b) acknowledging that I can create an improvement ticket later on if the team determines the "leave page" modal creates confusion
