### ISSUE TITLE
Intake Queue prototype for MVP

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#78]
Title of ticket: 

#### Description
Prototype/design for development of intake Queue for next Sprint. Designs will meet DOR for refinement on Thursday and Friday.

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Remove non MVP features as discussed (i.e. captured in Miro board)
- [x] Add designs for drop down functionality from Material UI
- [x] Add designs for date pickers from Material UI
- [x] Add design for ministry selector
- [x] To single page view of request add Applicant Type selector
- [x] To single page view make primary action 'Open request', secondary 'Reject Request'

**Comment by JHarrietha-AOT** [comment]
Changes shown here: https://miro.com/app/board/o9J_lGy2kgo=/

**Comment by lmullane** [comment]
@JHarrietha-AOT, looks good in Miro. I've moved one sticky from start date in date range to start date of submission and made a few comments. Great work!

**Comment by JHarrietha-AOT** [comment]
@m-prodan made the few little changes we talked about after meeting with Natalie. Could you do a review. If it looks good the issue can be closed

https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/632044886

**Comment by m-prodan** [comment]
It looks good to me @JHarrietha-AOT - I'll close the ticket with this comment.
