### ISSUE TITLE
Attachment Log - Delete an Attachment

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#780]
* As an Intake/Flex/FOI Analyst or Ministry Coordinator
* I want to be able to delete an attachment that has been uploaded to the attachment log
* so that I can correct any duplicate or irrelevant uploads to a request

**Assumptions & Scope**	
What are the assumptions for this story?
This covers the delete functionality for the attachment log

**Acceptance Criteria**	

**Scenario 1: Delete an Attachment**
•	GIVEN the ellipsis is open for a file that was not uploaded during a state update
•	https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
•	WHEN "Delete" has been selected
•	THEN a modal will pop out, asking: "Are you sure you want to delete the attachment?", with a button to continue and cancel
•	https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Scenario 2: Cancel back to Attachment Log from Delete**
•	GIVEN you are on the delete attachment modal
•	WHEN the cancel button is pressed
•	THEN the modal will close and the user will remain on the attachment log

**Scenario 3: Confirm Delete Attachment**
•	GIVEN you are on the delete attachment modal
•	WHEN the Continue button is pressed
•	THEN the modal will close and the user will remain on the attachment log
•	https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
•	AND the attachment will be removed from the list

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
QA completed, all scenarios passed in Chrome, Edge and Firefox.

Acceptance Criteria does not specify any role based permissions – may need to restrict Ministry and IAO uploads to each respective user group in future user story.
