### ISSUE TITLE
Delete a Comment

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#781]
* As a user (all user types)
* I want the ability to delete comments I have posted 
* so that I can remove comments posted in error 

**Assumptions & Scope**	
What are the assumptions for this story?

- All users will have the ability to delete their own comments
- Users cannot delete another user's comments
- Users cannot delete system generated comments
- Users cannot delete their own parent comments if replies have been made on it. Exception: Super users/admins can delete all comments, including parent threads

What is IN scope?
- Deleting a comment (parent)
- Deleting a reply to a comment (child)

What is NOT in scope?
- Ellipsis options for user's own comments covered in #777

**Acceptance Criteria**	

**Scenario 1: Select Delete from ellipsis options**
* GIVEN I have clicked on the ellipsis for my own comment
* WHEN I click 'Delete' 
* THEN a modal will appear asking the user if they are sure they want to delete this comment
* AND the options will be 'Ok' and 'Cancel' 

**Scenario 2: Select Ok to Delete comment**
* GIVEN I am on the modal to confirm I want to delete my comment
* WHEN I click 'Ok' 
* THEN the modal will close
* AND the comment will be deleted from the comments page
* AND the rest of the posted comments will remain in the original chronological placement

**Scenario 3: Select Cancel to Delete comment**
* GIVEN I am on the modal to confirm I want to delete my comment
* WHEN I click 'Cancel'
* THEN the modal will close
* AND the original comment will be retained

**Scenario 4: Cannot Delete a Parent comment if there are replies**
* GIVEN a parent comment has replies
* WHEN the user who has made the Parent Comment clicks the ellipsis
* THEN a modal will open
* AND the options will be 'Delete' will be grey and inactive with a "i" tooltip

**Scenario 5: Click tooltip when Delete a Parent comment if there are replies**
* GIVEN a parent comment has replies
* AND the user who made the comment has clicked on the ellipsis
* WHEN the user clicks the tooltip
* THEN a message will open that says "Parent comments with a reply cannot be deleted. You may edit the comment.'

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, @m-prodan, this story looks good to me. 

Please advise if you see any issues with the AC.

cc @abin-aot

**Comment by JHarrietha-AOT** [comment]
This issue looks good to me!

**Comment by mpilchar** [comment]
Works as expected except after selecting the ellipses a pop out appears with "edit and delete". When I select delete, the modal appears, if I click "cancel", the pop out that appeared initially remains in place. It should disappear. Have discussed this change with @abin-aot

**Comment by mpilchar** [comment]
Rechecked and this passed! Thanks for the changes @abin-aot
