### ISSUE TITLE
Attachment Log - Replace Attachment

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#782]
* As an Intake/Flex/Ministry 
* I want to be able to replace an attachment
* so that I can ensure the correct record is uploaded for a state change

**Assumptions & Scope**	
This allows for the ability for a user to swap an attachment during specified state changes where uploading a record is required. Users should not be able to delete state change attachments, only replace them. 

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Replace Attachment**
•	GIVEN the ellipsis is opened for a file that was uploaded during a state update
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
•	WHEN "Replace" has been selected
•	THEN the Replace attachment modal will pop out
•	https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
•	AND the text will include the state transition from which the attachment originated
•	AND the continue button will not be active

**Scenario 2: Replace Attachment - Cancel Back to Attachment log**
•	GIVEN you are on the replace attachment modal
•	WHEN the cancel button is pressed
•	THEN the modal will close and the user will return to the attachment log

**Scenario 3: Replace Attachment - Drag and Drop to add files**
•	GIVEN you are on the replace attachment modal from the Attachment Page
•	WHEN you drag and drop a file that is less than 50 mb into the "drag and drop" space
•	AND that file is one of the valid filetypes from state transitions (excel, word, PDF)
•	THEN the file name will appear when it is uploaded, and the continue button will be active

**Scenario 4: Replace Attachment - Add files using the Add File Button**
•	GIVEN you are on the replace attachment modal from the Attachment Page
•	WHEN you click on the "add file" button
•	THEN the user will be able to select a valid file (less than 50 mb, word, PDF or excel only) from their local machine to add to the upload file modal
•	AND when the user selects a file and clicks "upload"
•	THEN the file will appear in the modal and the "Continue" button will be active

**Scenario 5: Replace Attachment - Clicking On Continue Button**
•	GIVEN the continue button has become active on the "Replace attachment" modal
•	WHEN the Continue button has been clicken
•	THEN the modal will close, and the attachment will be added to the attachment log in the manner described in scenario 3

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
QA completed, all scenarios passed in Chrome, Edge and Firefox.
