### ISSUE TITLE
Navigating to Comments section of request

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#784]
* As a FOI Analyst
* I want to navigate to Comments easily
* so that I can view additional information about the request

**Assumptions & Scope**	
* Comments should be able to me made in an unopened request and carried through to the request even after assigned to multiple ministries

What is IN scope?
Left navigation item and the Comments page.

What is NOT in scope?
Posting, editing and deleting comments and notifications of unread comments.d

**Acceptance Criteria**	

**Scenario 1: View Comments by selecting the Comments tab**
GIVEN I am on the Request information page
WHEN I click on "Comments" in the left nav bar
THEN the the Comments page will be opened
AND Comments will be listed with the newest (date and time) Parent Comment on the top and the oldest Parent Comment (date and time) on the bottom

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Just confirming with this particular user story - believe the intent is to have comments displayed in two seperate places, correct? At the bottom of the review request page, and a standalone page accessed through the left side nav bar? If so, this appears to cover it - we would just need designs added @JHarrietha-AOT

**Comment by m-prodan** [comment]
Also the check re: workflows and states, I don't think there should be any changes required to those for comments

**Comment by JHarrietha-AOT** [comment]
@m-prodan I don't think it is nessecary to have the comments display in two sections when they can be navigated to with one click in the left nav. My option would be just the left nav, happy to hear your thoughts @m-prodan @lmullane

**Comment by lmullane** [comment]
Agreed that just the left nav is all that is needed. 

I will remove the first scenario. @JHarrietha-AOT, do we have design for this yet?

**Comment by lmullane** [comment]
Updated the scenarios to include the ordering of the comments on the Comments Page (newest Parent on top).

**Comment by JHarrietha-AOT** [comment]
@lmullane these are the designs that are in progress and could have further changes after the research is completed as some designs may be altered based on the library chosen by the devs

**Comment by mpilchar** [comment]
@lmullane I left order of comments out of this AC as I figured it would be better included as part of Sorting/Filtering of comments, which Arielle and I didn't feel we had enough information to write yet. Breakdown of stories is here: https://miro.com/app/board/o9J_lE1ZlVA=/ Let us know if you'd still like to keep it as part of this AC or not

**Comment by abin-aot** [comment]
@lmullane @mpilchar Scenario 2, Show more comments itself is different user story , Right? - Refer #791

**Comment by mpilchar** [comment]
@abin-aot Good catch - I am removing Scenario #2 since it is covered in Scenario 4 of #791

**Comment by mpilchar** [comment]
QA testing complete, functions as expected
