### ISSUE TITLE
Navigating away from a draft comment

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#785]
* As a FOI analyst
* I want to notifications if I navigate away from a draft comment
* so that my changes will not be lost

**Assumptions & Scope**	
What are the assumptions for this story?
* Comment features are written like MS Teams
* I have left out the formatting bar beneath the comments as a) I don't know if we need it, for MVP, and b) I assume this will be scoped into whatever Material UI components get used

What is IN scope?
* Comment tab
* deleting a draft comment, leaving the page

What is NOT in scope?
* Replying (starting a child comment), deleted a submitted comment
*  comments section of request page

**Acceptance Criteria**	

**Scenario 1: Clicking elsewhere on the page after I've started typing in the conversation window**
* GIVEN ... I am on the comments tab and have clicked in the conversation window to begin a new comment
* AND ... have typed characters within the conversation window
* WHEN ... I click on any blank space outside of the conversation window
* THEN ... What I've typed will remain in the window but the cursor will disappear

**Scenario 2: Clicking elsewhere on the page after I've clicked in the conversation window, but before I've typed anything**
* GIVEN ... I am on the comments tab and have clicked in the conversation window to begin a new comment, BUT have not yet typed anything
* WHEN ... I click on any blank space outside of the conversation window
* THEN ... The conversation window remains but the cursor will disappear

**Scenario 3: Deleting text that I have typed, before any submit takes place**
* GIVEN ... I am on the comments tab and have begun typing text within the conversation window
* WHEN ... I delete the text entirely
*THEN ... the conversation window remains and "add a new note" text reappears
*AND ... If I click elsewhere on the page
*THEN ... the conversation window disappears and is replace with the "New conversation" button

**Scenario 4: Navigating away from the browser**
* GIVEN ... I am on the comments tab and have begun typing a new comment
* WHEN ... I try to leave the page
* THEN ... A modal will appear confirming if I want to leave and that my changes will be lost, 
* AND ... If I click "yes"
* THEN ... The comment will not be saved 

**Scenario 5: Navigating away from the browser**
* GIVEN ... I am on the comments tab and have begun typing a new comment
* WHEN ... I try to leave the page
* THEN ... A modal will appear confirming if I want to leave and that my changes will be lost, 
* AND ... If I click "no"
* THEN ... What I've typed will remain in the conversation window and I can resume typing

**Scenario 6: Clicking "x" on a reply
* GIVEN ... I am replying to a parent comment and have typed text in the reply window but have not submitted the comment
* WHEN ... I click the "x" to close the reply
* THEN ... a modal appears providing a warning that changes will be lost  
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
This looks good to me. 

@JHarrietha-AOT and @m-prodan, let me know if we need any changes.

**Comment by JHarrietha-AOT** [comment]
@lmullane based off of this mornings conversation should the modal that appears when navigating away be a separate user story?

**Comment by lmullane** [comment]
Good point, @JHarrietha-AOT.

I was thinking it there would be a few user stories for the warning of lost changes, but we could put it in one.

**Comment by m-prodan** [comment]
From refinement: remove clicking away, and warning will appear if you click x with text

**Comment by mpilchar** [comment]
All scenarios pass and I will close this ticket. However, I am going to create a bug with a recommended revision for the text that appears in the modal when closing a draft reply comment. cc: @abin-aot
