### ISSUE TITLE
Replying to Comments

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#786]
* As a FOI Analyst
* I want to leave replies to comments 
* so that I can provide related input to the parent comment

**Assumptions & Scope**	
What are the assumptions for this story?
These stories are based on the commenting functionality found within MS Teams
Same restrictions for reply as with posting in #584 (character limits will be same for reply)

What is IN scope?
Replying to a comment

What is NOT in scope?
* Starting a new comment thread, editing a comment, etc
* I have left out the formatting bar beneath the comments as a) I don't know if we need it, for MVP, and b) I assume this will be scoped into whatever Material UI components get used

**Acceptance Criteria**	

**Scenario 1: Replying to a parent comment**
* GIVEN ... I am on the Comments tab and viewing a parent comment
* WHEN ... I click on the "Reply" link beneath the parent comment
* THEN ... a conversation window appears with "Reply" text and I have the ability to type within it

**Scenario 2: Replying to a child comment 1**
* GIVEN ... I am on the Comments tab and viewing a comment thread
* WHEN  there has been a reply
* THEN the Reply' link appears beneath the last reply (not the parent comment)

**Scenario 3: Replying to a child comment 2**
* GIVEN ... I am on the Comments tab and viewing a comment thread
* AND there has been a reply
* WHEN ... I click on the "Reply" link beneath the previous child comment
* THEN ... the view stays the same, but a conversation window appears below the child comment with "Reply" text and I have the ability to type within it

**Scenario 4: Submitting a reply**
* GIVEN ... I am on the Comments tab and replying to a comment
* WHEN ... I click on the "send" paper airplane icon
* THEN ... the comment is posted with a Reply link underneath

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
Creating a separate user story to hide and view additional replies.

**Comment by JHarrietha-AOT** [comment]
Just want to post her for whoever is testing the UX of this needs to be updated to closer match the desired UI/UX

Currently:
![Screen Shot 2021-11-17 at 12.15.48 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/07f85be3-8c23-44b1-a0ff-6fbb4d9de064)

UX:
![Screen Shot 2021-11-17 at 12.17.32 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/59c7bae1-a111-4df8-b511-903b9e9b7654)

As discussed based on the library we are using there are some things that are too difficult from the design. 

Changes I would recommend:
- Move 'X' either inline with text editor or inside box
- Remove blur from background
- Make reply full width with outline - like design
- Make Airplane icon inline with Character counter

**Comment by mpilchar** [comment]
@lmullane can you please test if the bold text format in Comments is showing up for you? It's fine for me (PC) but not for Jackie, who is viewing on a mac. cc: @JHarrietha-AOT

**Comment by mpilchar** [comment]
Functions as expected. Bugs #869 and written up to address some improvements.

**Comment by lmullane** [comment]
@mpilchar, I can confirm that the bold did not work on my Mac. cc @JHarrietha-AOT
