### ISSUE TITLE
Tagging another user in a request comment

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#787]
* As an FOI analyst
* I want to tag another user in a request comment
* so that they know to review information included in the request

**Assumptions & Scope**	
What are the assumptions for this story?
Display only name, not ministry or idir info

What is IN scope?
Tagging users only, not team.
IAO can tag all users x-gov. MInistries can tag anyone within their ministry and any IAO user.

What is NOT in scope?
Notifications when a user is tagged

**Acceptance Criteria**	

**Scenario 1: Generating a list of users when tagging**
* GIVEN ... I am on the comments tab and have clicked in the conversation window
* WHEN ... I type the "@" symbol
* THEN ... a list will appear above where I'm typing with system users listed alphabetically from A to Z 
* AND only the first 5 users full names would appear (e.g. Andrews, Arielle)

**Scenario 2: Generating a list of users when tagging**
* GIVEN ... I am on the comments tab and have clicked in the conversation window
* AND  I have typed the "@" symbol
* WHEN I type a letter (e.g. M)
* THEN ... a list will appear above with all the users who have a FIRST NAME or LAST NAME beginning with that letter (e.g. M)
* AND only the first 5 users full names would appear (e.g. Andrews, Arielle)

**Scenario 3: Generating a list of users when tagging**
* GIVEN ... I am on the comments tab and have clicked in the conversation window
* AND  I have typed the "@" symbol
* WHEN I type more letters (e.g.ma...)
* THEN ... a list will filter by user's who have that letter sequence in their FIRST NAME or LAST NAME 
* AND if more than one user has that letter sequence, only the first 5 users full names would appear (e.g. Prodan, Matt)

**Scenario 4: Selecting a user when tagging**
* GIVEN ... I am on the Comments tab and trying to tag a user in a comment
* AND a user's name is listed
* WHEN .I click the user's name I am trying to tag
* THEN ... the name will appear in blue coloured text within the conversation window and I can continue typing
* AND the list will close

**Scenario 5: Submitting a comment with a tagged user(s)**
* GIVEN ... I am on the Comments tab and have selected a user to tag
* WHEN ... I click on the "Submit" icon
* THEN ... the tagged name will remain highlighted in a different colour text within the comment history

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
- Notifications 

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
cc: @lmullane I've indicated notifications as a dependency to this story (see AC #3)

**Comment by m-prodan** [comment]
Do we need to add to scenario 1 - the functionality of the list continuing to filter as you type out a name? (Ie: when I use the tagging feature in zenhub, as I type out a name it filters closer and closer to the user I want).... I assume the library we choose will have this kind of thing baked into it, but just thought I would flag it

**Comment by lmullane** [comment]
@m-prodan, I think so. I've added two additional scenarios based on how Team's functions for your review. cc @JHarrietha-AOT 

I expect the dev team will want the notification in Scenario 4 in a separate story.

**Comment by JHarrietha-AOT** [comment]
@lmullane I would agree that notifications for when a user is tagged in a comment should be a different story,

@m-prodan Agreed, I think listing the first three usernames would be enough and there should be a story around the idea that this list is refreshed with each character a user adds

**Comment by lmullane** [comment]
I've removed the notification clause in the last scenario and added the dynamic filtering as additional characters are typed in.

**Comment by m-prodan** [comment]
I included tagging users in #855 - events that trigger notifications, so no need to write up a new story. If the devs want them separated out we can do so.

**Comment by mpilchar** [comment]
@JHarrietha-AOT This meets all testing criteria. Since there was no prototype to reference with this one, are you happy with the way the text displays for AC#5?

**Comment by JHarrietha-AOT** [comment]
@mpilchar It passes the AC I think it would be a tech debt/bug ticket for the design changes that I would make.
