### ISSUE TITLE
Hide and show replies to a comment

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#791]
* As a ministry coordinator or IAO analyst
* I want comments to be able to hide or show comments when there is more than 3
* so that I can see the comments posted.

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Hide comments**
* GIVEN ... I am on the Comments tab 
* WHEN there are more than 3 replies under a Parent comment
* THEN only the 2 most recent Child comments and the original Parent comment will appear
* AND all other comments will be hidden
* AND there will be a link to 'Show More Comments'

*Scenario 2: Showmore comments**
* GIVEN ... I am on the Comments tab and viewing a comment thread and the thread of comments is collapsed
* WHEN ... I click "show more comments" link  that appears between the parent comment and most recent child comment
* THEN ... the comment thread expands to show all child comments in chronological order, from oldest on top to newest on bottom

**Scenario 3: Collapse comments**
* GIVEN ... I am on the Comments tab and viewing a comment thread and the thread of comments is expanded
* WHEN ... I click "Collapse all" link  that appears between the parent comment and top listed child comment
* THEN ... the comment thread collapses and just the most recently posted child comment will display

**Scenario 4: Number of comments displayed restricted by character limit**
GIVEN I am on the Request information page
WHEN there are comments and replies that collectively are more than xxxx characters
THEN additional comments will be hidden
AND there will be a 'Show more comments' at the bottom of the screen

**Scenario 5: Click 'Show more comments' **
GIVEN I am on the Request information page
WHEN the user clicks 'Show more comments'
THEN the next x comments will be shown

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, @m-prodan, Molly wrote this pretty much identical to how MS teams works. Only change is I put to show the last 2 replies rather than just 1 reply.

I think it's likely they may not have seen recent messages. 

Thoughts?

**Comment by m-prodan** [comment]
I like the idea of showing a little more than just the last comment - no concerns from me.

**Comment by abin-aot** [comment]
@lmullane @JHarrietha-AOT @m-prodan - for scenario 4 ,   show more for entire comment by characters - Can I do this with Responsively, if possible? Because the display is as per screen size right? bigger screen size can have more main comments displayed , comparing with smaller screens.  For Replies - I can adhere to what is there is scenario 1, 2 . Shall I connect once I do the change?

**Comment by mpilchar** [comment]
@abin-aot should scenario 4 read "Given I am on the Comments tab within a request"? Was there a number of characters determined? Is it a "pass" so long as at some point the "Show more Comments" button appears after a certain number/amount of comments?
