### ISSUE TITLE
Check for Excel and iCalendar files

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#8]
As a Flex team analyst, I want a Excel and iCalendar files automatically pulled from the LAN folder so that I do not have to manually upload the files for processing

**Acceptance Criteria**	

**Scenario 1: Scan for folders created after xx date**
* GIVEN the date of a folder is created after xx date
* WHEN the file watcher polls the LAN
* THEN the file watcher will poll folders created after xx date
* AND the file watcher will poll every 5 minutes

**Scenario 2: Pull Excel and iCalendar files**
* GIVEN the file watcher is scanning folders created after the xx date
* WHEN the watcher finds an Excel or iCalender file extensions
* THEN the file will be pulled in for processing
* AND output will be saved in an output folder with a log file attached

**Scenario 3: xxxxxx**
...

**Dependencies?**

If we require a change of state in the integrated application (i.e. ministry coordinators marks the Call for Record ready for processing) then we need the integrated application.

How might we find another solution so we can deliver a solution for the problematic file types without waiting?

- Test LAN - for testing.

- OS DMZ across firewall to LAN

**Validation Rules? (If yes, list here)**	

**Design**
No UI, no design required.

**Definition of Ready**

1. [x] Is there a well articulated User Story?
2. [x] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [x] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [x] Does this User Story needs stakeholder approval?
6. [x] Design / Solution accepted by Product Owner
7. [x] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.     [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
From QA perspective, I can conclude that each subfolder behaves as expected. When new folders are created in the "call for records'' folder of a Ministry - file watcher has been able to detect and convert xls and ics files into the appropriate subfolders as described in the acceptance criteria.
