### ISSUE TITLE
Edit ministry selected on unopened request

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#81]
* As an analyst
* I want to be able to edit the ministries selected for a request
* so that I can ensure the right ministry(s) receives the Call for Records

**Assumptions & Scope**	
What are the assumptions for this story?

What is in and not in scope?

**Acceptance Criteria**	

**Scenario 1: Ministry's selected**
* GIVEN the analyst is on a Unopened equest:
https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957825
* WHEN the analyst views the ministry(s) selected
* THEN the ministries selected with the checkboxes be be auto-populated from the applicant Request Form
* AND the selected ministry checkbox will be green with a white checkmark

**Scenario 2: Select Ministry**
* GIVEN the analyst is on a request:
https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957825
* WHEN the analyst clicks the check box next to a ministry
* THEN the ministry(s) will be selected (more than 1 ministry can be selected)
* AND the selected ministry checkbox will turn green with a white checkmark

**Scenario 3: Unselect Ministry**
* GIVEN the analyst is on a request:
https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA/631957825
* WHEN the analyst clicks the check box next to an already selected ministry
* THEN the ministry will be unselected
* AND the selected ministry checkbox will be empty (no colour or checkmark)

**Scenario 4: xxxxxx**
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
Not a dynamic form. At least one ministry must be selected

For action: Add a hover-over option to spell out the full name of each ministry?

For decision: Is there the ability to save this form / save a draft?

**Comment by lmullane** [comment]
Passed QA.
