### ISSUE TITLE
Inconsistency observed on modal state change descriptive message 

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#817]
**Description:** 
Discussed at stand up Nov 3/21.
Modal headings should be consistent across states

**DOD:**
- [ ] Update modal headers throughout application to be consistent with each other

![MicrosoftTeams-image (3).png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/bd5d1a7d-c325-4565-bfa3-b674dcc9752d)
![MicrosoftTeams-image (2).png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/b5591039-2567-4bd3-98ea-4e912a79a2c0)

**Comment by mpilchar** [comment]
@sumathi-thirumani-aot I updated with the screenshots you provided yesterday
