### ISSUE TITLE
Content for Fee Confirmation Email

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#819]
Title of ticket: Content for Fee Confirmation Email

#### Description
Need Content for email to be sent to applicant upon submission

#### DOD
- [x] Draft Content
- [x] Share with UX for designs
- [x] PO Approval
- [x] IAO Approval (Senior Leaders, CK + KG, and RH)

**Comment by m-prodan** [comment]
Sent to Cindy and Kris today for senior mgmt approval - will send to RH for final approval once received.

**Comment by mpilchar** [comment]
The development for this is now in test. @lmullane will provide @jadmsaadaot the content that went to managers for review so that it can be updated in it's most current version for demo tomorrow

**Comment by m-prodan** [comment]
Closing this as we completed this a little bit ago!
