### ISSUE TITLE
Attach receipt to applicant email

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#828]
* As an applicant who has submitted a general FOI request
* I want a receipt attached to the confirmation email
* so that I can use the receipt for billing purposes

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?
Attaching the receipt to the applicant's email

What is NOT in scope?
Sending the email is covered in #818
Design of receipt

**Acceptance Criteria**	

*Scenario 1: Attach receipt to confirmation email**
* GIVEN  the user is on the PayBC credit card screen     
* AND the user has entered a valid email address
* AND the user enters a valid credit card number, expiry and CVD       
* WHEN the user click 'Pay'     
* THEN the email sent to the applicant's email will include an attached receipt

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@jadmsaadaot 
Receipt is attached - but I found issues with the format when "Social Development and Poverty Reduction" is selected - it appears as a sub-org of Emergency Management BC, when it should be it's own line item.

This bug happens when it is picked individually and as a part of multiple ministry selections. All others appear OK! 

[https://app.zenhub.com/files/358004325/bf5e6d72-5157-4fd7-9d6c-3cf5057cf9ad/download](https://app.zenhub.com/files/358004325/bf5e6d72-5157-4fd7-9d6c-3cf5057cf9ad/download)

cc @lmullane

**Comment by m-prodan** [comment]
I should also mention that this behavior also occurs when you download the receipt.
