### ISSUE TITLE
Re-Open A Request

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#832]
* As an IAO User
* I want the countdowns and due dates of a request I have "re-opened" from closed to be updated correctly
* so that I can continue working on a request that may have been closed in error or prematurely

**Assumptions & Scope**	

- This is related to user story #765 - included in the excel document is a number of state transitions from Closed
- IAO Users will be the only users that can move a request from the Closed State.
- When re-opening requests, IAO can re-open to the last state it was in prior to closure, and earlier states, with some exceptions.
- Most state changes from closed will require the clock to continue as it normally would have, with the exception of the case where a request was in an on hold state, and later closed as abandoned - there will be a different rule for the new due date and calculation in this particular scenario. There is only one scenario where a request will move from On-Hold to closed.

What is IN scope?
This story will be entirely focused on how the due date and countdown will be reflected when a request moves from Closed back to a prior open state

What is NOT in scope?
State transitions themselves, covered in #765

**Acceptance Criteria**	

**Scenario 1: Change State from Closed - drop down options for requests closed from CFR state and later**
* GIVEN an IAO user is on the review request page of a request in the closed state, where the last prior state was Call for Records, or later
* WHEN you click on the state menu drop-down on the left hand navigation panel
* THEN the available options will be: The last state the request was in prior to close, and any earlier state up to and including "Call for Records"

**Scenario 2: Change State from Closed - drop down options for requests closed from Open state**
* GIVEN an IAO user is on the review request page of a request in the closed state, where the last prior state was Open
* WHEN you click on the state menu drop-down on the left hand navigation panel
* THEN the available options will be: Open

**Scenario 3: Change State from Closed - drop down options for requests closed from Intake in Progress**
* GIVEN an IAO user is on the review request page of a request in the closed state, where the last prior state was Intake in Progress
* WHEN you click on the state menu drop-down on the left hand navigation panel
* THEN the available options will be: Intake in Progress

**Scenario 4: Change State from Closed to On Hold**
* GIVEN an IAO is on the review request page of a closed request, and has activated the state dropdown
* WHEN you change the state from Closed, to On-Hold
* THEN the request will remain in the on-hold state
* AND the On-hold days will continue to accumulate as if the request was always on hold
* AND the due date will display as N/A in both the request review page, and the request queue

**Scenario 5: Change State from Closed to Any State other than "On-Hold"**
* GIVEN an IAO is on the review request page of a closed request
* WHEN you change the state from Closed, to any state OTHER than "On-Hold"
* THEN the legislated due date will remain the same as it was when the request was closed
* AND the request countdown will display based on how it would normally function

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
Looks good to me, @m-prodan

**Comment by JHarrietha-AOT** [comment]
Looks good @m-prodan

**Comment by mpilchar** [comment]
@mprodan to rewrite scenarios based on refinement discussion today

**Comment by m-prodan** [comment]
I believe I've captured the required changes based on our discussion earlier. Please review @lmullane @mpilchar @JHarrietha-AOT @arielleandrews

**Comment by mpilchar** [comment]
@divyav-aot - Matt has updated these as discussed at refinement earlier this week. Please review and advise if all makes sense. If so, we can move to Product Backlog cc: @m-prodan

**Comment by m-prodan** [comment]
Updated AC to reflect discussion over sprint planning and stand up today @divyav-aot - let me know if this matches with your understanding we discussed.

**Comment by JHarrietha-AOT** [comment]
Design Link: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/843963404

**Comment by arielleandrews** [comment]
Clarifying for Scenario 1: dropdown options when reopening a request will show only the previous states that particular request went through. Example: a request went from CFR to Ministry Sign Off to Response to Closed. When reopening, the options displayed will be CFR, Ministry Sign Off and Response. Other possible states such as Deduplication will NOT be options as that particular request did not move through that state prior to be closed.

**Comment by arielleandrews** [comment]
Scenario 4: request is able to move from Closed to On Hold successfully. However, when taking the request from On Hold to Call for Records, the due date and days remaining countdowns are not calculating correctly. Example EDUC-2021-27080 in Test: request placed On Hold on Dec 17 (Friday), then closed on Dec 20 (Monday), and reopened to On Hold on Dec 20. The due date remained as Jan 14 but should have updated to add two business days. 
![image](https://user-images.githubusercontent.com/82615839/146822100-fa4330c7-3d8d-413c-a1d7-e7bfc6cc9cf2.png)
![image](https://user-images.githubusercontent.com/82615839/146822052-00102deb-b15a-4b87-b437-376f4fea2b58.png)
 Moving ticket back to In Progress as discussed @divyav-aot - let me know if there's anything to chat about further

**Comment by arielleandrews** [comment]
@divyav-aot I'm testing this one again and I think an extra day is being added when going from On Hold to Call for Records. Test request EDUC-2021-26793 was placed On Hold on Dec 22, then Closed on Dec 23, then reopened to On Hold on Dec 23 and moved to Call for Records on Dec 23 (so 2 business days total on hold). The countdown days in the left nav bar are correct but it seems the actual due date has increased by 3 business days (went from Jan 18 2022 to Jan 21 2022)
Before request was On Hold: 
![image](https://user-images.githubusercontent.com/82615839/147293249-49f7ceed-41b8-4d74-89b8-b53deafc891e.png)
After request was Closed, Reopened to On Hold, then moved to Call for Records: 
![image](https://user-images.githubusercontent.com/82615839/147293341-dae3e089-0f5e-4031-acb0-07faff967eac.png)

**Comment by arielleandrews** [comment]
Testing completed. All scenarios passed in Chrome, Edge and Firefox. Testing covered a range of state paths but not every possible iteration. For Scenario 4, test cases passed as going from Closed to On Hold does show legislated due date as "N/A", however bug ticket #1211 created as going from On Hold to Call for Records calculates an incorrect legislated due date.
