### ISSUE TITLE
Filter Comments

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#845]
* As a user (all user types)
* I want to filter comments 
* so that I can easily see the most relevant comment entries on a request

**Assumptions & Scope**	
- Filtering by User or System generated comments will be based on the parent comment
- Comments with replies will show all replies
- If a user replies to a system generated comment, and the system generated comments filter is applied, then the parent comment and all replies will display
- Users can toggle between 'All Comments', 'Request History Comments' and 'User Comments' in any order

What is IN scope?
- Displaying the filtered comments as selected

What is NOT in scope?
- Posting or replying to a comment (covered in separate user story)
- System generated comments (covered in a separate user story)

**Acceptance Criteria**	

**Scenario 1: All Comments default**
* GIVEN I am a user
* WHEN I navigate to the Comments tab 
* THEN the 'All Comments' radio button will be selected by default
* AND all Comments and Replies for the request will be displayed

**Scenario 2: Filter by 'Request History Comments'**
* GIVEN I am on the Comments tab of a request
* WHEN I select the 'Request History Comments' radio button  
* THEN only comments posted by 'Request History' will display
* AND any replies to the Request History comments will also display
* AND the comments will be in chronological order by newest to oldest from the top

**Scenario 3: Filter by 'User Comments'**
* GIVEN I am on the Comments tab of a request
* WHEN I select the 'User Comments' radio button
* THEN only comments posted by Users will display
* AND any replies to the User comments will also display
* AND the comments will be in chronological order by newest to oldest from the top

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813726

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment]
@JHarrietha-AOT, I'm leaning towards the filter not being FOI system posted comment vs user posted comment.

It's semantics, but suggest we consider the filter to be Request History vs user posted comments.

Ultimately the user wants to have a visual of the history of the request - when states changes, extensions happened, etc. It's the what happened that matters not that we automated posting the comment after a user made an action (.e.g. extension, state change).

A title change could change how the user's value the filter.

Thoughts?

cc @m-prodan

**Comment by JHarrietha-AOT** [comment]
@lmullane I do see that, and even thinking about the idea that this filter would be based off the parent comment there could be issues if there were lots of replys on the system generated app. The users could be losing a lot of comments. 

Maybe we need to rethink the usefulness of this filter. @m-prodan @arielleandrews what so you think?

**Comment by m-prodan** [comment]
I think filtering might still be useful to remove the strictly historical aspects of the request vs the potentially more meaningful comments you'll see in user generated comments. I personally can't imagine there will be a lot of conversations on system generated comments, but that remains to be seen I suppose. I feel like users would be more inclined to have conversations on user generated comments vs system generated ones.

I do like the idea of calling it "Request History" as a filter instead of system generated.

**Comment by arielleandrews** [comment]
Testing completed, all scenarios passed in Chrome, Edge and Firefox
