### ISSUE TITLE
Sort Request Queue by column headings

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#85]
* As a (type of user)
* I want (goal) 
* so that (reason/ why/ value) 

**Assumptions & Scope**	
What are the assumptions for this story?

What is in and not in scope?

**Acceptance Criteria**	

**Scenario 1: Sort by received or days left**
* GIVEN is on the request queue
* WHEN the intake analyst clicks the arrow next to each column heading 
* THEN the request will be sorted by the request will be sorted by the column heading (e.g. file number)
* AND requests will be ordered by the newest to the oldest number
* AND open requests underneath will be ordered by days left

**Scenario 4: Sort by request status (this will be default)**
* GIVEN is on the request queue
* WHEN the intake analyst clicks the arrow next to the Request Status
* THEN the request will be sorted by the request will be sorted by with Unopen at top (by date submitted from newest to oldest), in the middle by Open (days left, less to more), and at the bottom Closed (by date closed, newest to oldest).

**Scenario 3: xxxxxx**
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by mpilchar** [comment]
Not MVP

**Comment by mpilchar** [comment]
Create stories for: 
- Sort for Intake - personal & all toggles
- Sort for coord - all toggle options

**Comment by mpilchar** [comment]
completed
