### ISSUE TITLE
In-App Notifications - Notification Log 

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#850]
* As a user of the application
* I want a place to check on my in-app notifications
* so that I can see updates to requests I am assigned to

**Assumptions & Scope**	
- This story covers the look and behaviour of the in-app notification 
- Notifications appear in chronological order
- If a user is assigned and also a watcher on the same request, than they will only receive notifications as an assigned user, not as a watcher.

What is IN scope?
The notification log itself
How notifications are displayed and sorted
Notifications for requests assigned to a user, and users assigned as watchers to a request

What is NOT in scope?
Events that trigger a notification (separate user stories #855)
Dismissing Notifications (Separate user story #854)
Navigation from Notifications (Separate user story #856)

**Acceptance Criteria**	

**Scenario 1: Red dot - Default View, My Requests**
* GIVEN a user has at least one notification that has not been dismissed 
* WHEN the user is on any page in the application
* THEN there will a red dot next to the bell, along with the number of notifications indicated in red

**Scenario 2: Notifications View - Default View, My Requests**
* GIVEN a user is signed in to the application
* WHEN the user clicks on the notification "bell" icon 
* THEN the notification log will appear below the bell, overlayed on top of the screen
* AND they will NOT see any notifications from events the user themselves have triggered
* AND the default view will show any notifications that have not been dismissed, for requests that the user is assigned to

**Scenario 3: Notifications View - Specific Notifications**
* GIVEN a notification has been sent to an assigned user
* WHEN the notification appears in the log
* THEN the notification will include the following information: The FOI Request number the notification resulted from, the username of the person that triggered the notification, a timestamp, and an x mark to dismiss a notification

**Scenario 4: Notification View - Order of Notifications**
* GIVEN multiple notification has been sent to an assigned user
* WHEN the notifications appear in the log
* THEN they will be sorted from newest notifications at the top, to oldest 

**Scenario 5: Notification View - Watching Requests**
* GIVEN a user clicks on the notification "bell" icon 
* WHEN they click on the "Watching Requests" Tab
* THEN they will see all notifications on requests that they are assigned as a watcher to
* AND they will NOT see any notifications from events the user themselves have triggered
* AND the notifications and sort order will be the same as in scenarios 2 and 3

**Scenario 6: Expiry of notifications**
* GIVEN a user is viewing the notification list
* WHEN 10 business days has passed
* THEN they will no longer see notifications older than 10 business days

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/ckvl79z2u04k5012uctn2cyxn/play

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
First notification story drafted - thinking here is that this one would just focus on the look and view of the notification log - how specific notifications will appear, the fact that they are separated between assigned and watching.

I am going to draft seperate stories for reading/dismissing, navigating from specific notifications, and a story for events that will trigger notifications (this will likely require multiple stories over time as we add functions). 

Comments welcome! @lmullane @JHarrietha-AOT @mpilchar @arielleandrews

**Comment by lmullane** [comment]
@m-prodan, which should have the bell icon showing a red dot.

GIVEN a user has at least one notification that has not been dismissed or viewed??
WHEN the user is on any page in the applicaiton
THEN there will a red dot next to the bell

cc @JHarrietha-AOT @mpilchar

**Comment by m-prodan** [comment]
Good catch - I think that scenario makes sense in this particular story.

**Comment by lmullane** [comment]
Agreed, @m-prodan. I will have the red dot persist if the user has not dismissed the notification.

Same way an Outlook meeting notification works.

Having the notification work on any page will be big work for the devs.

**Comment by m-prodan** [comment]
Sounds good - do you want to write up that particular scenario(s)?

**Comment by m-prodan** [comment]
Need to update to remove references to read notifications

**Comment by m-prodan** [comment]
References to marking notifications as "Read" has been removed from this story

**Comment by m-prodan** [comment]
Updated assumption per discussion at stand-up today: If a user is assigned and also a watcher on the same request, than they will only receive notifications as an assigned user, not as a watcher.

**Comment by lmullane** [comment]
As discussed at standup, if multiple state changes occur for a request within the comment notification update window (approximately 15 minutes), then only the most recent state change will appear in the notification log; all state changes will still be posted as a comment in the request history. cc @abin-aot @sumathi-thirumani-aot

**Comment by aparna-aot** [comment]
Found out a bug where the entire page goes blank while clicking the notification bell icon before a page loads completely. Fixing it and will update once done.

**Comment by aparna-aot** [comment]
Fixed the above mentioned issue and is in QA.

**Comment by arielleandrews** [comment]
Edited AC for Scenario 3 to remove reference to read check marks - this was from a previous design and check marks have since been removed from design

**Comment by arielleandrews** [comment]
QA completed, all scenarios passed in multiple browsers. Nice work @aparna-aot and @sumathi-thirumani-aot, and thanks for your patience with the testing on this one!
