### ISSUE TITLE
Merge Pay and full Flow API into a branch

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#853]
Title of ticket: 

#### Description
For the application fees we have a stripped down version of the Flow API. This enables us to go to production with for application fees.

 In dev and test we now want to merge the pay integration with the full Flow API for the future development of CFR fees.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Create a new branch and merge
- [ ]

**Comment by mpilchar** [comment]
Spoke with Jad Dec 6/21. This is ~80% complete, will need to make additional merges as development continues
