### ISSUE TITLE
In-App Notifications - Dismiss Notifications

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#854]
* As a User of the application
* I want to be able to dismiss notifications from my log 
* so that I can no longer see notifications that I've actioned/have no relevance anymore

Assumptions & Scope
What are the assumptions for this story?
This story will show how dismissing notifications are handled
This functionality will work the same for both assigned requests, and watching requests

What is IN scope?
The function of dismissing notifications in the log

What is NOT in scope?
Navigation from Notifications (Separate user story #856)
Events that trigger a notification (separate user stories #855)

**Acceptance Criteria**	

**Scenario 1: Notifications Log – Dismiss a single Notification**
* GIVEN a user has activated the notification log, and is on either the "My requests" or "Watching Requests" tab
* WHEN they click on the x button on a specific notification
* THEN that notification will disappear from the log

**Scenario 2: Dismiss all notifications**
* GIVEN a user has activated the notification log
* WHEN they click on the space where "Dismiss All" sits
* THEN all notifications will disappear from the tab the user is on

**Design**
https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/ckvl79z2u04k5012uctn2cyxn/play

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Dismiss notification story - a little smaller, could roll it up with marking notifications as read... Just a thought while I was writing this - should a user be able to dismiss an unread notification? I can update the AC if so - I think creating that condition may annoy, especially for simple notifications that a user just needs to see once.

Comments welcome @lmullane @arielleandrews @JHarrietha-AOT @mpilchar

**Comment by lmullane** [comment]
@m-prodan, @JHarrietha-AOT, why do you think we need both a 'Read' and a 'Dismiss'?

**Comment by JHarrietha-AOT** [comment]
@lmullane I included a read and a dismiss as in discussions @arielleandrews & @m-prodan they mentioned how helpful it would be to have the quick access link to click into requests. This made me think users would then want to be able to show that they have completed the task or want to show they have actioned the notification but may want to keep it in there notifications to have quick access to it. If they decide they no longer want it to appear in their list than they can dismiss it and it will disappear from the list.

@m-prodan @arielleandrews Feel free to add any additional thoughts to the benefit of this.

**Comment by arielleandrews** [comment]
Thanks @JHarrietha-AOT, I think that captures it. The user may want to mark for themselves that they've read the notification but leave it displayed if they haven't actioned it yet and want the link and reminder easily accessible

**Comment by lmullane** [comment]
I wonder if this would be used more like a flag (i.e. flag this for later because it is important).

**Comment by JHarrietha-AOT** [comment]
I like that @lmullane I'll update the icon from read to be a flag instead of a checkmark. I'll comment in #852 when its updated

**Comment by arielleandrews** [comment]
QA completed, all scenarios passed as expected.
