### ISSUE TITLE
In-App Notifications - Assignment & State Change Events that Trigger Pull Notifications

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#855]
* As a User
* I want assignments and state change events to trigger notifications through a pull
* so that I can be informed of important changes to my requests

**Assumptions & Scope**	
This covers specific events in the application that will PULL a notification to a user assigned or watching a request
This story covers notification for when a user is assigned or a state change events only.

Notification Pulls will occur every 15 minutes.

What is IN scope?
This covers events across the application that will be pull notifications to an assigned user, as both a primary user and watcher of the request. 

What is NOT in scope?
CFR and LDD event notifications are covered in story #1242 
Dismissing Notifications (Separate user story #854)
Navigation from Notifications (Separate user story #856)

**Acceptance Criteria**	

**Scenario 1: Assignment**
* GIVEN a FOI Request has been assigned to a user
* WHEN the assignments are saved
* THEN any new assignees will be given a notification showing: the request number, and a message saying: "New Request assigned to you." through a pull notification that occurs every 15 minutes. 

**Scenario 2: State Change of a Request**
* GIVEN a FOI Request is in any state
* WHEN the state of the request changes
* THEN all users assigned to the request, EXCEPT for the user that made the change, will receive a notification that includes: FOI Request number, and a message saying "Moved to XXX State" - where XXX will be the state that a request has been changed to. through a pull notification that occurs every 15 minutes. 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/ckvl79z2u04k5012uctn2cyxn/play

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Notification events! I'm probably missing some here, so eyes most definitely welcome on this. We will likely need to create tickets in the future as additional functionality is added. I've not included extensions since we won't have that feature built yet - I'll make sure I set up a user story for a push notification to go with our collection of extension user stories.

@lmullane @JHarrietha-AOT @mpilchar @arielleandrews

**Comment by m-prodan** [comment]
Also of note - I added two kinds of notifications on top of requests being due today - I thought it would be good to have an automated push notification when there is one day remaining on both LDD and CFR due date.

This will save analysts from having to send reminder emails when requests are coming due.

**Comment by m-prodan** [comment]
need to split up this story into push/pull notifications (push comments, pull all others)

**Comment by m-prodan** [comment]
AC Updated to remove comments, which we discussed would be push notifications and are covered in #906

Also updated AC to remove notification event from changes to request details - this covers pull notification events only now. @sumathi-thirumani-aot

**Comment by lmullane** [comment]
As discussed in Sprint Planning, split user story into 2: 1 with scenario 1 and 6 (estimate); 2nd story will be scenarios 2-5.

Estimates:

1 ->3
2 -> 3
3 -> 5
4 -> 5
5 -> 5
6 -> 3

**Comment by lmullane** [comment]
@sumathi-thirumani-aot, split story as discussed. cc @mpilchar

**Comment by sumathi-thirumani-aot** [comment]
Thanks @abin-aot for reporting bugs on scenarios:
1. Closing notification should clear the old assignment notifications
2. If IAO changes assignment; then ministry is notified of assignment and vice versa. 
Status -> In progress.

**Comment by arielleandrews** [comment]
QA completed, all scenarios passed as expected. Nice work @aparna-aot and @sumathi-thirumani-aot!
