### ISSUE TITLE
In-App Notifications - Navigating from Notifications

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#856]
* As a user of the application
* I want to be able to navigate from the notifications log
* so that I can more quickly get to where a notification originates

**Assumptions & Scope**	
This story covers a users ability to navigate to where a notification originates from
Future stories will be required as additional functionality is added
To navigate from a notification, users will need to click on the Request ID space of the notification

What is IN scope?
- Navigating to the comments section from the notification log
- Navigating to a Requests page from the notification log

What is NOT in scope?
Events that trigger a notification (separate user stories #855)
Marking Notifications as read (separate user story #852)
Dismissing Notifications (Separate user story #854)

**Acceptance Criteria**	

**Scenario 1: Request State Change Notification**
* GIVEN a user has received a notification relating to change of state of a request
* WHEN the user clicks on the request ID from the log
* THEN they will be taken to the review request page of the request that triggered the notification

**Scenario 2: Assignment Notification**
* GIVEN a user has received a notification that they have been assigned to a request
* WHEN the user clicks on the request ID from the log
* THEN they will be taken to the review request page of the request that triggered the notification

**Scenario 3: Due Date Notification**
* GIVEN a user has received a notification that a request is on, or near it's legislated due date OR call for records due date
* WHEN the user clicks on the request ID from the log
* THEN they will be taken to the review request page of the request that triggered the notification

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Navigation story - am not sure if we need designs for this. Do these scenarios and outcomes all make sense? We'll need to create additional stories as additional notification events are created.

Comments welcome @JHarrietha-AOT @arielleandrews @mpilchar @lmullane

**Comment by lmullane** [comment]
@m-prodan, when the user click on the comment and is redirected to the relevant request, does the comment log close?

cc @JHarrietha-AOT

**Comment by m-prodan** [comment]
Update AC to click on the request ID itself to take user to page

**Comment by m-prodan** [comment]
Also update to take to comments page instead of specific comment

**Comment by m-prodan** [comment]
Updated AC to have user click on the request ID itself instead of the notification. Also removed references to "read" notifications to be consistent with other changes.

**Comment by aparna-aot** [comment]
Adding the suggestions from Dev team on UX of notification log with this story:

1. Change message from "No requests" to "No notifications".
2. Since it is tabbed for "My Requests" and "Watching Requests". Next to label "My Requests" append the specific count tab wise count i.e., "My Requests(1)" and "Watching Requests(2)".

**Comment by aparna-aot** [comment]
@arielleandrews @m-prodan @mpilchar @lmullane 
Since comment related notifications are not part of this sprint and is covered in a separate user story( #906 ) , it would be better to draft a separate story for scenario 1 of the above AC.

**Comment by aparna-aot** [comment]
There is a **known tech debt** with this story which is not in scope of this story. Attaching it here for reference: #1343 .

**Comment by arielleandrews** [comment]
Edited AC to remove scenario related to navigating to comments - this has been written as a separate user story (#1345)

**Comment by arielleandrews** [comment]
QA completed, all scenarios passed. Great work @aparna-aot and @sumathi-thirumani-aot!
