### ISSUE TITLE
Extensions - Create First Extension (Public Body)

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#858]
* As an IAO Analyst
* I want a place to record an extension
* so that I can record when an extension has been taken on a request

**Assumptions & Scope**	
What are the assumptions for this story?
This story reflects the ability for a user to move from the review request page to the create a new extension module. This story is for the FIRST extension only - when an extension has been created already, there will be separate behaviour that will be covered in #
A public body extension can NOT be longer than 30 days, 30 days is the maximum number of days a request can be extended.
Public Body extensions will be defaulted to 30 days, with the ability to edit to the number of days to less than 30. 
The extended due date space is not intended to be an active calendar picker - it will just display the extended due date based on # of days
Extensions can only be taken when a file is in Open state onward. 
Extensions cannot be taken when a file is On Hold.
Extensions will not be visible or possible to action in Unopened, Intake in Progress, Redirect, On Hold or Closed states.

What is IN scope?
Navigating to the extension module
The create extension module itself
The creation of a first extension - public body extension

What is NOT in scope?
Extension log when one or more extensions have been created (#878)
OIPC Extensions Approve/Deny (#881 #882)
Deleting or Editing Extensions (#968)

**Acceptance Criteria**	

**Scenario 1: Navigate to Extension Module**
* GIVEN an IAO analyst is on the Review Request page
* WHEN they hover over the "New Extension" hyperlink
* THEN their cursor will turn into a hand

**Scenario 2: Navigate to Extension Module with no active extensions**
* GIVEN an IAO user is on the review request page
* AND no extension has been taken
* WHEN they click on the New Extension hyperlink
* THEN a modal will pop out for creating a new extension https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/ckv6tij0n04v001yzd1c4d2mq/play
* AND the Save Change button will be inactive

**Scenario 3: Cancel back to Request View**
* GIVEN an IAO user is on the extension modal
* WHEN they click on the cancel button
* THEN the modal will close and they will be taken back to the review request page

**Scenario 4: Reason for Extension**
* GIVEN an IAO user is on the extension modal
* WHEN they click on the Reason for Extension
* THEN the following options will appear in the drop-down menu in the following order: Public Body - Applicant Consent; Public Body - Consultation; Public Body - Further Detail from Applicant Required; Public Body - Large Volume and/or Volume of Search; Public Body - Large Volume and/or Volume of Search and Consultation OIPC - Applicant Consent; OIPC - Consultation; OIPC - Further Detail from Applicant Required; OIPC - Large Volume and/or Volume of Search; OIPC - Large Volume and/or Volume of Search and Consultation; OIPC - Fair and Reasonable; 

**Scenario 5: Reason for Extension - Public Body Selected**
* GIVEN an IAO user is on the extension modal and has activated the Reason for Extension drop-down
* WHEN they click on any of the following options: Public Body - Consultation; Public Body - Further Detail from Applicant Required; Public Body - Large Volume and/or Volume of Search; Public Body - Large Volume and/or Volume of Search and Consultation
* THEN the 'Days to Extend' field will be auto-filled to 30 days
* AND the extended due date will show, where the extended due date will be the legislated due date, plus the number of business days extended (default 30 for public body) https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/ckv8gjplj05kb01zp8zmfaj6s/play
* AND the Save Change button will be active

**Scenario 6: Extend Due Date - Number of Days Greater than 30**
* GIVEN an IAO user is on the extension modal and has activated a public body extension as the reason for extension
* WHEN they enter a number in the number of days to extend
* AND that number is greater than 30
* THEN the data field will not allow the user to enter a value greater than 30

**Scenario 7: Extend Due Date - Number of days less than 30**
* GIVEN an IAO user is on the extension modal and has activated a public body extension as the reason for extension
* WHEN they edit the number of days to a number less than 30
* THEN the 'Extended Due Date' field will update based on the number of business days inputted
* AND the save change button will be active

**Scenario 8: Public Body Extension - Save and Complete**
* GIVEN an IAO user is on the extension modal, and has selected a public body extension
* WHEN they click on the Save button
* THEN the modal will close and they will be taken back to the review request page
* AND the legislated due date will be updated with the new extended due date
* AND the countdown will be updated
* AND the new legislated due date will be updated in all queues where the request appears
* AND an extension log will appear above the request details https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Story 1 for extensions - this one will cover where the extension hot spot lives, and how to take the first public body extension. Separate stories for second extensions, and OIPC extensions will be done separately. Please review and add any updated designs: @JHarrietha-AOT @arielleandrews @mpilchar @lmullane

**Comment by arielleandrews** [comment]
Looks good so far! Do we need to be explicit about the date updating if a different number of days is inputted? Or instructions for the calendar picker? Use case will be that users will input the desired number of days and likely won't need the calendar at all, other than to potentially open for reference

**Comment by m-prodan** [comment]
Good point - I think what I can do is update the assumptions to include that a public body extension can not be greater than 30 days - though that might need to be a separate AC... and I can note that the extended due date space will not be a clickable calendar picker at all

**Comment by lmullane** [comment]
Could we change the 'Extend Due Date' to 'Days Extended.' Similarity of the field tiles is a bit confusing imo.

**Comment by arielleandrews** [comment]
Good catch Loren. Maybe even 'Number of Days' instead. I would think from context the user would already know the days would be specific to the extension

**Comment by lmullane** [comment]
Number or Day works for me.

Question - can I confirm that the user can only select an OIPC extension if a Public Body extension has been previously taken?

**Comment by lmullane** [comment]
Also curious whether Public Body extensions are captured and displayed in the Extension Log?

**Comment by arielleandrews** [comment]
@lmullane there are some circumstances where an OIPC extension may be taken before a Public Body - an example being the OIPC 'Fair and Reasonable' reason. So we wouldn't want to enforce any specific logic to that effect. 

Yes, Public Body extensions would be captured and displayed in the Log.

**Comment by lmullane** [comment]
Great, thanks for those clarifications.

These are really well written. While AC take time, they capture the business requirements for future  changes too.

**Comment by m-prodan** [comment]
Public body extension updated AC to include scenario for when days extended is greater than 30

**Comment by m-prodan** [comment]
To do: Update AC and designs - no longer have modal on top of modal - move extension listing to review request page below request details

**Comment by m-prodan** [comment]
Updated the AC based on refinement meeting today - @JHarrietha-AOT - when designs have been updated, please let me know and I can do a last comparison before I move it over to backlog.

**Comment by lmullane** [comment]
As discussed, we are not going to follow the designs.

For IAO user request view:

- the current request details box/section with dates will remain unchanged
- Exception - when CFR is complete we will include a new date field in request descriptions in the request details section
- Extensions will be a separate section at the bottom - above the 'Save' button
- If there is no extension there will be only the 'New Extension' and the text "No extensions taken."


For Ministry users on the ministry request view:

- the current request description and details boxes/sections with dates will remain unchanged
- Extensions will be a separate section at the bottom - above the 'Save' button
- Ministries will not be able add a "New Extension" or edit extensions taken, but they can view all extensions (Pending, Approved, Denied)
- If there is no extension there will be only the text "No extensions taken."

@divyav-aot, @jadmsaadaot, please review that I have captured the discussion accurately.

**Comment by mpilchar** [comment]
cc @JHarrietha-AOT @arielleandrews for awareness of these changes since you were away for this discussion

**Comment by divyav-aot** [comment]
@arielleandrews @m-prodan -we had a discussion on original due date in the extension modal. I would like to confirm the value for the same. 
**For example:** 
When the request is in "Intake In Progress", the dueDate calculated was "2022-01-28"
Later the request changed to "OnHold" then changed it back to "CFR" then the new calculated dueDate is "2022-02-02". 
If we create a new extension, then the "original due date" will show "2022-01-28" and "current due date" will show "2022-02-02".
Please correct me if I am wrong.
@JHarrietha-AOT @mpilchar @jadmsaadaot - I hope this is everything we discussed about original and current due date. Please review and add more points if I missed anything. 
 @abin-aot

**Comment by arielleandrews** [comment]
Good question. @m-prodan I like the idea of maintaining the original due date and having the current due date update if the request was placed on hold, do you agree?
@divyav-aot our thinking behind the original vs current due date was to reflect when multiple extensions have been taken the current due date field will always show the most recent due date (not technically applicable for this ticket but will be in others). You have raised a good point!

**Comment by m-prodan** [comment]
Yes -  I do agree with that. We want to preserve the original due date (as it's required for some things, like OIPC extension applications), and the current due date reflects any changes (on hold, extensions). 

Thanks for flagging!

**Comment by JHarrietha-AOT** [comment]
@divyav-aot @jadmsaadaot @mpilchar 

I have updated the designed to pull the extensions out into there own section/box on the review page.  Link below, let me know if you have any questions.

https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852

**Comment by divyav-aot** [comment]
@m-prodan @JHarrietha-AOT  @arielleandrews  - Just wanted to confirm on the visibility of  Extension log and "New Extension" link. Our understanding is that this section will be visible only from "Open" state onwards. Could you please confirm and update the Assumptions/AC based on that.

**Comment by arielleandrews** [comment]
Thanks @divyav-aot, I added that clarification to the assumptions. Extensions will not be possible in Unopened, Intake in Progress, Redirect, On Hold or Closed states. All other states extensions will be possible. Let me know if you need any further clarfication!

**Comment by divyav-aot** [comment]
Thanks @arielleandrews

**Comment by jadmsaadaot** [comment]
btw, do we set the number of days automatically to 30 days for all public body selections or only a select subset of them @lmullane @arielleandrews

**Comment by jadmsaadaot** [comment]
Arielle answered the above: "Default to 30 days for all public body selections, with the option to edit. Occasionally we will take less than 30 days, although it is rare"

**Comment by arielleandrews** [comment]
@jadmsaadaot and @divyav-aot I updated the assumptions and added Scenario 7 in the AC to cover changing the number of days to less than 30 as noted above. Scenario 5 already includes that the default number of days will be 30. Please let me know if you have any more questions!

**Comment by m-prodan** [comment]
QA Complete - I updated AC6, because you can not actually enter a value greater than 30, which I think accomplishes the same thing. The original AC said the box would turn red and a message would appear saying extended days cannot exceed 30. 

This essentially does the same thing - analysts should know better that a PB extension can't be more than 30, and the app will not allow it, so it functions as expected.

All scenarios passed - Of note - you can add additional PB extensions to a file, but I know the AC addressing that is in a separate story, so will keep an eye out when 878 is ready
