### ISSUE TITLE
Unchecking PROGRAM Area gives blank screen

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#860]
**Describe the bug in current situation**

Go a Request Details Form and if we uncheck ministry from the checkbox list, provided if there is only 1 ministry left checked, the form will crash and turn to blank

**Link bug to the User Story**

**Impact of this bug**
Have minor to medium impact since we cant leave the ministry unchecked , if only 1 left.  As a workaround, check other ministry and uncheck required one.

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to  Review Request form on any state with all ministries available to be selected. 
2. Check few of the ministries 
3. start unchecking each and on the last uncheck of ministry
4. See error - blank screen or on browser console - we can see a Javascript error

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by mpilchar** [comment]
Passes with flying colours, nicely done!
