### ISSUE TITLE
Extensions - Extension Log and OIPC Extension

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#878]
* As an IAO user
* I want to be able to take and track subsequent extensions
* so that I can manage the timelines of my request

**Assumptions & Scope**	
What are the assumptions for this story?
This story will cover the look of the extension module when putting in a second or subsequent extension
This story will also cover how an OIPC extension is tracked
Only one pending extension can be created at a time. 
Pending extensions will have no impact on the due date.

What is IN scope?
Secondary and subsequent extensions
Creating a pending OIPC extension

What is NOT in scope?
Completing and approving or denying an OIPC extension (#881 #882)
Editing/Deleting Extensions (#968)

**Acceptance Criteria**	

**Scenario 1: Extension Log when Extension(s) have been created**
* GIVEN a user is on the review request view
* WHEN an extension has been applied
* THEN the extension log will display above the save button on the request view
* AND extensions will be ordered in the following format: Pending, Approved, Denied

**Scenario 2: Create Extension**
* GIVEN a user is on the review request page
* WHEN they click on the New Extension hotspot
* THEN they are taken to the new extension window

**Scenario 3: Create Second Extension**
* GIVEN a user is on the new extension window
* AND a request has a prior public body extension taken
* WHEN the user clicks on the extension reason
* THEN they will see the following options on the drop-down: OIPC - Applicant Consent; OIPC - Consultation; OIPC - Further Detail from Applicant Required; OIPC - Large Volume and/or Volume of Search; OIPC - Large Volume and/or Volume of Search and Consultation; OIPC - Fair and Reasonable

**Scenario 4: Create Second Extension - OIPC**
* GIVEN a user is on the new extension window and has the extension reason activated
* WHEN the user clicks on an OIPC extension
* THEN the "Extend Number of Days" will be an empty and fillable text field
* AND radio buttons will appear showing: Pending; Approved; Denied
* AND Pending will be the default selection
* AND the save change button will be inactive https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/ckv6xm2a3053101zbb1e7exhy/play

**Scenario 5: Create Second Extension - Enter Days to activate save**
* GIVEN a user has selected an OIPC extension reason
* WHEN the user enters the number of days in the extend due date field
* THEN the extended due date will be calculated and display
* AND the save change button will be active

**Scenario 6: Create Second Extension - Save**
* GIVEN a user has selected an OIPC extension reason and has entered the number of days
* WHEN the user clicks on the save button
* THEN the modal will close
* AND the OIPC extension will be saved in the log as "Pending"
* AND the new extension hotspot will become deactivated

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Second extension story, and setting up OIPC extension as pending. I will tackle approve/deny extensions as a separate user story

@JHarrietha-AOT - I was just looking at the designs and am not sure if I've captured this correctly. If the user has an extension created already, I believe that when they click the extension hotspot, it should take them to that log page first so they can see what's already been done - see scenario 3. What's missing from the design is a button to add a new extension. I'm not sure if that was the UX you were planning on, but the more I think about it, the more it makes sense to me. Happy to discuss soon!

@arielleandrews @lmullane @mpilchar - comments welcome

**Comment by arielleandrews** [comment]
For Scenario 2, I would personally rather see extensions ordered by the created/actioned date rather than status, with newest on top. If we go by date created then any pending ones will be at the top anyway, and all the others will be in chronological order as well. @JHarrietha-AOT your thoughts?

Otherwise looks great @m-prodan!

**Comment by JHarrietha-AOT** [comment]
@m-prodan I completely agree, it had been added to the UX of the Extension Log Page

https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817290037

Should we add a new user story for this or update the AC here to include?

**Comment by JHarrietha-AOT** [comment]
@m-prodan Just thought of this but we should include in the AC that extensions should be listed in a specific order with Pending Status First, Followed by Approved Extensions and Denied at the bottom of the list.

**Comment by m-prodan** [comment]
Removed AC reflecting number of extensions showing in the request description hotspot area, based on discussion with @JHarrietha-AOT @arielleandrews

**Comment by m-prodan** [comment]
Update AC: Re-design of extension log to appear on review request page

**Comment by m-prodan** [comment]
Updated AC based on refinement discussion this morning - of note, included function that when a pending extension is in the log, the new extension hotspot will be de-activated. I will update approving and denying extensions to include the fact that it will activate the hotspot again. Let me know when designs are done @JHarrietha-AOT

**Comment by JHarrietha-AOT** [comment]
@m-prodan Here is a link to the updated designs, let me know if you have any questions
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852

**Comment by lmullane** [comment]
See comment on decision on request views on #858

**Comment by jadmsaadaot** [comment]
According to the meeting with Jackie, Arielle and Matt:

- Radio buttons will always show when reason is OIPC, whether it's first or subsequent extension creation.
- Radio buttons will never show when reason is a public body one even on edit.
- If 1st extension was a public body, the reason drop down will not show any public body anymore. However, if 1st extension is OIPC there will be no effect on the dropdown

**Comment by mpilchar** [comment]
Thanks for connecting on this, team, and for relaying the discussion @jadmsaadaot

**Comment by JHarrietha-AOT** [comment]
Almost done QA, all scenarios have passed in chrome. Will test in Firefox and edge after demo

**Comment by JHarrietha-AOT** [comment]
All Scenarios have passed! Great job @jadmsaadaot & @divyav-aot
