### ISSUE TITLE
Extensions - Approving OIPC Extensions

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#881]
* As an IAO user
* I want to be able to approve an OIPC extension
* so that I can complete the extension

**Assumptions & Scope**	
This covers how a user will complete an OIPC extension for the approval path
Only one attachment can be uploaded for the file upload step.
This functionality can also be used as a means to edit an already approved extension - but only when that extension is the most recent extension. Users will not be able to edit extensions prior to the most recent extension.
The ellipsis with the Edit and Delete options will only be enabled for the most recent extension

What is IN scope?
Approving the OIPC extensions
Uploading attachments to complete OIPC extensions

What is NOT in scope?
Deleting extensions (#968)
Denying OIPC Extensions (#882)

** Dependencies: **
#882, #968 and this ticket will be handled together

**Acceptance Criteria**	

**Scenario 1: Completing a Pending Extension**
* GIVEN an IAO user is on the extension log of the request page
* WHEN they click on a pending OIPC extension
* THEN they will be taken to the extension view https://jacklyn808742.invisionapp.com/console/FOI---Intake-ckpq19frj032r013q6gpm8t1m/ckv6xm2a3053101zbb1e7exhy/play

**Scenario 2: Approving an Extension**
* GIVEN an IAO user is on a pending OIPC extension
* WHEN they select the "Approved" radio button
* THEN a drag and drop field for an attachment will appear
* AND a new calendar picker field will appear titled "Approved Date" and "Approved Number of Days"
* AND the Approved Date will default to Today's Date
* AND the Approved number of days will default to the Number of Days Extended
* AND the save change button will become inactive

**Scenario 3: Approved Date - Calendar Picker**
* GIVEN an IAO user is on a pending OIPC extension, and has activated the approved radio button
* WHEN they click on the approved date space
* THEN a calendar picker will appear
* AND the user will be unable to pick a date in the future

**Scenario 4: Approved Date - Select Date**
* GIVEN an IAO user has the approved date calendar picker open
* WHEN they click on a valid date
* THEN the date will populate into the space

**Scenario 5: Approved Number of Days**
* GIVEN an IAO user has selected the approved radio button in the extension modal
* WHEN they modify the 'Approved Number of Days' field
* THEN the Extended due date will update based on the approved number of days entered

**Scenario 6: Add a file - drag and drop**
* GIVEN an IAO user is approving an OIPC extension
* WHEN they drag a valid filetype into the drag and drop zone (Word, email, or PDF, 50 mb limit)
* THEN the file name will appear, with an x next to the attachment name

**Scenario 7: Add a file - Add file button**
* GIVEN an IAO user is approving an OIPC extension
* WHEN they click the add file button
* THEN a window will pop up allowing the user to upload a valid file using the file explorer of their computer
* AND when a file is selected, the name will appear with an x next to the attachment name

**Scenario 8: Remove a file**
* GIVEN an IAO user has uploaded a file to the extension modal
* WHEN they click the x button next to the file name
* THEN the attachment will be removed

**Scenario 9: Saving an Approved OIPC Extension**
* GIVEN an IAO user is approving an OIPC Extension
* WHEN the user presses the save change button
* THEN the modal will close and they will be taken back to the review request page
* AND the legislated due date will be updated with the new extended due date
* AND the countdown will be updated
* AND the new legislated due date will be updated in all queues where the request appears
* AND the 'New Extension' hotspot will become active

**Scenario 10: Attachment Log**
* GIVEN an IAO user has completed approving an OIPC Extension
* WHEN the uploaded file is saved
* THEN it will appear in the attachment log
* AND display the original file name 
* AND display the badge "Extension - Approved"

**Scenario11: Editing Pending OIPC Extension**
* GIVEN an IAO user has a pending OIPC extension
* WHEN the user clicks on the ellipsis and selects Edit
* AND the user changes the number of days extended
* AND the user changes the extension reason to a different OIPC extension reason
* THEN those fields will be updated with the new information
* AND the legislated due date will be updated if required

**Scenario 12: Editing Approved OIPC Extension**
* GIVEN an IAO user has completed an approved extension
* AND that extension is the most recent extension
* WHEN the user clicks on the ellipsis and selects Edit
* AND the user changes the number of days extended
* AND the user changes the extension reason to a different OIPC extension reason
* THEN those fields will be updated with the new information
* AND the legislated due date will be updated if required

**Scenario 13: Editing Approved OIPC Extension to Public Body Extension**
* GIVEN an IAO user has completed an approved extension
* AND that extension is the most recent extension
* AND there is no Public Body extension already taken
* WHEN the user clicks on the ellipsis and selects Edit
* AND the user changes the extension reason to a Public Body extension reason
* THEN the user can approve the extension
* AND the maximum number of days extended allowed will be 30

**Scenario 14: Editing Approved Extension - Replace Uploaded File**
* GIVEN an IAO user has completed an approved extension
* AND that extension is the most recent extension
* WHEN the user clicks into the approved extension
* AND the user clicks the x button next to the file attachment name
* THEN the file will be removed
* AND the user can upload a new file to replace it
* AND the new file will appear in the attachment log when uploaded

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Approving OIPC Extensions - comments welcome! @JHarrietha-AOT @lmullane @mpilchar @arielleandrews

**Comment by arielleandrews** [comment]
Only suggestion is to have the Approved Date autofill with the current date

**Comment by m-prodan** [comment]
Good call - I like that idea... most analysts will be approving/completing their OIPC extension the same day they get the decision

**Comment by m-prodan** [comment]
Update AC and design: add approved # of days, default to original request, include decision letter in attachment log

**Comment by m-prodan** [comment]
Updated AC based on refinement discussion today

**Comment by m-prodan** [comment]
@m-prodan - update AC to remove mandatory attachment

**Comment by m-prodan** [comment]
@m-prodan  - update AC - only one pending ext at a time, no edit when a pending extension is present

**Comment by m-prodan** [comment]
AC has been updated based on our discussion yesterday, changing these stories to have AC present for editing purposes. Please let me know if I've missed anything @abin-aot @JHarrietha-AOT @lmullane @mpilchar  @arielleandrews

**Comment by m-prodan** [comment]
Updated AC by adding scenario 13 to address discussion we had this morning re: replacing attachments.

Please let me know if this tracks with your understanding of our discussion this morning @divyav-aot @jadmsaadaot 

Will update the other user story with the same criteria as well. 

cc @mpilchar @lmullane

**Comment by divyav-aot** [comment]
Points noted during the discussion:
>>> PUBLIC BODY, if already 1 Approved, will not allow new public body extension
>> PUBLIC BODY - auto approval - max to 30 days


>> OPIC EXTENSION - if already 1 Approved, WILL allow new public body extension IN ANY CATEGORY
>> OPIC EXTENSION - MAX three digits -XXX < 999
>>> OPIC EXT - IF ONE IN PENDING, then SYS. will NOT allow to add any new extension


>> EDIT/DELETE EXTENSION - If ON TOP 

>> IF THERE ARE ERRORS on the listed previous extension, then delete way down till the one they need edit, 
then make addition again top once?

**Comment by arielleandrews** [comment]
@JHarrietha-AOT @divyav-aot @jadmsaadaot this User Story has been updated based on our discussion today. Please let me know if this captures everything you understood or if anything is missing. Thanks!

**Comment by divyav-aot** [comment]
Thanks @arielleandrews . One query on scenario 15. We will not have an approved extension in the top if there is a Pending extension. So scenario 15 is not valid right? Could you please confirm.

**Comment by arielleandrews** [comment]
Good catch @divyav-aot! I've removed that last scenario now. Thanks for the flag

**Comment by divyav-aot** [comment]
@arielleandrews  - One more query regarding the documents. 
The extension is approved then the document will show in the attachment log.
if we edit this extension and change to Pending with different reason then what should happen to the document? Should we remove this document from the attachment log?

**Comment by JHarrietha-AOT** [comment]
@divyav-aot I would say yes it should be removed - I would add a toast just to let the user know that: The attachment "filename.docx" will be deleted when the status of the extension is changed." I will leave for @arielleandrews to confirm

**Comment by divyav-aot** [comment]
@arielleandrews 
Scenario 9: Save button Activation

GIVEN an IAO user is approving an OIPC Extension
**WHEN the Approved date, and a valid file has been uploaded**
THEN the save change button will be activated

SC 9 states that, the save button is enabled only when the approved date and valid file is uploaded. But during the discussion we concluded that file upload is optional.
Could you please confirm?

**Comment by arielleandrews** [comment]
Good catch @divyav-aot - I think we can remove that scenario entirely, and update scenario 10 to remove the reference to the Save button being active. With the upload being optional the Save button would always be active

**Comment by arielleandrews** [comment]
@divyav-aot and @jadmsaadaot - removed above noted scenario, updated Attachment Log scenario to cover the file name and badge, and added a scenario to cover editing a pending extension. Let me know if you have any questions or concerns! cc @m-prodan
