### ISSUE TITLE
UX for the Redirect prototype

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#89]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD - This prototype will include: 
- [x] assigning a ticket
- [x] modifying request description
- [x] contacting applicant - opening acknowledgement letter
- [x] contacting applicant - redirect 
- [x] contacting applicant - redirect and open
- [x] contacting applicant - more info needed

**Comment by JHarrietha-AOT** [comment]
Invision Link - https://jacklyn808742.invisionapp.com/console/share/XU2L77IGEA

**Comment by lmullane** [comment]
@JHarrietha-AOT, thanks for sharing the prototype. At refinement I'd like to discuss the redirect flow. I'm mostly curious whether the redirect can be one flow regardless of whether it is a redirect in part or full. Talk soon.

**Comment by JHarrietha-AOT** [comment]
Prototype has been updated based off of teams feedback. Changed the redirect flow to show.

Split Request 
     - Partial Redirect 
     - XGOV with Individual Descriptions

Original descriptions will be pasted into all fields so it is easy for IAO to edit content

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews This issue can be closed if you have completed a final review. If you have any further changes please let me know

**Comment by arielleandrews** [comment]
@JHarrietha-AOT is the idea with Partial Redirects and XGOV that after you prepare the letters, the user will be taken back to the Review Request screen and still have to click Open Request at the bottom? That makes sense to me as a flow but just wanted to confirm. Other than that no further changes I can think of!

**Comment by JHarrietha-AOT** [comment]
@arielleandrews That is correct, thanks for pointing this out the updated hotspots didn't save when I changed them yesterday. They should be updated now.
