### ISSUE TITLE
Discover FOI Reporting Personas

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#892]
#### Description
We need to determine who receives FOI reports in order to do research by persona (IAO exec, ministry exec, IAO coordinators, ministry coord, etc)

#### DOD
- [ ] Obtain lists of all reports sent out in a year and who receives them
- [ ] Obtain lists of IAO recipients
- [ ] Obtain lists of ministry recipients
- [ ] Create final list of personas for reporting

**Comment by mpilchar** [comment]
cc: @JHarrietha-AOT @lmullane @m-prodan @arielleandrews

**Comment by JHarrietha-AOT** [comment]
Thinking this ticket could be closed as I have included this in the planning ticket #937
