### ISSUE TITLE
Create templates for redirect

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#90]
Title of ticket: 

#### Description
Summarize issue 

Assumptions: 
Use current styling

#### Dependencies
GDX to advise on legislative requirements

#### DOD
- [x] GDX to advise on legislative requirements
- [x] Checked for Legislative guidelines in accordance with FOIPPA
- [x] Letter templates
- [x] Email templates

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews Have either of you had a chance to reach out to GDX to see if there are any legislative guidelines that the letters have to adhere to? 
I am working on the report out today, and I have the last user session. 
So I'm hoping to start these Monday, if we have that information from them.

**Comment by m-prodan** [comment]
@JHarrietha-AOT In terms of legislative requirements, our current templates include what is required from the legislation's perspective for a letter to be valid.

Our letters need to have our Ministry/divisional branding, and our current templates also reflect this. GDX does require us to follow accessibility guidelines for web content though, and I suppose this could be translated into our templates as well to reflect that. I am unsure if our current templates are setup in that way. 

Accessibility guidelines are here: https://developer.gov.bc.ca/Accessibility

**Comment by lmullane** [comment]
@JHarrietha-AOT, GCPE has some guidelines around the use of the Provincial logo. I'll see if I can dig up the direction on that.

**Comment by lmullane** [comment]
@JHarrietha-AOT, here's the guidance on use of the logo: https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/design-guidelines

This may be captured already in the [Design System repo](https://github.com/bcgov/design-system).

**Comment by JHarrietha-AOT** [comment]
@arielleandrews @m-prodan @lmullane 

Thanks for linking these resources so quickly. I will get started on the templates on Monday!

**Comment by mpilchar** [comment]
Questions to answer: 
- Does Section 5 text need to be included in full, summarized, or linked?
- Can we minimize phone #s in contact section to a single number?

**Comment by JHarrietha-AOT** [comment]
Review Process Removed from issue as it will take some back and forth and waiting.

Can be seen in task #167

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews 

Here is the first draft of the re-design of the redirect letter/email. Core difference is letter has header and footer with contact info, email has signature with contact info. And I have added titles for content to be easier to find. I designed these as examples, so anything in orange is what would be auto-populated based off of what is selected.

Email: https://teams.microsoft.com/l/file/ECA6AA0D-76BF-4B29-8A8C-3879655BC8DB?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FTemplates%2FNEW%20Email%20Templates%2FProposed%20-%20Redirect%20Email.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

Letter: https://teams.microsoft.com/l/file/5AE076A7-98B1-4627-9D70-11646732D606?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FTemplates%2FNEW%20Letter%20Examples%2FProposed%20-%20Redirect%20Letter.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

Here is the start of the excel with the different options and the text for each, included what was originally provided and what I have changes: https://teams.microsoft.com/l/file/327608AA-011C-44C9-AF85-B325C3325F31?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=xlsx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521%2FShared%20Documents%2FGeneral%2FUser%20Research%2FTemplates%2FTemplates.xlsx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F03521&serviceName=teams&threadId=19:1c5b921afa4b45d49bad9acfaf3d5a6e@thread.tacv2&groupId=b287cae4-97c4-48f4-a76a-84cf0dbb84be

**Comment by arielleandrews** [comment]
Nice work @JHarrietha-AOT! I have added some comments and suggested edits in Teams. I like how streamlined they are now. @m-prodan would you like to review before moving this to closed?

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Thanks for all the great feedback I made changes based off of your suggestions.

@m-prodan Would you like to review before we move over the the review task ticket? Otherwise either of you can close the ticket when it feels ready to do so, all links are also in the review ticket
