### ISSUE TITLE
Events that Trigger PUSH notifications

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#906]
* As a user
* I want certain events to trigger a push notification
* so that I can be notified close to real time of specific events

**Assumptions & Scope**	
What are the assumptions for this story?
This story covers the scenarios where push notifications will be triggered by certain events

What is IN scope?
Notifications related to the comment log, that will be considered PUSH notifications

What is NOT in scope?
Pull notifications covered in (#855)

**Acceptance Criteria**	

**Scenario 1: New comments by User**
* GIVEN a FOI Request is in any state
* WHEN a comment has been created by any other user on that request
* THEN all users assigned to the request, except for the user that created the comment, will receive a PUSH notification that includes: FOI Request number, and a message saying "New Comment: XXXX" where XXX will be the first 90 characters of the comment added, with three dots at the end if the comment continues past the character limit

**Scenario 2: Replies to Comments**
* GIVEN a FOI Request has a parent comment added by a user
* WHEN a reply to that comment has been entered
* THEN the author of the parent comment will receive a PUSH notification that includes: FOI Request number, and a message saying "New Reply to Your comment: XXXX" where XXX will be the first 90 characters of the reply added, with three dots if the reply continues past the character limit

**Scenario 3: Comments - Replies to Replies**
* GIVEN a FOI Request has a parent comment with replies by one or more user
* WHEN subsequent replies are added
* THEN the author of the parent comment, and any other user that has authored a reply, EXCEPT for the user that authored the reply, will receive a PUSH notification that includes: FOI Request number, and a message saying "New Reply to Your comment: XXXX" where XXX will be the first 90 characters of the reply added, with three dots at the end of the text if the reply continues past the character limit

**Scenario 4: Comments - Tagged in a Comment**
* GIVEN a FOI Request is in any state
* WHEN a user has been tagged in a comment added to a request
* THEN the user that has been tagged will receive a PUSH notification that includes: FOI Request number, and a message saying "You've been tagged in a comment: XXXX where XXX will be the first 90 characters of the comment the user is tagged in, with three dots at the end of the text if the comment continues past the character limit

**Scenario 5: New comments by User in Watcher Log*
* GIVEN a FOI Request is in any state
* WHEN a comment has been created by any other user on that request
* THEN all users watching the request, except for the user that created the comment, will receive a PUSH notification in their 'Watching Notifications' log that includes: FOI Request number, and a message saying "New Comment: XXXX" where XXX will be the first 90 characters of the comment added, with three dots at the end if the comment continues past the character limit

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
User story created, split off from #855 - this covers specific events from the comment log that will generate push notifications

**Comment by sumathi-thirumani-aot** [comment]
@mpilchar @m-prodan Please note for scenario#3 is implemented as given and have not included tagged

**Comment by sumathi-thirumani-aot** [comment]
@mpilchar @m-prodan Observation; this does not cover edit or delete notifications. Confirmation required.

**Comment by sumathi-thirumani-aot** [comment]
@mpilchar @m-prodan Where does the comments to be displayed in UI; because any user of team can comment and tagged users need not be watcher or  assignee.

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews Just chatted with @sumathi-thirumani-aot this is not a blocker so we can discuss at Stand-up on Monday. What we are trying to resolve is the fact that a user who is not the "Assigned" or "Watched" could be tagged in a request comments. For our notifications we currently have them broken into two tabs "Assigned & Watching" but a user who is neither of those could be tagged so where should we be displaying those notifications. 

I think this does flag an issue that could continue to arise as our platform grows. Should be remove the tabs in notifications and have it display all with some filtering options for requests assigned and requests watching? Should we add an all tab and have 3 sections? Just some quick ideas I have thought of, but would like to hear what you both think before we change the design or if you have an idea of where users would like these types of notifications to sit. We will discuss Monday. 

cc: @mpilchar @lmullane for awareness

**Comment by arielleandrews** [comment]
@sumathi-thirumani-aot and @divyav-aot I have added scenario 5 to auto delete the notification for deleted comments per our discussion this morning. Please let me know if you think anything is missing or if this needs to be separated out for comments vs replies. Thanks!

**Comment by arielleandrews** [comment]
Removed Scenario 5 - this has been moved to its own ticket #1514

**Comment by aparna-aot** [comment]
@JHarrietha-AOT There are some design updates with comment notifications. Please test that as well. Thanks!

**Comment by JHarrietha-AOT** [comment]
@lmullane @m-prodan @arielleandrews This ticket has passed UX assurances. 

One change I would recommend is instead of scenario 1 being limited at 90 characters I think it should be two lines to the whole word. This will lend to better responsiveness and remove awkward single letters on the third line like you can see in screenshots below.

Wanted to flag one thing I noticed while I was reviewing.

Bug - User Name of who made change/authored comment on request shows up on notifications when logged in as a Ministry User but not as an IAO User (See Screenshot below)

Signed in as Ministry User: ![Screen Shot 2022-02-22 at 1.52.22 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/d7c10840-33b0-49cc-b6e7-3ae1318e8ac2)

Signed in as IAO User: ![Screen Shot 2022-02-22 at 1.56.34 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/a4fd48eb-beec-45b8-a65f-6d643becbae7)

cc: @aparna-aot @sumathi-thirumani-aot

**Comment by aparna-aot** [comment]
Hey @JHarrietha-AOT That's a good catch, although the issue is different. Issue with the author name exists when u open the notifications in the dashboard view and that is happening with the latest dashboard updates. Will fix and push to QA once dev is unlocked. Thanks!

**Comment by JHarrietha-AOT** [comment]
@aparna-aot Thanks for the quick response, that sounds great!

**Comment by lmullane** [comment]
The 4 scenarios worked as expected. Super fast and easy to use.

I added a 5th scenario for notifications for watchers (aka these notifications show in the 'Watching Notifications' log. 

One bug - if a watcher replies to an a comment by an assigned user, the reply shows up in the 'Watching Notifications' log for the assigned user. Minor but should appear in the My Notifications log for an assignee.

**Comment by sumathi-thirumani-aot** [comment]
@lmullane Thank you. we will have this addressed as part of delete notifications in current sprint.

**Comment by aparna-aot** [comment]
@JHarrietha-AOT Created #1569 for the bug regarding author name as it's not part of push notifications alone and is in QA. Please view the ticket.

**Comment by arielleandrews** [comment]
@aparna-aot This fix is working. One minor glitch is that the username takes a second longer to load than the rest of the notification - so it appears like the screenshot above for a second or two and then the username of the author populates. This occurs for both IAO and Ministry users. Thoughts on next steps for this bug ticket? cc @sumathi-thirumani-aot
