### ISSUE TITLE
Attachment Log - Download Multiple Attachments

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#909]
* As an IAO analyst or ministry coordinator
* I want to download multiple attachments from the attachment log 
* so that I can export all the files I need in one action 

**Assumptions & Scope**	
What are the assumptions for this story?

This story will cover the use case for someone to be able to export all attachments, in the event all files attached to a request need to be accessed.

Only IAO can download all files from the log.
Ministry Coordinators can download all files they are able to view or download. 

Downloading all files should produce a .zip file that contains all of the attachments

What is IN scope?
Downloading of all attachments in the attachment log

What is NOT in scope?
Custom selecting multiple files (later iteration planned?)

Blocking ministry from downloading any attachments

**Acceptance Criteria**	

**Scenario 1: Export all attachments  - IAOusers**
* GIVEN an IAO analyst is on the attachment log
* WHEN they click on the "Export All Attachments" button
* THEN the application will automatically trigger a download of all attachments as a .zip file, onto the users local machine

**Scenario 2: Export all attachments - Ministry users**
* GIVEN a Ministry analyst is on the attachment log
* AND there are attachments the ministry user cannot view
* WHEN a Ministry user clickes on the "Export all" button on the attachment log
* THEN only the attachments the Ministry user can view will be downloaded to their computer

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
Updated this story with the scenarios that make sense to me, but I believe designs may be needed for a simple button. I know we talked about this one recently, @JHarrietha-AOT and @arielleandrews - I know we were thinking of a potential to have users select all/some (like a table kind of format).... but maybe for an MVP it just starts as a simple export of all into a zip file? 

I'll update this one and remove the incomplete AC tag. Flagging for @lmullane @mpilchar to add to refinment for Wed

**Comment by lmullane** [comment]
Looks good, @m-prodan

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews Here is the updated designs including the button and checkboxes let me know what you both think. https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Comment by m-prodan** [comment]
Thanks @JHarrietha-AOT - I think having a box to "select all" would be helpful in this design. I wrote the AC around not having checkboxes, I can update the AC accordingly but I wonder if we just start with exporting doing everything, and building out checkboxes later? I don't know how much more effort it is to have customized downloads via checkboxes vs a simple export all.

**Comment by JHarrietha-AOT** [comment]
@m-prodan Thats right! I have updated the design here thanks for reviewing it. Let me know if we need any other changes https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727

**Comment by lmullane** [comment]
Looks good. Agreed a button is sufficient as there is a download option in the ellipsis.

**Comment by m-prodan** [comment]
@m-prodan update AC re: roles MC vs IAO

**Comment by m-prodan** [comment]
AC Updated based on refinement discussion. Let me know if there are any issues @abin-aot @arielleandrews @JHarrietha-AOT @mpilchar @lmullane 

On an unrelated note... tagging yourself does NOT generate you an email :)

**Comment by lmullane** [comment]
Thanks, @m-prodan.

That tagging behaviour makes sense,

In terms of scope, permissions to view and download attachments are not part of this story, correct?

**Comment by m-prodan** [comment]
Correct - we'll need a separate user story for general attachment uploads, and personal request attachments AC specifically exclude the Ministry from being able to download directly

**Comment by mpilchar** [comment]
Clarification at standup: No checkboxes needed for MVP

**Comment by lmullane** [comment]
@m-prodan, can I confirm that scenario 2 is for an authorization attachment submitted as part of the a request through the request webform?

**Comment by m-prodan** [comment]
Yes @lmullane - you will need to submit a personal request through the webform and upload some documents when you do so. When you open it in our system through the raw request route (login as intake, search by unopened, and open request that way) - it should pull those attachments over and the Ministry should not be able to download them.

**Comment by lmullane** [comment]
AC passes as expected. Nice work, @nkan-aot
