### ISSUE TITLE
Reporting - Tool Evaluation

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/foi-flow#922]
Title of ticket: Tool Evaluation

#### Description
This ticket is to analyze and document the features and advantages of available reporting tools. 

#### Dependencies
No

#### DOD
- [x] Setup a test data warehouse to be used to build the analytics 
- [x] Setup the tool on local machine
- [x] Check the connectivity to PostgreSQL DB
- [x] Check the latency while running direct reports
- [x] Check if the tool allow caching of data
- [ ] Check if there is an option to triggers emails based on threshold
- [ ] Check if there are custom styling options available
- [x] Check the available visualizations
- [x] Check the options to apply row level security

**Comment by mpilchar** [comment]
@VineetBala-AOT Is this likely to be complete within this sprint? Do you want my help creating a new task with any remaining tasks for next sprint?

**Comment by VineetBala-AOT** [comment]
Hi @mpilchar , there are two points still need to be tested. We can close this ticket and create a new task with those two for next sprint.
