### ISSUE TITLE
DataModel update - versioning, WF instanceID updates, Python DB Entity Updates

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#93]
Title of ticket: 

#### Description
Update the existing Datamodel to incorporate request data versioning, capture WorkFlow instances etc

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Design data modelling for FOI requests
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by abin-aot** [comment]
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/4c21fed1-21e7-42b8-8169-8a1be694f7f5)

**Comment by divyav-aot** [comment]
Analysis of General and Personal Requests.
[Data captured from Request form and sample data](https://app.zenhub.com/files/358004325/f82969de-cec5-4c48-8598-8578cfa7902a/download)

**Comment by abin-aot** [comment]
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/0af6da13-cfed-4270-b4e7-6ecc055db0e1)

**Comment by sumathi-thirumani-aot** [comment]
Discussion Points:
	1. Table: FOIRequests  **-> Changes applied.**
      - As the table already has word "Requests"; it need not be repeated in column level. Rename request description to description. 
	- SearchDateFrom and SearchDateTo can be renamed to fromDate and toDate or recordFromDate and recordToDate
	- Include audit columns createdDate and createdBy
	- Introduce lookup table to maintain request types (GENERAL & PERSONAL) and associate the ID as "RequestTypeId" and not "RequestType".
	- Remove column "Start Date" - Refer step # 8
	2. Table: FOIRequestorType  (Lookup) - Holds good. 
	3. Table: Applicant, ApplicantRequestRecords, ApplicantContactInformation
	 - Please merge the data from ApplicantRequestRecords & ApplicantContactInformation to Applicant. [Kindly Note: It is not essential to have table for every flow in UI - These can be logically combined and simplified] -> **Refer section "Details of Discussion"** 
	NOTE: This covers information of requestor & records of person.
	4. Table: ContactType  (Lookup)  - Holds good.
	5. Table: ContactInformation - Holds good
	6. Table: Ministries  (Lookup)  -**> Changes applied.**
	This needs to be expanded to capture agencies.
	7. Table: FOIRequestMinistries  -**> Changes applied.**
	Include the column "Start Date" considering the extensive scope
	8. Include the columns "fromDate" and toDate".  **-> Changes applied.**
	9. Table: FOIRequestNotes - Holds Good
	10. Table: FOIPersonalAttributes - Holds Good
	11. Table: PersonalInformationAttributes (Lookup) - Holds Good
	12. Table: DocumentType (Lookup) - Holds Good
	13. Table: FOIRequestDocuments -> Assuming Temporary (To live till DM comes in; and only soft link of document is used instead of attachment)
	 - This may need an association with Contact Information.
	
Note:
	- All lookup tables should have description.
Questions:
Do we need to capture "join request" identifier in FOI request 


**Details of Discussion:**
- Point#3 
a. The join table "ApplicantRequestRecords" is in place considering use case of "Service ID integration with profile management". b.  Discussion around "ApplicantContactInformation" is deferred.
- Entity to capture raw request.

**Comment by acoard-aot** [comment]
Done, marking as closed
