### ISSUE TITLE
Absence of Bold in Comments when using Mac computer

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#930]
#### DOD
- [x] Updated Rich Text Editor that has Rich Text Editing capabilities like BOLD, Italics, Underline, Listing - bulleted 
- [x]  Need to work on Mac machine 
- [ ] 
- [ ] 
- [ ]

**Comment by mpilchar** [comment]
@abin-aot Please complete DOD and estimate - thanks!

**Comment by JHarrietha-AOT** [comment]
@abin-aot Closing issues as it has been fixed. Thanks for the great work Abin
