### ISSUE TITLE
Develop Training Plan for Pilot Groups

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#934]
Title of ticket: Develop Training Plan for Pilot Groups

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Draft Test Scenarios - Intake Team - DEFER TO LATER
- [x] Draft Test Scenarios - Flex Team
- [x] Draft Test Scenarios - Ministry Coordinator
- [x] Draft Test Scenarios - Processing Team
- [x] Prepare Presentation for Pilot Team Meetings

**Comment by mpilchar** [comment]
- EDUC preferred timing for training is  end of Jan/early Feb.
- AXIS 10.7 rollout is planned for Feb 14. It is mainly a backend upgrade and will not require huge amounts of training. There will likely be 2-3 spot-training sessions that week, led by Jaimie and Andrew.

**Comment by m-prodan** [comment]
Need to update the testing scenarios for intake once feedback from teams have been received.
