### ISSUE TITLE
Automatic assignment to Flex Team 

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#935]
* As an Intake user
* I want open General requests to be automatically assigned to the Flex team 
* so that I don't have to assign requests individually

**Assumptions & Scope**	
Only General requests will be automatically assigned to the Flex Team Queue
Only Personal requests will be automatcially assigned to the Processing Team 
Assignment occurs when moving request from Intake in Progress state to Open state
If multiple ministries are selected, all resulting individual requests will be assigned to Flex Team

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Select Open state in state change dropdown**
* GIVEN I am an IAO user on a general request in the Intake in Progress state
* WHEN I select Open from the state change dropdown 
* THEN the state change modal will appear 
* AND the modal will display the "IAO Assigned To" field as "Flex Team Queue"

**Scenario 2: Cancel Open state change**
* GIVEN I have selected Open from the state change dropdown
* WHEN I select Cancel on the state change modal 
* THEN the modal will close
* AND the IAO assigned user will remain as the same user previously assigned 

**Scenario 3: Save Open state change*
* GIVEN I have selected General Request that is Open from the state change dropdown
* WHEN I select Save on the state change modal
* THEN the modal will close
* AND the request will now be assigned to the Flex Team Queue
* AND the previous user will no longer be assigned
* AND the request will no longer display in the Intake team queue

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
@m-prodan @lmullane @mpilchar @JHarrietha-AOT Please review and make any changes you see fit. For refinement at Sprint Planning Nov 24

**Comment by lmullane** [comment]
Looks good to me, @arielleandrews

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Looks good, I just added General Request in the Scenarios. I know its in the assumptions just always good to have in the specific scenarios as well

**Comment by m-prodan** [comment]
Team structure and Ministries serviced found at this link: https://bcgov.sharepoint.com/:x:/r/teams/03521/Shared%20Documents/General/IAO%20Processing%20Teams.xlsx?d=w74ab3990f0574ab49121c6d455cb9c60&csf=1&web=1

**Comment by arielleandrews** [comment]
QA completed, all scenarios passed in Chrome, Edge and Firefox. Personal requests are assigned to generic Processing Team, will need to be assigned to specific teams in future user story.
