### ISSUE TITLE
UX Research Plan - Reporting

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#937]
Title of ticket: UX Research Plan - Reporting

#### Description
Planning Phase for Multiple Rounds of Research in IAO and Ministry Users Currently Practice for Reporting

#### Dependencies

- [x] Receiving folder of ALL currently reports (To who and Why)

#### DOD
- [x] Initial Discovery into Currently Reporting Practices 
- [x] Discover List of Personas who Receive Reports
- [x] How will we discover each Persona ideal report
- [x] Draft Research Plan
- [x] Share Draft Research Plan with SME for Feedback
- [ ] Share Draft Research Plan with PO for Feedback

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews 

Wanted to share out the link to this for feedback when you have time. The research for this will include the analyzing of the report samples we are provided by personas and the sessions afterwards to confirm we have the right defaults for each personas needs for reporting.

https://bcgov.sharepoint.com/:w:/t/03521/EWtHd6FQRyBNqFsJPXm9HtIBQMS3SRsykMVAF1Yr2mc9Pg?e=iPWtJJ

As a question, when do you think it is realistic for us to ask for these reports from IAO Managers and the Governance Committee? Assuming we send them emails today. Ideally I am thinking Wednesday, which would give me Thursday and Friday to review them and prep and we could book in short sessions to review the proposed defaults next week. Let me know if you think we need to give them a week, which is fine just means we might not be able to fit in sessions before I leave for the holidays.

**Comment by m-prodan** [comment]
I'm going to manager's meeting today, and can ask them to have me copies of their reports early this week, by Wednesday if possible. They should all have custom reports handy that they can push out.

**Comment by arielleandrews** [comment]
I'll send a note around to the Team Leads today as well and see if I can get a few responses back from that group

**Comment by JHarrietha-AOT** [comment]
That's what I was thinking, this shouldn't be a time consuming task for everyone. Would you be able to email the governance committee today as well just to get some from the Ministries. Ideally were looking for minimum 4 from each user group. The more the better

**Comment by m-prodan** [comment]
Yep no problem - I'll send a note to the working group as many of them immediately supervise Ministry coordinators

**Comment by JHarrietha-AOT** [comment]
Plan has been reviewed and collecting of sample reports has begun
