### ISSUE TITLE
Create API for FOI requests 

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#94]
Title of ticket: 

#### Description
Python API

###Scope
Capturing data (i.e. integration with FOI request service) is a separate ticket

Logic includes both personal and general requests, which will impact data modelling.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Unit test cases
- [ ] Exception handling
- [ ] Functional Logic
- [ ] Code standards
- [ ] Code linting and code coverage
- [ ] Swagger API Spec
- [ ] Deploy to TEST

**Comment by abin-aot** [comment]
1. Functional Logic for capturing FOI Requests - Done
2. Data Modelling design related is over
3. JSON Schema validation is done
4. Exception Handling Done , covered by Boiler Plate
5. Swagger API Done, as part of Boiler plate


Note :  Unit test case Task has been spitted and will be taken over by @sumathi-thirumani-aot . 
Deploying to DEV, TEST - @acoard-aot  is working on it
