### ISSUE TITLE
UX Discovery Sessions - Andrew & Jamie

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#940]
Title of ticket: UX Discovery Sessions - Andrew & Jamie

#### Description
Two sessions, with Andrew & Jamie to watch current process for creating reports and get feedback on what they think is required info to share vs not 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Book Session with Andrew & Jamie - @arielleandrews
- [x] Session with Andrew
- [x] Create User Flows based off of Andrew's Process and current Pain Points
- [x] Session with Jamie
- [x] Create User Flow based on Jamie's Process and current Pain Points

**Comment by JHarrietha-AOT** [comment]
@arielleandrews Added booking in the two sessions with Andrew and Jamie into the DOD of this ticket. In thinking that Dec 1st is also the big IAO meeting - would it be a bad idea to take more hours on the day to have Andrew walk me through things? Not sure just wanted to ask here in knowing that they are both very busy

**Comment by arielleandrews** [comment]
Sessions booked as follows:
1. Andrew - Wednesday December 1st 1PM-3PM PST
2. Jamie - Friday December 3rd 11AM-12PM PST

**Comment by JHarrietha-AOT** [comment]
Session 1 Recording

https://bcgov.sharepoint.com/:v:/r/teams/03521/Shared%20Documents/General/User%20Research/1%20-%20Sprint%2014%20-%20Recordings/Session%201%20-%20Andrew%20Bonneau%20-%20Process%20Walk-though%20Reporting.mp4?csf=1&web=1&e=vT94sJ

**Comment by JHarrietha-AOT** [comment]
Session 2 Recording

https://bcgov.sharepoint.com/:v:/r/teams/03521/Shared%20Documents/General/User%20Research/1%20-%20Sprint%2014%20-%20Recordings/Session%202%20-%20Jamie%20Onciul%20-%20Pain%20Points%20%26%20Feedback.mp4?csf=1&web=1&e=id0TsD

**Comment by JHarrietha-AOT** [comment]
All sessions are complete
