### ISSUE TITLE
Display Number of Extensions in Left Nav Panel

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#946]
* As a user
* I want the number of extensions on a file to display in the left navigation panel 
* so that I know at a glance if I need to prioritize a request 

**Assumptions & Scope**	
What are the assumptions for this story?
* Extensions counter will display in the left nav panel from Open state onward
* Will show as zero until an extension has been taken
* Extensions counter will display for all users
* Approved extensions will count and display as just the number [i.e. Extensions     1]
* Pending extensions will display in brackets after the number of approved extensions [i.e. Extensions     2 (1) ] until they are approved, at which point they will be counted as an Approved extension
* Denied extensions will not be counted and will not be displayed
* Approved Public Body and OIPC extensions are both counted

What is IN scope?
* Displaying the count of pending and approved extensions

What is NOT in scope?
* Creating, approving or denying extensions 

**Acceptance Criteria**	

**Scenario 1: Extension counter displays zero**
* GIVEN a request is in Intake in Progress state
* WHEN the state is changed to Open 
* THEN the Extensions counter displays in the left navigation panel above the Days Remaining counter
* AND the Extensions counter will display 0  

**Scenario 2: Public Body Extension is saved and approved**
* GIVEN an IAO user has created a Public Body extension 
* WHEN the IAO user clicks 'Save and Approve' on the extension modal
* THEN the extension counter in the left navigation panel will update to display the number of extensions as 1

**Scenario 3: OIPC Extension is saved as pending**
* GIVEN the IAO user has created an OIPC extension
* WHEN the IAO user clicks 'Save as Pending' on the extension modal
* THEN the extension counter in the left navigation panel will update to display the pending extension in brackets after the number of approved extensions e.g. Extensions 1(1)

**Scenario 4: OIPC Extension is moved from pending to approved**
* GIVEN the IAO user has created and saved as pending an OIPC extension
* WHEN the IAO user clicks 'Approved' and 'Save Change' on the extension modal 
* THEN the extension counter in the left navigation panel will increase by 1 and will no longer display in brackets e.g. Extensions 2

**Scenario 5: OIPC Extension is moved from pending to denied**
* GIVEN that IAO user created and saved as pending an OIPC extension
* WHEN the IAO user clicks 'Denied' and 'Save Change' on the extension modal
* THEN the extension counter in the left navigation panel will not increase and will no longer display in brackets e.g. Extensions 1 

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
@JHarrietha-AOT @m-prodan ticket drafted per our discussion earlier, let me know if you think there's anything missing

**Comment by JHarrietha-AOT** [comment]
@divyav-aot @jadmsaadaot This technically works but doesn't meet the expected UX.

UX Assurance Changes:
- [ ] All Caps
- [ ] Decrease spacing between lines
- [ ] Numbers should be aligned to right
- [ ] Less space between numbers in left nav and bottom of nav bar

![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/c37b01eb-eb75-480f-ac1b-f3525295d995)

**Comment by jadmsaadaot** [comment]
Hello Jackie,

I understand that the end objective for that section is to look as per the
UX assurance changes. But could we keep this effort separate in #945. #946
would serve to display it and #945 would serve to change the layout there
for all the numbers displayed.

This is because #945 may need some dedicated effort as I found that it is
not as easy as it seems when I picked it up.

**Comment by JHarrietha-AOT** [comment]
@jadmsaadaot That works for me, thanks for reminding me of those tickets. Happy to have it in those separate tickets so the effort is calculated accordingly. Just wanted to make sure it was captured somewhere, I will move these onto Ready for QA

**Comment by arielleandrews** [comment]
@divyav-aot and @jadmsaadaot - this works as expected for IAO users, but does not display for Ministry users. It is listed in the assumptions that the extensions counter should display for all users (same as days remaining). Would you like me to move this back to In Progress?

**Comment by jadmsaadaot** [comment]
@arielleandrews , thanks for catching that. Yes, please move it back to in progress and I will look into it

**Comment by abin-aot** [comment]
@arielleandrews  : Please cross check bug #1547 and close it out, if fixed. thanks

**Comment by lmullane** [comment]
@jadmsaadaot, please check that the 'Days Remaining' in the left panel is showing.

**Comment by JHarrietha-AOT** [comment]
Ready for QA

**Comment by arielleandrews** [comment]
QA completed, this is working as expected and the days remaining counter is fixed as well. Nice work @jadmsaadaot!
