### ISSUE TITLE
Display Divisional Tracking for IAO Users

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#955]
* As an IAO user
* I want to see what divisions have been canvassed for records and what stage they are at
* so that I can see the progress of the file

**Assumptions & Scope**	
What are the assumptions for this story?
* All IAO users will be able to see the divisional tracking information
* Divisional tracking information will be read only
* Divisional tracking will be available from Call for Records state onward

What is IN scope?
* Displaying the divisional tracking information on the Request Details view for IAO users

What is NOT in scope?
* Entering and updating the divisional tracking information - this has been completed 

**Acceptance Criteria**	

**Scenario 1: Ministry Coordinator adds divisional tracking information**
* GIVEN a Ministry Coordinator is on the Request Details view 
* WHEN a Division and Division Stage has been selected
* AND the Ministry Coordinator clicks Save 
* THEN the Divisional Tracking information will populate and display on the IAO Request Details view 
* AND this information will not be editable by IAO analysts

**Scenario 2: Ministry Coordinator updates divisional tracking information**
* GIVEN a Ministry Coordinator is on the Request Details view 
* WHEN a Division or Division Stage has been changed or deleted
* AND the Ministry Coordinator clicks Save 
* THEN the Divisional Tracking information will update in the display on the IAO Request Details view 
* AND this information will not be editable by IAO analysts

**Scenario 3: xxxxxx**
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment]
@JHarrietha-AOT Let me know if this covers the use case for the Divisional Tracking field

**Comment by lmullane** [comment]
@JHarrietha-AOT, please advise if you agree with the AC. Particularly that the division stages  section only appears on the IAO request view when the ministry coordinator has made a change,

**Comment by JHarrietha-AOT** [comment]
@lmullane @arielleandrews @m-prodan. This looks good to me.

**Comment by lmullane** [comment]
Thanks, @JHarrietha-AOT

**Comment by aparna-aot** [comment]
Can somebody add the message to be displayed when there are no divisions present ? @arielleandrews @lmullane @m-prodan

**Comment by m-prodan** [comment]
Is it possible to have it so that nothing appears when no divisions are present? If there were no designs for the view when nothing is assigned - then maybe we can have it so that the divisional tracking only appears when there is a division assigned?

**Comment by m-prodan** [comment]
Nice work @aparna-aot - all scenarios passed across multiple browsers/Ministries and users
