### ISSUE TITLE
Potential bugs - flex queue

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#957]
**Describe the bug in current situation**

Recently it came to our attention that the flex queue does not look as expected. 
1) new incoming requests are not coming in at top and are not highlighted in blue
2) ID# should be at far left column - isn't currently
3) Default filter status should be set to most recently received -isn't currently

**Comment by mpilchar** [comment]
cc: @m-prodan @arielleandrews please proof/add any additions

**Comment by abin-aot** [comment]
related with #1094

**Comment by mpilchar** [comment]
CLosing - dupe with #1094
