### ISSUE TITLE
Delete an Extension

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#968]
* As an FOI analyst
* I want to delete an extension
* so that I have the ability to remedy when errors are made or circumstances have changed

**Assumptions & Scope**	
What are the assumptions for this story?
This story covers the ability to delete extensions.
Any approved extensions that are deleted will roll back the legislated due date clock.
Users will have the ability to delete the most recent extension only. The most recent extension can be in Pending, Approved or Denied status; any status can be deleted. Users will not be able to delete any extensions taken prior to the most recent extension.

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Ellipses Options in Extension**
* GIVEN an IAO user is on the extension log on the review request page
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852
* WHEN they click on the ellipsis on the most recent extension
* THEN they will see the following options: Edit, Delete
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852
* AND the ellipsis will be inactive for any extensions prior to the most recent extension

**Scenario 2: Extension Log - Click Delete**
* GIVEN an IAO user has activated the ellipsis on the most recent extension
* WHEN they click on delete
* THEN a pop up will appear asking the user "Are you sure you want to delete this extension?" with the options to continue and cancel

**Scenario 3: Delete a Pending Extension**
* GIVEN an IAO user has activated the delete button on the ellipsis of a pending 
* WHEN they click on Continue
* THEN the extension will be deleted from the log
* AND the legislated due date will remain the same

**Scenario 4: Delete a Denied Extension**
* GIVEN an IAO user has activated the ellipsis  and clicked delete on a denied extension in the log
* AND there are no pending extensions
* WHEN they click on Continue
* THEN the extension will be removed from the log
* AND the legislated due date will remain the same
* AND if any files were uploaded, they will also be deleted from the attachment log

**Scenario 5: Delete an Approved Extension**
* GIVEN an IAO user has activated the ellipsis and clicked delete on an approved extension in the log
* AND there are no pending extensions
* WHEN they click on Continue
* THEN the extension will be removed from the log
* AND the legislated due date will revert back to the previous legislated due date before the extension was created
* AND if any files were uploaded, they will also be deleted from the attachment log

**Scenario 6: Cancel Back to Log**
* GIVEN an IAO user has activated the delete button on the ellipsis of an extension (any state)
* WHEN they press cancel on the prompt
* THEN the window will close and the user will remain on the review request view

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**
#878 - Extension Log
#881, #882 and this ticket will be handled together

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
I've updated the AC based on @JHarrietha-AOT design. The design didn't seem to let me click into what would happen if I click edit or delete, so I wrote out suggested scenarios.

I think we might need a separate criteria to handle deleting an extension with a file upload (does the file in the attachment log also get deleted?). Also thinking we might want a new system generated comment to accompany this, and may need a separate user story.

Comments welcome @mpilchar @arielleandrews @lmullane

**Comment by m-prodan** [comment]
per refinement - move edit AC's over to 881/882 - edit will be the same experience

**Comment by m-prodan** [comment]
AC Updated based on our discussion at refinement - please let me know if I've captured the understanding of this one - thanks @abin-aot @JHarrietha-AOT @mpilchar @lmullane

**Comment by arielleandrews** [comment]
Removing the below copied scenario. During discussion on Jan 19/22 it was agreed the ellipsis will only be active for the most recent extension, so the user will be unable to select Delete on an approved/denied extension when there is one in Pending.
**Scenario 5: Delete an Extension with a pending extension**
* GIVEN an IAO user has activated the ellipsis of a completed extension on the log
* AND a pending extension is also on the log
* WHEN they click on delete
* THEN an error message will appear, telling the user "You can't delete a completed extension when there is a pending extension"

**Comment by arielleandrews** [comment]
@JHarrietha-AOT @divyav-aot @jadmsaadaot this User Story has been updated based on our discussion today. Please let me know if this captures everything you understood or if anything is missing. Thanks!

**Comment by arielleandrews** [comment]
QA is completed, all scenarios passed in Chrome, Edge and Firefox. @jadmsaadaot I see #1390 is still open, can I move this use story to closed?
